### ISSUE TITLE
BACKTRACE 64358e rct_peep::UpdateRideLeaveVehicle

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8165] opened 2018-10-27 05:26 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/64358e45e5e1c46026042b933daa9d1f6ac8abe2cec8a607e72636043721aaa8?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Oct 27 2018 05:25:13)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>rct_peep::UpdateRideLeaveVehicle -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 19:45
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/7700

**Closed by janisozaur** 2019-02-02 19:45 UTC
Labels: backtrace.io, crash
