### ISSUE TITLE
open rct is not  zooming  all the way in

### ISSUE THREAD

**Issue by goose0324** [OpenRCT2/OpenRCT2#20978] opened 2023-11-16 02:41 UTC
### Operating System

windows 10

### OpenRCT2 build

OpenRCT2, v0.4.6 (b40b5da) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

zoom in is not working on open rct\

 also 8 cars trainer keeps  saying no process

### Steps to reproduce

none

**Comment by ocalhoun6** [comment] 2023-11-16 10:30
Your maximum zoom level might depend on what type of rendering you're using -- software, software/hardware, or OpenGL. If you changed this recently, that might be why the zoom is no longer working.

-----

And as for 8cars ... what are you using a trainer with OpenRCT2 for? If there's something it can do that OpenRCT2 still can't do without it, we should probably think about just adding that feature, or at least exposing it to plugins instead.

**Comment by goose0324** [comment] 2023-11-16 12:35
I'm not sure which one I'm using cuz I'm new to open RCT. I'm used to using
the disc but the desk is not working correctly and 8 cars trainer doesn't
work with it for some reason anymore.

**Comment by Gymnasiast** [comment] 2023-11-19 12:27
You’ll have to be much more specific. Adding screenshots might help.

OpenRCT2 supports every zoom level that RCT2 supports, and adds two additional modes when in OpenGL mode. You might be running OpenRCT2 at a higher resolution than you did with RCT2, which might make it look as if everything is zoomed out further. If you don’t like this, you can use the scaling feature, or run at a lower resolution.

8 cars per trainer is written for RCT2, not OpenRCT2, so there is no way it _could_ even work. But all its functions have been built into OpenRCT2 anyway, so there is no need to.

**Comment by goose0324** [comment] 2023-11-19 19:40
music on rides is not working

**Comment by ZehMatt** [comment] 2023-11-21 14:41
I don't think that there is anything wrong with the zoom levels, try using OpenGL renderer in the options menu for closer zoom levels or use the scaling option, as for trainers, they do not work for OpenRCT2, if there is a specific function the trainer offers that OpenRCT2 is missing feel free to create a feature request.

> music on rides is not working

We track one issue at a time, if you feel like there is something wrong with ride music please create a new issue.

So not a bug, closing this.

**Closed by ZehMatt** 2023-11-21 14:41 UTC
Labels: bug
