### ISSUE TITLE
Typos in ride descriptions

### ISSUE THREAD

**Issue by Fisherpon** [OpenRCT2/OpenRCT2#5345] opened 2017-04-06 22:53 UTC
**OS: Windows 10**
**Version: 2.01.028**
**Commit/Build: e9c4365**
 
The description of Splash Boats when you go to choose it from the Build New Ride/Attraction menu has a typo in it:
"Large capacity boats travel along a wide water channel, propelled up slopes by a **conveyer** belt, accelerating down steep slopes to soak the riders with a **gaint** splash"

I'm not entirely sure if the first one (conveyer) is a typo, as google seems to think it's a rare spelling of conveyor, but the second one definitely is.

There's another typo in the description of Top Spin:
"Passengers ride in a gondola suspended by large rotating arms, rotating forwards and backwards head-over-**heals**"

- [~] Reproducible in RCT2 (vanilla)? (Unsure, cannot run RCT2 vanilla on my PC)
- [~] Multiplayer? (Haven't checked, but likely)

**Steps to reproduce:**
1. Start a new scenario
2. Unlock Splash Boats and Top Spin
3. Open Build New Ride/Attraction menu
4. Go to Splash Boats and Top Spin
5. Hover mouse over them
6. Observe typos

**Screenshots / Video:**
![](https://i.gyazo.com/ff23827308267e7a09c6d4f65e533621.png)
![](https://i.gyazo.com/3eda96cfbad8a38be09b2f2227083ede.png)

**Comment by crorabaugh2015** [comment] 2017-04-06 23:48
This is not reproducible in vanilla RCT2.

**Comment by Gymnasiast** [comment] 2017-04-07 06:15
@crorabaugh2015 It's very unlikely this is not reproducible in vanilla. There either is an error in the .DAT files or there isn't one.

Anyway, I'll fix this error.

**Comment by Gymnasiast** [comment] 2017-04-07 06:37
Hm, this is odd. I cannot reproduce the faulty Splash Boats description. Could you send me your SPBOAT.DAT file? Also, have you set OpenRCT2 to US English or UK English?

**Comment by Fisherpon** [comment] 2017-04-07 06:38
It's set to US english, and I haven't the foggiest on how to get the SPBOAT.DAT file. I'll poke around and see if I can find it though.

**Comment by Gymnasiast** [comment] 2017-04-07 06:48
You need to go to the directory where RollerCoaster Tycoon 2 is installed, then to ObjData. It should be in that folder.

I pushed a fix for the Top Spin description issue. It should be visible very soon for UK Engllish, and tomorrow for US English.

As for the Splash Boats: it's possible this typo was only in the disk version, and was fixed on the TTP version. The computer I'm currently on has the TTP version, but my desktop has the disk version, so I can check there when I get home tonight.

**Comment by Fisherpon** [comment] 2017-04-07 07:12
Edited my post above to have the file

**Comment by Gymnasiast** [comment] 2017-04-07 08:05
Ah, I found it! You're in select-by-track-type mode, and the US English file contains an error: https://github.com/OpenRCT2/Localisation/blob/master/data/language/en-US.txt#L576 .

It also means that @crorabaugh2015 was right about it not being reproducible in vanilla.

**Comment by Fisherpon** [comment] 2017-04-07 08:28
Ah, whoops. Probably should have mentioned that I was in select-by-track-type. Sorry!
Glad to hear it's all sorted out now, though. I'll keep an eye out for any more typos.

Again, not familiar with how we do things around here. Should I close the thread now, or do we wait until the main game's been updated...?

**Comment by Gymnasiast** [comment] 2017-04-07 09:32
I'll just close the issue now. If the typo doesn't go away for some reason, you can reopen it.

**Closed by Gymnasiast** 2017-04-07 09:32 UTC
Labels: data file bug
