### ISSUE TITLE
BACKTRACE 3c9b88

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8298] opened 2018-11-25 22:32 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/3c9b882c7ccdba22e9a0a5088613677ae696134248f356b265af89a613143f58?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sun Nov 25 2018 22:06:11)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> d0108b3: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>banner_get_closest_ride_index -> SignSetNameAction::Execute -> GameActions::Execute -> Network::ProcessGameCommandQueue -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:12
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8380

**Closed by janisozaur** 2019-02-02 22:12 UTC
Labels: backtrace.io, crash
