### ISSUE TITLE
Demolishing rides refunds twice as much as the ride costs to build

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6420] opened 2017-10-09 14:32 UTC
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 9effe3a

When I build a ride and demolish it again I get back twice the amount of money I spent on the ride.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Screenshots:**

![forest frontiers 2017-10-09 16-30-05](https://user-images.githubusercontent.com/25930360/31343218-4812a884-ad0f-11e7-8b29-e2490c7988a6.png)
![forest frontiers 2017-10-09 16-30-17](https://user-images.githubusercontent.com/25930360/31343216-47cbbec4-ad0f-11e7-8993-ba7f09d3db9b.png)
![forest frontiers 2017-10-09 16-30-21](https://user-images.githubusercontent.com/25930360/31343217-47cbb5b4-ad0f-11e7-8781-bcd33f634a99.png)

**Comment by janisozaur** [comment] 2017-10-09 14:34
Sort-of duplicate of https://github.com/OpenRCT2/OpenRCT2/pull/6405 and https://github.com/OpenRCT2/OpenRCT2/issues/6397, but we need to keep track of it too, so it stays.

**Closed** 2017-10-11 05:58 UTC
Labels: bug
