### ISSUE TITLE
New bug with Mac M1 OpenRCT2 making game unplayable / occasionally unopenable: "OpenRCT2 would like to access files in your Desktop folder." error message pops up repeatably

### ISSUE THREAD

**Issue by barnoopy** [OpenRCT2/OpenRCT2#17569] opened 2022-07-18 23:04 UTC
### Operating System

M1 Macbook Pro, 12.4

### OpenRCT2 build

Open RCT2, 0.4.1

### Describe the issue

I am a longtime OpenRCT2 player on Mac and have stumbled onto a very frustrating new bug that seems to have arisen from a recent update to the computer. I am running on a Macbook Pro M1 on Monterrey 12.4. I am using the most recent stable OpenRCT2 build 0.4.1 and have never had issues like this before.

When I try to open the application, I get this error message repeatably: https://i.imgur.com/QYCfAAM.png

<img width="266" alt="Screen Shot 2022-07-11 at 7 19 32 PM" src="https://user-images.githubusercontent.com/109559463/179631177-c4c558ea-0ae7-49fa-8533-9eaf6cf4d73e.png">

It states: "OpenRCT2 would like to access files in your Desktop folder". When I click 'OK', the error message immediately pops up again. I need to spam the error message repeatably to get the game to open and it's about a 25% chance that the game will open. Usually it will just hang until I force quit it then I start the process of spamming the 'OK' button until the game decides to open. I will have clicked this error message dozens of times before the game opens. Once the game is open, every couple minutes this box will appear again pausing the game. If I click "OK", I am usually free to play again for a couple of minutes. It seems to be appearing whenever most when the game is trying to load a new asset i.e. building a new coaster, the box always pops up if you accidentally move the cursor over the pre-built designs, but it seems sort of random as well.

I thought that this was maybe a weird permissions thing with the new system-wide computer update so I went into my security settings and have granted OpenRCT2 both 'Files and Folders' access and 'Full Disk Access' hoping that the computer would allow the application to run, but no dice still even with full access granted. My computer has been set up to allow apps downloaded from 'Anywhere'. I don't have this issue with any other apps on my Mac -- just OpenRCT2. I think it has something to do with how the application is pulling data from the original RCT2 files stored on my computer. I even moved the RCT2 files into a new location and still get this constantly appearing error.

I'm at my wits end here -- the game is virtually unplayable (if i can even get it open) and I don't know what to do. 

I'm happy to provide any further information or screenrecord what this all looks like in action. Fingers crossed someone can help! thank you

### Steps to reproduce

1. Open OpenRCT2 on M1 Mac with 12.4 Monterey 
2. "'OpenRCT2' would like to access files in your desktop" error message immediately pops up

### Attachments

<img width="266" alt="Screen Shot 2022-07-11 at 7 19 32 PM" src="https://user-images.githubusercontent.com/109559463/179631389-bb72e56b-63ec-47c5-8adf-50caeb83836a.png">

**Comment by James103** [comment] 2022-07-18 23:07
Duplicate of #17162

Try running the following command: `codesign -s - --deep /Applications/OpenRCT2.app` (replace the path with the actual path to the app bundle containing your OpenRCT2 installation)

Source of command: `qbittorrent/qBittorrent#16728`

**Comment by janisozaur** [comment] 2022-07-18 23:09
Please search for existing issues before duplicating them

**Closed by janisozaur** 2022-07-18 23:09 UTC
Labels: bug

**Comment by barnoopy** [comment] 2022-07-18 23:15
this worked!! thank you. sorry for the duplicate. i tried searching "mac" but could not find that linked bug thread

**Comment by ocalhoun6** [comment] 2022-07-18 23:44
> Please search for existing issues before duplicating them

Really shouldn't be so hard on people. Github's search function isn't exactly amazing, people don't always title their issues well, and there are a _lot_ of issues to look through.

**Comment by markand** [comment] 2023-08-20 07:02
I propose to pin this issue? Happened to me as well, fortunately saw the issue by searching :)
