### ISSUE TITLE
BACKTRACE 85fb78

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8415] opened 2018-12-10 19:53 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/85fb7893fddbe4d7d61a072c03d9fc6d3411591b0efa4f2d62344bd8a782ea5e?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Mon Dec 10 2018 19:53:29)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Anh-Ton\\Documents\\OpenRCT2\\07857311-a5cd-4470-a639-69ac811229fd.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Anh-Ton\\Documents\\OpenRCT2\\07857311-a5cd-4470-a639-69ac811229fd.sv6.gz: <em>1</em><br><strong>commit:</strong> 85b443f: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>operator delete -> std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy_deallocate -> Object::~Object -> TerrainEdgeObject::scalar deleting destructor' -> ObjectManager::UnloadObjectsExcept -> ObjectManager::LoadObjects -> TitleSequencePlayer::LoadParkFromStream -> TitleSequencePlayer::ExecuteCommand -> TitleSequencePlayer::Update -> OpenRCT2::TitleScreen::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 19:54
Most likely duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8517

**Closed by janisozaur** 2019-02-02 19:54 UTC
Labels: backtrace.io, crash
