### ISSUE TITLE
Crooked House shows too many operating modes

### ISSUE THREAD

**Issue by ThePsionic** [OpenRCT2/OpenRCT2#3990] opened 2016-07-04 21:41 UTC
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** f3786b3

The Crooked house shows pretty much all operating modes in the game instead of just "Crooked house mode".

- Reproducible in RCT2 (vanilla)? Tested, not the case
- Multiplayer? No

**Steps to reproduce:**
1. Build a Crooked House
2. Under the settings tab of the Crooked House, click the dropdown menu
3. See that there are a lot more than just "Crooked house mode"

**Screenshots / Video:**
![crooked_house](https://cloud.githubusercontent.com/assets/842080/16570167/b946ee74-4240-11e6-8f83-9e178b22489b.png)

**Save game:**
[Crazy Castle.txt](https://github.com/OpenRCT2/OpenRCT2/files/346849/Crazy.Castle.txt)

**Comment by Nubbie** [comment] 2016-07-04 21:43
That's because of 'Show all operating modes'

**Comment by Goddesen** [comment] 2016-07-04 21:48
Crooked House in race mode sounds fun.

**Comment by ThePsionic** [comment] 2016-07-04 22:16
@Nubbie It somehow fixed itself - I've not heard of a "Show all operating modes" option before, and I don't know what caused it to happen in this instance :o

**Comment by ThePsionic** [comment] 2016-07-04 22:17
@Goddesen I don't know, I'm kind of eyeing that "Upward launch" mode myself :wink:

**Comment by Nubbie** [comment] 2016-07-04 22:22
@ThePsionic Try looking in cheats and see if you can find it there

**Comment by Gymnasiast** [comment] 2016-07-05 08:04
I can't imagine this being triggered by anything other than accidentally checking 'Show all operating modes' when in the cheat window. For this reason, I'll close this. Should you find another reproducible way this can be reopened.

**Closed by Gymnasiast** 2016-07-05 08:04 UTC
