### ISSUE TITLE
Crash Panda World Object Selection

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#6763] opened 2017-12-02 11:21 UTC
**OS:** Windows 10
**Version:** v0.1.2.-develop build
**Commit/Build:** 0920e58  provided by AppVeyvor

Invalid font index 65675

**Steps to reproduce:**
1.  Open Panda World ( http://rct.wikia.com/wiki/Panda_World#Other_Notes)
2.  Open Object Selection
3. Crash

**Dump file**
no crash file found in the Users/OpenRCT2 directory. I had to close it via task manager.

**Screenshots / Video:**
![crash](https://user-images.githubusercontent.com/12634026/33514866-1a295d70-d75b-11e7-9b43-6069236aa526.PNG)

**Comment by janisozaur** [comment] 2017-12-02 11:32
Yet another duplicate of #6761

**Closed by janisozaur** 2017-12-02 11:32 UTC
