### ISSUE TITLE
[.park format] Ice Cube scenery object does not appear in Snow and Ice Themeing

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#14743] opened 2021-05-25 18:13 UTC
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 5f030df on refs/pull/10664/merge

#14736 has been fixed, but there is still an issue with the Ice Cube scenery object where if you have both the Water Feature Themeing and Snow and Ice Themeing scenery groups present, the Ice Cube (rct2.scenery_small.icecube) is selected, and you have scenery objects in the Miscellaneous Objects group, it appears in both Water Feature Themeing _and_ Miscellaneous Objects instead of correctly appearing in Water Feature Themeing _and_ **Snow and Ice Themeing**. It can even happen if the Miscellaneous Objects tab is not present at all.

**Screenshots:**
![Mythological Madness 2 2021-05-25 11-10-04](https://user-images.githubusercontent.com/61885939/119547316-cf1d5380-bd49-11eb-9795-f93d9264af45.png)
![Mythological Madness 2 2021-05-25 11-10-02](https://user-images.githubusercontent.com/61885939/119547319-d04e8080-bd49-11eb-9745-ce24dd4b4215.png)
![Mythological Madness 2 2021-05-25 11-09-59](https://user-images.githubusercontent.com/61885939/119547321-d17fad80-bd49-11eb-8a62-a980ccf1f028.png)
In the third screenshot, the Ice Cube can't be found anywhere in the Snow and Ice Themeing.

**Save game:**
[Mythological Madness 2.zip](https://github.com/OpenRCT2/OpenRCT2/files/6541822/Mythological.Madness.2.zip)

**Comment by Gymnasiast** [comment] 2021-06-05 09:26
Should be fixed as of https://github.com/OpenRCT2/OpenRCT2/pull/10664/commits/03339ce298c9ace85dd967f27f37de51434d6028 . I can’t reproduce this issue any more, could you verify this?

**Comment by Fred-1044276** [comment] 2021-06-05 15:31
It now appears in Trees instead.
![Hailstone Hills 2021-06-05 08-31-02](https://user-images.githubusercontent.com/61885939/120896893-6e5b0a00-c5d8-11eb-9f5b-6a8925335ecb.png)

**Comment by James103** [comment] 2021-06-05 15:37
> It now appears in Trees instead.

Can you confirm this actual behavior by letting OpenRCT2 generate a new landscape in the scenario editor with "Place Trees" selected? If the ice cube appears under "Trees", it may be classified as a tree and therefore be randomly placed in the "Place Trees" routine.

**Comment by Fred-1044276** [comment] 2021-06-05 15:50
I just went into the scenario editor with build 5991e47 and let the game generate a new landscape with "place trees" selected. The Ice Cube did not appear, only the Aleppo Pine Tree was placed.
![Unnamed park 2021-06-05 08-49-30](https://user-images.githubusercontent.com/61885939/120897431-fa6e3100-c5da-11eb-8c85-137717a370b3.png)

**Comment by Gymnasiast** [comment] 2021-06-05 16:19
> > It now appears in Trees instead.
> 
> Can you confirm this actual behavior by letting OpenRCT2 generate a new landscape in the scenario editor with "Place Trees" selected? If the ice cube appears under "Trees", it may be classified as a tree and therefore be randomly placed in the "Place Trees" routine.

This is not how it works. At all. Please do not comment on issues you don’t understand.

**Comment by IntelOrca** [comment] 2021-06-07 17:12
How do I reproduce the ice cube ending up in trees tab? What are the exact steps to repro?

**Comment by Gymnasiast** [comment] 2021-07-27 11:05
As of 03194d813ee08004477d251913b14ded2353d76e, it appears in the European theming tab (and doesn’t appear in the Snow and Ice theming tab).

It can be reproduced like this:

1. Load up the save in the opening post
2. Check the European Theming tab and see that the ice cube is there.
3. Check the Snow & Ice Theming tab and see that the ice cube is not there.

**Comment by Gymnasiast** [comment] 2021-07-27 11:39
Found the cause. It was confusing tab ids with object entry indices.

**Closed by Gymnasiast** 2021-07-27 11:39 UTC
Labels: New save format branch, bug, user interface
