### ISSUE TITLE
Scrolling texts going rogue

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3813] opened 2016-06-03 19:41 UTC
**OS:** Window 8
**Version:** 0.0.5.0 build a79e793

I don't know what happened, but suddenly all the scrolling texts are jumping all over the place. Texts on banners, scenery, entrance huts, park entrance, is jumping and glitching and flashing like crazy. One of the queue entrance scrolling texts was actually displaying both the normal text and a red 'closed' text, offset by maybe twenty pixels to the top-left, even though the ride was open.

I opened a scenario park to confirm that it's the game, not the savegame. Here's a screen from Electric Fields.

http://imgur.com/PaTDaT9

**Comment by Wirlie** [comment] 2016-06-03 20:56
Confirmed:
![scr32](https://cloud.githubusercontent.com/assets/7508197/15792488/31fe2ba4-29a3-11e6-8b14-3c34422fca0d.png)

a79e793e67be8e9d57819b6c7797c8e405c0d39d is the cause of this bug.

**Comment by dVoCex** [comment] 2016-06-03 21:15
I've this bug also

![3812](https://cloud.githubusercontent.com/assets/2843239/15792921/d5657710-29e0-11e6-8d19-4ff700a6fe00.gif)

**Comment by janisozaur** [comment] 2016-06-03 21:22
fixed in a9bf0cdd4e4db716

**Comment by Wirlie** [comment] 2016-06-03 21:25
@janisozaur are you sure? I can get this bug with the latest build a9bf0cd

**Comment by janisozaur** [comment] 2016-06-03 21:30
I can no longer reproduce it, and a9bf0cd seems to fix touch the area of code I would expect to contain the cause. Do you have a park I could check this on? What OS are you on?

**Comment by Wirlie** [comment] 2016-06-03 21:41
**os:** Windows 10 (32 bits).
I can get this problem when I start any scenario (or when I load any save game, this does not affect).

**Comment by dVoCex** [comment] 2016-06-03 21:51
OS: Windows 10 (64bits)
Happens in any save game, new game, or multiplayer game.

**Closed** 2016-06-03 22:27 UTC
Labels: bug
