### ISSUE TITLE
Rides built too high

### ISSUE THREAD

**Issue by McCake147** [OpenRCT2/OpenRCT2#4298] opened 2016-08-16 19:26 UTC
Windows 10
0.0.5
3f9c545
I'm trying to build a Twist, but it is being built a tiny bit too high. I tried it with a Top Spin, and the same issue happened. It originally happened in Razor Rocks, but I tried it in Park Maharaja and the rides did it there too. This happens with any flat ride (twist, carousel, etc) but not ones that you customize (observation tower, roto-drop, etc) This only happened today, and it's never happened before.

**Steps to reproduce:**
1. open any park
2. try to place a flat ride

**Reproducible in Multiplayer**
In multiplayer I can't build flat rides at all.

**Screenshots / Video:**
http://imgur.com/JKtZ6fo
It also happens when I elevate the ride:
http://imgur.com/RAFLUVl

**Save game:** (if it's any help)
[Razor Rocks.txt](https://github.com/OpenRCT2/OpenRCT2/files/421124/Razor.Rocks.txt)

**Comment by duncanspumpkin** [comment] 2016-08-16 20:31
Duplicate of #4297

**Closed by duncanspumpkin** 2016-08-16 20:31 UTC
Labels: duplicate

**Comment by McCake147** [comment] 2016-08-16 20:43
oh sorry

**Comment by duncanspumpkin** [comment] 2016-08-16 20:46
Its fine you both submitted at the same time. The other report was just a fraction quicker.
