### ISSUE TITLE
Switching between palettes requires to reopen object selection in order to load the new palette

### ISSUE THREAD

**Issue by Wulfke** [OpenRCT2/OpenRCT2#11912] opened 2020-06-08 17:30 UTC
**OS:** Windows 10
**Version:** 0.2.6-798
**Commit/Build:** g22d099d6b

Switching between two palettes requires you to reopen the object selection window and go to the water tab in order to correctly load the new palette you've chosen. In between loading the new palette it switches back to natural water.

**Comment by James103** [comment] 2020-06-08 17:37
I've seen that happen in Deurklink's videos, see https://youtu.be/2epMQ_6tU1s?t=53 (published on 2 June 2018, made in OpenRCT2 0.1.3 build 58bde44).

**Comment by Gymnasiast** [comment] 2020-06-08 23:04
Can reproduce. Has been in the game for a while.

**Comment by AaronVanGeffen** [comment] 2020-06-09 06:46
Duplicate of #10639?

**Comment by Gymnasiast** [comment] 2020-06-09 14:42
Yeah. Closed the old one because this is described better.

Video from old issue: http://puu.sh/F5RjT/16b330d3db.mp4

**Comment by Ryder17z** [comment] 2020-06-09 16:27
> Video from old issue: http://puu.sh/F5RjT/16b330d3db.mp4

file purged for some reason. returns 404 now.

**Comment by Gymnasiast** [comment] 2021-01-17 21:23
Possibly a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/4605.

**Closed** 2021-01-18 20:25 UTC
Labels: bug
