### ISSUE TITLE
Camera movement locked at 60 updates per second?

### ISSUE THREAD

**Issue by knexfan0011** [OpenRCT2/OpenRCT2#11242] opened 2020-04-07 02:40 UTC
When I move the camera, either with arrow keys or the mouse, the game view appears to not update at my framerate(120). 
The game is running at 120fps according to the ingame FPS counter and moving objects, like vehicles or peeps, are perfectly smooth when the camera is stationary.
But moving the game view is not smooth and seems to just update 60 times per second, this is especially apparent when looking at long bright vertical supports in front of a dark background and moving the camera side to side.
With Blur Reduction (low persistence) enabled on my monitor it is much more obvious, as the supports appear to duplicate.

**Steps to reproduce:**
1. Have game running at 120fps on a 120hz monitor, if available enable blur reduction(low persistence) to make this issue more obvious
2. Observe objects move smoothly at 120fps with stationary camera
3. When you move the camera, you can see that the game view appears to update only every other frame.

**Comment by Richard-L** [comment] 2020-04-07 08:03
I would love smoother panning as well.

**Comment by Gymnasiast** [comment] 2020-04-07 08:55
Duplicate of #6152.

**Closed by Gymnasiast** 2020-04-07 08:55 UTC
