### ISSUE TITLE
Ride supports invisible when opening parks

### ISSUE THREAD

**Issue by jpmad94** [OpenRCT2/OpenRCT2#22753] opened 2024-09-12 02:56 UTC
### Operating System

Windows 10, 64-bit operating system, x64-based processor

### OpenRCT2 build

OpenRCT2, v0.4.14 (18492da) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When opening parks, the supports for coasters are defaulted to invisible. It's nothing major, but something to note as happening as it is expected not to operate that way.
![No Supports](https://github.com/user-attachments/assets/8dfedf69-264a-46de-8d58-f113b92b1240)

### Steps to reproduce

1. open the game
2. load any saved park

### Attachments

![No Supports](https://github.com/user-attachments/assets/d1e260a2-540e-423c-acd5-852a41e1e435)

**Comment by SpartanFrederic104** [comment] 2024-09-12 06:48
Related to #22729

**Comment by Gymnasiast** [comment] 2024-09-12 07:33
Duplicate of #22729.

**Closed by Gymnasiast** 2024-09-12 07:33 UTC
Labels: bug
