### ISSUE TITLE
BACKTRACE 0325e3

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8243] opened 2018-11-09 07:27 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/0325e3ac64405064af93236345ed5b90bec211b1419b946f7f1910f54645e924?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Nov 09 2018 07:27:33)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 18f1fab: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ride_modify -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:45
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8441

**Closed by janisozaur** 2019-02-02 22:45 UTC
Labels: backtrace.io, crash
