### ISSUE TITLE
Can't pop balloons

### ISSUE THREAD

**Issue by spawnraider** [OpenRCT2/OpenRCT2#4261] opened 2016-08-10 20:06 UTC
Balloons can't be popped in single player or multiplayer. Nothing happens when you click on them.

**Comment by mrtnptrs** [comment] 2016-08-10 20:25
@spawnraider Are you sure your problem isn't the same as this issue report?: #675

**Comment by spawnraider** [comment] 2016-08-10 20:39
I don't think so since I see no response at all. No movement or popping.

**Comment by Gymnasiast** [comment] 2016-08-10 20:42
Why did you remove the issue template? It isn't there for nothing. Please put it back and fill in the appropriate fields.

**Comment by zsilencer** [comment] 2016-08-10 22:36
balloon popping was disabled in multiplayer because it causes desyncs but it should still work in single player.

**Comment by Nubbie** [comment] 2016-08-15 22:39
Expired?

**Comment by Gymnasiast** [comment] 2016-08-16 06:54
Can't reproduce it in single player, it's disabled deliberately in multiplayer and the OP has not responded to my requests. Closing this.

**Closed by Gymnasiast** 2016-08-16 06:54 UTC
Labels: invalid/incomplete

**Comment by Margen67** [comment] 2016-08-16 10:52
Will it be re enabled if it doesn't cause a desync?

**Comment by duncanspumpkin** [comment] 2016-08-16 11:05
It would require making a game command just for popping but yes if that was done it could be reenabled.
