### ISSUE TITLE
Guest entering no entry signs

### ISSUE THREAD

**Issue by harrysbird** [OpenRCT2/OpenRCT2#2344] opened 2015-11-19 05:50 UTC
We put a Sign No Entry and guest is bypassing and entering no entry sign, we tried to put secruity guard and still not work.

**Comment by PFCKrutonium** [comment] 2015-11-19 05:58
I can't seem to find it (?) but I know this has already been posted, so it may be a duplicate.

**Comment by IntelOrca** [comment] 2015-11-19 08:27
Duplicate of #2327.

**Closed by IntelOrca** 2015-11-19 08:27 UTC
Labels: duplicate
