### ISSUE TITLE
Explosive track

### ISSUE THREAD

**Issue by Wimali** [OpenRCT2/OpenRCT2#2368] opened 2015-11-22 23:21 UTC
Simple: If your ride failed and a car blew up, the track was going to be destroyed too. As originally intended by Chris Sawyer. Example picture from the game's concept art: http://i.imgur.com/T3FEiET.gif

This could be expanded, too- You'd be able to repair the broken track, there could be debris in the vicinity of a broken track, guests currently in the park could get scared and leave the park because they hear/see there was an explosion, the park could be forced to temporarily close,--- The exploding rides could be expanded much more in general, and have a bigger impact on the game than before.

**Comment by Christipher** [comment] 2015-11-23 00:23
Assuming the issue was not caused by two trains colliding into each other - that I believe should have precedence over the track being wiped...

**Comment by HaasJona** [comment] 2015-11-23 09:25
:-1: Exploding track is unrealistic, roller coaster trains are not loaded with dynamite. Chris Sawyer did the right thing by not implementing this. Also, this would require tons of new exploded track sprites, which we currently don't have and probably don't want to create.

**Comment by Gymnasiast** [comment] 2015-11-23 09:26
^ Exactly.

Also a duplicate of #663.

**Comment by osconnoisseur** [comment] 2015-11-24 18:44
Perhaps Sawyer wanted some broken track piece like on Expedition Everest. Who knows...

**Closed** 2015-11-24 21:53 UTC
Labels: alteration, vetoed
