### ISSUE TITLE
Scenario(including korean texts in scripts) load fails

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#7415] opened 2018-04-15 10:19 UTC
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** d0ad94b

There are hundreds of OpenRCT2 custom-made scenarios in korean community, and also they have korean texts in their scripts such as scenario description.
But it is impossible to load such scenarios, nor hovering mouse on the scenario list. Game just crashes.

When I run them by using **openrct2.com**, its console returns like this:
``
WARNING[c:\projects\openrct2-ject9\src\openrct2\localisation\localisation.cpp:1155 (format_string)]: Truncating formatted string "혦챘?셋㉲ヂ볛뼯 챠혬혙챘혷혵챙휋혞챘혫짚챙혶??챙휋혨챗?댿뎵 챙혞혱 챙혷혞챘혡혬 챘혛?챙혶?쑦ぢ년궗챙혴혨챙혶혙 챘흟혣챘혫혵챘혡혬챗?ㅒ걘?뺚뼱!, 챗째?챘째짤 챘혙혞챘혡혬 챘?볛쑦?쀂눬?앪쑦ヂ볛뼯 챙혷혱 챠혮??챙혞혱 챙혷혞챙혵?늘ヂ떷댠も겭혣" to 256 bytes.
``

Note that 0.1.2 stable works fine, and default scenarios work fine, too.

**Steps to reproduce:**
1. Download and apply a scenario that contains korean text in their scenario description.
   (for example: https://rctsc.telk.kr/download?no=625)
2-1. Double click the sc6 file
2-2. Or, open the scenario list, and hover the mouse on it.
3. Game crashes.

**Dump file**

**Screenshots / Video:**
And, the three scenarios in the very bottom in the list are custom scenarios made by users.
Their name were "숨겨진 진실", "폐교된 대학교", "환상의섬 제주", which is korean text.
![image](https://user-images.githubusercontent.com/10726524/38777350-6702d8c0-40e1-11e8-973e-e336bea93c43.png)

And, an error message when I double-clicked sc6 file directly:
![image](https://user-images.githubusercontent.com/10726524/38777379-cdc363b8-40e1-11e8-98b0-23c1d3fa908a.png)

**Save game:**

**Comment by Gymnasiast** [comment] 2018-04-15 10:33
Until recently, OpenRCT2 would save newly created scenarios in the wrong encoding. But since it also loaded scenario names in the wrong encoding, this was never obvious.

In any case, it should not crash because of encoding going wrong.

**Comment by Lastorder-DC** [comment] 2018-04-15 14:30
adding utf-8 string check to `rct2_to_utf8` solves this problem.(not convert to utf-8 if string is already utf-8)
but it will be better if encoding is checked by library like libicu.

**Comment by fromthere** [comment] 2018-04-22 07:38
http://rctsc.telk.kr
There are about 600 custom scenarios literally and most of them are unplayable because of this bug.(having korean in names)

**Comment by AaronVanGeffen** [comment] 2018-04-26 19:46
I can reproduce the rendering issue using English, too. For me, the pause button does appear, but chunks of the menus themselves are missing, including the background. This notably happens on the save menu, for me. I'm guessing this is unrelated to the character set changes, but I have not had time to bisect the issue.

**Comment by Lastorder-DC** [comment] 2018-05-04 03:53
@telk5093 names are not fixed. try delete `scenarios.idx` file. scenario names will break again

**Comment by AaronVanGeffen** [comment] 2018-05-11 20:42
I'm afraid loading scenario names and descriptions still hasn't been fixed yet.

On c7b40cec7cf55326aa4b33eeb1d71b58311660ef:
![screenshot_20180511_223342](https://user-images.githubusercontent.com/604665/39945886-62c8b69a-556c-11e8-9213-371aca45600a.png)

On v0.1.2:
![screenshot_20180511_224047](https://user-images.githubusercontent.com/604665/39945887-62e6937c-556c-11e8-968b-a4a5e36ca669.png)

**Comment by Gymnasiast** [comment] 2018-05-12 07:56
This is not related. What you have is a bit reading STEX objects, what @telk5093 has is an encoding bug in the scenario files themselves.

**Comment by AaronVanGeffen** [comment] 2018-05-12 08:30
OK. Split off to https://github.com/OpenRCT2/OpenRCT2/issues/7509.

**Comment by Gymnasiast** [comment] 2018-05-12 09:03
@telk5093 In the original Korean version of RCT2, is it possible to save scenario descriptions in Korean?

**Comment by telk5093** [comment] 2018-05-12 09:05
@Gymnasiast Yes, it is stored in modified CP-1252.

**Comment by Gymnasiast** [comment] 2018-05-12 09:06
Can you provide me with a scenario with Korean descriptions, created in the **original Korean version of RCT2**?

**Comment by telk5093** [comment] 2018-05-12 09:07
@Gymnasiast Please wait a couple of hours.

**Comment by telk5093** [comment] 2018-05-12 10:59
[Korean scenario.zip](https://github.com/OpenRCT2/OpenRCT2/files/1997525/Korean.scenario.zip)
Scenario name: ``한국어 이름``
Park name: ``한국어 이름``
Scenario description: ``한국어 설명``

Generated from vanilla RCT2 (not a steam edition. Steam edition does not support korean)

**Comment by telk5093** [comment] 2018-07-20 17:35
So, it is not solved until today.
Is it hard to solve it or nobody is interested in?
@Gymnasiast @AaronVanGeffen

**Comment by Lastorder-DC** [comment] 2018-07-21 00:39
@telk5093 making converter and convert all wrong encoding scenario files might better than converting in openrct2.

there's already solution for this(2e7d6e58d0daef41c2216081314ad9551049446d) but that commit is not complete(that did not check name, needs rebase). also, some short korean string might parsed as utf-8 anyway(since it only depends having colour code in string and short korean strings might not have that)

**Comment by Gymnasiast** [comment] 2018-07-22 09:32
@Lastorder-DC That, plus I would also want to add support for the encoding that RCT2 used, if possible.

By the way, could someone provide me with the Korean exe of RCT2, so I can test a few more things?

**Comment by telk5093** [comment] 2018-07-22 09:33
@Gymnasiast Here you are: [rct2.zip](https://github.com/OpenRCT2/OpenRCT2/files/2216871/rct2.zip)

**Comment by telk5093** [comment] 2018-07-23 15:08
@Gymnasiast 
I have tried to avoid this issue like below:
 1. delete scenarios.idx file
 1. Rollback 0.1.2
 1. Run, and revert to latest develop.

But It seems that all korean scenario name/desc are broken after **Danish** translation is added.
I think LANGUAGE_KOREAN is shifted one in src/openrct2/localisation/Language.h so that my palliative does not work, do you think am I right?

**Comment by Gymnasiast** [comment] 2018-07-23 15:12
Yes, I think so.

**Comment by telk5093** [comment] 2018-07-29 06:11
Is it right to put danish in the middle of enum, instead of being added at the last position?

**Comment by telk5093** [comment] 2018-08-04 19:17
I think recently saved scenario in OpenRCT2 mangles korean encoding.

I just made a scenario in OpenRCT2(3ccad7c) with name ``시나리오이름``, but when I decode SC6 file and look its hex data, it stores name as ``20 C2 9C 20 20 20 20 20 20 20 C6 A4 20 C7 B4 20 20 20``

Originally, ``시나리오이름`` = ``BD C3 B3 AA B8 AE BF C0 C0 CC B8 A7`` in EUC-KR encoding. (``BD C3`` = ``시`` / ``B3 AA`` = ``나`` / ...)
And the vanilla would stores ``시나리오이름`` as ``FF BD C3 FF B3 AA FF B8 AE FF BF C0 FF C0 CC FF B8 A7``. Note that there are **FF**s in front of each two bytes.

**Comment by Gymnasiast** [comment] 2018-08-12 14:29
I finally got around to testing it.

This is what the scenario you provided looks like in vanilla RCT2:

![scr2](https://user-images.githubusercontent.com/1478678/44003024-38b76cb0-9e4c-11e8-9c61-e675d0a57daf.PNG)

And there lies the problem: RCT2 simply assumed that the scenario was in the same encoding as the language the EXE was in. It basically means that we cannot import scenarios with Korean descriptions properly without breaking support for scenarios with English/German/Dutch/etc. descriptions.

**Comment by telk5093** [comment] 2018-08-12 15:54
I can't understand that it **requires new save format**.
Former OpenRCT2 had supported korean scenario names/descriptions very well(Eg. before 0.2.0), and it has been ruined at some time.

**Comment by Gymnasiast** [comment] 2018-08-12 16:00
No, because that breaks importing scenarios from vanilla with non-ASCII characters. The code wrongly assumed that RCT2 saves used UTF-8 encoding.

I know it's not nice that you cannot save Korean descriptions now, but I cannot fix that without breaking compatibility with the vanilla encoding.

This issue can only be _properly_ solved with a new save format. All other options break _something_.

**Comment by AaronVanGeffen** [comment] 2018-08-12 16:07
As I understand it, vanilla RCT2 used different encoding in the scenario files depending on its language. Unfortunately, it does not save which language a scenario is describing, so we have to pick the most compatible one…

**Comment by telk5093** [comment] 2018-08-12 16:13
Then it will be very serious since Korean won't use most of custom scenarios until new save format is applied(and we have no idea when it will be applied). I think it is not proper to wait until we apply new save format. Any alternatives?

**Comment by IntelOrca** [comment] 2018-08-12 17:45
Would you be able to detect the encoding based on the strings in the scenario file?

**Comment by Gymnasiast** [comment] 2018-08-12 18:40
I don't think so. I can detect the `0xFF` character, which means it's multibyte (and since I think most CJK users will be Korean, we could assume Korean if the SV6 file has them). I can also detect if the converted CP1252 contains colour codes or other stuff not expected in descriptions - meaning I can detect the broken scenarios with UTF-8 encoding. Saving is far more complicated, though.

**Comment by AaronVanGeffen** [comment] 2018-08-12 18:47
> I can detect the 0xFF character, which means it's multibyte

Sorry, I don't follow. 0xFF is forbidden by the UTF-8 specification…?

**Comment by Gymnasiast** [comment] 2018-08-12 19:04
Chris Sawyer used the 0xFF character to separate characters in multibyte encodings. So if it contains them pre-conversion, it means that the text is using a multibyte encoding.

**Comment by tupaschoal** [comment] 2020-10-01 03:54
@telk5093 I can load the park just fine, with no crash and no pause button glitch, so I'm closing this issue. Please let us know if you can still reproduce it.

**Closed by tupaschoal** 2020-10-01 03:54 UTC
Labels: bug, requires new save format
