### ISSUE TITLE
BACKTRACE 79303d

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8494] opened 2018-12-19 14:48 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/79303dd15502cd0a8a6fc9d5179f3a07ab6299902009147248139f7e9ce70ac3?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Dec 19 2018 14:45:29)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\chris\\OneDrive\\Documents\\OpenRCT2\\bd9a7d5f-fef8-40e9-a682-557ccc0ab727.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\chris\\OneDrive\\Documents\\OpenRCT2\\bd9a7d5f-fef8-40e9-a682-557ccc0ab727.sv6.gz: <em>1</em><br><strong>commit:</strong> 38b26e0: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Network::ProcessPlayerList -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::TitleScreen::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2018-12-19 19:35
duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8482

**Closed by janisozaur** 2018-12-19 19:35 UTC
Labels: backtrace.io, crash
