### ISSUE TITLE
Assertion Failed When Opening Build New Ride/Attraction Window with Active Tab Previously Set to R&D

### ISSUE THREAD

**Issue by Androgeos** [OpenRCT2/OpenRCT2#4958] opened 2016-12-31 15:12 UTC
**OS:** Windows 10
**Version:** 0.0.6
**Commit/Build:** 99a662f

- [ ] Reproducible in RCT2 (vanilla)
- [ ] Multiplayer

**Steps to reproduce:**
1. Load _any_ scenario or saved game
2. Open the Build new ride/attraction window
3. Change the tab to Research & Development
4. Close the Build new ride/attraction window
5. Open the Build new ride/attraction window

**Notes**
No dump files were generated as this wasn't a crash. If I choose "Ignore", the Research & Development tab in the Build new ride/attraction window opens and the game continues as per normal.

My untrained eye tells me that the game was apparently trying to highlight something on the Research & Development tab, but since there's nothing to highlight there, it throws up the error.

I initially thought it was a crash, so this proves that the "Ignore" button still has its uses. ;)

**Screenshots / Video:**
You can generate this assertion failure easily, but here's a screenshot of the error message anyway:
![assertionfail](https://cloud.githubusercontent.com/assets/18898491/21578086/55201334-cfae-11e6-85b0-7185d063895f.png)

https://youtu.be/1oZQKc7BMfY
This video was uploaded when I still thought it was a crash and caused by something else. However, you can see that I (accidentally) avoided the assertion failure at 2:31 when I clicked on the Research & Development button instead of opening the Build new ride/attraction window; if I had opened the Build new ride/attraction window then, there would have been an assertion failure at that point.

**Comment by janisozaur** [comment] 2016-12-31 16:05
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/4957, but I'll leave this one for nice repro steps.

**Comment by IntelOrca** [comment] 2017-01-01 20:01
@janisozaur 99a662fc5f0fd71077f58694daf3592a2148a1b1 is after the fix... why does it still happen?

**Closed** 2017-01-01 20:07 UTC
