### ISSUE TITLE
Staff areas not working in multiplayer

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2777] opened 2016-01-19 16:25 UTC
They walk all over the place.

**Comment by duncanspumpkin** [comment] 2016-01-19 17:15
This is a duplicate of #2275

**Closed** 2016-01-19 17:16 UTC
Labels: duplicate

**Comment by Phyxion** [comment] 2016-01-19 17:19
Is it a duplicate? It might be related to the same but the one you referenced talks about crashes. I can see the area's assigned but the staff is just ignoring them.

**Comment by duncanspumpkin** [comment] 2016-01-19 17:30
Its completely related once #2275 is fixed it will fix this.

**Comment by IntelOrca** [comment] 2016-01-19 17:38
Basically anything to do with staff = not work in multiplayer. The whole code around staff and peep movement needs to be completely re-worked so its not necessary to have multiple issues about it.
