### ISSUE TITLE
Profit calculation is wrong when using on-ride photos

### ISSUE THREAD

**Issue by chaitanyathengdi** [OpenRCT2/OpenRCT2#12244] opened 2020-07-13 20:08 UTC
Below is profit and customer stats of the Shuttle Loop ride with an on-ride photo added:
![image](https://user-images.githubusercontent.com/14993220/87346946-0343b780-c570-11ea-81cc-0e964cbdd52f.png)
![image](https://user-images.githubusercontent.com/14993220/87346958-08a10200-c570-11ea-8ab4-21d7a6d2e98e.png)
These stats are around the 7-month mark, and 1 hour elapses in ~10 months.

Based on the numbers above, the profit seems to be calculated based on the assumption that every customer buys a ticket as well as a photo, whereas actual profit seems to be based on ticket OR photo(1600 tickets + 400 photos)

There should be a less-than-1 multiplier for adding profit of on-ride photos to the total profit, since not all guests end up buying photos.

**Comment by tupaschoal** [comment] 2020-07-13 20:10
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/10946

**Closed by tupaschoal** 2020-07-13 20:10 UTC
Labels: duplicate
