### ISSUE TITLE
BACKTRACE aa1bdd

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8241] opened 2018-11-08 08:03 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/aa1bdd46bb3581b20df57ddd8f94c2f287b3033666c87f362293e35c1a15cbb7?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Thu Nov 08 2018 08:03:08)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 223ae74: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy_deallocate -> Object::~Object -> SceneryGroupObject::scalar deleting destructor' -> ObjectManager::UnloadAll -> OpenRCT2::Context::~Context -> OpenRCT2::Context::scalar deleting destructor' -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-03 07:54
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8423

**Closed by janisozaur** 2019-02-03 07:54 UTC
Labels: backtrace.io, crash
