### ISSUE TITLE
Opening the object selection window or inventions list automatically completes research for currently researched ride

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#17627] opened 2022-07-27 22:00 UTC
### Operating System

Windows 10 64 bit

### OpenRCT2 build

30f4779

### Describe the issue

If the ride/scenery research in the second (designing) or third (completing design) phase and you open up the inventions list or the object selection window, that ride/scenery item will automatically be researched when you close it again. 

I have tested this in the current dev build, 0.4.0, and 0.2.0, and it happened in all three versions, so it's been in the game for a very long time.

### Steps to reproduce

1. Wait until research is in the second phase
2. Open one of the mentioned windows through the cheats
3. Close the window again
4. Check the research, the item should now be researched

**Comment by James103** [comment] 2022-07-27 22:44
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/15502

**Closed** 2022-07-27 23:20 UTC
Labels: bug
