### ISSUE TITLE
Incorrectly directed sprite in Monorail

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2901] opened 2016-02-09 06:02 UTC
![image](https://cloud.githubusercontent.com/assets/10726524/12908859/1836265a-cf3e-11e5-9683-6f7db317bd61.png)

As you can see on above.

**Comment by PFCKrutonium** [comment] 2016-02-09 20:59
I think I have seen this on trains as well, so it may effect transport rides in general.

**Comment by Christipher** [comment] 2016-02-10 22:07
This can be reproduced in the original game as well...

**Comment by Phyxion** [comment] 2016-02-13 09:27
But it happens way more often in OpenRCT2.

**Comment by PFCKrutonium** [comment] 2016-02-13 18:34
Far more often in OpenRCT2.

**Comment by Christipher** [comment] 2016-02-14 07:15
just because it happens more often in openRCT2 does not mean that the fact it did appear in the original game should be ignored - this does on occasion occur with the original game.

**Comment by PFCKrutonium** [comment] 2016-02-14 07:50
But it does mean we are doing something different that is aggravating it.

**Comment by Phyxion** [comment] 2016-02-14 09:16
This also happens on coasters.

**Comment by duncanspumpkin** [comment] 2016-02-14 09:27
Can anyone provide a save with this happening.

**Comment by Phyxion** [comment] 2016-02-14 09:38
It happens on the coaster named "Purple Rain". You can also see the a few wagons going slighlty up and down for a while. Then, when they enter the station you can see the wrong sprite rendered.
[Gravity Gardens.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/129605/Gravity.Gardens.sv6.txt)

**Comment by duncanspumpkin** [comment] 2016-02-14 11:17
It looks to be direction `0x14` is causing issues. I can't work out why. I tried reverting the rendering to  vanilla code to fix it but that still created the same issue. I also tried reverting the vehicle update code and the issue was still present. Can we get this tested on the disc version of the game. I have a working idea that possibly this is one of the odd bugs that might be fixed in later versions of the game. (@Phyxion i've made a super small version of your affected ride for testing purposes) 
[2901Test.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/129628/2901Test.sv6.txt)

**Comment by Phyxion** [comment] 2016-02-14 11:22
Even though the same wagons are also going up and down in the vanilla version, the correct sprites are rendered. I use the Steam version in case it helps.

**Comment by duncanspumpkin** [comment] 2016-02-14 11:44
Okay looks like this is a bug that was fixed in later versions of the game https://files.gitter.im/OpenRCT2/OpenRCT2/Ec6m/SCR1.PNG this is from the original disc version and this is from the gog version 
![gogversion](https://cloud.githubusercontent.com/assets/1277401/13033491/3e86f9a8-d310-11e5-8e98-0289115338bb.PNG)

I think it will need modification of the drawing code to fix.

**Comment by duncanspumpkin** [comment] 2019-07-08 20:11
This was fixed at some point.

**Closed by duncanspumpkin** 2019-07-08 20:11 UTC
Labels: original bug
