### ISSUE TITLE
New Lower Maximum Images Number

### ISSUE THREAD

**Issue by Gutterflower** [OpenRCT2/OpenRCT2#7785] opened 2018-07-16 15:47 UTC
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** ab20dcd

Having recently been away from home with no internet connection I have been building a park on version 0.1.2 The park loads correctly in this version of the game and the park was built to viewable within the existing game limits. 

When i returned hope i updated to 0.2.0 and the park no longer correctly displays as it appears the maximum image number has been significantly lowered. (Through a bit of testing and removing ride types it appears to have dropped by at around 50,000 images)

I'm aware the Image memory problem is a known issue but the latest release seems to have made it much worse. 

**Screenshots / Video:**
![brokenrct](https://user-images.githubusercontent.com/41299760/42768007-4c349f9c-8916-11e8-88cd-bf7cb1b94cf5.JPG)

![brokenrct2](https://user-images.githubusercontent.com/41299760/42768520-aa8072aa-8917-11e8-90e7-a7df1ecfae6f.JPG)

**Comment by Gymnasiast** [comment] 2018-07-20 08:56
I expect it might have been caused by JSON objects not properly freeing image slots, what do you think @IntelOrca ?

**Comment by IntelOrca** [comment] 2018-07-20 09:50
Can you upload the saved game with objects please.

**Comment by Gymnasiast** [comment] 2024-05-27 12:34
No save was uploaded and the issue was likely to have been fixed anyway, so I’m closing it.

**Closed by Gymnasiast** 2024-05-27 12:34 UTC
Labels: bug
