### ISSUE TITLE
Diagonal Steep-Slope Supports on Inverted Coasters Drawn Incorrectly

### ISSUE THREAD

**Issue by YoloSweggLord** [OpenRCT2/OpenRCT2#5148] opened 2017-01-31 15:15 UTC
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 94d38b9

Supports on diagonal steep slope track are drawn wrong. The horizontal bar seems to be drawn below the track, rather than above, and the support doesn't stop at the land tile, resulting in no footer being drawn.

**Steps to reproduce:**
1. Build a diagonal steep slope track piece on an inverted coaster, such as flying or inverted coaster types.
2. The horizontal bar is clearly being drawn too low, and no footer is being drawn where those supports touch the ground. Turning on underground/inside view shows that the supports don't stop when they hit the ground.

**Screenshots / Video:**
![diagonal supports 2017-01-31 10-08-02](https://cloud.githubusercontent.com/assets/19209095/22470526/96ae8856-e79d-11e6-858a-c9047ff24358.png)
![diagonal supports 2017-01-31 10-08-04](https://cloud.githubusercontent.com/assets/19209095/22470525/96ae6a2e-e79d-11e6-840c-289ccaa95dbc.png)

**Comment by Broxzier** [comment] 2017-05-18 17:56
Related to (possibly duplicate of) #4591

**Comment by Liampie** [comment] 2017-07-08 21:23
All inverted track has problems when diagonal and steep.

![ne multiplayer map 2017-07-08 23-22-02](https://user-images.githubusercontent.com/19242088/27989212-2271011c-6402-11e7-82fc-c5fa8d0c7564.png)
![ne multiplayer map 2017-07-08 23-22-01](https://user-images.githubusercontent.com/19242088/27989213-2271bc74-6402-11e7-9e61-a91ce4719b8a.png)

**Comment by duncanspumpkin** [comment] 2017-07-09 07:04
@Liampie what is it meant to be drawn as? From my quick tests its not meant to draw any support for steep slopes is that correct?

**Comment by Gymnasiast** [comment] 2017-07-09 17:41
I always found it strange that vanilla doesn't draw supports on steep slopes for some coasters. Should we change that?

**Closed** 2017-07-10 06:16 UTC
Labels: bug
