### ISSUE TITLE
Permission denied for autosave in multiplayer

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#4156] opened 2016-07-23 12:26 UTC
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 306cf2383c37987db4b4b0c51ec4b2aaf59c9b21

In multiplayer, when a client autosaves, a permission denied error box is shown. Saving should not send a command to the server and visa versa.

**Comment by Nubbie** [comment] 2016-07-23 12:33
Have been wondering why it popped up all the time, if happen from some months ago

**Comment by mrtnptrs** [comment] 2016-07-23 12:40
Duplicate of #3833 :)

**Closed** 2016-07-23 12:41 UTC
Labels: bug, multiplayer
