### ISSUE TITLE
OpenRCT2 brakes/boosters can't be changed

### ISSUE THREAD

**Issue by DarkestOfAll** [OpenRCT2/OpenRCT2#17819] opened 2022-08-14 10:43 UTC
### Operating System

Win 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.1-187-g121afbe (121afbe on develop) provided by GitHub

### Describe the issue

Whenever I open a game and build a coaster, I cannot change its speed values for brakes and boosters. Haven't made any changes to the game. Yesterday it ran completely normal, today it isn't anymore.

### Steps to reproduce

1. Start any park.
2. Start building a rollercoaster.
3. Try to adjust speed values while building a brake oder booster section.

### Attachments

![Six Flags Holland 2022-08-14 12-38-55](https://user-images.githubusercontent.com/111226259/184533154-7e222f8d-baa8-4d45-a96f-8a0716c55d25.png)
![Six Flags Holland 2022-08-14 12-39-20](https://user-images.githubusercontent.com/111226259/184533156-5d264072-bf22-4b4d-9a2f-ccb623596f69.png)

**Comment by karst** [comment] 2022-08-14 13:18
Duplicate of #17818 (although i like this title better)

**Comment by Rybread0912** [comment] 2022-08-14 18:10
I'm having the same issue.

**Comment by Gymnasiast** [comment] 2022-08-14 20:19
They _can_ be changed, but the display is broken.

**Closed** 2022-08-14 20:37 UTC
Labels: bug
