### ISSUE TITLE
Uppercase - lowercase on banners

### ISSUE THREAD

**Issue by keukenrol** [OpenRCT2/OpenRCT2#17380] opened 2022-06-12 13:01 UTC
### Operating System

Windows 10 x64

### OpenRCT2 build

OpenRCT2 develop b0ffa9d

### Describe the issue

Some banners show the text in uppercase depending on the color. On the other end, the "display text on banners in uppercase" option under rendering does not have an effect either. This for both placeable banners over paths as well as the main enterance banners.

### Steps to reproduce

1.  Place banners in game and change the text color
2.  Cycle the uppercase option
3.  Check park enterance and placeable banner case.

**Comment by Artemyanen** [comment] 2022-06-20 13:49
Taking a look at this one

**Comment by Gymnasiast** [comment] 2022-06-21 18:36
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/15787.

**Closed by Gymnasiast** 2022-06-21 18:36 UTC
Labels: bug
