### ISSUE TITLE
No entry signs ignored

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#4320] opened 2016-08-22 09:59 UTC
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 35ae7600f9647f7be01b4ec3f059f7061aa5f52a.

Guests go through the no-entry signs. This didn't happen before the pathfinding update (or at least I didn't notice it before).
Very easy to spot by running the game at turbo speed. 

**Screenshots / Video:**
![mines of africa 2016-08-22 11-54-19](https://cloud.githubusercontent.com/assets/7643972/17850893/9a95a764-685f-11e6-88e5-3fbc992d390a.png)

**Save game:**
[Mines of Africa - Copy.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/429813/Mines.of.Africa.-.Copy.sv6.txt)

**Comment by IntelOrca** [comment] 2016-08-22 10:32
@zaxcav Could you look at this?

**Comment by duncanspumpkin** [comment] 2016-08-22 11:16
Is this only happening on wide paths?

**Comment by zaxcav** [comment] 2016-08-22 11:17
I'll have a look.  I'm not yet familiar with how no-entry signs relate to the tile edges, so I'll need to get up to speed. At present the pathfinding search explores all set tile edges, so if no-entry signs are not reflected in the tile's set edges the AI can walk through them.

**Comment by zaxcav** [comment] 2016-08-22 14:19
Found the issue.  It appears to be an original bug inherited from RCT2.
_peepPathFindIsStaff is not always set when necessary - only aimless peeps are affected.
I'll try to make a fix and submit a PR tonight or tomorrow.

**Comment by duncanspumpkin** [comment] 2016-08-22 15:00
@zaxcav that sounds very unlikely. I might get time to fix it tonight if you don't get there first

**Comment by duncanspumpkin** [comment] 2016-08-22 20:02
Bug has been in the game since i implemented the peep pathfinding last year. Issue caused by refactoring.

**Comment by zaxcav** [comment] 2016-08-22 20:05
I've just committed a 1 line fix and was about to make a PR. Shall I continue or would you prefer to correct it?

**Comment by duncanspumpkin** [comment] 2016-08-22 20:05
10 seconds too slow :(

**Comment by zaxcav** [comment] 2016-08-22 20:05
That's ok.  It's fixed, and that's what's important :-)

**Closed** 2016-08-22 20:05 UTC
Labels: bug
