### ISSUE TITLE
Ride viewport does not scale with window size

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#15440] opened 2021-09-19 20:30 UTC
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (d3f7660 on develop) provided by GitHub

### Describe the issue

When opening a ride, the viewport size is smaller than its frame. Changing the size of the viewport does not change it.

![image](https://user-images.githubusercontent.com/3454156/133941781-e6743c01-5a72-4a9d-b2fc-d34c0043fc8a.png)
![image](https://user-images.githubusercontent.com/3454156/133941874-ab279ab0-4de6-47c6-b41c-7b93e07c3d3c.png)

Changing the subject from the drop-down menu does update it, but if one shrinks the window after updating the viewport size the viewport size will overrun the window size.

### Steps to reproduce

1. 
2. 
3.

**Comment by duncanspumpkin** [comment] 2021-09-19 20:41
Duplicate of #15439

**Closed by duncanspumpkin** 2021-09-19 20:41 UTC
Labels: bug, duplicate
