### ISSUE TITLE
Park entrance disconnect with clearance checks disabled in sandbox mode

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1613] opened 2015-07-14 16:17 UTC
Hovering over the park entrance's path tile while in sandbox with clearance checks disabled will disconnect the path. See [video](https://www.dropbox.com/s/4zykjo0a77x4e6y/entrance_path_disconnect.mov?dl=0).

**Comment by Margen67** [comment] 2016-05-17 09:55
This can also happen with any path that's "connected" like ride exits, entrances, and shops.

It's quite annoying, especially since you can't re-enable clearance checks without proper permissions.

**Comment by Broxzier** [comment] 2018-03-11 00:11
Unable to reproduce this with park entrances, since now the park entrance's path type gets update when building a path on top of them, even with zero clearance, both path building modes, and even with a clear entrnace and clear path type used. This is still an issue with ride entrances, ride exits and stalls however.

I'm closing this issue, because there's more information about it here: https://github.com/OpenRCT2/OpenRCT2/issues/7042#issuecomment-359256236

**Closed by Broxzier** 2018-03-11 00:11 UTC
Labels: bug
