### ISSUE TITLE
Multiple Enterance Types Selected

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2138] opened 2015-10-26 18:31 UTC
https://openrct.net/cloud/uploads/98f7a672b75bcfa348fd240049e7eb56.sv6

![doubleselection](https://cloud.githubusercontent.com/assets/3945538/10738544/47480966-7bee-11e5-9039-f5ef38ec4828.png)

**Comment by PFCKrutonium** [comment] 2015-10-26 18:33
Upon loading the map it seems like it fixed itself...

**Comment by duncanspumpkin** [comment] 2015-10-26 22:26
It will be caused by the change in dropdown code last week

**Comment by duncanspumpkin** [comment] 2015-11-01 19:56
Fixed in #2176

**Closed by duncanspumpkin** 2015-11-01 19:56 UTC
Labels: bug, interface
