### ISSUE TITLE
Cannot build certain inversions backwards on laydown/flying coasters

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#16728] opened 2022-02-27 12:37 UTC
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (ba85cf4 on develop) provided by GitHub

### Describe the issue

It is not possible to build inline twists and corkscrews backwards on both the lay-down coaster and flying coaster, they simply do not appear in the list of special elements. When building forwards they do appear. 

On other types of coasters is it possible to build inline twists and corkscrews backwards.

### Steps to reproduce

1. Build a lay-down/flying coaster, or open a park that has one half-built (ex. Loopy Landscapes' Dusty Desert scenario).
2. Try to add an inline twist at the end and see it does not appear in the list of special elements.
3. Try to add an inline twist at the beginning and see it does appear in the list. 

### Attachments

Example of Loopy Landscapes' Dusty Desert scenario with this issue:
https://user-images.githubusercontent.com/20048660/155882566-65fda8a8-2af8-4da0-add0-2d37494a2616.mp4

**Comment by e-foley** [comment] 2022-02-28 04:41
Perhaps a duplicate of #7464?

**Closed** 2022-02-28 06:51 UTC
Labels: bug
