### ISSUE TITLE
Lowering land with mountain tool has inconsistent pricing 

### ISSUE THREAD

**Issue by RogoDarius** [OpenRCT2/OpenRCT2#5586] opened 2017-06-10 18:51 UTC
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** 5c5389a

When lowering land with the mountain tool switched on, the cost can vary depending on where in the square the cursor is positioned.

- [No] Reproducible in RCT2 (vanilla)?
- [Yes] Multiplayer?

**Steps to reproduce:**
1. Go to any flat park
2. Go to the land deform tool
3. Press the green slope to turn mountain deformation on
4. Raise one complete square in a flat area one unit upwards
5. Lower one corner of this square from the full square placement (you will lose £160)
6. Put the land back to how it was before lowering it
7. Lower one corner of this square from the corner-square placement appropriate (you will lose £80)

**Screenshots / Video:**
![land](https://user-images.githubusercontent.com/12530301/27005406-1208f606-4e16-11e7-90bf-582f315d3806.PNG)
This was done on Forest Frontiers (a very flat map) as a control, so no other land masses were interfering.

**Comment by IntelOrca** [comment] 2017-06-10 19:08
I think this is duplicate of #2127.

**Comment by Patrik356b** [comment] 2017-06-11 04:47
Just skimming through it, I'd say no but related as the same thing wasn't mentioned.

**Comment by jensj12** [comment] 2017-06-11 12:34
The best solution would be to not use the mountain tool at all when in a money scenario. The pricing has a bug that sawyer fixed by slapping a x4 multiplier on it. Still this looks like a bug I didn't know about yet, so thanks for reporting. It will eventually be fixed.

**Comment by rwjuk** [comment] 2017-06-11 12:45
I think this is a separate issue with the mountain tool, but probably caused by the same issue(s) that cause #2127.

**Comment by jensj12** [comment] 2017-07-30 15:12
Fixed by 0d52030. Both operations now cost 20.

**Closed** 2017-07-30 15:12 UTC
Labels: bug
