### ISSUE TITLE
Underground view does not stay on when constructing roller coaster on ground

### ISSUE THREAD

**Issue by rain1** [OpenRCT2/OpenRCT2#17114] opened 2022-04-30 23:18 UTC
### Operating System

Windows 10, 64-Bit

### OpenRCT2 build

OpenRCT2, v0.4.0 (c6302a1 on master) provided by GitHub

### Describe the issue

When I construct roller coaster on ground and I turn on underground view it automatically turns itself off. I believe it might have something to do with behavior of automatically turning it off when I exit underground which in itself is totally expected behavior. However sometimes when I am above the ground I still want to see what is going on below the ground - for example to coordinate with other rides. For that I want to be able to use underground view.  It does not happen with simple rides that only consists of 1 piece such as merry go round. But it does happen for example when you construct path in a bridge mode but above the ground.

### Steps to reproduce

1. Start constructing roller coaster on ground with custom design
2. Placing new detail in air has better chance to cause bug than placing it directly on ground
3. Place at least 1 piece so that you would see it normally, not with white ghost style but stay in construct mode. Like on added screenshot.
4. Switch to underground view.
5. It will turn off immediately.

### Attachments

![image](https://user-images.githubusercontent.com/1515714/166125388-0410eb34-39b1-4686-9f8e-f2787f354f83.png)
Screenshot or roller coaster being constructed.

**Comment by Broxzier** [comment] 2022-05-01 07:05
Duplicate of #5448 (tracks) and #7353 (paths).

**Closed by Broxzier** 2022-05-01 07:05 UTC
Labels: bug
