### ISSUE TITLE
Handyman stuck in queue when vomit/litter on path nearby

### ISSUE THREAD

**Issue by manuelVo** [OpenRCT2/OpenRCT2#4554] opened 2016-10-07 20:17 UTC
**OS:** Arch Linux
**Version:** 0.0.5
**Commit/Build:** 5a77355

Whenever a visitor vomits on a path near a queue in which a handyman is walking right now there is a chance of the handyman getting stuck inside the queue (the handyman will walk back and forth near the vomit).

The Handyman in the Screenshot will try to reach the marked litter because it's close. Moving towards the vomit will not be done via actual path finding but rather via just walking into the general direction. This will cause the handyman in the screenshot to turn around shortly after taking the screenshot rather than leaving the queue. You can observe this in the attached save file. The marked handyman is handyman number 16.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a queue alongside a normal path
2. Assign a handymans patrol area to the queue and the path
3. Have a visitor vomit on the path while the handyman is inside the queue
OR
1. Load the attached save game
2. Spot handyman number 16 and watch him being stuck

**Screenshots / Video:**
![handyman_stuck_queue](https://cloud.githubusercontent.com/assets/1705157/19204013/ba20bd9a-8cda-11e6-9900-50bad4f1e442.png)

**Save game:**
[handyman_stuck_in_queue.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/517042/handyman_stuck_in_queue.sv6.zip)

**Comment by duncanspumpkin** [comment] 2016-10-07 23:57
This is a duplicate of an original bug.

**Closed by duncanspumpkin** 2016-10-07 23:57 UTC
