### ISSUE TITLE
Building "Vertikale Schleife" causes crashing of the game

### ISSUE THREAD

**Issue by babbochabbo** [OpenRCT2/OpenRCT2#3883] opened 2016-06-15 18:51 UTC
[Fill in the placeholders below. Delete any headings and placeholders that you do not fill in. Delete this line as well]

**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 31812a0

+++Edit+++
Stable release 0.0.4 also crashes.

Game crashes everytime during creating a "Vertikale Schleife" in my a track of the ride "Spiral-Achterbahn" (see Screenshot down below)

**Steps to reproduce:**
1. Start building a track of "Spiral-Achterbahn"
2. Building the part "Vertikale Schleife"

**Dump file**
[1bb3b739-ca18-4764-b6a4-d458cf48ccc7(31812a0).zip](https://github.com/OpenRCT2/OpenRCT2/files/316929/1bb3b739-ca18-4764-b6a4-d458cf48ccc7.31812a0.zip)

**Screenshots / Video:**
![rctcrash](https://cloud.githubusercontent.com/assets/19958739/16092974/43c16518-333a-11e6-94a1-bffedee7dd8d.png)

**Save game:**
[1bb3b739-ca18-4764-b6a4-d458cf48ccc7.zip](https://github.com/OpenRCT2/OpenRCT2/files/316930/1bb3b739-ca18-4764-b6a4-d458cf48ccc7.zip)

**Comment by Wirlie** [comment] 2016-06-15 19:27
Duplicate of #3564, again...

**Closed** 2016-06-15 19:36 UTC
