### ISSUE TITLE
The Object Selection Tool starts to act weird when attempting to select objects for scenarios and saved games

### ISSUE THREAD

**Issue by RT12Productions** [OpenRCT2/OpenRCT2#8500] opened 2018-12-19 23:27 UTC
**OS:** Windows 10
**Version:**  0.2.1
**Commit/Build:** develop 7568123

I notice that, when I try to switch and replace objects with the Object Selection Tool (either while I'm playing a saved game **or** building a scenario), it has started to act weird (it would show something like **?** or **??** within the Text Search Bar of the Object Selection Tool), thus—making it **UTTERLY IMPOSSIBLE** to replace or to select new or replacement objects!  Has it done this with your setups?!?!  What could it be?!?!

**Comment by deurklink** [comment] 2018-12-20 03:05
Duplicate of #8484

**Closed** 2018-12-20 06:20 UTC
