### ISSUE TITLE
Workers wandering around off their paths

### ISSUE THREAD

**Issue by Laz45** [OpenRCT2/OpenRCT2#1620] opened 2015-07-15 05:03 UTC
Is anybody experiencing this bug? I was playing in Great Wall of China with build 999 and placed a couple of workers (police, entertainers, handyman, etc) around the paths and 5-10 mins later most of them are walking through the forest just wondering around. I've tested it twice.
![issue](https://cloud.githubusercontent.com/assets/13055170/8691149/366d7e6c-2a8d-11e5-929a-505917d92371.png)

**Comment by daihakken** [comment] 2015-07-16 10:00
Experienced this bug from build 1007 (OpenRCT2.com).

**Comment by Laz45** [comment] 2015-07-16 20:53
So I did more testing! Downloaded build 1010 and redid the scenario but this time just had workers, LOTS! and the issue arises when I go build anything that has a blueprint or in the game a whiteprint? the paths actually try to connect to the exits and entrances without me even planting the ride down yet and the workers think there's a path there? 
![issue2](https://cloud.githubusercontent.com/assets/13055170/8734914/35e72958-2bdb-11e5-8db8-ad13204a30b6.png)

**Comment by duncanspumpkin** [comment] 2015-07-16 21:11
We call the white thing a ghost. This is quite an interesting bug. Does it not happen on stable (0.0.2)?

**Comment by Laz45** [comment] 2015-07-16 21:29
On stable it acts correctly the only issue is or maybe its normal? If I put the ghosts exit on a path,  workers will try to enter and as they turn to enter the exit I move the ghost and the workers will continue to walk towards it onto the grass and then get lost.

**Comment by daihakken** [comment] 2015-07-19 07:38
Experienced this bug again, but this time is different: a path suddenly connect to a slope nearby, causing staffs to roaming through the slope. Re-loading the game and the connected path disappeared, the staffs did't roam again.

**Comment by daihakken** [comment] 2015-07-19 08:02
![capture](https://cloud.githubusercontent.com/assets/13048125/8765094/75843ad2-2e2f-11e5-873c-fda5d1aee3cb.PNG)
The cause of this bug: the invalid connection between paths

**Comment by duncanspumpkin** [comment] 2015-07-19 09:01
@daihakken i don't think that issue is connected. I worked out what is causing that footpath connection bug and fixed it in the latest build.

**Comment by duncanspumpkin** [comment] 2015-07-19 09:08
I can actually reproduce this on the original game. Staff when they see a gap in a path connection can always walk across even when there is no path due to ghosts. I think we can fix this in the peep ai eventually though.

**Comment by daihakken** [comment] 2015-07-19 10:11
Thanks for clarifying it, but I didn't experienced in the vanilla game, so please bear my ignorance.

**Comment by duncanspumpkin** [comment] 2016-09-28 18:18
Fixed by #4024

**Closed by duncanspumpkin** 2016-09-28 18:18 UTC
Labels: original bug
