### ISSUE TITLE
Random Crash in Scenario Editor

### ISSUE THREAD

**Issue by Generalcamo** [OpenRCT2/OpenRCT2#4076] opened 2016-07-14 01:50 UTC
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** b6b8ce1

I get this crash while selecting rides and scenery in the Scenario Editor. I was able to reproduce it several times, I attached the latest dump and save game.
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Go into scenario editor
2. Get crash while selecting rides and scenery 

Exact cause unknown

**Dump file**
[53d25b5d-5186-4efe-996f-bbb96a1500ba(b6b8ce1).txt](https://github.com/OpenRCT2/OpenRCT2/files/362872/53d25b5d-5186-4efe-996f-bbb96a1500ba.b6b8ce1.txt)

Change extension to .dmp

**Save game:**
[53d25b5d-5186-4efe-996f-bbb96a1500ba.txt](https://github.com/OpenRCT2/OpenRCT2/files/362871/53d25b5d-5186-4efe-996f-bbb96a1500ba.txt)

Change extension to .sv6

**Comment by jensj12** [comment] 2016-07-14 14:02
Duplicate of #4070?

**Comment by Nubbie** [comment] 2016-07-14 14:51
Not a dupe
**To Devs;**
This is what I got from the dumpfile OP gave out called 53d25b5d-5186-4efe-996f-bbb96a1500bab6b8ce1.dmp


**Error message:** 
Unhandled exception at 0x5CE24C3E (openrct2.dll) in 53d25b5d-5186-4efe-996f-bbb96a1500bab6b8ce1.dmp: 0xC0000005: Access violation reading location 0x0A58DA1F.

**Call Stack:**
```
>	openrct2.dll!SoftwareDrawingContext::FillRect(unsigned int colour, int left, int top, int right, int bottom) Line 903	C++
 	openrct2.dll!window_draw_widgets(rct_window * w=0x5d352668, rct_drawpixelinfo * dpi=0x000cfdc0) Line 1612	C
 	openrct2.dll!window_editor_object_selection_paint(rct_window * w=0x5d352668, rct_drawpixelinfo * dpi=0x000cfdc0) Line 1231	C
 	openrct2.dll!window_draw_single(rct_drawpixelinfo * dpi, rct_window * w=0x5d352668, int left=384, int top=192, int right=1152, int bottom=704) Line 1591	C
 	openrct2.dll!window_draw(rct_drawpixelinfo * dpi=0x000cfe28, rct_window * w=0x5d3521a0, int left=384, int top=192, int right=1152, int bottom=704) Line 1485	C
 	openrct2.dll!window_draw_all(rct_drawpixelinfo * dpi, short left, short top, short right, short bottom=704) Line 200	C
 	openrct2.dll!SoftwareDrawingEngine::DrawDirtyBlocks(unsigned int x=9, unsigned int y=3, unsigned int columns=6, unsigned int rows=8) Line 617	C++
 	openrct2.dll!SoftwareDrawingEngine::DrawAllDirtyBlocks() Line 586	C++
 	openrct2.dll!SoftwareDrawingEngine::Draw() Line 374	C++
 	openrct2.dll!openrct2_loop(...) Line 425	C
 	openrct2.dll!openrct2_launch(...) Line 326	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x015e5c02, int nCmdShow=10) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Locals:**
```
		this	Variable is optimized away and not available.	
		bottom	Variable is optimized away and not available.	
		colour	Variable is optimized away and not available.	
		crossPattern	0	unsigned short
+		dpi	0x000cfdc0 {bits=0x0a30b1a0 <Error reading characters of string.> x=384 y=192 ...}	rct_drawpixelinfo *
		dst	Variable is optimized away and not available.	
+		dst	0x0a321c95 <Error reading characters of string.>	unsigned char *
		dst	Variable is optimized away and not available.	
		dst	Variable is optimized away and not available.	
		endX	Variable is optimized away and not available.	
		endY	Variable is optimized away and not available.	
		esi	Variable is optimized away and not available.	
+		g1Bits	0x0a58d9d6 <Error reading characters of string.>	unsigned char *
		height	Variable is optimized away and not available.	
		i	0	int
		j	1	int
		left	Variable is optimized away and not available.	
		nextdst	Variable is optimized away and not available.	
+		nextdst	0x0a3222d4 <Error reading characters of string.>	unsigned char *
		nextdst	Variable is optimized away and not available.	
		numLines	400	int
		numPixels	Variable is optimized away and not available.	
		p	Variable is optimized away and not available.	
		pattern	Variable is optimized away and not available.	
		patternsrc	Variable is optimized away and not available.	
		patternX	Variable is optimized away and not available.	
		patternY	Variable is optimized away and not available.	
		right	Variable is optimized away and not available.	
		startX	116	int
		startY	58	int
		top	Variable is optimized away and not available.	
		width	600	int
```

**Closed** 2018-06-01 11:35 UTC
Labels: expired
