### ISSUE TITLE
Building paths that would automatically remove fences desyncs

### ISSUE THREAD

**Issue by srett** [OpenRCT2/OpenRCT2#5459] opened 2017-05-09 20:34 UTC
**OS:** All
**Commit/Build:** 8d7fa07cbae288ffc453c5f7c106d2a47b6a417b

Building a path using the second path building option (not point and drag) will remove fences locally but not on the server. Since this is stupid to put into words, look at this screenshot
![2017-05-09-221945_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11955902/25871308/5b748170-3507-11e7-813b-aded0b8e698b.png)
: Right hand side is the client that built the path, left is server's view.
Starting point of building the path was the existing gray path, the black one was newly built.

- [v] Multiplayer?

**Steps to reproduce:**
1. Build Path
2. ?
3. DESYNC

**Comment by Margen67** [comment] 2017-05-09 20:37
#3852

**Comment by srett** [comment] 2017-05-09 20:47
Ah well, that existing issue even has nice moving images explaining the issue further. Btw. I tested on abad7dd mentioned in the previous issue, and it's broken there too, so no regression but was never fixed.

**Comment by rwjuk** [comment] 2017-05-09 20:58
Closing as a duplicate of #3852.

**Closed by rwjuk** 2017-05-09 20:58 UTC

**Comment by janisozaur** [comment] 2017-05-10 19:09
For archival purposes, here's a bit of information provided on [reddit](https://www.reddit.com/r/openrct2/comments/6a1o6q/trying_to_hunt_down_network_desync/):

> You have to use the second option of building paths (not point and drag). What happens is the client building the path removes the fence locally, creating a connected path, while on the server the fence remains so the new path is separated.
> Building a path in the marked spot immediately triggers a desync, every time

[desync2.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/990950/desync2.sv6.txt)
![desync2a](https://cloud.githubusercontent.com/assets/550290/25916450/f1e73892-35c4-11e7-8419-5701a22fc178.png)
![desync2b](https://cloud.githubusercontent.com/assets/550290/25916453/f3db2596-35c4-11e7-89fa-d2128b58dc0d.png)
![desync2c](https://cloud.githubusercontent.com/assets/550290/25916455/f5cb5218-35c4-11e7-903f-4184edba7312.png)
