### ISSUE TITLE
Suggestions: Seasons in RCT2

### ISSUE THREAD

**Issue by harrysbird** [OpenRCT2/OpenRCT2#14659] opened 2021-05-14 22:38 UTC
It's would be great to have Seasons on the RCT2 just like changing grass color and tree, weather climate and temperature rising and lower

Seasons:

- Fall = Tree and grass changing to orange and rainy and thunderstorm weather. Min: 10 to 15C Temperature
- Winter = No Leaf in Tree, Grass and Flowers will not grow weeds and snowy and blizzard weather Min: -5 to 1C Temperature, Park might force to close depending on snowy weather.
- Spring = Tree Leaf will come back and weeds will grow in grass Min: 10 to 20C Temperature
- Summer = Very Hot Summer Weather sunny and shower Min: 20 to 35C temperature

You can change the seasons settings in the options menu.

- Change Month before next seasons.
- Enable or Disable Seasons.
- Changing Min and Max Temperature on select seasons.

**Comment by tupaschoal** [comment] 2021-05-14 22:41
The game already skips some months and I think this is to be "thematic", as parks usually close on winters (?). So I'm not sure how players would feel about that.

Note that we do have the weathers and blizzard is already something we introduced.

**Comment by Gymnasiast** [comment] 2021-05-15 14:51
You already made an issue for this (https://github.com/OpenRCT2/OpenRCT2/issues/5499), which we told you was a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/1634. Check before you create an issue please.

**Closed by Gymnasiast** 2021-05-15 14:51 UTC
