### ISSUE TITLE
Recent messages window stops updating after being opened once and 6+ messages present

### ISSUE THREAD

**Issue by SevenChords** [OpenRCT2/OpenRCT2#14775] opened 2021-05-28 16:48 UTC
**OS:** macOS 10.15.7
**Commit/Build:** 4c1ab8d

once the Recent Messages window (default hotkey M) has been opened at least once **and** st least 6 messages are present, it wont fetch any newly appearing messages into the Recent Messages window.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. load any scenario (new or save file)
2. open the Recent Messages Window (default hotkey M)
3. wait for at least 6 messages to appear
4. open the Recent Messages window again at any later point, all messages after steps 2 & 3 wont appear in the Recent Messages window

**Comment by James103** [comment] 2021-05-28 16:50
Related to #14674

**Comment by SevenChords** [comment] 2021-05-28 16:54
> Related to #14674

i have had a lot more than 7 messages working correctly, for me it always stopped recording new messages after at least 6 messages and opening the messages window for the first time.

if i open the recent messages window after about 20 messages for the first time ever since starting that park, i can see all those 20 messages correctly, but from that point onward no new messages would be recorded.

**Comment by Gymnasiast** [comment] 2021-05-28 17:46
I still think this is the same issue as #14674.

**Comment by Gymnasiast** [comment] 2021-07-31 17:23
Closing this as duplicate of #14674.

**Closed by Gymnasiast** 2021-07-31 17:23 UTC
Labels: duplicate
