### ISSUE TITLE
Only 1 Wooder Coaster Train Type when more types are checked in object selection

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#4091] opened 2016-07-15 02:25 UTC
**OS:Windows 7 Home Premium SP1 x64**
**Version: 0.0.5-11**
**Commit/Build 097c5b1:**
Hey. I am hosting a server and someone requested me to add 6 seater to the park which already is, but the train type is absent when selecting a train type.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Select many Wooden Coaster train types as you can
2. Build a Wooden Coaster
3. Check to see if there is only one when many are selected in object selection.

![gitbugrct](https://cloud.githubusercontent.com/assets/17324259/16861763/c93573f4-4a11-11e6-8d91-7afdd24041b7.png)

**Comment by Wirlie** [comment] 2016-07-15 02:51
I can confirm this issue :
![scr1](https://cloud.githubusercontent.com/assets/7508197/16862106/9d12d6ea-4a0c-11e6-8049-b858cde5ef9d.png)

**Comment by Gymnasiast** [comment] 2016-07-15 07:45
Duplicate of #3806.

**Closed by Gymnasiast** 2016-07-15 07:45 UTC
