### ISSUE TITLE
OS X: In-game textfield doesn't show active dead key

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2765] opened 2016-01-17 23:39 UTC
When pressing a dead key, usually the active symbol appears with a yellow background, allowing you to see a dead key is active and what effect it will have.
![image](https://cloud.githubusercontent.com/assets/737603/12380802/d3a7d61a-bd7b-11e5-8cb2-91d314d26830.png) ![image](https://cloud.githubusercontent.com/assets/737603/12380773/49707f2e-bd7b-11e5-9d93-fc17f9638bf5.png) ![image](https://cloud.githubusercontent.com/assets/737603/12380776/51f562ae-bd7b-11e5-8e78-676a2bf8df2c.png)

Currently dead keys do work in RCT, but you can't see they're active.

**Comment by IntelOrca** [comment] 2016-01-17 23:40
What is a dead key? Are you talking about IME composition?

**Comment by marijnvdwerf** [comment] 2016-01-17 23:47
For Latin languages, you can use accents for letters, like üïöëä. In Windows you can press the `"` key, and nothing will appear. When you press a vowel, it turns into the accented version. If you press space or another key, the regular symbol will appear. On a Mac `alt+e` is used to trigger the dead sequence. The difference between the two OS'es is that OS X actually indicates that such a sequence is taking place, by marking the symbol, whereas Windows just won't show it.

This probably won't apply to 'normal' English keyboard layouts though.

**Comment by IntelOrca** [comment] 2016-01-17 23:51
I think this is a duplicate of #2608

**Comment by marijnvdwerf** [comment] 2016-01-17 23:55
Might not be the same, but definitely similar enough to be marked as a duplicate

**Closed** 2016-01-17 23:59 UTC
