### ISSUE TITLE
[Hybrid Coaster][Track Designer] Cannot save my custom designs

### ISSUE THREAD

**Issue by NobbiHabogs** [OpenRCT2/OpenRCT2#21000] opened 2023-11-21 12:31 UTC
### Operating System

Windows 10 Pro, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.6 (b40b5da) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

I build my coaster as usual but if i try to save the design the game shows me a red error box.
When i just build a very short track it works, so it is possible to build some track pieces that cannot be saved into a pre-build.
You can see the coaster i build in the attachments

### Steps to reproduce

1. Open Track-Designer
2. Build a fancy Hybrid Coaster
3. Try to save it

### Attachments

![Unbenannt](https://github.com/OpenRCT2/OpenRCT2/assets/151637624/30c517eb-c396-4b43-9c55-5b5c2e8c79e4)

**Comment by NobbiHabogs** [comment] 2023-11-21 14:37
I tested a bit now and found out, that following track pieces causing this problem:
(track pieces are defined as: straight, wide turn, normal turn, tight turn)

- both "zero-g rolls", the small and big one
- wide banked steep turn
- wide unbanked steep turn

**Comment by ZehMatt** [comment] 2023-11-21 14:49
The issue is that the track file format doesn't support the new things we added, switching to a better format has been a discussion for quite some time now but there is currently no progress on that.

Closing this as its most likely a duplicate, there are a few issues for this already.

**Closed by ZehMatt** 2023-11-21 14:49 UTC
Labels: bug
