### ISSUE TITLE
Cursor appears outside of text box in Track Designer and Track Designs Manager

### ISSUE THREAD

**Issue by Alex20509** [OpenRCT2/OpenRCT2#13173] opened 2020-10-12 16:33 UTC
Windows x86
0.3.1 Release
d01dcea

While typing in a ride type in Track Design and Track Designs Manager, the cursor dash appears out of the text box.
Most of the time it's above the text box; but sometimes it's below.

How to Reproduce
1. Open Track Designer or Track Designs Manager (This can be done from the Toolbox icon in the main menu)
2. Type anything in the ride type selection text box.

![image](https://user-images.githubusercontent.com/72755593/95770211-5b966c80-0cb9-11eb-8bc0-bf9d1242577a.png)
![Cursor_Bug](https://user-images.githubusercontent.com/72755593/95770227-60f3b700-0cb9-11eb-9af5-e7d272bdbf42.png)

**Comment by AaronVanGeffen** [comment] 2020-10-12 18:13
Duplicate of #13158

**Closed by AaronVanGeffen** 2020-10-12 18:13 UTC
