### ISSUE TITLE
Regression: crash in native code on saving park

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3514] opened 2016-05-07 12:16 UTC
**OS:** Linux
**Version:** 0.0.5-develop
**Commit:** 355b163

Load attached save game, try saving it, observe crash on address: 0x6e023e.

This park used to load correctly, as it was used as a prime candidate for https://github.com/OpenRCT2/OpenRCT2/pull/2983

**Save game:**
[Circus Circus & Adventuredome Atlantic City - Roof On [Open First].SV6.txt](https://github.com/OpenRCT2/OpenRCT2/files/253412/Circus.Circus.Adventuredome.Atlantic.City.-.Roof.On.Open.First.SV6.txt)

**Comment by IntelOrca** [comment] 2016-05-07 12:23
I can't reproduce this, and I am surprised its getting to 0x6E023E when the only RCT2 code that should run now is drawing related.

**Comment by Wirlie** [comment] 2016-05-07 14:17
I can reproduce this on Windows 10
![sin titulo](https://cloud.githubusercontent.com/assets/7508197/15092545/d7c48514-1432-11e6-9306-0c3cd21de149.png)

**Comment by janisozaur** [comment] 2016-05-07 16:15
it looks like it is crashing with this stack trace:
```
#0  RCT2_CALLPROC_X (address=7208775, _eax=0, _ebx=0, _ecx=3, _edx=144, _esi=16207816, _edi=0, _ebp=0) at /home/janisozaur/workspace/OpenRCT2/src/addresses.c:31
#1  0x01533875 in scenery_paint (direction=3 '\003', height=144, mapElement=0xf74fc8) at /home/janisozaur/workspace/OpenRCT2/src/paint/map_element/scenery.c:22
#2  0x015335ba in sub_68B3FB (x=2016, y=384) at /home/janisozaur/workspace/OpenRCT2/src/paint/map_element/map_element.c:262
#3  0x01533006 in map_element_paint_setup (x=2016, y=384) at /home/janisozaur/workspace/OpenRCT2/src/paint/map_element/map_element.c:65
#4  0x0153b0dd in viewport_paint_setup () at /home/janisozaur/workspace/OpenRCT2/src/paint/paint.c:482
#5  0x0149394e in get_map_coordinates_from_pos (screenX=63922, screenY=1242, flags=-135, x=0xff9469fc, y=0xff9469fe, interactionType=0xff946a30, mapElement=0xff946a3c, viewport=0x0) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:1445
#6  0x014941f4 in viewport_interaction_get_item_left (x=87, y=51, info=0xff946a30) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport_interaction.c:60
#7  0x0149435c in viewport_interaction_left_over (x=87, y=51) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport_interaction.c:112
#8  0x0152c883 in process_mouse_over (x=87, y=51) at /home/janisozaur/workspace/OpenRCT2/src/input.c:1075
#9  0x0152a803 in game_handle_input () at /home/janisozaur/workspace/OpenRCT2/src/input.c:162
#10 0x01543d2d in game_update () at /home/janisozaur/workspace/OpenRCT2/src/game.c:342
#11 0x01547c42 in rct2_update () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:464
#12 0x01531fb0 in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:391
#13 0x01531dfd in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:320
#14 0x014ec7f0 in main (argc=2, argv=0xff946c34) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:60
```

I can reproduce it reliably on one of my machine, the other is immune to this.

**Comment by IntelOrca** [comment] 2016-05-07 16:39
It looks unrelated to saving, although maybe its just that saving the game is corrupting something.

**Comment by janisozaur** [comment] 2016-05-07 16:47
I run bisection on it, it was introduced by e906ab5e95d74fa679eed9752e3033a0c5f88d81

Do note I almost always load saves via commandline, in this case:
`./openrct2 ~/Downloads/150415-rct2-louis-austin55-djbrcace1234-\[h2h7_r1\]_circus_circus_and_adventuredome_atlantic_city/Circus\ Circus\ \&\ Adventuredome\ Atlantic\ City\ -\ Roof\ On\ \[Open\ First\].SV6`

**Comment by IntelOrca** [comment] 2016-05-07 17:23
Duplicate of #3323

**Closed by IntelOrca** 2016-05-07 17:23 UTC
Labels: bug, duplicate
