### ISSUE TITLE
Shops selling all colors.

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#2154] opened 2015-10-28 23:43 UTC
~~I would love a function in the cheats menu to automatically press the "Balloons" button (configurable pace) so that the balloons in everyone's hands change colors every so often. Personally I would love an interval of 0.25 seconds.!~~

**Comment by Patrik356b** [comment] 2015-10-28 23:46
Also: static color but random for every buyer would be a nice option.

Original idea i don't agree with, especially the timing

**Comment by PFCKrutonium** [comment] 2015-10-29 02:55
Actually, I would love to be able to set a balloon stand to sell random colors as well :D

**Comment by pizza2004** [comment] 2015-10-29 04:41
Randomly colored balloons and umbrellas and such would be amazing.

**Comment by PFCKrutonium** [comment] 2015-10-29 09:13
No longer will you need 20 Balloon stands to sell all the colors!

**Comment by delebota** [comment] 2015-10-29 15:58
#1438 refers to adding random color option for balloons and hats

**Comment by Gymnasiast** [comment] 2015-10-29 16:30
I find this quite trivial and overkill, to be honest.

I do like the idea of setting stalls to hand out balloons (and umbrellas, and hats...) of random colours.

**Comment by ThomasdenH** [comment] 2015-10-29 20:52
Yeah, I agree with @Gymnasiast. Flashing balloons is not in the realistic style of RCT2 either.

**Comment by vzybilly** [comment] 2015-10-29 23:15
I would love the paint/color options to include, "random" and "guest color". guest color gives them the color of the guests shirt, as said above.

**Comment by Overv** [comment] 2015-11-01 02:15
The logic that assigns a balloon/umbrella color to a guest when they buy one at the shop hasn't been decompiled yet to my knowledge.

**Comment by IntelOrca** [comment] 2015-11-01 02:24
@Overv it has

**Comment by Overv** [comment] 2015-11-01 02:26
@IntelOrca Where is it? I searched for assignments of the peep.balloon_colour variable, but couldn't find anything.

**Comment by HaasJona** [comment] 2015-11-01 09:05
It should be here I think: https://github.com/HaasJona/OpenRCT2/blob/Fix2138/src/peep/peep.c#L8045-8045 (sorry for referencing my fork, not sure how to fix easily)

**Comment by Overv** [comment] 2015-11-01 12:58
Ah you're right, not sure how I missed that.

**Comment by HaasJona** [comment] 2015-11-19 18:39
Okay, I messed around with this just for fun and I added an option for shops to sell random colours. If you want, I can create a pull request.

However I'm not really happy about the result as most colours (especially browns) look awful on balloons and hats. Maybe it would be a better idea to just unlock some additional colours and let the user choose, maybe 3 or 4 different colours that are chosen randomly. Any ideas?

**Comment by HaasJona** [comment] 2015-11-19 19:36
![scr3](https://cloud.githubusercontent.com/assets/4310707/11281937/25d5704e-8efd-11e5-9fda-8cfbd59f6598.png)

**Comment by Overv** [comment] 2015-11-19 20:44
Nice work!

**Comment by Patrik356b** [comment] 2017-07-20 10:58
One thing that always bothered me is the forced "white and X" umbrellas, it would be nice if we could change both

**Comment by say25** [comment] 2020-08-04 02:41
This is semi-related to https://github.com/OpenRCT2/OpenRCT2/issues/6549 as you would likely desire all shops in the park to behave the same in terms of what "color" they are selling.

**Comment by Gymnasiast** [comment] 2020-12-24 14:10
The "sell all colours" bit is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/1438 . The rest is either already implemented (the balloons cheat already gives out randomised colours) or not really in the spirit of the game (flashing).

**Closed by Gymnasiast** 2020-12-24 14:10 UTC
Labels: feature, user interface
