### ISSUE TITLE
BACKTRACE b07f5c

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8234] opened 2018-11-06 19:33 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/b07f5c30cd61a762c402d58c09c9dc116adc506e0713e770dbf9f6593ffed2f9?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Tue Nov 06 2018 19:33:12)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 223ae74: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guard::Assert_VA -> openrct2_assert_fwd -> peep_go_to_ride_entrance -> peep_find_vehicle_to_enter -> rct_peep::UpdateRideAtEntrance -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-03 07:52
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8178

**Closed by janisozaur** 2019-02-03 07:52 UTC
Labels: backtrace.io, crash
