### ISSUE TITLE
The list for starting a campaign for a specific ride is broken

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2425] opened 2015-12-02 16:21 UTC
It only seems to happen in scenarios and saves with many rides.

![scr85](https://cloud.githubusercontent.com/assets/1478678/11536539/254f51b4-9919-11e5-9b66-361b33ad7ede.png)

**Comment by IntelOrca** [comment] 2015-12-02 17:37
Can I have instructions to re-produce or a saved game?
I can't reproduce this with the vanilla scenarios I tried.

**Comment by Gymnasiast** [comment] 2015-12-02 17:41
Open SF Magic Mountain and put down six extra flat rides. That should trigger the issue.

**Comment by IntelOrca** [comment] 2015-12-02 17:44
Thanks, seems to be when you hit a certain number of rides.

**Comment by IntelOrca** [comment] 2015-12-02 17:50
Fixed in pre-release-0.0.3.1.

**Closed by IntelOrca** 2015-12-02 17:50 UTC
Labels: bug
