### ISSUE TITLE
BACKTRACE b3e3cd DrawRLESprite1<0> -> gfx_rle_sprite_to_buffer

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8352] opened 2018-12-04 01:46 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/b3e3cd88cfae06b2f6eb16a87dea5c5718acd2ced8a9dc404b72b035af751953?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Tue Dec 04 2018 01:46:38)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Nunzi\\Documents\\OpenRCT2\\64e0002a-71b1-4bca-9761-07e485dcd370.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Nunzi\\Documents\\OpenRCT2\\64e0002a-71b1-4bca-9761-07e485dcd370.sv6.gz: <em>1</em><br><strong>commit:</strong> c845924: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>DrawRLESprite1<0> -> gfx_rle_sprite_to_buffer -> gfx_draw_sprite_palette_set_software -> gfx_draw_sprite_software -> gfx_draw_sprite -> paint_draw_struct -> window_guest_overview_paint -> window_draw_single -> window_draw -> window_draw_all -> OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks -> OpenRCT2::Drawing::X8DrawingEngine::PaintWindows -> OpenRCT2::Paint::Painter::Paint -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 20:16
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8471

**Closed by janisozaur** 2019-02-02 20:16 UTC
Labels: backtrace.io, crash
