### ISSUE TITLE
clicking the X on a ride build pane while placing the first piece creates a strange error label

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6393] opened 2017-10-07 05:34 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** b56ad77

https://gfycat.com/IllRadiantCopepod

The message appears if you open a tracked ride build pane then click X, or if you build some pieces then delete all of them and click the X.

**Comment by TyPR124** [comment] 2017-10-07 19:03
I can confirm this happens. Console output:

RideDemolishAction.hpp:57 (RideDemolishAction::Query)]: Invalid game command for ride x

Also, if I start a game, open the track build window, and close it without building anything, the in-game error message is blank. I only see the error message if I place and delete some track before closing the window. After doing this, the error appears every time, even if I do not place any track.

**Comment by ZehMatt** [comment] 2017-10-07 19:18
Can you verify with https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.1.2.10585 if the issue still occurs?

**Comment by TyPR124** [comment] 2017-10-07 19:57
Yes, this still occurs as of 84086a2465f1756381cf8ad6128fc858a9c3d94c

**Comment by ccoors** [comment] 2017-10-07 20:13
This always seems to habben when closing a 'build ride' window, but sometimes the string is empty and it just creates a tiny red box.

**Comment by ZehMatt** [comment] 2017-10-07 20:22
![2017-10-07_22-16-43](https://user-images.githubusercontent.com/5415177/31311495-89358d58-abad-11e7-8e50-c97e47784fd2.gif)

I'm having a hard time reproducing this, am I doing this wrong?

**Comment by ccoors** [comment] 2017-10-07 20:25
Interesting, now I can't reproduce it either. But I definitively had this problem today.

**Comment by TyPR124** [comment] 2017-10-07 20:32
When the track build window closes, it attempts to demolish the ride if it cannot find the rides origin element. I'm investigating, but very unfamiliar with the general game logic so someone else might know a solution before I do.

Since the ride list seems to be a global state, I'm wondering if building a piece of the track causes the next ride to be initialized in the table or something, which then leads to a different error (and if the next ride, or the ride to be demolished, hasn't been initialized yet, then it shows a blank error). This is mostly speculation by me at this point.

@ZehMatt - Don't build anything prior. I think maybe the act of building and demolishing via the ride window UI does something to prevent the bug.

I can reproduce every time by:

1: Launch game
2: Open a new scenario (seems to happen with any scenario, but Electric Fields is one I've specifically tested)
3: "Build" a new miniature railroad, custom design. Do NOT place any pieces.
4: Close the track build window. You should see a blank error
5: Repeat step 3, but this time place a station platform, and then delete it (all within the track build window).
6: Close the track build window. This time you should get "Can't construct this here..."

**Comment by ZehMatt** [comment] 2017-10-07 20:34
I repeated all steps and I can't reproduce it with the latest develop branch build.

**Comment by TyPR124** [comment] 2017-10-07 21:01
Okay, can confirm as of latest I no longer see the issue.

I think I was being dumb and not actually testing 84086a2465f1756381cf8ad6128fc858a9c3d94c as I thought I was. However as of 2d993671 it seems to be fixed. My bad.

**Comment by Gymnasiast** [comment] 2017-10-09 09:07
This bug was posted around the time ZehMatt committed a fix dealing with demolishing rides. I'm going to consider this solved. If it isn't: let me know and I'll open this again.

**Closed by Gymnasiast** 2017-10-09 09:07 UTC
Labels: bug
