### ISSUE TITLE
Default system dialog not accessible from saving landscape window

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#5210] opened 2017-02-11 13:37 UTC
**OS:** Windows 10 x64
**Version:** 0.0.7
**Commit/Build:** 3a13311

**Steps to reproduce:**
1. Open the scenario editor
2. Go to Floppy > Save landscape
3. Click "Use system dialog window"

Result: A system dialog window does not open.

**Comment by grimpunch** [comment] 2017-02-18 16:01
Can you check if this happens still after my changes to Linux.c were merged?

**Comment by Gymnasiast** [comment] 2017-02-18 17:36
He is using Windows 10, so it's not likely that's the issue.

**Comment by Broxzier** [comment] 2017-02-18 21:24
@grimpunch I can confirm your PR has not fixed this issue.

**Comment by Gymnasiast** [comment] 2018-01-02 14:39
Cannot reproduce this on macOS.

Is this still an issue?

**Comment by Broxzier** [comment] 2018-01-03 13:01
Yes, the issue still exists following the exact same steps. I can only test it on Windows 10.

**Closed** 2018-03-24 12:59 UTC
Labels: Windows (OS), investigate
