### ISSUE TITLE
Guests get stuck at the beginning of golf holes D and E permanently

### ISSUE THREAD

**Issue by Kyzer-dev** [OpenRCT2/OpenRCT2#12724] opened 2020-08-19 05:58 UTC
Unknown if being right after a turn is relevant, but I've had it happen multiple times at this point.

**Comment by duncanspumpkin** [comment] 2020-08-19 08:08
Please fill in the template correctly. What version are you on?

**Comment by jensj12** [comment] 2020-08-19 09:41
Is there still another guest on the hole and do they continue after he is finished?

Guests wait at the start of a hole until the previous guest has finished the hole. Since these holes take more time than other, guests might pile up at the start of these holes.
A guest is allowed to enter the course if the last guest has finished the first hole. If the first hole is a short hole directly at the start, guests will get stuck at D/E holes later in the course. As far as I've tested (`8d141fa`), this is still the case and guests won't get stuck otherwise.

**Comment by Gymnasiast** [comment] 2021-04-30 19:20
Since there is no version specified, no affected save and not reproduced by @jensj12 , I'm closing this.

**Closed by Gymnasiast** 2021-04-30 19:20 UTC
Labels: invalid/incomplete, investigate
