### ISSUE TITLE
Scenery items are not removed when building paths on them

### ISSUE THREAD

**Issue by andy55699** [OpenRCT2/OpenRCT2#15921] opened 2021-11-16 17:55 UTC
### Operating System

Windows 10,64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5 (b9bc8d0) provided by GitHub

### Describe the issue

When building paths across some small scenery items such as shrubs, some of the scenery items are not removed automatically as normal. 

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Building paths across some small scenery items such as shrubs.
2. Some of the scenery items still stays.
![Shrub bug 2021-11-17 01-35-15](https://user-images.githubusercontent.com/92691705/142039634-777f8972-b004-473c-b41c-07cd7a509919.png)

### Attachments

Saved file. 

[Shrub bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/7548703/Shrub.bug.zip)
)

**Comment by Broxzier** [comment] 2021-11-16 18:08
This appears to be a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/15138.

**Closed by Broxzier** 2021-11-16 18:08 UTC
Labels: bug
