### ISSUE TITLE
Trains collide on different parts of track even though they're built without ZC

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#7978] opened 2018-09-08 16:49 UTC
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** a5cbcb4

Sometimes when you build two track pieces in a certain way, trains can collide with each other if they happen to be on the two track pieces at the same time. An example is medium banked turns through a looping. This coaster was built without zero clearance, yet the blue and yellow trains are about to collide. 
![image](https://user-images.githubusercontent.com/25930360/45256460-f9126a00-b396-11e8-95cc-131b0f00d674.png)
Another example is this, where the red train is about to collide with the blue train. The yellow spiral starts 1.5 meters above the station and ends 3 meters above it.
![image](https://user-images.githubusercontent.com/25930360/45256505-7342ee80-b397-11e8-8548-2465b8241e12.png)
I've included the save files if you want to see it happen for yourself.

- [x] Reproducible in RCT2 (vanilla)?

**Steps to reproduce:**
1. Open the save files and wait until the trains collide.

**Save game**
[save.zip](https://github.com/OpenRCT2/OpenRCT2/files/2363498/save.zip)

**Comment by jensj12** [comment] 2018-09-09 19:05
Duplicate of #3830

**Closed** 2018-09-09 21:07 UTC
Labels: duplicate, original bug
