### ISSUE TITLE
Ride name is displayed incorrectly in ride list

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#7532] opened 2018-05-16 17:34 UTC
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** 94f005a

Some ride's name is displayed incorrectly in ride list window.
I had thought that it was about language, but it wasn't. This issue is occured in english, too.

In below screenshot, 24 is _Go Karts 1_ that I opened

**Screenshots / Video:**
In korean:
![image](https://user-images.githubusercontent.com/10726524/40133211-09489fba-597a-11e8-8b7a-4582659ec36a.png)

In english:
![image](https://user-images.githubusercontent.com/10726524/40133386-8538cb4a-597a-11e8-801c-c7ca42fa341c.png)

**Comment by AaronVanGeffen** [comment] 2018-05-16 19:56
Duplicate of #7454.

**Closed** 2018-05-19 08:29 UTC
Labels: bug
