### ISSUE TITLE
Cannot save game from older save files.

### ISSUE THREAD

**Issue by MadeInDutch** [OpenRCT2/OpenRCT2#15018] opened 2021-07-17 00:14 UTC
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 3f65f28

Basically, any older save files I have (made in older versions and imported from my old laptop) are not saveable, although I can load the existing save files. Any save files I make in the current release save and load just fine.

- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Specific to multiplayer? No

**Steps to reproduce:**
1. Load included save file.
2. Try saving said save file.

**Dump file**
---

**Screenshots / Video:**
![resim](https://user-images.githubusercontent.com/67276601/126019251-18277720-c958-44bc-8824-d2851be27796.png)

**Save game:**
[honkbox error save.zip](https://github.com/OpenRCT2/OpenRCT2/files/6833866/honkbox.error.save.zip)

**Comment by MadeInDutch** [comment] 2022-04-10 21:29
Is anyone working on this I still have this problem?

**Comment by IntelOrca** [comment] 2022-04-10 23:45
I can not reproduce this on the latest develop version.

**Comment by janisozaur** [comment] 2022-04-11 05:29
Same here - cannot reproduce. Check if you can save it as a different file, perhaps the one you are trying to overwrite is marked as RO? We fail to notify user about that and present them with generic error instead.

**Comment by MadeInDutch** [comment] 2022-04-11 07:32
Thanks, that does actually work. But what does RO mean?

**Comment by spacek531** [comment] 2022-04-11 07:34
Read-Only

**Comment by MadeInDutch** [comment] 2022-04-11 07:41
Ahh, I see.

**Closed** 2022-04-11 16:50 UTC
Labels: investigate
