### ISSUE TITLE
Memory/savegame corruption when saving games with certain characters in scenerio description

### ISSUE THREAD

**Issue by RRvW** [OpenRCT2/OpenRCT2#15888] opened 2021-11-10 18:37 UTC
### Operating System

Linux, Nixos x86-64

### OpenRCT2 build

OpenRCT2, v0.3.5

### Describe the issue

I first encountered this issue when playing the "Fun at the Beach" scenario from Wacky Worlds. At some point, the scenario description in the objectives tab of the park window had the apostrophe replaced by some spaces and garbage characters: ![after one save/load cycle](https://user-images.githubusercontent.com/1765691/141171139-f28e0fe0-8b19-43d7-9ba9-45257610a1cc.png)
(Original text: "A local entrepreneur's sealife park")

As my playthrough progessed, I noticed that the number of space & garbage characters where increasing, to the point where it overflowed the window. Eventually opening that tab crashed the game. 
At first i could not reproduce this issue, and thought it was caused by upgrading from 0.3.4.1 to 0.3.5. However, loading the same save in version 0.3.3 produced the same results.

It turns out that every time the scenario is saved and reloaded, the amount of garbage data increases in the dialog. Scenarios I could reproduce this bug:
 - Fun at the Beach
 - Extreme Hawaiian Island
 - Rock 'n' Roll

In both cases, the apostrophe is being replaced. I could not reproduce this in the "Cradle of Civilization" scenario, even though it also has the symbol in the description 

### Steps to reproduce

1. load one the scenarios listed above
2. save the game
3. exit to menu
4. load the same savefile
5. open the objectives tab (I always click on the guest counter, and then the trophy icon)
6. observe that text has changed 
7. repeat steps 2-6 for more garbage

### Attachments

![many cycles](https://user-images.githubusercontent.com/1765691/141169775-e02d68ab-c463-46f1-b5cb-4bd660cb5655.png)

**Comment by Gymnasiast** [comment] 2021-11-10 21:44
This appears to be a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/15571.

**Closed by Gymnasiast** 2021-11-10 21:44 UTC
Labels: bug
