### ISSUE TITLE
Cannot pause/unpause the game while interface is hidden

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#9133] opened 2019-04-22 21:06 UTC
When I hide the interface, the keyboard shortcut I have for pausing/unpausing the game stops working. It works fine again when the interface is visible again.

Using version 0.2.2 462bafc on windows 8.

**Comment by Gymnasiast** [comment] 2019-04-22 21:14
It's a technical limitation, since the shortcut in question is handled by the toolbar window (yes, the toolbar is technically just another window).

It's not impossible to change, though, but not an easy fix.

**Comment by Liampie** [comment] 2019-04-22 22:39
Interesting. How come other shortcuts like rotating the view or zooming in and out still work? They usually go through the toolbar too.

**Comment by AaronVanGeffen** [comment] 2024-07-20 18:59
Does this still happen?

**Comment by AaronVanGeffen** [comment] 2024-07-30 20:16
Confirmed this was fixed by #21343.

**Closed by AaronVanGeffen** 2024-07-30 20:16 UTC
Labels: enhancement
