### ISSUE TITLE
Can't place any path

### ISSUE THREAD

**Issue by austinjb555** [OpenRCT2/OpenRCT2#1619] opened 2015-07-15 01:28 UTC
![scr5](https://cloud.githubusercontent.com/assets/12687508/8688872/19c91dac-2a6f-11e5-86fb-a5373a664dfe.png)
Both buttons on the bottom of the footpath window depress when clicked but do not stay depressed once the mouse button is released.

**Comment by duncanspumpkin** [comment] 2015-07-15 17:18
Any steps to reproduce?

**Comment by IntelOrca** [comment] 2015-07-15 17:26
I can't reproduce this.

**Comment by Gymnasiast** [comment] 2015-07-15 17:48
I vaguely recall something like this in an old build, so I guess it will be something like that.

**Comment by austinjb555** [comment] 2015-07-16 01:43
It actually has resolved itself. I wasn't doing anything out of the ordinary, just building rides, and it wouldn't let me build path. It resolved when I closed the window and reloaded OpenRCT2.

**Comment by Gymnasiast** [comment] 2015-07-25 14:13
Just had this again. It also affected the Clear Scenery tool. I'm not sure how to reproduce it yet, though.

**Comment by sjoerddebruin** [comment] 2015-07-25 14:42
I've also had this issue, don't know what causes it.

**Comment by IntelOrca** [comment] 2015-07-25 16:43
A similar issue, possible the same same is caused by placing the Splash Mine log flume track. The queue path is not completed connected.

**Comment by PFCKrutonium** [comment] 2015-07-25 23:44
I had this happen about 20 minutes ago, and I have no idea how to re-produce.

**Comment by austinjb555** [comment] 2015-07-29 04:08
I agree. This is happening randomly and resolving itself when you reload the scenario.

**Comment by jensj12** [comment] 2015-08-27 10:19
It has happened to me a few times too. Fixed by building a station section of a new coaster with entrance and exit. After that it worked again. Last time it happened was after removing a ride entrance, but that doesn't reproduce it. It affects every tool that lets you place something (as far as I've tested), but not the build entrace/exit tool.

**Comment by Bouncer** [comment] 2015-10-03 15:24
I've also had this bug occur many times. I think it is related to the fact that when you select the "bridge and tunnel footpath" button in the "Footpaths" window, the button gets deselected after constructing a path. However, I've not been able to reproduce the bug.

**Comment by IntelOrca** [comment] 2015-10-03 15:25
We won't get any closer to fixing this until there we know the set of steps necessary to reproduce this reliably.

**Comment by PFCKrutonium** [comment] 2015-10-04 15:40
I've been streaming a lot lately @IntelOrca - if I have it occur while on Stream I'll upload the Stream to YouTube and link it here for you guys to analyse.

**Comment by duncanspumpkin** [comment] 2015-11-15 17:42
Has anyone been able to reproduce this recently?

**Comment by PFCKrutonium** [comment] 2015-11-17 17:29
I had it happen a couple weeks ago, but I havn't had it happen in a while now.

**Comment by Broxzier** [comment] 2015-11-28 14:23
I had this happen yesterday, and within only a minute of gameplay. I haven't been able to reproduce this yet though. All I remember is picking up someone, zooming out and moving the view around, and while having the person still picked up opening a tool.

**Comment by IntelOrca** [comment] 2015-12-21 22:04
Just happened to me for the first time. Literally just went straight into scenario editor and tried to own some land.

**Observation:** It displays the map size label when trying to own land. Usually this gets hidden.

![image](https://cloud.githubusercontent.com/assets/1482259/11942464/a7dc955a-a82e-11e5-9c4c-71cde6f3160e.png)

**Comment by duncanspumpkin** [comment] 2015-12-21 22:26
Yup can confirm. Technique to reproduce is open a window with a scroll bar click on scroll bar. Open a tool window. It will now be broken. To fix click on the main part of the scrollable window.

**Comment by IntelOrca** [comment] 2015-12-21 22:28
AND FIXED!

**Closed** 2015-12-21 22:28 UTC
Labels: bug

**Comment by LinusU** [comment] 2015-12-21 22:30
Awesome :clap: :clap:
