### ISSUE TITLE
RCTdeluxe_install is not reorganized

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#7022] opened 2018-01-13 21:05 UTC
Currently, OpenRCT2 not using files from the steamapps/common/RollerCoaster Tycoon Deluxe/RCTdeluxe_install what means that things like the new introduced rct1 edge styles don't work. (the csg1i.dat is therefore needed).
so please add support for the RCTdeluxe_install directory for the steam version.

**Comment by IntelOrca** [comment] 2018-01-13 21:09
Duplicate of #5809

**Closed** 2018-01-13 21:09 UTC
