### ISSUE TITLE
Arch Linux crash

### ISSUE THREAD

**Issue by PureTryOut** [OpenRCT2/OpenRCT2#1872] opened 2015-09-01 20:31 UTC
Since yesterday, OpenRCT2 crashes on startup.

Wine crash log:
```
Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x7bc52106).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7bc52106 ESP:0032f3f0 EBP:0032f428 EFLAGS:00210202(  R- --  I   - - - )
 EAX:00000000 EBX:7bceb000 ECX:00000000 EDX:016e0638
 ESI:0032f4b0 EDI:015d0080
Stack dump:
0x0032f3f0:  ffffffff 0032f418 016e0588 00000000
0x0032f400:  7b8ca000 015d0000 0032f430 016e0638
0x0032f410:  7bceb000 0032f4c0 016355b8 94e75600
0x0032f420:  0032f440 7bceb000 0032f498 7bc534ef
0x0032f430:  7bc51526 016e0590 0032f498 7bc534ef
0x0032f440:  00000000 016e0588 00000098 016e0588
Backtrace:
=>0 0x7bc52106 in ntdll (+0x42106) (0x0032f428)
  1 0x7bc534ef in ntdll (+0x434ee) (0x0032f498)
  2 0x7bc55bd8 RtlReAllocateHeap+0x2d0() in ntdll (0x0032f538)
  3 0x7e163b44 in msvcrt (+0x33b43) (0x0032f598)
  4 0x7e16467a MSVCRT_realloc+0x47() in msvcrt (0x0032f5c8)
  5 0x6c99f897 in sdl2 (+0x5f896) (0x016355c0)
  6 0x0050005c in openrct2 (+0x10005b) (0x003a0043)
0x7bc52106: movl	0x0(%eax),%eax
Modules:
Module	Address			Debug info	Name (110 modules)
PE	  330000-  33f000	Deferred        sdl2_ttf
PE	  400000- 14b6000	Export          openrct2
PE	62540000-625c3000	Deferred        libfreetype-6
PE	64b40000-64b53000	Deferred        libwinpthread-1
PE	69ec0000-69ed7000	Deferred        libbz2-1
PE	6c940000-6ca13000	COFF            sdl2
PE	70200000-71412000	Deferred        openrct2
ELF	7b800000-7ba73000	Deferred        kernel32<elf>
  \-PE	7b810000-7ba73000	\               kernel32
ELF	7bc00000-7bd08000	Dwarf           ntdll<elf>
  \-PE	7bc10000-7bd08000	\               ntdll
ELF	7bf00000-7bf04000	Deferred        <wine-loader>
ELF	7c8b3000-7c8ed000	Deferred        msctf<elf>
  \-PE	7c8c0000-7c8ed000	\               msctf
ELF	7d1ee000-7d21d000	Deferred        libvorbis.so.0
ELF	7d21d000-7d225000	Deferred        libogg.so.0
ELF	7d225000-7d240000	Deferred        libnsl.so.1
ELF	7d240000-7d2cf000	Deferred        libvorbisenc.so.2
ELF	7d2cf000-7d352000	Deferred        libflac.so.8
ELF	7d352000-7d36c000	Deferred        libgcc_s.so.1
ELF	7d36c000-7d41c000	Deferred        libgcrypt.so.20
ELF	7d41c000-7d495000	Deferred        libsndfile.so.1
ELF	7d495000-7d523000	Deferred        libsystemd.so.0
ELF	7d523000-7d579000	Deferred        libdbus-1.so.3
ELF	7d5d4000-7d5da000	Deferred        libattr.so.1
ELF	7d5da000-7d606000	Deferred        liblzma.so.5
ELF	7d606000-7d61f000	Deferred        libresolv.so.2
ELF	7d61f000-7d6a7000	Deferred        libpulsecommon-6.0.so
ELF	7d6a7000-7d702000	Deferred        libpulse.so.0
ELF	7d735000-7d840000	Deferred        libasound.so.2
ELF	7d841000-7d856000	Deferred        libgpg-error.so.0
ELF	7d856000-7d85d000	Deferred        libasyncns.so.0
ELF	7d85d000-7d86a000	Deferred        libjson-c.so.2
ELF	7d86a000-7d873000	Deferred        libasound_module_pcm_pulse.so
ELF	7d873000-7d8a9000	Deferred        winealsa<elf>
  \-PE	7d880000-7d8a9000	\               winealsa
ELF	7d8a9000-7d8cd000	Deferred        mmdevapi<elf>
  \-PE	7d8b0000-7d8cd000	\               mmdevapi
ELF	7d8ef000-7d929000	Deferred        uxtheme<elf>
  \-PE	7d900000-7d929000	\               uxtheme
ELF	7d929000-7d92f000	Deferred        libxfixes.so.3
ELF	7d92f000-7d93a000	Deferred        libxcursor.so.1
ELF	7d93a000-7d94d000	Deferred        libxi.so.6
ELF	7d94d000-7d951000	Deferred        libxcomposite.so.1
ELF	7d951000-7d95e000	Deferred        libxrandr.so.2
ELF	7d95e000-7d984000	Deferred        libxcb.so.1
ELF	7d984000-7dad3000	Deferred        libx11.so.6
ELF	7dad3000-7dae8000	Deferred        libxext.so.6
ELF	7dae9000-7daee000	Deferred        libcap.so.2
ELF	7daee000-7daf7000	Deferred        librt.so.1
ELF	7db1b000-7dbc3000	Deferred        winex11<elf>
  \-PE	7db30000-7dbc3000	\               winex11
ELF	7dbc3000-7dbec000	Deferred        libexpat.so.1
ELF	7dbec000-7dc28000	Deferred        libfontconfig.so.1
ELF	7dc28000-7dc9d000	Deferred        libpcre.so.1
ELF	7dc9d000-7ddc4000	Deferred        libglib-2.0.so.0
ELF	7ddc4000-7de27000	Deferred        libharfbuzz.so.0
ELF	7de27000-7de64000	Deferred        libpng16.so.16
ELF	7de64000-7de75000	Deferred        libbz2.so.1.0
ELF	7de75000-7df35000	Deferred        libfreetype.so.6
ELF	7df36000-7df42000	Deferred        libxrender.so.1
ELF	7df68000-7dfa0000	Deferred        ws2_32<elf>
  \-PE	7df70000-7dfa0000	\               ws2_32
ELF	7dfa0000-7e11c000	Deferred        oleaut32<elf>
  \-PE	7dfc0000-7e11c000	\               oleaut32
ELF	7e11c000-7e1e1000	Dwarf           msvcrt<elf>
  \-PE	7e130000-7e1e1000	\               msvcrt
ELF	7e1e1000-7e206000	Deferred        imm32<elf>
  \-PE	7e1f0000-7e206000	\               imm32
ELF	7e206000-7e259000	Deferred        dsound<elf>
  \-PE	7e210000-7e259000	\               dsound
ELF	7e259000-7e29c000	Deferred        winspool<elf>
  \-PE	7e260000-7e29c000	\               winspool
ELF	7e29c000-7e3c7000	Deferred        comctl32<elf>
  \-PE	7e2a0000-7e3c7000	\               comctl32
ELF	7e3c7000-7e444000	Deferred        shlwapi<elf>
  \-PE	7e3d0000-7e444000	\               shlwapi
ELF	7e444000-7e6a6000	Deferred        shell32<elf>
  \-PE	7e450000-7e6a6000	\               shell32
ELF	7e6a6000-7e79d000	Deferred        comdlg32<elf>
  \-PE	7e6b0000-7e79d000	\               comdlg32
ELF	7e79d000-7e7ca000	Deferred        msacm32<elf>
  \-PE	7e7a0000-7e7ca000	\               msacm32
ELF	7e7ca000-7e85b000	Deferred        rpcrt4<elf>
  \-PE	7e7e0000-7e85b000	\               rpcrt4
ELF	7e85b000-7e9eb000	Deferred        ole32<elf>
  \-PE	7e870000-7e9eb000	\               ole32
ELF	7e9eb000-7ea6c000	Deferred        advapi32<elf>
  \-PE	7ea00000-7ea6c000	\               advapi32
ELF	7ea6c000-7eba6000	Deferred        gdi32<elf>
  \-PE	7ea80000-7eba6000	\               gdi32
ELF	7eba6000-7ed1f000	Deferred        user32<elf>
  \-PE	7ebc0000-7ed1f000	\               user32
ELF	7ed1f000-7edde000	Deferred        winmm<elf>
  \-PE	7ed30000-7edde000	\               winmm
ELF	7ef6d000-7ef80000	Deferred        libnss_files.so.2
ELF	7ef80000-7efcd000	Deferred        libm.so.6
ELF	7efcd000-7efe4000	Deferred        libz.so.1
ELF	7efe4000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f7343000-f734a000	Deferred        libxxf86vm.so.1
ELF	f734a000-f734e000	Deferred        libxinerama.so.1
ELF	f7350000-f7355000	Deferred        libdl.so.2
ELF	f7355000-f735c000	Deferred        libxdmcp.so.6
ELF	f735c000-f7360000	Deferred        libxau.so.6
ELF	f7388000-f7542000	Deferred        libc.so.6
ELF	f7542000-f7560000	Deferred        libpthread.so.0
ELF	f7560000-f7719000	Dwarf           libwine.so.1
ELF	f771a000-f773e000	Deferred        ld-linux.so.2
ELF	f7740000-f7741000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\usr\share\openrct2\openrct2.exe
	0000002e   15
	0000002d   15
	0000002c    0
	00000009    0 <==
0000000e services.exe
	00000026    0
	00000025    0
	0000001d    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001c    0
	00000019    0
	00000018    0
	00000013    0
0000001a plugplay.exe
	00000020    0
	0000001f    0
	0000001b    0
00000021 PnkBstrA.exe
	00000028    0
	00000027    0
	00000022    0
00000023 explorer.exe
	0000002b    0
	0000002a    0
	00000029    0
	00000024    0
System information:
    Wine build: wine-1.7.50
    Platform: i386 (WOW64)
    Host system: Linux
    Host version: 4.1.6-1-vfio
```

When ran via the console it also spits out the following:
```
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
err:module:load_builtin_dll failed to load .so lib for builtin L"winemp3.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
```

Using Arch Linux with the 4.1.6 kernel. Also use Wine 1.7.50 and RCT2 with both expansions installed.

**Comment by s0r00t** [comment] 2015-09-01 20:32
This is a WINE crash dump.
Is your config.ini containing the good path to RCT2?

**Comment by PureTryOut** [comment] 2015-09-01 20:35
Where is that file located?

**Comment by Gymnasiast** [comment] 2015-09-01 20:38
I'm afraid WINE crash dumps aren't useful any more since we enabled optimisations. I have had people saying that Wine 1.7.50 causes problems with RCT2.

Also, what does it say when you run it in a console?

**Comment by PureTryOut** [comment] 2015-09-01 20:40
I edited my original comment with the output from the console:
```
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
err:module:load_builtin_dll failed to load .so lib for builtin L"winemp3.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
```

**Comment by s0r00t** [comment] 2015-09-01 20:40
That file should be in ~/Documents/OpenRCT2.
Check the line (11 IIRC) containing game_path at its start.
It's the path to the RCT2 install.
If it's good, try : 
```
openrct2 --verbose
```
The second thing you pasted is also WINE output.

**Comment by PureTryOut** [comment] 2015-09-01 20:45
```
game_path = "C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2"
```
This is the correct location, RCT2 is installed there.

With `openrct2 --verbose` I get the following:
```
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
err:module:load_builtin_dll failed to load .so lib for builtin L"winemp3.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
```

**Comment by PureTryOut** [comment] 2015-09-01 20:47
```
game_path = "C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2"
```
This is the correct location, RCT2 is installed there.

With `openrct2 --verbose` I get the following:
```
VERBOSE: initialising game
VERBOSE: loading object list cache (plugin.dat)
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Bumbly Bazaar.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Extreme Heights.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Roaring Twenties - Prison Island.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Infernal Views.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Africa - African Diamond Mine.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Rock 'n' Roll - Rock 'n' Roll.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Six Flags Great Adventure.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Mythological - Animatronic Film Set.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Build your own Six Flags Park.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Antarctic - Ecological Salvage.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Lucky Lake.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\North America - Grand Canyon.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Dusty Greens.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Botany Breakers.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Crazy Castle.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Asia - Great Wall of China Tourism Enhancement.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Build your own Six Flags Belgium.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Six Flags over Texas.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Six Flags Magic Mountain.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Asia - Japanese Coastal Reclaim.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\South America - Rain Forest Plateau.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Mythological - Cradle of Civilization.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Ghost Town.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Six Flags Belgium.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Dark Age - Robin Hood.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Europe - Renovation.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\South America - Inca Lost City.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Six Flags Holland.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Africa - Victoria Falls.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\North America - Rollercoaster Heaven.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Africa - Oasis.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\N America - Extreme Hawaiian Island.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Alpine Adventures.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Rock 'n' Roll - Flower Power.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Prehistoric - After the Asteroid.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Build your own Six Flags Holland.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Electric Fields.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Dark Age - Castle.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Europe - European Cultural Festival.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Future - Future World.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Build your own Six Flags Magic Mountain.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Factory Capers.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Build your own Six Flags over Texas.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Fungus Woods.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Prehistoric - Jurassic Safari.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Australasia - Ayers Rock.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\South America - Rio Carnival.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Australasia - Fun at the Beach.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Roaring Twenties - Schneider Cup.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Gravity Gardens.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Roaring Twenties - Skyscrapers.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Build your own Six Flags Great Adventure.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Amity Airfield.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Rainbow Summit.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Asia - Maharaja Palace.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Prehistoric - Stone Age.SC6
VERBOSE: loading scenario details, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Future - First Encounters.SC6
VERBOSE: loading track list cache (tracks.idx)
VERBOSE: loading g1 graphics
VERBOSE: loading g2 graphics
fixme:win:EnumDisplayDevicesW ((null),0,0x32f728,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x32f728,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x32f370,0x00000000), stub!
fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x32f728,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x32f728,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),0,0x32f728,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),1,0x32f728,0x00000000), stub!
fixme:win:RegisterTouchWindow (0x20062 00000003): stub
fixme:imm:ImmReleaseContext (0x20062, 0x14cd70): stub
fixme:ole:CoCreateInstance no instance created for interface {3e90ade3-7594-4cb0-bb58-69628f5f458c} of class {529a9e6b-6587-4f23-ab9e-9c7d683e3c50}, hres is 0x80004002
fixme:imm:NotifyIME NI_CLOSECANDIDATE
VERBOSE: loading title
VERBOSE: loading scenario, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Six Flags Magic Mountain.SC6
VERBOSE: loading required objects
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\BALLN.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\BURGB.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\CNDYF.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\ATM1.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\ARRT1.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\DOUGH.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\DRNKS.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\LIFT1.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\FAID1.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\INFOK.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\ZLDB.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\LFB1.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\MGR1.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\RBOAT.DAT
err:heap:validate_block_pointer Heap 0x15d0000: bad size 0000e178 for in-use arena 0x16d2428
VERBOSE: loading object, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData\TLT1.DAT
```

**Comment by Gymnasiast** [comment] 2015-09-01 20:49
Are you using develop or stable?

**Comment by PureTryOut** [comment] 2015-09-01 20:50
Latest git version, so develop. Installed it from the openrct2-git aur package.

**Comment by s0r00t** [comment] 2015-09-01 20:53
```
VERBOSE: loading scenario, C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Scenarios\Six Flags Magic Mountain.SC6
```
It might be RCT2's title sequence which is crashing it.

**Comment by PureTryOut** [comment] 2015-09-01 20:57
Can I pause/disable it? Or maybe change it for the OpenRCT2 one?

**Comment by s0r00t** [comment] 2015-09-01 21:22
It's not that. With my own brewed build, the game crashes, Arch x64.

**Comment by PureTryOut** [comment] 2015-09-01 21:22
Good, means it's not just me ;) I'll just wait for a solution.

**Comment by medsouz** [comment] 2015-09-01 23:52
The latest develop branch is working for me on Arch x64

**Comment by s0r00t** [comment] 2015-09-02 00:14
And latest WINE?

**Comment by medsouz** [comment] 2015-09-02 00:18
Wine 1.7.50-1

**Comment by medsouz** [comment] 2015-09-02 00:19
![2015-09-01-201855_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1078339/9620297/c1bf63fc-50e6-11e5-946e-5148b4ce1ab7.png)

**Comment by s0r00t** [comment] 2015-09-02 00:26
After testing, it seems my compiled version does not runs but a downloaded ZIP one works. 
MD5 sums are different.
@medsouz , are you using a downloaded one or a compiled one?

**Comment by medsouz** [comment] 2015-09-02 00:28
Just built it. :)

**Comment by s0r00t** [comment] 2015-09-02 00:30
Are your dependencies up to date?

**Comment by medsouz** [comment] 2015-09-02 00:32
Yeah, unless something has changed in the past week.

**Comment by s0r00t** [comment] 2015-09-02 00:33
Try checking for updates, it might be the reason.
Here, deps are up to date, built with ./install.sh; ./build.sh

**Comment by medsouz** [comment] 2015-09-02 00:36
I updated everything and it still works fine for me. It might be an issue with the openrct2-git package in the AUR.

**Comment by s0r00t** [comment] 2015-09-02 00:36
I am not using openrct2-git, so that's weird...

**Comment by medsouz** [comment] 2015-09-02 00:37
I have all the dependency DLLs copied directly into my OpenRCT2 git directory, maybe that is why it is working for me?

**Comment by s0r00t** [comment] 2015-09-02 00:38
Could you make a list of all the DLLs you copy? I'll test on my side.

**Comment by medsouz** [comment] 2015-09-02 00:41
SDL2_ttf.dll
libbz2-1.dll
libfreetype-6.dll
libwinpthread-1.dll

**Comment by s0r00t** [comment] 2015-09-02 00:44
Same libs as you. However I copied SDL2_ttf.dll too.
a0159619be091843ec1d29778bc6d1b9  libbz2-1.dll
ce30249c2f21f00a72f5503474d447a0  libfreetype-6.dll
fe0a8c47ae59e68bd8acc60980e9de5b  libwinpthread-1.dll
cc8ddf690af47497c3dfd901204d04c7  SDL2.dll
6cd35ad828659b95eeef1d423a98e661  SDL2_ttf.dll
SDL2.dll's sum is different from the one of the ZIP, however inverting them changed nothing.

**Comment by medsouz** [comment] 2015-09-02 01:00
I can't really think of anything else that I'm doing different

**Comment by s0r00t** [comment] 2015-09-02 16:42
I might have another idea. When ORCT2 builds, it fails (sometimes) building g2.dat. It might be that.

**Comment by s0r00t** [comment] 2015-09-02 16:44
That is indeed the cause of the bug : missing g2.dat
@PureTryOut, try downloading a ZIP develop, and put data/g2.dat in your compiled ORCT2. If that fixes it, please close the issue.

**Comment by PureTryOut** [comment] 2015-09-02 16:48
Downloaded the latest zip file (development build) from openrct2.net, and extracted g2.dat in /usr/share/openrct2/data like you suggested. However it still crashes, it seems with the same error.

Do note, the build does not fail for me.

**Comment by ipatix** [comment] 2015-09-02 18:37
I don't know if this issue is related to this but I have an issue with OpenRCT and Wine for quite some time now on Ubuntu.
Wine log: http://pastebin.com/PBtbjEVE
OpenRCT log: http://pastebin.com/maGYqJsz

I don't know what's going on but OpenRCT used to work without problems in this setup. It doesn't seem to make a difference if I use PoL or not.

**Comment by PureTryOut** [comment] 2015-09-02 18:54
Fun fact, I just had it working for about 10 minutes. Was checking out some of the maps, and then crashed again. Now it won't start up properly again.

**Comment by PureTryOut** [comment] 2015-09-02 19:09
Tried building again, noticed
```
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
err:module:load_builtin_dll failed to load .so lib for builtin L"winemp3.acm": libmpg123.so.0: cannot open shared object file: No such file or directory
Building: data/g2.dat
```
at the very end of the compiling. Replacing g2.dat didn't work like I said before, so not sure if it makes a difference.

**Comment by s0r00t** [comment] 2015-09-02 19:40
When it shows "Building: data/g2.dat", and then ends, is there a g2.dat file built?
(Also, everything that starts with fixme: or err: is from WINE)

**Comment by PureTryOut** [comment] 2015-09-02 19:42
Yes there is.

**Comment by duncanspumpkin** [comment] 2015-10-16 11:37
Is this still happening?

**Comment by PureTryOut** [comment] 2015-10-16 12:45
No, not since the native Linux build came out anyway.

**Closed** 2015-10-16 15:58 UTC
