### ISSUE TITLE
Unable to build saved track design on a 4-station mobius coaster

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7907] opened 2018-08-15 20:28 UTC
**OS:** e.g. Windows 8
**Version:** e.g. 0.2.0
**Commit/Build:** 8784dfb

In the save game provided, I'm trying to save the track design of the '4-way AND Gate' coaster. This has worked perfectly in the past (and still does) for 2-station coasters that are basically the same (as shown in the screenshots). And the 4-station ride _seems_ to save properly when the track design is saved.

But when I try to build another copy of the track design (in the same scenario where I originally built it), it says that the design contains scenery which is not available (even when I try saving it without scenery), and the preview pane is blank. When I try to place it, there is no ghost -- only the outline of the footprint. If I _do_ place it, nothing appears there and a blank ride construction window with no clickable buttons appears. Closing that window does not cause the (missing) ride's window to open, and the ride is not listed in the list of rides in the park. I've tried re-saving the track design with and without scenery several times, but it always gives this result.

**Steps to reproduce:**
1. open the save provided (or try to build your own 4-station mobius?)
2. save the 4-station mobius track design
3. attempt to build another copy of it

**Screenshots / Video:**
The ride I'm trying to save on the upper left, and a ride that saves and reproduces fine, on the bottom right:
![workbench 1 2018-08-15 12-59-45](https://user-images.githubusercontent.com/26573303/44171360-e1451000-a08e-11e8-8a77-237f7250f42e.png)

Building another copy of the 2-station mobius works fine:
![workbench 1 2018-08-15 12-59-52](https://user-images.githubusercontent.com/26573303/44171388-ec983b80-a08e-11e8-997f-fec675959625.png)
![workbench 1 2018-08-15 13-00-03](https://user-images.githubusercontent.com/26573303/44171392-f02bc280-a08e-11e8-9390-a1f9de296128.png)

But when I try to build a saved track design for the 4-station mobius:
![workbench 1 2018-08-15 13-00-11](https://user-images.githubusercontent.com/26573303/44171439-12bddb80-a08f-11e8-97ac-4bf3292ed428.png)
![workbench 1 2018-08-15 13-00-16](https://user-images.githubusercontent.com/26573303/44171444-15203580-a08f-11e8-83d0-f02681ec86a6.png)
![workbench 1 2018-08-15 13-00-19](https://user-images.githubusercontent.com/26573303/44171447-16e9f900-a08f-11e8-911f-d53b33684f55.png)

**Save game:**
[Binary Converter.zip](https://github.com/OpenRCT2/OpenRCT2/files/2291585/Binary.Converter.zip)

**Comment by jensj12** [comment] 2018-08-19 14:36
Thanks for investigating. I would consider #6123 as a duplicate of this.

**Closed** 2020-03-25 13:20 UTC
Labels: bug, duplicate
