### ISSUE TITLE
Cannot return to ride's "Overall View" by clicking on track

### ISSUE THREAD

**Issue by sta5is** [OpenRCT2/OpenRCT2#19654] opened 2023-03-16 05:26 UTC
### Operating System

Window 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.3-383-ga102688 (a102688 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

In vanilla RCT2, clicking on a piece of track will bring the ride's window to display its "Overall view". However, in the listed version of OpenRCT2, while clicking on the track gives the same behavior as in vanilla, selecting a train or station (either by clicking on them directly on main view or selected through the ride's view dropdown), and then clicking on the track does not return to "Overall view" as it should as seen in vanilla.

### Steps to reproduce

1. Click on a ride's train/vehicle or its station.
2. Click on the ride's track.
3. View does not return to "Overall view"

**Comment by ocalhoun6** [comment] 2023-03-16 10:08
Duplicate of #13406?

**Comment by ZehMatt** [comment] 2023-03-16 15:18
Yep, dupe.

**Closed by ZehMatt** 2023-03-16 15:18 UTC
Labels: bug
