### ISSUE TITLE
BACKTRACE 9cea77 rct_peep::UpdateRideMazePathfinding

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8193] opened 2018-10-31 17:35 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/9cea777b2b183b603aa5e952630750c25ab954237f7cfe3e826a7adddb044e44?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Oct 31 2018 16:46:04)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 215ea7e: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>rct_peep::UpdateRideMazePathfinding -> rct_peep::UpdateRide -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> SDL_PeepEvents_REAL -> SDL_WaitEventTimeout_REAL -> SDL_PollEvent_REAL -> UiContext::ProcessMessages -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:05
Duplicate of #8300

**Closed by janisozaur** 2019-02-02 22:05 UTC
Labels: backtrace.io, crash
