### ISSUE TITLE
handymen walking in waiting lines

### ISSUE THREAD

**Issue by remcooo96** [OpenRCT2/OpenRCT2#4595] opened 2016-10-11 14:14 UTC
-->
**OS:** MacOS 10.12
**Version:** [e.g. 0.0.5]
**Commit/Build:** b007aa9

Recently my handymen started to walk in waiting lines causing them to work a lot less efficient. Also it is useless,  because peeps never litter in them. As far as I can remember they didnt walk in waiting lines before. Maybe a bug?

**Comment by Nubbie** [comment] 2016-10-11 14:15
Duplicate of #1999

**Comment by remcooo96** [comment] 2016-10-11 14:17
Don't think it is a duplicate. They didnt walk in them before, now they do.

**Comment by janisozaur** [comment] 2016-10-11 14:18
#1999 is worded so confusingly I'm not sure if it is a duplicate or the opposite.

**Comment by devnoname120** [comment] 2016-10-11 14:48
@janisozaur

> Staff have always entered queue lines, since the first game, and it's always been annoying. There's no reason for them to be in there. **I'd love it if I could prevent them from doing so.**

It seems to be a duplicate.

**Comment by duncanspumpkin** [comment] 2016-10-11 16:10
Handymen code is quite seperate to the rest of the code so I'm pretty confident nothing has changed so this is a duplicate.

**Closed by duncanspumpkin** 2016-10-11 16:10 UTC
