### ISSUE TITLE
Steep lift hill of wood roller coaster is not dawn

### ISSUE THREAD

**Issue by manuelVo** [OpenRCT2/OpenRCT2#4448] opened 2016-09-18 11:17 UTC
**OS:** Arch Linux
**Version:** 0.0.5
**Commit/Build:** b3ef319

When building a wood roller coaster in reverse-incline launched shuttle using steep lift hills the chains are not rendered (they are functional though).

- [ ] Multiplayer

**Screenshots / Video:**
![lift_hill_chain_not_rendered](https://cloud.githubusercontent.com/assets/1705157/18615245/06f446f2-7da2-11e6-9b94-7fb8227ce074.png)

**Comment by fromthere** [comment] 2016-09-18 11:29
That's no possible now because there's no sprite for steep lift hill.
sprites should added manually like steep hill of junior coaster.

**Comment by YJSoft** [comment] 2016-09-18 11:32
also, it's duplicate of #3274(see https://github.com/OpenRCT2/OpenRCT2/issues/3274#issuecomment-207959876)

**Closed** 2016-09-18 13:16 UTC
Labels: duplicate
