### ISSUE TITLE
RCT1 (LL + AA) title sequence goes way too fast

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#3173] opened 2016-03-25 17:03 UTC
The RCT1 (LL + AA) title sequence has moments where it switches from view every 1-2 seconds. This goes way too fast. This problem might also apply to other RCT1 title sequences.

**Comment by IntelOrca** [comment] 2016-03-27 11:56
Looks fine to me, the timings are copied straight from the original RCT1 LL game.

**Comment by Stevoisiak** [comment] 2016-04-24 23:16
Has anyone else reported this being an issue? I'm not able to reproduce on my end.

**Comment by JarnoVgr** [comment] 2016-04-25 06:29
After about 1 minute in it stays only 1 second at the parks/shots. A short while later timings are normal again.

I play with uncapped FPS at 60fps. Maybe that's related?

Even people are still unable to reproduce I'll just upload a video of it.

**Comment by Gymnasiast** [comment] 2016-06-09 17:55
I just checked it on my RCT1 install. After the long Grapevine (Funtopia) shot, a series of shorter shots of around a few seconds each follow. It doesn't look like there is a time difference, but that set contains a few very precisely-timed shots. In other words: it starts just when the a roller coaster train does something interesting. Recreations of RCT1 scenarios don't always have the trains in exactly the same location (not surprising, really). So in short: it doesn't look like the OpenRCT2 version is faster-paced. I'll therefore close this.

**Closed by Gymnasiast** 2016-06-09 17:55 UTC
Labels: investigate
