### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by UnsaltedCashews** [OpenRCT2/OpenRCT2#4578] opened 2016-10-10 03:58 UTC
OS: Windows 10
Version: 0.0.5
Commit/Build: b15f8d0

Selecting Rides/Attractions in park button causes game to crash

- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Multiplayer? 

**Steps to reproduce:**
1. Start any new park
2. Select Rides/Attractions in Park button, it opens and displays no rides, with number of attractions at 0 and the games crashes.

[DumpFilesandSaves.zip](https://github.com/OpenRCT2/OpenRCT2/files/518775/DumpFilesandSaves.zip)

**Comment by IntelOrca** [comment] 2016-10-10 07:39
Duplicate of #4577

**Closed by IntelOrca** 2016-10-10 07:39 UTC
Labels: duplicate
