### ISSUE TITLE
Object Selection instability

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6850] opened 2017-12-19 00:30 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** aa23370

Recently I have had a lot of issues with the Object Selection window crashing. It will crash on opening the window and will crash when I change ride categories. The crashing is not very consistent, sometimes it will crash every time I load a game, other times it will not. Saving right before opening the object selection window seems to mitigate the crashing, which I find odd.

step 1. load a game
step 2. open the object selection window
step 3. ~70% chance OpenRCT2 crashes
step 4. change tabs of the ride selection widget
step 5. ~50% chance OpenRCT2 crashes

**Comment by spacek531** [comment] 2017-12-20 01:41
This instability appears to have died down. Hopefully it will last.

**Comment by Nubbie** [comment] 2017-12-23 00:05
Do you have a crash-dump or can you create one in task-manager?

**Comment by Gymnasiast** [comment] 2019-01-28 11:16
Closing this as it's a very old report. Let us know if the issue is still there.

**Closed by Gymnasiast** 2019-01-28 11:16 UTC
Labels: crash, investigate
