### ISSUE TITLE
OpenRCT2 Launcher - Stable build - Fatal Error

### ISSUE THREAD

**Issue by afr33sl4ve** [OpenRCT2/OpenRCT2#1949] opened 2015-09-20 19:34 UTC
Standard Output:
Starting OpenRCT2 v0.0.2
  Windows (x86)
  Jun 21 2015 09:42:17

Time: 2015/09/20 12:31:24

Standard Error:
VERBOSE: initialising game
VERBOSE: install directory does not exist, (null)
VERBOSE: searching common installation locations.
FATAL[..\src\rct2.c:275 (check_file_path)]: Could not find file C:\Users\fkamaal\Documents\OpenRCT2\bin\Data\G1.DAT

This does not happen while using the development build. The only fix is to reinstall the launcher and use the development build from the get go.

**Comment by afr33sl4ve** [comment] 2015-09-20 19:44
Huh... enabling logging while using the development build results in the game not launching. I have a path specified, I don't know if that's a contributing factor. And, it does not log the error (if any), so I can't paste any output.

**Comment by Gymnasiast** [comment] 2015-09-20 22:40
It's recommended to use the development builds if the stable build causes problems for you. While many bugs were fixed in the stable build, OpenRCT2 is still very much in development, and because of that, the stable build is by no means bug free.

As for the launcher troubles: keep in mind that it's only semi-official and not maintained by the OpenRCT2 devs. It's maintained here: https://github.com/PFCKrutonium/OpenRCT2Launcher

I'm not sure what the logging option on the launcher does. Perhaps @PFCKrutonium can shed more light on your problem.

**Comment by afr33sl4ve** [comment] 2015-09-20 22:56
Sorry, /u/Krutonium pointed me here. I've since edited the title to include that it's the launcher that's giving me troubles.

**Comment by PFCKrutonium** [comment] 2015-09-21 04:31
Yah, so as far as I know, this isn't an issue on my end, the stable build works fine for me. I would use the development builds @afr33sl4ve , since the stable doesn't work.

**Comment by afr33sl4ve** [comment] 2015-09-21 05:04
Is it an issue with the GoG version of the game? As that's what I'm using.

**Comment by Gymnasiast** [comment] 2015-09-21 07:45
I don't think so, as it doesn't actually use the rct2.exe GOG supplies. (OpenRCT2 even works with the extremely limited Mini Game, so subtle differences like those between disk, GOG and Steam don't affect OpenRCT2).

Does your game work when you turn logging off (and use the develop version)?

**Comment by IntelOrca** [comment] 2015-09-21 11:25
Does it work using the stable version from openrct2.com?

**Comment by afr33sl4ve** [comment] 2015-09-21 17:12
@Gymnasiast Yes, it works if I reinstall the launcher and use the development (nightly?) build.

@IntelOrca I may have missed something, don't I need to compile the stable version before playing? That's why I bought the game and am using the launcher.

**Comment by IntelOrca** [comment] 2015-09-21 18:09
The launcher is an unofficial external application which automatically downloads either the latest stable build or develop build from one of many build servers and installs it for you.

You can also download a portable zip from or installer for both stable and develop from https://openrct2.com, http://openrct.net or https://openrct.ursalabs.co. The installer will by default install in OpenRCT2 in Program Files, the portable zip is for you to decide. The launcher however puts OpenRCT2 in a bin folder in Documents/OpenRCT2. I don't know if the launcher is to blame or not for this issue but you can try all of those other options to get the game. The latest stable is also available as a release on GitHub.

**Comment by Enzemo** [comment] 2015-09-22 00:54
The Github page for the OpenRCT2 Launcher can be found here: https://github.com/PFCKrutonium/OpenRCT2Launcher

You may wish to open an issue there instead

**Comment by PFCKrutonium** [comment] 2015-09-22 02:09
@Enzemo The problem isn't the launcher.

@afr33sl4ve Try http://cdn.limetric.com/games/openrct2/OpenRCT2-0.0.2-master-b840.zip

**Comment by Gymnasiast** [comment] 2015-10-18 12:36
Considering the problem is gone in development, I'd say this can be closed.

**Closed** 2016-04-10 12:31 UTC
Labels: help

**Comment by PFCKrutonium** [comment] 2016-04-11 13:47
Closing is a long game apparently lol.
