### ISSUE TITLE
Background music is played if only a ride is at the centre of main view

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#3404] opened 2016-04-23 05:28 UTC
**OS:** Windows 10
**Version:** 0.0.5 develop
**Commit:** b0da767

It seems that background musics is only played when the centre of main view is at the ride.
(I think it must be fade out the volume when the distance from the ride is further.)

I have no idea wether it is a bug or is happend in only my pc
because sometimes it fades out correctly (as you can see in the video below)

See the Video. (I turned off effect sounds to explain more accurately)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
~~vid.me/Lz5F~~

**Comment by YJSoft** [comment] 2016-04-23 05:29
@telk5093 Duplicate of #3367

**Comment by telk5093** [comment] 2016-04-23 05:30
@YJSoft Thanks and sorry (감사하고 죄송합니다 ㅎ;)

**Closed** 2016-04-23 06:48 UTC
Labels: duplicate
