### ISSUE TITLE
Multiplayer Crash on adding banked turn to Steeplechase

### ISSUE THREAD

**Issue by flaminglog** [OpenRCT2/OpenRCT2#3625] opened 2016-05-15 22:24 UTC
**OS:** Windows 10
**Version:** 0.0.5.0
**Commit:** 6df1b9a

Explanation of the issue...

- [ ] Reproducible in RCT2 (vanilla)? Not sure
- [x] Multiplayer? Yes

**Steps to reproduce:**
1. Begin Steeplechase construction
2. Attempt to add banked turn when coming out of uphill.

**Dump file**
If you have a dump file, zip it and drag&drop it here.
[9a94655b-d4bc-445d-b580-c6c017fddeac(6df1b9a).zip](https://github.com/OpenRCT2/OpenRCT2/files/265305/9a94655b-d4bc-445d-b580-c6c017fddeac.6df1b9a.zip)

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video. None

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...
[9a94655b-d4bc-445d-b580-c6c017fddeac.zip](https://github.com/OpenRCT2/OpenRCT2/files/265308/9a94655b-d4bc-445d-b580-c6c017fddeac.zip)

**Comment by X123M3-256** [comment] 2016-05-15 22:54
This is a duplicate of #3597 and #3594. It seems that the game is allowing users to select track pieces that shouldn't be enabled.

**Comment by Gymnasiast** [comment] 2016-05-17 07:36
Duplicate of #3564.

**Closed by Gymnasiast** 2016-05-17 07:36 UTC
