### ISSUE TITLE
Multiple Ride Banners displayed when building a path while the game is paused using the advanced path tool

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2375] opened 2015-11-24 20:07 UTC
![screenshot](http://i.imgur.com/zDouueF.png)

When building a path from the entrance of a ride like in the screenshot, two banners appear. The one in the middle will disappear as soon as the screen area needs to be redrawn.

**Comment by duncanspumpkin** [comment] 2015-11-25 19:08
I can't reproduce this can you provide any more tips on how to reproduce.

**Comment by Broxzier** [comment] 2015-11-26 17:33
I hope this image is clearer. The game needs to be paused for it to work, because otherwise the scrolling banner will invalidate the screen area instantly.

![](http://i.imgur.com/k1LlCvt.png)

**Comment by duncanspumpkin** [comment] 2015-11-27 12:42
Okay that makes sens I didn't check it when in paused mode. Will take another look at it tonight.

**Comment by duncanspumpkin** [comment] 2015-11-27 19:18
Fixed in the pre-release.

**Closed by duncanspumpkin** 2015-11-27 19:18 UTC
Labels: bug
