### ISSUE TITLE
Is openrct2.exe still needed?

### ISSUE THREAD

**Issue by gibmat** [OpenRCT2/OpenRCT2#13707] opened 2021-01-05 23:54 UTC
At the root of this repo there's a file "openrct2.exe", which hasn't been modified in over five years, and is almost 6.5MB in size. Is this a leftover from when the exe was needed before all the code was reverse compiled? If so, can it be removed? It's bloating the size of the source code releases.

**Comment by Lastorder-DC** [comment] 2021-01-05 23:58
> It is no longer needed for the main game, no, but it is still used for some of our automated tests. We use 'testpaint' to check whether the game's track rendering matches the original game's.

From https://github.com/OpenRCT2/OpenRCT2/issues/7217#issuecomment-368211552

Duplicate of #7217

**Comment by gibmat** [comment] 2021-01-06 00:06
OK -- so long as there is still a reason for it to exist.

**Comment by duncanspumpkin** [comment] 2021-01-06 06:18
Working on removing it since test paint no longer can be trusted to give reliable results

**Closed** 2021-01-06 12:18 UTC
Labels: duplicate, question/help
