### ISSUE TITLE
Since new update 0.3

### ISSUE THREAD

**Issue by AlexanderLaheij** [OpenRCT2/OpenRCT2#2424] opened 2015-12-02 13:01 UTC
Assertion failed! Always happens online. Never happend before.

https://scontent-ams3-1.xx.fbcdn.net/hphotos-xtp1/v/t1.0-9/12314030_10207364012794190_3883801481181789907_n.jpg?oh=2b0d7286a4c62081e7a69174bf8fa5bc&oe=56DB8C7C

**Comment by duncanspumpkin** [comment] 2015-12-02 13:02
Duplicate of #2417

**Closed** 2015-12-02 13:02 UTC

**Comment by IntelOrca** [comment] 2015-12-02 13:07
@AlexanderLaheij For future, please give the issue a title that describes the issue - not the version. Version information should go in the body.

**Comment by AlexanderLaheij** [comment] 2015-12-03 04:56
Feel free to join the facebook group community we go online every now and then and share maps :D : https://www.facebook.com/groups/openrct2/
