### ISSUE TITLE
Strange "Arriving At Station" glitch.

### ISSUE THREAD

**Issue by wolfreak99** [OpenRCT2/OpenRCT2#2373] opened 2015-11-24 05:59 UTC
I do not know really how to title this glitch as it is fairly hard to explain in a title, so I apologize if it's already been posted. I am not if it is in the original RCT2 or not. I'm sharing the file which I've discovered this bug in.
https://www.mediafire.com/?273dk2n3ck6f9nt

In this file you'll find a test wooden coaster that has a large track of chain lifts. The settings is set to continuous circuit mode, with a 270mph chain lift, and 5 laps. The first lap it will act as average, it will travel along the chained tracks, reaching a max of around 270mph. After it passes the station though, the train will have a status of "Arriving at station", during this second lap it will gradually slow down until it is coasting on the chains at what seems around 4mph. It will become noticable it is not following the chain speed once it gets to about having 8 hills left.
What I'm assuming is happening is it is travelling so fast through the station that it does not detect that it entered and exited the station correctly (even though, when monitoring the train, it will say "Arriving at station" and "Departing station" before it begins to stall on "Arriving at station").
On the very last lane of track, I also tried removing a few pieces of chain track near the end and replacing with breaks to see if it still follows break limits and to see if breaks would break the "arriving at station" status, the break speeds are detected and it does slow down the train but it does not remove the "arriving at station" status. 

The only details I have so far that seem to spawn this bug is to have it multiple laps, and make sure the car enters the station at around 200+mph.

**Comment by HaasJona** [comment] 2015-11-24 06:35
Duplicate of #1923?

**Closed** 2015-11-24 08:29 UTC
Labels: duplicate
