### ISSUE TITLE
Too many objects in ObjData causes visual corruption in Scenario Editor

### ISSUE THREAD

**Issue by RCTMASTA** [OpenRCT2/OpenRCT2#7228] opened 2018-03-02 17:34 UTC
**OS:** Windows 10 b1607 x64
**Version:** 0.1.2
**Commit/Build:** 57be3b4

Having a large number of object files causes the Scenario Editor to behave strangely near the bottom of the scenery list. I assume this could happen for every "advanced" category--large scenery, paths, etc.--but for me I only have enough to introduce bugs in the Small Scenery list. I doubt there's enough CSO available for the other categories for this ever to be an issue there.

A little over halfway down the list, checkboxes start to disappear from beside object names:

![2018-03-02 09-08-09](https://user-images.githubusercontent.com/3528342/36911728-44191f14-1df9-11e8-8a78-c464f5f0ecf3.png)

Regardless of how large the window is, scrolling any distance past these missing boxes causes the list to disappear:

![2018-03-02 09-11-04](https://user-images.githubusercontent.com/3528342/36911832-a654f202-1df9-11e8-9aaf-7446de862db3.png)

The amount of objects with missing checkboxes seems directly related to how large the window is set; the missing boxes persist for exactly one window-length before the object names disappear.

Objects can still be moused over and their previews and names viewed, but as you can see the list itself is "gone," which makes things difficult to use, to say the least.

I believe that in the vanilla case, the list just won't scroll down past a certain point (likely the same point where things start getting weird here.) Most likely a failsafe to prevent exactly this issue from happening. Don't have my RCT2 disc handy to confirm this behavior, but I'm reasonably sure I remember that being a "thing."

Seems like this is due to limits in the drawing code and/or text buffer code being exceeded?

Fisch mentioned having the same issue on the New Element Discord.

> Fisch - Today at 7:11 AM
so im currently creating a bench
but the bottom 30% of my small scenery selection options
are just shown as blank
probably because i have too many objects?

- [ Possibly ] Reproducible in RCT2 (vanilla)?

**Steps to reproduce:**
1. Have a large number of objects in ORCT2's "object" or RCT2's "ObjData" folder.
2. Scroll to the end of the small scenery list.

**Comment by Gymnasiast** [comment] 2018-03-02 19:25
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/592.

**Closed by Gymnasiast** 2018-03-02 19:25 UTC
