### ISSUE TITLE
Hamachi: Disconnected No data on join

### ISSUE THREAD

**Issue by swecooo** [OpenRCT2/OpenRCT2#11277] opened 2020-04-11 20:48 UTC
**OS:** Windows 10
**Version:** 0.2.5
**Commit/Build:** 4f6e77e

We're trying to connect two servers via Hamachi. The issue appears only with relayed tunnel. When the Hamachi is able to connect via a direct tunnel, everything works.

On the client side after connecting to the server, the password prompt is successfully shown. After sending the password the game is stuck for a few seconds at _Authenticating_ step and then errors with _Disconnected: No data_.

Meanwhile on the server it is shown that the user has joined the game and after a few seconds (when the user gets _Disconnected: No data_) the server shows that the user has closed the connection.

Client side logs:
```
VERBOSE: Loading key from C:\Users\---\Documents\OpenRCT2\keys\---.privkey
VERBOSE: requesting token
VERBOSE: client received object list, it has 0 entries
VERBOSE: client requests 0 objects
VERBOSE: requesting gameinfo
# Gets stuck here, no more logs afterwards, not even on Disconnected: No data
```

Server side logs:
```
VERBOSE: Begin listening for clients
Ready for clients...
VERBOSE: Signature verification ok. Hash 522bb7b54bf201b6d1b39e3fa171a815a63cdfaa
VERBOSE: Signature verification ok. Hash 522bb7b54bf201b6d1b39e3fa171a815a63cdfaa
VERBOSE: Server sends objects list with 0 items
VERBOSE: Client requested 0 objects
VERBOSE: Sending map of size 4764401 bytes, compressed to 89431 bytes
```

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Connect two computers via Hamachi (relayed tunnel)
2. Start server on one machine
3. Connect to the server from the other machine
4. Type in the password and submit
5. Observe being stuck at _Authenticating_ step
6. Observe failing with error: _Disconnected: No data_

**Comment by janisozaur** [comment] 2020-04-11 21:21
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/11270

Though it has some good logs, @swecooo can you post this as a comment in the other issue?

**Closed by janisozaur** 2020-04-11 21:21 UTC
