### ISSUE TITLE
Cannot Build built-in Looping Coaster Designs

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#13472] opened 2020-11-28 02:12 UTC
**OS:** Windows 10
**Version:** 0.3.2 develop (and release)
**Commit/Build:** 79c6b22

Bumble Bee and Deep Freeze are Looping Coaster designs from RCT2 vanilla. 
Unfortunately, I can no longer build them in OpenRCT2.  
They don't show a preview in the build window, but you can see the ghost and try to place it.
However, it will give an error: Cannot Construct This Here... is in the way.   
Turning off scenery doesn't help.
They both contain track going through loops; maybe that's why they don't build.  

Reproducible in RCT2 (vanilla)? _no_
Specific to multiplayer? _no_

**Steps to reproduce:**
1. Go to Build Your Own Six Flags Park (a park with the Looping Coaster and flat land)
2. Try to build Bumble Bee or Deep Freeze

**Comment by ocalhoun6** [comment] 2020-11-28 02:29
Pretty sure this is because of #12707

Which makes this mostly a duplicate of #13336

I don't know if the developers here plant to fix it or not. But if it helps in the meantime, you should be able to place these track designs if you use the 'disable clearance checks' cheat first.

**Comment by Gymnasiast** [comment] 2020-11-28 13:31
Indeed a duplicate of #13336.

**Closed by Gymnasiast** 2020-11-28 13:31 UTC
