### ISSUE TITLE
Peep jailed on the road.

### ISSUE THREAD

**Issue by jkroepke** [OpenRCT2/OpenRCT2#4629] opened 2016-10-16 14:32 UTC
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 5fa5f29

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
It happends multiple times after some hours playtime on multiple locations. Whether singleplayer or multiplayer.

**Screenshots / Video:**
![https://i.imgur.com/c50vZYo.png](https://i.imgur.com/c50vZYo.png)

**Save game:**
[RCT.zip](https://github.com/OpenRCT2/OpenRCT2/files/531863/RCT.zip)

**Comment by zaxcav** [comment] 2016-10-16 22:15
These peep jams are caused by the same problem as in #4626.
Until this is fixed, you can avoid the problem by making sure the final queue piece that joins the normal path is flat.

**Comment by jkroepke** [comment] 2016-10-17 16:51
@zaxcav The queue are flat, not?`

**Comment by zaxcav** [comment] 2016-10-17 19:32
@jkroepke 
The end of the queue, connecting to the normal path (as opposed to the front of the queue connected to the ride entrance) needs to be flat to avoid this bug.

So, for the ride Enterprise 3, which originally looked like this:
![Before](https://cloud.githubusercontent.com/assets/20344978/19452289/d1de6738-94b0-11e6-8afe-9b45df873b8c.png)

You could change it to look like this:
![After](https://cloud.githubusercontent.com/assets/20344978/19452300/e3304074-94b0-11e6-92e9-3d89c4808d16.png)

As you can see, the crowd of peeps is already arriving at the queue.

**Comment by jkroepke** [comment] 2016-10-17 19:40
Oh, I thought you mean the attractions on my screenshot.

Thanks

**Comment by zaxcav** [comment] 2016-10-18 05:28
I should have been clearer.
When peeps get stuck heading to a ride, the only ride that usually matters is the ride they are heading to. Other rides are ignored.

The fix for this bug should get merged in the next few days.

**Closed** 2016-10-20 14:49 UTC
