### ISSUE TITLE
Crash Occurs After Closing Park and All Rides

### ISSUE THREAD

**Issue by Sportpilot919** [OpenRCT2/OpenRCT2#4526] opened 2016-10-04 00:42 UTC
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 3bb05e2

After closing the park and all rides (in an attempt to get guests to leave) the game crashes. This was occurring with just the vanilla steam version before installing OpenRCT2. I installed OpenRCT2 in an attempt to fix the issue. I'm still keeping OpenRCT2 installed, this is awesome. Nice work. 
- [x ] Reproducible in RCT2 (vanilla)?

**Steps to reproduce:**
1. Close Park
2. Close all rides.
3. Wait approximately 2 mins.

**Dump file**
[47898128-fbc8-4180-9b32-d1e18fa769a7(3bb05e2).zip](https://github.com/OpenRCT2/OpenRCT2/files/507453/47898128-fbc8-4180-9b32-d1e18fa769a7.3bb05e2.zip)

**Save game:**
[47898128-fbc8-4180-9b32-d1e18fa769a7.txt](https://github.com/OpenRCT2/OpenRCT2/files/507455/47898128-fbc8-4180-9b32-d1e18fa769a7.txt)

**Comment by Nubbie** [comment] 2016-11-08 22:10
Related/duplicate of #4714 (even tho this was first, the other has just more context)

**Error message;**
Unhandled exception at 0x678D6DEC (openrct2.dll) in 47898128-fbc8-4180-9b32-d1e18fa769a7(3bb05e2).dmp: 0xC0000005: Access violation reading location 0x020E6358.

**Call Stack;**
```
>	openrct2.dll!vehicle_update_track_motion_mini_golf(rct_vehicle * vehicle=0x011299bc, int * outStation=0x00000000) Line 8153	C
 	openrct2.dll!vehicle_update_travelling(rct_vehicle * vehicle=0x01129abc) Line 3170	C
 	openrct2.dll!vehicle_update(rct_vehicle * vehicle=0x01129abc) Line 1668	C
 	openrct2.dll!vehicle_update_all(...) Line 1058	C
 	openrct2.dll!game_logic_update(...) Line 371	C
 	openrct2.dll!game_update(...) Line 293	C
 	openrct2.dll!rct2_update(...) Line 462	C
 	openrct2.dll!openrct2_loop(...) Line 466	C
 	openrct2.dll!openrct2_launch(...) Line 340	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance=0x00400000, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x01533646, int nCmdShow=10) Line 134	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Locals;**
```
		i	-32768	int
+		input	{x=820 y=-4713 element=0xffffede9 {type=??? flags=??? base_height=??? ...} }	rct_xy_element
		mapElement	Variable is optimized away and not available.	
		moveInfo	Variable is optimized away and not available.	
		nextFrame	Variable is optimized away and not available.	
		outDirection	1743234516	int
+		output	{x=-5258 y=1737931471 element=0xffffffbf {type=??? flags=??? base_height=??? ...} }	rct_xy_element
+		outStation	0x00000000 {???}	int *
		outZ	18097852	int
		rand16	Variable is optimized away and not available.	
+		regs	{eax=11 ax=11 al=11 '\v' ...}	registers
+		ride	openrct2.exe!0x01367038 (load symbols for additional information) {type=67 'C' subtype=36 '$' pad_002=...}	rct_ride *
+		rideEntry	0x0ac17cc8 {name=??? description=??? images_offset=??? ...}	rct_ride_entry *
		rideType	Variable is optimized away and not available.	
+		trackBeginEnd	{begin_x=17995964 begin_y=20344888 begin_z=17996476 ...}	track_begin_end
		trackType	Variable is optimized away and not available.	
		unk16	Variable is optimized away and not available.	
		unk16_v34	Variable is optimized away and not available.	
		vEDI	Variable is optimized away and not available.	
		vEDI	Variable is optimized away and not available.	
+		vehicle	openrct2.exe!0x011299bc (load symbols for additional information) {sprite_identifier=0 '\0' is_child=...}	rct_vehicle *
+		vehicleEntry	0x0ac17ce2 {rotation_frame_mask=??? var_02=??? var_03=??? ...}	rct_ride_entry_vehicle *
		x	Variable is optimized away and not available.	
		y	Variable is optimized away and not available.	
		z	Variable is optimized away and not available.	
```

**Autos;**
```
		i	-32768	int
+		input	{x=820 y=-4713 element=0xffffede9 {type=??? flags=??? base_height=??? ...} }	rct_xy_element
		mapElement	Variable is optimized away and not available.	
		moveInfo	Variable is optimized away and not available.	
		nextFrame	Variable is optimized away and not available.	
		outDirection	1743234516	int
+		output	{x=-5258 y=1737931471 element=0xffffffbf {type=??? flags=??? base_height=??? ...} }	rct_xy_element
+		outStation	0x00000000 {???}	int *
		outZ	18097852	int
		rand16	Variable is optimized away and not available.	
+		regs	{eax=11 ax=11 al=11 '\v' ...}	registers
+		ride	openrct2.exe!0x01367038 (load symbols for additional information) {type=67 'C' subtype=36 '$' pad_002=...}	rct_ride *
+		rideEntry	0x0ac17cc8 {name=??? description=??? images_offset=??? ...}	rct_ride_entry *
		rideType	Variable is optimized away and not available.	
+		trackBeginEnd	{begin_x=17995964 begin_y=20344888 begin_z=17996476 ...}	track_begin_end
		trackType	Variable is optimized away and not available.	
		unk16	Variable is optimized away and not available.	
		unk16_v34	Variable is optimized away and not available.	
		vEDI	Variable is optimized away and not available.	
		vEDI	Variable is optimized away and not available.	
+		vehicle	openrct2.exe!0x011299bc (load symbols for additional information) {sprite_identifier=0 '\0' is_child=...}	rct_vehicle *
+		vehicleEntry	0x0ac17ce2 {rotation_frame_mask=??? var_02=??? var_03=??? ...}	rct_ride_entry_vehicle *
		x	Variable is optimized away and not available.	
		y	Variable is optimized away and not available.	
		z	Variable is optimized away and not available.	
```

**Comment by janisozaur** [comment] 2016-11-08 22:20
> duplicate of #4714 (even tho this was first, the other has just more context)

**Closed by janisozaur** 2016-11-08 22:20 UTC
Labels: investigate
