### ISSUE TITLE
Mouse cotrol locking to the edge of the screen in 'only' specific map and coaster.

### ISSUE THREAD

**Issue by sgnilwar** [OpenRCT2/OpenRCT2#7107] opened 2018-01-30 22:10 UTC
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** ac2ad02

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1.  Choose a map  "BOTANY BREAKER" or "GHOST TOWN" .
2.  Select "Wooden Roller coaster"
3.  Build a one of the following. Brainstorm, Colossus(track 1,2), Loup-Garou, Rolling Thunder(Track 1,2), Ugly Twisters

**Dump file**

**Screenshots / Video:**

![trouble issue](https://user-images.githubusercontent.com/35976091/35594029-274b8252-0655-11e8-8cc6-fb986a11d392.jpg)
**Save game:**

**Comment by Gymnasiast** [comment] 2018-01-30 22:14
Likely a duplicate of #7085.

**Closed by Gymnasiast** 2018-01-30 22:14 UTC
