### ISSUE TITLE
This .td6 has some unusual behavior

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5763] opened 2017-07-03 08:04 UTC
**OS:** Windows 8.1
**Version:** 0.0.8
**Commit/Build:** 126dOdf

The included .td6 file has no preview in the window. The ghost appears as normal. When you place the ride, it subtracts the money as normal, but the ride disappears and it opens the ride edit window with the place entrance cursor, but no entrance can be placed. Opening the console and typing `rides list` returns no results.

.TD6 file:

[Schwarzkopf Wildcat.txt](https://github.com/OpenRCT2/OpenRCT2/files/1118842/Schwarzkopf.Wildcat.txt)

This behavior may be related to the rotated entrance huts the ride was saved with.

**Comment by IntelOrca** [comment] 2017-07-03 08:32
Does it build correctly with disable clearance and disable support limits?

**Comment by spacek531** [comment] 2017-07-03 17:22
It builds correctly with height limit and clearance checks disanbled, but with clearance checks enabled it does not build. It takes your money either way.

**Comment by IntelOrca** [comment] 2017-07-03 19:40
I think this is a duplicate of #3788.

**Closed** 2017-07-03 19:41 UTC
Labels: duplicate
