### ISSUE TITLE
Attempting to build while paused crashes the game

### ISSUE THREAD

**Issue by itsNowOrNever13** [OpenRCT2/OpenRCT2#17621] opened 2022-07-27 06:04 UTC
### Operating System

Windows 10 21H2 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-52-ga516b0c (a516b0c on develop) provided by GitHub

### Describe the issue

Attempting to build anything (flat ride, tracked ride, stall) while paused freezes the game and crashes out after a couple seconds.

Doesn't drop any crashlog in the OpenRCT2\crash folder
Generates an application error in Windows Event Viewer, event ID 1000, exception code 0xc0000005, error offset 0x0000000000198549
Issue wasn't present in last week's build, not sure about the exact version

### Steps to reproduce

1. Open any park
2. Select any ride to build
3. Pause the game
4. Attempt to build
5. Crash

**Comment by janisozaur** [comment] 2022-07-27 10:16
Can you try dumping the process state? https://www.barco.com/en/support/knowledge-base/2669-creating-a-dump-file-using-task-manager-for-troubleshooting-app-crashes-and-hangs

**Comment by duncanspumpkin** [comment] 2022-07-27 10:47
Probable duplicate of #17620

**Comment by itsNowOrNever13** [comment] 2022-07-28 05:41
Seems to be working correctly again with the new dev release 0.4.1-60-g1a8660d, probably indeed related to the issue mentioned above. Thanks!

**Closed** 2022-07-28 06:49 UTC
Labels: bug
