### ISSUE TITLE
openrct2.exe will continue running after game close

### ISSUE THREAD

**Issue by Fraser-Watson** [OpenRCT2/OpenRCT2#8114] opened 2018-10-18 19:04 UTC
**OS:**  Windows 10
**Version:** 0.2.1
**Commit/Build:** f26c4c3 (not specific to this build, it has happened for about a week or two now)

openrct2.exe process will continue running even when the game is closed. An online game is required to be joined for this to happen.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. open game
2.  join any server
3. quit game
4. open task manager and see that openrct2.exe is still running

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by janisozaur** [comment] 2018-10-18 19:34
Duplicate of #8021

**Closed by janisozaur** 2018-10-18 19:34 UTC
