### ISSUE TITLE
Downloaded park keeps crashing

### ISSUE THREAD

**Issue by coasterbill** [OpenRCT2/OpenRCT2#13947] opened 2021-01-24 14:26 UTC
OpenRCT2, v0.3.2 (cea5fab) provided by Github - Windows(x86)

I know this isn't specific to this park but I found another park that doesn't work in v0.3.2 that worked in previous versions. It will load but when un-pausing it crashes almost immediately.

Steps to reproduce:

    Download https://www.nedesigns.com/park/3737/nes-mirage-islands/
    Open the park.
    Wait.

[170130-rct2-collabo-nes_mirage_islands.zip](https://github.com/OpenRCT2/OpenRCT2/files/5862417/170130-rct2-collabo-nes_mirage_islands.zip)

**Comment by ZehMatt** [comment] 2021-01-24 15:22
Can't reproduce this with the latest develop build. I'll close this, feel free to comment if you are still having trouble with the latest builds.

**Closed by ZehMatt** 2021-01-24 15:22 UTC
