### ISSUE TITLE
Cablelift is not applied in ride/attraction simulation

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10044] opened 2019-10-04 16:12 UTC
**OS:** Windows 10
**Version:** 0.2.3
**Commit/Build:** 0b95dcd

Originally issued at [here](https://gall.dcinside.com/mgallery/board/view/?id=rct&no=20400).
Cablelift is not applied in ride/attraction simulation.

**Steps to reproduce:**
1. Make any gigacoaster, it doesn't matter it is completed or not.
2. Simulate the coaster

**Screenshots / Video:**
![1570204610](https://user-images.githubusercontent.com/10726524/66222800-ee96e100-e70c-11e9-885a-741ee02f3336.gif)

**Comment by duncanspumpkin** [comment] 2019-10-05 07:24
Cable lifts have a huge section of special code I'm not at all surprised that it doesn't handle simulation mode nicely.

**Comment by Generalcamo** [comment] 2022-09-24 02:36
This is a duplicate of #9541

**Comment by Meekimoto** [comment] 2022-12-03 07:57
Mine does this too

**Comment by Gymnasiast** [comment] 2024-12-22 15:57
Closing this as a duplicate.

**Closed by Gymnasiast** 2024-12-22 15:57 UTC
Labels: investigate
