### ISSUE TITLE
Scenery disappeared from saved game

### ISSUE THREAD

**Issue by bkalish18** [OpenRCT2/OpenRCT2#15483] opened 2021-09-29 15:33 UTC
### Operating System

Mac OS 15.17

### OpenRCT2 build

OpenRCT2,  (4f6af6f on HEAD)

### Describe the issue

After loading my save, basically all of my scenery has been replaced by green triangles, both in game and in the selection menu

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. 
2. 
3. 
<img width="1220" alt="Bug" src="https://user-images.githubusercontent.com/91558327/135301205-97a7fd26-d1b0-4f80-9eb3-6e2ca8608c82.png">

**Comment by Gymnasiast** [comment] 2021-09-29 17:04
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/14943

**Closed by Gymnasiast** 2021-09-29 17:04 UTC
Labels: bug
