### ISSUE TITLE
Feature request: vandalize park

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5829] opened 2017-07-07 20:06 UTC
This is a son of beast trainer function. It would break all the benches, bins and lamps instantly. Related to this, a button that spreads litter on the paths would be cool. I think the SoB trainer's Riot function would do this, alongside making every peep pissed.

**Comment by Nubbie** [comment] 2017-07-15 10:17
Duplicate off #3526

**Closed** 2017-07-15 11:08 UTC
Labels: feature, plug-in
