### ISSUE TITLE
Heat maps ideas 

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3470] opened 2016-05-01 18:39 UTC
Using the same greyed out view as "save track design with scenery" I think it might be possible to get heat maps. 

![screen shot 05-01-16 at 07 20 pm](https://cloud.githubusercontent.com/assets/1381723/14943459/e753c4a0-0fd1-11e6-84ac-fa014481215a.PNG)

Some of the ideas I've come up with are combining the greyed out view with the graphs option and using the "alternative colour" option to change the colour of the coasters. 

![screen shot 05-01-16 at 07 22 pm](https://cloud.githubusercontent.com/assets/1381723/14943463/0955454c-0fd2-11e6-945c-e714210d9c95.PNG)

So green sections would be slow parts and red sections would be the fast parts, combine this with the height markers which would be used to display speed you end up getting something similar to Parkitect.

![untitle4864d-1](https://cloud.githubusercontent.com/assets/1381723/14943470/3b0d7802-0fd2-11e6-8719-7eb1f4c9abef.jpg)
![untitle45646d-2](https://cloud.githubusercontent.com/assets/1381723/14943483/944c3994-0fd2-11e6-8b37-71d54ecb51db.jpg)

It could also be used to highlight guests with certain thoughts, so for example if you want to see where the litter problems are in your park.  

![a](https://cloud.githubusercontent.com/assets/1381723/14943526/a2071940-0fd3-11e6-9ca9-fe35fe59204d.jpg)

Or see how handy men are spread throughout your park  

![aa](https://cloud.githubusercontent.com/assets/1381723/14943548/215c7ab4-0fd4-11e6-9024-ce5cb4d3024d.jpg)

I'd Imagine it would require a lot of work so maybe something for the future.

**Comment by Superjustinbros** [comment] 2016-05-01 19:08
Sounds interesting.

**Comment by janisozaur** [comment] 2016-05-01 19:43
I have a hunch this might be a duplicate or if not, then it's something I wanted to do as well. In any case, I really like your mockups and would love to see this done.

**Comment by duncanspumpkin** [comment] 2016-05-01 19:47
Well the second idea is a duplicate of the existing map if thats what you mean. 

![map](https://cloud.githubusercontent.com/assets/1277401/14943933/ded90400-0fdd-11e6-87c1-404c4a3a0970.PNG)

**Comment by Gymnasiast** [comment] 2020-12-24 18:04
Seeing where staff is is already implemented: just click the map icon in the Staff window and it will mark them with flickering dots.

Having a heatmap for the ride is not really in the spirit of RCT, which requires players to be a bit more on the ball.

**Closed by Gymnasiast** 2020-12-24 18:04 UTC
Labels: enhancement
