### ISSUE TITLE
Water and object animations frozen

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3924] opened 2016-06-20 10:05 UTC
**OS:** Windows 8
**Version:** 0.0.5
**Commit/Build:** c177cc7

Water is no longer animated. Animated objects are frozen in a single frame as well.

**Comment by janisozaur** [comment] 2016-06-20 10:15
Caused by #3897 works on 7b421c8, broken on 39aaf85

**Comment by mrtnptrs** [comment] 2016-06-20 10:24
Huh? At my side the water still animates. Are you using the OpenGL drawing engine? When yes, this issue can be closed as this is a known bug with this engine at the moment and the developers are working on fixing bugs regarding the OpenGL drawing engine.

**Comment by Liampie** [comment] 2016-06-20 10:33
Water is working again suddenly.

I don't know what OpenGL is.

**Comment by Liampie** [comment] 2016-06-20 10:35
Walls are apparantly working as well.

**Comment by mrtnptrs** [comment] 2016-06-20 10:44
So, only water object are still broken, except for waterfalls.

**Comment by Liampie** [comment] 2016-06-20 11:07
No, any animated small scenery is broken.

**Comment by WhenPenguinsAttack** [comment] 2016-06-21 07:19
Getting this issue as well.

**Comment by End3rp** [comment] 2016-06-27 20:48
@WhenPenguinsAttack same.

**Comment by PFCKrutonium** [comment] 2016-06-28 06:03
Can Confirm

**Comment by duncanspumpkin** [comment] 2016-07-02 07:06
I don't see this issue happening any more. @janisozaur reverted the changes that broke this (i think)

**Comment by IntelOrca** [comment] 2016-07-06 07:32
https://www.reddit.com/r/openrct2/comments/4reffw/moving_scenery_objects_are_frozen_any_fix/

**Comment by duncanspumpkin** [comment] 2016-07-09 07:08
@IntelOrca that was from an old build before the revert. I think this can now be closed if everyone is in agreement.

**Comment by IntelOrca** [comment] 2016-07-09 11:20
@duncanspumpkin they said their commit was 080f470, which is after the revert.

**Comment by mrtnptrs** [comment] 2016-07-17 21:06
This is fixed now, can't reproduce it.

**Closed** 2016-07-17 21:18 UTC
Labels: bug
