### ISSUE TITLE
First Aid Rooms aren't really used, they should be used asap when nausea reaches inhibiting values

### ISSUE THREAD

**Issue by Enquidou** [OpenRCT2/OpenRCT2#5273] opened 2017-03-04 11:41 UTC
I so I'm very new to this...
I was told to go here by someone on [this reddit thread](https://www.reddit.com/r/openrct2/comments/5xa2nf/question_on_first_aid_rooms/). I hope I'm doing this right.

Also, perhaps it's a nice idea to give queue lines the ability to work for stalls, could be very useful for these First Aid Rooms (if they get 'fixed').

**Comment by Nubbie** [comment] 2017-03-04 13:10
Possible dupe #1959
A short title with the whole context is the best 👍 
and also a bit off an explanation etc why and links to 3rd party places where it's been talked about
So guess this is okay :p

**Comment by ensiform** [comment] 2017-03-04 14:26
Interesting. I think I noticed this in my park.  I have like 10 of them and they usually sit on benches after getting off of rides.

**Comment by ensiform** [comment] 2017-03-04 17:13
Pretty much just need to add these lines to the switch in `sub_68F41A` 
```cpp
					case PEEP_THOUGHT_TYPE_SICK:
					case PEEP_THOUGHT_TYPE_VERY_SICK:
						peep_head_for_nearest_ride_type(peep, RIDE_TYPE_FIRST_AID);
						break;
```

**Comment by Enquidou** [comment] 2017-03-08 09:18
@ensiform wow, would that really work??
That would be aweome. I could add that piece of code to my own version? How, uhm, would I do that?

**Comment by duncanspumpkin** [comment] 2017-03-08 13:05
Duplicate of #1959

**Closed by duncanspumpkin** 2017-03-08 13:05 UTC

**Comment by ensiform** [comment] 2017-03-08 20:52
@Enquidou it kinda does. But there is some more logic involved.  Like they still prefer to sit on benches for a while. And it seems they don't immediately attempt to go to first aid always.  IMO down the road the goals and such should get an overhaul.  From what I looked at it seems like guests stats trigger a thought and a thought triggers a "go find <x>" goal which is a little weird.
