### ISSUE TITLE
Hovering a ride design over scenery will give tons of money

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7571] opened 2018-05-27 18:04 UTC
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** 617372f

Take a ride design, and hover it over scenery. You will make tons of money in seconds.

![image](https://user-images.githubusercontent.com/6469413/40589169-fa252144-61e8-11e8-8904-a7152c0c7301.png)

**Comment by AaronVanGeffen** [comment] 2018-05-27 18:07
Sounds like a regression from #3473... (cc @jensj12)

**Comment by jensj12** [comment] 2018-05-27 18:35
I currently have no idea how #3473 could have caused this... Any help investigating is appreciated.
Only happens if clearance checks are disabled.

**Comment by Umdlye** [comment] 2018-05-27 18:45
Just tested 6f5ce20 (before #3473 was merged) and it happens there too.

**Comment by Umdlye** [comment] 2018-05-27 18:51
Tested 77b09b3 (before #3473 was merged), happens there too.

**Comment by AaronVanGeffen** [comment] 2018-05-27 19:33
@jensj12 Sorry for jumping the gun on #3473… It reminded me of bugs like #259 and I dreaded we had reintroduced it!

@Umdlye Only when clearance checks are disabled… Thanks for the testing effort!

**Comment by Broxzier** [comment] 2018-05-27 20:54
This bug seems to occur with track pieces too, not just scenery.
![six flags 2018-05-27 22-53-24](https://user-images.githubusercontent.com/9705046/40590554-d7f32144-6200-11e8-913a-bbd0f897ce21.png)

**Comment by Umdlye** [comment] 2018-05-27 22:26
The issue is somewhere in #5053! I tried bisecting it but got all kinds of errors while building. Going to leave it up to the more savvy people now.

**Closed** 2018-05-30 12:39 UTC
Labels: bug
