### ISSUE TITLE
Vehicle

### ISSUE THREAD

**Issue by Coasterhacker** [OpenRCT2/OpenRCT2#23288] opened 2024-11-28 19:05 UTC
### Operating System

windows  10 16 bit

### OpenRCT2 build

OpenRCT2, v0.4.16 (2193ed7a7b on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

the vehicle appears in strange places. where the vehicles are stuck together

### Steps to reproduce

step 1 build the bumper car or flying saucer.
Step 2. open the attraction.
Step 3. Look carefully for the vehicles. the Vehicles are stuck together. and you don't know how to take apart

**Comment by karst** [comment] 2024-11-28 19:21
Duplicate of #23289

**Closed by karst** 2024-11-28 19:21 UTC
Labels: bug
