### ISSUE TITLE
Crash when reducing map size

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#3383] opened 2016-04-22 10:38 UTC
**OS:** Windows 10
**Version:** 0.0.5-develop
**Commit:** d7cd3d0662c729d4e2fd2bf1b2ff18bb0b5bc3d2

When reducing the map size while there is a large scenery entry near the edges, the game crashes. This does not happen in vanilla rct2.

![](http://i.imgur.com/2dWEVcm.png)

- [ ] Reproducible in RCT2 (vanilla)?

**Steps to reproduce:**
1. Open the scenario editor, and place a large scenery piece near the edges or corner
2. Reduce the map size - crash occurs

**Comment by IntelOrca** [comment] 2016-04-22 12:37
hmm, I thought I fixed this :/

**Comment by Gymnasiast** [comment] 2016-04-22 13:04
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/1432

**Closed by Gymnasiast** 2016-04-22 13:04 UTC
