### ISSUE TITLE
Corrupted .TD6 files crashing the game

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#435] opened 2014-09-15 20:34 UTC
When browsing through the track designs available for a selected ride, hovering the mouse over an invalid or corrupted track design will instantly cause the game to crash.

**Comment by duncanspumpkin** [comment] 2015-01-29 12:55
Any chance you could provide a .TD6 that causes a crash. I found a problem with .TD4 files that cause an instant crash but I don't have any corrupt .TD6 files so its hard to reproduce.

**Comment by Nubbie** [comment] 2016-04-20 19:17
Tried this out now 2 years later on the latest build - Dev 0.0.5: e9bf2a7
I had taken a .TD6 file and opened it up with wordpad, messing around with it (deleting and moving lines)
When I later loaded up the game and selected and hovered over it and pressed on it, nothing happen, didn't show a preview of the coaster, didn't select the coaster, didn't crash the game

I got the error in the 'CMD' thingy (but the game ignored it and kept on playing normally)
```
ERROR[src\ride\track.c:546 <load_track_design>]: Track checksum failed.
ERROR[src\ride\track.c:2270 <track_get_info>]: Failed to load track: Test.td6
```

Does this glitch still happen that it crashes the game or does the game just ignore it now?
_Tried this with the 'checksum' option on and off_

**Comment by Superjustinbros** [comment] 2016-04-20 19:39
Well, today I was trying to place down some track designs that I had, but when I had one selected and hover over the place I want to put it, the whited out silhouette of the coaster is shown before placing it, but after doing so, it suddenly disappears (along with all the paths and scenery associated with it), leaving only the Construction window open with only the Dinghy Slide's open/close buttons shown. Others simply don't have an image in the preview window and you have to place them down in a park and re-save it to get it to show a pic (This seems to happen when you have a track file that uses an invalid lift hill speed)

**Comment by PFCKrutonium** [comment] 2016-04-20 23:00
Afaik the game attempts to validate the ride and if that fails it should just ignore it.

**Comment by rwjuk** [comment] 2017-05-08 12:37
I tried to corrupt various TD6 files and select them, but it seems that since this issue was opened the game has been updated to simply ignore and not display corrupted tracks. Therefore, I'll close this as fixed unless someone can provide a bad TD6 which still gets through.

**Closed by rwjuk** 2017-05-08 12:37 UTC
Labels: original bug
