### ISSUE TITLE
Ghost train test mode whilst building a roller coaster

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2349] opened 2015-11-19 22:11 UTC
In RCT3, apparently there is a ghost car that automatically starts using the coaster you're building at the moment, which helps building good designs.

OpenRCT2 should have similar feature, perhaps enabled with a switch.

See video: https://youtu.be/-litTSiMOvo?t=8m51s

**Comment by IntelOrca** [comment] 2015-11-19 22:16
This is planned.

**Comment by janisozaur** [comment] 2015-11-19 22:16
I couldn't find it already filed and I just found out about it.

**Comment by HaasJona** [comment] 2015-11-19 22:17
just for clarification, the ghost isn't automatically started, you have to put the ride in test more (yellow flag). What we would need to change apart from the ghost appearance is that you can test while building and that a crash doesn't cause any bad reputation or debris or something like that while in ghost mode.

**Comment by Gymnasiast** [comment] 2015-11-20 20:07
Duplicate of #485. (And it was _very_ easy to find, as the search term I used was "ghost"...)

**Closed** 2015-11-20 20:14 UTC
Labels: duplicate

**Comment by janisozaur** [comment] 2015-11-21 07:25
Right, sorry. I looked through all open issues labeled 'feature', which it didn't have at the time.
