### ISSUE TITLE
BACKTRACE 9d8627 RideCreateAction::Query -> GameActions::Query

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8317] opened 2018-11-30 01:30 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/9d8627b4fa836b47144eba338d26c1cd7d766c86aa86b7b6c6dbc8d2a75dea9f?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Nov 30 2018 01:03:07)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Stefan\\Documents\\OpenRCT2\\f461c295-5c89-432a-9c29-3d9790bee19e.sv6.gz: <em>1</em><br><strong>commit:</strong> eeaca61: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>RideCreateAction::Query -> GameActions::Query -> GameActions::Execute -> Network::ProcessGameCommandQueue -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 21:49
https://github.com/OpenRCT2/OpenRCT2/blob/381e2c12bcf4b61390ff6bd97f52891f35bde4a6/src/openrct2/actions/RideCreateAction.hpp#L104 Likely still happening

**Comment by janisozaur** [comment] 2019-02-02 22:36
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8404

**Closed by janisozaur** 2019-02-02 22:36 UTC
Labels: backtrace.io, crash
