### ISSUE TITLE
Random Crashes When Building Paths/Rides

### ISSUE THREAD

**Issue by frankthetankthatsank** [OpenRCT2/OpenRCT2#7400] opened 2018-04-10 21:40 UTC
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** 1cd88a1

I'm having a weird issue where when I'm placing paths or rides, OpenRCT crashes because "an assertion failed" when it tried getting sprite 65535. 

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. place some paths down
2. start building rides

**Dump file**

**Screenshots / Video:**
![error](https://user-images.githubusercontent.com/38265007/38584950-1888ae8a-3ce6-11e8-92cf-eddcef443504.PNG)

**Save game:**
[FrankPark.zip](https://github.com/OpenRCT2/OpenRCT2/files/1896518/FrankPark.zip)

**Comment by janisozaur** [comment] 2018-04-10 21:49
Dupe of #7393.

@frankthetankthatsank double-close the ferris wheel.

**Closed by janisozaur** 2018-04-10 21:49 UTC
