### ISSUE TITLE
BACKTRACE 7c8212 ObjectJsonHelpers::RequiredImage::RequiredImage(unsigned int,std::function ObjectJsonHelpers::ParseImages

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8409] opened 2018-12-10 05:39 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/7c82125107c338381b6aacdf040acbbe1834d16b1f3d9a6949401e98d3cace4c?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Mon Dec 10 2018 05:37:52)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\RobTe\\OneDrive\\Documents\\OpenRCT2\\ae908e8b-ef45-45d1-b6ca-4eebbdcaabc0.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\RobTe\\OneDrive\\Documents\\OpenRCT2\\ae908e8b-ef45-45d1-b6ca-4eebbdcaabc0.sv6.gz: <em>1</em><br><strong>commit:</strong> 4863b7c: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>stack-overflow</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ObjectJsonHelpers::RequiredImage::RequiredImage(unsigned int,std::function<rct_g1_element const * __cdecl -> ObjectJsonHelpers::ParseImages -> ObjectJsonHelpers::LoadImages -> ObjectFactory::CreateObjectFromJson -> ObjectFactory::CreateObjectFromJsonFile -> ObjectRepository::LoadObject -> ObjectManager::LoadObject -> ObjectManager::LoadDefaultObjects -> ObjectManager::LoadObjects -> TitleSequencePlayer::LoadParkFromStream -> TitleSequencePlayer::ExecuteCommand -> TitleSequencePlayer::Update -> OpenRCT2::TitleScreen::Load -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2018-12-10 06:13
Looks like a regression from https://github.com/OpenRCT2/OpenRCT2/pull/7961

**Comment by janisozaur** [comment] 2019-02-02 19:57
Probably fixed in https://github.com/OpenRCT2/OpenRCT2/pull/8416

**Closed by janisozaur** 2019-02-02 19:57 UTC
Labels: backtrace.io, crash
