### ISSUE TITLE
Game crashes instantly

### ISSUE THREAD

**Issue by End3rp** [OpenRCT2/OpenRCT2#3949] opened 2016-06-24 18:23 UTC
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** [496]

When I open up the launcher and click "play", a command box pops up briefly before crashing.

- Reproducible in RCT2 (vanilla)?

**Steps to reproduce:**
1. Open up launcher
2. Click "play"

**Dump file**
[5b0c5bb1-971d-4c4c-9915-bce521606e83(080f470).zip](https://github.com/OpenRCT2/OpenRCT2/files/332293/5b0c5bb1-971d-4c4c-9915-bce521606e83.080f470.zip)

**Screenshots / Video:**
[N/A}

**Save game:**

[5b0c5bb1-971d-4c4c-9915-bce521606e83.zip](https://github.com/OpenRCT2/OpenRCT2/files/332296/5b0c5bb1-971d-4c4c-9915-bce521606e83.zip)

EDIT: Cleaner formatting

**Comment by Nubbie** [comment] 2016-06-24 18:37
Please specify what version off the game you're using, you can find it in the bottom left corner in-game.
![sghdfgsdfhdgs](https://cloud.githubusercontent.com/assets/17282384/16347159/84e8d432-3a4b-11e6-8ddd-10a8796c0ab3.png)

**Comment by janisozaur** [comment] 2016-06-24 18:41
@Nubbie you can see it in file name of dump. 080f470.

**Comment by Gymnasiast** [comment] 2016-06-25 13:07
Please update to the newest version, then try again.

**Comment by End3rp** [comment] 2016-06-25 20:58
@Gymnasiast I let it auto-update through the launcher, but it still crashed.
[d2dbbfb4-1bd5-42db-b020-02b8b839bde5.zip](https://github.com/OpenRCT2/OpenRCT2/files/333288/d2dbbfb4-1bd5-42db-b020-02b8b839bde5.zip)

**Comment by mrtnptrs** [comment] 2016-06-26 10:39
Make sure you're not running the old launcher by re-installing the launcher through this link: https://github.com/LRFLEW/OpenRCT2Launcher/releases/download/v0.0.5/OpenRCT2Launcher-win.exe And after you installed it, open the launcher and it should update correctly. Please provide the commit/build numer, which you can find at the bottom left of the main menu.

**Comment by End3rp** [comment] 2016-06-27 17:00
I re-installed the launcher, but to no avail.
![Crash screenshot](https://cloud.githubusercontent.com/assets/20131889/16388386/d1343d28-3c4d-11e6-908a-86e2b62c1e13.png)

The commit number is be9d2c1, and the build number (obtained through the launcher) is 953.

**Comment by Nubbie** [comment] 2016-06-27 17:01
Try to delete your 'plugins.dat'

**Comment by End3rp** [comment] 2016-06-27 17:05
@Nubbie I can't find it in the OpenRCT2 folder (did a search and everything). Where can I find it?

**Comment by Nubbie** [comment] 2016-06-27 17:16
`Rollercoaster Tycoon 2\Data`

**Comment by Gymnasiast** [comment] 2016-06-27 17:22
@Nubbie It hasn't been there since at least 0.0.2.

**Comment by End3rp** [comment] 2016-06-27 18:50
@Gymnasiast That's exactly what I see.

**Comment by Gymnasiast** [comment] 2016-06-27 20:40
Could you run openrct2.exe from the command prompt and with `--verbose` as an argument?
This mean:
- Open a command prompt
- `cd` to the directory where openrct2.exe resides
- `openrct2.exe --verbose`

**Comment by End3rp** [comment] 2016-06-27 20:47
@Gymnasiast tried that. Still crashed.
![prompt](https://cloud.githubusercontent.com/assets/20131889/16395222/aa7f31c2-3c6d-11e6-852c-a0924ddf7850.png)

**Comment by janisozaur** [comment] 2016-06-27 21:00
send us your `1ATLANT.DAT`

**Comment by End3rp** [comment] 2016-06-27 21:50
@janisozaur not in the OpenRCT2 folder either.

**Comment by janisozaur** [comment] 2016-06-27 21:56
I'm not sure what you mean. I can clearly see it being loaded from the screenshot you posted.

It's also quite extraordinary to post screenshots of logs instead of, well, *logs*.

**Comment by End3rp** [comment] 2016-06-27 22:00
Aha, it was in AppData, not the OpenRCT2 folder!
[1ATLANT.zip](https://github.com/OpenRCT2/OpenRCT2/files/335914/1ATLANT.zip)

**Comment by Gymnasiast** [comment] 2016-06-28 06:55
What janisozaur means is that you can simply copy and paste the text from the Command Prompt into here, rather than taking a screenshot of it.

**Comment by End3rp** [comment] 2016-06-28 16:54
@Gymnasiast ok got it.

**Comment by duncanspumpkin** [comment] 2016-06-30 19:03
1ATLANT.DAT is broken. Its string table is all wrong.

**Comment by duncanspumpkin** [comment] 2016-06-30 19:08
Replace it with the following .DAT. I have no idea how its been corrupted possibly the object packer has an issue.
[1ATLANTFixed.zip](https://github.com/OpenRCT2/OpenRCT2/files/342161/1ATLANTFixed.zip)

**Comment by End3rp** [comment] 2016-06-30 19:25
@duncanspumpkin Tried that. Ran it with --verbose, here's what I got:

C:\Program Files (x86)\OpenRCT2>openrct2.exe --verbose
OpenRCT2, v0.0.5-develop build b5706a5 provided by AppVeyor
Windows (x86)
@ Apr 29 2016 11:44:35

VERBOSE: time is 2016/06/30 12:22:02
VERBOSE: Setting exe path to C:\Program Files (x86)\OpenRCT2
VERBOSE: initialising game
VERBOSE: loading g1 graphics
VERBOSE: loading g2 graphics
VERBOSE: loading object list cache (plugin.dat)
VERBOSE: Unable to load C:\Users\Jackson\Documents\OpenRCT2\plugin.dat
VERBOSE: building cache of available objects...
VERBOSE: loading object, C:\Program Files (x86)\Infogrames Interactive\RollerCoa
ster Tycoon 2\ObjData\11.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames Interactive\RollerCoa
ster Tycoon 2\ObjData\1A.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames Interactive\RollerCoa
ster Tycoon 2\ObjData\1ATLANT.DAT
VERBOSE: loading object, C:\Program Files (x86)\Infogrames Interactive\RollerCoa
ster Tycoon 2\ObjData\1ATLANT2.DAT
Dump Path: C:\Users\Jackson\Documents\OpenRCT2\59d75faa-3a31-4737-9f90-03a4545ba
34f.dmp
Dump Id: 59d75faa-3a31-4737-9f90-03a4545ba34f
Version: 0.0.5
Commit: b5706a5
VERBOSE: saving game

**Comment by Nubbie** [comment] 2016-06-30 19:31
@End3rp Did you re-name the old 1ATLANT.DAT to '1ATLANT**2**.DAT'?, if so, delete it as it's now the cause of the problem

**Comment by End3rp** [comment] 2016-06-30 19:34
@Nubbie I didn't. It was just there.

**Comment by IntelOrca** [comment] 2016-06-30 19:35
Just so you know, my new branch I am working on is more reliable at loading objects and can cope with such objects:

This is what I get:
```
PS [refactor/object-list] .\bin\openrct2
Scanning 2820 objects...
Warning: Image table size shorter than expected.
Warning: Image table size shorter than expected.
Warning: Image table size shorter than expected.
Error reading object: 'C:\Users\Ted\Documents\OpenRCT2\object\corrupt\1ATLANT2.DAT'
Scanning complete in 0.94 seconds.
```

**Comment by duncanspumpkin** [comment] 2016-06-30 19:42
@intelorca the packer is broken though that needs fixed as well.

**Comment by IntelOrca** [comment] 2016-06-30 19:43
what is the packer?

**Comment by Patrik356b** [comment] 2016-06-30 19:58
I think @duncanspumpkin is talking about the "export objects with save game" feature

**Comment by Nubbie** [comment] 2016-06-30 20:00
@duncanspumpkin Think he ment the plugin file

**Comment by IntelOrca** [comment] 2016-06-30 20:00
do we know that this object was created from a save that was created with OpenRCT2? How do we know its not the exporter?

**Comment by duncanspumpkin** [comment] 2016-06-30 20:05
It's only a guess but it's awfully suspicious we have multiple reports with the same issue.

**Comment by Nubbie** [comment] 2016-06-30 20:11
My thought is that files on a specific server added stuff that got corrupt after a Pr changed around with the plug-in and packs

No clue if most of them is because of that but a lot off issues came after that and have heard people pointing out a server too 

Wonder if it's just a badly made plug in the change of that system that cause the crashes, hence the corrupted file

**Comment by duncanspumpkin** [comment] 2016-06-30 20:22
@Nubbie i think you are probably correct.

**Comment by Nubbie** [comment] 2016-06-30 21:58
```
> 	openrct2.dll!object_chunk_load_image_directory(unsigned char * * chunk=0x000cf9b0) Line 481	C
 	openrct2.dll!object_type_small_scenery_load(void * objectEntry=0x054b0020, unsigned int entryIndex=0, int * chunkSize) Line 1398	C
 	openrct2.dll!object_load(int type=1, void * objectEntry=0x054b0020, unsigned int entryIndex=0, int * chunkSize=0x000cfb38) Line 2565	C
 	openrct2.dll!object_load_file(int groupIndex=-1, const rct_object_entry * entry, int * chunkSize=0x000cfb38, const rct_object_entry * installedObject=0x0172acdd) Line 137	C
 	openrct2.dll!install_object_entry(rct_object_entry * entry=0x000cfb78, rct_object_entry * installed_entry=0x0172acdd, const char * path, rct_object_filters * filter=0x000cfb5c) Line 802	C
	openrct2.dll!object_list_load(...) Line 348	C
 	openrct2.dll!rct2_init(...) Line 167	C
 	openrct2.dll!openrct2_initialise(...) Line 243	C
 	openrct2.dll!openrct2_launch(...) Line 271	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x016b351d, int nCmdShow=10) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	

```

**Comment by janisozaur** [comment] 2016-06-30 22:07
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3948

**Closed by janisozaur** 2016-06-30 22:07 UTC
Labels: crash

**Comment by End3rp** [comment] 2016-07-01 19:28
@janisozaur that issue involves multiplayer... this is just starting up the game itself
