### ISSUE TITLE
Put cap on number of individual Staff Windows

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3778] opened 2016-05-30 21:30 UTC
This was mostly something I realized days ago when I was placing down numerous Staff at once, that unlike vanilla RCT2, the number of Windows open-on screen no longer cap (as in, the oldest window isn't removed when the newest one opens up).

If you lose track and don't close the staff windows as they open (usually on top of one another) the game slows down by a considerable amount.

**Comment by IntelOrca** [comment] 2016-05-30 21:38
Duplicate of #3746

**Closed by IntelOrca** 2016-05-30 21:38 UTC
Labels: duplicate
