### ISSUE TITLE
Memory Corruption Bug

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#11189] opened 2020-03-31 20:48 UTC
There is some sort of memory corruption bug that is breaking many games and causing a number of backtrace issues.

#10852 
#10862 
#11174 
#11132

It looks like the base_height is being set to 255. This has the unfortunate side affect of changing how import and export works. When a base_height is 255 it is assumed to be a free element so only 8bytes are copied into the save this means garbage data will be written into it on load. This can cause some issues with working out what is wrong. The corruption appears to happen around squares that have been recently modified which would suggest its to do with the map reorganise function.

![image](https://user-images.githubusercontent.com/1277401/78073852-8b26fc80-7399-11ea-9ae7-641073c317b3.png)

![image](https://user-images.githubusercontent.com/1277401/78073956-b6a9e700-7399-11ea-9e36-cdad25643369.png)

**Comment by AaronVanGeffen** [comment] 2020-03-31 23:54
Looks related to #11147

**Comment by janisozaur** [comment] 2020-04-04 14:16
Closing as duplicate of #11147

**Closed by janisozaur** 2020-04-04 14:16 UTC
Labels: bug
