### ISSUE TITLE
No rain in guest/ride window

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3311] opened 2016-04-15 17:55 UTC
Version: 0.0.5.0 build 1b3f46f

Set the weather to rain or heavy rain click on a guest/ride and notice that there is no rain affect in the window that shows the guest/ride.

Sorry I can't explain it better than that, hopefully this screenshot will help better explain what I mean.

![untitled](https://cloud.githubusercontent.com/assets/1381723/14570280/677c0bd6-033b-11e6-88b2-bfbc3d35e6d9.jpg)

I'm not sure if this is the same in the vanilla version.

**Comment by janisozaur** [comment] 2016-04-15 18:02
Dupe of https://github.com/OpenRCT2/OpenRCT2/issues/2607

**Closed** 2016-04-15 18:11 UTC
Labels: duplicate
