### ISSUE TITLE
Change scenery picker icon

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#5438] opened 2017-05-05 17:57 UTC
While I like the idea of the scenery picker, I don't think the current icon is a good representation of what it does, it looks like it's something that removes, or 'picks it up', the selected scenery (especially as the tooltip is 'right click to delete' (or something like that). It would be better if it would be something like this:

[picker](https://camo.githubusercontent.com/598d972de07997ee519a3ceb65f75bddd31d24d5/687474703a2f2f6f70656e636c69706172742e6f72672f696d6167652f38303070782f7376675f746f5f706e672f3139303936312f636f6c6f725f7069636b65722e706e67)

**Comment by Nubbie** [comment] 2017-05-05 18:05
Duplicate off #5339
Also, someone has to make the sprite for the 'vial dropper' :l

**Comment by rwjuk** [comment] 2017-05-05 18:12
Closing as duplicate of #5339.

**Comment by Phyxion** [comment] 2017-05-05 18:12
Sorry, I tried to find already (already expected it existed), will close.

**Closed by rwjuk** 2017-05-05 18:12 UTC
Labels: duplicate
