### ISSUE TITLE
Water level is raised abnormally (in the first)

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#8942] opened 2019-03-23 09:13 UTC
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** 6d99426

Water is raised on the every land level in the same time when I first raise them.

**Steps to reproduce:**
1. Raise the water

**Screenshots / Video:**
![녹화_2019_03_23_18_09_31_300](https://user-images.githubusercontent.com/10726524/54864187-e1c92600-4d96-11e9-83e7-e09aaaedbcae.gif)

**Comment by Nazey** [comment] 2019-03-25 02:29
Yea it is definitely something new within version 0.2.2, because 0.2.1 did not have this issue at all.

**Comment by Nazey** [comment] 2019-03-25 03:10
I'm gonna try and give this one a go

**Comment by duncanspumpkin** [comment] 2019-03-25 06:49
@nazey your welcome to have a shot but i do know where the issue is. I changed this code to game action two weeks ago. The mistake will be in the lower water game action.

**Comment by duncanspumpkin** [comment] 2019-03-25 11:23
I've accidently removed `if(surfaceElement->base_height > maxHeight) continue;` from the water raise game action loop.

**Comment by Nazey** [comment] 2019-03-25 13:18
Dang you work fast. I was messing around with `WaterRaiseAction.hpp` yesterday and thought I was getting close, but your snippet fixed it.

**Comment by duncanspumpkin** [comment] 2019-03-25 14:04
Well i only touched this code last week so had a big headstart

**Comment by Nazey** [comment] 2019-03-25 17:01
@duncanspumpkin I've tried cleaning my repo and performing a hard reset on the repo for like the past hour, but the old commits still show up when I try to pull request from the new branch. Is it because I am on my own forked repo? Or is there something I'm still missing.

**Comment by Broxzier** [comment] 2019-03-25 17:25
When you've already pushed your branch before, you need to force push to overwrite it on the remote repo (GitHub). If your branch is named `bugfix/water-level` for instance, you'd run:

```
git checkout bugfix/water-level # your branch
git fetch upstream
git reset --hard upstream/develop # resets your branch to be the same as upstream/develop
# make your changes and commit them
git push --force origin bugfix/water-level # push your branch to your fork
```

Where `origin` points at your fork and `upstream` points at this repository.

If you already have made commits and just want to apply it on a newer version of the develop branch, you should rebase instead.

**Comment by duncanspumpkin** [comment] 2019-03-25 18:10
In addition to the above i expect the issue is the commits you are trying to get rid of are still in your feature branch. You could do a `git rebase -i upstream/develop` and delete all of the bad commits then force push to github or just delete the feature branch and recreate it from upstream/develop.

**Comment by Nazey** [comment] 2019-03-25 23:17
@Broxzier @duncanspumpkin thanks for the suggestions, finally got it. The git learning curve is very difficult.

**Closed** 2019-03-26 16:34 UTC
Labels: bug, regression
