### ISSUE TITLE
Phantom Swan Peddle Boat

### ISSUE THREAD

**Issue by EternallySlaying** [OpenRCT2/OpenRCT2#2728] opened 2016-01-14 20:24 UTC
![Imgur](http://i.imgur.com/2hev1Hf.png)

Boats continue to operate after the boat hire is turned off.
This particular save and image were from 0.0.4 1646, and I have reconfirmed it in 0.0.4 1652 in multiplayer and singleplayer

[BoatError.zip](https://github.com/OpenRCT2/OpenRCT2/files/90953/BoatError.zip)
.
This one got a good laugh on the server I was on, and jokes were made.

**Comment by Gymnasiast** [comment] 2016-01-14 21:58
I have had this issue in vanilla RCT2 once as well. 
(Open)RCT2 contains many rides that can have more cars/boats than fit on the platform (the log flume for example) and will keep on releasing them until there are no guests left. That code might be responsible, as this bug only seems to be triggered by closing boat hire while there are still guests on it.

**Comment by IntelOrca** [comment] 2016-01-14 22:08
I thought boats could not leave the platform unless they were populated?

**Comment by Gymnasiast** [comment] 2016-01-14 22:16
Not normally, no. That's why I came up with my theory above.

**Comment by Gymnasiast** [comment] 2016-02-27 12:07
Easily reproducible:
1) Open Electric Fields.
2) Close the Boat hire.
3) An empty rowing boat immediately leaves the station.

**Comment by Gymnasiast** [comment] 2016-02-27 12:26
Looking into it now.

**Comment by duncanspumpkin** [comment] 2016-02-27 12:30
And is that reproducible in vanilla?

**Comment by Gymnasiast** [comment] 2016-02-27 12:30
Yes.

**Comment by Gymnasiast** [comment] 2016-02-27 12:38
Fix in #3027

**Closed** 2016-02-28 10:21 UTC
Labels: bug, original bug
