### ISSUE TITLE
Crash due to invalid footpathEntry in path_paint

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3738] opened 2016-05-26 02:49 UTC
[Crash May 25th.zip](https://github.com/OpenRCT2/OpenRCT2/files/283385/Crash.May.25th.zip)
My build is 01f4ddd

**Comment by Nubbie** [comment] 2016-07-02 11:43
To devs; This is what I got from the dump file from OP

Error Message;
Unhandled exception at 0x006A37BE (openrct2.exe) in ebebe55d-1ed7-4d05-aa91-a6e505d7ab6c(01f4ddd).dmp: 0xC0000005: Access violation reading location 0x00000009.

Call stack;
```
>	openrct2.exe!006a37be()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	openrct2.dll!RCT2_CALLPROC_X(int address, int _eax, int _ebx, int _ecx, int _edx, int _esi, int _edi, int _ebp) Line 45	C
 	openrct2.dll!sub_68B3FB(int x, int y) Line 234	C
 	openrct2.dll!map_element_paint_setup(int x, int y) Line 58	C
 	openrct2.dll!viewport_paint_setup(...) Line 690	C
 	openrct2.dll!viewport_paint(rct_viewport * viewport, rct_drawpixelinfo * dpi=0x000cfcc0, int left=-1704, int top=-2418, int right, int bottom=-2390) Line 790	C
 	openrct2.dll!viewport_render(rct_drawpixelinfo * dpi=0x000cfcc0, rct_viewport * viewport=0x63948d80, int left=-1704, int top=0, int right=-139, int bottom=-2390) Line 691	C
 	openrct2.dll!window_editor_main_paint(rct_window * w=0x63935d60, rct_drawpixelinfo * dpi=0x000cfcc0) Line 96	C
 	openrct2.dll!window_draw(rct_window * w=0x63935d60, int left=0, int top=0, int right=1565, int bottom=28) Line 1543	C
 	openrct2.dll!gfx_redraw_screen_rect(short left=0, short top, short right, short bottom=28) Line 355	C
 	openrct2.dll!sub_6E7F34(rct_window * w=0x63935d60, rct_viewport * viewport=0x63948d80, short x_diff=12, short y_diff=28) Line 426	C
 	openrct2.dll!sub_6E7DE1(short x=-1704, short y=-2418, rct_window * w=0x63935d60, rct_viewport * viewport=0x63948d80) Line 502	C
 	openrct2.dll!viewport_update_position(rct_window * window=0x63935d60) Line 628	C
 	openrct2.dll!window_update_all(...) Line 161	C
 	openrct2.dll!rct2_draw(...) Line 284	C
 	openrct2.dll!openrct2_loop(...) Line 458	C
 	openrct2.dll!openrct2_launch(...) Line 324	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x015a32e7, int nCmdShow=1) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[External Code]	
```

Local & Auto empty

Seems relevant and similar to the referenced issue

**Comment by janisozaur** [comment] 2016-11-04 21:02
Crash in native code, we don't use it anymore.

Save game still (as of 3653baf) still reproduces crash with following stack trace:
```
#0  0x00000000005cd819 in path_paint (direction=3 '\003', height=112, map_element=0x28cade8 <gMapElements+228136>) at /home/janisozaur/workspace/OpenRCT2/src/paint/map_element/path.c:769
        word_F3F038 = false
        sceneryImageFlags = 0
        imageFlags = 0
        x = 1920
        y = 2976
        surface = 0x28cade0 <gMapElements+228128>
        bl = 14
        pathType = 7 '\a'
        footpathEntry = 0xffffffffffffffff
#1  0x00000000005c6792 in sub_68B3FB (x=1952, y=3008) at /home/janisozaur/workspace/OpenRCT2/src/paint/map_element/map_element.c:251
        direction = 3
        height = 112
        dword_9DE574 = {
          x = 1920, 
          y = 2976
        }
        dpi = 0x7fffffffd260
        map_element = 0x28cade8 <gMapElements+228136>
        rotation = 2 '\002'
        dx = -2684
        bx = -2428
        element = 0x28cade0 <gMapElements+228128>
        max_height = 144
        segmentPositions = {[0] = {[0] = 0, [1] = 6, [2] = 2}, [1] = {[0] = 5, [1] = 4, [2] = 8}, [2] = {[0] = 1, [1] = 7, [2] = 3}}
#2  0x00000000005c536a in map_element_paint_setup (x=1920, y=2976) at /home/janisozaur/workspace/OpenRCT2/src/paint/map_element/map_element.c:70
#3  0x00000000005ea548 in paint_generate_structs (dpi=0x7fffffffd260) at /home/janisozaur/workspace/OpenRCT2/src/paint/paint.c:694
#4  0x000000000055baf4 in viewport_paint_column (dpi=0x7fffffffd260, viewFlags=1024) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:750
#5  0x000000000055b925 in viewport_paint (viewport=0x273e5e0 <g_viewport_list>, dpi=0x7fffffffd3f0, left=-1645, top=-2444, right=-431, bottom=-2416) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:734
#6  0x000000000055aad4 in viewport_render (dpi=0x7fffffffd3f0, viewport=0x273e5e0 <g_viewport_list>, left=-1645, top=-2444, right=-431, bottom=-2416) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:664
#7  0x0000000000d410d1 in window_main_paint (w=0x273ed20 <g_window_list>, dpi=0x7fffffffd3f0) at /home/janisozaur/workspace/OpenRCT2/src/windows/main.c:97
#8  0x0000000000590e9e in window_event_paint_call (w=0x273ed20 <g_window_list>, dpi=0x7fffffffd3f0) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:2041
#9  0x000000000058c417 in window_draw_single (dpi=0x7fffffffd3f0, w=0x273ed20 <g_window_list>, left=0, top=0, right=1214, bottom=28) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1688
#10 0x000000000058a788 in window_draw (dpi=0x7fffffffd520, w=0x273ed20 <g_window_list>, left=0, top=0, right=1214, bottom=28) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1584
#11 0x000000000050124d in window_draw_all (dpi=0x61a00000a710, left=0, top=0, right=1214, bottom=28) at /home/janisozaur/workspace/OpenRCT2/src/drawing/drawing.c:460
#12 0x0000000000556cdd in viewport_shift_pixels (dpi=0x61a00000a710, w=0x273f200 <g_window_list+1248>, viewport=0x273e5e0 <g_viewport_list>, x_diff=116, y_diff=96) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:399
#13 0x000000000055863c in viewport_move (x=-1645, y=-2444, w=0x273ed20 <g_window_list>, viewport=0x273e5e0 <g_viewport_list>) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:479
#14 0x000000000055982e in viewport_update_position (window=0x273ed20 <g_window_list>) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:608
#15 0x000000000057c36d in window_update_all_viewports () at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:154
#16 0x0000000000f73a06 in SoftwareDrawingEngine::Draw (this=0x61a00000a280) at /home/janisozaur/workspace/OpenRCT2/src/drawing/engines/SoftwareDrawingEngine.cpp:391
#17 0x0000000000f59456 in drawing_engine_draw () at /home/janisozaur/workspace/OpenRCT2/src/drawing/NewDrawing.cpp:134
#18 0x000000000069dad3 in platform_draw () at /home/janisozaur/workspace/OpenRCT2/src/platform/shared.c:171
#19 0x00000000005bbdd1 in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:440
#20 0x00000000005bb035 in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:342
#21 0x0000000000696334 in main (argc=2, argv=0x7fffffffdb08) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:59
```

**Comment by janisozaur** [comment] 2016-11-04 21:49
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3589

**Closed by janisozaur** 2016-11-04 21:49 UTC
Labels: crash, multiplayer
