### ISSUE TITLE
Meeting "Finish Building 5 Coasters" objective won't trigger

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1666] opened 2015-07-23 06:22 UTC
The "Win" Box only prompted when playing on v0.0.2, but not the latest one.
Save file to test (Wait for the wooden coaster finishes its test to trigger):
https://drive.google.com/file/d/0B2_12DbzmFxYX2RyVXZQUF9TMms/view?usp=sharing

**Comment by IntelOrca** [comment] 2015-07-23 11:24
Duplicate of #597

**Comment by duncanspumpkin** [comment] 2015-07-23 11:25
But it sounds like it used to work in 0.0.2.

**Comment by IntelOrca** [comment] 2015-07-23 11:27
The code for it just isn't right though...
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/scenario.c#L1224

**Comment by daihakken** [comment] 2015-07-23 13:49
just load my save in 0.0.2, and wait for the roller coaster finishes its test to show the result...

**Comment by Christipher** [comment] 2015-07-25 02:35
oh garbage - sounds like an original bug resurfaced (this bug can also be reproduced in the original game).

How: create a park with 5 incomplete coasters where there is unlimited money
Use the 5 incomplete coasters objective
play the park - it won't trigger when you have met the conditions.

**Comment by daihakken** [comment] 2015-07-25 09:00
@Christipher It **isn't** an original bug. The "Won!" window appears normally in vanilla game.
![capture](https://cloud.githubusercontent.com/assets/13048125/8888777/84ec9190-32ee-11e5-9b49-a585d3b8f5df.PNG)

**Comment by IntelOrca** [comment] 2015-07-25 10:11
@daihakken This is an original bug, the win condition code is wrong.

**Comment by daihakken** [comment] 2015-07-25 10:17
Ummm...but in action, the condition can be triggered, so I think that was not an original bug. (but again, I know nothing about coding, so please bear my ignorance.)

**Comment by IntelOrca** [comment] 2015-07-25 10:19
@daihakken It is an original bug, just because it can be triggered doesn't mean it should have been triggered.

**Comment by Christipher** [comment] 2015-07-27 16:34
also, what describes an original bug is that you can reproduce said bug in the original game.  Doesn't matter when the bug surfaced for correction, but if that bug occurs in a newer build and can be reproduced in the original game, it is also considered an original bug (even if it was temporarily quashed).

**Comment by IntelOrca** [comment] 2015-07-27 18:04
@Christipher It wasn't temporarily quashed.

**Comment by IntelOrca** [comment] 2015-08-05 12:56
See #597.

**Closed by IntelOrca** 2015-08-05 12:56 UTC
Labels: bug
