### ISSUE TITLE
Crashes often in OpenRCT2::Audio::MemoryAudioSource::Convert

### ISSUE THREAD

**Issue by r4nd0m6uy** [OpenRCT2/OpenRCT2#6468] opened 2017-10-14 11:49 UTC
Compiling latest develop branch  (v0.0.4-rc1-6159-g167662f65), the game crashes very often at the same place. Here is the stack trace I got from the core dump:

#0  0x00007f371a56cef3 in ?? () from /usr/lib/libSDL2-2.0.so.0
#1  0x00007f371a56d0a5 in ?? () from /usr/lib/libSDL2-2.0.so.0
#2  0x00007f371a56d5f7 in ?? () from /usr/lib/libSDL2-2.0.so.0
#3  0x000000000054c365 in OpenRCT2::Audio::MemoryAudioSource::Convert (this=0xc5f3320, format=0x2b61ff4)
    at /home/random/sources/OpenRCT2/src/openrct2-ui/audio/MemoryAudioSource.cpp:162
#4  0x000000000054bc46 in OpenRCT2::Audio::AudioSource::CreateMemoryFromWAV (path=..., targetFormat=0x2b61ff4)
    at /home/random/sources/OpenRCT2/src/openrct2-ui/audio/MemoryAudioSource.cpp:228
#5  0x00000000005498b3 in OpenRCT2::Audio::AudioMixerImpl::LoadMusic (this=0x2b61fe0, pathId=3)
    at /home/random/sources/OpenRCT2/src/openrct2-ui/audio/AudioMixer.cpp:208
#6  0x00000000006547ed in Mixer_Play_Music (pathId=3, loop=-1, streaming=0) at /home/random/sources/OpenRCT2/src/openrct2/audio/AudioMixer.cpp:156
#7  0x00000000006e2f78 in peep_update_crowd_noise () at /home/random/sources/OpenRCT2/src/openrct2/peep/Peep.cpp:7750
#8  0x00000000005b409d in game_logic_update () at /home/random/sources/OpenRCT2/src/openrct2/game.c:431
#9  0x00000000005b3d24 in game_update () at /home/random/sources/OpenRCT2/src/openrct2/game.c:323
#10 0x00000000006452c1 in OpenRCT2::Context::Update (this=0x2d6af00) at /home/random/sources/OpenRCT2/src/openrct2/Context.cpp:690
#11 0x0000000000645062 in OpenRCT2::Context::RunFixedFrame (this=0x2d6af00) at /home/random/sources/OpenRCT2/src/openrct2/Context.cpp:615
#12 0x0000000000644f98 in OpenRCT2::Context::RunFrame (this=0x2d6af00) at /home/random/sources/OpenRCT2/src/openrct2/Context.cpp:588
#13 0x0000000000644f13 in OpenRCT2::Context::RunGameLoop (this=0x2d6af00) at /home/random/sources/OpenRCT2/src/openrct2/Context.cpp:559
#14 0x0000000000644d4e in OpenRCT2::Context::Launch (this=0x2d6af00) at /home/random/sources/OpenRCT2/src/openrct2/Context.cpp:535
#15 0x0000000000643f11 in OpenRCT2::Context::RunOpenRCT2 (this=0x2d6af00, argc=1, argv=0x7fff8f20e868) at /home/random/sources/OpenRCT2/src/openrct2/Context.cpp:157
#16 0x000000000053e32c in main (argc=1, argv=0x7fff8f20e868) at /home/random/sources/OpenRCT2/src/openrct2-ui/Ui.cpp:60

Running Void Linux with SDL 2.0.6

Any pointer? Known issue?

**Comment by r4nd0m6uy** [comment] 2017-10-14 12:05
Probably related to #6364

**Comment by janisozaur** [comment] 2017-10-14 12:40
Yes, duplicate of it. Use latest sdl2.

**Closed by janisozaur** 2017-10-14 12:40 UTC
