### ISSUE TITLE
BACKTRACE 453773 RideCreateAction::Query -> GameActions::Query

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8277] opened 2018-11-18 23:03 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/453773394956604dd03ae0dc7ade0fe0297bcaa5cae25333eee3ee7ee31b7112?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sun Nov 18 2018 23:02:58)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 18f1fab: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>RideCreateAction::Query -> GameActions::Query -> GameActions::Execute -> Network::ProcessGameCommandQueue -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:36
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8404

**Closed by janisozaur** 2019-02-02 22:36 UTC
Labels: backtrace.io, crash
