### ISSUE TITLE
entrance not yet build bug

### ISSUE THREAD

**Issue by tulsidas** [OpenRCT2/OpenRCT2#5244] opened 2017-02-21 00:05 UTC
**OS:** Linux
**Version:** 0.0.6-HEAD
**Commit/Build:** 7eac99c

I've built a floorless roller coaster, when I try to test it or open it I get "entrance not yet built" error, but the entrance (and exit) are clearly there. 

**Steps to reproduce:**
1. Switch to "Test" or "Open" the floorless rollercoaster 
2. It should start running, but instead throws the error "Entrance not yet built"

**Save game:**
[Aeropuerto Amistad.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/788752/Aeropuerto.Amistad.sv6.zip)

**Comment by janisozaur** [comment] 2017-02-21 00:12
The coaster seems to have two stations, is that correct for this type of ride?

**Comment by tulsidas** [comment] 2017-02-21 00:50
Indeed. Maybe the bug is that the game thinks there are two stations when there is only one?

**Comment by tulsidas** [comment] 2017-02-21 22:37
I can't remember precisely, but *maybe* I did some of this:

- build the whole coaster loop, then delete something and add some station platform *to the rear end* (to enlarge the station platform)
- build the first slope up after the initial station, realize that I didn't add a chain lift to it, delete it, replace it with a proper slope with chain

hope it helps, I'll try to reproduce it again, thanks

**Comment by meatbee** [comment] 2018-06-09 02:05
I'm having this bug too with the latest build. Ride won't open/test despite an entrance obviously being present. Even with 3 entrances on the same single station still "entrance not yet built".
[Blue fire 2 (glitch).sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/2086547/Blue.fire.2.glitch.sv6.txt)

**Comment by Orig-Technofuzz** [comment] 2018-11-25 02:29
I have just run into this issue, it happens when you use the tile inspector to edit the station and try to open/test it without deleting the extra station sections.  Not sure of 100% cause, however, if you highlight the station while you are building it says "station" as long as you keep the station section separated from the rest of the ride, connected on one side.  As soon as you build the penultimate track section that would complete the ride, the station changes from "station" to "station 3".  So the end result is that you can't open the ride, because it thinks there are 2 other "ghost stations" that exist.  I can't figure out any fix atm.

**Comment by tjwrona1992** [comment] 2019-11-23 22:13
I'm also experiencing this bug, I built this coaster, built a big entrance building and modified some surrounding scenery with the tile inspector. I decided I didn't like the building so I tore it down and made a few edits to the ride and now I can't open the ride again. The save file is attached. It does seem to think the ride has two stations, but there's no way to remove the first station that is invisible.

I'm attaching the park as a zip file because it wouldn't let me upload an sv6 file.

[no_entrance_bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/3882984/no_entrance_bug.zip)

**Comment by lifenotprofit** [comment] 2020-10-04 08:45
I ran into the same problem, and made some progress... i built an exit, and an entrance at both platforms... NOW it tells me 'track is not complete'... so im going to try completing a full circuit... that should get it running i hope... what a pain in the ass attraction 😆

**Comment by lifenotprofit** [comment] 2020-10-04 09:32
Pretty sure we are experiancing the same problem as a result of not completing the circuit... i had to build my ent/exit in the same platform to get it to work. I wonder if a platform built on another side, with its own ent/exit, would work.... i give up for tonight... 

> I ran into the same problem, and made some progress... i built an exit, and an entrance at both platforms... NOW it tells me 'track is not complete'... so im going to try completing a full circuit... that should get it running i hope... what a pain in the ass attraction 😆

**Comment by HenkKalkwater** [comment] 2021-05-09 12:01
I have the same problem running on an unmodified (without plugins/scripts) version of OpenRCT2 v0.3.3. Since I already was creating a new issue before I found this one, I´ll cut and paste the description over here.

While building a steel coaster as I normally would, I managed to get an invisible "ghost" station while building. When I add the station back in the gap of the current track, the coaster has suddenly two stations. When I try to test it (with the blue flag).

When setting the track mode to "continuous circuit mode", the coaster can be tested but it won´t make it uphill as expected.

I cannot exactly remember how I managed to do it and therefore not how to reproduce it, but I can remember the following:
* I have used the "blue flag" testing mode
* I have deleted and re-added the station on multiple occasions while building
* I have added the exit and entrance before completing the entire track 
* I have switched the operating mode several times while editing the track between "continuous circuit mode", "powered launch (passing station)" and "powered launch (without passing station)" 

![Screenshot_20210509_133116](https://user-images.githubusercontent.com/4262067/117570611-1c9f8c80-b0cb-11eb-9962-b0aa69952383.png)

The save file I´m playing in: (I had to gzip it since GitHub does not support directly uploading .sv6 files for some reason)
[Factory Capers.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/6447395/Factory.Capers.sv6.gz)

**Comment by squishiifx** [comment] 2021-12-29 05:46
Found a fix for this station bug that worked for me:

1) Select ride and the drop down menu for the ride 'Overview'
2) If there are any accidentally added stations they will be listed in numerical order (station 2, station 3, etc). Selection one of those stations and select the construction icon on the right
3) once in build mode, just delete/destroy the extra stations and it should allow ride testing again

**Comment by Kevinglass907** [comment] 2022-05-28 23:46
This bug is popping up when switching the monorail to "shuttle mode" and then back to continuous circuit mode. seems to maybe be a different bug since there doesn't appear to be a real piece of "station" to delete

**Comment by harvito** [comment] 2022-07-05 04:08
I've run in to this bug too, it seems. OpenRCT2, v0.4.0 (c6302a1 on master) provided by GitHub

![image](https://user-images.githubusercontent.com/14914822/177245238-e21e592b-d2b7-46f0-a093-100046a4d4a1.png)

There are no stations, but Station 1 is available from the drop-down menu. 
![image](https://user-images.githubusercontent.com/14914822/177245745-eab6986c-1ee7-472f-957f-a691baec826a.png)

When I add a station piece, it becomes Station 1 and then the game complains that there is no entrance on Station 2. The ghost station seems to be on the tile on which I first started building the ride. When I press the construction button while focused on the ghost station, we enter ride construction with a seemingly random banked turn piece highlighted. Deleting this piece and re-adding has no effect.

When constructing the ride, I used the Tile Inspector to copy the first station platform piece 3 times. Later, after connecting all 4 sections, all 4 of those station platform pieces were replaced with straight pieces. While copying using the Tile Inspector I also ran into a game crash by rotating the station platform piece from which the ride construction ghost piece was being built. The game froze and I had to reload autosave. 

The ride is Hyper-Twister 1 in the saved game. 


[Pacific Plains.zip](https://github.com/OpenRCT2/OpenRCT2/files/9043129/Pacific.Plains.zip)

**Comment by Broxzier** [comment] 2022-07-05 13:53
The problem is that removing track elements with the tile inspector simply deletes the element, but the ride still thinks there is one.

I'm not sure if it's sensible to update the ride's knowledge about the station when removing the last station piece for two reasons. One being that in case someone copied a station piece, then deletes the last remaining station piece, then newly pasted station pieces would have an invalid station index. Secondly, adding safety checks like that to the tile inspector doesn't seem the right place, even if that's the cause. Adding very specific behaviour to these kinds of situations introduces code bloat.

Instead, I think the best course of action would be to move this specialized logic from the generic 'modify element' action to some other more specialized action, or to fix this on park load, similar to how invalid ride entrances and banners are fixed.

**Comment by harvito** [comment] 2022-07-05 23:56
@Broxzier you're right, I must have deleted a station piece with the Tile Inspector. The bug is quite easy to repro when you do that. Still looking for a way to salvage my design, no luck yet

**Comment by spacek531** [comment] 2022-07-05 23:58
Unless I'm mis-remembering, there ought to be code to re-align the station indices with reality when you enter entrance building mode.

**Comment by Basssiiie** [comment] 2022-09-12 20:11
Related issues: #16718, #14696

A fix for a similar bug with moving/rotating the entrance/exits was already fixed long ago in [this commit](https://github.com/OpenRCT2/OpenRCT2/pull/7207/commits/dc334e3952c0877093498f4c726231eb572a911c).

**Comment by cseepe** [comment] 2023-04-18 20:05
I'm also having the same problem with a "ghost" station: "Can't open Twister Roller Coaster 1... / Entrance not yet built"

Not sure of the steps to reproduce, but some things to note:
- I did not use Tile Inspector at all in this scenario, even since the beginning to view/edit anything
- The only plug-ins I used in this scenario were Benchwarmer (to add benches/bins to paths) and the ride price manager
- This ride never had two stations built (so it's not like two stations existed at some point in time)
- I tried using the Simulate feature in the middle of construction and I got an error: "Can't simulate Twister Roller Coaster 1" (not the usual not-a-complete-circuit error; this was different). The Simulate feature works now, but not sure when/why.
- When in Simulate, the "ghost" station says "Exit only" at the bottom of the ride management dialog; in Closed, the dialog says "No entrance"
- I tried using the workaround mentioned earlier about selecting the station from the drop-down menu, clicking Construction, and deleting several sections, but no change
- The center of the "ghost" station appears to be just one tile ahead of the real station (based on the ride management dialog centering on the station when selected in the drop-down)

Screenshot and save file are attached
Version is "OpenRCT2, v0.4.4 (9e4918c) provided by GitHub / Windows (x86-64)"
WW/TT add-ons are installed

![image](https://user-images.githubusercontent.com/12725835/232891804-22aee4d2-c4b4-45dd-9ab0-0de0bb376e4b.png)


[Infernal Views-05-CannotOpenRide.zip](https://github.com/OpenRCT2/OpenRCT2/files/11265774/Infernal.Views-05-CannotOpenRide.zip)

**Comment by kyphii** [comment] 2023-04-27 00:15
> I'm able to reproduce the bug pretty reliably, and recorded a video of what I did to make it happen. Also uploaded the save file created as part of the video. They're uploaded to [#19152](https://github.com/OpenRCT2/OpenRCT2/issues/19152#issuecomment-1523886804) since that seems to have the most recent activity.
> 
> Update: I added a near-minimalist list of steps to reproduce the bug to the other ticket, along with another video showing it happen in a completely new game. [#19152 (comment)](https://github.com/OpenRCT2/OpenRCT2/issues/19152#issuecomment-1523923653)

This bug should be fixed in the recent develop version; it looks like you're using stable release. Can you try on the develop version to confirm this bug hasn't reappeared?

**Comment by ZehMatt** [comment] 2023-05-02 09:00
I also can't reproduce this, probably fixed.

**Closed by ZehMatt** 2023-05-02 09:00 UTC
Labels: investigate
