### ISSUE TITLE
Cannot switch to underground view when building a ride or path and game is not paused

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#8657] opened 2019-01-30 23:01 UTC
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** ec13e8d

I am unable to switch to underground view when I am in the middle of constructing a roller coaster or track ride, or when using the advanced pathway tool.  However, as soon as I pause the game, then it will let me view underground.  If I am viewing underground while the game is paused and I am in the middle of construction, and then I unpause, it will instantly switch back to above-ground.

If my current construction is underground, then I am unable to switch to above-ground unless the game is paused.

I understand the latter, but the former is difficult to adjust to from the vanilla behavior.  Is this behavior by design?

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start constructing a roller coaster
2. With the ride construction window open, try to switch to underground view.
3. Pause the game, and now you can switch to underground view.

**Dump file**
N/A

**Screenshots / Video:**
none

**Save game:**
N/A

**Comment by rpstester** [comment] 2019-01-30 23:08
Upon further review, if the above-ground piece cannot be built - the ghost image is not visible - such as a ride is in the way, then I can switch between underground and above ground. So maybe it's how the ghost image code works??

**Comment by jensj12** [comment] 2019-01-31 12:02
Any tool that has a ghost piece open automatically sets underground view according to the ghost piece. It should only do that when the ghost piece changes.

**Comment by Broxzier** [comment] 2019-01-31 21:40
Duplicate of #5448 (tracks) and #7353 (paths).

**Closed** 2019-01-31 21:40 UTC
