### ISSUE TITLE
To meney objects solected in custom scenery group

### ISSUE THREAD

**Issue by Legotown55** [OpenRCT2/OpenRCT2#16848] opened 2022-03-22 17:39 UTC
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (45369e3 on develop) provided by GitHub

### Describe the issue

When i download a custom scenery group i get a message saying to meney objects solected

### Steps to reproduce

1. Dowload a custom secnery group
2. Install it in the game
3. open it and you get that message
[Uploading OpenRCT2-0.3.5.1-develop-41e17a0-windows-x64.zip…]()

**Comment by oli414** [comment] 2022-03-22 18:37
Duplicate of #16565

**Closed by oli414** 2022-03-22 18:37 UTC
Labels: bug
