### ISSUE TITLE
Bug - When creating a new handyman; A random guests gets assigned as a staff

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3132] opened 2016-03-12 00:36 UTC
**OS:Windows 7** 
**Version:0.0.4.0** 
**Commit:dda036a** 

If you're not the host and you sometimes try to create a new handyman, it picks a random guest in the park and gets the status as a staff (even tho' the options doesn't work) which you can assign into the specific handyman/mechanic options. You also get the handyman you hired normally. 

- [ ] Reproducable in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Let someone create a server
2. Be a Client (Doesn't work for host) and place a handyman in a park where there is some already
3.Have luck (Watch the vid if you cant re-produce, doesn't always happen ) 

**Video/Screenshot**
https://vid.me/q3so

**Comment by IntelOrca** [comment] 2016-03-12 00:40
Creating staff can not work after a desync.

**Comment by IntelOrca** [comment] 2016-09-30 11:14
Duplicate of #1943

**Closed by IntelOrca** 2016-09-30 11:14 UTC
Labels: bug, duplicate, multiplayer
