### ISSUE TITLE
JsonException possibly due to "space" in the ./save/Crazy\ Castle.sv6 name.

### ISSUE THREAD

**Issue by cablegunmaster** [OpenRCT2/OpenRCT2#8103] opened 2018-10-16 22:42 UTC
**OS:** Ubuntu 18.04
**Version:**  0.2.1
**Commit/Build**: 38cc469

VERBOSE: CreateObjectFromJsonFile("/opt/openrct2/OpenRCT2/data/object/rct2/scenery_group/rct2.scgmine.json")
VERBOSE: CreateObjectFromJson(...)
VERBOSE: CreateObjectFromJsonFile("/opt/openrct2/OpenRCT2/data/object/rct2/scenery_group/rct2.scgpirat.json")
VERBOSE: CreateObjectFromJson(...)
VERBOSE: CreateObjectFromJsonFile("/opt/openrct2/OpenRCT2/data/object/rct2/scenery_group/rct2.scgsnow.json")
VERBOSE: CreateObjectFromJson(...)
VERBOSE: CreateObjectFromJsonFile("/opt/openrct2/OpenRCT2/data/object/rct2/scenery_group/rct2.scgspook.json")
VERBOSE: CreateObjectFromJson(...)
VERBOSE: CreateObjectFromJsonFile("/opt/openrct2/OpenRCT2/data/object/rct2/scenery_group/rct2.scgwater.json")
VERBOSE: CreateObjectFromJson(...)
VERBOSE: CreateObjectFromJsonFile("/opt/openrct2/OpenRCT2/data/object/rct2/scenery_group/rct2.scgwwest.json")
VERBOSE: CreateObjectFromJson(...)
VERBOSE: CreateObjectFromJsonFile("/opt/openrct2/OpenRCT2/data/object/rct2/park_entrance/rct2.pkent1.json")
VERBOSE: CreateObjectFromJson(...)
VERBOSE: CreateObjectFromJsonFile("/opt/openrct2/OpenRCT2/data/object/rct2/water/rct2.wtrcyan.json")
VERBOSE: CreateObjectFromJson(...)
VERBOSE: 0 / 0 objects unloaded
VERBOSE: 532 / 721 new objects loaded
VERBOSE: Inspecting ride entrance / exit locations
VERBOSE: file '/opt/openrct2/OpenRCT2/save/users.json' exists = 1
VERBOSE: Begin listening for clients
ERROR[../src/openrct2/network/TcpSocket.cpp:143 (Listen)]: IPV6_V6ONLY failed. 92
VERBOSE: file '/opt/openrct2/OpenRCT2/save/groups.json' exists = 0
VERBOSE: Create directory: /opt/openrct2/OpenRCT2/save/chatlogs/
VERBOSE: mkdir(/opt)
VERBOSE: mkdir(/opt/openrct2)
VERBOSE: mkdir(/opt/openrct2/OpenRCT2)
VERBOSE: mkdir(/opt/openrct2/OpenRCT2/save)
VERBOSE: mkdir(/opt/openrct2/OpenRCT2/save/chatlogs)
VERBOSE: mkdir(/opt/openrct2/OpenRCT2/save/chatlogs/)
VERBOSE: Create directory: /opt/openrct2/OpenRCT2/save/serverlogs/Willems Wilde rit V2
VERBOSE: mkdir(/opt)
VERBOSE: mkdir(/opt/openrct2)
VERBOSE: mkdir(/opt/openrct2/OpenRCT2)
VERBOSE: mkdir(/opt/openrct2/OpenRCT2/save)
VERBOSE: mkdir(/opt/openrct2/OpenRCT2/save/serverlogs)
VERBOSE: mkdir(/opt/openrct2/OpenRCT2/save/serverlogs/Willems Wilde rit V2)
VERBOSE: file '/opt/openrct2/OpenRCT2/save/users.json' exists = 1
VERBOSE: file '/opt/openrct2/OpenRCT2/save/users.json' exists = 1
Ready for clients...
VERBOSE: begin openrct2 loop
openrct2 $ terminate called after throwing an instance of 'JsonException'
                                                                           what():  '[' or '{' expected near '<'
                                                                                                                Aborted (core dumped)
- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1.  Download this commit. 
2.  install  on linux, by the wiki steps.
3. Serve the game: using following command:"./openrct host ./save/Crazy\ Castle.sv6 --port 21175 --user-data-path=./save/ --headless --address localhost --verbose

**Dump file**

**Screenshots / Video:**

**Save game:**

[Crazy Castle.txt](https://github.com/OpenRCT2/OpenRCT2/files/2485187/Crazy.Castle.txt)

user.json is empty.

**Comment by cablegunmaster** [comment] 2018-10-17 03:55
Possibly by the " ./save/Crazy\ Castle.sv6 " space in the title it didn't load correctly. after removing the space it would run.  without the error.

**Comment by Gymnasiast** [comment] 2018-10-17 07:52
I doubt it's that, JSON does not get anywhere near file names.

**Comment by cablegunmaster** [comment] 2018-10-17 09:46
Otherway around filenames get filled in somewhere? or escaping issues? with backslash?

**Comment by IntelOrca** [comment] 2018-10-17 10:41
The problem will be that one of the json files it is trying to read has invalid syntax. Unfortunately even with the verbose flag, the path of the json file is not logged.

**Comment by cablegunmaster** [comment] 2018-10-17 11:02
That would be a Jenkins test to be made "Check if JSON is valid" unit test, checking if all JSON files are valid.

**Comment by cablegunmaster** [comment] 2018-10-17 11:41
Are there any JSON files generated ? for example: users.json? I did not touch any files yet. Only changed "config.ini" to change the title of the server, and the description of the server. 
The only other thing I did was add the parameters shown above.

**Comment by Gymnasiast** [comment] 2018-10-17 11:44
We really can't tell what it was until one of us reproduces the error in a debugger. I'm not near my home system for the rest of the week, so I can't test it.

By all means, let's not jump into conclusions yet.

**Comment by janisozaur** [comment] 2018-10-17 19:20
@cablegunmaster can you access https://servers.openrct2.io/ in your browser and post your `/opt/openrct2/OpenRCT2/save/config.ini`?

**Comment by cablegunmaster** [comment] 2018-10-17 20:48
> @cablegunmaster can you access https://servers.openrct2.io/ in your browser and post your `/opt/openrct2/OpenRCT2/save/config.ini`?

Yes added.
[config.zip](https://github.com/OpenRCT2/OpenRCT2/files/2489093/config.zip)
https://servers.openrct2.io/328234 Is the Server im using right now. 

_facts:_
1. It was a clean installation, first time booting up RCT2 and only using headless as argument.
2. I'm a beginner in openrct2
3. I dont know anything about C++/C but do about Java and JSON.

Assumption which should be checked:
- A JSON file is broken / checked with a empty installation.
I cannot reproduce it myself anymore, so I am hoping its a fluke.

**Comment by janisozaur** [comment] 2018-10-17 21:53
In that case it would be best if you provided us with the core dump as well as your binary with debug symbols, or load it on your end and provide with stack trace.

Having looked at the code, I believe it's the handling of master server response, so I will add some safeguards and logs there.

**Comment by cablegunmaster** [comment] 2018-10-18 11:01
Thanks for the thinking, I got some questions to your request: 
1. How to make a core dump? 
2. What is a core dump? 
3. Binary with debug symbols?

I would love to give you the corresponding files, If understood how , or linked on to a wiki on how to make a dump / thread?

**Comment by Gymnasiast** [comment] 2022-12-08 21:15
Since it has been 4 years, I’m closing this. If anyone is experiencing something similar, please just create a new issue.

**Closed by Gymnasiast** 2022-12-08 21:15 UTC
Labels: investigate
