### ISSUE TITLE
Unable to access invention list when creating scenario

### ISSUE THREAD

**Issue by L3mmy** [OpenRCT2/OpenRCT2#7963] opened 2018-09-01 11:40 UTC
**OS:** Windows 10
**Version:** 0.2.1-23
**Commit/Build:** 303dd66

I wanted to create a scenario for the challenge, but as i was clicking the invention list, the game sent me a error message sayint that the entrance is the wrong way round or has no path leading to the map edge. This is blocking me from creating any scenarios

- [X] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1.Create a new scenario using the scenario editor
2.click on next until you see the Invention list button appear and click on it

**Dump file**

**Screenshots / Video:**
![ne workbench 2017 by louis 2018-09-01 12-25-13](https://user-images.githubusercontent.com/41308252/44945567-90eae380-adec-11e8-8482-ac63c7f42d81.png)

**Save game:**

**Comment by Broxzier** [comment] 2018-09-08 14:53
Someone else mentioned this same bug in the RC&F Discord server a few days ago. Just like Gymnasiast I am unable to reproduce this, but it doesn't seem to be a one-time thing.

**Comment by L3mmy** [comment] 2018-09-09 13:37
It's fixed :)

**Comment by Broxzier** [comment] 2018-09-09 13:43
AFAIK nothing related to entrances and scenario building was changed recently, but I guess you're also unable to reproduce it now. Were you able to reproduce this issue consistently before?

**Comment by Gymnasiast** [comment] 2020-12-24 09:46
Since the OP has not answered and nobody else appears to have this issue, I'll close this.

**Closed by Gymnasiast** 2020-12-24 09:46 UTC
Labels: bug, investigate
