### ISSUE TITLE
Multiple trains dispatching simultaneously if train spacing value set too low

### ISSUE THREAD

**Issue by Csikasz** [OpenRCT2/OpenRCT2#17077] opened 2022-04-27 16:10 UTC
I encountered an issue for a somewhat niche use case - I want to have the smallest possible (or at least a very small) spacing between cars. However, the way the game works, more than one car is dispatched if the spacing value is set below a certain value. Through empirical experimenting this value seems to be around 90000.

This video shows normal 1-by-1 dispatching behavior when the spacing is set to 90000:
https://user-images.githubusercontent.com/83851186/165562286-6b39d427-27ad-4ee3-abb9-9884d53842c9.mp4

Here I have changed the spacing to 50000. Notice how the first three cars all leave at the same time:
https://user-images.githubusercontent.com/83851186/165562537-3d742c20-0fa7-495f-a167-e48572128a51.mp4
Subsequent trains leave 1 by 1 somehow, but already the fact that three cars leave the first time is an issue for me. With even lower spacing settings like 20000, several cars will leave not only in the beginning but subsequently too.

So, how does the station dispatching work in RCT? Can the dispatching behavior be modified to allow for a finer "resolution" of cars. so that only one car is always dispatched even if the spacing is small?

**Comment by Csikasz** [comment] 2022-04-27 17:36
Update - Apparently, whether or not a station has an entrance (as opposed to only an exit hut) influences this behaviour. If there is no entrance, several trains can dispatch. In the previous videos I uploaded, the first station only has an exit. However, if there is an entrance, it seems a single train will always dispatch, even if the spacing is tight:

https://user-images.githubusercontent.com/83851186/165585847-21791149-4de6-49b9-ae2c-f7348cd22d62.mp4

So this actually works as a solution to my problem locally, but if anyone is still interested out of curiousity to find out why several trains can dispatch when there is only an exit, feel free to investigate.

**Comment by jensj12** [comment] 2022-04-27 18:01
Duplicate of #4192

**Comment by Gymnasiast** [comment] 2024-05-27 12:24
Closing as a duplicate of #4192.

**Closed as not planned by Gymnasiast** 2024-05-27 12:24 UTC
Labels: duplicate
