### ISSUE TITLE
"Encountered zero-sized chunk"

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#7810] opened 2018-07-23 16:27 UTC
**OS:** Windows 7
**Version:** 2.0
**Commit/Build:** f6b5f9e

Yesterday I attempted to play some OpenRCT2, then because of my carelessness, my computer got unplugged on the titlescreen. Now whenever I go to play, even if it's on the newest version of Open RCT2, I'm greeted with this:
![zerochuck openrct2](https://user-images.githubusercontent.com/4167951/43089760-7cae8e82-8e73-11e8-857f-4c1f31547a87.png)
And the error window gets spammed about 7 or 8 times till I mash the X button on the top right to get out. This has been occurring in every version/build ever since this accident with my computer happened.

**Comment by Broxzier** [comment] 2018-07-23 17:57
The park that it's loading has likely been corrupted. Since you mention it happens while loading the title screen, try redownloading the park sequence. If that doesn't work, download a the portable version and extract is to its own folder, and run it from there. Opening the openrct2.com file will open a black window that could print some additional information.

**Comment by Superjustinbros** [comment] 2018-07-23 18:23
It actually occurs just before the title sequence (all the logos and such).
Anyways this is what I got when running the .com file.
![openrxt2](https://user-images.githubusercontent.com/4167951/43095392-ae8faa0c-8e83-11e8-91bb-d3aa12d33fc0.png)
Even running a fresh download does not fix the error.

**Comment by Margen67** [comment] 2018-07-23 19:21
Duplicate of #7738?

**Comment by Broxzier** [comment] 2018-07-23 22:03
The screenshot suggests that it happend while rebuilding the object database.

Can you run it with the `--verbose` switch from command prompt or powershell, and post the full output until the first assert here please? You should be able to just copy the text from the window.

**Comment by Superjustinbros** [comment] 2018-07-24 17:31
Okay, I figured out what the issue was; there was a corrupt file in my objects folder so I went and deleted it and now the game runs without issue.

**Closed** 2018-07-24 17:48 UTC
Labels: help, investigate

**Comment by Broxzier** [comment] 2018-07-24 18:08
It's still strang that the file got corrupted, that shouldn't have happened by a unexpected power down if the file wasn't being written to.
