### ISSUE TITLE
Crash when clicking tabs on Park Entrance window

### ISSUE THREAD

**Issue by Fittz11** [OpenRCT2/OpenRCT2#9633] opened 2019-07-23 17:12 UTC
**OS:** Windows 10
**Version:** 0.2.3
**Commit/Build:** ab5f5b2

Upon starting a new scenario, the game will crash if any tab from the Park Entrance window is clicked. The window can be closed and other actions can be performed; however, on one particular instance, the game crashed without any deliberate action. 

- [No ] Reproducible in RCT2 (vanilla)?
- [Not Tested] Specific to multiplayer?

**Steps to reproduce:**
1. Open a new park scenario.
2. Without closing the initial window, click a tab on the the Park Entrance window. 
3. The crash can occur even after other actions have been performed in-game.

**Dump file**

[2e98b3f5-0743-4bc5-9d48-461b8fb85a46(ab5f5b2_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/3423214/2e98b3f5-0743-4bc5-9d48-461b8fb85a46.ab5f5b2_x86-64.zip)

**Screenshots / Video:**

![RCT2OpenCrash](https://user-images.githubusercontent.com/53230739/61731786-3af79500-ad4a-11e9-9059-3c2fce2a624b.jpg)

**Save game:**

**Comment by IntelOrca** [comment] 2019-07-23 19:26
Duplicate of #9626

**Closed by IntelOrca** 2019-07-23 19:26 UTC
