### ISSUE TITLE
objects replicating into a trail that won't stop

### ISSUE THREAD

**Issue by stefan084** [OpenRCT2/OpenRCT2#4841] opened 2016-11-30 14:28 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.5]
**Commit/Build:** [e.g. 426e106]

 when I click on the object to place it in the game it forms a trail of the object as in the picture(pictures,sorry) shown below

- [ ] Reproducible in RCT2 (vanilla)? no, trail only happens on my park in Open RCT2
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

![rct2broke](https://cloud.githubusercontent.com/assets/22662966/20756109/798a344e-b6df-11e6-8b5d-fd749bb4a33e.png)

**Save game:**

**Comment by AaronVanGeffen** [comment] 2016-11-30 14:35
Probably a duplicate of #4838

**Closed** 2016-11-30 15:46 UTC
Labels: duplicate
