### ISSUE TITLE
RCT2 wooden RC track designs aren't treated as RCT1 classic wooden RC track designs

### ISSUE THREAD

**Issue by rctdude2** [OpenRCT2/OpenRCT2#18093] opened 2022-09-25 01:28 UTC
### Operating System

W10 x64

### OpenRCT2 build

develop 6972811

### Describe the issue

Wooden RC track designs aren't treated as classic wooden RC track designs, probably because the game treats them as two separate track types - this doesn't happen with the looping/steel RC because they're treated as the same track type.

The RCT1 classic wooden RC and RCT2 wooden RC should show each other's track designs.

### Steps to reproduce

1. Open an RCT1 scenario (e.g. Bumbly Beach)
2. Try to build prebuilt Wooden track design

**Comment by ZeeMajora** [comment] 2022-09-25 20:34
This is intended behavior, the wooden roller coaster ride type from RCT1 isn't in RCT2. Instead it was merged with the wooden twister roller coaster to create the wooden roller coaster seen in RCT2.

The RCT1 wooden roller coaster is overall a more limited coaster in terms of elements and stats compared to the RCT2 wooden coaster alongside visual differences between the two such as it having a different track paint style alongside a different angle for banked track pieces.

OpenRCT2 has reintroduced RCT1's wooden roller coaster as the classic wooden roller coaster with it's differences and it is completely separate from the RCT2 wooden roller coaster.

**Comment by rctdude2** [comment] 2022-09-25 20:44
So does RCT1/Deluxe have absolutely no included track designs for it that
should be shown here then? It's been an extremely long time since I've
touched Deluxe for more than a couple of minutes, so I don't remember.

**Comment by ZeeMajora** [comment] 2022-09-25 20:48
There are pre-built track designs for it, you may need to regenerate your track design cache to get them to show up under the right ride type if you've recently upgraded from a previous version of openrct2.
It should automatically be regenerated when saving a new track design so do that and the vanilla pre-built tracks should properly be under the classic wooden roller coaster ride type?

**Comment by Gymnasiast** [comment] 2022-09-25 21:22
As Majora said, this is indeed intended behaviour.

For me, Mischief and Woodchip both turn up when I start building a Classic Wooden RC.

**Closed by Gymnasiast** 2022-09-25 21:22 UTC
Labels: invalid/incomplete

**Comment by rctdude2** [comment] 2022-09-25 21:44
Future reference for anyone wondering, I manually deleted `tracks.idx` under the `user` directory and the designs (Mischeif, Woodchip, and a few UGC ones) indeed showed up.
