### ISSUE TITLE
[.park format] Generating random landscape with trees only spawns Aleppo Pine Trees

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#14825] opened 2021-06-05 15:53 UTC
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 5991e47 on refs/pull/10664/merge

In Scenario Editor, if you let the game generate random landscapes with the "place trees" option selected, only the Aleppo Pine Tree is placed.

**Steps to reproduce:**
1. Go to Scenario Editor
2. Go to the Landscape Editor step
3. Generate a random landscape multiple times
4. Each time only the Aleppo Pine Tree should appear.

**Screenshots:**
![Unnamed park 2021-06-05 08-49-30](https://user-images.githubusercontent.com/61885939/120897518-7b2d2d00-c5db-11eb-9532-4378f0e3632d.png)
![Unnamed park 2021-06-05 08-52-12](https://user-images.githubusercontent.com/61885939/120897521-7bc5c380-c5db-11eb-82c1-fdf5dc5a9c9d.png)
![Unnamed park 2021-06-05 08-52-16](https://user-images.githubusercontent.com/61885939/120897523-7cf6f080-c5db-11eb-9654-1c8ba6113095.png)

**Comment by James103** [comment] 2021-06-05 15:56
Did you make sure to select other trees (besides the Aleppo Pine Tree) in the Object Selection?

**Comment by Fred-1044276** [comment] 2021-06-05 15:57
Yes, they already were selected beforehand.
![Unnamed park 2021-06-05 08-57-34](https://user-images.githubusercontent.com/61885939/120897645-158d7080-c5dc-11eb-9037-659409a28c1f.png)

**Comment by Gymnasiast** [comment] 2021-06-05 16:20
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/14155.

**Closed by Gymnasiast** 2021-06-05 16:20 UTC
