### ISSUE TITLE
Missing maze previews on 84eebb1

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#6081] opened 2017-07-31 15:38 UTC
I believe this is caused by #5943
Running version 84eebb1 on Windows 10

RCT1 scenario: ALL previews are missing
RCT2 scenario: only some are missing

**Comment by mrtnptrs** [comment] 2017-10-14 13:11
Wasn't this fixed?

**Comment by AaronVanGeffen** [comment] 2017-10-14 19:54
84eebb1 was committed on July 31. Please update and try again.

**Comment by Patrik356b** [comment] 2017-11-03 04:16
The issue has changed at some point between that build and 45b7569

The second "Mini Maze" & "Spiral Maze" crashes the game or the the blueprint goes haywire.
Very rarely the render just decides to spew the black background color over the map (when this occurred the money turned into a giant negative number also).
It's really random, but usually just crashes now

I did not experience crashes before.

I believe this is because of an issue with the RCT1 import code.

Only sometimes, openrct2 doesn't crash when picking these two designs, but placing them gives another set of issues:

![minimaze-rct1](https://user-images.githubusercontent.com/2000703/32360222-139c2866-c054-11e7-897e-dd01a7717858.png)
![spiralmaze-rct1](https://user-images.githubusercontent.com/2000703/32360223-13b620ea-c054-11e7-9fc7-e5e3253a5825.png)

Whenever it doesn't crash in the track select, it will crash when you click "select a different design".

I do not think the TD4 and TP4 files are corrupt because it was a long time since i put RCT1 & 2 on my laptop and the issue happens on my desktop as well where the game(s) were just downloaded directly from GOG very recentrly.

**Comment by janisozaur** [comment] 2017-11-03 22:11
Can you post track designs in question?

**Comment by Patrik356b** [comment] 2017-11-03 22:52
[rct§_Maze_Tracks.zip](https://github.com/OpenRCT2/OpenRCT2/files/1442685/rct._Maze_Tracks.zip)

**Comment by IntelOrca** [comment] 2017-11-22 01:41
I think this is a duplicate of #5398.

**Comment by Patrik356b** [comment] 2017-11-22 05:47
Probably.

**Closed** 2017-11-22 10:50 UTC
Labels: bug
