### ISSUE TITLE
Glitched text strings and windows crash the game

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12945] opened 2020-09-17 23:17 UTC
**OS:** Windows 10
**Version:** 0.3.0
**Commit/Build:** c72f547

The research & development window now not only displays weird text, but if you even attempt to access it via the finances tab, the game crashes. These bugs and crashes have been caused by a mistake made in a change to the files that produce the game's text strings, and that mistake is causing bugs and crashes like this one. DededeRob from the Roller Coaster & Friends Discord server also confirmed that the cheats menu is broken and crashes the game due to these same text bugs/glitches.

OpenShinx (A Wild Shinx) on the official OpenRCT2 Discord server also confirmed that the game crashed on him when he tried to use cut-away view, which confirms that these crashes from broken/glitched text strings are now making the game virtually unplayable. How? The launcher was supposed to update, but the first attempt to start up the game resulted in the game not starting up. This tells me that the launcher did not update correctly.

**Steps to reproduce:**
1. Load up or start up any game in any scenario.
2. Open the research & development window by pressing D or clicking on the icon at the top right corner of the screen.
3. Open up the finances window and attempt to open the research funding section. It will crash the game.
4. Accessing the cheats window will also crash the game.

**Dump file**
[60832ec0-7484-4e75-827d-f948ae84aebe(c72f547_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/5242396/60832ec0-7484-4e75-827d-f948ae84aebe.c72f547_x86-64.zip)

**Screenshots / Video:**
![Mirage Madness II 2020-09-17 16-08-04](https://user-images.githubusercontent.com/61885939/93537462-63543280-f900-11ea-9b76-5397624345b2.png)
Image 1 shows glitched text in the research funding window.
![Mirage Madness II 2020-09-17 16-08-18](https://user-images.githubusercontent.com/61885939/93537485-79fa8980-f900-11ea-9dd5-b400e10278a1.png)
Image 2 shows a completely blank finances window, including a blank research funding section. This screenshot was automatically generated when the game crashed.

Both screenshots were taken from my scenario [Africa - Oasis II （Mirage Madness II）](https://drive.google.com/file/d/1K8O_9QSxpBlCntMsICao81VSzDtQj24G/view?usp=sharing) right when I tried to play it.

**Comment by frutiemax** [comment] 2020-09-17 23:58
I cannot reproduce the bug on my side with same commit.

**Comment by rpstester** [comment] 2020-09-18 01:30
This bug and crash happened to me, too.

**Comment by frutiemax** [comment] 2020-09-18 01:32
I believe the launcher is incorrectly updating OpenRCT2.

**Comment by duncanspumpkin** [comment] 2020-09-18 07:30
Optimiser is causing this as it removed the formatter due to reasons which means the ptr to the arguments of these strings are missing.

**Comment by AaronVanGeffen** [comment] 2020-09-18 08:29
Fixed in #12961

**Closed by AaronVanGeffen** 2020-09-18 08:29 UTC
