### ISSUE TITLE
Where is the latest build 0.2.3 in the releases tab for Linux?

### ISSUE THREAD

**Issue by ich777** [OpenRCT2/OpenRCT2#9744] opened 2019-08-07 05:45 UTC
Hope i don't overlooked something but where is the latest build (0.2.3) in the 'releases' section for Linux?

Regards, ich777

**Comment by duncanspumpkin** [comment] 2019-08-07 21:00
https://github.com/OpenRCT2/OpenRCT2/pull/9548 isnt this this

**Comment by JarnoVgr** [comment] 2019-08-12 14:12
The release of v0.2.3 was kinda problematic as macOS and Linux builds weren't automatically built. macOS was built manually by @AaronVanGeffen .

**Comment by AaronVanGeffen** [comment] 2019-08-12 14:14
They were built: https://travis-ci.org/OpenRCT2/OpenRCT2/builds/556998142

Something went wrong transferring them to OpenRCT2.org, however.

**Comment by JarnoVgr** [comment] 2019-08-12 14:21
@AaronVanGeffen The problem is that releases weren't using https://openrct2.org builds before. The files were manually added to the GitHub releases page, which wasn't done for macOS and still isn't for Linux.

**Closed** 2020-05-26 07:30 UTC
Labels: Linux (OS)
