### ISSUE TITLE
Guests won't ride some covered flat rides in the rain

### ISSUE THREAD

**Issue by astraylife1** [OpenRCT2/OpenRCT2#22093] opened 2024-05-24 05:40 UTC
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.11 (6cb49d2 on develop)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Guests will not ride flat rides like the flying saucers, space rings, twist, etc while it's raining, despite the rides being underground or covered by scenery base blocks.

### Steps to reproduce

Build flat ride underground or cover it with base blocks
Guests will not ride when raining

**Comment by Gymnasiast** [comment] 2024-05-24 08:00
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/21440.

**Closed by Gymnasiast** 2024-05-24 08:00 UTC
Labels: bug
