### ISSUE TITLE
Guests getting stuck in front of a railroad crossing a path

### ISSUE THREAD

**Issue by SupraGL** [OpenRCT2/OpenRCT2#14340] opened 2021-03-16 22:45 UTC
**OS:** [Windows 7, does not apply]
**Version:** [e.g. 0.3.3]
**Commit/Build:** [e.g. 426e106]

Some railroad layouts make the guests being stuck in front of the railroad indefinitely while the railroad is open or in test mode, even if there is no train crossing the path. When the railroad is closed, the guests get unstuck. I have an example where the guests are stuck and another example where the guests are not stuck.

**Stuck Guests:**
![Broken](https://user-images.githubusercontent.com/33940430/111389095-c0019180-8686-11eb-8680-4269c1974514.PNG)

**Free Guests:**
![Fixed](https://user-images.githubusercontent.com/33940430/111389168-ddcef680-8686-11eb-8e80-2cc8b7734654.PNG)

**Saves with Stuck Guests and Free Guests (respectively named Broken and Fixed)**
[Guests Stuck Railroad.zip](https://github.com/OpenRCT2/OpenRCT2/files/6152589/Guests.Stuck.Railroad.zip)

**Comment by ocalhoun6** [comment] 2021-03-17 02:14
Duplicate of #10535

Though it would be really nice to see a solution to that. It's really annoying when it comes up.

**Comment by rik-smeets** [comment] 2022-09-21 07:29
I'll take a shot at this one too.

**Closed** 2022-09-23 20:58 UTC
Labels: bug

**Comment by CloudyMcDowd** [comment] 2023-03-30 09:25
I just had a train get stuck on a Mine Train Coaster (for no apparent reason); and the ride wasn't designated as broken down. Fixed by: closing the ride; reducing trains to one (which removed the stuck train); reopening the ride; then closing to restore the number of trains then reopening again. A bit of a faff, but it worked!

**Comment by Broxzier** [comment] 2023-03-30 09:33
That has nothing to do with guests waiting for railroad crossings. It sounds like your track just didn't manage to make it over a hill, likely because of there being fewer guests in the train (so lower mass, less energy), or them being distributed over the train unevenly. Not a bug.

**Comment by CloudyMcDowd** [comment] 2023-03-30 19:24
It was actually "Dynamite Blaster" from the Dynamite Dunes scenario -- a pre-built ride in that scenario. Sorry if it's a bit off-topic.
