### ISSUE TITLE
Building g2.dat fails with libpng 1.2

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#7075] opened 2018-01-23 03:36 UTC
**OS:** Ubuntu 16.04
**Commit/Build:** 9a362a8aa382334f04b88938490990d5adb00021

While running `fakeroot dpkg-buildpackage -b uc`, my latest build failed because:
`Added: /home/richard/OpenRCT2/resources/g2/icons/search.png
An assertion failed, please report this to the OpenRCT2 developers.
Version: OpenRCT2, v0.1.2 build 9a362a8 (DEBUG)
Location: PngRead:117
CMakeFiles/g2.dir/build.make:64: recipe for target 'g2.dat' failed
make[5]: *** [g2.dat] Aborted
make[5]: *** Deleting file 'g2.dat'`
On a separate line:
`openrct2: /home/richard/OpenRC
T2/src/openrct2/core/Guard.cpp:106: void Guard::Assert_VA(bool, const char *, __
va_list_tag *): Assertion `false' failed.`

This is hampering me from being able to try the latest changes, as I am unable to build g2.dat.

**Comment by janisozaur** [comment] 2018-01-23 08:31
Hmm, indeed. It even showed up on the offending commit, 6bf09e7abbe0f7b841279f655a21a5d5e7989463, from the [build job](https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/331585292#L830):

```
An assertion failed, please report this to the OpenRCT2 developers.
Version: OpenRCT2, v0.1.2 build 6dfff3b
Location: PngRead:117
```

But as this is at some stage post-build, the job was not marked as failing.

I also wonder why AppVeyor does not exhibit the same issue: https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.1.2.12722/job/fvo76323odoj2w1u

**Comment by janisozaur** [comment] 2018-01-23 08:38
I may have spoken too soon, #7071 is not to blame as the error can be seen much earlier. Probably ever since https://github.com/OpenRCT2/OpenRCT2/pull/6338, as https://github.com/OpenRCT2/OpenRCT2/pull/6362 is clean.

Additionally, there's this warning being written out:
```
Added: /home/travis/build/OpenRCT2/OpenRCT2/reImage is not palletted, it has bit depth of 4
Could not import image file: /home/travis/build/OpenRCT2/OpenRCT2/resources/g2/surface/glassy_recolourable.png
Canceling
sources/g2/track/railway/quarter_turn_3_tiles_sw_se_part_3.png
```

**Comment by janisozaur** [comment] 2018-01-23 08:56
@IntelOrca have you checked why AppVeyor does not report failure?

**Comment by IntelOrca** [comment] 2018-01-23 09:18
Because when running the command, there is no output and the exit code is 0.

**Comment by janisozaur** [comment] 2018-01-23 09:20
I can see that myself, but my question is: why is there no output and the exit code is 0?

**Comment by IntelOrca** [comment] 2018-01-23 09:23
I don't know.

**Comment by IntelOrca** [comment] 2018-01-23 09:25
Okay, it was because I was using .exe instead of .com. The output is:
```
Building: G:\git\github\OpenRCT2\bin\data\g2.dat
Added: G:\git\github\OpenRCT2\resources\g2\logo.png
Added: G:\git\github\OpenRCT2\resources\g2\logo_text.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\fast_forward.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\game_speed_indicator.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\game_speed_indicator_double.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\twitch.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\map_gen_land.png
Added: G:\git\github\OpenRCT2\resources\g2\7.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\zoom_in.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\zoom_in_background.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\zoom_out.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\zoom_out_background.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\map_gen_trees.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\map_gen_noise.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\large_scenery.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\small_scenery.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\paths.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_close_off.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_close_off_pressed.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_close_on.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_close_off_pressed.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_test_off.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_test_off_pressed.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_test_on.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_test_on_pressed.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_open_off.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_open_off_pressed.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_open_on.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\rct1_open_on_pressed.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\29.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\30.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\31.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\32.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\cheats.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_2_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_3_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_4.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_2_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_3_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_2_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_3_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_4.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_2_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_3_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_lift_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_lift_2_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_lift_3_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_lift_4.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_lift_2_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_lift_3_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_lift_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_lift_2_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_lift_3_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_lift_4.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_lift_2_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_lift_3_2.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\58.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\server_password.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\multiplayer.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_diagonal_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_diagonal_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_diagonal_3.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_diagonal_4.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_diagonal_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_diagonal_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_diagonal_3.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_diagonal_4.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_diagonal_lift_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_diagonal_lift_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_diagonal_lift_3.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\flat_to_steep_diagonal_lift_4.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_diagonal_lift_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_diagonal_lift_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_diagonal_lift_3.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\steep_to_flat_diagonal_lift_4.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\sort.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\copy.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\paste.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\tab_disabled.png
Added: G:\git\github\OpenRCT2\resources\g2\track\intamin\booster_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\intamin\booster_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\bm\booster_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\bm\booster_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\booster_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\junior\booster_2.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\mute.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\mute_pressed.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\unmute.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\unmute_pressed.png
Added: G:\git\github\OpenRCT2\resources\g2\track\mini\booster_1.png
Added: G:\git\github\OpenRCT2\resources\g2\track\mini\booster_2.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\quarter_turn_3_tiles_sw_se_part_3.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\gravel_sw_ne.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\gravel_nw_se.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\grooved_sw_ne.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\grooved_nw_se.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\grooved_sw_ne_trans.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\grooved_nw_se_trans.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\grooved_end_ne_trans.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\grooved_end_se_trans.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\grooved_end_nw_trans.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\grooved_end_sw_trans.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\grooved_end_sw_ne_trans.png
Added: G:\git\github\OpenRCT2\resources\g2\track\railway\grooved_end_nw_se_trans.png
Added: G:\git\github\OpenRCT2\resources\g2\icons\search.png
Added: G:\git\github\OpenRCT2\resources\g2\surface\glassy_recolourable.png
Added: G:\git\github\OpenRCT2\resources\g2\surface\selection_edge_nw.png
Added: G:\git\github\OpenRCT2\resources\g2\surface\selection_edge_ne.png
Added: G:\git\github\OpenRCT2\resources\g2\surface\selection_edge_sw.png
Added: G:\git\github\OpenRCT2\resources\g2\surface\selection_edge_se.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\brick.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\rust.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\white_stucco.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\yellow_stucco.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\red_stucco.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\purple_stucco.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\green_stucco.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\brown_sandstone.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\grey_sandstone.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\skyscraper_a.png
Added: G:\git\github\OpenRCT2\resources\g2\edge\skyscraper_b.png
Finished
```

**Comment by AaronVanGeffen** [comment] 2018-02-02 22:54
It's good that you've found a workaround, but disabling all asserts is a little drastic… The one that's being triggered is in `Imaging.cpp`, on line 117:
```cpp
// 32-bit PNG (with alpha)
Guard::Assert(rowBytes == pngWidth * 4, GUARD_LINE);
```

The assert does not trigger when building `g2.dat` on my end, however. Possibly related to whatever version of libpng either of us is using? I'm using version 1.6.34 over here.

**Comment by RQWorldblender** [comment] 2018-02-03 04:24
I have two libpng versions installed:
- libpng12-0 1.2.54-1ubuntu1
- libpng16-16 1.6.20-2
My binaries compile with the former.

**Comment by AaronVanGeffen** [comment] 2018-02-03 10:19
Could you try compiling and building g2 with the latter, then?

**Comment by RQWorldblender** [comment] 2018-02-11 05:09
Unfortunately, I did try to compile again, but many of the dev packages in Ubuntu 16.04 depend on libpng-dev instead of libpng16-dev, and I'm unable to continue as I must also install libfreetype6-dev, which also depends on libpng-dev. However, I seem to not encounter this problem in later Ubuntu versions.
This is another message I may receive during g2 building:
`Image is not palletted, it has bit depth of 4`
`Could not import image file: /home/richard/OpenRCT2/resources/g2/surface/glassy_recolourable.png`
`Canceling`
`An assertion failed, please report this to the OpenRCT2 developers.`
`Version: OpenRCT2, v0.1.2 build f431ecd (DEBUG)`
`Location: PngRead:118`
This error appears only if I disabled the assertion from Guard.cpp. I wonder if the offending image itself is the problem, in which it needs to be altered.
Overall, I really think I need to upgrade my Ubuntu version just to keep up with OpenRCT2 code without modification to the source code, but I want to wait until 18.04 becomes stable.

**Comment by AaronVanGeffen** [comment] 2018-02-11 12:08
Hmm, that file was introduced after #6362 was merged, which is the PR that introduced that assert. While I can confirm it has a bit depth of 4, it seems to work just fine on my end — no assertion triggers.

@janisozaur Any ideas?

**Comment by janisozaur** [comment] 2018-02-12 07:28
I was not able to immediately reproduce it on my system, but I have libpng12 and libpng16 available on my system, so I'll verify if that's a case of using older library.

**Comment by Gymnasiast** [comment] 2018-02-18 19:52
The error saying it isn't paletted is odd: it's supposed not to be paletted! If you look in the sprites.json file, you will notice it has 'palette: keep' specified.

**Closed** 2018-03-09 18:33 UTC
Labels: bug
