### ISSUE TITLE
Game reports drink stall is inaccessible but it isn't

### ISSUE THREAD

**Issue by felipeek** [OpenRCT2/OpenRCT2#18637] opened 2022-11-20 03:20 UTC
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.2 (8ceea45) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

I have a drink stall and every month I receive a message saying it is not accessible, but it is accessible

### Steps to reproduce

I really don't know how to reproduce it, but I am attaching an screenshot and the save file with the bugged drink stall

### Attachments

![Untitled](https://user-images.githubusercontent.com/3253502/202881074-4873ecd6-5bc2-425a-9b0d-f35fc12ed922.png)
[drink2 bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/10048378/drink2.bug.zip)

**Comment by ocalhoun6** [comment] 2022-11-20 04:11
A) Is there any chance you've been messing around with path connections using the tile inspector?

B) It *looks* like a peep is using it right now in the screenshot, but just to be sure, have you looked at the stalls stats and/or money tab and confirmed that it is indeed able to sell drinks to peeps?

**Comment by felipeek** [comment] 2022-11-20 05:19
Hi @ocalhoun6 

A) I never used the tile inspector, I just found out what it was by googling it 😄 

B) Yes, I confirmed it. The message has been appearing since I first placed the stall, but it has already sold 92 drinks.

C) I searched for thoughts about the stall and there are none. In fact, as I said the message has been appearing since I first placed it, so it should not be the case.

**Comment by cheweytoo** [comment] 2022-11-20 16:43
I've let the attached park run for a year in f4e0480 develop and haven't seen that message yet.

@felipeek: Could you try your park with a build from https://openrct2.org/downloads/develop/latest to see if your issue still shows up in it?

**Comment by Gymnasiast** [comment] 2022-11-20 17:31
I see two drinks stalls in that screenshot. One of those is on the left, right next to the information kiosk, and it has no path leading up to it.

**Comment by cheweytoo** [comment] 2022-11-20 18:17
Oh, good find! - They're both "Drinks Stall 2" and share the same stats, so there's been some cloning going on…

**Comment by felipeek** [comment] 2022-11-20 18:26
Yes, very good finding. I don't know how but I have never seen that drink stall there 😄 . Both stalls are called "Drink Stall 2" (not sure how they got the same name), and when the message appears and I click on the "red arrows icon" to locate the stall, it always points to the one that I showed in the screenshot... that's why I encircled it.

It seems that even though they are different stalls, they share the same stats as @cheweytoo said. They also share the same name.. if I change the name of one, the other changes as well.

I didn't do any fancy edits in this park whatsoever, I simply build a regular drink stall... I might have misclicked and built another one there somehow, but I have no idea how I ended up in this situation. Very weird... Do you guys know possible actions that I might have taken mistakenly that could have lead to this situation?

**Comment by ocalhoun6** [comment] 2022-11-20 18:32
Sounds a lot like #17028 but with stalls this time instead of flat rides.

**Comment by Gymnasiast** [comment] 2022-11-21 06:38
That bug did also affect stalls. So if @felipeek started this park on a slightly older version of OpenRCT2, that could very well have been the cause. The only other two possibilities I can think of are using the Scenery Manager, or the Tile Inspector, but felipeek has said they didn’t use tools like those.

**Comment by duncanspumpkin** [comment] 2022-11-21 21:11
I think its safe then to close this issue.

**Closed by duncanspumpkin** 2022-11-21 21:11 UTC
Labels: bug
