### ISSUE TITLE
Title Screen rapidly switching between different parks

### ISSUE THREAD

**Issue by ipatix** [OpenRCT2/OpenRCT2#6289] opened 2017-09-20 15:57 UTC
**OS:** Debian Stretch
**Version:** 0.1.2-develop
**Commit/Build:** a24f2fb

It seems like the current builds will rapidly (multiple times a second) change between the different title screen scenes not looking very pleasent.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Compile the specified build
2. Start the game and see the mess

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by IntelOrca** [comment] 2017-09-20 16:40
You will need to update your title sequences.

**Comment by Invictaz** [comment] 2017-09-20 23:24
Also on the Android build

**Comment by janisozaur** [comment] 2017-09-21 07:20
@Invictaz you are using old build, that was fixed.

**Comment by janisozaur** [comment] 2017-09-21 07:23
I'm going to close this on the grounds of it being a known issue that's caused by using old title sequence files.

**Closed by janisozaur** 2017-09-21 07:23 UTC
Labels: help
