### ISSUE TITLE
Staff Walk off Paths with Connection Flag Turned On but no Adjacent Path, whereas Peeps do not

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#7418] opened 2018-04-15 17:05 UTC
In situations where you have a path with an edge that is "connected" to an adjacent path, but there is actually no adjacent path, peeps turn around and do not walk off the edge. Staff members keep walking, and end up off the path. Should these two behaviors be the same (either they both keep walking, or both turn around)?

**Comment by AaronVanGeffen** [comment] 2018-04-15 17:39
Sounds like a duplicate of #7402.

**Comment by Broxzier** [comment] 2018-04-15 17:44
It's related, but not the same issue. #7402 is a side-effect of a bug causing staff to walk off paths, and this issue is explicitly about staff behaving differently from guests in such cases.

**Comment by saxman1089** [comment] 2018-04-15 18:24
It's mentioned in #7402 but not stated as an issue. For the record, I don't think peeps or staff should be able to walk off these paths, because there are legitimate uses for enabling the connections without having adjacent paths (for example, only having benches on one side of a single wide path).

**Comment by ocalhoun6** [comment] 2018-04-15 20:33
Fixing this issue would 90% solve #7402, though. 

If it weren't for staff wandering off the path, the bug in #7402 would just be a very minor cosmetic issue.

**Closed** 2018-05-19 17:55 UTC
Labels: pathfinding
