### ISSUE TITLE
feature request: weather effect snow

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [OpenRCT2/OpenRCT2#10717] opened 2020-02-16 15:40 UTC
Hi

I don't know if feature requests are possible but I would like to have snow weather effect added.

This would work by making 2 things:

1) animated snow: similar how rain is animated now. There could be a difference between small or big snowflakes. Of course this weather is only occuring in the typical months in winter.

I found somebody made it but I'm no developer and don't know why it was not added to the game:

https://github.com/OpenRCT2/OpenRCT2/pull/3636

2) ground tiles (for the grass) that replace the current ones when it's snowing. Snow will add up on the tiles and when snowing is stopped, the tiles slowly return to normal. 

See here (somebody made tiles for snow):

https://imgur.com/BX7wqwu

I think this weather effect snow is a real cool addition for the game. It's a new thing because the original game doesn't have it and it really looks great (tiles in combination with animated snow).

It could also be very cool to use in combination of custom made objects and rides with a 'christmas theme'. In this way, cool winter parks could be constructed!

Thanks for reading and I hope a developer wants to make this!

best regards,
Jessica

**Comment by jessicajonesunitedkingdom** [comment] 2020-02-16 16:16
Some additional github issues about this topic. I think snow never was added but I don't know why.
One person did already work on it. Others talked about the idea.

See:

https://github.com/OpenRCT2/OpenRCT2/issues/3576

https://cloud.githubusercontent.com/assets/10356800/15232985/d5a77e44-189c-11e6-82d1-807f662318c0.gif


https://github.com/OpenRCT2/OpenRCT2/issues/2350


Also look here in the comments of the source code:

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Climate.cpp

// There is actually a sprite at 0x5A9C for snow but only these weather types seem to be fully implemented
const WeatherState ClimateWeatherData[6] = {
    { 10, WEATHER_EFFECT_NONE, 0, RAIN_LEVEL_NONE, SPR_WEATHER_SUN },         // Sunny
    { 5, WEATHER_EFFECT_NONE, 0, RAIN_LEVEL_NONE, SPR_WEATHER_SUN_CLOUD },    // Partially Cloudy
    { 0, WEATHER_EFFECT_NONE, 0, RAIN_LEVEL_NONE, SPR_WEATHER_CLOUD },        // Cloudy
    { -2, WEATHER_EFFECT_RAIN, 1, RAIN_LEVEL_LIGHT, SPR_WEATHER_LIGHT_RAIN }, // Rain
    { -4, WEATHER_EFFECT_RAIN, 2, RAIN_LEVEL_HEAVY, SPR_WEATHER_HEAVY_RAIN }, // Heavy Rain
    { 2, WEATHER_EFFECT_STORM, 2, RAIN_LEVEL_HEAVY, SPR_WEATHER_STORM },      // Thunderstorm
};

Does this mean the original game had a snow sprite included but not used it in the game?

**Comment by AaronVanGeffen** [comment] 2020-02-16 16:37
Duplicate of #2350.

> Does this mean the original game had a snow sprite included but not used it in the game?

This most likely carried over from Locomotion. The games have their engine in. common

**Closed** 2020-02-16 16:38 UTC
Labels: duplicate

**Comment by IntelOrca** [comment] 2020-02-16 18:23
Unfortunately the OP for #3576 never pushed their changes which is a shame because the screenshots looked promising.

**Comment by brettpenzer123** [comment] 2020-02-19 03:12
I guess I'm back?

**Comment by thenamelessone1** [comment] 2020-02-19 23:43
Welcome back!
