### ISSUE TITLE
Opening 

### ISSUE THREAD

**Issue by TyandorX** [OpenRCT2/OpenRCT2#13864] opened 2021-01-18 22:22 UTC
[0cb0cee9-d3e1-4d67-9b5a-6de6eb5d1639(bd27046_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/5832591/0cb0cee9-d3e1-4d67-9b5a-6de6eb5d1639.bd27046_x86-64.zip)

**OS:** [Windows 10]
**Version:** [0.3.2]
**Commit/Build:** develop-bd27046 (same issue earlier develop builds, release 0.3.2 does work)

When I try to open any save game the game starts loading and then crashes at the moment the game should visible and playable. I am able to open basic scenarios though.

- [ ] Specific to multiplayer?
No
**Steps to reproduce:**
1.  just load any save (probably with custom objects)

**Dump file**
enclosed

**Comment by spacek531** [comment] 2021-01-18 23:41
Do you have any plugins? If you do, try removing the plugins.

**Comment by Gymnasiast** [comment] 2021-07-29 13:20
Cannot reproduce this (certainly not with “any save”), and OP has not answered the follow-up question, so I’ll have to close this.

**Closed by Gymnasiast** 2021-07-29 13:20 UTC
