### ISSUE TITLE
Resync button

### ISSUE THREAD

**Issue by Nubebuster** [OpenRCT2/OpenRCT2#14801] opened 2021-06-01 21:07 UTC
When I play multiplayer I get a network desync about every minute or so. It would be nice to have a button appear on desync that, if clicked, reconnects you. This would make the multiplayer experience a lot more pleasurable while being very easy to implement.

**Comment by Margen67** [comment] 2021-06-01 21:17
#14563

**Comment by James103** [comment] 2021-06-01 21:22
Actually a duplicate of #2695, already vetoed (will not implement).

**Comment by YJSoft** [comment] 2021-06-02 00:48
> Only way to resync is to download whole map again(which is not different from reconnect)
> Also, we should remove cause of desync, not adding "Resync" button.

From https://github.com/OpenRCT2/OpenRCT2/issues/14563#issuecomment-831174432

Please search before making new issue. There are already four issues about resync button. (#2695, #3134, #5512, 14563)

**Comment by Nubebuster** [comment] 2021-06-02 02:32
Since this is something pretty easy to implement and since other people are also requesting this, and since the problem of desyncs dates has been around for 5 years now, why is it not being added?

It would make this game a lot more playable.

**Comment by tupaschoal** [comment] 2021-06-02 02:39
Desyncs are an undesirable state, a "resync" button sounds too much like a workaround.

Note that even though one issue comment mentioned it as not being "too hard", it doesn't mean it's too easy. Do remember this is a community maintained project and people improve the game on their spare time.

**Closed** 2021-06-02 11:16 UTC
Labels: duplicate
