### ISSUE TITLE
Guests Bunching Up in Certain Areas

### ISSUE THREAD

**Issue by GravityUnown** [OpenRCT2/OpenRCT2#3265] opened 2016-04-08 02:04 UTC
Mac OS X 10.10.5
0.0.4.0 build b8fc3b2

I honestly don't know what's happening, but at some points while playing the AI of the guests will randomly bunch up into huge, dense groups of very small parts of pathways, and even though all the paths are connected the AI is just drawn to very specific areas sometimes.

**Steps to reproduce:**
1. Have a lot of guests in your park?
2. Make a lot of paths?

SCREENSHOT:
https://i.gyazo.com/f13334676249466c5bb2123bfd83dd74.png

**Comment by fromthere** [comment] 2016-04-08 02:25
Duplicate of #396 , #2499

**Comment by GravityUnown** [comment] 2016-04-08 02:30
I have noticed those posts from a while ago, but the weird thing is no one in my park has been complaining about getting lost, I have noticed them leaving the dense area, but different people go to that same area so it never lessens.

**Comment by Gymnasiast** [comment] 2016-04-08 07:05
Seen the screenshot, but that is just how the pathfinder works. It will frequently send most people along one side of a double-width path.

The problem is amplified by your path layout: one single-width path leads to several rides, rather than multiple double-width paths. I suggest you look at parks from other people for inspiration.

**Closed** 2016-04-08 07:58 UTC
Labels: non-bug

**Comment by GravityUnown** [comment] 2016-04-08 11:48
Hi, I did experiment and add an additional path to reduce the clutter, and eventually the dense area did get neutralized. Thank you, and I apologize for the inconvenience. I will keep that in mind in the future.

**Comment by Gymnasiast** [comment] 2016-04-08 11:57
No problem, and don't be afraid to ask things. If you're unsure, you can also use the [dev chat](https://gitter.im/OpenRCT2/OpenRCT2) to ask your question.
