### ISSUE TITLE
command line and parkobj sprite builders differ significantly

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#16747] opened 2022-03-04 07:25 UTC
### Operating System

Windows 10

### OpenRCT2 build

most versions

### Describe the issue

Command line sprite building and parkobj sprite building use different language and have different features. This is a problem, for example, when using `sprite exportalldat` and pasting the offsets into a `sprites.json` file and running `sprite build` on the file. Command line sprite uses "x_offset" and "y_offset" to define the offset for the sprite while parkobj sprite uses "x" and "y". Command line sprite does not have atlas import while parkobj sprite does.

The import and export code should be ironed out to have the same functionality.

### Area(s) with issue?

Building the game

### Steps to reproduce

1. run `sprite exportalldat`
2. the output uses "x" and "y" instead of "x_offset" and "y_offset"

**Comment by Gymnasiast** [comment] 2022-03-04 21:39
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/12045.

**Closed by Gymnasiast** 2022-03-04 21:39 UTC
Labels: bug
