### ISSUE TITLE
Reseting path type when a new client joins in multiplay

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2931] opened 2016-02-14 09:12 UTC
When I'm building path with opening the path window during multiplay, if a new client joins, then path type re-selected as the first one.

**Comment by IntelOrca** [comment] 2016-02-14 10:50
Probably duplicate of #2912.

**Comment by telk5093** [comment] 2016-02-14 10:53
I'm saying just when new client joins in **Multiplay**. Nevertheless, do you think that it is duplicate of #2912? If so, I feel sorry for duplicated issue posting.

**Closed** 2016-05-15 18:08 UTC
Labels: investigate
