### ISSUE TITLE
"Same price throughout park" flag doesn't function properly

### ISSUE THREAD

**Issue by emwedekind** [OpenRCT2/OpenRCT2#17987] opened 2022-09-08 01:18 UTC
### Operating System

Windows 11 Home

### OpenRCT2 build

OpenRCT2, v0.4.1-155-g9e1b24d (9e1b24d on develop) provided by GitHub

### Describe the issue

When setting "same price throughout park" to shops and stalls, nothing seems to happen. Changing the price of one shop doesn't affect the rest of them, and vice versa. Not sure what causes this or how to fix it.

### Steps to reproduce

![Alpine Adventures 2022-09-07 20-15-25](https://user-images.githubusercontent.com/71282551/189012208-b2f8ffc4-b574-48ec-a6bd-e9ddf5489a8a.png)

Just try setting the flag as shown here.

**Comment by karst** [comment] 2022-09-08 02:03
I cannot reproduce on the latest version. Can you [update to the latest version of develop](https://openrct2.org/downloads/develop/latest)?

**Comment by Gymnasiast** [comment] 2022-09-08 20:33
Yup, seems to be a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/17746, which was solved not long after it was introduced.

Please, **always** update to the latest develop first before reporting a bug. Many bugs get solved within a few days.

**Closed** 2022-09-08 20:34 UTC
Labels: invalid/incomplete
