### ISSUE TITLE
Open rct 2 save bug

### ISSUE THREAD

**Issue by Legotown55** [OpenRCT2/OpenRCT2#17961] opened 2022-09-04 09:34 UTC
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.1-268-ge9f7f18 (e9f7f18 on develop) provided by GitHub

### Describe the issue

Every so oftern the game will not save and chash

### Steps to reproduce

1 Start a new game
2 play for a long time
3 every so offtern the game will not save and chash

**Comment by Gymnasiast** [comment] 2022-09-09 18:01
Duplicate of #17664. It’s right on top of the page:

![afbeelding](https://user-images.githubusercontent.com/1478678/189415301-c57dd639-8add-426d-ae1c-0ba2b76aa5d5.png)

**Closed by Gymnasiast** 2022-09-09 18:01 UTC
Labels: bug
