### ISSUE TITLE
BACKTRACE 44373f rct_peep::UpdateRideAdvanceThroughEntrance

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8184] opened 2018-10-28 23:23 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/44373fd168b502b7a853e8c80e5784c4bb31e5adcb57c7022aa0c966cd3f9841?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sun Oct 28 2018 23:17:51)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 590196b: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guard::Assert_VA -> Guard::Assert -> rct_peep::UpdateRideAdvanceThroughEntrance -> rct_peep::UpdateRide -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:31
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8462

**Closed by janisozaur** 2019-02-02 22:31 UTC
Labels: backtrace.io, crash
