### ISSUE TITLE
Shops & Stalls placement bug (with sprite clipping)

### ISSUE THREAD

**Issue by Syst3mSh0ck** [OpenRCT2/OpenRCT2#20870] opened 2023-10-10 21:07 UTC
### Operating System

Windows 10 Enterprise LTSC 2019 (Version 17763.4851 64-bit)

### OpenRCT2 build

OpenRCT2, v0.4.6 (b40b5da) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Nice work; but there is an issue concerning Shops & Stalls intermittently appearing graphically clipped by other stalls and rotating the camera results in the shop/stall physically moving to another grid location. The issue occurs intermittently with a new park but easily reproduceable with scenarios. It is easy to replicate and unfortunately deleting and replacing the object does not fix the problem. Impacted objects are unreachable by peeps. Save file attached.

### Steps to reproduce

Start a New Game using any park then build Shops & Stalls next to each other. Eventually you will encounter some that are graphically clipped and rotating the camera results in the shop/stall physically moving to another grid location.

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/4252736/e92e780e-7929-4b37-81e8-938ff181aa97)
![image](https://github.com/OpenRCT2/OpenRCT2/assets/4252736/b138b097-c2fa-43a7-a6a2-984a9bcf1a3a)
[Electric Fields (shops & stalls clipping and placement bug).zip](https://github.com/OpenRCT2/OpenRCT2/files/12861746/Electric.Fields.shops.stalls.clipping.and.placement.bug.zip)

**Comment by BodocCalado** [comment] 2023-10-10 21:51
This doen't look like a bug to me. The shops, that are appearing glitched, are one tile in front and a few above the other shops. You can see wooden platforms under these shops but no supports because of the paths underneath.

**Comment by Syst3mSh0ck** [comment] 2023-10-10 22:19
> This doen't look like a bug to me. The shops, that are appearing glitched, are one tile in front and a few above the other shops. You can see wooden platforms under these shops but no supports because of the paths underneath.

It's clearly a bug. Shops & Stalls should not appear clipped or move grid location upon camera rotation. They're also unreachable by peeps. This doesn't happen with vanilla.

**Comment by BodocCalado** [comment] 2023-10-10 22:25
These in-front-and-above shops do not clip. They are just in front of the shops standing on the ground. The sops are unreachable by peeps because they are not connected to path underneath.
Try making the same screenshot but with the path removed. Also enable height-marks for rides please.

**Comment by Syst3mSh0ck** [comment] 2023-10-10 22:41
I've removed the paths and now they appear in front and above like you've said. I built all of these shops in a straight row on level ground, so it doesn't make sense that they're elevated and moved forward when viewed from a different angle. See below:
![image](https://github.com/OpenRCT2/OpenRCT2/assets/4252736/cf202024-db4d-4b28-991d-f29bcb10d858)
![image](https://github.com/OpenRCT2/OpenRCT2/assets/4252736/9279e419-d696-4e17-a06b-0e768231baa0)
Sorry but how do I enable height-marks? I've had a look in the options but it's not there. Thanks.

**Comment by BodocCalado** [comment] 2023-10-10 22:51
Height marks are in the view options (eye icon). Put they are superfluous now because the supports show the elevation.
The moment it went "wrong" is: when you place ride/shop/path, but another ride/shop is at the location of your cursor, it just puts the new one ontop of the existing one. Supports are not shown for the height interval that the ride/shop/path needs for clearance (clear of supports).
So imo there is no bug or glitch present and the issue is "Solved" or is there?

**Comment by Syst3mSh0ck** [comment] 2023-10-10 23:05
I think you're right, thanks for your help. I guess I didn't click the correct locations and because supports are not shown when a footpath is underneath, I couldn't really see that it was in front and above until rotating. It would be good if supports could still be shown in someway when there is a footpath underneath. Thanks.

**Comment by ZehMatt** [comment] 2023-10-11 18:59
Closing this as this is not a bug and behaves the same way as the vanilla game. Feel free to create a feature request regarding the supports, I also find this a bit odd.

**Closed by ZehMatt** 2023-10-11 18:59 UTC
Labels: bug
