### ISSUE TITLE
Superfluous messages in the Message log when loading save after starting new scenario

### ISSUE THREAD

**Issue by galfisk** [OpenRCT2/OpenRCT2#17521] opened 2022-07-07 12:39 UTC
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4) provided by GitHub

### Describe the issue

When loading some saved games after starting a new scenario, tons of messages are in the Recent Messages log that don't belong there, all dated March 1st, all about new rides or vehicles. Additionally, if one clicks on a message related to a ride not available in the scenario, the New Ride windows opens with the incorrect tab (for instance, clicking New vehicle: rowing boats" sends me to the Shops&Stalls tab in a save where the boat hire is not available.
Attached screenshots shows the same save loaded with and without the issue.

### Steps to reproduce

1. Start OpenRCT2
2. Start a new scenario "Factory Capers"
3. Load the attached save "Dusty Greens"
4. Open the Recent Messages window

### Attachments

[Dusty Greens.zip](https://github.com/OpenRCT2/OpenRCT2/files/9063542/Dusty.Greens.zip)
![Dusty Greens 2022-07-07 14-34-38](https://user-images.githubusercontent.com/31153158/177774642-a29ca404-6862-43c1-8318-d79791c98025.png)
![Dusty Greens 2022-07-07 14-34-38](https://user-images.githubusercontent.com/31153158/177774759-a1116412-6a21-4012-a07e-d8f423321b57.png)

**Comment by James103** [comment] 2022-07-07 12:43
> 3\. Load the attached save "Dusty Greens"

Can you please re-upload that park file?

**Comment by galfisk** [comment] 2022-07-07 12:52
[Crazy Castle (2).zip](https://github.com/OpenRCT2/OpenRCT2/files/9063723/Crazy.Castle.2.zip)
Ok, rezipped and reuploaded.

**Comment by galfisk** [comment] 2022-07-07 12:54
(is the inability to upload .park files directly an inherent GitHub limitation?)

**Comment by galfisk** [comment] 2022-07-07 12:55
Seems like I sent the buggy screenshot twice as well, here's the unbuggy one.
![Dusty Greens 2022-07-07 14-35-53](https://user-images.githubusercontent.com/31153158/177778502-88833dc4-79b2-41bb-840f-c3c6e2a15ecf.png)

**Comment by SpartanFrederic104** [comment] 2022-07-14 05:45
If anyone also noticed in the buggy screenshot, the ride researched messages are now once again showing new ride types as new vehicles (#13236 all over again?). Except this time, every non-flat ride type except for the tower rides is affected too.

**Comment by lalip** [comment] 2022-08-10 06:15
Solved by #17705 which closed a duplicate of this issue

**Closed** 2022-08-10 09:57 UTC
Labels: bug

**Comment by spazzylemons** [comment] 2022-12-30 16:17
Still experiencing this, using version v0.4.3 on Linux
![Lightning Peaks 2022-12-30 11-14-43](https://user-images.githubusercontent.com/25674682/210090776-0faf52eb-6516-4dc6-bfac-5cc8627c866f.png)

**Comment by spazzylemons** [comment] 2022-12-30 16:21
Attaching the .park file as well
[park.zip](https://github.com/OpenRCT2/OpenRCT2/files/10325484/park.zip)

**Comment by lalip** [comment] 2023-01-03 20:37
I think this issue shouldn't have been closed. I'm sorry! I must have been confused by the "unbuggy" screenshot...

In my limited testing, this appears to happen when the park is saved while a notification message is still visible in the bottom bar. The messages aren't stored in the .park file itself (though they are in spazzylemons' park - did you save it again?)
Reloading the park in-place after dismissing all the superfluous messages seems to get rid of them.
[Have another test subject.](https://github.com/OpenRCT2/OpenRCT2/files/10339599/17521.zip)

It's worth noting that the park in the OP doesn't reproduce this issue on my end (815d349)
