### ISSUE TITLE
BACKTRACE 4f0e0c track_block_get_next -> vehicle_update_track_motion_mini_golf

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8297] opened 2018-11-25 21:32 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/4f0e0cc4a32a1650cd8d90a45cbab5b0b947a0ebddf94a1a5282c77a8d53ec11?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sun Nov 25 2018 21:32:14)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 18f1fab: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>track_block_get_next -> vehicle_update_track_motion_mini_golf -> vehicle_update_travelling -> vehicle_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:14
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8398

**Closed by janisozaur** 2019-02-02 22:14 UTC
Labels: backtrace.io, crash
