### ISSUE TITLE
Number of vehicles is incorrectly calculated when opting to paint different vehicles

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#4861] opened 2016-12-09 18:29 UTC
**OS:** Ubuntu 16.04
**Commit/Build:** d1d6be0b9316fd8a0322024b55ef5fbb0f3f7d7f

When going to color options for certain rides, and then the "Different colors per vehicle" option is selected, the number of vehicles can be incorrectly calculated by having an invisible front and back vehicle, which can affect the car shown in the second tab of a ride window. I have only confirmed this with the Junior Roller Coaster, but there may be other rides that have this same problem. Most of the rides that have at least 3 trains do not suffer from this, but the problems is more obvious for rides that have cars that support less than 3 vehicles per car, though this doesn't seem true for all rides like this.

Rides, vehicles (if none specified, only one kind is implied) I tested to have this problem (only the official base game and official expansion packs were tested):
- Junior Roller Coaster, all kinds of vehicles
- Reverse Roller Coaster, all kinds of vehicles (although all the vehicles show up, the front and rear 'vehicles' are not really so, but just attachments to the main one, so these should not be colorizable. Additionally, these 'vehicles' show up on top of the main one in the second tab preview, when they should be on the bottom of it.)
- Miniature Railroad, trams only
- Wild Mouse, all kinds except spinning wild mouse (on a side note, when switching from this kind to another, the new vehicles may not immediately show up, and sometimes be given unusual color combinations)
- Wooden Wild Mouse, all kinds of vehicles
- Water Coaster, all kinds of vehicles
- Splash Boats, all kinds of vehicles
- Tunnel of Horror, all kinds of vehicles
- Car Ride, all kinds of vehicles
- Mini Helicopters

**Steps to reproduce:**
1. If a ride of the above is not in a scenario yet, build one of those.
2. Open that ride's window.
3. Go to the colour options.
4. Change "All vehicles in same colors" to "Different colors per vehicle".
5. The problem will become apparent after the option change, as the first vehicle to be shown is an invisible one, and the sames with the rearmost vehicle.
6. The colors from the front invisible 'vehicle' will show up in the second tab, but the actual colors will start from the second vehicle.
7. I can derive a formula for this problem: the index colors that will show up are between (# of vehicles) +1 and (# of vehicles) - 1.

**Screenshots:**
![gentle glen 2016-12-09 11-33-00](https://cloud.githubusercontent.com/assets/13372387/21059414/e187d158-be07-11e6-87c4-523fd733313a.png)
![gentle glen 2016-12-09 11-33-08](https://cloud.githubusercontent.com/assets/13372387/21059415/e196fa8e-be07-11e6-8e02-619a0cef8959.png)

**Comment by X123M3-256** [comment] 2016-12-10 22:53
This is a possible duplicate of [#2614](https://github.com/OpenRCT2/OpenRCT2/issues/2614).

You're right, this is caused by trains that have invisible cars. I think detecting default vehicles with such cars ought to be possible somehow (don't know how), because I noticed the game behaving differently (i.e crashing) when I made a train out of default invisible cars vs custom invisible cars.

**Comment by Gymnasiast** [comment] 2016-12-29 09:25
This is indeed a duplicate of #2614. You can track the status of this bug there.

**Closed by Gymnasiast** 2016-12-29 09:25 UTC
Labels: duplicate
