### ISSUE TITLE
corrupted save with custom json object

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#11265] opened 2020-04-11 04:00 UTC
**OS:** Windows 10
**Version:** 0.2.5 DEBUG

I attempted to create a modified json object to test out my animation modifications branch. Selecting the object with the park loaded works fine, and the object behaves as expected.

When I save the game, I get this message:

![image](https://user-images.githubusercontent.com/3454156/79034817-d1384900-7b6d-11ea-9c8c-fc6093c1e20e.png)

Attempting to load the game brings me to the title screen.

[save game in question](https://github.com/OpenRCT2/OpenRCT2/files/4464008/modified.object.tests.zip)

The object attached is below:

```json
{
    "id": "rct2.asdf1",
    "authors": ["Spacek"],
    "version": "1.0",
    "originalId": "0000008D|SPACEKLOL|00000000",
    "sourceGame": ["custom"],
    "objectType": "ride",
    "properties": {
        "type": "miniature_railway",
        "category": "transport",
        "tabScale": 0.5,
        "hasShelter": true,
        "playDepartSound": true,
        "noCollisionCrashes": true,
        "minCarsPerTrain": 3,
        "maxCarsPerTrain": 8,
        "numEmptyCars": 2,
        "defaultCar": 2,
        "headCars": [
            0,
            1
        ],
        "carColours": [
            [
                ["yellow", "bordeaux_red", "bright_yellow"]
            ],
            [
                ["dark_green", "dark_brown", "yellow"]
            ],
            [
                ["bordeaux_red", "dark_green", "yellow"]
            ]
        ],
        "cars": [
            {
                "rotationFrameMask": 31,
                "spacing": 296344,
                "mass": 3000,
                "animation": 1,
                "frictionSoundId": 31,
                "soundRange": 3,
                "poweredAcceleration": 240,
                "poweredMaxSpeed": 18,
                "drawOrder": 5,
                "frames": {
                    "flat": true,
                    "gentleSlopes": true,
                    "diagonalSlopes": true
                },
                "VEHICLE_ENTRY_FLAG_ENABLE_ADDITIONAL_COLOUR_2": true,
                "VEHICLE_ENTRY_FLAG_ENABLE_ADDITIONAL_COLOUR_1": true,
                "VEHICLE_ENTRY_FLAG_POWERED": true,
                "VEHICLE_ENTRY_FLAG_VEHICLE_ANIMATION": true,
                "animationSpeed": {
                    "exponent": 14,
                    "multiplier": 1
                },
                "steamPositionModifier":{
                    "longitudinal": 0.2,
                    "vertical": 1.0
                }
            },
            {
                "rotationFrameMask": 31,
                "spacing": 183036,
                "mass": 110,
                "frictionSoundId": 31,
                "soundRange": 3,
                "drawOrder": 7,
                "frames": {
                    "flat": true,
                    "gentleSlopes": true,
                    "diagonalSlopes": true
                },
                "VEHICLE_ENTRY_FLAG_ENABLE_ADDITIONAL_COLOUR_2": true,
                "VEHICLE_ENTRY_FLAG_ENABLE_ADDITIONAL_COLOUR_1": true,
                "VEHICLE_ENTRY_FLAG_POWERED": true
            },
            {
                "rotationFrameMask": 31,
                "spacing": 270196,
                "mass": 600,
                "numSeats": 6,
                "numSeatRows": 3,
                "frictionSoundId": 31,
                "soundRange": 3,
                "drawOrder": 5,
                "frames": {
                    "flat": true,
                    "gentleSlopes": true,
                    "diagonalSlopes": true
                },
                "VEHICLE_ENTRY_FLAG_ENABLE_ADDITIONAL_COLOUR_2": true,
                "VEHICLE_ENTRY_FLAG_ENABLE_ADDITIONAL_COLOUR_1": true,
                "VEHICLE_ENTRY_FLAG_POWERED": true,
                "loadingPositions": [10, 8, 1, -1, -8, -10]
            }
        ]
    },
    "images": ["$RCT2:OBJDATA/NRL2.DAT[0..1154]"],
    "strings": {
        "name": {
            "en-GB": "LOLOLOL",
            "fr-FR": "Trains vapeur couverts",
            "de-DE": "Dampfzüge mit überdacht. Wagons",
            "es-ES": "Tren de Vapor Cubierto",
            "it-IT": "Treni a vapore con carrozze coperte",
            "nl-NL": "Stroomtrein met overdekte wagons",
            "sv-SE": "Ångtåg med täckta vagnar",
            "ko-KR": "천장이 있는 증기 기관차",
            "zh-CN": "有屋顶的蒸汽火车",
            "zh-TW": "有蓋蒸氣火車",
            "pt-BR": "Trens a Vapor com Carros Cobertos",
            "cs-CZ": "Parní vlaky s krytými vozy",
            "ja-JP": "屋根の蒸気機関車",
            "pl-PL": "Pociągi parowe z krytymi wagonami",
            "ru-RU": "Паровозики с вагончиками"
        },
        "description": {
            "en-GB": "Miniature steam trains consisting of a replica steam locomotive and tender, pulling wooden carriages with fabric roofs",
            "fr-FR": "Trains miniatures comprenant une réplique de locomotive à vapeur et des petits wagons en bois avec des toits en tissu",
            "de-DE": "Mini-Dampfzüge bestehend aus nachgemachter Dampflok und Tender mit Holzwagons mit Stoffdächern",
            "es-ES": "Trenes miniatura de vapor con locomotoras réplica y vagones de madera y techos de lona",
            "it-IT": "Treni in miniatura che replicano le locomotive a vapore e i carri scorta. Trainano carrozze di legno con i tetti in tessuto",
            "nl-NL": "Miniatuurstroomtrein bestaande uit een replicastoomlocomotief en tender, die wagons met stoffen overdekking voorttrekt.",
            "sv-SE": "Miniångtåg som består av en kopia av ånglokomotiv  som mjukt drar trävagnarna med tygtak",
            "ko-KR": "부드러운 천으로 된 지붕을 가진 나무 객차와 증기 기관차 모형으로 이루어진 모형 증기 기관차 차량",
            "zh-CN": "微型蒸汽火车是由酷似蒸汽火车及媒车拖拉具有布织车顶的木制四轮马车所组成的",
            "zh-TW": "配備著復刻蒸氣火車頭及煤水車的小型蒸氣火車, 拉著帶有織布車頂的木製車廂",
            "pt-BR": "Trens a vapor em miniatura, consistindo de uma réplica de uma locomotiva a vapor e vagão de carga, puxando vagões de madeira com tetos de tecido",
            "cs-CZ": "Miniaturní replika parní lokomotivy s tendrem táhne dřevěné vagóny s plátěnými střechami",
            "ja-JP": "レプリカの蒸気機関車と炭水車、布製の屋根の木製客車からなるミニチュア列車です",
            "pl-PL": "Miniaturowe pociągi składające się z lokomotywy parowej i tendra, ciągnących drewniane wagoniki z płóciennymi daszkami",
            "ru-RU": "Miniature steam trains consisting of a replica steam locomotive and tender, pulling wooden carriages with fabric roofs"
        },
        "capacity": {
            "en-GB": "6 passengers per carriage",
            "fr-FR": "6 passagers par voiture",
            "de-DE": "6 Fahrgäste pro Wagon",
            "es-ES": "6 pasajero por vagón",
            "it-IT": "6 passeggeri a carrozza",
            "nl-NL": "6 passagiers per wagon",
            "sv-SE": "6 passagerare per fordon",
            "ko-KR": "객차당 6명의 승객",
            "zh-CN": "6 位乘客/每辆马车",
            "zh-TW": "每車廂6位乘客",
            "pt-BR": "6 passageiros por vagão",
            "cs-CZ": "6 míst v každém vagónu",
            "ja-JP": "各車両6名",
            "pl-PL": "6 pasażerów na wagon",
            "ru-RU": "6 пассажиров"
        }
    }
}


```

**Comment by duncanspumpkin** [comment] 2020-04-11 06:19
Duplicate of #11259

**Closed by duncanspumpkin** 2020-04-11 06:20 UTC
