### ISSUE TITLE
Handymen frequently become trapped in queue lines when puke is on a nearby path

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7947] opened 2018-08-28 19:31 UTC
**OS:** Windows 8
**Version:** 0.2.1
**Commit/Build:** 8784dfb

This is a kind of pathfinding issue that I've been noticing more and more lately.
If a handyman enters a queue line that zig-zags back and forth, then approaches close to puke/litter on a nearby path that the queue isn't connected to, he'll constantly try to walk directly toward the puke, but never arrive there because in order to reach it, he first needs to walk away from it.

An example -- in these screenshots, two handymen are stuck indefinitely in this queue line, trying to reach the puke on the exit path. They've been there for a long time, and they'll continue to stay there until a different random handyman happens to clean that puke:
![leaky lake 2018-08-22 11-46-43](https://user-images.githubusercontent.com/26573303/44745396-7f3bd000-aabc-11e8-839c-204a43fa5cb0.png)
![leaky lake 2018-08-22 11-46-47](https://user-images.githubusercontent.com/26573303/44745407-8236c080-aabc-11e8-9012-21154c60adbc.png)

I've sometimes seen three or four handymen trapped like this, and it can be especially problematic when using patrol areas for handymen, because in that case, there may never be another random handyman coming by to clean the puke, so they get stuck there forever. (And meanwhile, pukes and trash pile up in the area they're supposed to be patrolling.)

This mainly only comes up in queue lines, but it would probably also be a problem with any two adjacent but non-connecting paths.

I know a complete revamp of handyman pathfinding is too much to ask for, but maybe something simpler such as...
- once every certain number of ticks, handymen will stop seeking out trash/pukes, and will instead travel in a straight line for a specified amount of time (while remaining in their patrol areas), thus helping break the cycle?
- check for a path being connected before attempting to walk toward that path?
- make it so that if a handyman must reverse direction to travel toward a puke or trash, he'll have a 50% chance of 'not seeing it because it's behind him', and instead continue in the direction he was going, giving a 50% chance of escaping this kind of loop for ever iteration? (ie, handymen would still seek out pukes to the front, left, and right, but if the puke is behind them, they only have a 50% chance of heading for it; give them a bias against completely reversing direction.)
- have it work more like the peeps' pathfinding, where they can only change direction at a path intersection, never on a straight-line path with only 2 connections?
- make handymen 'forget' about a puke if they've been chasing it for more than a specified amount of time?
- or even the age old request: give handymen a strong bias against entering queue lines in the first place?

**Steps to reproduce:**
1. Build a queue path adjacent to a normal path, with curves or zig-zags that make crossing between the two in a simple straight-line path impossible. (Such that to get from the queue path to a specific point on the normal path, you'd have to first travel away from the normal path for several squares)
2. Get a puke/trash on the normal path
3. Place a handyman on the queue path near the puke.

**Comment by bjschuit** [comment] 2018-08-29 12:02
+1 noticed this yesterday too.

**Comment by Broxzier** [comment] 2018-08-29 12:56
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3205

**Closed by Broxzier** 2018-08-29 12:56 UTC
