### ISSUE TITLE
Track saving dialog is annoying to use (bad default values)

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4011] opened 2016-07-08 16:56 UTC
Version: 0.4.0 on Arch Linux

This is something which annoys me a lot: If you want to save a track design while playing a scenario by using the save button in the track window somewhere, no good default values are used.
It just points me to the home directory with no file name pre-entered. Every fucking time. (Besides, I don't even know where I am supposed to save my tracks to make them visible in OpenRCT2: https://openrct2.org/forums/topic/1454-where-to-place-custom-scenariostracksetc/).

This dialog should point to the OpenRCT2 track directory by default, and also pre-enter the file name which is just the track's name plus the “.td6” suffix. So basically the player can just hit “save” in 99% of cases and be done with it. This is also the way it worked in RCT (I don't know about RCT2, however), so this alone is a strong reason to implement it properly.

Also, the dialog should use the OpenRCT2-ingame dialog, not the system one (by default, at least), because many other things in OpenRCT2 already use this one, so saving tracks seem to be “the odd one in the family”. ;-)

**Comment by IntelOrca** [comment] 2016-07-08 17:38
Does it work if you create a `track` directory in your OpenRCT2 user directory... the one that contains `config.ini`?

**Comment by Wuzzy2** [comment] 2016-07-08 22:34
No. I have placed serveral `.td6` files into said directory but none of them seem to become visible in OpenRCT2. :-(

**Comment by IntelOrca** [comment] 2016-07-08 22:47
What I meant was, does it navigate to the correct directory if you create it. But if it already existed then it doesn't work regardless - that is what I wanted to check.

**Comment by Wuzzy2** [comment] 2016-07-09 06:10
Oh, I just noticed I did not have the “track” directory. I had “tracks” instead, haha! I renamed the directory but OpenRCT2 still opens the system dialog pointing to my home directory.
But at least I can now load custom tracks.

**Comment by SijmenSchoon** [comment] 2016-07-09 06:15
Try to remove the last_track_directory entry in your config.ini. It should default to the OpenRCT2 track directory

**Comment by duncanspumpkin** [comment] 2016-07-09 06:51
I can't quite remember what we had in 0.0.4. Was that before @IntelOrca made the change to the tracks so that it loaded from a different folder.

**Comment by Wuzzy2** [comment] 2016-07-09 09:09
Nope, removing `last_track_directory` doesn't do anything.
BTW: I am now using the development version (current: 76b2621).

**Comment by grimpunch** [comment] 2017-02-08 22:15
I just looked into this and it happens for me on Ubuntu  16.10,
The in game window does show the correct folder structure and even creates the ~/.config/OpenRCT2/track folder when opening for the first time, however when you use the "Using system dialog" button, herein lies the issue! This button doesn't take into account the folder path.

I'm going to look into this and see where this button action is set, shouldn't be too troubling!

**Comment by grimpunch** [comment] 2017-02-09 00:16
As far as I can tell, the browse function in loadsave.c is being partially optimised out so the path gets mangled before we open the file dialog
I'll have to look into this further to be sure

**Comment by IntelOrca** [comment] 2017-02-09 07:45
> As far as I can tell, the browse function in loadsave.c is being partially optimised out so the path gets mangled before we open the file dialog

Optimisation shouldn't change expected behaviour, it would be a bug in this case like stack memory being used out of scope or allocated memory that is freed too early.

**Comment by JoelTroch** [comment] 2017-02-28 10:38
Since #5201 is merged, shouldn't this be closed as well ?

**Closed** 2017-02-28 12:21 UTC
Labels: enhancement, starter
