### ISSUE TITLE
"Invert right mouse dragging" causes cursor to move after dragging

### ISSUE THREAD

**Issue by Alicecomma** [OpenRCT2/OpenRCT2#8592] opened 2019-01-15 15:30 UTC
**OS:** Windows 10
**Version:** Both 0.2.1 and current dev build
**Commit/Build:** Both 8ac731e and 51fc2fe

When right-click dragging normally, the direction of the mouse dragging matches the direction of the screen movement. Also, the mouse cursor remains at the screen position at which the drag was started, so no mouse cursor movement is seen.

Turning on "Invert right mouse dragging" in the fifth Options tab:
Right-click dragging direction of the mouse now is the opposite of the direction of the movement, as expected. _However, after releasing the RMB, the mouse cursor jumps to a position expected if the right mouse button was not held for the duration of the drag._ One caveat is that the mouse cursor ends up in a position at maximum about 2/3rds of the screen width away from the center of the screen.

**Reproducible in RCT2 (vanilla)?**
RCT2 vanilla handles right-click dragging as OpenRCT2 does by default. RCT2 does not have an invert drag direction option.

**Steps to reproduce:**
1. Open any park/savefile
2. Press RMB and drag. Notice where the cursor ends up
3. Toggle "Invert right mouse dragging", repeat step 2

It appears that the behaviour outlined in #4826 is implemented when "Invert right mouse dragging" is toggled, but not when it is off.

**Comment by IntelOrca** [comment] 2019-01-15 16:43
When I tried both invented and without I got the expected behaviour which is that the mouse cursor always remains at the same position relative to the game window. In other words if start dragging when the mouse is below the fast forward toolbar button it should still be below the fast forward toolbar button after releasing the right mouse button. This is the same regardless of whether invert is enabled or not.

**Comment by Alicecomma** [comment] 2019-01-15 19:44
For me this occurred when dragging in the middle of the screen, but not near the edges (edges being about 1/6th of the width/height of the screen to either side)

**Comment by 733737** [comment] 2024-04-20 05:59
is this still an issue?

**Comment by Alicecomma** [comment] 2024-04-22 11:56
It seems fixed to me,

The cursor [seems to remain visible](https://youtu.be/UGH0FipTkZg) during dragging with the option enabled now (v0.4.10). I also don't get different behaviour at the window/fullscreen borders anymore. Given this I'd reckon the original issue was that the cursor wasn't visible while dragging.

**Comment by Gymnasiast** [comment] 2024-04-30 19:29
The cursor being visible is also reported here: https://github.com/OpenRCT2/OpenRCT2/issues/21940

As the original issue seems to be fixed, I am closing this report.

**Closed by Gymnasiast** 2024-04-30 19:29 UTC
Labels: investigate
