### ISSUE TITLE
Crash when selecting Build New Ride/Attraction macOS

### ISSUE THREAD

**Issue by hoghedge** [OpenRCT2/OpenRCT2#4967] opened 2017-01-01 23:03 UTC
**OS:** macOS Sierra
**Version:** 10.12.2
**Commit/Build:** ae6ed29

Every 1 in 10 times I click on the Build New Ride/Attraction button it will crash my game. It happens on new games and all of my saves, if I play the game for 5 mins or so I can guarantee a crash within that time frame. To workaround this issue I have auto save set to every minute so I don't lose much progress.

I have added the error report that my Mac produces when the game crashes.

Let me know what other information you guys need.

[rct2crash.txt](https://github.com/OpenRCT2/OpenRCT2/files/680234/rct2crash.txt)

**Comment by IntelOrca** [comment] 2017-01-01 23:20
Duplicate of #4958

**Comment by IntelOrca** [comment] 2017-01-01 23:20
It has been fixed now, please update your game.

**Closed by IntelOrca** 2017-01-01 23:20 UTC
Labels: duplicate

**Comment by hoghedge** [comment] 2017-01-02 00:18
Apologies for the duplicate, I must learn to have a more thorough search before posting. Thanks for the reply and thanks for all the hard work put into this project.
