### ISSUE TITLE
Can't change a ride's vehicle type

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12121] opened 2020-07-04 00:03 UTC
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 55f0f34

I have found a rather annoying bug that sometimes prevents me from changing a ride's vehicle type, even if the ride itself is already not forbidden from being altered or removed. The only way that I can use the vehicle type I want is to place down a prebuilt design using said vehicle type (e.g. Judge Roy Scream with the Wooden Roller Coaster Trains (6 seater)) and then alter it into my own design from there, which can be a waste of money in scenarios where money is present.

- Reproducible in RCT2 (vanilla)? No
- Specific to multiplayer? No

**Steps to reproduce:**
1. Start up a new game in any scenario with a ride that has multiple vehicles available (e.g. wooden coaster in Build your own Six Flags Park, Crazy Castle, or Rollercoaster Heaven). It doesn't matter if the scenario either was made in RCT2 vanilla or has other vehicle types unlockable via research.
2. Build a custom ride design (you can also do a prebuilt) for said ride that has multiple available vehicle types.
3. Attempt to change the ride's vehicle type. It should eventually give a short error message of "Can't make changes..."

NOTE: This bug may not be successfully reproducible on all scenarios. I attempted to replicate it on Fungus Woods (where I also started a new game) and the bug didn't occur.

**Screenshots / Video:**
![Screaming Woods 2020-07-03 16-45-59](https://user-images.githubusercontent.com/61885939/86501392-63a34f80-bd4d-11ea-852b-2b44a45d3e0d.png)
As you can see here, I have tried to change Wooden Roller Coaster 2's vehicles from the Articulated Roller Coaster Trains to the Wooden Roller Coaster Trains (6 seater) but it fails every time, as it always spawns a "Can't make changes..." error message.

**Save game:**
[wooden coaster vehicle change fail.zip](https://github.com/OpenRCT2/OpenRCT2/files/4871881/wooden.coaster.vehicle.change.fail.zip)

**Comment by duncanspumpkin** [comment] 2020-07-04 06:30
I can't reproduce this.

**Comment by Broxzier** [comment] 2020-07-04 14:43
@Fred-1044276 Did you have any cheats enabled? Posting your config.ini file may help find what's causing this for you.

**Comment by Fred-1044276** [comment] 2020-07-04 15:09
No, I did not have any cheats enabled. Even with them on, the issue still persists.

**Comment by duncanspumpkin** [comment] 2020-07-04 18:41
What about plugins? Do you have any installed

**Comment by Fred-1044276** [comment] 2020-07-04 18:41
I don't have any plugins installed either because I have never used them before.

**Comment by Fred-1044276** [comment] 2020-07-28 17:35
I was able to reproduce the bug again, this time by loading up a scenario with multiple train types available for a ride type and then starting a new game on another scenario with the same ride type but with less train types available (e.g. load up Funtopia, which has stand-up twister trains available by default, and then start a new game on Extreme Heights, which has only the twister trains available by default).

**Comment by adam-bloom** [comment] 2020-11-29 05:55
This is a duplicate of #12981. The issue is that the Ride window does not repopulate in some scenarios when it should repopulate. In this case, the bug is seen when the last Ride window opened in a park has a vehicle researched that is not available the next time the window is opened. It looks like @evilclownattack has a fix in https://github.com/evilclownattack/OpenRCT2/commit/8431a1dcda24aea620e816efcf524146c80ac43d.

https://github.com/OpenRCT2/OpenRCT2/blob/a7481b40b4197d6208735165cf6cd993dd2f6680/src/openrct2-ui/windows/Ride.cpp#L2096-L2100

**Comment by Gymnasiast** [comment] 2021-04-24 08:12
Closing as duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/12981.

**Closed by Gymnasiast** 2021-04-24 08:12 UTC
Labels: investigate
