### ISSUE TITLE
Custom objects crash the game whenever I open it

### ISSUE THREAD

**Issue by lachlanshanks** [OpenRCT2/OpenRCT2#3947] opened 2016-06-24 09:32 UTC
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 080f470

After trying to enter a server the game crashed when it loaded the objects. Now my game crashes on start up when trying to load these extra objects.

**Steps to reproduce:**
1. Load server with bad objects
2. Try and start game again

**Dump file**
[5842154c-243b-4ada-a7d9-f670c5604e9d(080f470).zip](https://github.com/OpenRCT2/OpenRCT2/files/331538/5842154c-243b-4ada-a7d9-f670c5604e9d.080f470.zip)

**Comment by mrtnptrs** [comment] 2016-06-24 10:07
Delete the following file: %userprofile%\documents\OpenRCT2\plugin.dat and then restart the game. Then the objects cache will get a refresh in case it got corrupted. Can you also provide me with a name of the server you connected to and which caused your problem?

**Comment by ptkato** [comment] 2016-06-24 18:58
I guess #3916 is the same issue.

**Comment by lachlanshanks** [comment] 2016-06-24 21:14
Sorry I can't remember which server it was I connected to. I tried deleting that file but my game still isn't starting.

**Comment by WhenPenguinsAttack** [comment] 2016-06-25 16:22
Did you delete the bad objects (almost certainly the most recent ones; sort the folder by date to find them)?

**Comment by lachlanshanks** [comment] 2016-06-25 17:54
I am in the ObjData folder however all the files are dated either 2002 or 2003. I am in the C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData folder, is this right?

**Comment by Gymnasiast** [comment] 2016-06-25 18:06
Please update to the newest version and try again.

**Comment by Nubbie** [comment] 2016-06-30 20:30
@ptkato 
Could you run openrct2.exe from the command prompt and with --verbose as an argument?
This mean:

1.  Open a command prompt
2.  cd to the directory where openrct2.exe resides
3.  openrct2.exe --verbose


Can you then right click and copy all the text and paste it in here? (or at least show a screenshot at the end of the text)
_(copied from Dev Gymnasiast)_

**Comment by Nubbie** [comment] 2016-06-30 22:29
Dupe of #3948 

```
>	openrct2.dll!object_chunk_load_image_directory(unsigned char * * chunk=0x000df9a0) Line 481	C
 	openrct2.dll!object_type_small_scenery_load(void * objectEntry=0x04854020, unsigned int entryIndex=0, int * chunkSize) Line 1398	C
 	openrct2.dll!object_load(int type=1, void * objectEntry=0x04854020, unsigned int entryIndex=0, int * chunkSize=0x000dfb30) Line 2565	C
 	openrct2.dll!object_load_file(int groupIndex=-1, const rct_object_entry * entry, int * chunkSize=0x000dfb30, const rct_object_entry * installedObject=0x033522e1) Line 137	C
 	openrct2.dll!install_object_entry(rct_object_entry * entry=0x000dfb70, rct_object_entry * installed_entry=0x033522e1, const char * path, rct_object_filters * filter=0x000dfb54) Line 802	C
 	openrct2.dll!object_list_load(...) Line 348	C
 	openrct2.dll!rct2_init(...) Line 167	C
 	openrct2.dll!openrct2_initialise(...) Line 243	C
 	openrct2.dll!openrct2_launch(...) Line 271	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x01773acd, int nCmdShow=10) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Comment by janisozaur** [comment] 2016-07-01 05:48
Duplicate of #3916

**Closed by janisozaur** 2016-07-01 05:48 UTC
Labels: crash, help
