### ISSUE TITLE
Unlock scenario objective variables

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#9069] opened 2019-04-07 10:57 UTC
Feature request requiring new save format:

The variables you can set for the existing scenario objectives have limits and steps that could be changed when there's a new save format.

Number of guests: min. `250` - max. `5000` - in steps of `50`
Objective date: min. `October, Year 1` - max. `October, Year 25` - in steps of `1 year`
Monthly profit: min. `1000` - max. `???` - in steps of `100`
Park value: min. `1000` - max. `2000000` - in steps of `1000`
Roller coaster min. length: min. `1000m` - max. `5000m` - in steps of `100m`
Roller coaster excitement rating: min. `4.00` - max. `9.90` - in steps of `0.10`

The amount of roller coasters in the "build roller coasters" and "finish building roller coasters" is locked to `10` and `5` respectively.

Also, I'm not sure if this is related to save format limitations, but the "number of guests in park" objective (without the time limit) can only be set when "no money" is set, it would be cool if this was also available for scenarios with money.

**Comment by duncanspumpkin** [comment] 2019-04-07 11:03
duplicate of #7546

**Closed by duncanspumpkin** 2019-04-07 11:03 UTC

**Comment by Umdlye** [comment] 2019-04-07 11:21
Oh, I even commented there. Oops!

Do you happen to know anything about this?

> Also, I'm not sure if this is related to save format limitations, but the "number of guests in park" objective (without the time limit) can only be set when "no money" is set, it would be cool if this was also available for scenarios with money.

**Comment by duncanspumpkin** [comment] 2019-04-07 11:25
Can certainly be addressed when we move to a new save format.
