### ISSUE TITLE
Rubberbanding/lagging on multiplayer - Mac

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#4277] opened 2016-08-13 20:36 UTC
**OS:** Mac OS X 10.11.6
**Version:** 0.0.5
**Commit/Build:** 7f71bec (Build 1149)

Rubberbanding/very noticeable lagging is experienced while playing multiplayer in slightly busy park.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer? Only on Multiplayer

**Steps to reproduce:**
1. Build a server with a few rides, plants, and peeps
2. Join server using a Mac

**Screenshots / Video:**
https://vid.me/lDJe

**Save game:**
[Ruberbanding.txt](https://github.com/OpenRCT2/OpenRCT2/files/416757/Ruberbanding.txt)

**Comment by Gymnasiast** [comment] 2016-08-13 20:43
You posted a link to delete your video. I'd replace that with the intended link if I were you.
Also, could you describe what you mean by 'rubberbanding'?

**Comment by IntelOrca** [comment] 2016-08-13 20:43
Your server can not cope... multiplayer isn't multi-theaded, nor is our drawing. If your server is running at a high resolution it will degrade the QoS.

**Comment by joshbgosh10592** [comment] 2016-08-13 21:35
But the thing is, it happens only on the Mac. Every other Windows client is fine, and it's on every server I connect to. And I don't believe it's due to latency, as my ping time is only 75ms, including when it's showing the symptom.
Sorry, I've updated the link.

**Comment by IntelOrca** [comment] 2016-08-13 23:52
hmm

**Comment by zsilencer** [comment] 2016-08-14 05:27
I just tried it on my macbook, no rubberbanding/lagging or other issues whatsoever for me.  This could be caused by your wifi connection or something.

**Comment by joshbgosh10592** [comment] 2016-08-17 22:28
Can't be my Wifi connection, as I've tried on multiple wireless networks. If it was Wifi related, though, the ping times should show evidence. CPU utilization isn't an issue, since it never reaches above about 70% (ESXi VM), and I'm the only client (all others are Windows) that shows the trouble.
I have a Mac Mini that's hard wired. I'll try that tonight and post the results when I can.

**Comment by IntelOrca** [comment] 2016-08-27 22:31
This also happens if the client has a bad connection. For example if the client is downloading a lot of other things in the background, this is likely to happen as it isn't getting the server messages quickly enough.

**Comment by IntelOrca** [comment] 2016-09-09 23:00
@joshbgosh10592 I forgot to ask the obvious question... what did your ping say when you open the players window?

**Comment by joshbgosh10592** [comment] 2016-09-10 14:02
@IntelOrca I forgot to note the obvious evidence, sorry about that... The ping time is either 25ms (within my LAN) or about 75ms (not local to my LAN).
When this happens, OpenRCT2 is the only application pulling anything worth noting over the network.
It also happens on other servers, including MoT's random server. I never have an issue with this on my Windows desktop, and I don't have any other issues playing other online games on my Mac, so I don't believe it's an issue with the laptop.

**Comment by AaronVanGeffen** [comment] 2016-09-10 14:10
This sounds like your router may be throttling your packets through QoS. If enabled, could you try and see whether disabling it makes any difference?

**Comment by janisozaur** [comment] 2016-09-10 14:15
Are our OS X builds built in release mode?

**Comment by janisozaur** [comment] 2016-09-10 14:22
Are our OS X builds built in release mode? I've observed such behaviour on localhost, when using debug build – it struggled to stay up to date and needed to perform more than one logic update at once.

Although, @joshbgosh10592 mentioned:
> CPU utilization isn't an issue, since it never reaches above about 70% (ESXi VM)

The other thing:
> I have a Mac Mini that's hard wired. I'll try that tonight and post the results when I can.

@joshbgosh10592 have you ever managed to test it out?

**Comment by joshbgosh10592** [comment] 2016-09-10 15:03
@AaronVanGeffen I've been on multiple networks connecting to multiple servers, so that rules out any router I communicate with (unless it's in the telecom cloud, but I won't get into that).
@janisozaur I haven't.. I've had some issues with it and haven't had much time to investigate. However, I have a Mac OS VM (10.11) on my Windows machine (the one that has no problems at all, and is hardwired). The Mac VM had the exact same issue as on my MacBook Pro.
I typed in the IP address of the server as well, so it's not even leaving my LAN. I also tested on another busy park, same thing.

**Comment by joshbgosh10592** [comment] 2016-09-10 18:38
Interesting... I'm looking at my Activity monitor (on my MacBook), and the CPU usage is at 112% (both in multiplayer, and sitting idle at the intro screen). This is odd, because I can play The Sims 4 with no problem at all (around 153% CPU), and that's a heck of a lot more of a resource hog than OpenRCT2 should be. Maybe there's a CPU leak that flares up when the game needs to draw the sprites?

*Note: It's over 100% due to hyperthreading/multi core CPU.

**Comment by duncanspumpkin** [comment] 2016-09-10 18:55
Sprite drawing is quite a CPU heavy activity at high resolutions

**Comment by joshbgosh10592** [comment] 2016-09-17 22:16
@IntelOrca Just tried, same thing.
It seems like the game is just extremely resource heavy on a Mac? I just find it weird that a game with sprites crushes the CPU more than an HD game with 3D modeling. Maybe graphics optimization isn't working right?

**Comment by IntelOrca** [comment] 2016-09-17 22:32
@joshbgosh10592 That is of no surprise... all the drawing is CPU bound and 1 processor at that on same thread as game logic.

**Comment by IntelOrca** [comment] 2016-09-29 12:03
Closing as I can't see anything more we can do to improve the situation here.

**Closed by IntelOrca** 2016-09-29 12:03 UTC
Labels: investigate, macOS (OS)
