### ISSUE TITLE
Loading both RCTC and RCT1DX doubles up on all RCT1 scenarios.

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#18017] opened 2022-09-12 02:19 UTC
### Operating System

Windows 10, 64 Bit 

### OpenRCT2 build

OpenRCT2, v0.4.1-304-g4f0f660 (4f0f660 on develop) provided by GitHub

### Describe the issue

![image](https://user-images.githubusercontent.com/1516893/189561749-fd7f0b4b-4b1a-476a-9a27-2dfe6256f7b8.png)
When you have both RollerCoaster Tycoon Classic and RollerCoaster Tycoon Deluxe loaded in all RCT1 scenarios (except for real parks) are listed twice (once as `sc4` and once as `sea` file). 
It would be best to unlist the `sea` files if RCTDX gets connected since the RCT1 scenarios contain different elements (like seperated paths, terrain surfaces, etc) while the RCTC versions of these scenarios do not.

### Steps to reproduce

Connect both RCTC (not RCT2DX) and RCTDX to the game, click on scenarios. All RCT1 scenarios will be listed twice.

**Comment by Gymnasiast** [comment] 2022-09-12 08:03
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/17949.

**Closed by Gymnasiast** 2022-09-12 08:03 UTC
Labels: bug
