### ISSUE TITLE
Mechanics try to head to ride to inspect whether impossible or patrolled

### ISSUE THREAD

**Issue by RoyTheDragon** [OpenRCT2/OpenRCT2#13262] opened 2020-10-22 18:55 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.3.1]
**Commit/Build:** [e.g. 426e106]

I was testing out a scenario I made which I am making for my own scenario pack of 100 scenarios and while testing I noticed something very weird about how the mechanics disregard the fact that either there's no path connected to the route going to the coaster or it's outside the parameters of the patrol area.

- [ n ] Reproducible in RCT2 (vanilla)?
- [ n ] Specific to multiplayer?

**Steps to reproduce:**
1. Create a coaster either with or without a path heading to it.
2. set a patrol area for a mechanic and watch the action line at the bottom of what it's attempting to do.

**Screenshots / Video:**
https://cdn.discordapp.com/attachments/480234265712394240/768907842111012874/unknown.png

**Comment by duncanspumpkin** [comment] 2020-10-22 19:13
Pretty sure thats vanilla behaviour. It is up to you to layout your mechanics so that this doesn't happen.

**Comment by Gymnasiast** [comment] 2020-11-21 10:37
> Pretty sure thats vanilla behaviour.

It is not. In vanilla, mechanics would go outside the patrol area if the exit was in it. We changed the code so that the mechanics never go outside it, in order to make their behaviour more predictable.

> It is up to you to layout your mechanics so that this doesn't happen.

Do you think this should be closed as "works as intended"?

**Closed** 2024-10-11 12:05 UTC
