### ISSUE TITLE
Flat Ride Ghosts Flash at High Speed

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#5888] opened 2017-07-13 18:51 UTC
**OS:** Windows 10, Arch Linux
**Version:** 0.1.1
**Commit/Build:** a808da9

Ghosts Flash at High Speed before Placement, if they are held in the air.

This issue is at least a couple weeks old, but more than one person has said they will report it, and as far as I know, none of them have.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Select Merry-Go-Round
2. Use Shift to hover it (Or try to put it over some path).

**Screenshots / Video:**
https://youtu.be/dUr7ewO-bOw

**Comment by zsilencer** [comment] 2017-07-13 19:14
#5865

**Comment by rwjuk** [comment] 2017-07-13 19:16
Closing as a dupe of #5865 - the video is useful so I've posted that there.

**Closed by rwjuk** 2017-07-13 19:16 UTC

**Comment by PFCKrutonium** [comment] 2017-07-13 19:27
Thanks, I didn't find that one.
