### ISSUE TITLE
Bobsled with block brakes got stuck (presumably on first lifthill)

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#5555] opened 2017-06-06 11:33 UTC
Not entirely sure what's the cause, but the bobsled attraction is forever stuck.
I left the game running for a few minutes when the bobseld was set to test mode and when i get back it is not moving.

[Razor Rocks-bobsled.zip](https://github.com/OpenRCT2/OpenRCT2/files/1054789/Razor.Rocks-bobsled.zip)

Version: OpenRCT2-0.0.8-develop- e7eb5f7 -windows-x64

**Comment by Patrik356b** [comment] 2017-07-12 09:50
retested on e7eb5f7 with same result.

**Comment by IntelOrca** [comment] 2017-07-22 20:26
I am not sure whether this is a bug or not. The problem is that the first train hits the first block brake before it has completely departed the station. This stops the last train from moving to the next block and the other trains from following.

**Comment by Gymnasiast** [comment] 2017-07-22 20:31
As IntelOrca said, the first block brake is almost immediately after the station - the top of the left hill acts as one. You need to ensure that block sections are long enough to accommodate a train.

**Closed by Gymnasiast** 2017-07-22 20:31 UTC
Labels: investigate

**Comment by Patrik356b** [comment] 2017-07-23 20:40
at least that explains it.
