### ISSUE TITLE
Custom scenery group bug

### ISSUE THREAD

**Issue by Legotown55** [OpenRCT2/OpenRCT2#16847] opened 2022-03-22 17:32 UTC
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (45369e3 on develop) provided by GitHub

### Describe the issue

When you download custom groups of scenery you get a message saying to meny objects solected

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Download a custom secnery groop
2. Install it in the game
3. Open it in the solector

### Attachments

[Uploading OpenRCT2-0.3.5.1-develop-41e17a0-windows-x64.zip…]()

**Comment by oli414** [comment] 2022-03-22 18:39
Duplicate of #16849

**Closed by oli414** 2022-03-22 18:39 UTC
Labels: bug
