### ISSUE TITLE
Autosave includes pending construction pieces

### ISSUE THREAD

**Issue by aputlock** [OpenRCT2/OpenRCT2#1331] opened 2015-06-13 22:57 UTC
Steps to reproduce:

1) hover any pre-built rollercoaster over a valid section of the map to get the ghost/preview image
2) wait for autosave to create a new file
3) load the autosave file that was created

It helps to set autosave to every week and utilize the fast forward functionality. The saved images do not prevent building in those areas, but they cannot all be removed as far as I can tell.

**Comment by IntelOrca** [comment] 2015-06-13 23:03
Duplicate of #1145

**Comment by Gymnasiast** [comment] 2015-06-23 08:14
Since it's a duplicate of #1145, it should be solved by https://github.com/OpenRCT2/OpenRCT2/commit/b206a31cae7830b45afb68ed182e30b272460caa as well.

**Closed** 2015-06-23 11:04 UTC
Labels: duplicate
