### ISSUE TITLE
BACKTRACE a369e1

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8336] opened 2018-12-01 14:23 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/a369e141b92e6892a885472ee7379e17260e9f824c2c274c038b81ed68c59721?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Dec 01 2018 14:23:17)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> *: <em>1</em><br><strong>commit:</strong> a9a583d: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>tile_element_insert -> SmallSceneryPlace -> game_command_place_scenery -> game_do_command_p -> Network::ProcessGameCommandQueue -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-03 12:45
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8357

**Comment by janisozaur** [comment] 2019-02-03 12:45
Or of elements?

**Closed by janisozaur** 2019-02-03 12:45 UTC
Labels: backtrace.io, crash
