### ISSUE TITLE
Traffic lights not drawn on B&M sitdown coasters

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#9345] opened 2019-06-01 21:38 UTC
**OS:** [Windows 10]
**Version:** [0.2.2]
**Commit/Build:** [f26a1ae]

On B&M Sitdown coasters, the traffic lights of the station are not drawn. This issue has actually been around for quite a long time now, but i forgot to report it earlier. It affects all B&M sitdown coasters, including vertical drop coaster (because they use same track pieces for station I assume).

![image](https://user-images.githubusercontent.com/6469413/58753860-19a2c700-84c6-11e9-9a94-4f4f24c52416.png)

**Comment by deurklink** [comment] 2019-06-01 21:39
In addition, it looks like the last piece of the station is also drawn incorrectly.

**Comment by Gymnasiast** [comment] 2019-06-09 12:58
I wonder if testpaint fails this.

**Comment by aw20368** [comment] 2019-06-09 15:54
I'll work on this, but what does B&M mean? Also, this is an original bug (repro in RCT1):

![VerticalStation](https://user-images.githubusercontent.com/29646196/59161168-2d918e80-8aad-11e9-93fd-f9582c7a950c.png)

**Comment by AaronVanGeffen** [comment] 2019-06-09 16:06
I believe it refers to [Bolliger & Mabillard](https://en.wikipedia.org/wiki/Bolliger_%26_Mabillard), a roller coaster design company.

**Comment by deurklink** [comment] 2019-06-09 18:33
Oh it actually is an original bug. I never realized! 
Screenshot from vanilla rct2:
![image](https://user-images.githubusercontent.com/6469413/59162695-d8c63600-8af5-11e9-9408-9e378c9d1caf.png)

**Comment by e-foley** [comment] 2019-06-25 05:12
I played around with this a bit and it's hard for me to determine whether it's a bug or not. I noticed that there are two primary types of stations: those with narrow peep walkways and those with wide peep walkways.

![station_types](https://user-images.githubusercontent.com/6338134/60070510-d48c4200-96cb-11e9-9102-9992a66dcdfe.png)
*(narrow, narrow, wide, wide)*

All stations where the peep walkway is narrow, including the rides mentioned here, don't display the traffic light at the head of the station or the perpendicular peep barrier at the rear of the station. At least, I can't find a counterexample.

In addition to B&M rides, the issue affects the Air Powered Coaster and Reverse Freefall coaster. It also happens to the Multi-Dimension Coaster, though the latter ride uses a special station type. These are just a few I came across, but there are likely more.

**Comment by Gymnasiast** [comment] 2019-06-25 15:30
I expect that CS did this deliberately.
Of course, that doesn't mean that we _have_ to do the same, but it would need a compelling reason, especially since it seems new sprites would have to be drawn.

I would say it's not really worth bothering.

**Comment by Gymnasiast** [comment] 2020-09-30 19:08
I'm going to chalk this up as "intended behaviour" and close it.

**Closed by Gymnasiast** 2020-09-30 19:08 UTC
Labels: discussion, graphics, wontfix
