### ISSUE TITLE
Chance of scenery window getting messed up

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4145] opened 2016-07-21 14:02 UTC
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** bc3ec7a

[Explanation of the issue...]
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. I loaded my save today, there was nothing wrong with it yesterday.
2. Open the scenery selection window.
3. The tabs are all messed up: many are missing and a "?"-tab is added, containing many different objects. Seems like the object loading or something went wrong. This has the symptoms of #3562, but the difference is that I didn't load another save in the same session, only this save. Saving and reloading the savegame solved the issue for me. So, there is still something wrong in the object loading code.

**Screenshots / Video:**
![2016-07-21_15-52-54](https://cloud.githubusercontent.com/assets/4948213/17025411/03ca4ea0-4f5c-11e6-847a-3458fae051e6.png)
![2016-07-21_15-53-58](https://cloud.githubusercontent.com/assets/4948213/17025410/03c96472-4f5c-11e6-882a-2f13be1f7a1a.png)

**Save game:**

[Six Fingers.zip](https://github.com/OpenRCT2/OpenRCT2/files/376154/Six.Fingers.zip)

**Comment by duncanspumpkin** [comment] 2016-07-21 16:53
That save does not match the scenery window.

**Comment by mrtnptrs** [comment] 2016-07-21 21:45
@duncanspumpkin I know, the bug happend before i saved the game, but when I load the save myself, the bug seems to be gone. Looks like the object loading went wrong one time....

**Comment by Patrik356b** [comment] 2016-07-21 22:18
I had this happen today on win8.1x64 on commit f6c8993 - closing and opening the scenery window again fixed it

**Comment by Niels-NTG** [comment] 2016-07-27 20:15
Did you by any chance change the language between loading the game again. Because I had this too recently. And that was when I changed the language from Dutch to English (UK). Shortly after a research for a new scenery set was completed. Then when I opened up the scenery window I had the same kind of result.

**Comment by AaronVanGeffen** [comment] 2018-06-01 11:34
Can you still reproduce this?

**Comment by Gymnasiast** [comment] 2020-09-30 19:18
No reply since June 2018, and cannot reproduce it using the provided save. Closing this.

**Closed by Gymnasiast** 2020-09-30 19:18 UTC
Labels: investigate
