### ISSUE TITLE
Validate track types with ride types

### ISSUE THREAD

**Issue by RaymondBakker** [OpenRCT2/OpenRCT2#2924] opened 2016-02-13 19:09 UTC
In the few days that I have been running a multiplayer server all savegames have become corrupted because some parts of the rollercoaster tracks had incorrect types that, I guess, could never be used with the specified ride type, obviously resulting in a crash.

To test my theory I created a short piece of code in game_fix_save_vars() in game.c, right before the NULL map element check, that resets the type of all the tracks of the ride that was causing the crash:

```
	//Reset broken track types..
	for (int y = 0; y < 256; y++) {
		for (int x = 0; x < 256; x++) {

			rct_map_element *mapElement = map_get_first_element_at(x, y);

			do
			{
				if (mapElement != NULL)
				{

					int type = map_element_get_type(mapElement);

					if (type == MAP_ELEMENT_TYPE_TRACK)
					{
						int rideIndex = mapElement->properties.track.ride_index;
						int trackType = mapElement->properties.track.type;

						if (rideIndex == 18 || rideIndex == 19)
							mapElement->properties.track.type = TRACK_ELEM_END_STATION;
					}
				}
			} while (!map_element_is_last_for_tile(mapElement++));
		}
	}
```

When trying this it resolved my crash and I could solve other crashes on my other savegames this way also:

![Image of fix](http://i.imgur.com/ECgmzWc.png)

Which makes me think there should be validation of the track types based on the ride type when saving a game (as in which track types are allowed and which are not) because apparently the game creates some funky savegames.

The same should probably be done for multiplayer commands. This would most likely solve alot of crashing issues that I have seen in the past few days of playing.

Would love to hear some other opinions because I just jumped into the source code and I could be wrong. Only other thing I can think of is something going wrong when converting the track type somewhere?

Savegame:
http://raymondbakker.com/dl/rct/save_13_02_2016.sv6

**Comment by IntelOrca** [comment] 2016-02-13 19:39
The crash is usually when the game tries to draw the track piece. We haven't implemented much of this area which is why we aren't able to add the defences necessary to stop it from drawing invalid track pieces. But otherwise I think this is better than actually modifying the map.

For multiplayer, this just should not happen. If its happening then we need to fix something specifically for multiplayer - not work around it. The validation should actually be in the place track game command not when loading the saved game.

**Comment by RaymondBakker** [comment] 2016-02-13 20:59
Sounds about right, though, if modifying the drawing code to ignore invalid track parts has priority over modifying the savegame to remove or fix the invalid track parts then this will cause savegames to no longer be compatible with the original game, which is fine if that is not the direction this project wants to take.

Will look into it some more.

**Comment by duncanspumpkin** [comment] 2016-02-13 21:19
If you can work out a reliable technique to corrupt it we can fix that but its not too easy to validate the track types.

**Comment by IntelOrca** [comment] 2016-02-13 21:25
Yes, it could be something really simple which we can fix without having to add validation of some sort.

**Comment by RaymondBakker** [comment] 2016-02-14 10:26
Seems to be related to #2581 also, where duncan basically suggested doing the same thing as this issue and says there is a bug in multiplayer netcode that sends the wrong ride type to users causing this corruption.

**Comment by IntelOrca** [comment] 2016-02-14 10:48
This is likely due to desynchronisation, but I wouldn't have thought the issue would be particularly common because players should usually have their ride list in sync.

**Comment by RaymondBakker** [comment] 2016-02-14 11:05
Maybe a potential fix would be to send along the ride type with every piece of track that gets sent to the server when building? Even if desynchronisation takes place this info could then be used to doublecheck and correct the issue if need be?

**Comment by IntelOrca** [comment] 2016-02-14 11:06
@RaymondBakker Yeah, that might work.

**Comment by RaymondBakker** [comment] 2016-02-14 15:29
@IntelOrca Been tinkering with some stuff, see the above commit. Tested it as well:

![Image](http://i.imgur.com/0z8cvlD.png)

**Comment by IntelOrca** [comment] 2016-02-14 15:30
OK, we need to investigate why the client has a different ride to the server.

**Comment by janisozaur** [comment] 2016-02-14 15:37
Could that be caused by ongoing research, that does ride X on server and ride Y on client due to desync at some point in the past?

**Comment by IntelOrca** [comment] 2016-02-14 15:53
Yes, but desync is usually just a few different guest positions. The game commands are still sent and received, so how could a client end up with different ride types?

**Comment by janisozaur** [comment] 2016-02-14 15:59
Research uses `scenario_rand()` at least in a few places, which when desynced will return different values, which can cause the rides to be research in different order. I assume when a ride gets researched, it will get assigned some unused ID, which will be different on server and client, hence this issue.

**Comment by IntelOrca** [comment] 2016-02-14 16:06
Research should only dictate what appears on the create ride window. When a player creates a ride it calls the create ride command with the ride type to the server. Server will then send that to all the players, so the number of rides and what ride types each ride should theoretically be consistent.

**Comment by RaymondBakker** [comment] 2016-02-15 11:57
Only thing that would shed light on this issue is to host a server with additional verbose lines to keep track of what exactly is happening. Will see what I can find..

**Comment by IntelOrca** [comment] 2016-02-15 13:41
You will only get a desync window when a desync is detected. Our current method of detection is if the random seed is different - usually happens quickly enough as soon as peep logic differs between the clients.

This is interesting, can you make a pull request (not intended for merging) with this extra logging so the me and others can use it to investigate. Thanks!

**Comment by IntelOrca** [comment] 2016-02-15 21:22
I have found a way to reproduce something strange at least:
```text
1. **Server:** Start new server
2. **Server:** Click new ride, Merry-Go-Round
3. **Server:** Hover the ghost somewhere, but do not place it.
4. **Client:** Connect to the server
5. **Server:** Place the Merry-Go-Round
6. **Server:** Place the entrance and exit
```
After these steps, the merry-go-round will have only been placed on the server, not the client. The entrance and exit are visible on client though. The ride exists on the client and the ride window of it can be opened, but it does not have a name.

**Comment by IntelOrca** [comment] 2016-02-15 22:02
I have done a potential fix, @RaymondBakker could you try to reproduce now?

**Comment by RaymondBakker** [comment] 2016-02-16 12:20
Been trying to reproduce for 2 hours on latest, still hasen't occured yet. :+1:

Looks like it is a good step towards more stable multiplayer.

**Comment by IntelOrca** [comment] 2016-02-16 12:40
@RaymondBakker thanks, I will close this issue for now then. If there are still further reports and validating seems beneficial, I'll re-open this.

**Closed by IntelOrca** 2016-02-16 12:40 UTC
Labels: bug, investigate, multiplayer

**Comment by RaymondBakker** [comment] 2016-02-16 13:47
One last thing, not sure if related:

When placing a ride on latest it only gives a minimum amount of carts:

![Image](http://i.imgur.com/gdjftBb.png)

When reconnecting:

![Image](http://i.imgur.com/NaTJ7Da.png)
