### ISSUE TITLE
Korean specific number placement bug in OpenGL

### ISSUE THREAD

**Issue by vpsxhtus** [OpenRCT2/OpenRCT2#19165] opened 2023-01-16 08:59 UTC
### Operating System

Windows 10, 64bit

### OpenRCT2 build

OpenRCT2, v0.4.3-32-gf0127d4 (f0127d4 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

![Bug](https://user-images.githubusercontent.com/106915420/212637093-09fedb31-4913-4aa1-8e39-dc0e45e4fbb6.png)
If you set language in Korean, Rollercoaster Value overlap with default explanation.
This only happens in OpenGL

![Correct way](https://user-images.githubusercontent.com/106915420/212637407-3ef9e1df-ec34-4f02-8d9f-884ac2d90667.png)
It should look like this.

### Steps to reproduce

1. Set language to Korean and Drawing Engine to OpenGL 
2. Open any scenario and check ride mesurement data (nausea.. etc)

### Attachments

![Bug](https://user-images.githubusercontent.com/106915420/212637807-c99d84e1-bf65-4fcc-8518-24e459d88c9e.png)

**Comment by telk5093** [comment] 2023-01-16 11:16
Duplicate of #15293

**Closed** 2023-01-16 11:48 UTC
Labels: bug
