### ISSUE TITLE
Boat Hire Stuck when open

### ISSUE THREAD

**Issue by superchadST345** [OpenRCT2/OpenRCT2#20776] opened 2023-09-09 17:19 UTC
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.6 (b40b5da) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

When Playing OpenRCT2 I have built a boat hire, the boat hire consists of a station, and 2 turns, allowing guests to paddle around the lake

when guests all get to the entry to return to the station, all boats get stuck there

![image](https://github.com/OpenRCT2/OpenRCT2/assets/6529196/137ea538-b79c-4a94-9693-d613718368ee)

### Steps to reproduce

1. Build a boat hire on a lake(Arid Heights is where i did this, with a lake created)
2. make the boat hire have a turn out, and turn in, with no in-between track
3. let the boat hire operate normally

**Comment by ocalhoun6** [comment] 2023-09-09 17:33
This is a duplicate of #866 

One of the oldest bugs still open.

**Closed** 2023-09-21 19:28 UTC
Labels: bug, duplicate
