### ISSUE TITLE
Cable lift pulley not grabbing train on cable lift block

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#21215] opened 2024-01-17 22:20 UTC
### Operating System

Windows 10, 64-Bit

### OpenRCT2 build

OpenRCT2, v0.4.7-48-gece7601 (ece7601 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

Please note: This test park was created using https://github.com/OpenRCT2/OpenRCT2/pull/20683
This bug needs to be fixed before 20683 can be merged.

### Steps to reproduce

- Downloaded the provided park.
- Unpause.
- Watch the pulley not grab the train (which was spawned on top of the cable lift block).
- Kaboom

### Attachments

[Bug Report Pulley not grabbing train.zip](https://github.com/OpenRCT2/OpenRCT2/files/13969305/Bug.Report.Pulley.not.grabbing.train.zip)

**Comment by karst** [comment] 2024-02-11 18:41
I was able to reproduce this in Vanilla using two stations:
https://cdn.discordapp.com/attachments/1175487763001376779/1206308852174426132/Reproduction_of_the_21215_bug_in_develop.park?ex=65db89aa&is=65c914aa&hm=149e1150eb18130f2b55b16b6f898fa74c6a33d1e5749675772cf4f7b56e0c69&

Make sure to test the ride and it'll have the same behaviour.

**Comment by karst** [comment] 2024-02-11 18:47
![image](https://github.com/OpenRCT2/OpenRCT2/assets/1516893/cf38c180-db50-4b48-b181-c97dc9a29697)
I just confirmed on RollerCoaster Tycoon 2.

**Comment by Gymnasiast** [comment] 2024-12-22 18:01
This is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/1122 . The nature of this bug means that it’s easier to trigger with #20683, but it’s already in vanilla.

**Closed by Gymnasiast** 2024-12-22 18:01 UTC
Labels: bug, original bug
