### ISSUE TITLE
Chairlift Station Platform Clipping Through Station Styles

### ISSUE THREAD

**Issue by HtotheTML** [OpenRCT2/OpenRCT2#19743] opened 2023-03-27 22:25 UTC
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.3-414-g4bf35b2 (4bf35b2 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

All of the styles of station platform do not display correctly (the chairlift itself clips through the enclosures).
This issue does not exist within the original version of RCT2.

### Steps to reproduce

1. Open a Scenario
2. Construct a chairlift
3. Change the style of station/entrance

### Attachments

![image](https://user-images.githubusercontent.com/108596959/228080372-b63d1f6f-861b-4c4c-9d21-d922f812f0d2.png)
![image](https://user-images.githubusercontent.com/108596959/228080415-b16b4a31-ce25-4ced-a5e1-1429036a5e2b.png)
![image](https://user-images.githubusercontent.com/108596959/228080474-f830b7cd-7511-4259-9bc2-c7692dbcdc4e.png)
![image](https://user-images.githubusercontent.com/108596959/228080512-3412ccfd-376b-45b2-9a76-0299996fe427.png)
![image](https://user-images.githubusercontent.com/108596959/228080557-da31dd21-3ebf-4fc8-be3d-4d2ceb64b7e7.png)

**Comment by ocalhoun6** [comment] 2023-03-27 23:16
This is something I've been living with for so long that I never even thought to report it as a bug.

You're sure it's not present in vanilla? I thought it was...

**Comment by HtotheTML** [comment] 2023-03-27 23:18
seems that way.
![image](https://user-images.githubusercontent.com/108596959/228088095-57267e46-3d57-441d-a1fc-0dd2385e4c7b.png)

**Comment by Gymnasiast** [comment] 2023-03-28 12:09
This is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/16357.

**Closed** 2023-03-28 19:49 UTC
Labels: bug, duplicate
