### ISSUE TITLE
[Suggestion] AppImage for linux releases

### ISSUE THREAD

**Issue by frenchiveruti** [OpenRCT2/OpenRCT2#7940] opened 2018-08-27 16:55 UTC
Hello, Although I admit I haven't tested any linux release as for now I'm not running under Linux. I would like to suggest the release of AppImages for the Stable branches (AKA Releases/Master) to make an ease of use of the game in Different linux systems.  
https://appimage.org/

Would that be possible?

**Comment by AaronVanGeffen** [comment] 2018-08-27 17:04
Snap has been under consideration as well: #6112

**Comment by janisozaur** [comment] 2018-08-27 19:10
Duplicate of #6112. @TheAssassin has been working on AppImage support for OpenRCT2 a while ago, but the use of C++17 posed some problem, as the first project to do so.

Please continue discussion in #6112, if any.

**Closed by janisozaur** 2018-08-27 19:10 UTC
