### ISSUE TITLE
Closing Object Selection Window Crashes Game

### ISSUE THREAD

**Issue by MrRct** [OpenRCT2/OpenRCT2#4751] opened 2016-11-04 15:51 UTC
OS: Windows 8.1
Version: 0.0.5
Build: Developer Version 3653baf

When I try to check some of the scenery and/or rides in the Object Selection, it works like it should.  Then when I close the Object Selection Menu, the game crashes.  I also did the same exact method on another save and it worked just fine.  So I know that its just this park that this bug crashes the game.  I also tried different version of the developer builds and it does the same thing.  This started earlier this week.  UPDATE: I happen to notice that the Invention List does the same thing.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

Steps to reproduce:
1. Open the object selection window.  You may have to turn on Debugging Tools.
2. Once the window opens, close it.
3. The game should crash.

Dump file
[b497122f-0a87-435f-b52d-0a92cfd6982c(3653baf_x86).zip](https://github.com/OpenRCT2/OpenRCT2/files/571970/b497122f-0a87-435f-b52d-0a92cfd6982c.3653baf_x86.zip)

Screenshots / Video:
![image](https://cloud.githubusercontent.com/assets/23262731/20012362/4b6d5906-a285-11e6-87be-da19fb5cb5b6.png)

Save game:
[b497122f-0a87-435f-b52d-0a92cfd6982c.txt](https://github.com/OpenRCT2/OpenRCT2/files/571973/b497122f-0a87-435f-b52d-0a92cfd6982c.txt)

**Comment by janisozaur** [comment] 2016-11-05 09:22
@MrRct please save the game with custom objects embedded.

**Comment by janisozaur** [comment] 2016-11-06 19:57
```
#0  0x000000000082f311 in research_finish_item (entryIndex=1026) at /home/janisozaur/workspace/OpenRCT2/src/management/research.c:232
        i = 0
        ebx = 18
        base_ride_type = 18
        rideEntryIndex = 16802208
        subSceneryEntryIndex = 108
        rideEntry = 0x4498b00 <gSceneryGroupEntries+144>
        rideEntry2 = 0x615000001600
        scenerySetEntry = 0x0
#1  0x00000000008326d2 in sub_684AC3 () at /home/janisozaur/workspace/OpenRCT2/src/management/research.c:348
#2  0x00000000019ff856 in window_editor_object_selection_close (w=0x44764a0 <g_window_list+1248>) at /home/janisozaur/workspace/OpenRCT2/src/windows/editor_object_selection.c:759
#3  0x00000000007bcd4b in window_event_close_call (w=0x44764a0 <g_window_list+1248>) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1880
#4  0x00000000007b7f4b in window_close (window=0x44764a0 <g_window_list+1248>) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:708
#5  0x00000000019ff98b in window_editor_object_selection_mouseup (w=0x44764a0 <g_window_list+1248>, widgetIndex=2) at /home/janisozaur/workspace/OpenRCT2/src/windows/editor_object_selection.c:781
#6  0x00000000007e1e37 in window_event_mouse_up_call (w=0x44764a0 <g_window_list+1248>, widgetIndex=2) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1886
#7  0x00000000006e5dfc in input_state_widget_pressed (x=898, y=165, state=2, widgetIndex=2, w=0x44764a0 <g_window_list+1248>, widget=0x30792a0 <window_editor_object_selection_widgets+64>) at /home/janisozaur/workspace/OpenRCT2/src/input.c:1280
#8  0x00000000006e0ced in game_handle_input_mouse (x=898, y=165, state=2) at /home/janisozaur/workspace/OpenRCT2/src/input.c:323
#9  0x00000000006df764 in game_handle_input () at /home/janisozaur/workspace/OpenRCT2/src/input.c:133
#10 0x00000000006d12de in game_update () at /home/janisozaur/workspace/OpenRCT2/src/game.c:349
#11 0x0000000000ab6759 in rct2_update () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:468
#12 0x000000000083d738 in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:416
#13 0x000000000083bb74 in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:342
#14 0x0000000000a9a63d in main (argc=1, argv=0x7fffffffd7d8) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:59
```

`scenerySetEntry = 0x0` at:
https://github.com/OpenRCT2/OpenRCT2/blob/fe3b15c/src/management/research.c#L232

**Comment by Nubbie** [comment] 2016-11-08 22:29
Duplicate of #4751 ?

(checking dumpfile, brb)

**Comment by Liampie** [comment] 2017-07-14 21:49
Happens with this park too:
https://www.nedesigns.com/park/3372/morow-world/

**Comment by IntelOrca** [comment] 2017-07-19 17:15
The original issue has since been protected against.

@Liampie I tried that park and could not reproduce.

**Closed** 2017-07-19 17:16 UTC
Labels: crash, investigate
