### ISSUE TITLE
Allow other kinds of tracked rides to be used in the Roller Coaster Design mode

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#4824] opened 2016-11-23 08:39 UTC
As a follow-up to #4823, I've wondered for some time that if roller coasters can get their own sandbox, why not extend this to other kinds of rides with tracks from other categories, such as 
- Transportation rides (all kinds of them)
- Gentle rides (such as the car ride, tunnel of horror, monorail cycles, mini helicopters, observation tower, and maze)
- Thrill rides (such as the go karts, launched freefall, and the roto-drop)
- Other water rides (such as the boat hire, log flume, river rafts, river rapids, splash boats, and the submarine ride)

It would save players like me from having to open up a scenario to build these kinds of rides. Instead, players can just open the special Roller Coaster Designer, and build in there, without having to worry about weather, money, and other potential interferences. Though if this is to be accepted, the Roller Coaster Designer mode will need to be renamed to something more generic, to reflect that any kind of tracked ride is supported.

**Comment by hytacker** [comment] 2016-12-07 16:02
Maybe even adding the ability to place scenery on the rides. This way a coaster/ride can be made complitly in one time. Saving design with scenery has always been visible but can not be selected.

**Comment by X123M3-256** [comment] 2016-12-08 16:45
At that point, there is really no point in having the coaster designer, you might as well just use a blank map instead. In fact, that's what I do - the coaster designer is pretty much redundant since the object selection was made available in game.

**Comment by Patrik356b** [comment] 2016-12-17 21:26
There was already a discussion about this: 4135

**Comment by Gymnasiast** [comment] 2017-05-29 12:24
Duplicate of #4135.

**Closed by Gymnasiast** 2017-05-29 12:24 UTC
Labels: duplicate, feature
