### ISSUE TITLE
Misleading "Save this be..." button when exiting Track Designer

### ISSUE THREAD

**Issue by NinjaCowboy** [OpenRCT2/OpenRCT2#21052] opened 2023-12-04 17:50 UTC
### Operating System

Void Linux x86-64, kernel 6.5.12_1

### OpenRCT2 build

OpenRCT2, v0.4.6

### Base game

RollerCoaster Tycoon Classic

### Describe the issue

When attempting to quit the Track Designer, I get a dialog with two buttons: "Save this be..." and "Cancel". With the first button being truncated, it's impossible to guess what it should say (I'm guessing it's something like "Save this before quitting"). Clicking it doesn't appear to actually save anything, but exits Track Designer. Original RCT2 does not show any such popup when trying to exit Track Designer (or Roller Coaster Designer, as it's called there). 

### Steps to reproduce

1. Open Track Designer in OpenRCT2.
2. Build some track.
3. Wait a few minutes with fast-forward enabled to pass some time.
4. Exit Track Designer from the menu.
5. 

### Attachments

![Unnamed park 2023-12-04 11-06-06](https://github.com/OpenRCT2/OpenRCT2/assets/137745099/98b69117-4868-4424-aeb8-eba57a423f48)

**Comment by zzril** [comment] 2023-12-07 17:19
Duplicate of #20616.

**Closed** 2023-12-07 19:34 UTC
Labels: bug
