### ISSUE TITLE
[v0.1.3-bb42319] Assertion Failed, Tried getting sprite 65535

### ISSUE THREAD

**Issue by cheeseburgur101** [OpenRCT2/OpenRCT2#7396] opened 2018-04-09 20:53 UTC
**OS:** Windows 10
**Version:** v0.1.3-develop
**Commit/Build:** bb42319

Me and my friends were playing multiplayer, and ran into this same crash many, many times. There's 3 of us, and all of our games crash with an 'Assertion Failed: Tried getting sprite 65535'. Although the save was created in OpenRCT2 multiplayer, when loading it in singleplayer (OpenRCT2) it produces the same error, and loading it in vanilla RCT2 gave an 'Access Violation Error'. We've tried creating new saves, reloading old saves many times and it always seems to cause this crash. I've even tried using latest release (non-development build, 0.1.2) and it produces the same crash. After searching the forums and other GitHub issues, it seems no one has had this problem in over a year, which is odd since we seem to get it a lot.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load world
2. wait 30 seconds - 2 minutes

**Screenshots / Video:** 
![screenshot.png](https://user-images.githubusercontent.com/22647801/38521410-9b851464-3c13-11e8-95d1-fb8fdd665af2.PNG)
[Recording of crash](https://youtu.be/PcNZY_lRW9E)

**Save game:** [save.zip](https://github.com/OpenRCT2/OpenRCT2/files/1891699/save.zip)

**Comment by janisozaur** [comment] 2018-04-09 21:03
You're using an outdated version and it looks like this is a dupe of https://github.com/OpenRCT2/OpenRCT2/issues/7393.

Also there's no use posting such screenshots, when it should've been pasted as text, if at all, as it is all duplicated in what you've written.

**Comment by cheeseburgur101** [comment] 2018-04-09 21:04
I've just tried the save file in OpenRCT 0.1.3 build 124fb0d and the crash still occurs

**Comment by janisozaur** [comment] 2018-04-09 21:15
Yeah, it's a dupe of #7393. It will still hit the assertion as some invalid state made its way to the save, but you can workaround it by double-closing ferris wheel to force all guests out of it (you can later re-open it).

**Closed by janisozaur** 2018-04-09 21:15 UTC
