### ISSUE TITLE
Game is stuttering more than usual

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#7908] opened 2018-08-16 04:02 UTC
**OS:** windows vista 32-bit
**Version:** 0.2.0-331
**Commit/Build:** 90b40e6

ever since maybe between 2,3 or 5 updates ago, the game, during game play, and during opening sequence, is stuttering... maybe about 8 stutters per second, perceived mostly through audio, but also through graphical movement. The stuttering comes and goes some, but seems to be more frequent than it ever was before.
I have a slow computer, a year 2006 Toshiba laptop amd dual core.
I suppose something with my computer may have changed recently, otherwise i do not know why this is happening...

- [ ] Reproducible in RCT2 (vanilla)? No, stuttering seems to be decreased or non existent in vanilla
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. open a save game, especially a complex one, and observe stutter
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by jamtraks** [comment] 2018-08-16 04:12
I had user account control "on" when the game was stutteroing so now i've turned uac off and it seems to be better.

**Comment by AaronVanGeffen** [comment] 2018-08-18 08:16
Sorry to hear you're experiencing a slowdown. I cannot reproduce this, however.

Could you narrow this down to a specific version? You've mentioned 81b778f as a commit on which it happens, but what build actually introduced the problem for you? Since it's apparently very recent, you could try the versions on [OpenRCT2.org's download page](https://openrct2.org/downloads).

**Comment by jamtraks** [comment] 2018-08-18 14:02
I installed and ran "e87e9f1", as a test, because e87e9f1 was the oldest openrct2 version available on the download page (it's from 11 days ago). Then i compared that to the latest launcher download: "64d45bd". The older version "e87e9f1" does seem to stutter a little bit less than 64d45bd but its hard to see much difference.
I don't know what could change in the openrct2 software to cause "stuttering" but i am noticing it more than ever in recent updates. 
May be the openrct2 was stuttering before and i just didn't notice it until now. I do have a very slow computer and i plan on getting a newer one someday.
Well thanks anyway, i think it might just be my computer, i don't know...

**Comment by AaronVanGeffen** [comment] 2018-08-18 14:04
Could you try the v0.2.0 release version rather than a development build, then? Is there a significant difference in terms of this stuttering?

**Comment by jamtraks** [comment] 2018-08-18 14:31
Oh my windows install was at least 2 years ago maybe up to 5 years ago.?
I am planning on buying a new computer sometime soon.

**Comment by AaronVanGeffen** [comment] 2018-09-05 23:14
We recently identified a possible cause to this issue. I believe #7952 fixed your problem. Could you confirm this is the case?

**Comment by jamtraks** [comment] 2018-09-06 18:32
as of right now i am running version 0.20-331(90b40e6on develop). I tested "bobthegifty-rainbow_road" (just as a random .sv6). I tested it on vanilla vs. openrct2. The stutter is still present in openrct2. Completely non existent in vanilla though. In general the stutter may be slightly improved in openrct2 but it's still there.

**Comment by AaronVanGeffen** [comment] 2018-09-06 18:49
That is a rather old version. The newest build identifies as 0.2.1-34.

**Comment by jamtraks** [comment] 2018-09-06 18:55
Well i'm using the launcher, and this is it's latest update. I suppose i could wait until it decides to update again or i would have to manually install the newest version...

**Comment by AaronVanGeffen** [comment] 2018-09-06 19:00
The launcher is not something we develop, so I don't know how it checks for updates. I'd recommend you update manually instead.

**Comment by jamtraks** [comment] 2018-09-06 19:05
i installed "OpenRCT2-0.2.1-develop-a1fd033-windows-win32.exe" from https://www.openrct2.org/downloads/develop/latest. The stutter is still present. Is there a different version you recommend i install?

**Comment by AaronVanGeffen** [comment] 2018-09-06 19:13
That's pretty much as up-to-date as you can get. I had expected that version to work better for you, as it does contain the fix from #7952. Unfortunately, as it doesn't help, my best guess is off the table.

**Comment by janisozaur** [comment] 2018-09-06 20:14
@jamtraks are you running both (vanilla and OpenRCT2) in the same resolution? In options please enable showing FPS and report if OpenRCT2 reaches at least 40.

**Comment by ZehMatt** [comment] 2018-09-06 23:51
Are you using the OpenGL renderer perhaps? I've noticed some stuttering whenever I use OpenGL.

I've added a basic check to see when such things happen.
```
INFO[f:\c++\openrct2\src\openrct2\context.cpp:869 (OpenRCT2::Context::RunFixedFrame)]: Long tick detected, tick: 85295, time elapsed 46 ms
INFO[f:\c++\openrct2\src\openrct2\context.cpp:869 (OpenRCT2::Context::RunFixedFrame)]: Long tick detected, tick: 85296, time elapsed 595 ms
INFO[f:\c++\openrct2\src\openrct2\context.cpp:869 (OpenRCT2::Context::RunFixedFrame)]: Long tick detected, tick: 85297, time elapsed 51 ms
INFO[f:\c++\openrct2\src\openrct2\context.cpp:869 (OpenRCT2::Context::RunFixedFrame)]: Long tick detected, tick: 85298, time elapsed 663 ms
INFO[f:\c++\openrct2\src\openrct2\context.cpp:869 (OpenRCT2::Context::RunFixedFrame)]: Long tick detected, tick: 85399, time elapsed 26 ms
INFO[f:\c++\openrct2\src\openrct2\context.cpp:869 (OpenRCT2::Context::RunFixedFrame)]: Long tick detected, tick: 85400, time elapsed 26 ms
```

**Comment by jamtraks** [comment] 2018-09-07 00:40
I'm using software rendering in openrct2 i tried choosing "open gl" but openrct2 doesn't allow me to choose that for some reason. I just now compared vanilla to openrct2 again and the stutter persists in openrct2 and not in vanilla (both at 1280x800). If i set the resolution in openrct2 to 800x400, the game still seems to stutter some, and also i wouldn't want to have to play the game in that resolution. 
I noticed the options menu in vanilla is much more extensive then openrct2's  options menu, being that it has sound quality options and even a sound buffering option. The stuttering seems to be rooted more in the sound than anything else.

**Comment by ZehMatt** [comment] 2018-09-07 01:45
Some things to consider, please turn on the FPS counter in the options settings, the other thing is disable "Uncap FPS" the FPS should stay at consistent 40 FPS now. If the game really stutters it will drop below 40, if its audio stuttering it should stay unaffected. After that could you please try to disable the audio in the options and see if the issue still persists?

**Comment by Gymnasiast** [comment] 2020-02-15 13:33
Closing this, as it only seems to affect OP, who has (had?) an old computer running Windows Vista. It will be very hard to investigate, with a very limited return.

**Comment by janisozaur** [comment] 2020-02-15 20:28
@jamtraks is it still stuttering for you?

**Comment by jamtraks** [comment] 2020-02-18 09:49
Yes, but it might just be my computer. I am using an amd athlon x2 dual 64 2.1ghz (which is actually a 32 bit processor) that is in my year 2006 toshiba satellite laptop computer. This computer was not built for performance or gaming. When i have tried, on this laptop, to run the gamecube emulator- 'dolphin'- and when i opened any game-rom for it, that emulator would stutter.
I am currently using a very old openrct version for worry that updating to a newer version may cause me to have an openrct2 version that does not run at all, but i am fine for now with the stuttering. I am planning on setting up a more advanced desktop when i can afford one, or the parts for one i have, but until then, i don't think there's anything else i can do.

**Comment by janisozaur** [comment] 2020-02-18 10:28
The 32 bit versions for Windows are made so that they should run on such older systems, @IntelOrca only enabled more advanced optimisations for x86_64 builds.

As OpenRCT2 should be a portable binary, can you please download a new, separate build and test if the stutter persists? Please also provide more detailed specs of your system: exact CPU, GPU models, OpenRCT2 `config.ini` file and if possible record (with a camera) how exactly it stutters (enable FPS counter first), as well as how it compares against vanilla. That should help us figure out possible root causes.

**Comment by janisozaur** [comment] 2020-02-18 20:24
I managed to spend some time today with a [T9600](https://ark.intel.com/content/www/us/en/ark/products/35563/intel-core-2-duo-processor-t9600-6m-cache-2-80-ghz-1066-mhz-fsb.html)-based laptop and test performance of OpenRCT2 vs vanilla, using windows 10 and ddhack, which allowed me to use fraps to gather some performance metrics. I tested some older x86_64 build of OpenRCT2 and x86 build of a8b53047 Vs steam release of rct2. I set all versions to use 1280x1024 window and used the dome park to run the test. Vanilla scored 20-22fps, while both OpenRCT2 builds kept around 8fps. There is something going seriously wrong on our end to be nearly 3x slower than vanilla.

**Comment by ZehMatt** [comment] 2020-02-18 22:05
Well a lot of handcrafted asm is gone, the sprite sorter works a bit different as the raw x86 version compared to our C/C++ version.

**Comment by janisozaur** [comment] 2020-02-18 22:31
We always told people modern compilers trump the ASM of yore, was that a lie?

**Comment by janisozaur** [comment] 2020-02-18 22:54
I tested a few releases all the way back to 0.0.2 and all of them are this slow (0.0.1 doesn't have binary attached to the release). I haven't checked try, but I would expect the drawing code to still be used from the native version back then, so that most likely invalidates the argument about handcrafted ASM and puts the early SDL code as possible culprit.

**Comment by janisozaur** [comment] 2020-02-18 23:15
There is some code in https://github.com/OpenRCT2/OpenRCT2/blob/v0.0.2/src/drawing/sprite.c after all. Hefty chunk done in https://github.com/OpenRCT2/OpenRCT2/commit/b073c8eaef45aff97d8b12e942494075d2ade666, when the file was named `src/gfx.c`

**Comment by ZehMatt** [comment] 2020-02-18 23:20
I would recommend to just profile it, that eliminates all assumptions.

**Comment by janisozaur** [comment] 2020-02-18 23:25
I will surely profile our code, but that only tells me where we're slow, a more interesting question is where we're slower than vanilla and I have very limited possibilities of profiling that code. Do you have any suggestions?

**Comment by ZehMatt** [comment] 2020-02-18 23:35
If you can provide me the address of the original function then we can simply hook it and measure the average at least.

**Comment by janisozaur** [comment] 2020-02-18 23:40
How about https://github.com/OpenRCT2/OpenRCT2/blob/b3bf0663e54a94f3a9ec959519b3961b53eb74ec/src/drawing/sprite.c#L471 then?

**Comment by ZehMatt** [comment] 2020-02-19 04:38
Getting this too work took me literally all night but here you go:
```
Function: 0027A462 (gfx_draw_sprite_palette_set)
  Calls: 110798764
  Exits: 110798764
  Average Time: 0.00000035 secs
  Total Time: 38.77804500 secs / 183.30565000 secs (21.15485529%)
```
Note that the address is slightly different on the Steam version but its the same function.

**Comment by ZehMatt** [comment] 2020-02-19 05:36
More measurements:
```
develop x64
Function: 00000000 (gfx_draw_sprite_palette_set_software)
  Calls: 70862380
  Exits: 70862380
  Average Time: 0.00000016 secs
  Total Time: 11.31453600 secs / 60.24514500 secs (18.78082624%)
```
```
develop x86:
Function: 00000000 (gfx_draw_sprite_palette_set_software)
  Calls: 88450144
  Exits: 88450144
  Average Time: 0.00000019 secs
  Total Time: 16.56898700 secs / 60.30689600 secs (27.47444836%)
```
Total time is a little bit skewed but don't mind that part, its just total run time, for vanilla RCT2 I had to rely on a debugger so that time can not be considered accurate. However when it comes to the average we are clearly faster.

**Comment by ZehMatt** [comment] 2020-02-19 05:50
Also as I suspected already:
```
Vanilla:
Function: 0028820B (paint_arrange_structs)
  Calls: 293599
  Exits: 293599
  Average Time: 0.00001504 secs
  Total Time: 4.41437300 secs / 91.11218900 secs (4.84498622%)
```
```
ORCT2:
Function: 00000000 (paint_session_arrange)
  Calls: 513042
  Exits: 513042
  Average Time: 0.00002531 secs
  Total Time: 12.98285300 secs / 91.14640100 secs (14.24395572%)
```
One strange thing here is the amount of calls, vanilla is doing nearly only half of what we do, also performance is worse on our end as well so this isn't helping in any case.

**Comment by jamtraks** [comment] 2020-02-19 05:53
How do i install the latest version separately so that i can go back to my older version if i need to? is there a way i can do this?

**Comment by janisozaur** [comment] 2020-02-19 06:55
@jamtraks just download a "portable" build and launch it. The only thing it might do is change some settings in your `config.ini`, in the worst case the other version is unable to parse them, they will get restored to defaults. But you should be able to copy the file and restore it yourself. It's in `Documents/OpenRCT2`.

**Comment by janisozaur** [comment] 2020-02-19 07:00
@ZehMatt so the paint session arrange then? Even though the drawing is actually 3x faster, at least on your hw? Is it using our benchmark stuff? Can you provide a build that hooks to vanilla, so I can test in on my laptop? Many thanks for helping out in this investigation.

**Comment by ZehMatt** [comment] 2020-02-19 07:07
It depends a little on what RCT2 version you have, the Steam version has some packed binary and I have to rely a bit on a debugger to inject my dll after the code section has been restored. If you could provide me the GOG version I can see what I can do.

**Comment by IntelOrca** [comment] 2020-02-19 08:23
@ZehMatt @janisozaur said 0.0.2 is slow which predates any changes to `paint_arrange_structs`. How do you explain that?

**Comment by janisozaur** [comment] 2020-02-19 08:52
For 0.0.2 it seemed slow, but I wasn't able to get exact metrics from fraps, I guess the hw display was not enabled back then yet. Still a difference between 6fps and 20 is noticeable to the naked eye.

**Comment by Ruedii** [comment] 2020-09-16 12:00
Many of the issues come from the increased quality and increased limits.  My suspicion is that this is agrevating existing issues.

I noticed many segments of the game run on the world thread when that isn't necessary.

First on the rendering stack.  Currently the entire render process runs while the main loop is frozen from what I can tell.  This is pretty wasteful.   

A snapshot list of the objects in need of rendering to the screen could be copied out to an array at the end of frame simulation and then the game can resume as it converts the list into draw instructions and renders them.  To further parallelize, this buffer could be page-flipped out providing a blank buffer, and the same could be done on the final draw buffer, allowing two in-progress frames to be drawn.  The use of Z-Data in this set could allow the use of fast-z stenciling.  As the game currently is we won't see over 1024 layers on the screen, let alone the 16K or 4G which would make this impractical to use due to z-fighting. 

For OpenGL rendering, a pixel shader could be theoretically written to convert this list (in the form of a series of array structures) into draw calls using pixmap assets in memory. 

As of simulation, that too should be offloaded onto parallelized helper threads to reduce time in single-threaded world loop lock.

While I can't write the actual code for either of these just yet (I'm barely familiarizing myself with the codebase). I could draw out some flow charts on how to break down the logic if someone wants to fill in the gaps to turn those into code.

**Comment by IntelOrca** [comment] 2020-09-16 12:31
> A snapshot list of the objects in need of rendering to the screen could be copied out to an array at the end of frame simulation and then the game can resume as it converts the list into draw instructions and renders them.

The game update can only progress after the draw tree has been constructed which unfortunately is most of the cost in OpenGL mode (probably 1/3 or 1/2 in Software). Attempting to copy the entire game state could also be expensive, given the size of it. Not sure how feasible that is.

**Comment by ZehMatt** [comment] 2020-09-16 20:23
> I experience the same issues in Linux on 0.3.0 They improved substantially in 0.3.0 over the stable 0.2.x series. So, it's not like it's not improving.
> 
> Many of the issues come from the increased quality and increased limits. My suspicion is that this is simply making existing issues worse. Our codebase may not be as cleanly optimized yet as the RTC2 codebase either.
> 
> I noticed most of the game runs on the main thread when that isn't necessary.
> 
> First on the rendering stack. Currently the entire render process runs while the main loop is frozen from what I can tell. This is pretty wasteful.
> 
> A snapshot list of the objects in need of rendering to the screen could be copied out to an array at the end of frame simulation and then the game can resume as it converts the list into draw instructions and renders them. To further parallelize, this buffer could be page-flipped out providing a blank buffer, and the same could be done on the final draw buffer, allowing two in-progress frames to be drawn. The use of Z-Data in this set could allow the use of fast-z stenciling. As the game currently is we won't see over 1024 layers on the screen, let alone the 16K or 4G which would make this impractical to use due to z-fighting.
> 
> For OpenGL rendering, a pixel shader could be theoretically written to convert this list (in the form of a series of array structures) into draw calls using pixmap assets in memory.
> 
> As of simulation, that too should be offloaded onto parallelized helper threads to reduce time in single-threaded world loop lock.
> 
> While I can't write the actual code for either of these just yet (I'm barely familiarizing myself with the codebase). I could draw out some flow charts on how to break down the logic if someone wants to fill in the gaps to turn those into code.
> 
> I'd like to note that in ANY game like this, stutter will be a constant battle. There is literally no way around it. I suspect this issue will be turned into a meta-issue for this, unless a dedicated one is created.
> 
> I could list all the things that cause stutter. I noticed you are already dealing with some of them, like moving temporaries to be marked as such so the compiler deals with them accordingly.

It all sounds pretty nice in theory but in practice this is not so easy I'm afraid. I've experimented with this before and its better to get to the root cause of the stutters than trying to introduce new complex code and locking all over the place. RCT/RCT2 also used a much lower resolution while we allow basically any resolution, if you run it with the original maximum resolution we usually outperform the original game. A lot of things have been already optimized and there is only so much you can do when you have such a large simulation. The way to go on about this is to just profile what functions are taking longer than expected.

**Comment by jamtraks** [comment] 2021-06-22 23:33
I have a new computer now, a windows 10 64-bit laptop, manufactured in 2021. I no longer have the stuttering issue. Although people using older computers might... 
Anyway, thanks.

**Closed** 2024-10-18 10:15 UTC
Labels: epic, help wanted, performance
