### ISSUE TITLE
Banked diagonal inclines using wrong train sprites when reversed

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#20183] opened 2023-05-11 07:39 UTC
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2, v0.4.5

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When a train reversed via the reversed trains option enters a banked diagonal incline, it will use the wrong sprites.

### Steps to reproduce

1. Build a hybrid/single rail coaster with banked diagonal incline pieces
2. Enable the reversed trains option
3. The trains will use the wrong sprites when travelling through the banked diagonal incline pieces

### Attachments

![Screenshot_select-area_20230511033333](https://github.com/OpenRCT2/OpenRCT2/assets/42477864/756ee828-2c1a-4332-9b10-12757cc65613)
![Screenshot_select-area_20230511033340](https://github.com/OpenRCT2/OpenRCT2/assets/42477864/7ef2d953-74bc-49f9-9454-2e68adcabcb2)
![Screenshot_select-area_20230511033543](https://github.com/OpenRCT2/OpenRCT2/assets/42477864/f7a85921-e305-48cf-8af5-6ba0e90d6ac0)
![Screenshot_select-area_20230511033549](https://github.com/OpenRCT2/OpenRCT2/assets/42477864/b0a3f60d-cd1a-4036-a2eb-ac51cfaefb91)

**Comment by zzril** [comment] 2024-01-18 20:42
Duplicate of #20389 (or rather the other way around), was fixed by #20570 .

**Comment by tupaschoal** [comment] 2024-01-19 11:11
Thanks for letting us know. @ZeeMaji do comment/reopen if you disagree

**Closed by tupaschoal** 2024-01-19 11:11 UTC
Labels: bug
