### ISSUE TITLE
Textures missing on scenario loading

### ISSUE THREAD

**Issue by MisterSchmidt** [OpenRCT2/OpenRCT2#7423] opened 2018-04-17 21:42 UTC
OS: _Windows 10_
version: _0.1.3_
build: _11207f9_

Some weird path loading issues which can be fixed by starting the scenario multiple times in a row without closing down the game. I found this issue by looking at the Path menu and also noticed the Park Entrance disappearing.

- [ **No** ] Reproducible in RCT2 (vanilla)?
- [ **No** ] Specific to multiplayer?

1. Start game.
2. Open a scenario or savegame with preferable mutliple paths.
3. Look in the path menu. (some paths should be missing.)
4. Close scenario.
5. Open the same scenario again.
6. Take another look in the path menu. (less paths should be missing then before)

My Example, I also tried this with a savegame

**First load:**
![naamloos1](https://user-images.githubusercontent.com/11180804/38899526-67a56302-4298-11e8-9352-7764b35ba1e4.jpg)

**Second load after closing scenario:**
![naamloos2](https://user-images.githubusercontent.com/11180804/38899573-8f2f75f2-4298-11e8-9b75-84a9dce21829.jpg)

**Third load after closing scenario:**
![naamloos3](https://user-images.githubusercontent.com/11180804/38899582-95191554-4298-11e8-8153-78ff190052a3.jpg)

**Comment by AaronVanGeffen** [comment] 2018-04-17 21:44
Looks like your savegame is including too many objects. Try opening the object selection window and deselecting some. (Keep an eye on the limits in the status bar.)

**Comment by MisterSchmidt** [comment] 2018-04-17 21:48
There is a limit isn't there?

**Comment by AaronVanGeffen** [comment] 2018-04-17 22:03
There is indeed, but the image limit may still be exceeded if large objects are selected. We recently learned as much in https://github.com/OpenRCT2/OpenRCT2/issues/7294.

**Comment by MisterSchmidt** [comment] 2018-04-17 22:13
Uhm ok, an image limit, what do you suggest? disabling some Large Scenery as they are in the same category as paths or someting?

**Comment by MisterSchmidt** [comment] 2018-04-17 22:51
Ah, I get the problem now! I disabled a lot of rides which seem to fix the problem indeed. And here's a save file with the issues. 

[Jupiter Lawn (image limit).zip](https://github.com/OpenRCT2/OpenRCT2/files/1921874/Jupiter.Lawn.image.limit.zip)

**Comment by Gymnasiast** [comment] 2019-08-23 18:47
I can no longer reproduce this issue on the current develop version of OpenRCT2. Could you try for yourself to see if the issue is solved?

**Comment by Gymnasiast** [comment] 2019-08-29 21:14
Closing this as I can no longer reproduce it. If the issue is still there, please say so and I'll reopen this.

**Closed by Gymnasiast** 2019-08-29 21:14 UTC
Labels: investigate
