### ISSUE TITLE
Animations for steam trains and helicopters do not play

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6366] opened 2017-10-04 09:57 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** 8d2769d

These two rides are perfectly static. The steam train's wheels don't move, and the helicopter's rotor does not spin. These two are animation type (var_11) 0x01 and 0x07 respectively.

![image](https://user-images.githubusercontent.com/3454156/31170042-82cb20aa-a8af-11e7-8515-95f19a0348ac.png)

https://gfycat.com/RegularTornCommabutterfly

The observation car is unaffected. Its animation type is 0x06.

**Comment by spacek531** [comment] 2017-10-04 10:06
I lost 2 hours of sleep from this bug.

It is my most fiersome enemy.

**Comment by Gymnasiast** [comment] 2017-10-04 10:22
Perhaps related to #6245?

**Comment by oli414** [comment] 2017-10-04 12:33
Partial duplicate of: #6118

**Comment by oli414** [comment] 2017-10-04 13:28
@Gymnasiast this issue can be closed.

**Closed** 2017-10-04 13:29 UTC
Labels: bug
