### ISSUE TITLE
Custom scenery causes "ghost" and duplicate scenery groups in inventions list when deselected

### ISSUE THREAD

**Issue by hypocube** [OpenRCT2/OpenRCT2#2326] opened 2015-11-17 03:16 UTC
Steps to reproduce:

1. Open scenario editor, select a custom scenery group.
2. Go to inventions list and move all scenery to bottom (easier to see effect)
3. Go back to object selection, deselect that custom scenery.
4. Go to inventions list. If there's no duplicate scenery, repeat 1-3.

Before glitch: 
![](https://i.gyazo.com/f9ac4da9c727020f0c5fa4802b9639fe.png)

After glitch:
![](https://i.gyazo.com/6c7f2b3ec0782e0c18b8fb833d6ea1e4.png)

If you deselect the vanilla RCT2 sceneries that are duplicated, it might create a ghost, blank scenery group.

![](https://i.gyazo.com/668d878dd35d75a2cc92e54573df39b9.png)

The blank scenery group cannot be removed and will crash the scenario if researched or if it is pre-invented.
If the duplicate sceneries are researched, nothing abnormal happens other than a scenery group already researched getting researched.

I can't seem to reproduce this in Vanilla RCT2

Version:
![](https://i.gyazo.com/fc8b64ea9734e716c52ab10f963b74cc.png)

I created a scenario with custom scenery and this is causing me trouble.

**Comment by hypocube** [comment] 2015-11-21 21:50
So I've done some more testing with this, in which I discovered that it is not exclusive to custom scenery. The TL:DR is this: When going back to the Invention List with a ride in the bottom part, there's a chance it can duplicate to the top. The bug hasn't worked when I simply go to the Landscape Editor and back, only to Object Selection and back.

1. In scenario editor, deselected all rides except for Air Powered Vertical Coaster (APVC)
2. Made a minimal park to go to Invention List
3. APVC was in top.
4. This is a step I repeat a lot. I go back to the object selection and go back to invention list.
5. After repeating Step 4 about ten times, I discovered that while the APVC is in the top, no duplicates are made.
6. Moved APVC to bottom invention list.
7. Repeated Step 4 several times.
8. On the second repeat, an APVC was created in the top. 
9. Without moving it, repeated step 4 more times.
10. Nothing happened so I moved the APVC down to the bottom (there's two now)
11. Repeated Step 4, second time a third APVC appeared in the top.
12. Moved it to the bottom, repeated Step 4 three times and a fourth appeared.
13. This time I go into Object Selection, deselect APVC, and select Miniature Railroad.
14. Went back into Invention List
15. APVC is on the bottom but with the picture of Miniature Railroad. 
16. Went back to Object Selection to check that I unchecked APVC, and it was unchecked.
17. Repeated Step 4 a few times with no results.
18. Moved Miniature Railroad to bottom. 
19. Repeated step 4 several times and Miniature Railroad moved itself to the top.
20. Decided to make it a scenario to see what would happen if I researched the APVC with an icon of Miniature Railroad.
21. Opened park, sped up time. Only thing to research was in Rollercoasters.
22. It showed up in Research and Development as Air Powered Vertical Coaster.
Got the message "New ride/attraction new available: Air Powered Vertical Coaster"
23. When the ride icon is clicked on, it just goes to Miniature Railroad.
24. Opened the park back up in scenario editor.
25. Deselected Miniature Railroad and selected Boat Hire.
26. The Miniature Railroad with the APVC text turns into Canoes, so there's two canoes.

![](https://i.gyazo.com/12766e2e05fa91a6ffbdf0b307c5afd4.png)

**Comment by duncanspumpkin** [comment] 2015-11-23 18:26
This was an amusing one to solve. Issue was caused by not checking to see if the item is already in the populated list invented section. When placing items randomly. Fixed in the pre-release.

**Closed by duncanspumpkin** 2015-11-23 18:26 UTC
Labels: bug
