### ISSUE TITLE
Messages about killed guests suppressed for Six Flags scenarios

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2382] opened 2015-11-26 22:37 UTC
The original RCT2 will trigger an alert message when a guest drowns or when peeps die in a ride crash... except in Six Flags scenarios.  This is almost certainly intentional, so this message-suppressing behavior—faithfully carried over to build 1475—is not a bug.

At the same time, we've made efforts to reduce the game's special considerations for Six Flags rides and scenarios via #1694 and #969, among others.  Should we do the same for this issue?

I don't have a strong opinion one way or the other, but I think it's a worthy topic of conversation.

**Comment by IntelOrca** [comment] 2015-11-26 22:49
The special behaviour should probably be removed.

**Comment by xzyxzy** [comment] 2015-11-26 23:13
Removed and making it optional? Sort of "vanilla" mode?

**Comment by IntelOrca** [comment] 2015-11-26 23:23
@xzyxzy i can't imagine a single player caring about wanting these messages to be hidden for just six flag parks

**Comment by xzyxzy** [comment] 2015-11-27 07:52
@IntelOrca "Purists" you know. The same reason Chocolate Doom exists and most doom ports having tons of "vanilla mode" flags. Not saying that is priority, just maybe some people would like that.

**Comment by IntelOrca** [comment] 2015-11-27 08:07
@xzyxzy I think that's against the objective of this project.

**Comment by HaasJona** [comment] 2015-11-27 08:16
The limitations probably just existed for legal reasons because six flags demanded that their rides don't break down and guests don't die in their park and so on. I can't imagine any reason why anyone would want these limitations from a gameplay perspective.

**Comment by duncanspumpkin** [comment] 2015-11-27 12:31
The part where it suppress the number of fatalities in a crash is in vehicle-update https://github.com/OpenRCT2/OpenRCT2/blob/vehicle-update/src/ride/vehicle.c#L2203 so it can't be done till that is merged.

**Comment by Gymnasiast** [comment] 2015-11-29 18:37
I am very much in favour of getting rid of the special treatment.

**Comment by duncanspumpkin** [comment] 2015-11-29 18:38
There are a few other things i've come across in vehicle-update that check the six flag flag. Does anyone have a list of everything it changes?

**Comment by Gymnasiast** [comment] 2015-11-29 18:41
The ones I'm aware of:
- Suppressing the number of fatalities in a ride crash
- No message saying a guest has drowned
- Brakes failure impossible*
- Not being able to save and edit (removed in OpenRCT2)

I would be in favour of removing this one as well.

**Comment by Gymnasiast** [comment] 2015-11-29 18:58
By the way, the offending line about the ride crash fatalities is this one, I think:
https://github.com/OpenRCT2/OpenRCT2/blob/vehicle-update/src/ride/vehicle.c#L2744

**Comment by IntelOrca** [comment] 2015-11-29 19:00
I came across one in my sub_6DAB4C branch, but I have no idea what it is for. It is part of a flag that is returned from the function.

**Comment by Christipher** [comment] 2015-11-30 20:36
I also can note that this was suppressed in Crazy Castle scenario (possibly an inconsistency, and also that the worst amusement park accident did occur in a six flags park)

**Comment by Gymnasiast** [comment] 2015-11-30 21:21
@Christipher : Cannot reproduce this in Crazy Castle using stable 0.0.3. It only shows the message when there are fatalities, btw.

**Closed** 2015-12-26 17:40 UTC
Labels: discussion
