### ISSUE TITLE
[Feature Request] More zoom levels please

### ISSUE THREAD

**Issue by artao** [OpenRCT2/OpenRCT2#2234] opened 2015-11-08 01:55 UTC
Particularly when running at higher resolutions, the display of the graphics of the park can get rather small and hard to see well enough to work with comfortably. It would be very nice to be able to zoom in further.

**Comment by IntelOrca** [comment] 2015-11-08 02:13
Duplicate of #775

**Closed by IntelOrca** 2015-11-08 02:13 UTC
Labels: duplicate
