### ISSUE TITLE
Ride entrance/exits deletes walls with zero clearance

### ISSUE THREAD

**Issue by MaxMallon** [OpenRCT2/OpenRCT2#21046] opened 2023-12-04 09:50 UTC
### Operating System

win11

### OpenRCT2 build

Latest Dev (4-12-2023)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

This issue has been in the game for ages.
If you build a ride's entrance/exit on a tile that has walls, it will delete those walls. Normally fine, but not when you have zero clearance on.
If you have some super ornate building, with layered walls, all ordered in tile inspector etc, and wanna put a ride inside it, you're guaranteed to lose work, as the exit/entrance delete part of your building. 

### Steps to reproduce

Place wall
Turn off clearance checks
Build ride
Put exit in tile with wall

**Comment by MaxMallon** [comment] 2023-12-20 08:45
I have made a PR for this problem

**Comment by Broxzier** [comment] 2023-12-20 11:39
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/12299

**Closed by Broxzier** 2023-12-20 11:39 UTC
Labels: bug
