### ISSUE TITLE
Game crashing upon loading savegame

### ISSUE THREAD

**Issue by DisneyPrincessss** [OpenRCT2/OpenRCT2#3886] opened 2016-06-16 11:39 UTC
**OS:Windows 8**
**Version:0.0.5** 
**Commit/Build:920** 

Game crashes and shuts down when I try loading a savefile I've been playing on a couple of days. We've been playing on it with 2 players over a lan-connection, I was playing on it, other computer tried to connect to server and crashed. I shut down the server, tried to load the game and got the same crash.

- [ x ] Reproducible in RCT2 (vanilla)?
- [ ./ ] Multiplayer?

**Steps to reproduce:**
1. Start server (or load the file singleplayer)
2. Crash

**Dump file**
I'm pretty sure it gave me a dump file, don't know where to find it though.

**Save game:**
[WeTransfer](https://www.wetransfer.com/downloads/d3629c739cf9d35686089ddbfc891e4620160616113721/989288a1365c4e477a1a9e67165606a120160616113721/e5c284)

**Comment by janisozaur** [comment] 2016-06-16 11:45
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3193

**Comment by DisneyPrincessss** [comment] 2016-06-16 11:50
I'm sorry :(

**Comment by janisozaur** [comment] 2016-06-16 11:51
That's no problem, it's not easy to figure that out unless you load it into debugger.

**Comment by janisozaur** [comment] 2016-06-16 12:20
Basically: there are missing objects that were not exported with this save. The code to let user know about which ones appears to be broken.

**Comment by DisneyPrincessss** [comment] 2016-06-16 12:21
Is there a way to retrieve those objects?

**Comment by janisozaur** [comment] 2016-06-17 06:42
@DisneyPrincessss can you tell us which commit you were using? It seems a regression may have entered the code and while the crashing is the same as #3193, it shouldn't really happen in such scenario.

**Comment by janisozaur** [comment] 2016-06-17 06:57
Regression from #3884, 7c9f59f works correctly

**Closed** 2016-06-17 07:30 UTC
