### ISSUE TITLE
Guests are unable to out from toilet if its exit is slope

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#11477] opened 2020-04-26 16:16 UTC
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 8936ce6

Guests who used the toilet won't get out from it if exit path is slope, especially upper slope.
See the GIF below.

**Steps to reproduce:**
1. Build a toilet
2. Connect path as upper slope.
3. Guest who used the toilet won't get out

**Screenshots / Video:**
![2](https://user-images.githubusercontent.com/10726524/80313224-846a9880-8824-11ea-87e7-dd58cd2f6ee3.gif)

**Comment by tupaschoal** [comment] 2020-04-26 16:36
Sounds like a duplicate of #10634

**Closed** 2020-04-26 17:40 UTC
Labels: duplicate
