### ISSUE TITLE
Seems that css50.dat is not loaded properly

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#6466] opened 2017-10-14 05:20 UTC
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** ab38357

As you can see in [this code](https://github.com/OpenRCT2/OpenRCT2/blob/2d993671599ffd133b56694f68de1837ff605cbb/src/openrct2/Context.cpp#L233),
it seems that OpenRCT2 loads RCT1 title music as ``(RCT1 path in option)/data/css17.dat``, not ``(OpenRCT2 path)/data/css50.dat``.
I think it should be splitted into two parts:
 1. using css50.dat file only
 1. using original RCT1 path

p.s. I know there is [Setting](https://github.com/OpenRCT2/OpenRCT2/wiki/Loading-RCT1-scenarios-and-data) to load RCT1 scenarios and data, but it is uncomfortable if there is a user like me who uses alternative RCT1 scenarios imported to RCT2. (downloadable at [here](http://www.mediafire.com/download/3cw47sd2wt3hues/ExactRCT1Recreations.zip))
The part detecting RCT1 title music should be splitted into two part to support users who uses alternative RCT1 scenarios like me.

**Steps to reproduce:**
1. Install OpenRCT2 with vanilla or demo, without RCT1, (eg. install at ``C:/OpenRCT2/``)
2. Copy css17.dat from RCT1, rename it css50.dat and move to OpenRCT2 data folder(eg. ``C:/OpenRCT2/data/css50.dat``)
3. Run game and select RCT1 title music
4. Error: couldn't find css50.dat

**Comment by IntelOrca** [comment] 2018-04-13 10:18
Duplicate of #6141

**Closed by IntelOrca** 2018-04-13 10:19 UTC
Labels: duplicate
