### ISSUE TITLE
Routine fix.

### ISSUE THREAD

**Issue by CamdenShadowWolf** [OpenRCT2/OpenRCT2#14520] opened 2021-04-23 18:02 UTC
**OS:** Windows 10
**Version:** v0.3.3
**Commit/Build:** 3f65f28

After using the Object Selection cheat, the ride trains don't appear on the selection.  I have to save and reload the save in order to see them on screen.  I've had this issue for a bit and I'm surprised nobody noticed it earlier.

![RCTProblem](https://user-images.githubusercontent.com/77296291/115911449-1a3b0280-a43c-11eb-9abb-7718a971af69.png)

**Comment by Fred-1044276** [comment] 2021-04-23 18:26
I've also had this issue occur when I get a new vehicle type researched, e.g. Floorless Twister Trains in Extreme Heights.

**Comment by Gymnasiast** [comment] 2021-04-24 08:12
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/12981 and #12121.

**Closed by Gymnasiast** 2021-04-24 08:12 UTC
