### ISSUE TITLE
Client-side staff hiring crashes game

### ISSUE THREAD

**Issue by mclucario** [OpenRCT2/OpenRCT2#4491] opened 2016-09-26 15:32 UTC
**OS: Windows 10**
**Version: 0.0.5**
**Commit/Build: CE74CA9**

As I tried to add personell (clientside) it cashed (clientside only)

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Open a Server
2. Try to add personell clientside.

**Dump file**
[8590ff74-4dd2-4d5f-b988-ac90a1f75135(ce74ca9).zip](https://github.com/OpenRCT2/OpenRCT2/files/493454/8590ff74-4dd2-4d5f-b988-ac90a1f75135.ce74ca9.zip)

**Screenshots / Video:**

![2016-09-26_17-31-38](https://cloud.githubusercontent.com/assets/10533763/18840509/1de2954e-840f-11e6-866b-b242b91bd0ca.png)

**Save game:**

[8590ff74-4dd2-4d5f-b988-ac90a1f75135.zip](https://github.com/OpenRCT2/OpenRCT2/files/493457/8590ff74-4dd2-4d5f-b988-ac90a1f75135.zip)

**Comment by Gymnasiast** [comment] 2016-09-26 15:39
This is a known issue, but I'm not sure if it's actually in the issues list. And I'm not sure it has actually caused crashes before - I'm only aware of desyncs.

**Comment by duncanspumpkin** [comment] 2016-09-26 16:31
It can do pretty much anything it will access an invalid sprite and try turn it into a staff. Crashes are expected.

**Comment by IntelOrca** [comment] 2016-09-26 17:03
We should put in a check to make sure it only updates the sprite if the staff ID is the same... otherwise it corrupts other things and misleads issues else where.

**Comment by IntelOrca** [comment] 2016-09-30 11:13
Duplicate of #1943

**Closed by IntelOrca** 2016-09-30 11:13 UTC
Labels: crash, duplicate, multiplayer
