### ISSUE TITLE
[Vanilla] Restore Pricing Algorithm for Flat Rides / Coasters

### ISSUE THREAD

**Issue by Marcus101RR** [OpenRCT2/OpenRCT2#13244] opened 2020-10-19 18:13 UTC
_**Current Version:** OpenRCT2 v0.3.1 (d01dcea)_

This is to get the original Vanilla experience for Pricing Rides. For some reason, in this game 3x3 Flat Rides refuse to go any higher than $2.00, while in Vanilla games they can be pushed up as high as $6.00, but typically $3, to $2, then finally $1 depending on factors the game uses.

In OpenRCT2 this seems to be drastically lower, not sure if this is intentionally to change the difficulty of the game or an overlooked function.

Would prefer if this stays as close to vanilla as possible when playing this game legit as it was first intended.

EG:
![image](https://user-images.githubusercontent.com/8344293/96495051-466b9180-1215-11eb-93cb-bec477fcb608.png)
[https://i.imgur.com/7uzixjc.png](url)

**Comment by ocalhoun6** [comment] 2020-10-19 18:33
These rides are near trees (scenery items) which will raise the excitement slightly and slightly increase the amount peeps are willing to pay.

Not that it accounts for much of the actual difference, but if you're going to compare vanilla vs open behavior, it would be best to do so on a blank map where there would be fewer variables involved. That would allow the comparison to be more exact.

**Comment by Marcus101RR** [comment] 2020-10-19 18:54
> These rides are near trees (scenery items) which will raise the excitement slightly and slightly increase the amount peeps are willing to pay.
> 
> Not that it accounts for much of the actual difference, but if you're going to compare vanilla vs open behavior, it would be best to do so on a blank map where there would be fewer variables involved. That would allow the comparison to be more exact.

I wouldn't know here to get a Blank Map for RCT, since it doesn't come with an editor. I can do put it in the middle of the map with no trees nearby and then the same on OpenRCT2 and show you the price difference. I just still think its significantly different though. I managed to already find the algorithm with the assembly the oddball 0x07 number is strange, but boosting it up seems to emulate closer to RCT/RCT2 playstyle then openrct. If putting it in Forest Frontier middle of the map with nothing else would that be enough to show the accuracy?

**Comment by jensj12** [comment] 2020-10-19 19:08
Currently OpenRCT2 deliberately deviates from vanilla RCT(2), see [RideRatings.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/RideRatings.cpp#L790). For expensive rollercoasters the price is roughly the same, but small flat rides had their maximum price in the first few months significantly lowered. For discussion, see [#5294](https://github.com/OpenRCT2/OpenRCT2/pull/5294).

**Comment by duncanspumpkin** [comment] 2020-10-20 06:33
This is just a duplicate of the discussion that was had in #5294. If you want to use the old pricing you can by building with the ORIGINAL_RATINGS flag enabled.

**Closed by duncanspumpkin** 2020-10-20 06:33 UTC
Labels: duplicate
