### ISSUE TITLE
Reverse boosters - possible?

### ISSUE THREAD

**Issue by chaitanyathengdi** [OpenRCT2/OpenRCT2#12302] opened 2020-07-17 20:11 UTC
I've made a coaster design, let's call it the Shuttle Double Loop due to the dual loops and the similarity to Shuttle Loop:

![image](https://user-images.githubusercontent.com/14993220/87826776-1cfa3d00-c897-11ea-9958-ff872693ef32.png)

To avoid having to go too fast through Loop 1(the one with the train in it), I've installed two booster pieces to speed the train up through Loop 2, so that when the train comes back from the hill, it has enough speed to go back up the curved drop and still clear the higher-up Loop 1.
Now, the boosters don't work backwards when the train is coming back from the hill, so I've had to put the train unnecessarily fast through loop 2 even though it's not required. If I had booster pieces that worked backwards, this could have been avoided.
Is it possible to add reverse boosters(or any reverse pieces, for that matter)?

**Comment by Umdlye** [comment] 2020-07-17 20:20
This has been discussed in #6453, looks like it would require the new save format.

**Comment by Gymnasiast** [comment] 2020-07-17 21:58
Duplicate of #6453 , indeed.

**Closed by Gymnasiast** 2020-07-17 21:58 UTC
Labels: duplicate
