### ISSUE TITLE
Trash cans and other items do not appear in 'Signs and Items for Footpaths' tab

### ISSUE THREAD

**Issue by jjohnson9899** [OpenRCT2/OpenRCT2#21693] opened 2024-03-30 22:22 UTC
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.9 (a172405) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Trash cans and other items do not appear in 'Signs and Items for Footpaths' tab after use. save, quit, and loading. 

### Steps to reproduce

1. New game 'Asia - Great Wall of China Tourism Enhancement'
2. Place some 'Litter Bins' on a path
3. Save your game as a new file
4. Restart your game
5. Load your save and you will no longer have access to litter bins

**Comment by SidaRadis** [comment] 2024-03-31 21:09
To add a bit of information, this bug only happens when a footpath item is selected but not its scenery group. For example, if the Egyptian theme is selected the stone bench doesn't disappear.

**Comment by Gymnasiast** [comment] 2024-04-08 11:07
This looks like a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/21496 to me.

**Closed by Gymnasiast** 2024-04-08 11:07 UTC
Labels: bug
