### ISSUE TITLE
Sprites in scenery selection menu are glitched

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#14943] opened 2021-06-23 22:25 UTC
OS: WIndows 10
Version: .park format
Build: Latest .park build

Issue:
I was creating a scenario and adding a selection of custom scenery to the scenery menu, when I noticed that some of the item sprites had been replaced with a generic grass land texture (not even the whole texture either, just a triangular grass bit). I have no idea what caused it, but I have a feeling it involves having a large number of scenery items selected, or maybe selecting them too quickly/frequently. I think it is worth noting that I use an auto clicker set to 10 clicks per ms, so this can't be reproduced entirely by a human.

Reproducable in Vanilla: No
Multiplayer: No

**Steps to reproduce:**
Not entirely sure how to reproduce, but I believe it involves selecting too many items/selecting them too quickly.

**Comment by Gymnasiast** [comment] 2021-09-26 21:41
This is simply caused by having too many images loaded and not specific to the new save format. I’d point you to the correct issue, but I can’t for the life of me _find_ it.

**Comment by IntelOrca** [comment] 2021-09-27 09:02
@Gymnasiast I think we closed previous ones after raising the image limit. This was good enough for the original object limit, but not the new limits.

Even if we are able to increase the numerical limit of image ID, I expect some people will hit a limit based on their RAM or VRAM (in OpenGL) capacity. So warning messages may also need to be implemented, and a way of displaying an obvious ? image instead of nothing or random stuff.

One of the previous issues: #6073

**Comment by Gymnasiast** [comment] 2021-12-18 19:47
@Derpercoaster We merged a commit today that increases the image limit. Could you test if this solves the problem for you?

**Closed** 2021-12-20 08:53 UTC
Labels: duplicate

**Comment by Derpercoaster** [comment] 2021-12-20 18:26
@Gymnasiast I would, but I don't know which one I'm supposed to use. Can you link the correct one here?

**Comment by Gymnasiast** [comment] 2021-12-20 21:57
Just pick the newest `develop` build.
