### ISSUE TITLE
Linebuild Fences/walls

### ISSUE THREAD

**Issue by Generalcamo** [OpenRCT2/OpenRCT2#9438] opened 2019-06-17 03:32 UTC
Currently, all fences and walls must be placed a single tile at a time. It would be far easier to instead have the ability to click and drag a line of fences/wall, like what many newer games do.

**Comment by IntelOrca** [comment] 2019-06-17 06:43
Duplicate of #6355

**Closed by IntelOrca** 2019-06-17 06:43 UTC
