### ISSUE TITLE
Broken peep AI: peeps are heading for entrance huts, not queue entrances

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3541] opened 2016-05-09 09:17 UTC
See title. In the original game, peeps could find the rides alright, heading for the queue entrance as they should. This gives a lot of problems, unsolvable without redoing entire park sections, when peeps are getting stuck in a corner somewhere because their AI changed from when the area was originally built. In general, this AI mechanic limits park composition a lot. I hope you can solve this soon, because it's the only thing in OpenRCT that ruins my fun occassionally. The other bugs are so minor I can live with them, and the beneifts of Open more than compensate for them. This one though... renders parks made before OpenRCT unusable.

**Comment by janisozaur** [comment] 2016-05-09 09:34
Isn't it dupe of #2499 ?

**Comment by Gymnasiast** [comment] 2016-05-09 09:55
@janisozaur Hm, I don't think so. And at least this is something we should be able to check more easily than #2499.

**Comment by Liampie** [comment] 2016-05-09 10:02
I expected this issue would've been brought up before, and the search engine dd bring me to #2499, but it is not the same at all. Definitely a different issue.

**Comment by IntelOrca** [comment] 2016-05-09 11:11
Originally guests only set their destination to a ride if very close to it. Because the range was increased (because it looked like a bug in the original game), this has made not finding the ride more likely.

**Comment by Liampie** [comment] 2016-05-09 12:58
Peeps have always been heading to rides even if they were on the other side of the map. I'm talking about a 120x120 plus map size here. And the peeps getting stuck hasn't got anything to do with these distance, because the peep jams I'm talking about can occur less than ten tiles away from the ride. They just seem to flock to the stations.

**Comment by IntelOrca** [comment] 2016-05-09 14:53
> Peeps have always been heading to rides even if they were on the other side of the map.

Are you sure about that? Did they have a cuddly toy?

**Comment by jensj12** [comment] 2016-05-09 15:42
I get your issue. If there's a queue path from the entrance, the queue entrance could be miles away from the entrance (hut) itself. Guests are heading for the entrance hut instead of the queue entrance which sometimes leads to guests getting lost. If that's what you're saying, I can't yet reproduce the issue.
The only situation I've seen where guests got stuck near a ride was when they were repeatedly switching the entrance they were heading for (heading for an elevator).

**Comment by IntelOrca** [comment] 2016-05-09 17:07
@jensj12 ok, you can add this issue to our ever growing list of AI bugs.

**Comment by Liampie** [comment] 2016-09-26 11:25
I was invited to post a savegame where this is happening. The sitation has improved a little bit since some peeps will actually reach the queue entrance, but there is still a massive peep jam near the entrance hut. I suppose it depends on where in the park they start heading for the ride; from some directions they'll head for the queue, in others they'll head for the entrance hut. I don't know. Here's the savegame, with all scenery and things stripped because I don't like to release unfinished parks. Hopefully this will help solve the AI issues!
[Mysterious Peep Jam.zip](https://github.com/OpenRCT2/OpenRCT2/files/492946/Mysterious.Peep.Jam.zip)

**Comment by IntelOrca** [comment] 2016-09-28 10:39
@Liampie the current logic as follows:

1. Guest decides to head for a particular ride.
2. Guest chooses the closest entrance position to them
3. Guest heads for the queue for that entrance

There are several strategies in how a guest chooses a ride, one is to choose the close ride to them - and that is based on station position. Are you suggesting that changes to be based on queue end position?

**Comment by Liampie** [comment] 2016-09-28 19:18
That logic seems clear, but not reflected by the peeps in my park. Otherwise, why would they get stuck?

Aside from the problem in my park, queue end position seems more relevant and practical than station position, anyway. That's also how real people would behave.

**Comment by duncanspumpkin** [comment] 2016-09-28 19:23
It is much more expensive to get the queue end that's why it uses the entrance location when deciding the ride

**Comment by zaxcav** [comment] 2016-09-29 09:39
I'm currently working on further pathfinding improvements. I loaded the savegame up in my current development build and all the peeps get unclogged and find their way to the ride queue without problem.
So, hooray!

I'm done with the functional changes to the pathfinding (and it's working better than ever), but I want to do some performance optimisation before I submit a PR.

Incidently, the goal given to the pathfinding **is** the station entrance location, not the queue end.  A **very good reason** for peeps to head for the station entrance location is so that editing the queue won't mess up peeps already on their way to the ride.  If the ride queue gets changed the pathfinding adjusts dynamically to match, rather than directing the peep to a location that no longer has the queue end on it. There **is** potential for queues that end far, far, far away from the entrance station to defeat the pathfinding,  so the best advice is to end the ride queue close to the station entrance if you want fool proof pathfinding.

**Comment by Liampie** [comment] 2016-09-29 13:41
I can definitely see your reasoning there. But why is it more important to avoid peeps heading to tiles that have no queue entrance, in the extremely rare case of your queue being edited, than to avoid peeps heading for a point they will never ever reach and therefore breaking the park?

By the way, is it correct that your pathfinding improvements are not yet included in the latest development build? There are no changes noticable yet. Only way to dissolve the peep jam is to go back in the original game and staying there.

**Comment by zaxcav** [comment] 2016-09-29 19:01
What I said previously was based on observing what actually happens when running the program.
I've just taken a look at the applicable code though and there **is** a call to get the location of the queue end.
That call must be failing (in which case the station entry location is used).  Someone will need to look into this - possibly me if no one beats me to it.

The improvements I am doing at the moment are not in the development builds yet.  As I said, I want to do some optimisation first (and hopefully get back the performance that was lost), then I'll submit a pull request for others to review the changes.  When the core developers give their approval, the changes will get merged into the development builds. Have patience.

**Closed** 2016-09-30 05:43 UTC
Labels: AI bug, investigate
