### ISSUE TITLE
Can't hire new staff

### ISSUE THREAD

**Issue by AnnaSaysHi** [OpenRCT2/OpenRCT2#5560] opened 2017-06-06 20:34 UTC
**OS:** [MacOS Sierra]
**Version:** [0.0.8]
**Commit/Build:** [1e9f979]

Whenever I try to hire a staff member, a box pops up centered on an existing guest. If I then try to move the "staff member", I get an error saying "Can't hire new staff". This occurs consistently and is extremely obstructive to starting scenarios.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start a scenario from scratch or load a savegame.
2. Go to the Staff tab and attempt to hire a staff member of any kind - Handyman, Entertainer, Mechanic, Security guard.

**Comment by janisozaur** [comment] 2017-06-06 20:40
Duplicate of #5558

**Closed by janisozaur** 2017-06-06 20:40 UTC
