### ISSUE TITLE
Bobsled vehicle configuration is bugged

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#5539] opened 2017-06-02 18:20 UTC
I'm pretty sure this is a duplicate but i didn't find anything when searching.
![openrct2_2017-06-02_20-16-11](https://cloud.githubusercontent.com/assets/2000703/26738981/6b8954b0-47d0-11e7-8d3f-20031d35a4dd.png)

The coaster on the right side has only the wrong option in the dropdown box. Switching it will most likely cause the setting to be irreversible.

Version: OpenRCT2-0.0.8-develop- e7eb5f7 -windows-x64

**Comment by Gymnasiast** [comment] 2017-06-03 11:11
Cannot reproduce. Please upload your save.

**Comment by Patrik356b** [comment] 2017-06-03 15:06
[Cleveland's Luna Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/1049664/Cleveland.s.Luna.Park.zip)
Scenario comes from RCT2 UCES

**Comment by Patrik356b** [comment] 2017-06-06 10:12
If #4044 is implemented, this issue would expire automatically.

**Comment by Gymnasiast** [comment] 2017-06-06 10:19
Sort of. It wouldn't solve the underlying issue.

**Comment by Patrik356b** [comment] 2017-06-06 11:37
true, but i haven't observed an issue like that in a very long time. if memory serves me right, the first remotely similar issue was with the wooden roller coaster

**Comment by Gymnasiast** [comment] 2017-06-06 15:42
To check: you have 'Sort rides by track type' on, right?

**Comment by Patrik356b** [comment] 2017-06-07 01:06
I do

**Comment by Gymnasiast** [comment] 2018-01-02 15:58
This is a research issue. Opening and closing the inventions list, or turning on "ignore research status" makes it show up.

This is quite annoying as research is annoyingly complex.

**Comment by Gymnasiast** [comment] 2019-08-24 15:52
I have just loaded it this scenario up again. In this scenario, the regular bobsleigh trains are not invented yet, so it's unsurprising they're not in the box. If you let research do its thing, they will eventually be invented.

Apart from bugs, the only way to wind up in this situation is to use a cheat. Since the ride type is eventually invented, I'm going to chalk this up as "expected behaviour".

**Closed by Gymnasiast** 2019-08-24 15:52 UTC
Labels: broken save, investigate
