### ISSUE TITLE
BACKTRACE 2141cc

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8167] opened 2018-10-27 10:51 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/2141ccb0d8fdbc9d44d4217f8f7d746221448ee29bbf062ff47ddce3b33aea1a?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Oct 27 2018 10:51:18)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>window_close -> window_text_input_mouseup -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2018-11-02 22:19
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8164

**Closed by janisozaur** 2018-11-02 22:19 UTC
Labels: backtrace.io, crash
