### ISSUE TITLE
Building a vertical loop (left) or (right) on a mini roller coaster crashes the game.

### ISSUE THREAD

**Issue by kuanjiaqing** [OpenRCT2/OpenRCT2#3597] opened 2016-05-14 11:57 UTC
**OS:** Windows 8.1 x64
**Version:**  0.0.5
**Commit:** f62932a

Building a vertical loop (left) or (right) on a mini roller coaster crashes the game. In both Roller Coaster Designer and Scenarios this happens.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Dump file**
(I can't upload zip files)
[ca1267b2-55b1-4c8c-b619-270ed0036f25.zip.txt](https://github.com/OpenRCT2/OpenRCT2/files/264499/ca1267b2-55b1-4c8c-b619-270ed0036f25.zip.txt)

**Screenshots / Video:**
![capture](https://cloud.githubusercontent.com/assets/15967648/15268320/38012d26-1a0d-11e6-93ef-3d442db8fdc9.PNG)

**Comment by Broxzier** [comment] 2016-05-14 12:00
Very related to https://github.com/OpenRCT2/OpenRCT2/issues/3564

**Comment by Gymnasiast** [comment] 2016-05-17 07:36
Duplicate of #3564.

**Closed** 2016-05-17 07:38 UTC
Labels: duplicate
