### ISSUE TITLE
 Custom Campaigns/Custom Scenario Groups

### ISSUE THREAD

**Issue by Zygoat23** [OpenRCT2/OpenRCT2#13617] opened 2020-12-20 23:58 UTC
The ability to organize custom scenarios into their own campaigns or groups would be a welcome addition for those who like playing custom scenarios. This would function like the official groups (RCT1/LL/CF etc.), allowing custom scenario creators to make campaigns with intended scenario orders based on difficulty, and could include progressive unlocking of the custom scenarios for people who use that setting. It would help keep things organized rather than having a cluster of custom scenarios with no rhyme or reason to their location and order.

**Comment by Gymnasiast** [comment] 2020-12-21 12:59
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/5235.

**Closed by Gymnasiast** 2020-12-21 12:59 UTC
