### ISSUE TITLE
headless server is not able to connect if it is paused

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#14668] opened 2021-05-15 14:38 UTC
**OS:** Windows 10(client) & Ubuntu 20.04 (server)
**Version:** 0.3.3
**Commit/Build:** 9fe9e67

When open a headless server with ``pause_server_if_no_clients = true``, the server is not listed on the master server and not be able to connect.

An according to _Carli_ in Discord:
> And shortly after I pause the game on the server by executing ``context.executeAction("pausetoggle", {})`` my client disconnects with a "no data" error.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Set ``pause_server_if_no_clients = true`` in config.ini
2. Open a headless server

**Comment by Broxzier** [comment] 2021-05-15 14:45
This is a regression from #14596, though it's not clear to me how its changes cause this bug exactly. Any builds from before that PR was merged did not have this issue.

**Comment by Gymnasiast** [comment] 2021-05-15 14:51
@ZehMatt

**Comment by ZehMatt** [comment] 2021-05-15 20:44
I tested this and I can't reproduce it, I always end up being registered on the master server.

**Comment by ZehMatt** [comment] 2021-05-15 20:51
```
openrct2 host parks/park2.sv6 --headless
Listening for clients on *:11753
Registering server on master server
Server successfully registered on master server
openrct2 $                                             
```` 
for this configuration:
```
pause_server_if_no_clients = true
```

**Comment by kscheel** [comment] 2021-05-15 21:09
The behaviour is now different for me too after pulling the latest docker container. It seems ' pause_server_if_no_clients = true' is now ignored. The ticks keep going although no client is connected:

```
openrct2 $ date.ticksElapsed
2328908
openrct2 $ date.ticksElapsed
2328991
openrct2 $ date.ticksElapsed
2329035
``` 

But toggling pause on the server still causes me to get disconnected with the "no data" error. And the same error appears when I try to reconnect unless I toggle pause again by calling `context.executeAction("pausetoggle", {})`

**Comment by Gymnasiast** [comment] 2021-05-16 08:15
There is a possible fix pending in https://github.com/OpenRCT2/OpenRCT2/pull/14673 . Would you all be able to test it?

**Closed** 2021-05-16 11:14 UTC
Labels: bug, multiplayer, regression

**Comment by kscheel** [comment] 2021-05-16 20:08
> There is a possible fix pending in #14673 . Would you all be able to test it?
Yes, I'll be glad to test this. It seems the new development build with the fix isn't available yet?

About my earlier comment:
> It seems pause_server_if_no_clients = true is now ignored. The ticks keep going although no client is connected:
that was wrong, sorry about the confusion, I simply had a typo and wrote "ture" instead of "true" in my config.ini 🤦‍♂️

**Comment by telk5093** [comment] 2021-05-17 16:52
It is nicely fixed 👍

**Comment by Gymnasiast** [comment] 2021-05-18 08:16
@kscheel It should be in `develop` by now. Could you check if this solves it for you?

**Comment by kscheel** [comment] 2021-05-18 20:51
yes, pausing works just fine again, thanks for the fix :)

btw, how do the develop builds work? Is a release created automagically once a day containing the new commits to the develop branch (if there were any commits)?

Cheers :)

**Comment by Broxzier** [comment] 2021-05-18 21:14
@kscheel New 'develop' builds are automatically made for any new commit made to the develop branch. Releases don't happen automatically. Every so often when the develop branch seems stable, we hold off to merging anything big or what might introduce new bugs to make sure it remains stable, then manually create a release.
