### ISSUE TITLE
Crasf after finishing Fungus Woods

### ISSUE THREAD

**Issue by Zyngi** [OpenRCT2/OpenRCT2#4690] opened 2016-10-23 18:40 UTC
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 2bf4ded

- [ ] Reproducible in RCT2 (vanilla)?
Don't know.

- [x] Multiplayer?
No.

**Steps to reproduce:**
1. Play Fungus Woods
2. Finish map with expected result
Game crashes after several seconds (probably one day later after "Contragulations" window showed up.

**Dump file**
[save.zip](https://github.com/OpenRCT2/OpenRCT2/files/546554/save.zip)

**Screenshots / Video:**
http://i.imgur.com/P2UyCiv.jpg

**Save game:**
In save.zip

**Comment by IntelOrca** [comment] 2016-10-23 19:05
I think this is caused by the sprite limit exceeding and steam particles not handling that. Its been fixed already in 82b18ddaf371fe30f648be7bedf81afa56ebffa9, try updating to latest build.

**Comment by IntelOrca** [comment] 2016-10-23 19:05
Duplicate of #4644

**Closed by IntelOrca** 2016-10-23 19:05 UTC
Labels: duplicate
