### ISSUE TITLE
BACKTRACE cd4baf

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8306] opened 2018-11-27 21:46 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/cd4baf7c3fee1cca2adb6780b0ae4d604d1f02e80fcabc141029d7e21720c684?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Tue Nov 27 2018 21:46:13)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> d0108b3: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ride_get_broken_vehicle -> rct_peep::UpdateFixing -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 21:54
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8474

**Closed by janisozaur** 2019-02-02 21:54 UTC
Labels: backtrace.io, crash
