### ISSUE TITLE
Letting the game run on the title screen for a long time causes a crash

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1656] opened 2015-07-22 01:15 UTC
![screenshot 1](https://cloud.githubusercontent.com/assets/3945538/8815904/914bfa56-2fed-11e5-9e9f-15ccac6ea230.png)

Console has no errors.

I ran it for a good 10 minutes, Hardware Rendering and Uncapped FPS enabled.

**Comment by duncanspumpkin** [comment] 2015-07-22 11:32
Can you try get this to reproduce a bit quicker. I'd prefer not to run the game for tens of minutes in the hope of reproducing it. Does it happen if you load that displayed save and run it for 10 minutes?

**Comment by zsilencer** [comment] 2015-07-22 17:13
this save file has the same crash almost immediately
http://wikisend.com/download/367658/Cedar Point's Raptor.SV6

**Comment by IntelOrca** [comment] 2015-07-22 19:32
@zsilencer I am unable to load that saved game due to a missing object.
But these crashes may have been fixed by 43b657730ecdc5524a9e8683c3cbc7612cd86fc5. Do they still happen?

**Comment by PFCKrutonium** [comment] 2015-07-22 19:32
I'll check on the title screen.

**Comment by PFCKrutonium** [comment] 2015-07-22 19:38
Crash seems to be corrected. Also, I overestimated the time, closer to 5 minutes.

**Comment by zsilencer** [comment] 2015-07-22 21:53
yeah looks like it is fixed now

**Closed** 2015-07-22 23:47 UTC
