### ISSUE TITLE
Test vertical coaster crashes game.

### ISSUE THREAD

**Issue by chrisolver** [OpenRCT2/OpenRCT2#5147] opened 2017-01-31 12:29 UTC
Windows 10
0.0.7.0 build 94d38b9
Multiplayer or Single Player
[autosave_2017-01-31_23-17-53.zip](https://github.com/OpenRCT2/OpenRCT2/files/741918/autosave_2017-01-31_23-17-53.zip)

**Steps to reproduce:**
1. Select Green Vertical Coaster
2. Click Test
3. Local game crashes or will also crash server

Saved Game attached.

**Comment by jensj12** [comment] 2017-07-02 16:33
I can't test the save because of missing objects. Can you check if it's a duplicate of #3846?

**Comment by Nubbie** [comment] 2017-07-15 09:09
@chrisolver Can you re-upload with the 'export objects' checked in settings?

**Comment by Gymnasiast** [comment] 2018-01-02 15:47
Considering the OP has not answered, I'll just assume this was a duplicate of #3846 and thus solved.

**Closed by Gymnasiast** 2018-01-02 15:47 UTC
Labels: crash, investigate
