### ISSUE TITLE
No Ambient Park/Guest Noise; Only Ride Songs

### ISSUE THREAD

**Issue by ataylor9552** [OpenRCT2/OpenRCT2#22052] opened 2024-05-17 20:30 UTC
### Operating System

Windows 10 Home x64; Version: 10.0.19045 Build 19045

### OpenRCT2 build

OpenRCT2, v0.4.11-94-g340a683 (340a683 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

I've been playing OpenRCT2 for about a month now. Ever since I started, the ambient park noise (guest excitement on a rollercoaster, haptic feedback from object placement, etc.) has been accompanied by a noise I can only describe as "tinny-sounding microwaved popcorn." Despite the ride song option being ticked and playing, this popcorn noise often overpowers all other sound effects. 

However, starting today, the *only* sound effect emitting from the game is ride music. There are no ambient guest/ride SFX, tinny popcorn popping, nor haptic feedback--just the "Galaxy" ride song I have set to play for several rides. 

Troubleshooting attempts to mitigate SFX loss: 
- Saved the current park, opened a different park save file, then returned to aforementioned park(no change)
- Exited the OpenRCT2 game entirely, then returned (no change) 
- Ticked/unticked the mute button (the ear icon) 

### Steps to reproduce

I do not have a screenshot to show the SFX is not working properly. Thank you. 

I am utilizing the OpenRCT2 launcher, if that makes any difference.

**Comment by cheweytoo** [comment] 2024-05-17 20:40
Duplicate of #22051 ;-)

**Comment by ataylor9552** [comment] 2024-05-17 21:16
My apologies for the duplicate ticket! The user user must have posted
theirs shortly after I verified there weren't any similar tickets open.
Please forgive me, as I'm relatively new to OpenRCT2 and GitHub.

Please let me know if there is any additional information I can provide to
facilitate this process, or if you prefer, I can delete my redundant
ticket.

Thank you so much for your time!

**Comment by AaronVanGeffen** [comment] 2024-05-17 21:19
Thanks for reporting the issue. It's a bit late at night for me, but I intend to get this sorted out quickly, tomorrow.

**Closed** 2024-05-17 21:24 UTC
Labels: duplicate

**Comment by cheweytoo** [comment] 2024-05-17 21:26
@ataylor9552: No apology required. I almost epxected the same to happen to my issue entry, since this is so immediately obvious that it couldn't go unnoticed.

**Comment by ataylor9552** [comment] 2024-05-18 21:15
> Thanks for reporting the issue. It's a bit late at night for me, but I intend to get this sorted out quickly, tomorrow.

I'm new to GitHub, so apologies if I'm doing this incorrectly. I just wanted to let you know that I appreciate you fixing the issue. It's working fine now. Thank you so much and have a great day 😊
