### ISSUE TITLE
Request: Sticky window

### ISSUE THREAD

**Issue by DavydeVries** [OpenRCT2/OpenRCT2#3388] opened 2016-04-22 13:59 UTC
In RCT2 you have windows with an [x] in the right corner. You can close all windows with the shortcut `Shift` + `backspace`. I use that a lot, but some windows I like to keep open, like finance window or visitors/guest thoughts window. But these will also close.

In OpenTTD (Transport Tycoon Deluxe) you have the option to make it sticky, so if you use the shortcut to clear your screen of all those useless windows. The sticky screens stay.
<img width="365" alt="schermafbeelding 2016-04-22 om 15 55 55" src="https://cloud.githubusercontent.com/assets/7860305/14743660/f5eec87e-08a2-11e6-9da2-3c5ddff196f8.png">

My request is to make a sticky button by the [x] button (or the opposite side). So you can easily close all other windows with the shortcut.

**Comment by IntelOrca** [comment] 2016-04-22 14:29
Duplicate of #2981

**Closed** 2016-04-22 14:29 UTC
Labels: duplicate, feature
