### ISSUE TITLE
back of stall shown through vertical terrain

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#18787] opened 2022-12-08 23:22 UTC
### Operating System

Ubuntu Linux 20.04.5

### OpenRCT2 build

9226448 develop, AppImage

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Introduced by commit 94e8e9e (it was arguably worse before) – but now, the back of a stall is visible through vertical terrain as well:

![stall_in_ice](https://user-images.githubusercontent.com/29800630/206587255-e11abc4f-513c-4a6a-8058-1f011768559b.png)

### Steps to reproduce

Build underground stall with its back touching vertical terrain

**Comment by ocalhoun6** [comment] 2022-12-09 00:22
Well the employees working in there have got to be able to access the stall *somehow*, now don't they?

**Comment by cheweytoo** [comment] 2022-12-09 00:26
> Well the employees working in there have got to be able to access the stall _somehow_, now don't they?

Excellent point. I hereby propose the introduction of implicit utilidors.

**Comment by rik-smeets** [comment] 2022-12-09 14:03
> Well the employees working in there have got to be able to access the stall _somehow_, now don't they?

That's exactly the joke I wanted to make when I saw @Gymnasiast assigned this to me 😅.

The root cause of this is that tunnels are used to ensure that underground shops are visible. They currently always show on both sides.

**Comment by cheweytoo** [comment] 2022-12-09 14:28
Is it maybe possible to instead re-use another tunnel type that doesn't go all the way through?

The Giga Coaster "steep track" tunnel e.g. would be one-sided. And the "low version" of that tunnel (see issue #18389 – sort of) would be exactly the same size as the currently used ride entrance tunnel (on the right):

![one-sided_tunnel](https://user-images.githubusercontent.com/29800630/206723750-b6c6118e-ed2d-47e7-a671-d64080c19cfb.png)

**Comment by Gymnasiast** [comment] 2022-12-09 18:10
I have a fix.

**Closed** 2022-12-09 18:59 UTC
Labels: bug
