### ISSUE TITLE
Unable to build upwards helix on the Junior Coaster

### ISSUE THREAD

**Issue by StrangeAnomoly** [OpenRCT2/OpenRCT2#16948] opened 2022-04-08 20:12 UTC
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (5e82e90 on develop) provided by GitHub

### Describe the issue

You cannot build an upwards helix on the Junior Coaster. You can build a downwards helix but not an upwards one.

### Steps to reproduce

1. Build a Junior coaster
2. Attempt to build a downward helix
3. The game doesn't allow for the option.

### Attachments

![Razor Rocks 2022-04-08 21-06-06](https://user-images.githubusercontent.com/41911850/162518890-aaf56ed3-c221-4fc9-8d1a-9c4d62816aa4.png)

**Comment by Gymnasiast** [comment] 2022-04-08 22:16
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/16922.

**Closed by Gymnasiast** 2022-04-08 22:16 UTC
Labels: bug
