### ISSUE TITLE
RCT1 Crumbly woods missing water tile

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#17184] opened 2022-05-08 22:48 UTC
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2, v0.4.0

### Describe the issue

There is a missing water tile in crumbly woods near the end of the wooden coaster's chain lift.
It also exists in RCT1 itself, i've included screenshots of the spot in both OpenRCT2 and RCT1 Deluxe.
OpenRCT2 screenshot has the map window in it to assist with locating it.

### Steps to reproduce

1. Open crumbly woods (use the original rct1 scenario, not a remake)
2. Go to the area in the screenshots
3. There is a missing tile of water

### Attachments

![DeepinScreenshot_openrct2_20220508184011](https://user-images.githubusercontent.com/42477864/167318871-aac938a3-5a8f-4652-a525-15d106c70b73.png)
![DeepinScreenshot_explorer exe_20220508184029](https://user-images.githubusercontent.com/42477864/167318869-08c33b71-06db-47e7-ac2f-30691233b4bb.png)

**Comment by ZeeMajora** [comment] 2022-05-09 03:08
The missing water tile is also present in RCT Classic's (.sea) version of crumbly woods.
![DeepinScreenshot_openrct2_20220508230811](https://user-images.githubusercontent.com/42477864/167333931-b717635a-7605-451a-9863-ec2c446df1cd.png)

**Comment by sjoerddebruin** [comment] 2024-09-30 18:15
This is still happening despite https://github.com/OpenRCT2/OpenRCT2/blob/develop/data/scenario_patches/c67e91e.parkpatch existing.

**Comment by tupaschoal** [comment] 2024-10-01 00:28
@sjoerddebruin it works for me both on the `.sc4` and `.sea` file for Crumbly Woods on develop. Are you trying `develop` or the latest reelase?

Weirdly enough that patch was in for `v0.4.14`, but it seems like it was not shipped

**Comment by sjoerddebruin** [comment] 2024-10-01 08:22
> @sjoerddebruin it works for me both on the `.sc4` and `.sea` file for Crumbly Woods on develop. Are you trying `develop` or the latest reelase?
> 
> Weirdly enough that patch was in for `v0.4.14`, but it seems like it was not shipped

I was on develop, could it be some cache or is there something else I can supply to help? I'm using GOG versions for both of the games.

**Comment by tupaschoal** [comment] 2024-10-01 09:17
Can you check whether the `/data/scenario_patches/c67e91e.parkpatch` exists on your build?

Alternatively, the bottom of the window should show the path to the scenario file being used:
![image](https://github.com/user-attachments/assets/a1586efe-1100-4e6d-baa5-feda95bb7d0d)

Can you take it and generate the SHA hash manually and post here?
On Windows Powershell: `Get-FileHash PATH_TO_SCENARIO`
On Linux: `sha256sum PATH_TO_SCENARIO`

**Comment by sjoerddebruin** [comment] 2024-10-01 17:52
Both scenario_patches and asset_packs are missing on Mac builds, I'll open a new issue. This one can be closed as the fix is working as intended.

**Comment by tupaschoal** [comment] 2024-10-01 19:55
Nice find, thanks!

**Closed** 2024-10-01 19:55 UTC
Labels: data file bug, rct1
