### ISSUE TITLE
Single Random Unwanted Per User Transparency by Default

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#22800] opened 2024-09-20 03:35 UTC
### Operating System

Windows 11 Pro Insider Preview Canary

### OpenRCT2 build

OpenRCT2, v0.4.14-62-geb664a2 (eb664a2 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Depending on whom you ask, a single transparency option is enabled by default when parks are loaded. This can be annoying when you want to view someone else's park, and you realize that a transparency option is stubbornly staying enabled every time you load the game.

### Steps to reproduce

Open the game and load a park, a certain (per user) transparency will be enabled by default every time you restart the game and load a park. (for me it is vegetation)

**Comment by telk5093** [comment] 2024-09-20 03:50
Sounds like duplicate of #22729

**Closed** 2024-09-20 03:53 UTC
Labels: bug
