### ISSUE TITLE
Rides hanging and game crashes

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#5184] opened 2017-02-06 21:22 UTC
**OS:** Arch Linux
**Version:** 0.0.7
**Commit/Build:** 528843184c6caadcadf2caa13896624878fb9eeb

Load the attached save file. I did not modify it outside the game.

You'll notice that Monorail 1 is stuck, Train 2 is waiting for passengers at Station 2. A few 'months' before the save that also happened to Giga Coaster 1.

Also, as soon as the game advances to **April 28, Year 11** it completely freezes (!). This also happens in vanilla RCT2.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load the save file.
2. Observe the behavior.

**Save game:**
[A_Hill_Broken.zip](https://github.com/OpenRCT2/OpenRCT2/files/755870/A_Hill_Broken.zip)

**Comment by Nubbie** [comment] 2017-07-08 07:18
To temporarily fix this, use the cheat "Remove guests"

---------

Crashed at 9 may, year 11

Call stack;
```
>	openrct2.dll!ride_queue_insert_guest_at_front(rct_ride * ride=0x00007ff8bd396b60, int stationIndex=0, rct_peep * peep=0x00007ff8bceee570) Line 387	C
 	openrct2.dll!peep_update_ride_sub_state_2(rct_peep * peep=0x00007ff8bceee570) Line 3052	C
 	openrct2.dll!peep_update_all(...) Line 570	C
 	openrct2.dll!game_logic_update(...) Line 412	C
 	openrct2.dll!game_update(...) Line 355	C
 	openrct2.dll!rct2_update(...) Line 441	C
 	openrct2.dll!OpenRCT2::Context::RunVariableFrame() Line 422	C++
 	openrct2.dll!OpenRCT2::Context::RunGameLoop() Line 360	C++
 	openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int argc=54003488, char * * argv=0x000000000a100800) Line 136	C++
 	openrct2.dll!NormalisedMain(int argc=1, char * * argv=0x0000018d03328490) Line 65	C++
 	openrct2.dll!LaunchOpenRCT2(int argc, wchar_t * * argvW) Line 55	C++
 	[External Code]	
```

Autos;
```
+		window_ride_customer_widgets	0x00007ff8bcd8e2a0 {{type=1 '\x1' colour=0 '\0' left=0 ...}, {type=20 '\x14' colour=0 '\0' left=1 ...}, ...}	rct_widget[18]
```

Locals;
```
+		peep	openrct2.dll!0x00007ff8bceee570 {sprite_identifier=1 '\x1' var_01=0 '\0' next_in_quadrant=65535 ...}	rct_peep *
+		ride	openrct2.dll!0x00007ff8bd396b60 {type=65 'A' subtype=77 'M' pad_002=0 ...}	rct_ride *
		stationIndex	0	int
```

**Comment by rwjuk** [comment] 2017-07-28 16:13
I can't reproduce the hang on the latest build, and double-closing & reopening the Monorail gets it back to normal. It's possible that whatever caused this has been fixed.

**Comment by IntelOrca** [comment] 2017-07-28 16:41
Anything to do with queue that can't be reproduced has probably been fixed now.

**Closed** 2017-07-28 16:41 UTC
Labels: investigate
