### ISSUE TITLE
RCT1 theme should have the old message bar function 

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#3604] opened 2016-05-15 02:21 UTC
The RCT1 theme should bring back the old behavior of the message bar of not disappearing and just being blank when it has nothing to display, also allow custom themes to enable the feature as well.

**Comment by Ziscor** [comment] 2016-05-15 04:59
I'd like to point out that this will also hide the issue that rain does not cover the entire visible screen. From the bottom at least.

**Comment by IntelOrca** [comment] 2016-05-15 09:26
Duplicate of #1423

**Closed** 2016-05-15 13:48 UTC
Labels: duplicate
