### ISSUE TITLE
Some Track Designs Cannot be Built

### ISSUE THREAD

**Issue by CsTDesign** [OpenRCT2/OpenRCT2#16736] opened 2022-02-28 21:15 UTC
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (730364d on develop) provided by GitHub

### Describe the issue

Some pre-built coasters cannot be built, even when there is enough space available to build.

![image](https://user-images.githubusercontent.com/100553477/156059309-6440243d-89c2-45df-888d-df9e53b79b37.png)

### Area(s) with issue?

Building the game

### Steps to reproduce

1.  https://user-images.githubusercontent.com/100553477/156059309-6440243d-89c2-45df-888d-df9e53b79b37.png
2. 
3. 

### Attachments

https://user-images.githubusercontent.com/100553477/156059309-6440243d-89c2-45df-888d-df9e53b79b37.png

**Comment by James103** [comment] 2022-02-28 21:26
Can you please try reproducing this in the [latest develop version](https://openrct2.org/downloads/develop/latest)? The commit you entered is from January 16.

**Comment by duncanspumpkin** [comment] 2022-02-28 22:07
Most likely https://github.com/OpenRCT2/OpenRCT2/pull/16464 resolved this

**Comment by Broxzier** [comment] 2022-03-01 21:17
Closing this, since the standard "Deep Freeze" coaster track can be constructed without issue on the current latest develop 66b8f28.

**Closed by Broxzier** 2022-03-01 21:17 UTC
Labels: bug
