### ISSUE TITLE
Game fails to save and can't build custom tracks after playing for a while!

### ISSUE THREAD

**Issue by tylere661** [OpenRCT2/OpenRCT2#17673] opened 2022-08-02 09:06 UTC
### Operating System

Windows 10 64 bit.

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4) provided by GitHub

### Describe the issue

After playing the game for a few hours, I can't save the game or build any custom rides.  I have to close the game and restart it to temporarily fix the problem.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Open any park.
2. Play the game for a few hours.
3. Try building a custom ride or save the park.

**Comment by janisozaur** [comment] 2022-08-02 09:48
Duplicate of #17664 . Can you please use the build from #17665 for a while to provide us with debug info we need?

**Closed by janisozaur** 2022-08-02 09:48 UTC
Labels: bug

**Comment by tylere661** [comment] 2022-08-02 09:50
Sure!

Sent via the Samsung Galaxy S10e, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tylere661** [comment] 2022-08-03 06:27
I don't see the build download from the conversation!
________________________________

**Comment by James103** [comment] 2022-08-03 06:29
Try one of the build artifacts from https://github.com/OpenRCT2/OpenRCT2/actions/runs/2780372667.

**Comment by Andatho** [comment] 2022-08-28 08:09
Today, i have the same problem (playing with Develop-7136b08) - Issue #17664 
I was not able to report by the dialog cause it was not possible to leave the game.
I have installed the latest development build now and will report if the error occurs again.
![O-RCT2-Error](https://user-images.githubusercontent.com/106301901/187064416-37d37e84-11de-4ef6-9aff-ad72e34bd5e6.png)
