### ISSUE TITLE
When saving a track it replaces the number with ?

### ISSUE THREAD

**Issue by RapleAQN** [OpenRCT2/OpenRCT2#3141] opened 2016-03-16 16:17 UTC
**OS: Win 7 64Bit** 
**Version: 0.0.4** 
**Commit: 50b5214** 

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Select a ride
2. Save it

**Screenshots / Video:**
http://i.imgur.com/sIzRmpI.png

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by IntelOrca** [comment] 2016-03-16 17:46
Duplicate of #3112

**Closed by IntelOrca** 2016-03-16 17:46 UTC
Labels: duplicate
