### ISSUE TITLE
Unable to rotate Maze

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#3351] opened 2016-04-19 19:45 UTC
**OS: Linux** 
**Version: 0.0.5** 
**Commit: 423844c** 

Explanation of the issue...

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Select Maze Pre-Built
2. Try to Rotate

**Comment by janisozaur** [comment] 2016-04-19 19:48
Dupe of https://github.com/OpenRCT2/OpenRCT2/issues/3321

**Closed by janisozaur** 2016-04-19 19:48 UTC
