### ISSUE TITLE
BACKTRACE fb66a2

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8240] opened 2018-11-07 23:22 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/fb66a26283ed3e8ccff8c687ba40f1a9b048f604bdc539f5233f5132a8ec2006?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Nov 07 2018 23:21:49)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 223ae74: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>utf8_get_next -> WindowManager::OpenWindow -> context_open_window -> window_server_list_mouseup -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> OpenRCT2::TitleScreen::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2018-11-08 17:14
```
dump_path: /var/coronerd//openrct2/openrct2/_objects/0000/tx.00A7.dmp outfile: -
Classifier: invalid-read
Crash info:
	Application: openrct2.exe
	Crashed YES
	reason: EXCEPTION_ACCESS_VIOLATION_READ
	address: 0
Memory Regions:
Sysinfo:
	arch: x86 GenuineIntel family 6 model 55 stepping 8
	cpu_count: 4
	os: Windows NT windows 10.0.17134 
Modules:
	0x340000 - 0x369000	openrct2.exe 
	0x62320000 - 0x63180000	openrct2.dll 
	0x63180000 - 0x63256000	WinTypes.dll 6.2.17134.112
	0x63260000 - 0x634bd000	CoreUIComponents.dll 6.2.17134.112
	0x634c0000 - 0x6354b000	CoreMessaging.dll 6.2.17134.345
	0x64060000 - 0x6415b000	AudioSes.dll 6.2.17134.137
	0x64160000 - 0x641ee000	mscms.dll 6.2.17134.1
	0x65df0000 - 0x65e2e000	icm32.dll 6.2.17134.1
	0x65e30000 - 0x65e3c000	ColorAdapterClient.dll 6.2.17134.1
	0x65e40000 - 0x65e9c000	MMDevAPI.dll 6.2.17134.1
	0x65ea0000 - 0x65f1d000	TextInputFramework.dll 6.2.17134.191
	0x65f30000 - 0x65f38000	IconCodecService.dll 6.2.17134.1
	0x65f40000 - 0x65f48000	avrt.dll 6.2.17134.1
	0x664e0000 - 0x664ea000	secur32.dll 6.2.17134.1
	0x682b0000 - 0x68421000	WindowsCodecs.dll 6.2.17134.345
	0x6e450000 - 0x6e46b000	ncryptsslp.dll 6.2.17134.137
	0x6e470000 - 0x6e49d000	ntasn1.dll 6.2.17134.1
	0x6e4a0000 - 0x6e4bf000	ncrypt.dll 6.2.17134.1
	0x6e4c0000 - 0x6e4d0000	mskeyprotect.dll 6.2.17134.1
	0x6e4d0000 - 0x6e53a000	schannel.dll 6.2.17134.319
	0x6e540000 - 0x6e58f000	FWPUCLNT.DLL 6.2.17134.1
	0x6e590000 - 0x6e598000	rasadhlp.dll 6.2.17134.1
	0x6e6b0000 - 0x6e6d3000	WINMMBASE.dll 6.2.17134.1
	0x6e6e0000 - 0x6e704000	winmm.dll 6.2.17134.1
	0x6e720000 - 0x6e7bd000	apphelp.dll 6.2.17134.1
	0x6e7c0000 - 0x6e940000	propsys.dll 7.0.17134.112
	0x6f200000 - 0x6f225000	dbgcore.dll 6.2.17134.1
	0x6f270000 - 0x6f293000	dwmapi.dll 6.2.17134.1
	0x6f450000 - 0x6f4cc000	uxtheme.dll 6.2.17134.1
	0x6f4d0000 - 0x6f8d5000	wininet.dll 11.0.17134.345
	0x6fcd0000 - 0x6fed4000	comctl32.dll 6.10.17134.345
	0x70000000 - 0x70029000	ntmarta.dll 6.2.17134.1
	0x70d30000 - 0x70d52000	devobj.dll 6.2.17134.1
	0x70ef0000 - 0x71072000	dbghelp.dll 6.2.17134.1
	0x710a0000 - 0x7112e000	dnsapi.dll 6.2.17134.165
	0x71130000 - 0x71186000	mswsock.dll 6.2.17134.1
	0x71c80000 - 0x71caf000	rsaenh.dll 6.2.17134.254
	0x71cb0000 - 0x71cc3000	cryptsp.dll 6.2.17134.1
	0x73870000 - 0x73878000	version.dll 6.2.17134.1
	0x73c10000 - 0x73c31000	userenv.dll 6.2.17134.1
	0x73c60000 - 0x73c79000	bcrypt.dll 6.2.17134.112
	0x73d20000 - 0x73d50000	IPHLPAPI.DLL 6.2.17134.1
	0x73d50000 - 0x73d5a000	CRYPTBASE.dll 6.2.17134.1
	0x73d60000 - 0x73d80000	sspicli.dll 6.2.17134.1
	0x73d80000 - 0x73e08000	SHCore.dll 6.2.17134.112
	0x73e20000 - 0x73edf000	msvcrt.dll 7.0.17134.1
	0x73fc0000 - 0x73fd7000	win32u.dll 6.2.17134.1
	0x74170000 - 0x754ba000	shell32.dll 6.2.17134.320
	0x754c0000 - 0x75505000	shlwapi.dll 6.2.17134.1
	0x75940000 - 0x75998000	bcryptPrimitives.dll 6.2.17134.345
	0x759a0000 - 0x75a9c000	ole32.dll 6.2.17134.137
	0x75aa0000 - 0x75ae4000	sechost.dll 6.2.17134.319
	0x75af0000 - 0x75b16000	imm32.dll 6.2.17134.1
	0x75b20000 - 0x75ba3000	clbcatq.dll 2001.12.10941.16384
	0x75bb0000 - 0x75c70000	rpcrt4.dll 6.2.17134.112
	0x75c70000 - 0x75dd4000	gdi32full.dll 6.2.17134.345
	0x75de0000 - 0x75de8000	fltLib.dll 6.2.17134.1
	0x75df0000 - 0x75fd4000	KERNELBASE.dll 6.2.17134.319
	0x75fe0000 - 0x7605d000	msvcp_win.dll 6.2.17134.1
	0x76060000 - 0x76078000	profapi.dll 6.2.17134.1
	0x760e0000 - 0x761fe000	ucrtbase.dll 6.2.17134.319
	0x76200000 - 0x76267000	ws2_32.dll 6.2.17134.1
	0x76270000 - 0x762a9000	cfgmgr32.dll 6.2.17134.1
	0x762b0000 - 0x76328000	advapi32.dll 6.2.17134.319
	0x76330000 - 0x76352000	gdi32.dll 6.2.17134.285
	0x76360000 - 0x764f6000	crypt32.dll 6.2.17134.1
	0x76500000 - 0x76507000	nsi.dll 6.2.17134.1
	0x76510000 - 0x7651e000	msasn1.dll 6.2.17134.1
	0x76520000 - 0x76664000	msctf.dll 6.2.17134.319
	0x76670000 - 0x766b5000	powrprof.dll 6.2.17134.1
	0x76720000 - 0x76cd9000	windows.storage.dll 6.2.17134.345
	0x76ce0000 - 0x76d76000	oleaut32.dll 6.2.17134.48
	0x76d80000 - 0x76fdc000	combase.dll 6.2.17134.112
	0x76fe0000 - 0x76fef000	kernel.appcore.dll 6.2.17134.112
	0x77060000 - 0x77140000	kernel32.dll 6.2.17134.1
	0x77140000 - 0x77216000	comdlg32.dll 6.2.17134.1
	0x77220000 - 0x773ad000	user32.dll 6.2.17134.319
	0x774a0000 - 0x77630000	ntdll.dll 6.2.17134.254
Threads:
	thread-0 tid=8256 faulted
	[0] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!utf8_get_next(char const *,char const * *) [c:\projects\openrct2-ject9\src\openrct2\localisation\utf8.cpp : 19 + 0]
		ip=0x62404091 sp=0xf8f77c bp=0xf8f79c 
	[1] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!safe_strcpy(char *,char const *,unsigned int) [c:\projects\openrct2-ject9\src\openrct2\util\util.cpp : 398 + 0xd]
		ip=0x6243cd16 sp=0xf8f784 bp=0xf8f79c 
	[2] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!WindowManager::OpenWindow(unsigned char) [c:\projects\openrct2-ject9\src\openrct2-ui\windowmanager.cpp : 106 + 0x113]
		ip=0x6235998b sp=0xf8f7a4 bp=0xf8f7d4 
	[3] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!context_open_window(unsigned char) [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 1186 + 0x7]
		ip=0x623cc0b3 sp=0xf8f7dc bp=0xf8f808 
	[4] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!window_server_list_mouseup(rct_window *,short) [c:\projects\openrct2-ject9\src\openrct2-ui\windows\serverlist.cpp : 226 + 0x7]
		ip=0x623a470e sp=0xf8f810 bp=0xf8f820 
	[5] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!input_state_widget_pressed(int,int,int,short,rct_window *,rct_widget *) [c:\projects\openrct2-ject9\src\openrct2-ui\input\mouseinput.cpp : 1363 + 0x12]
		ip=0x6234c6fb sp=0xf8f828 bp=0xf8f858 
	[6] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!game_handle_input_mouse(int,int,int) [c:\projects\openrct2-ject9\src\openrct2-ui\input\mouseinput.cpp : 365 + 0xf]
		ip=0x6234b419 sp=0xf8f860 bp=0xf8f898 
	[7] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!game_handle_input() [c:\projects\openrct2-ject9\src\openrct2-ui\input\mouseinput.cpp : 118 + 0xb]
		ip=0x6234ab33 sp=0xf8f8a0 bp=0xf8f8e0 
	[8] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!OpenRCT2::TitleScreen::Update() [c:\projects\openrct2-ject9\src\openrct2\title\titlescreen.cpp : 185 + 0x53]
		ip=0x623f9f44 sp=0xf8f8e8 bp=0xf8f910 
	[9] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!OpenRCT2::Context::Update() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 932 + 0x8]
		ip=0x623caf08 sp=0xf8f918 bp=0xf8f9b0 
	[10] C:\Windows\System32\kernel32.dll!_SizeofResourceStub@8 + 0x20
		ip=0x77076490 sp=0xf8f91c bp=0xf8f9b0 
		guessed frame
	[11] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!OpenRCT2::Context::RunGameLoop() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 801 + 0xc7]
		ip=0x623caaba sp=0xf8f9b8 bp=0xf8f9d8 
	[12] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!OpenRCT2::Context::Launch() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 773 + 0x8]
		ip=0x623ca967 sp=0xf8f9e0 bp=0xf8fa40 
	[13] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int,char const * *) [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 213 + 0x7]
		ip=0x623c8bfa sp=0xf8fa48 bp=0xf8fa50 
	[14] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!NormalisedMain(int,char const * *) [c:\projects\openrct2-ject9\src\openrct2-ui\ui.cpp : 60 + 0x13]
		ip=0x62343da7 sp=0xf8fa58 bp=0xf8fac8 
	[15] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!LaunchOpenRCT2(int,wchar_t * *) [c:\projects\openrct2-ject9\src\openrct2-dll\openrct2-dll.cpp : 46 + 0x9]
		ip=0x623438c2 sp=0xf8fad0 bp=0xf8faec 
	[16] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.exe!wmain(int,wchar_t * *,wchar_t *) [c:\projects\openrct2-ject9\src\openrct2-win\openrct2-win.cpp : 27 + 0xc]
		ip=0x34100f sp=0xf8faf4 bp=0xf8fafc 
	[17] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.exe!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl : 288 + 0x1c]
		ip=0x3411d3 sp=0xf8fb04 bp=0xf8fb44 
	[18] C:\Windows\System32\kernel32.dll!@BaseThreadInitThunk@12 + 0x24
		ip=0x77078484 sp=0xf8fb4c bp=0xf8fb58 
	[19] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart + 0x2f
		ip=0x7750305a sp=0xf8fb60 bp=0xf8fba0 
	[20] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart@8 + 0x1b
		ip=0x7750302a sp=0xf8fba8 bp=0xf8fbb0 
	thread-1 tid=11764 
	[0] C:\Windows\System32\ntdll.dll!_ZwWaitForWorkViaWorkerFactory@20 + 0xc
		ip=0x7750bf1c sp=0x2f2f6b8 bp=0x2f2f870 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x296
		ip=0x774ecbb6 sp=0x2f2f6bc bp=0x2f2f870 
	[2] C:\Windows\System32\kernel32.dll!@BaseThreadInitThunk@12 + 0x24
		ip=0x77078484 sp=0x2f2f878 bp=0x2f2f884 
	[3] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart + 0x2f
		ip=0x7750305a sp=0x2f2f88c bp=0x2f2f8cc 
	[4] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart@8 + 0x1b
		ip=0x7750302a sp=0x2f2f8d4 bp=0x2f2f8dc 
	thread-2 tid=3492 
	[0] C:\Windows\System32\ntdll.dll!_ZwGetContextThread@8 + 0xc
		ip=0x7750b11c sp=0x3b0e58c bp=0x3b0e598 
	[1] C:\Windows\System32\ntdll.dll!RtlGetFullPathName_Ustr + 0x2bf
		ip=0x774e795f sp=0x3b0e6d4 bp=0x3b0e598 
	[2] C:\Windows\System32\ntdll.dll!RtlGetFullPathName_Ustr + 0x2d9
		ip=0x774e7979 sp=0x3b0e6e4 bp=0x2 
		guessed frame
	[3] C:\Windows\System32\ntdll.dll!_wcstombs + 0x70
		ip=0x77512580 sp=0x3b0e738 bp=0x2 
		guessed frame
	[4] C:\Windows\System32\ntdll.dll!LdrpResGetResourceDirectory + 0xb0
		ip=0x774f8700 sp=0x3b0e748 bp=0x3b0e8a8 
		guessed frame
	[5] C:\Windows\System32\dbgcore.dll!_memcpy + 0x4df3
		ip=0x6f222000 sp=0x3b0e8a0 bp=0x3b0eca4 
	thread-3 tid=10824 
	[0] C:\Windows\System32\ntdll.dll!_NtWaitForAlertByThreadId@8 + 0xc
		ip=0x7750beec sp=0x3c4fda4 bp=0x3c4fdec 
	[1] C:\Windows\System32\ntdll.dll!RtlSleepConditionVariableSRW + 0xe0
		ip=0x774fc0f0 sp=0x3c4fda8 bp=0x3c4fdec 
	[2] C:\Windows\System32\KERNELBASE.dll!_SleepConditionVariableSRW@16 + 0x23
		ip=0x75efe7b3 sp=0x3c4fdf4 bp=0x3c4fe10 
	[3] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!__crtSleepConditionVariableSRW(_RTL_CONDITION_VARIABLE *,_RTL_SRWLOCK *,unsigned long,unsigned long) [f:\dd\vctools\crt\crtw32\misc\winapisupp.cpp : 657 + 0x2]
		ip=0x62714649 sp=0x3c4fe18 bp=0x3c4fe2c 
	[4] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!Concurrency::details::stl_condition_variable_win7::wait_for(Concurrency::details::stl_critical_section_interface *,unsigned int) [f:\dd\vctools\crt\crtw32\stdcpp\thr\primitives.h : 216 + 0x15]
		ip=0x62880c00 sp=0x3c4fe34 bp=0x3c4fe44 
	[5] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!do_wait(_Cnd_internal_imp_t *,_Mtx_internal_imp_t *,xtime const *) [f:\dd\vctools\crt\crtw32\stdcpp\thr\cond.c : 82 + 0x5]
		ip=0x62880afe sp=0x3c4fe4c bp=0x3c4fe80 
	[6] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_b1de77b2e28beeaf6256a3f41ee36302> >,std::default_delete<std::tuple<<lambda_b1de77b2e28beeaf6256a3f41ee36302> > > > >::_Go() [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\thr\xthread : 230 + 0x110]
		ip=0x627604bc sp=0x3c4fe88 bp=0x3c4fed8 
	[7] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!std::_Pad::_Call_func(void *) [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\thr\xthread : 208 + 0x7]
		ip=0x623f36ca sp=0x3c4fee0 bp=0x3c4fee0 
	[8] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!thread_start<unsigned int (__stdcall*)(void *)>(void * const) [d:\rs1\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 115 + 0x2]
		ip=0x627481d5 sp=0x3c4fee8 bp=0x3c4ff1c 
	[9] C:\Windows\System32\kernel32.dll!@BaseThreadInitThunk@12 + 0x24
		ip=0x77078484 sp=0x3c4ff24 bp=0x3c4ff30 
	[10] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart + 0x2f
		ip=0x7750305a sp=0x3c4ff38 bp=0x3c4ff78 
	[11] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart@8 + 0x1b
		ip=0x7750302a sp=0x3c4ff80 bp=0x3c4ff88 
	thread-4 tid=9680 
	[0] C:\Windows\System32\ntdll.dll!_ZwWaitForWorkViaWorkerFactory@20 + 0xc
		ip=0x7750bf1c sp=0x505fac4 bp=0x505fc7c 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x296
		ip=0x774ecbb6 sp=0x505fac8 bp=0x505fc7c 
	[2] C:\Windows\System32\kernel32.dll!@BaseThreadInitThunk@12 + 0x24
		ip=0x77078484 sp=0x505fc84 bp=0x505fc90 
	[3] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart + 0x2f
		ip=0x7750305a sp=0x505fc98 bp=0x505fcd8 
	[4] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart@8 + 0x1b
		ip=0x7750302a sp=0x505fce0 bp=0x505fce8 
	thread-5 tid=10752 
	[0] C:\Windows\System32\ntdll.dll!_ZwWaitForWorkViaWorkerFactory@20 + 0xc
		ip=0x7750bf1c sp=0x559f64c bp=0x559f804 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x296
		ip=0x774ecbb6 sp=0x559f650 bp=0x559f804 
	[2] C:\Windows\System32\kernel32.dll!@BaseThreadInitThunk@12 + 0x24
		ip=0x77078484 sp=0x559f80c bp=0x559f818 
	[3] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart + 0x2f
		ip=0x7750305a sp=0x559f820 bp=0x559f860 
	[4] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart@8 + 0x1b
		ip=0x7750302a sp=0x559f868 bp=0x559f870 
	thread-6 tid=8976 
	[0] C:\Windows\System32\ntdll.dll!_NtWaitForSingleObject@12 + 0xc
		ip=0x7750a28c sp=0x35cfb0c bp=0x35cfb7c 
	[1] C:\Windows\System32\KERNELBASE.dll!WaitForSingleObjectEx + 0x99
		ip=0x75ee45c9 sp=0x35cfb10 bp=0x35cfb7c 
	[2] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!WASAPI_WaitDevice(SDL_AudioDevice *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\audio\wasapi\sdl_wasapi.c : 331 + 0x7]
		ip=0x626b101b sp=0x35cfb84 bp=0x11c06f0 
	[3] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!SDL_RunAudio(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\audio\sdl_audio.c : 711 + 0x7]
		ip=0x626851b6 sp=0x35cfba4 bp=0x11c06f0 
	[4] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll + 0x3ca90
		ip=0x6235ca90 sp=0x35cfbc0 bp=0x11c06f0 
	[5] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!SDL_RunThread(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\thread\sdl_thread.c : 283 + 0x3]
		ip=0x6267c95e sp=0x35cfbc4 bp=0x11c06f0 
		guessed frame
	[6] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!RunThreadViaBeginThreadEx(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\thread\windows\sdl_systhread.c : 105 + 0x11]
		ip=0x626a4337 sp=0x35cfbe4 bp=0x11c06f0 
	[7] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll + 0x384320
		ip=0x626a4320 sp=0x35cfbf4 bp=0x11c06f0 
	[8] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!thread_start<unsigned int (__stdcall*)(void *)>(void * const) [d:\rs1\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 115 + 0x2]
		ip=0x627481d5 sp=0x35cfbf8 bp=0x11c06f0 
		guessed frame
	[9] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!_ceil_pentium4() + 0xdd
		ip=0x6274817d sp=0x35cfc04 bp=0x11c06f0 
		guessed frame
	[10] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!_ceil_pentium4() + 0xdd
		ip=0x6274817d sp=0x35cfc08 bp=0x11c06f0 
		guessed frame
	[11] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll + 0x40e4f0
		ip=0x6272e4f0 sp=0x35cfc24 bp=0x35cfc78 
		guessed frame
	[12] C:\Windows\System32\ntdll.dll!_wcstombs + 0x70
		ip=0x77512580 sp=0x35cfc80 bp=0x35cfc90 
	[13] C:\Windows\System32\ntdll.dll!FinalExceptionHandlerPad31 + 0x1
		ip=0x7751eca0 sp=0x35cfc98 bp=0xffffffff 
	[14] C:\Users\Liam\AppData\Local\Temp\OpenRCT2-0.2.1-develop-223ae74-windows-win32\openrct2.dll!_ceil_pentium4() + 0xdd
		ip=0x6274817d sp=0x35cfca4 bp=0xffffffff 
		guessed frame
	thread-7 tid=12100 
	[0] C:\Windows\System32\ntdll.dll!_ZwWaitForWorkViaWorkerFactory@20 + 0xc
		ip=0x7750bf1c sp=0x15afb78 bp=0x15afd30 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x296
		ip=0x774ecbb6 sp=0x15afb7c bp=0x15afd30 
	[2] C:\Windows\System32\kernel32.dll!@BaseThreadInitThunk@12 + 0x24
		ip=0x77078484 sp=0x15afd38 bp=0x15afd44 
	[3] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart + 0x2f
		ip=0x7750305a sp=0x15afd4c bp=0x15afd8c 
	[4] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart@8 + 0x1b
		ip=0x7750302a sp=0x15afd94 bp=0x15afd9c 
	thread-8 tid=10184 
	[0] C:\Windows\System32\ntdll.dll!_ZwWaitForWorkViaWorkerFactory@20 + 0xc
		ip=0x7750bf1c sp=0x5e7f6f0 bp=0x5e7f8a8 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x296
		ip=0x774ecbb6 sp=0x5e7f6f4 bp=0x5e7f8a8 
	[2] C:\Windows\System32\kernel32.dll!@BaseThreadInitThunk@12 + 0x24
		ip=0x77078484 sp=0x5e7f8b0 bp=0x5e7f8bc 
	[3] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart + 0x2f
		ip=0x7750305a sp=0x5e7f8c4 bp=0x5e7f904 
	[4] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart@8 + 0x1b
		ip=0x7750302a sp=0x5e7f90c bp=0x5e7f914 
	thread-9 tid=11608 
	[0] C:\Windows\System32\ntdll.dll!_NtRemoveIoCompletion@20 + 0xc
		ip=0x7750a2dc sp=0x146f7e8 bp=0x146f818 
	[1] C:\Windows\System32\mswsock.dll!_SockAsyncThread@4 + 0x92
		ip=0x7114a1f2 sp=0x146f7ec bp=0x146f818 
	[2] C:\Windows\System32\kernel32.dll!@BaseThreadInitThunk@12 + 0x24
		ip=0x77078484 sp=0x146f820 bp=0x146f82c 
	[3] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart + 0x2f
		ip=0x7750305a sp=0x146f834 bp=0x146f874 
	[4] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart@8 + 0x1b
		ip=0x7750302a sp=0x146f87c bp=0x146f884 
	thread-10 tid=10416 
	[0] C:\Windows\System32\ntdll.dll!_ZwWaitForWorkViaWorkerFactory@20 + 0xc
		ip=0x7750bf1c sp=0x7b6f828 bp=0x7b6f9e0 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x296
		ip=0x774ecbb6 sp=0x7b6f82c bp=0x7b6f9e0 
	[2] C:\Windows\System32\kernel32.dll!@BaseThreadInitThunk@12 + 0x24
		ip=0x77078484 sp=0x7b6f9e8 bp=0x7b6f9f4 
	[3] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart + 0x2f
		ip=0x7750305a sp=0x7b6f9fc bp=0x7b6fa3c 
	[4] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart@8 + 0x1b
		ip=0x7750302a sp=0x7b6fa44 bp=0x7b6fa4c 
	thread-11 tid=11220 
	[0] C:\Windows\System32\ntdll.dll!_ZwWaitForWorkViaWorkerFactory@20 + 0xc
		ip=0x7750bf1c sp=0x132f824 bp=0x132f9dc 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x296
		ip=0x774ecbb6 sp=0x132f828 bp=0x132f9dc 
	[2] C:\Windows\System32\kernel32.dll!@BaseThreadInitThunk@12 + 0x24
		ip=0x77078484 sp=0x132f9e4 bp=0x132f9f0 
	[3] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart + 0x2f
		ip=0x7750305a sp=0x132f9f8 bp=0x132fa38 
	[4] C:\Windows\System32\ntdll.dll!__RtlUserThreadStart@8 + 0x1b
		ip=0x7750302a sp=0x132fa40 bp=0x132fa48 
```

**Comment by janisozaur** [comment] 2019-02-03 07:51
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8173

**Closed by janisozaur** 2019-02-03 07:51 UTC
Labels: backtrace.io, crash
