### ISSUE TITLE
Bug - Guests/AI/Peeps death traps (Cant find exit)

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3261] opened 2016-04-07 00:14 UTC
**OS:Win 7** 
**Version:0.0.4** 
**Commit:4f3edb6** 

KNOW the AI is BAD and there are a TON of issues out there about the AI problem, but have no idea if anyone mention the AI DEATH TRAPS (Mentioned on this [Wikipedia article](http://rct.wikia.com/wiki/Paths#Pathing_Systems)) `(rct.wikia.com)`

People always get stuck when trying to find the exit as they always walk to the path that are closest to the exit, even if it leads to a dead end and gets stuck in there forever, this is a problem I've seen a lot, especially when there is just one exit, just happens when they 'want to go home'

- [x] Reproducable in RCT2 (vanilla)
- [x] Multiplayer
- [x] Singleplayer

**Screenshots / Video:**
The red marked paths can lead to death traps! (Pulled from the wiki)
![death trap](https://cloud.githubusercontent.com/assets/17282384/14336615/14db1b0a-fc66-11e5-8746-ab7610650d6b.png)
The red paths are DEATH TRAPS where they get stuck as the green once are OK

**Comment by Nubbie** [comment] 2016-04-07 00:24
Explanation:
![explanation](https://cloud.githubusercontent.com/assets/17282384/14336801/e83abbc6-fc67-11e5-80dc-addd00df3091.jpg)

**Comment by Gymnasiast** [comment] 2016-04-07 07:37
Duplicate of #396. And you shouldn't have reacted in _every_ AI bug issue.

**Closed by Gymnasiast** 2016-04-07 07:37 UTC

**Comment by Nubbie** [comment] 2016-04-07 08:52
@Gymnasiast Wanted to make this more into **information** and less as an issue/bug report
I have no idea if most people know about this apparent behavior / bug as I've seen it too often (yesterday most recently) and not many know how to resolve it on servers
