### ISSUE TITLE
Zooming in/out is weird

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#7656] opened 2018-06-11 12:07 UTC
Another thing that is hard to describe... Some parks are super weird when you try zoom in and out and scroll. Zoomed out, the park ends up in the top left corner and it's impossible to just centre the screen on the map. It's a problem with some parks, others are fine. This park has it for example:
https://www.nedesigns.com/park/556/peublo-canyon-boardwalk/

Using version 0.2.0 bcd4e9c on Window 8

**Comment by Patrik356b** [comment] 2018-06-13 19:39
Could this be a new iteration of these sort of issues that has been reported previously?  #2589

**Comment by jensj12** [comment] 2018-06-14 10:11
Duplicate of #7676? (which has been solved in meantime)

**Closed** 2018-06-14 10:11 UTC
