### ISSUE TITLE
Moving mouse after placing haunted house create error in sprite.c

### ISSUE THREAD

**Issue by Vortjong** [OpenRCT2/OpenRCT2#4079] opened 2016-07-14 13:48 UTC
**OS:** Windows 7
**Version:**OpenRCT2-0.0.5.0-develop-5204fb0-windows
**Commit/Build:**5204fb0

[Explanation of the issue...]
Moving mouse after placing haunted house create error in sprite.c

- [ ] Reproducible in RCT2 (vanilla)?
No
- [ ] Multiplayer?
No

**Steps to reproduce:**
1. open attached save game
2. Game is running in windows mode
3. Move mouse around, results in crash

**Screenshots / Video:**
![capture](https://cloud.githubusercontent.com/assets/17613405/16841482/b6b699d4-49d9-11e6-9950-af5db19d9d32.PNG)

**Save game:**
[autosave_2016-07-14_15-01-50.txt](https://github.com/OpenRCT2/OpenRCT2/files/363838/autosave_2016-07-14_15-01-50.txt)

**Comment by Patrik356b** [comment] 2016-07-14 13:52
Clean up your post by removing the placeholders like [e.g. Windows 10]

**Comment by mrtnptrs** [comment] 2016-07-14 14:07
I can reproduce the assertion error using that save. Also, when loading the save, I see this output at the commandprompt window:

```
ERROR[src\rct2\S6Importer.cpp:392 (game_load_sv6)]: invalid checksum
ERROR[src\rct2\S6Importer.cpp:392 (game_load_sv6)]: invalid checksum
```

So, it seems like the save file has been corrupted. What to the devs think?

**Comment by duncanspumpkin** [comment] 2016-07-14 15:21
Something is generating an incorrect sprite identifier. This could be due to some sort of corruption.

**Comment by duncanspumpkin** [comment] 2016-07-16 12:25
There is an extra sprite that has the wrong sprite identifier in the sprite list. No idea how its been created though. Sprite is at 0, 0. So when park goes near those coordinates and tries to draw it will crash.

**Comment by duncanspumpkin** [comment] 2016-07-18 16:52
Retest after the latest commit. I think this is probably due to the map insert element corruption. Note this map is probably corrupted at this point so i expect it will still crash.

**Comment by mrtnptrs** [comment] 2016-07-18 21:07
@duncanspumpkin I think you are right, as the save still crashes for me I soon as I move up the map. I think this can be closed then, as we can never be sure.

**Comment by Gymnasiast** [comment] 2016-08-08 12:12
Considering Duncan's and Maarten's comments and the fact the OP has not reacted for three weeks, I'm going to consider this fixed and close it.

**Comment by janisozaur** [comment] 2016-08-08 12:14
@Gymnasiast have you checked #4083?

**Comment by duncanspumpkin** [comment] 2016-08-08 13:16
@janisozaur that is unrelated.

**Closed by duncanspumpkin** 2016-08-08 13:16 UTC
Labels: bug
