### ISSUE TITLE
Right-clicking in some windows causes the cursor to jump

### ISSUE THREAD

**Issue by Harbinger619** [OpenRCT2/OpenRCT2#2898] opened 2016-02-08 22:04 UTC
If you right-click somewhere in one of these windows, the cursor jumps up and to the left when you release the button. The amount the cursor jumps seems to be related to the size of the window.

Not every window seems to be affected. I could only reproduce this reliably in the Scenery window, the Tile Inspector, and Construct New Ride windows.

**Comment by marijnvdwerf** [comment] 2016-02-08 23:20
What window scale factor are you using?

**Comment by Harbinger619** [comment] 2016-02-09 01:50
I have it set at 1.25. It looks like this issue happens at higher scale settings, because I couldn't reproduce it at the default 1.0. It does still happen at 2.0 and higher.

**Comment by marijnvdwerf** [comment] 2016-02-09 10:48
Duplicate of #2754

**Comment by Wirlie** [comment] 2016-06-19 14:19
Fixed in 5e5ec75

**Closed** 2016-07-19 11:43 UTC
Labels: investigate
