### ISSUE TITLE
BACKTRACE 5730d3 rct_peep::UpdateRideLeaveVehicle

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8438] opened 2018-12-14 16:02 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/5730d3e0e27ef3e66201bbab6ef3c55daf7718a20d229cfdbe6a8ee1a7369039?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Dec 14 2018 16:02:21)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Globf\\Documents\\OpenRCT2\\e1ad5ac8-a8c2-4af8-b7a1-9aaa5e6d4d70.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Globf\\Documents\\OpenRCT2\\e1ad5ac8-a8c2-4af8-b7a1-9aaa5e6d4d70.sv6.gz: <em>1</em><br><strong>commit:</strong> f8d9127: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guard::Assert_VA -> Guard::Assert -> rct_peep::UpdateRideLeaveVehicle -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 19:46
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/7700

**Closed by janisozaur** 2019-02-02 19:46 UTC
Labels: backtrace.io, crash
