### ISSUE TITLE
OpenRCT2 loads a save game I've never seen before, and crashes

### ISSUE THREAD

**Issue by chaitanyathengdi** [OpenRCT2/OpenRCT2#12179] opened 2020-07-09 15:05 UTC
**OS:** Windows 7
**Version:** e.g. 0.2.6
**Commit/Build:** `6c3c857dfa5cd0d267b89a9d70930fbacdfbaea4`

When I try to open OpenRCT2 for the first time, I get a crash with this popup:
![image](https://user-images.githubusercontent.com/14993220/87056434-40801080-c223-11ea-95db-dc64df796d97.png)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Just pointing OpenRCT2 to my installation of RCT2 and opening for the first time.

**Dump file**

[1cb48452-84a5-4dea-b885-780803a4ba47(6c3c857_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/4897674/1cb48452-84a5-4dea-b885-780803a4ba47.6c3c857_x86-64.dmp.gz)

**Save game:**

[1cb48452-84a5-4dea-b885-780803a4ba47.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/4897677/1cb48452-84a5-4dea-b885-780803a4ba47.sv6.gz)

I know the file names don't match up, but it's the same message, just taken at a different time.

**Comment by AaronVanGeffen** [comment] 2020-07-09 15:27
If you just started OpenRCT2, the save game is probably the title screen scenario.

To be clear, you state this happened with the 0.2.6 release, not a develop build. Could you try a recent develop build to check whether the problem persists?

**Comment by chaitanyathengdi** [comment] 2020-07-09 15:38
@AaronVanGeffen I'll check.
I'm not sure if it's the save title screen scenario, but it loads some scenario with a large brown roller coaster I've never seen.
![SCR1](https://user-images.githubusercontent.com/14993220/87060577-5217e700-c228-11ea-942e-00a7536ed773.png)

**Comment by chaitanyathengdi** [comment] 2020-07-09 15:39
I don't get it. Is this save game corrupt?

**Comment by Gymnasiast** [comment] 2020-07-09 15:41
There is a large grey area between corrupt and squeaky-clean saves.

Anyway, please do what Aaron asked and try a `develop` build. Often, a crash in release has already been fixed in `develop`.

**Comment by chaitanyathengdi** [comment] 2020-07-09 15:45
Nope, doesn't work.
I've used the latest develop build available on the website: `6e83055910c1e7f159bf89729ccaa77d7520b607`
Dump:
[dcf69761-02bb-4522-af81-456b3a8715ac(6e83055_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/4897897/dcf69761-02bb-4522-af81-456b3a8715ac.6e83055_x86-64.dmp.gz)
Save:
[dcf69761-02bb-4522-af81-456b3a8715ac.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/4897899/dcf69761-02bb-4522-af81-456b3a8715ac.sv6.gz)

**Comment by chaitanyathengdi** [comment] 2020-07-09 15:48
@Gymnasiast I'd like to emphasize that the save is not mine. I don't have a single save in RCT2 yet; it seems to get that save from somewhere I don't know.

**Comment by duncanspumpkin** [comment] 2020-07-09 16:02
Yeah it's the title screen. That's a save just like any other

**Comment by AaronVanGeffen** [comment] 2020-07-09 16:06
@chaitanyathengdi If 0.2.6 release and develop don't work, could you try the 0.2.5 release and, if that also doesn't work, 0.2.4?

If the problem is what I think it might be, 0.2.4 should work, while 0.2.5 might exhibit the same problem.

**Comment by chaitanyathengdi** [comment] 2020-07-09 16:43
@AaronVanGeffen I'll try with v0.2.4 and report back.

**Comment by chaitanyathengdi** [comment] 2020-07-09 16:47
Doesn't work with v0.2.4 either.
Dump:
[a68daf94-5757-4408-835c-cc9cbf0073a5(d645338_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/4898193/a68daf94-5757-4408-835c-cc9cbf0073a5.d645338_x86-64.dmp.gz)
Save:
[a68daf94-5757-4408-835c-cc9cbf0073a5.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/4898195/a68daf94-5757-4408-835c-cc9cbf0073a5.sv6.gz)

**Comment by chaitanyathengdi** [comment] 2020-07-09 16:49
I tried to auto-upload the dump on another run but that failed with error code 403.

**Comment by chaitanyathengdi** [comment] 2020-07-09 16:51
v0.2.5 also crashes.
Dump:
[ec9d1fed-56f8-499b-959b-a8f336683987(4f6e77e_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/4898225/ec9d1fed-56f8-499b-959b-a8f336683987.4f6e77e_x86-64.dmp.gz)
Save:
[ec9d1fed-56f8-499b-959b-a8f336683987.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/4898224/ec9d1fed-56f8-499b-959b-a8f336683987.sv6.gz)

**Comment by Gymnasiast** [comment] 2020-07-09 16:53
Do you have security software that might get in the way? Some users had problems because their security software employed sandboxing or anti-ransomware protection.

**Comment by chaitanyathengdi** [comment] 2020-07-09 17:15
I tried disabling antivirus; still the same.

**Comment by chaitanyathengdi** [comment] 2020-07-09 17:15
I have Quick Heal Total Security, if that helps.

**Comment by chaitanyathengdi** [comment] 2020-07-09 17:22
BTW, I opened the dump file with a hex editor, and I see this:
![image](https://user-images.githubusercontent.com/14993220/87070675-c5c0f080-c236-11ea-8274-c0ef5dc24c61.png)
Points to some kind of overflow: 'out_of_range'.

**Comment by chaitanyathengdi** [comment] 2020-07-09 18:01
https://github.com/OpenRCT2/OpenRCT2/issues/5496
Reading this, I should say that I do have a copy that has both expansion packs, Time Twister and Wacky Worlds.

**Comment by AaronVanGeffen** [comment] 2020-07-09 19:00
The dump file can be loaded by one of our Windows-using devs. Hopefully it will contain something useful.

**Comment by chaitanyathengdi** [comment] 2020-07-09 19:24
@AaronVanGeffen I hope. Let's see. I'd really like to try out OpenRCT2!

**Comment by janisozaur** [comment] 2020-07-09 19:45
@AaronVanGeffen you can manually submit the dump to backtrace.io via webui

**Comment by duncanspumpkin** [comment] 2020-07-09 20:14
Your CPU doesn't like the avx2 instructions we are using. What CPU do you have?

**Comment by chaitanyathengdi** [comment] 2020-07-09 20:31
i5-4690k.

**Comment by chaitanyathengdi** [comment] 2020-07-09 20:34
Anything else I could do to make it work? Such as compatibility mode?

**Comment by duncanspumpkin** [comment] 2020-07-09 21:11
If you switch to the x86 32 bit builds  we don't enable avx2 instructions on that. See if that works

**Comment by duncanspumpkin** [comment] 2020-07-09 21:12
This is the backtrace https://github.com/OpenRCT2/OpenRCT2/issues/12183

**Comment by janisozaur** [comment] 2020-07-10 06:11
The problem is with end user - we only support win7 with SP1, which the user doesn't have.

**Closed** 2020-07-10 06:11 UTC

**Comment by chaitanyathengdi** [comment] 2020-07-10 06:31
I also ran with v0.2.6 32-bit; dump is here: #12190

**Comment by chaitanyathengdi** [comment] 2020-07-10 06:46
> Your CPU doesn't like the avx2 instructions we are using. What CPU do you have?

@duncanspumpkin I don't think the AVX2 instructions are the issue - look at this info:
![image](https://user-images.githubusercontent.com/14993220/87124706-e1fc7600-c2a6-11ea-8144-9ba674766a43.png)
It does support AVX2.

**Comment by chaitanyathengdi** [comment] 2020-07-10 06:49
Also, this seems related to my issue:
https://github.com/OpenRCT2/OpenRCT2/issues/8117

**Comment by duncanspumpkin** [comment] 2020-07-10 07:10
Or just update windows 7.

**Comment by chaitanyathengdi** [comment] 2020-07-10 08:38
Update: Works on the first try on Windows 10!
I just wish it worked on my Win7 PC - I haven't updated it on purpose because of all the Win10 nagware that's there.

**Comment by AaronVanGeffen** [comment] 2020-07-10 08:53
As @janisozaur mentioned, using Windows 7 would have been fine. However, you would have needed to update it to Windows 7 SP1 at least. I certainly hope you weren't using an unpatched Windows 7 while connected to the internet...

**Comment by IntelOrca** [comment] 2020-07-10 09:31
It doesn't explain why the 32-bit version does not work on W7.

**Comment by janisozaur** [comment] 2020-07-10 09:52
Same reason: AVX2 on outdated OS

**Comment by IntelOrca** [comment] 2020-07-10 10:18
The 32-bit version shouldn't be using any AVX2 or SSE, it is disabled for 32-bit builds to increase compatibility.

**Comment by chaitanyathengdi** [comment] 2020-07-10 14:31
@IntelOrca Would that be planned into a future release?

**Comment by chaitanyathengdi** [comment] 2020-07-10 14:52
Just updated my Win7 to SP1 and the application is now starting!
(Hope there's no nagware though...)

**Comment by Gymnasiast** [comment] 2020-07-10 14:58
@chaitanyathengdi The Windows 10 nagware on Windows 7 stopped when the 1-year upgrade "offer" ended. Besides SP1, I'd recommend also installing the most recent update rollup for Windows 7, especially if that computer is still connected to the internet (which I recommend against).

**Comment by AaronVanGeffen** [comment] 2020-07-13 14:41
> The 32-bit version shouldn't be using any AVX2 or SSE, it is disabled for 32-bit builds to increase compatibility. Well this was what I intended anyway, I might need to undef those macros for x86 platform.

@IntelOrca You may have been thinking of #8119 ?

**Comment by IntelOrca** [comment] 2020-07-13 15:08
@AaronVanGeffen yes, and given @janisozaur and me always have opposite opinions on the matter it sounds like it will only get resolved with a team vote.
