### ISSUE TITLE
Immediate Crash Upon Load in MP

### ISSUE THREAD

**Issue by SquabSauce** [OpenRCT2/OpenRCT2#4262] opened 2016-08-10 22:27 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.5]
**Commit/Build:** [e.g. 426e106]

[Load into Whiskey Station Server 2 Boss Map and BOOM CRASH goes the server]

- [Yessir] Reproducible in RCT2 (vanilla)? 
- [Yessir] Multiplayer? 

**Steps to reproduce:**
1. [Load Map]  
2. [Click to zoom in or move and BOOM CRASH]  

**Dump file**
[
[dumparooski.zip](https://github.com/OpenRCT2/OpenRCT2/files/412214/dumparooski.zip)
]

**Screenshots / Video:**
[
![screenarooski](https://cloud.githubusercontent.com/assets/20958366/17573315/98745340-5f27-11e6-99f0-d6c7c87e9f3c.jpg)
]

**Save game:**
[
[savearooski.zip](https://github.com/OpenRCT2/OpenRCT2/files/412216/savearooski.zip)
]

**Comment by Gymnasiast** [comment] 2016-08-11 07:29
Could you put the commit number in the appropriate field next time, that's a lot easier than having to pry it out of the screenshot.

**Comment by Nubbie** [comment] 2016-08-11 15:11
Like Gymnasiast said
The commit number should be: 69027a8 - But I could reproduce it on the latest commit  bb07785

**The problem** doesn't occure when you zoom out, the problem is with a object/thing somewhere in the middle off the map (check save file and run through the corners to see nothing happens) that can't load/corrupted/missing I presume.

Couldn't open OP's dumpfile (Unhandled exception at 0x362AC19F) <- probs the fault and 'missing file'

**Where does the crash occur/solution**- Delete Twister 1 

-----

Here is my dump file 778e2b8c-01e2-457a-9f4a-12960911e42a(bb07785).dmp

**Error Message:**
Unhandled exception at 0x362AC19F in 778e2b8c-01e2-457a-9f4a-12960911e42a(bb07785).dmp: 0xC0000005: Access violation reading location 0x362AC19F.

**Call Stack:**
```
>	362ac19f()	Unknown
 	[Frames below may be incorrect and/or missing]	
 	openrct2.dll!RCT2_CALLPROC_X(int address, int _eax, int _ebx, int _ecx, int _edx, int _esi, int _edi, int _ebp) Line 45	C
 	openrct2.dll!track_paint(unsigned char direction='\x1', int height=144, rct_map_element * mapElement=0x00f98958) Line 1305	C
 	openrct2.dll!sub_68B3FB(int x, int y) Line 237	C
 	openrct2.dll!viewport_paint_setup(...) Line 693	C
 	openrct2.dll!viewport_paint(rct_viewport * viewport, rct_drawpixelinfo * dpi=0x000cfd68, int left, int top=-555, int right, int bottom=-331) Line 754	C
 	openrct2.dll!viewport_render(rct_drawpixelinfo * dpi=0x000cfd68, rct_viewport * viewport=0x65c9afa0, int left=-5616, int top=0, int right=-1216, int bottom=-331) Line 656	C
 	openrct2.dll!window_editor_main_paint(rct_window * w=0x65c86a60, rct_drawpixelinfo * dpi=0x000cfd68) Line 96	C
 	openrct2.dll!window_draw_single(rct_drawpixelinfo * dpi, rct_window * w=0x65c86a60, int left=0, int top=0, int right=550, int bottom=28) Line 1683	C
 	openrct2.dll!window_draw(rct_drawpixelinfo * dpi=0x000cfdd0, rct_window * w=0x65c86a60, int left=0, int top=0, int right=550, int bottom=28) Line 1577	C
 	openrct2.dll!window_draw_all(rct_drawpixelinfo * dpi, short left, short top, short right, short bottom=28) Line 200	C
 	openrct2.dll!viewport_shift_pixels(rct_drawpixelinfo * dpi=0x06e7d7c0, rct_window * w=0x65c86a60, rct_viewport * viewport=0x65c9afa0, short x_diff=12, short y_diff=0) Line 384	C
 	openrct2.dll!viewport_move(short x, short y, rct_window * w=0x65c86a60, rct_viewport * viewport=0x65c9afa0) Line 464	C
 	openrct2.dll!viewport_update_position(rct_window * window=0x65c86a60) Line 593	C
 	openrct2.dll!window_update_all_viewports(...) Line 154	C
 	openrct2.dll!SoftwareDrawingEngine::Draw() Line 380	C++
 	openrct2.dll!openrct2_loop(...) Line 445	C
 	openrct2.dll!openrct2_launch(...) Line 339	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x01655552, int nCmdShow=10) Line 121	C
 	openrct2.exe!004069e4()	Unknown
 	[External Code]

**Comment by SquabSauce** [comment] 2016-08-11 19:44
Will do!  This was my first time posting to Github so bare with me as I
know nothing about coding or troubleshooting.

On Thu, Aug 11, 2016 at 3:29 AM, Michael Steenbeek <notifications@github.com

**Comment by WhenPenguinsAttack** [comment] 2016-08-13 06:06
@SquabSauce  It does say to put the commit number in the instructions.  ;)

Also getting this issue, on the Sheepsnoop server.  Files are attached.


[error.zip](https://github.com/OpenRCT2/OpenRCT2/files/416434/error.zip)

**Comment by duncanspumpkin** [comment] 2016-09-26 18:00
This has now been fixed by https://github.com/OpenRCT2/OpenRCT2/pull/4423 (well it wont crash but you can't delete the rides until you fix their type)

**Closed by duncanspumpkin** 2016-09-26 18:00 UTC
Labels: crash, investigate
