### ISSUE TITLE
Rowing boats are stuck in incomplete path

### ISSUE THREAD

**Issue by giantmustache** [OpenRCT2/OpenRCT2#11947] opened 2020-06-13 22:00 UTC
**OS:** Windows 10
**Version:** 0.2.6+
**Commit/Build:** 8f29810

Rowing boats get stuck on top of each other when you make a an open path at the end of the station. See image for more info.

It was working for quite a while, like, an hour playing, but they seem to get stuck somehow.

I don't know if this is a typical old RCT2 bug.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Dump file**

**Screenshots / Video:**

![afbeelding](https://user-images.githubusercontent.com/5402708/84579859-df0a8480-add1-11ea-8b4f-3d02f8063140.png)

**Save game:**

**Comment by Gymnasiast** [comment] 2020-06-13 22:09
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/866.

**Closed by Gymnasiast** 2020-06-13 22:09 UTC
