### ISSUE TITLE
Pathing Bug

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1991] opened 2015-10-01 01:21 UTC
https://openrct.net/cloud/uploads/9e16d8ee5cf4acc4888f7bcb28cfc279.sv6

There are a pile of people on that path, walking back and fourth, using their maps to turn around.

**Comment by Christipher** [comment] 2015-10-03 12:26
This appears to be extremely related to issue #1703 or is a duplicate of this issue...

**Comment by PFCKrutonium** [comment] 2015-10-04 15:45
It very well could be, but it is a lot less extreme, and I fixed it with no-entry signs in my save.

**Comment by mrtnptrs** [comment] 2016-06-18 13:52
Could you re-upload that or a similair save file for testing purposes?

**Comment by duncanspumpkin** [comment] 2016-09-28 19:01
Probably fixed

**Closed by duncanspumpkin** 2016-09-28 19:01 UTC
Labels: AI bug, bug
