### ISSUE TITLE
Queue lines broken by build preview paths

### ISSUE THREAD

**Issue by Jimver** [OpenRCT2/OpenRCT2#12072] opened 2020-06-28 13:48 UTC
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** bdbf128

Hi I tried to look for this issue in the GitHub issue tracker but couldn't find it, I'm sorry if I missed it. 

The issue is that queues are broken by paths from build previews. I have the steps below to reproduce and screenshots at every step.

I've had this issue sometimes in normal gameplay where queue lines were suddenly broken, and the cause seems to be hovering the build previews which have paths included over existing queue lines.

**Steps to reproduce:**
1. Build a ride with an queue line with an 180 degree corner
2. Get a ride preview with 2 adjacent paths (I used the woodworm wooden coaster design)
3. Hover the 2 adjacent paths over the 180 degree corner of the already built queue line
4. Move the build preview away again and cancel the build preview.
5. Queue line is now broken (note that no queue paths are deleted it's just the queue line connection that is broken)

**Screenshots:**
Step 1 and 2:
![step12](https://user-images.githubusercontent.com/7677699/85949256-075bbc80-b956-11ea-95db-0e2dc2c4b3b2.png)
Step 3:
![step3](https://user-images.githubusercontent.com/7677699/85949260-0a56ad00-b956-11ea-81f6-9a02514a16e1.png)
Step 4:
![step4](https://user-images.githubusercontent.com/7677699/85949263-0d519d80-b956-11ea-9b3e-13720992a1a8.png)
Step 5:
![step5](https://user-images.githubusercontent.com/7677699/85949262-0cb90700-b956-11ea-9e11-1eb9556edf82.png)

**Save game:**

This is the save after the queue line is broken.
[save.zip](https://github.com/OpenRCT2/OpenRCT2/files/4842348/save.zip)

**Comment by duncanspumpkin** [comment] 2020-06-28 16:26
Duplicate of #11617

**Closed by duncanspumpkin** 2020-06-28 16:26 UTC

**Comment by nepumax** [comment] 2020-07-07 14:33
Windows 10 (x86-64) Version 1909
OpenRCT2 v0.2.6-1063-g94b359810 (94b3598 on develop) provided by GitHub



I had the same issue today. I pre-built a queue line and after hovering over it with my rollercoaster with saved path the queue line was destroyed.

![1](https://user-images.githubusercontent.com/2079937/86796977-6f558580-c06f-11ea-9d5f-2ba7c8e347f1.png)
Pre-built path

![2](https://user-images.githubusercontent.com/2079937/86796980-6fee1c00-c06f-11ea-853b-24e51d1bce89.png)
After hovering over it

![3](https://user-images.githubusercontent.com/2079937/86796981-6fee1c00-c06f-11ea-9b1f-aeabce22db4b.png)
After building it

**Comment by duncanspumpkin** [comment] 2020-07-07 19:15
@nepumax please keep discussion to the open issue #11617
