### ISSUE TITLE
Feature Request: Mute screams

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#11070] opened 2020-03-26 22:12 UTC
**Version:** 0.2.5

[Brought up by this reddit thread](https://www.reddit.com/r/openrct2/comments/fpj42z/how_do_you_mute_guest_screams/)

It _would_ be nice to be able to mute guest screams... Probably as a checkbox in this tab:
![Evergreen Gardens 2020-03-26 15-08-28](https://user-images.githubusercontent.com/26573303/77701563-da24fa00-6f73-11ea-8f6b-bc6c2e57371f.png)
Maybe if you wanted to get really fancy, another volume slider for guest sound effects.

Or maybe for a quick and dirty version that doesn't cause feature bloat, there could at least be a console command that does this?

Besides the person asking for it on reddit, I know I'd appreciate the feature, too. I've tried to get my girlfriend interested in the game, but she refuses because she hates the sound of the screaming guests. Can't even play it when she's around because it bothers her from even a room away.

**Comment by Umdlye** [comment] 2020-03-26 22:28
There are probably an equal amount of people who can't stand the guest vomiting sounds. Having the ability to switch/edit the sound effect files would probably be better than loading up the options menu, but that sounds like a lot of work too.

**Comment by Gymnasiast** [comment] 2020-03-26 22:30
To me it seems that people who cannot handle the screams are either making a fuss about nothing or overly sensitive (in a medical sense). I'm inclined to say "you should turn off all sound effects, then".

There is another way though: get someone to prepare a special CSS1.DAT for you that replaces it with silence. That has been done before when someone wanted to mute the toilet flush sound. Would obviously also work for vomiting sounds.

**Comment by AaronVanGeffen** [comment] 2020-03-26 22:30
I would suggest to leave this to be developed as a plugin rather than a core feature.

**Comment by Gymnasiast** [comment] 2020-03-26 22:33
@AaronVanGeffen If this is possible to handle for a plug-in, of course. It's not like they're magical mods that can just modify everything.

**Comment by Gymnasiast** [comment] 2020-03-26 22:36
This questions also reminds me I still want to create scripts to extract and pack CSS1.DAT files. I even created the OpenSFX repo for that.

**Comment by ocalhoun6** [comment] 2020-03-26 22:46
> There are probably an equal amount of people who can't stand the guest vomiting sounds.

Maybe make the option to disable all guest-based sounds? Call it 'quiet guests' or something.

**Comment by AaronVanGeffen** [comment] 2020-03-26 23:22
> @AaronVanGeffen If this is possible to handle for a plug-in, of course. It's not like they're magical mods that can just modify everything.

Perhaps not in the first release, but we can aim to eventually make the system powerful enough such that this kind of thing _can_ be handled. 

Regardless, I do not think this should be a core feature.

**Comment by duncanspumpkin** [comment] 2020-03-27 07:58
If we made a json object of sounds it would be an easy json edit to remove/replace a sound.

**Comment by Gymnasiast** [comment] 2020-03-27 23:14
I completely forgot about it, but this is essentially a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/2624.

**Closed by Gymnasiast** 2020-03-27 23:14 UTC
Labels: discussion, feature

**Comment by Richard-L** [comment] 2020-04-06 00:02
Muting is a bad idea I agree, but the screaming should be tweaked, I agree. This has been brought up on both the RCF discord and in the project's new own server too:

> Making it so they don't scream over the slightest incline? Don't get me wrong, it's hilarious, but jesus christ they can get loud

The immediate parameters that would come to mind are:
- how long/deep is the drop
- how many peeps are on the train

So for example if the drop is very short, or not deep, and the train only has 4-6 peeps on it, the likelihood for a scream is 0-10%. And so forth...

**Comment by AaronVanGeffen** [comment] 2020-04-06 08:40
@Richard-L Those sound like valid points. Please file another issue for them.
