### ISSUE TITLE
[Feature Request] Sampler tool for scenery objects

### ISSUE THREAD

**Issue by ot5darva** [OpenRCT2/OpenRCT2#5304] opened 2017-03-13 01:00 UTC
OS: Windows 8.1
Version: 0.0.7

A common tool found in most creative programs is a sampler tool that copies already placed color/texture so more of the same thing can be placed again. I think a similar tool for scenery placement will be very useful.

How it can work:
In the scenery selection menu, select the sampler button. Possible button placement and icon:

![sampler placement example](https://cloud.githubusercontent.com/assets/26368692/23837457/e4bc6dde-0745-11e7-8bf3-03d891e30ff3.PNG)

Preferably a keyboard shortcut is assigned for this tool. Perhaps the key 'x' because, by default, it is not in use and conveniently next to the default shortcut for rotate ('z' key).

The cursor changes to eye dropper/picker icon and left-clicking on already placed scenery object on the map will deactivate the tool and change the current selected construction object to that that was copied earlier with the same color (if applicable) and the same rotation (if applicable).

The scenery menu should also jump to the appropriate tab where that object belongs and have that object selected as well.

The user can deactivate the tool by left-clicking on the button again similar to when deactivating the paint brush tool.

**Comment by harrysbird** [comment] 2017-03-13 03:23
I Love that idea
i would to be great to add this feature
This will take lot of work to make this feature.

**Comment by IntelOrca** [comment] 2017-03-13 07:48
> This will take lot of work to make this feature.

I don't think so, it do almost the same logic as the paint brush tool.

**Comment by IntelOrca** [comment] 2017-03-13 07:48
Duplicate of #2078

**Closed** 2017-03-13 08:45 UTC
Labels: duplicate

**Comment by ot5darva** [comment] 2017-03-13 20:02
This feature request is different than #2078. #2078 is about expanding the paint brush tool. It asks to add an additional function to copy an already-placed object color pattern when right-clicking on an object while the paint brush tool is activated.
