### ISSUE TITLE
Scrolling broken

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2589] opened 2015-12-29 21:06 UTC
(From reddit thread: https://www.reddit.com/r/rct/comments/3ym0qf/openrct2_i_made_a_park_with_one_goal_in_mind_put/cyf0cmb)

Retransferred save: https://transfer.sh/1imhJ/mega-micro-park.sv6.gz

When park is opened and you scroll the viewport to southmost corner, you can't scroll back up. happens on Linux and Windows, both on current develop (604e516d5b508e3e0a36360e284ed0cbb1533941) and `v0.0.3.1`

**Comment by LRFLEW** [comment] 2015-12-29 21:07
Can confirm that it happens on OS X as well.

**Comment by PFCKrutonium** [comment] 2016-01-03 01:23
I also confirmed it was also broken in Vanilla. There is also a coaster that inconsistently crashes, and lots of broken z sorting.

**Comment by Goddesen** [comment] 2016-06-03 14:59
Just to further specify, when scrolling past the lower edge of the map the viewport will get rubberbanded back when trying to scroll back up. (`9b705c5`)

**Comment by Patrik356b** [comment] 2017-07-20 12:03
I don't quite the reason for closing this as it hasn't been fixed yet

**Closed** 2017-11-08 16:44 UTC
Labels: bug
