### ISSUE TITLE
Guests enter queue line but reach the entrance and immediately leave

### ISSUE THREAD

**Issue by nathan-osman** [OpenRCT2/OpenRCT2#4819] opened 2016-11-21 00:31 UTC
**OS:** Ubuntu 16.04 (64-bit)
**Version:** 0.0.5

When a guest enters a queue line, they walk to the end of the queue (where the ride entrance is), turn around, and walk out:

I tried rebuilding the queue line in different ways but the result is always the same regardless of the direction of the path. This appears to be happening with most queue lines in the park (though not all).

**Screenshots / Video:**

![out](https://cloud.githubusercontent.com/assets/1253444/20467521/45587472-af3e-11e6-9fb8-0f6f9d705517.gif)

**Save game:**

[openrct2.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/602443/openrct2.sv6.zip)

**Comment by HaasJona** [comment] 2016-11-22 20:02
Closing the rides and rebuilding the entrances seems to fix the problem. Not sure about the actual problem.

**Comment by duncanspumpkin** [comment] 2016-12-10 08:42
This is caused by the next_in_queue being incorrectly set. I remember there was a bug a while back where a fix was submitted that I thought might cause unexpected behaviour. I think this might be related to that. Either way i have a cludge of a fix that will prevent this from causing issues.

**Closed** 2016-12-12 08:33 UTC
Labels: bug
