### ISSUE TITLE
custom scenarios are not having there description load right  

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#3608] opened 2016-05-15 10:29 UTC
OS: Windows 10
Version:0.0.5
Commit: 938c498
It seems custom scenarios are not having there description load right .
This screenshot has the right info. 
![20160515062000_1](https://cloud.githubusercontent.com/assets/18408903/15273372/9e2f1fd8-1a65-11e6-9268-71e2934fd8e1.jpg)

These screenshots show what might load instead of the right description
![20160515062022_1](https://cloud.githubusercontent.com/assets/18408903/15273386/03434fac-1a66-11e6-9dda-eb0fa55c47b5.jpg)

![20160515062036_1](https://cloud.githubusercontent.com/assets/18408903/15273389/308bc732-1a66-11e6-94cf-442e1e0a2868.jpg)

**Comment by YJSoft** [comment] 2016-05-15 10:52
maybe related to #3572

**Comment by IntelOrca** [comment] 2016-05-15 22:25
duplicate of #3572

**Closed by IntelOrca** 2016-05-15 22:25 UTC
Labels: duplicate
