### ISSUE TITLE
In the scenario editor, you can lower land near the edge but not raise it

### ISSUE THREAD

**Issue by Keatzee** [OpenRCT2/OpenRCT2#6210] opened 2017-08-21 16:56 UTC
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** d94c8ff (built myself)

**Steps to reproduce:**
1. Open scenario editor
2. Open the land editor tool and increase the grid size above 1
3. Move the cursor so that some of the tiles are off the map
4. Lower the land, then try to raise it back up

![2017-08-21 12-49-33](https://user-images.githubusercontent.com/18078273/29529993-e0a2db44-866f-11e7-8187-8f1e596ad1be.png)

**Comment by ccoors** [comment] 2017-08-21 17:15
Can reproduce. If I try the same thing outside the scenario editor I get inconsistend behavior. Some edges say 'Off edge of map!' others say 'Land not owned by park!'

**Comment by Keatzee** [comment] 2017-08-21 17:25
Also, on two of the four edges, I get a whole bunch of range errors when I move the selection grid over them. I imagine it's related.

![capture](https://user-images.githubusercontent.com/18078273/29530888-e768fcc0-8673-11e7-922a-8a9525bf07fe.PNG)

**Comment by Gymnasiast** [comment] 2017-08-22 11:03
Duplicate of #828.

**Closed by Gymnasiast** 2017-08-22 11:03 UTC
