### ISSUE TITLE
Request : Staff isn't allowed to enter queues / 

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#7334] opened 2018-03-22 21:55 UTC
Is it possible to realize that? My staff is moving up and down in the queues and isometimes its impossible to mark only the footpath. 

To be honest , i dont want to mark the working stations for each employee. I think its uneffective and i prefer moving employees which can act on the whole map.

The problem is that my staff very very often just enter queues and then they move up and down there and dont get out from there. 

I dont see any effect when my staff enter these queues.

**Comment by duncanspumpkin** [comment] 2018-03-22 21:58
Duplicate of #1999, #4595

**Closed by duncanspumpkin** 2018-03-22 21:58 UTC
Labels: duplicate

**Comment by bjschuit** [comment] 2018-08-28 15:47
This would be a great feature. This issue was unfortunately closed and labeled duplicate. However, the duplicates refer to this issue, so all issues are closed but the feature is not implemented or dismissed.

**Comment by Broxzier** [comment] 2018-08-29 12:58
https://github.com/OpenRCT2/OpenRCT2/issues/3205 is still open.
