### ISSUE TITLE
Game crashes upon save

### ISSUE THREAD

**Issue by iMakedonsky** [OpenRCT2/OpenRCT2#8724] opened 2019-02-19 14:34 UTC
**OS:** windows 10
**Version:** [ 0.2.1]
**Commit/Build:** [8ac731e]

**Steps to reproduce:**
1. Finish any scenario
2. Try to save a game via "new file" button while after clicking "save game" in "quit to menu" dialog.

Here's save and dump:
[5f4ca544-29f7-4ab0-94ca-faaefbd44bc6(8ac731e_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/2880405/5f4ca544-29f7-4ab0-94ca-faaefbd44bc6.8ac731e_x86-64.zip)
[5f4ca544-29f7-4ab0-94ca-faaefbd44bc6.zip](https://github.com/OpenRCT2/OpenRCT2/files/2880408/5f4ca544-29f7-4ab0-94ca-faaefbd44bc6.zip)

**Comment by IntelOrca** [comment] 2019-02-19 14:41
Duplicate of #8164

@iMakedonsky this has been fixed in the latest develop version.

**Closed** 2019-02-19 14:44 UTC
Labels: duplicate
