### ISSUE TITLE
Mystic Flight Track Pieces Suddenly appear as being disconnected in places

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#4589] opened 2016-10-10 21:20 UTC
**windows vista 32-bit** [e.g. Windows 10]
**launcher 0.0.5** [e.g. 0.0.5]
**1520** [e.g. 426e106]

- [ haven't checked] Reproducible in RCT2 (vanilla)?
- [ haven't checked] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

![extreme heights by joshmarsilio 2016-10-10 17-14-51](https://cloud.githubusercontent.com/assets/17103908/19251420/2c798c08-8f0d-11e6-92da-e1f7de88aa93.png)

**Save game:**

**Comment by IntelOrca** [comment] 2016-10-10 21:43
Duplicate of #4586

**Closed by IntelOrca** 2016-10-10 21:43 UTC
Labels: duplicate
