### ISSUE TITLE
TT Police chase coaster sprites glitched in save game

### ISSUE THREAD

**Issue by GustavGoblin** [OpenRCT2/OpenRCT2#6117] opened 2017-08-04 19:25 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.0]
**Commit/Build:** [e.g. 426e106]

The police chase coaster's sprites turn into various land and tunnel sprites. This only happens in an old save game.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

![alcatraz 2017-08-04 13-19-50](https://user-images.githubusercontent.com/30665347/28983669-005e9e10-7918-11e7-8236-838a80b5cef9.png)

**Save game:**

[Alcatraz 2.txt](https://github.com/OpenRCT2/OpenRCT2/files/1201421/Alcatraz.2.txt)

**Comment by jensj12** [comment] 2017-08-04 19:54
Did you load multiple save before opening this one? If so, #6073 might be related. Please provide the save this happens in and fill in the placeholders.

**Comment by Gymnasiast** [comment] 2018-01-02 14:32
With the OP away, I'm going to consider this a duplicate of #6073.

**Closed by Gymnasiast** 2018-01-02 14:32 UTC
Labels: investigate
