### ISSUE TITLE
BACKTRACE 7b2f86 ride_modify -> game_handle_input_mouse

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8366] opened 2018-12-05 17:47 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/7b2f86670b8643232185c49f2119812f231fb0e7e5b2e0809c89fc02cc7de19d?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Dec 05 2018 17:47:23)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> *: <em>1</em><br><strong>commit:</strong> 223ae74: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ride_modify -> game_handle_input_mouse -> game_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 20:05
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8441

**Closed by janisozaur** 2019-02-02 20:05 UTC
Labels: backtrace.io, crash
