### ISSUE TITLE
Feature request: bring back loading bars!

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5834] opened 2017-07-07 20:48 UTC
Currently loading the game, or loading a savegame, is staring at a frozen screen wondering if something is happening and how long it's going to take still.

**Comment by spacek531** [comment] 2017-07-07 21:05
Custom loading bars ala Locomotion I think would not be a bad idea.

**Comment by Liampie** [comment] 2017-07-07 21:09
Custom loading bars would be fun but I imagine it also takes a lot of time from the developer's, time which is better spent doing other things right now. I'd happily have the default windows loading bar back until OpenRCT comes up with its own loading bar!

**Comment by spacek531** [comment] 2017-07-07 21:10
I believe custom loading bars are actually mandatory for cross-platform compatibility. I assume that's the reason the custom file explorer was implemented, at any rate.

**Comment by rwjuk** [comment] 2017-07-07 21:11
@spacek531 Correct.

**Comment by Gymnasiast** [comment] 2017-07-08 08:43
A counter that says something like "Checking objects: 314 / 2712" would probably not be too difficult to implement.

**Comment by janisozaur** [comment] 2017-07-08 20:31
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3190

**Closed by janisozaur** 2017-07-08 20:31 UTC
Labels: feature
