### ISSUE TITLE
Checkboxes untoggling when mouse button released

### ISSUE THREAD

**Issue by dominateeye** [OpenRCT2/OpenRCT2#8945] opened 2019-03-23 12:52 UTC
**OS:** Windows 10
**Version:** 0.2.2-111
**Commit/Build:** 6d99426

When attempting to set prices across the park, the checkbox won't stay checked upon releasing the left mouse button, and if clicking on a checkbox which is below another, the checkbox you're clicking on will uncheck, and the one above will be checked.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by AaronVanGeffen** [comment] 2019-03-23 12:58
Duplicate of #8941

**Closed** 2019-03-23 12:58 UTC
Labels: duplicate
