### ISSUE TITLE
Random colors for balloon, umbrella, hat and T-shirts stalls

### ISSUE THREAD

**Issue by qqkookie** [OpenRCT2/OpenRCT2#7906] opened 2018-08-15 12:14 UTC
**OS:** Windows
**Version:** 0.2.0
**Commit/Build:**

Currently each  balloon, umbrella, hat and T-shirts stall sells one color item per stall.  You should switch colors manually frequently to let peep have balloons of varied colors. or build multiple stalls with different colors.

So how about selling random colored items to the guest?  Balloon stall will sell half of its balloons in the specified color, say light red. But other half balloons sold in same balloon stall will be of random  and varied color, preferably bright colors like blue or yellow. Same to umbrella, hat and T-shirts stalls.

What do you think about it?

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by Broxzier** [comment] 2018-08-15 12:33
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/2154.

**Closed by Broxzier** 2018-08-15 12:33 UTC
