### ISSUE TITLE
In the ride list, some rides' names are replaced with unrelated numbers.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7541] opened 2018-05-19 00:53 UTC
**OS:** [Windows 8]
**Version:** [0.1.3]
**Commit/Build:** [c7b4Oce]

I checked the list of rides in this park, and strangely, three of them have been replaced with numbers. 
When I click on the ride's name in the list, it opens up the ride window, and in _that_ window, the ride's name is displayed correctly.
In the screenshot below, I've opened up Observation Tower 1, which shows up on the list as '16'.
Not all rides are affected, and so far, none of the rides I've set custom names for are affected. I've built several more rides, but so far, none of the new ones have been affected either.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the provided save (or figure out how to get this to happen in a new park).
2. Open the list of rides/attractions

**Screenshots / Video:**
![wacky warren 2018-05-18 17-08-10](https://user-images.githubusercontent.com/26573303/40263237-4e5ba82c-5ac4-11e8-955d-f3e23d28e904.png)

**Save game:**
[Wacky Warren Glitch.zip](https://github.com/OpenRCT2/OpenRCT2/files/2018988/Wacky.Warren.Glitch.zip)

**Comment by telk5093** [comment] 2018-05-19 05:25
Duplicate of #7454, #7532.

**Closed** 2018-05-19 08:29 UTC
