### ISSUE TITLE
Path signs styles missing in RCT1 scenario's 

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#19268] opened 2023-01-24 19:36 UTC
### Operating System

Windows 10 64bit

### OpenRCT2 build

v0.4.3-200-g538b87e (538b87e on develop)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Scenarios provided by Rollercoaster Tycoon 1 Deluxe seem to have a issue related to path signs, as designs other than the default aren't available in the scenery window. This doesn't happen in other scenarios.

### Steps to reproduce

1. Start a new game in Forest Frontiers.
2. Open Object Selection and switch to advanced mode, then navigate to the Path Signs tab.
3. Notice that every style is selected, you can try to disable and enable them again. You can also try to add a scenery group featuring path signs.
4. Open the Scenery window and select the tab with path objects.
5. Notice that only the default path sign style is available. Scenarios that have scenery groups already available from the start, featuring path signs, do have their related styles visible. The rest doesn't show up though. When you remove all the styles in advanced mode, close the window to save these changes, and add them all again only the classical sign shows up.

**Comment by duncanspumpkin** [comment] 2023-01-24 20:46
Could you provide some screenshots just to make it crystal clear what you expect and what you get.

**Comment by sjoerddebruin** [comment] 2023-01-24 20:58
![image](https://user-images.githubusercontent.com/5605979/214411084-18728c1f-40e6-4bee-a740-6d99ab1d7b49.png)

**Current behaviour:**

![image](https://user-images.githubusercontent.com/5605979/214411307-b28ce9d9-69cc-4251-8622-5b5f98854867.png)

**Expected behaviour:**

![image](https://user-images.githubusercontent.com/5605979/214412027-905d342b-5daf-40eb-addb-fbfada3f5b69.png)

**Comment by Broxzier** [comment] 2023-01-24 22:51
I also bumped into a similar object issue on Forest Frontiers. With your provided steps, it's easy to reproduce this consistently.

**Comment by trzejos** [comment] 2023-01-24 23:38
It looks like they are getting filtered out because they get "restricted". You can bypass that check by enabling sandbox mode.

**Comment by trzejos** [comment] 2023-01-24 23:44
This line is responsible, I'm not sure why this choice was made for RCT1 scenarios though:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/rct1/S4Importer.cpp#L203

If you enable sandbox mode, you will see the entries in both the misc tab and the path items tab.

**Comment by trzejos** [comment] 2023-01-25 00:00
the s4 importer added that when the new save format came out, there might be discussion here to review:
https://github.com/OpenRCT2/OpenRCT2/pull/10664

**Comment by trzejos** [comment] 2023-01-25 01:37
It looks like the banners are available in RCT1 scenarios that have the associated themes for each banner available by default, but adding new themes with banners in them does not make the new banner objects available.

I think I know what the issue is, `ClearRestrictedScenery` and `RestrictAllMiscScenery` are only called when importing RCT1 saves/scenarios. When you change the object selection, the restricted scenery list is not refreshed, so the banners continue to get filtered out. I'm not quite sure how to approach this, the restricted scenery list is only ever populated when loading sc4/sv4, so refreshing it every time object selection is changed might make scenery unavailable in sv6/park saves. I've tried saving and reloading the park, but they are still filtered out though because the restricted scenery list is exported in the park file.

I think the correct approach is to remove the misc scenery filtering from S4Importer, and instead properly select scenery groups objects and their entries based on what was configured in the scenario instead of selecting all of the banners and filtering them out later. Maybe someone from the development team could have some input on this.

**Comment by Gymnasiast** [comment] 2024-04-04 16:47
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/21350.

**Closed by Gymnasiast** 2024-04-04 16:47 UTC
Labels: bug, rct1
