### ISSUE TITLE
Object names not showing correctly

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3925] opened 2016-06-20 10:38 UTC
Windows 8
v0.0.5
c177cc7

I just noticed that almost every object is missing letters at the beginning. Tree would show up as 'ee', scrolling sign would show up as 'n sign', et cetera. The number of letters missing seems to be inconsistent.

**Comment by duncanspumpkin** [comment] 2016-07-02 07:07
Is this still happening?

**Comment by mrtnptrs** [comment] 2016-07-14 21:25
I can't reproduce this. @Liampie Can you still reproduce this? If @Liampie doesn't respond, I think we can close this issue report?

**Comment by Gymnasiast** [comment] 2016-08-08 12:15
Closing this due to no answer from the OP.

**Closed by Gymnasiast** 2016-08-08 12:15 UTC
Labels: bug, expired
