### ISSUE TITLE
BACKTRACE 564295 rct_peep::UpdateRideLeaveVehicle

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8163] opened 2018-10-26 20:53 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/56429576538db0ceed190b3449fc8b83d933ceca9b73ac7c14c6c7ae4c0ded41?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Oct 26 2018 20:52:42)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>rct_peep::UpdateRideLeaveVehicle -> rct_peep::UpdateRide -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> SDL_PeepEvents_REAL -> SDL_WaitEventTimeout_REAL -> SDL_PollEvent_REAL -> UiContext::ProcessMessages -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2018-10-26 20:58
```
dump_path: /var/coronerd//openrct2/openrct2/_objects/0000/tx.0011.dmp outfile: -
Classifier: invalid-read
Crash info:
	Application: openrct2.exe
	Crashed YES
	reason: EXCEPTION_ACCESS_VIOLATION_READ
	address: 0x7
Memory Regions:
Sysinfo:
	arch: x86 GenuineIntel family 6 model 15 stepping 11
	cpu_count: 4
	os: Windows NT windows 6.1.7601 Service Pack 1
Modules:
	0x50000 - 0x79000	openrct2.exe 
	0xb5f0000 - 0xb628000	icm32.dll 6.1.7601.23971
	0xf0d0000 - 0xff2f000	openrct2.dll 
	0x5d770000 - 0x5d7e9000	mscms.dll 6.1.7601.23971
	0x670b0000 - 0x670e6000	AudioSes.dll 6.1.7601.23471
	0x69850000 - 0x698b8000	UMEngx86.dll 11.5.1.29
	0x6c7e0000 - 0x6c8cb000	dbghelp.dll 6.1.7601.17514
	0x6c8d0000 - 0x6c8d6000	IconCodecService.dll 6.1.7600.16385
	0x6e900000 - 0x6e903000	api-ms-win-core-synch-l1-2-0.DLL 10.0.14393.2247
	0x711b0000 - 0x711e2000	winmm.dll 6.1.7601.17514
	0x735f0000 - 0x73721000	WindowsCodecs.dll 6.2.9200.22551
	0x73760000 - 0x73773000	dwmapi.dll 6.1.7601.18917
	0x73a30000 - 0x73bce000	comctl32.dll 6.10.7601.18837
	0x73fb0000 - 0x73ff0000	uxtheme.dll 6.1.7600.16385
	0x74030000 - 0x74125000	propsys.dll 7.0.7601.17514
	0x74130000 - 0x74169000	MMDevAPI.dll 6.1.7601.17514
	0x74190000 - 0x74197000	avrt.dll 6.1.7600.16385
	0x74330000 - 0x74355000	powrprof.dll 6.1.7600.16385
	0x74360000 - 0x74369000	version.dll 6.1.7600.16385
	0x746a0000 - 0x746db000	rsaenh.dll 6.1.7600.16385
	0x748c0000 - 0x748c6000	wship6.dll 6.1.7600.16385
	0x748d0000 - 0x7490c000	mswsock.dll 6.1.7601.23451
	0x74910000 - 0x74927000	cryptsp.dll 6.1.7601.23471
	0x74c50000 - 0x74c58000	secur32.dll 6.1.7601.24260
	0x74d90000 - 0x74dab000	sspicli.dll 6.1.7601.24260
	0x74e00000 - 0x74e0c000	CRYPTBASE.dll 6.1.7601.24260
	0x74ee0000 - 0x74eeb000	profapi.dll 6.1.7600.16385
	0x74ef0000 - 0x74efc000	msasn1.dll 6.1.7601.17514
	0x74f00000 - 0x74f04000	api-ms-win-downlevel-shlwapi-l1-1-0.dll 6.2.9200.16492
	0x74f40000 - 0x74f52000	devobj.dll 6.1.7600.16385
	0x74f60000 - 0x75082000	crypt32.dll 6.1.7601.23971
	0x75090000 - 0x75094000	api-ms-win-downlevel-user32-l1-1-0.dll 6.2.9200.16492
	0x75130000 - 0x75133000	api-ms-win-downlevel-normaliz-l1-1-0.dll 6.2.9200.16492
	0x75140000 - 0x75157000	userenv.dll 6.1.7601.17514
	0x75160000 - 0x75187000	cfgmgr32.dll 6.1.7601.17514
	0x751a0000 - 0x751a4000	api-ms-win-downlevel-version-l1-1-0.dll 6.2.9200.16492
	0x751b0000 - 0x751fb000	KERNELBASE.dll 6.1.7601.24168
	0x75200000 - 0x75205000	api-ms-win-downlevel-advapi32-l1-1-0.dll 6.2.9200.16492
	0x75210000 - 0x7521a000	lpk.dll 6.1.7601.24231
	0x75220000 - 0x7529b000	comdlg32.dll 6.1.7601.17514
	0x752a0000 - 0x75342000	rpcrt4.dll 6.1.7601.24260
	0x75350000 - 0x75f9c000	shell32.dll 6.1.7601.24234
	0x75fa0000 - 0x75fbf000	imm32.dll 6.1.7601.17514
	0x75fc0000 - 0x76095000	kernel32.dll 6.1.7601.24168
	0x760a0000 - 0x760b9000	sechost.dll 6.1.7601.18869
	0x76110000 - 0x761a1000	oleaut32.dll 6.1.7601.24117
	0x761b0000 - 0x7634d000	setupapi.dll 6.1.7601.17514
	0x76350000 - 0x763f1000	advapi32.dll 6.1.7601.24260
	0x76400000 - 0x767e1000	wininet.dll 11.0.9600.19155
	0x767f0000 - 0x7683e000	gdi32.dll 6.1.7601.24260
	0x76840000 - 0x76909000	user32.dll 6.1.7601.23594
	0x76a60000 - 0x76b2d000	msctf.dll 6.1.7601.23915
	0x76b30000 - 0x76bcd000	usp10.dll 1.626.7601.23894
	0x76bd0000 - 0x76e06000	iertutil.dll 11.0.9600.19155
	0x76e10000 - 0x76e93000	clbcatq.dll 2001.12.8530.16385
	0x76f00000 - 0x76fac000	msvcrt.dll 7.0.7601.17744
	0x76fb0000 - 0x7710d000	ole32.dll 6.1.7601.24168
	0x77110000 - 0x77252000	ntdll.dll 6.1.7601.24260
	0x77260000 - 0x77263000	normaliz.dll 6.1.7600.16385
	0x77270000 - 0x772a5000	ws2_32.dll 6.1.7601.23451
	0x772f0000 - 0x772f6000	nsi.dll 6.1.7601.23889
	0x77300000 - 0x77357000	shlwapi.dll 6.1.7601.17514
Threads:
	thread-0 tid=124 faulted
	[0] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!rct_peep::UpdateRideLeaveVehicle() [c:\projects\openrct2-ject9\src\openrct2\peep\guest.cpp : 4092 + 0xd]
		ip=0xf2318d0 sp=0x30fadc bp=0x30fb2c 
	[1] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!rct_peep::UpdateRide() [c:\projects\openrct2-ject9\src\openrct2\peep\guest.cpp : 5064 + 0x5]
		ip=0xf232cfb sp=0x30fb34 bp=0x30fb4c 
	[2] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!rct_peep::Update() [c:\projects\openrct2-ject9\src\openrct2\peep\peep.cpp : 1331 + 0x18]
		ip=0xf1cf58a sp=0x30fb54 bp=0x30fb94 
	[3] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::GameState::UpdateLogic() [c:\projects\openrct2-ject9\src\openrct2\gamestate.cpp : 246 + 0xe0]
		ip=0xf1a1717 sp=0x30fb9c bp=0x30fbe8 
	[4] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::GameState::Update() [c:\projects\openrct2-ject9\src\openrct2\gamestate.cpp : 140 + 0x7]
		ip=0xf1a1207 sp=0x30fbf0 bp=0x30fc28 
	[5] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::Update() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 936 + 0x8]
		ip=0xf17aee2 sp=0x30fc30 bp=0x30fcc8 
	[6] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!SDL_PeepEvents_REAL(SDL_Event *,int,SDL_eventaction,unsigned int,unsigned int) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\events\sdl_events.c : 578 + 0x6]
		ip=0xf439152 sp=0x30fc40 bp=0x30fcc8 
		guessed frame
	[7] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!SDL_WaitEventTimeout_REAL(SDL_Event *,int) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\events\sdl_events.c : 681 + 0x11]
		ip=0xf439727 sp=0x30fc54 bp=0x30fcc8 
	[8] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!SDL_PollEvent_REAL(SDL_Event *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\events\sdl_events.c : 662 + 0xb]
		ip=0xf43916b sp=0x30fc78 bp=0x30fcc8 
	[9] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!UiContext::ProcessMessages() [c:\projects\openrct2-ject9\src\openrct2-ui\uicontext.cpp : 523 + 0x12]
		ip=0xf0f76d7 sp=0x30fc84 bp=0x30fcc8 
	[10] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunVariableFrame() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 891 + 0x7]
		ip=0xf17ab7a sp=0x30fcd0 bp=0x30fd18 
	[11] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunGameLoop() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 801 + 0x50]
		ip=0xf17aa13 sp=0x30fd20 bp=0x30fd38 
	[12] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::Launch() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 773 + 0x8]
		ip=0xf17a937 sp=0x30fd40 bp=0x30fda0 
	[13] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int,char const * *) [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 213 + 0x7]
		ip=0xf178bda sp=0x30fda8 bp=0x30fdb4 
	[14] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!NormalisedMain(int,char const * *) [c:\projects\openrct2-ject9\src\openrct2-ui\ui.cpp : 60 + 0x13]
		ip=0xf0f3da7 sp=0x30fdbc bp=0x30fe2c 
	[15] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!LaunchOpenRCT2(int,wchar_t * *) [c:\projects\openrct2-ject9\src\openrct2-dll\openrct2-dll.cpp : 46 + 0x9]
		ip=0xf0f38c2 sp=0x30fe34 bp=0x30fe50 
	[16] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.exe!wmain(int,wchar_t * *,wchar_t *) [c:\projects\openrct2-ject9\src\openrct2-win\openrct2-win.cpp : 27 + 0xc]
		ip=0x5100f sp=0x30fe58 bp=0x30fe60 
	[17] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.exe!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl : 288 + 0x1c]
		ip=0x511d3 sp=0x30fe68 bp=0x30fea8 
	[18] C:\Windows\System32\kernel32.dll!_BasepCopyEncryption@56 + 0x87
		ip=0x7600efac sp=0x30feb0 bp=0x30feb4 
	[19] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x2e
		ip=0x77173618 sp=0x30febc bp=0x30fef4 
	[20] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x1
		ip=0x771735eb sp=0x30fefc bp=0x30ff0c 
	thread-1 tid=5828 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77156c04 sp=0x7cf9b8 bp=0x7cf9ec 
	[1] C:\Windows\System32\kernel32.dll!_BasepCopyEncryption@56 + 0x87
		ip=0x7600efac sp=0x7cf9f4 bp=0x7cf9f8 
		guessed frame
	[2] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x2e
		ip=0x77173618 sp=0x7cfa00 bp=0x7cfa38 
	[3] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x1
		ip=0x771735eb sp=0x7cfa40 bp=0x7cfa50 
	thread-2 tid=7784 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77156c04 sp=0x22ff9d8 bp=0x22ffa74 
	[1] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0x850
		ip=0x7715658c sp=0x22ff9dc bp=0x22ffa28 
		guessed frame
	[2] C:\Windows\System32\KERNELBASE.dll!_InterlockedExchange@8 + 0x6
		ip=0x751b6a8e sp=0x22ff9e0 bp=0x22ffa9c 
		guessed frame
	[3] C:\Windows\System32\KERNELBASE.dll!_KernelBaseGetGlobalData@0 + 0x72
		ip=0x751b6b36 sp=0x22ffa24 bp=0x22ffa9c 
	[4] 0x22ffb00
		ip=0x22ffb00 sp=0x22ffaa4 bp=0x170 
	[5] C:\Windows\System32\user32.dll!_WinStationSendMessageW@40 + 0xb300
		ip=0x768a631b sp=0x22ffaa8 bp=0x22ffb00 
		guessed frame
	thread-3 tid=8128 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77156c04 sp=0x258fa64 bp=0x258fbb4 
	[1] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0x880
		ip=0x771565bc sp=0x258fa68 bp=0x258fb18 
		guessed frame
	[2] C:\Windows\System32\ntdll.dll!_RtlpProbeAssemblyStorageRootForAssembly@28 + 0xde
		ip=0x77141102 sp=0x258fa6c bp=0 
		guessed frame
	[3] C:\Windows\System32\ntdll.dll!_RtlAllocateMemoryZone@12 + 0x120c
		ip=0x771e8338 sp=0x258fa88 bp=0 
		guessed frame
	[4] C:\Windows\System32\ntdll.dll!_RtlAllocateMemoryZone@12 + 0x120c
		ip=0x771e8338 sp=0x258fa8c bp=0 
		guessed frame
	thread-4 tid=7524 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77156c04 sp=0x2b1eec8 bp=0x2b1eed8 
	[1] C:\Windows\System32\kernel32.dll!_BaseCopyStream@56 + 0x3f5
		ip=0x7600f972 sp=0x2b1eedc bp=0x2b1f190 
		guessed frame
	thread-5 tid=1060 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77156c04 sp=0x2a0f618 bp=0x2a0f670 
	[1] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0x840
		ip=0x7715657c sp=0x2a0f61c bp=0x2a0f640 
		guessed frame
	[2] C:\Windows\System32\ntdll.dll!_RtlpSetTimeZoneInformationWorker@8 + 0x104
		ip=0x7716386c sp=0x2a0f650 bp=0x2a0f640 
		guessed frame
	[3] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!__crtSleepConditionVariableSRW(_RTL_CONDITION_VARIABLE *,_RTL_SRWLOCK *,unsigned long,unsigned long) [f:\dd\vctools\crt\crtw32\misc\winapisupp.cpp : 657 + 0x2]
		ip=0xf4c38e9 sp=0x2a0f6a8 bp=0x2a0f698 
	[4] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!Concurrency::details::stl_condition_variable_win7::wait_for(Concurrency::details::stl_critical_section_interface *,unsigned int) [f:\dd\vctools\crt\crtw32\stdcpp\thr\primitives.h : 216 + 0x15]
		ip=0xf62ff00 sp=0x2a0f6c4 bp=0xffb3b4c0 
	[5] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!do_wait(_Cnd_internal_imp_t *,_Mtx_internal_imp_t *,xtime const *) [f:\dd\vctools\crt\crtw32\stdcpp\thr\cond.c : 82 + 0x5]
		ip=0xf62fdfe sp=0x2a0f6dc bp=0x2a0f710 
		guessed frame
	[6] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_b1de77b2e28beeaf6256a3f41ee36302> >,std::default_delete<std::tuple<<lambda_b1de77b2e28beeaf6256a3f41ee36302> > > > >::_Go() [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\thr\xthread : 230 + 0x110]
		ip=0xf50f74c sp=0x2a0f718 bp=0x2a0f768 
	[7] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!std::_Pad::_Call_func(void *) [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\thr\xthread : 208 + 0x7]
		ip=0xf1a36aa sp=0x2a0f770 bp=0x2a0f770 
	[8] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!thread_start<unsigned int (__stdcall*)(void *)>(void * const) [d:\rs1\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 115 + 0x2]
		ip=0xf4f7475 sp=0x2a0f778 bp=0x2a0f7ac 
	[9] C:\Windows\System32\kernel32.dll!_BasepCopyEncryption@56 + 0x87
		ip=0x7600efac sp=0x2a0f7b4 bp=0x2a0f7b8 
	[10] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x2e
		ip=0x77173618 sp=0x2a0f7c0 bp=0x2a0f7f8 
	[11] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x1
		ip=0x771735eb sp=0x2a0f800 bp=0x2a0f810 
	thread-6 tid=8152 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77156c04 sp=0x275fa40 bp=0x275faac 
	[1] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0x870
		ip=0x771565ac sp=0x275fa44 bp=0x275fac4 
		guessed frame
	[2] C:\Windows\System32\kernel32.dll!_BasepMoveFileDelayed@20 + 0x26b
		ip=0x7600c4f0 sp=0x275fa64 bp=0x2bfa438 
		guessed frame
	[3] C:\Windows\System32\KERNELBASE.dll!_MakeNamedLocaleHashNode@8 + 0x1ce
		ip=0x751d06bd sp=0x275faa4 bp=0x275fa54 
		guessed frame
	[4] C:\Windows\System32\kernel32.dll!_BasepMoveFileDelayed@20 + 0x2ae
		ip=0x7600c533 sp=0x275fab4 bp=0x8f8f1cae 
		guessed frame
	[5] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!WASAPI_WaitDevice(SDL_AudioDevice *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\audio\wasapi\sdl_wasapi.c : 331 + 0x7]
		ip=0xf46026b sp=0x275facc bp=0x8f8f1cae 
		guessed frame
	[6] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll + 0x3642c0
		ip=0xf4342c0 sp=0x275fafc bp=0x8f8f1cae 
	[7] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll + 0x3cb60
		ip=0xf10cb60 sp=0x275fb08 bp=0x8f8f1cae 
		guessed frame
	[8] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!SDL_RunThread(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\thread\sdl_thread.c : 283 + 0x3]
		ip=0xf42bb9e sp=0x275fb0c bp=0x8f8f1cae 
		guessed frame
	[9] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!RunThreadViaBeginThreadEx(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\thread\windows\sdl_systhread.c : 105 + 0x11]
		ip=0xf453587 sp=0x275fb2c bp=0x8f8f1cae 
	[10] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll + 0x383570
		ip=0xf453570 sp=0x275fb3c bp=0x8f8f1cae 
	[11] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!thread_start<unsigned int (__stdcall*)(void *)>(void * const) [d:\rs1\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 115 + 0x2]
		ip=0xf4f7475 sp=0x275fb40 bp=0x8f8f1cae 
		guessed frame
	[12] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll + 0x40d790
		ip=0xf4dd790 sp=0x275fb6c bp=0x8f8f1cae 
		guessed frame
	[13] C:\Windows\System32\kernel32.dll!_BasepCopyEncryption@56 + 0x87
		ip=0x7600efac sp=0x275fb7c bp=0x275fb80 
		guessed frame
	[14] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x2e
		ip=0x77173618 sp=0x275fb88 bp=0x275fbc0 
	[15] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x1
		ip=0x771735eb sp=0x275fbc8 bp=0x275fbd8 
```

**Comment by janisozaur** [comment] 2019-02-02 19:45
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/7700

**Closed by janisozaur** 2019-02-02 19:45 UTC
Labels: backtrace.io, crash
