### ISSUE TITLE
hack that worked fine while playing makes file crash when loading it next time

### ISSUE THREAD

**Issue by FischNE** [OpenRCT2/OpenRCT2#3384] opened 2016-04-22 10:40 UTC
**OS:** Windows 10
**Version:** ORCT2 last stable build 0.4
**Commit:** 

Explanation of the issue:
To reproduce it, build a station of any kind of ride. set operating mode to freefall. open and close the ride so that the car is in the game. zero clearences. build another station through the original station so that the original station's data will be overwritten. demolish the second ride so that in the end only the car without any track remains. it worked in original RCT perfectly when I wanted to create theming with ride cars, it worked in ORCT but now the savegame is corrupted and crashes right after loading it (in the latest stable build). It still works in an earlier build though.

- [ ] Reproducible in RCT2 (vanilla)?
Vanilla RCT2 won't work on my OS for me but the file still loads in an earlier build of ORCT.

- [ ] Multiplayer?
It happened during multiplayer but can be reproduced in single player apparently

**Comment by FischNE** [comment] 2016-04-22 10:42
I somehow can't drag and drop my winrar zip file here. Maybe it's too big?

**Comment by Broxzier** [comment] 2016-04-22 10:48
This assert is hit in `vehicle_update_sound`: `assert(ride->type < countof(RideLiftData));`
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/vehicle.c#L4365

**Comment by YJSoft** [comment] 2016-04-22 10:51
[FF_Cars2.txt](https://github.com/OpenRCT2/OpenRCT2/files/231615/FF_Cars2.txt)

**Comment by FischNE** [comment] 2016-04-22 11:01
Thanks for the help. But what do I do haha, I have no idea how to fix this myself.

**Comment by Broxzier** [comment] 2016-04-22 11:54
To continue working on your park, one of us can remove the ride and send you the new saved game. Then you don't have to wait for this to be fixed.

**Comment by Broxzier** [comment] 2016-04-22 13:11
Duplicate of #3375 by the way.

**Closed** 2016-04-26 09:34 UTC
Labels: duplicate
