### ISSUE TITLE
Rocket Cars on Junior Roller Coaster and Compact Inverted Coaster Train on Inverted Coaster (like in RCT1)

### ISSUE THREAD

**Issue by TheLarry98** [OpenRCT2/OpenRCT2#5001] opened 2017-01-06 14:47 UTC
Please add the Rocket Cars on the Junior Roller Coaster and the Compact Inverted Coaster Trains on the Inverted Roller Coaster by default. My point is that those are already selected when we importing track designs from RCT1. But we currently not have the option to select them in OpenRCT2 (except for the cheat or when you import tracks from rct1.)

So what I want:
*Rocket Cars on Mini Roller Coaster and on Junior Roller Coaster
*Compact Inverted Coaster Trains on Compact Inverted Coaster and on Inverted Coaster (like it was in RCT1)

Both things are already a thing when you are importing the Inverted Coaster track design "Danglefeet" and the Junior Roller Coaster design "Raging Rocket"
![rocket cars and compact inverted coaster for openrct2](https://cloud.githubusercontent.com/assets/12634026/21721122/2c0665ac-d427-11e6-9432-fc98530c4780.jpg)

**Comment by janisozaur** [comment] 2017-01-06 15:11
Isn't there a cheat to allow mixing vehicles and tracks already?

**Comment by Gymnasiast** [comment] 2017-01-06 15:23
I have tried to patch Rocket Cars on the fly, but that caused several side effects.
However, switching _to_ them might be within the realm of possibility.

**Comment by IntelOrca** [comment] 2017-01-06 15:55
I don't see why we should change this. The goal is to provide compatibility with RCT1 by using what exists in RCT2, but that doesn't mean we should hack RCT2's objects to work for other things they weren't designed for.

This applies to steep slopes for Junior RC as well. The trains available in RCT2 do not have steep angle sprites and therefore disable the steep slope track. However custom trains could enable the track.

**Comment by X123M3-256** [comment] 2017-01-06 16:52
This is already implemented - it's "Show vehicles from other track types" in the cheat window. It used to be available through the console as well but I think that has been dropped (it wasn't very useful anyway, the cheat is easier).

If you're asking for this to be made the default, I think that's a bad idea. The track gauges don't match and SLC wheels run on the inside of the rails. The only reason to want this is as a stand-in for a train that hasn't been made yet, or because you're importing a layout from RCT1.

Also, the track type for a ride is set in the object file, so to implement this may be awkward the way OpenRCT2 works currently - it loads the default objects from vanilla ObjData folder. You probably don't want to edit that because some people still play vanilla as well.

I would agree with @IntelOrca, the better solution is to port the RCT1 trains, and then set multiple track styles in those objects, not the original RCT2 ones (although the RCT1 SLC train looks awful and I wouldn't blame anyone for not wanting to use it). This would not require any change to OpenRCT2 to implement either.

**Comment by Gymnasiast** [comment] 2018-01-30 22:04
Will be addressed with JSON-objects.

**Comment by Patrik356b** [comment] 2018-01-31 02:48
@X123M3-256 Meanwhile LC train in rct2 is a severe eyesore

**Comment by Patrik356b** [comment] 2018-02-01 01:29
@Gymnasiast paint it fully black to exaggerate the eyesore

**Comment by X123M3-256** [comment] 2018-02-01 09:54
Not nearly as bad as the RCT1 looping trains though. In fact, the RCT1 trains in general are pretty terrible.

**Comment by Gymnasiast** [comment] 2018-02-01 10:17
I like the Giovanola train, though. (On the Inverted RC, at least.)

Anyway, this is getting more and more off-topic.

**Comment by Gymnasiast** [comment] 2018-06-18 17:57
Rocket Cars on the Classic Mini Roller Coaster is now possible. As for the Giovanola train: I plan to only make it available on the Inverted Roller Coaster (for which it was designed) and simply import it as the Vekoma SLC train if used on an Compact Inverted Roller Coaster.

**Comment by Gymnasiast** [comment] 2020-01-11 22:59
I have created https://github.com/OpenRCT2/OpenRCT2/issues/10545 to track status of RCT1 vehicles that weren't in RCT2.

Closing this, as the rocket cars have been modified and the Compact Inverted RC train is a temporary hack.

**Closed by Gymnasiast** 2020-01-11 22:59 UTC
Labels: alteration, rct1
