### ISSUE TITLE
“About 'OpenRCT2'” window has no information about OpenRCT2

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4033] opened 2016-07-10 11:24 UTC
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.5-develop
**Commit/Build:** 59c3656

If you open the “About 'OpenRCT2'” window (accessible in-game through the “floppy disc” icon, you only see the about dialog of RCT2. This dialog has zero information about OpenRCT2, so the menu action is clearly mislabelled.
Fix this by either adding a custom window for OpenRCT2 (and maybe leaving a possibilty to _also_ access the original RCT2 about window, if this makes sense) or by relabelling the menu action.

**Comment by AaronVanGeffen** [comment] 2016-07-10 11:38
Duplicate of #3941

**Closed** 2016-07-10 11:43 UTC
Labels: duplicate
