### ISSUE TITLE
Car ride won't launch

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#1893] opened 2015-09-05 21:07 UTC
I'm not sure if this is caused by overlapping tracks or the play-around with min/max wait time

I'm not sure why this never launches...

Link to savegame: http://puu.sh/k16Sp/29db6fa4a0.sv6

**Comment by Patrik356b** [comment] 2015-09-05 21:15
Might be considered as duplicate of #1838

**Comment by jensj12** [comment] 2015-09-05 21:28
#1838 is not a bug, all rides require guests boarding 2 by 2, and thus a single person won't be able to get on a ride. I can't check your savegame yet, but are there at least 2 peeps in the queue?

**Comment by Patrik356b** [comment] 2015-09-05 21:32
Que is 1 tile long and it's full. Though there are more seats than guests in the que

**Comment by Jjmarco** [comment] 2015-09-05 21:44
It's not a bug (for real this time).
I looked at your save, and you have "Synchronize with adjacent stations" checked in the operating options of your ride.

**Comment by IntelOrca** [comment] 2015-09-05 22:47
@Jjmarco is right, you had synchronise with adjacent stations on. Disable it or build another station adjacent and it will work.

**Closed by IntelOrca** 2015-09-05 22:47 UTC

**Comment by Patrik356b** [comment] 2015-09-06 15:43
@Jjmarco @IntelOrca 
I completely missed that. Though it's odd that it has any effect when there is no adjacent stations present

**Comment by IntelOrca** [comment] 2015-09-06 17:02
It may be unintuitive but that's how its always behaved.

**Comment by Gymnasiast** [comment] 2015-09-06 19:43
Sure, but that doesn't necessarily mean it should behave like that in OpenRCT2. I would be in favour of ignoring it when no adjacent stations are present, unless there are good reasons not to change it.

**Comment by pizza2004** [comment] 2015-09-06 22:56
Yeah, I agree with Gymnasiast on this one, unless it breaks some gameplay somehow it would probably be a nice change.

**Comment by vzybilly** [comment] 2015-09-07 00:21
I don't really see ignored being a good way to handle it but I agree with having a way to not have this issue happen. the way I see is to either disable the option (grey out and uncheck when no adjacent stations are present) or to give a warning when it is checked... after looking over this message, I would go for disabling the option when there are no stations around, simplier and easier for the users to understand.
