### ISSUE TITLE
Lots of guest overcrowd one small area of the park

### ISSUE THREAD

**Issue by austinjb555** [OpenRCT2/OpenRCT2#1703] opened 2015-07-29 03:49 UTC
I'm on build 1065, Windows 7. 
![scr9](https://cloud.githubusercontent.com/assets/12687508/8949586/851b94d0-3583-11e5-8bbb-875a432c0654.png)
There aren't any "No Entry" signs causing this
![scr10](https://cloud.githubusercontent.com/assets/12687508/8949587/851d56d0-3583-11e5-9d51-c46e04eec9b1.png)
The rest of the park is pretty empty.
![scr11](https://cloud.githubusercontent.com/assets/12687508/8949589/8520d602-3583-11e5-872a-6afff70f1c19.png)
Ghost town?
![scr12](https://cloud.githubusercontent.com/assets/12687508/8949588/85206be0-3583-11e5-87e3-d17e42568075.png)
They all seem to be headed somewhere.

EDIT: Removed all guests, placed a bunch of extra info kiosks, and people were headed to places once the park started repopulating. Gave everyone a park map and even though they are headed somewhere they are taking a ridiculous route to get there or walking back and forth in random places.

**Comment by duncanspumpkin** [comment] 2015-07-29 04:59
Ai was modified yesterday. Sounds like the find location code is failing and its calling the aimless code.

**Comment by sjoerddebruin** [comment] 2015-08-02 14:46
The game is unplayable now, what is the ETA for a fix?

**Comment by AaronVanGeffen** [comment] 2015-08-02 14:51
@sjoerddebruin Just roll back to an older build. @duncanspumpkin is moving house, so understandably not working on it atm.

**Comment by austinjb555** [comment] 2015-08-03 00:34
Yeah, I went back to build 1061 and it's working fine for me.

**Comment by ipatix** [comment] 2015-08-03 23:40
Mhm, is it in relation with regular peeps jams that occured in the original?

**Comment by duncanspumpkin** [comment] 2015-08-04 06:18
No it will be something I missed whilst implementing it last week. Sadly I'm still busy so can't look into the issue and intelorca is focused on the new font code right now.

**Comment by daihakken** [comment] 2015-08-04 07:04
@duncanspumpkin the font code is ready, and he has started to fix bugs.

**Comment by HairyMilkshakes** [comment] 2015-08-07 19:55
I've been following the latest dev builds here: https://openrct2.com/download/latest. Do all the recent ones still have pathfinding bug or is that notice just an old placeholder?

**Comment by IntelOrca** [comment] 2015-08-07 20:08
@HairyMilkshakes It might still have a few issues, but nothing as severe as it was a few days ago. I know of at least a couple of improvements we have done on top; @duncanspumpkin fixed a fence / banner issue and I fixed a bug related to peeps not being as observant of the park when they had a park map.

**Comment by HairyMilkshakes** [comment] 2015-08-07 20:09
Got it. I'll continue following new builds and play around with them. Thank you.

**Comment by IntelOrca** [comment] 2015-08-07 20:14
Play the new build, and if you think guests are behaving too strangely for your liking, move to an older build. You may also like to post here what you think is not quite right compared with the original game.

**Comment by austinjb555** [comment] 2015-09-07 19:27
Any updates on this? It's still present and game-crippling.

**Comment by Gymnasiast** [comment] 2015-09-07 19:29
Only a few minutes ago a commit was merged that _might_ have an influence on this.

**Comment by janisozaur** [comment] 2015-09-07 19:40
Oh cool, let me know!

**Comment by IntelOrca** [comment] 2015-09-07 20:13
@Gymnasiast The last commit was only to do with people leaving the park, so only an influence per se.

**Comment by Gymnasiast** [comment] 2015-09-07 20:14
Hm, ok. I can't reproduce this bug on the latest develop version anyway.

**Comment by IntelOrca** [comment] 2015-09-07 20:17
Well I did reduce the impact some time ago... Perhaps @austinjb555 can provide a demonstration save game?

**Comment by austinjb555** [comment] 2015-09-10 04:01
Sorry for taking so long to respond, but here's a save game. The save should load right where it's occuring. I've tried it on the current latest build of 1223, and fast forwarded the game for a minute to see if they disperse. You can click on a guest and see him go back and forth in the same area, even though he's leaving the park. [Download my save file here](http://s000.tinyupload.com/download.php?file_id=00012740230893618259&t=0001274023089361825902389)

**Comment by Patrik356b** [comment] 2015-09-10 16:39
Puush is great for screenshots and random files

**Comment by duncanspumpkin** [comment] 2015-09-28 20:56
@austinjb555 sorry for taking ages to have a look at this but I was away on holiday. The save you provided has quite a few custom objects to save time do you have a link to the custom objects? I can grab them myself but it takes awhile to find each of them.

**Comment by IntelOrca** [comment] 2015-09-28 21:54
@duncanspumpkin its worth checking magic mountain in the meantime - I believe lots of peeps bundle together in the food court which they don't do if you use the original peep update logic.

**Comment by duncanspumpkin** [comment] 2015-09-29 11:17
Okay thanks for that will try have a look tonight.

**Comment by duncanspumpkin** [comment] 2015-09-29 20:20
With magic mountain I find they do that with the normal logic as well.

**Comment by IntelOrca** [comment] 2015-09-29 20:32
Maybe its not as apparent now.

**Comment by austinjb555** [comment] 2015-10-05 22:45
I got all my custom scenery from Amazing Earl. http://ae.rctspace.com/ridewindows/rides-thrill.htm
I completely forgot about these. Hopefully they're not doing anything to cause this issue but it appears other people are having the issue. If you need anything else for me to help just let me know!

**Comment by hkben** [comment] 2015-10-11 18:53
Build 1307

![loop](https://cloud.githubusercontent.com/assets/15078254/10418344/596bb8dc-708a-11e5-9cf9-879c9ca4b39f.png)

As you can see ,guests are looping the same route . There are crossroads both in the beginning and the end of that route. 

Here is my [save](https://dl.dropboxusercontent.com/u/76193904/loop.sv6)

Hope it can help.

**Comment by duncanspumpkin** [comment] 2015-10-11 19:52
@hkben for that save the same behaviour happens in vanilla rct2. (at least it still happens when i switch the pathfinding code to the vanilla version.) Not saying we shouldn't fix issues like this but for now its not the focus.

**Comment by Broxzier** [comment] 2015-10-11 20:01
After removing the no-entry sign blocking the brown path next to the queuing line for the maze the peeps who were leaving the park would use that path. When I noticed that I removed ALL signs from the park, but that didn't change anything, so I doubt they are the cause of this issue.

Also confirmed that it's an issue in the original game as well.

**Comment by duncanspumpkin** [comment] 2015-11-04 12:39
I think AI is now working as good as vanilla. I'm closing this for that reason. If there is a noticeable difference it can be reopened.

**Closed by duncanspumpkin** 2015-11-04 12:39 UTC
Labels: AI bug, bug

**Comment by Littlemeister** [comment] 2016-01-25 18:58
This needs to be fixed, even if its "original" bug, it's still gamebreaking or atleast super anoying and not fun at all. May I ask, is this issue fixed, and if not, do you have any plans on fixing it?

**Comment by PFCKrutonium** [comment] 2016-01-26 17:58
AI Improvements are ongoing and never ending. Lots of work has been done since this was closed.
