### ISSUE TITLE
Opening system save dialog causes crash on Mac OS 10.11

### ISSUE THREAD

**Issue by Niels-NTG** [OpenRCT2/OpenRCT2#4307] opened 2016-08-19 19:06 UTC
**OS:** Mac OS 10.11.6
**Version:** 0.0.5
**Commit/Build:** `5f2c947`

When trying to save the game with the system's save dialog, the game crashed immediately.

**Steps to reproduce:**
1. Open any scenario, new or existing, doesn't matter which way.
2. Try to save the game with the system's save dialog via the corresponding button in the 'save as…' menu.

**Dump file**
[crashlog.txt](https://github.com/OpenRCT2/OpenRCT2/files/427705/crashlog.txt)

**Comment by LRFLEW** [comment] 2016-08-19 20:44
I can't seem to reproduce the error locally.

Looking at the log you've provided, it seems to be erroring during the url resolving before opening the window. That seems really odd to me.

**Comment by LRFLEW** [comment] 2016-08-19 21:11
Found the problem. #4078 Tried to clean up `window_loadsave_mouseup`, but missed a crucial step. Previously, the function set the `path` variable to the folder that the window was looking at, then `browse` would add the default filename, and `platform_open_common_file_dialog` would use that to determine where to open the dialog pointing to. The problem is, during the refactor, the first step got dropped, so the starting directory became undefined. This causes issues in the macOS code when it tries to split the `path` variable into the filename and parent directory, which is where the crash comes in.

**Closed** 2016-08-19 21:33 UTC
Labels: macOS (OS)
