### ISSUE TITLE
Side of water is draw wrong

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3659] opened 2016-05-19 04:38 UTC
**OS: OS X** 
**Version: 0.0.5** 
**Commit: 9e6df44** 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open `Crazy Castle` scenario
2. Raise water

**Screenshots / Video:**
![911E7CC6-3593-40F3-B77A-074AAA9F1F70-2589-00005408C8CBF576](https://dl.dropboxusercontent.com/s/nuhcdzoor9uv3nk/911E7CC6-3593-40F3-B77A-074AAA9F1F70-2589-00005408C8CBF576.gif?dl=0)

**Comment by duncanspumpkin** [comment] 2016-05-19 05:24
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/475 we have implemented enough to fix it though

**Closed by duncanspumpkin** 2016-05-19 05:24 UTC
Labels: duplicate
