### ISSUE TITLE
Pre-existing roller coaster selector shows neither preview nor ride information

### ISSUE THREAD

**Issue by kitsunenokenja** [OpenRCT2/OpenRCT2#6157] opened 2017-08-11 20:01 UTC
**OS:** Gentoo Linux
**Version:** 0.1.1
**Commit/Build:** 4601265

When viewing a list of pre-constructed rides for any roller coaster or variation of ride, the preview dialogue remains completely blank, showing neither a visual of the ride nor its statistics below.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a 64-bit Linux binary from source and load the game.
2. Enable the OpenGL rendering engine.
3. Begin any scenario (issue is exhibited in both RCT1 and RCT2 scenarios).
4. Open the construct ride dialogue and select any type of ride that offers to build a pre-constructed model of that ride.
5. Highlight any of the pre-constructions with the mouse.

**Dump file**

**Screenshots / Video:**

![factory capers 2017-08-11 16-00-46](https://user-images.githubusercontent.com/16778803/29229742-03ce7b24-7eae-11e7-8d82-2c50f2e0e63f.png)
![factory capers 2017-08-11 16-01-07](https://user-images.githubusercontent.com/16778803/29229744-06ab3774-7eae-11e7-99be-bea42321432f.png)

**Additional Notes**
Due to the nature of this bug, it may be related to #6156 since using the software rendering engine options are a workaround.

**Save game:**

**Comment by janisozaur** [comment] 2017-08-11 20:18
https://github.com/OpenRCT2/OpenRCT2/wiki/OpenGL-renderengine-issues

Also duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/4627

**Closed by janisozaur** 2017-08-11 20:18 UTC
