### ISSUE TITLE
There are some empty entries when try to change each cars of Junior RC

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#12319] opened 2020-07-19 13:01 UTC
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** ee39bff

**Steps to reproduce:**
1. Build a Junior Roller Coaster
2. Change its colour scheme by "Different colours per vehicle"
3. Then there are two empty entries: Vehicle 1 & (Last) vehicle

**Screenshots / Video:**
There are 10 cars in this coaster:
![image](https://user-images.githubusercontent.com/10726524/87875141-117b5300-ca0a-11ea-98a8-e7d1ce2724f4.png)

However, there are 12 entries:
![image](https://user-images.githubusercontent.com/10726524/87875153-222bc900-ca0a-11ea-95d2-03e15cb49734.png)

Please just close it if it is duplicated with #2614

**Comment by Gymnasiast** [comment] 2020-07-19 21:49
Yup, indeed a duplicate of #2614.

**Closed by Gymnasiast** 2020-07-19 21:49 UTC
