### ISSUE TITLE
Creating a looping underground crashes client

### ISSUE THREAD

**Issue by Nubebuster** [OpenRCT2/OpenRCT2#3655] opened 2016-05-18 17:48 UTC
**OS:** Windows 10
**Version:**  0.0.5.0
**Commit:** 811f24b

Explanation of the issue:
Creating a looping underground crashes client

- [x] Reproducible in RCT2 (vanilla)?

**Steps to reproduce:**
1. Start building a Giga Coaster
2. Go underground with the track
3. Try to place a looping while not far enough underground

[391b6afb-074b-42ee-a077-46f35bf51771(d4394c7).zip.txt](https://github.com/OpenRCT2/OpenRCT2/files/271067/391b6afb-074b-42ee-a077-46f35bf51771.d4394c7.zip.txt)

I couldn't upload it as a zip (github bug)

**Comment by Patrik356b** [comment] 2016-05-18 19:22
Giga coaster doesn't have a loop. This is a duplicate issue

**Comment by Wirlie** [comment] 2016-05-18 19:25
The same issue of #3597, duplicate of  #3564. I think.

**Comment by Patrik356b** [comment] 2016-05-18 19:26
Yes

**Closed** 2016-05-18 20:32 UTC
Labels: duplicate
