### ISSUE TITLE
Some Scenery Options Unavailable in Scenery Selection (e.g., Jumping Fountains, Certain Trees)

### ISSUE THREAD

**Issue by Mr-Mazoo** [OpenRCT2/OpenRCT2#17610] opened 2022-07-26 00:21 UTC
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.1-41-ge33b35a

### Describe the issue

In original RCT scenarios that had jumping fountains unlockable or unlocked in the original game, they don't show up in the scenery selection at all anymore, even in parks like Evergreen Gardens where there's already jumping fountains present; not even using the eyedropper tool in the scenery menu brings up the jumping fountains. I've also noticed that this applies to specific tree types, like some of those found in Leafy Lake (specifically some of the trees just labelled "Tree," like the more purple-y one and slightly yellow-ish one), they are unavailable for selection in the scenery selection.
![Evergreen Gardens 2022-07-25 17-05-30](https://user-images.githubusercontent.com/84253677/180895986-530722fa-f5a6-483b-8792-c4d124a3d386.png)
![Leafy Lake 2022-07-25 17-07-51](https://user-images.githubusercontent.com/84253677/180896140-05e28112-cba5-4c45-aafd-89839d535ab4.png)

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Open up any RCT1 scenario that has jumping fountains available, like Evergreen Gardens
2. Try to use the eyedropper tool in the scenery selection to select the jumping fountains, which will make the scenery selection screen flicker for a second, but not show the jumping fountains

**Comment by deurklink** [comment] 2022-08-29 18:02
The same happens for trees that are in a scenery set, like the trees from the creepy set in Evergreen Gardens. It also happens to the mine scenery in Forest Frontiers

**Comment by ZeeMajora** [comment] 2022-08-29 18:12
This is an issue with importing the hidden scenery property some RCT1 scenarios use for hiding out of park scenery (eg: the houses on bumbly beach) from the player.
For the time being this issue can be worked around by enabling sandbox mode under cheats, as that will show all the hidden scenery items.

**Comment by MASHzj** [comment] 2023-01-09 21:49
Enabling sandbox mode works for the creepy trees and mine objects in Forest Frontiers, but it doesn't work for the jumping fountains (in other scenarios like Evergreen Gardens). In the original RCT1 game, those trees and mine objects weren't available either in Forest Frontiers, so that works as intended. However, the jumping fountains are part of research in many RCT1 scenarios (the same happens with the clock in the gardens set). I think this might cause the problem, because in RCT2 jumping fountains are either available from the start, or not at all.

**Comment by MASHzj** [comment] 2023-01-16 23:30
Correction to myself: in RCT2 jumping fountains are part of the water feature theme, while in vanilla RCT1 it's added to the path items tab when it's researched. I hope it can be fixed in this way in OpenRCT2.

**Comment by HtotheTML** [comment] 2023-03-28 22:13
Indeed. I hope this finds a fix at some point.

**Comment by Gymnasiast** [comment] 2024-01-30 22:49
This is a bug in the code that tries to check if an object is "Misc scenery" - it doesn’t properly check if the item attaches itself to an existing group. What is needs to do is (1) check if the object attaches to a scenery group, (2) which is actually loaded in this particular game.

**Closed** 2024-03-02 00:46 UTC
Labels: bug, rct1
