### ISSUE TITLE
"Boat Ride 1" appeared as "Ride 1" in news items

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1719] opened 2015-08-03 10:50 UTC
![sss](https://cloud.githubusercontent.com/assets/13048125/9036073/85033c96-3a10-11e5-8a59-ba4dc6f755d8.PNG)
Build Tested, b1074&1063 from OpenRCT2.com

**Comment by IntelOrca** [comment] 2015-08-05 12:47
Might be because some break downs are still called from original code.

**Comment by Gymnasiast** [comment] 2015-08-07 08:40
I think that is the cause, yes. Vanilla RCT2 only had strings for rides with switchable trains, all others had 'Ride' as their name.

**Comment by IntelOrca** [comment] 2015-08-07 09:45
Does this only happen when the RCT1 ride selection feature is on?

**Comment by Gymnasiast** [comment] 2015-08-07 14:38
Probably, otherwise the ride in the screenshot wouldn't use the generic name 'Boat Ride' but 'Bumper Boats' instead.

**Comment by Gymnasiast** [comment] 2015-11-16 09:56
This bug is either already fixed or will be fixed when the responsible code is implemented.

@daihakken : Have you experienced this bug lately?

**Comment by duncanspumpkin** [comment] 2015-11-16 21:09
This doesn't happen any more for boat rides at least.

**Comment by duncanspumpkin** [comment] 2015-11-28 12:17
Not reproducible any more presumed fixed.

**Closed by duncanspumpkin** 2015-11-28 12:17 UTC
Labels: bug
