### ISSUE TITLE
Foothpath items and banners have no description in scenery window

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6822] opened 2017-12-13 23:01 UTC
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** cc27bee

Scrolling over path items like benches, litter bins and banners in the scenery window doesn't display anything in the bottom left like it normally should.

Screenshot:
![crazy castle 2017-12-13 17-54-07](https://user-images.githubusercontent.com/28242696/33966913-5fbde73e-e02f-11e7-96da-09f3cd461281.png)

**Comment by Gymnasiast** [comment] 2017-12-14 10:26
To make even more strange: it affects only UK English.

**Comment by AaronVanGeffen** [comment] 2017-12-14 12:20
Bisecting reveals this was caused by 2b2e617086576ae515a44685500957c846bf54c7.

**Comment by Gymnasiast** [comment] 2017-12-14 12:26
That was my main suspect, so good.

**Comment by Gymnasiast** [comment] 2017-12-14 12:47
Hm, this is irritating. English description for those items contain invalid characters for some reason, confusing our code. Even after reverting most of the changes in that commit.

**Comment by ArcticX9** [comment] 2017-12-15 05:43
This seems to be happening to a lot of buttons in the game for me.

**Comment by Gymnasiast** [comment] 2017-12-15 08:25
@ArcticX9 Which language are you using? Which build of OpenRCT2? Can you post a screenshot?

**Comment by ArcticX9** [comment] 2017-12-15 19:07
English (US) on 7816b11.
![bugs](https://user-images.githubusercontent.com/20503645/34056495-d59b6b2e-e198-11e7-982a-1a05ea22eb19.png)

**Comment by AaronVanGeffen** [comment] 2017-12-15 19:35
@ArcticX9 That version does not include the fix yet. Please try a newer build.

**Comment by mrtnptrs** [comment] 2017-12-15 22:57
@Gymnasiast I seems that your fix contains an error or there is something wrong with Travis CI, as your latest two fixes did produce errors and no builds.

**Comment by Gymnasiast** [comment] 2017-12-16 13:48
That was a failing test. Not ideal, but preferable to the bug. Anyway, it has been fixed by @AaronVanGeffen  in the meantime.

**Comment by Gymnasiast** [comment] 2017-12-22 15:59
Fixed in https://github.com/OpenRCT2/OpenRCT2/commit/c846d985160b2caaa0d69fac5b52421d76bbd0e2.

**Closed by Gymnasiast** 2017-12-22 15:59 UTC
Labels: bug
