### ISSUE TITLE
Constant desyncs when hiring staff

### ISSUE THREAD

**Issue by jombo23** [OpenRCT2/OpenRCT2#7350] opened 2018-03-25 19:25 UTC
**OS:** Windows 10
**Version:** 0.1.3

Any time someone places a lot of paths, pauses the game, or hires staff, everyone else gets booted from the game. This isnt save specific.

Spamming down paths seems to be an easy way to disconnect other users from the game, even on a lan connection. 

The SERVER hiring staff dumps everyone connected, and the SERVER pausing the game dumps everyone as well.

Would it be possible to just have it auto reconnect?

**Comment by ZehMatt** [comment] 2018-04-02 09:32
Regarding the footpath, the issue is because the server executes the placement at a different time than the client within the same tick as in: server executes this at the end of the frame where UI is handled and the client will execute it at the beginning of the frame. This can cause peeps to choose a different path on the client because the peep logic runs after the network update.

The new game actions will solve the out of order issue, however porting everything takes some time I'm afraid, sorry.

**Comment by jombo23** [comment] 2018-04-03 17:49
Hey thanks for the response. I totally get it. 

In the meantime though would it be possible to have an "autoreconnect on desync" option? it seems like itd be fairly easy to implement and a lot less of a hassle than having to quit and rejoin. Map sizes are pretty small too so a less than a second of "hang" would be near unnoticeable and lighten the load of people complaining about desync :V

**Comment by AaronVanGeffen** [comment] 2018-04-03 17:52
Trouble is, while you're reconnecting, the map is likely going to change. Of course, you can send the changes as you normally would, or in batches if you must, but what if another desync occurs? This seems very likely if someone is working with the path tool or what not, as you've pointed out fairly.

It is for this reason that this has not been implemented.

**Comment by jombo23** [comment] 2018-04-07 03:25
Couldnt the same exact thing happen when you reconnect anyways? I see your point but i fail to see why that would be an issue.

Sorry for the delayed response, didnt see the notification

**Comment by duncanspumpkin** [comment] 2019-03-07 19:00
Paths and pause should be fixed now. Staffs still cause desyncs.

**Comment by ZehMatt** [comment] 2019-05-11 17:53
Gonna close this as there is a more specific issue #8731. The other mentioned issues should be fixed.

**Closed by ZehMatt** 2019-05-11 17:53 UTC
Labels: bug, multiplayer
