### ISSUE TITLE
Scrolling signs get messed up in this park that has a lot of them in the same screen

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#11800] opened 2020-05-23 17:39 UTC
**OS:** [Windows 10]
**Version:** [0.2.6]
**Commit/Build:** [1020969]

It's most clearly visible on the queue entries and the park entrance.

![image](https://user-images.githubusercontent.com/6469413/82736859-e4bdfe80-9d2c-11ea-9b4d-69bfb4b36beb.png)

[Pokeypark1million.zip](https://github.com/OpenRCT2/OpenRCT2/files/4672228/Pokeypark1million.zip)

**Comment by leftie1989** [comment] 2020-06-09 03:29
I was about to report this myself. Here's a short gif i was going to post, this happens in this section the most. I'm happy to provide the entire save if it'd help. It's a heavily modified "Blackpool Pleasure Beach" scenario.  I can also provide the original size video for this, if its too difficult to ascertain from the much lower scale gif.

![scroll error](https://user-images.githubusercontent.com/8727023/84102986-b8330380-aa09-11ea-8a3f-e02c844895f5.gif)

Hopefully this might help someone to figure out what's going on from it, if weren't sure already.

**Comment by jensj12** [comment] 2021-01-11 10:42
Duplicate of #9631 and fixed by #13669.

**Closed** 2021-01-11 11:45 UTC
Labels: bug
