### ISSUE TITLE
Vehicle Design/Scenary Unavailable

### ISSUE THREAD

**Issue by D1JL** [OpenRCT2/OpenRCT2#8569] opened 2019-01-07 14:38 UTC
This may have been asked before however, I searched and found no referance.

Many of the pre-maid coasters available, there is a discloser at the bottom of the picture window. 
(Design Includes Scenery Which Is Unavailable) 
(Vehicle Design Unavailable - Ride Performance May Be Affected) 
Is there a way to see what is required to view these rides in the manner that the designer intended? 
Sometimes it is good to learn other's techniques. 
Thanks, 
Dave

**Comment by jensj12** [comment] 2019-01-07 18:07
Duplicate of #5860.

**Closed** 2019-01-18 19:06 UTC
Labels: duplicate
