### ISSUE TITLE
Rides with merged tracks using zero clearance can't be opened due to "Track is not a complete circuit" error

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#4733] opened 2016-10-31 11:30 UTC
**OS:** [Windows 10 x64]
**Version:** [0.0.5]
**Commit/Build:** [12bd31b]

You used to be able to connect rides using the "Zero clearance" cheat but it doesn't work anymore.

Enabling "allow testing unfinished tracks" lets you test the ride, but not open it.
The tracks are properly connected since the ride doesn't crash.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build two rides and connect their track using the zero clearance cheat.
2. Try to open the ride with a station. (doesn't matter if both of them have stations or not)

**Dump file**
N/A

**Screenshots / Video:**
![error](https://cloud.githubusercontent.com/assets/3462541/19852255/8b343532-9f1f-11e6-8d48-c968590771b3.PNG)

**Save game:**
[zcride.zip](https://github.com/OpenRCT2/OpenRCT2/files/561587/zcride.zip)

**Comment by IntelOrca** [comment] 2016-10-31 11:31
You must select a ride mode that doesn't require a complete circuit like Boat hire.

**Comment by Gymnasiast** [comment] 2016-11-01 09:36
Does the Looping RC make a complete circuit?

**Comment by Margen67** [comment] 2016-11-01 10:11
@Gymnasiast No. 
![no](https://cloud.githubusercontent.com/assets/3462541/19886530/e0493f56-9fe0-11e6-965b-2862042a0ece.PNG)

**Comment by Gymnasiast** [comment] 2016-11-01 11:04
Ok, in that case it's intended behaviour. I'll close this for that reason.

**Closed by Gymnasiast** 2016-11-01 11:04 UTC
Labels: non-bug

**Comment by IntelOrca** [comment] 2016-11-01 13:24
For future reference, this won't be a problem when we finally implement multiple track sprites for the same ride ID.
