### ISSUE TITLE
Game Crash when I test the roller coaster

### ISSUE THREAD

**Issue by LordHISKI** [OpenRCT2/OpenRCT2#5749] opened 2017-07-01 09:49 UTC
Everytime i try to test my rc (mine train 2) my game crash. I dont know why and there is no explanation.

**Save game:**

[Gamecrash.txt](https://github.com/OpenRCT2/OpenRCT2/files/1116966/Gamecrash.txt)

**Comment by Gymnasiast** [comment] 2017-07-01 10:15
You removed several fields in the template and did not fill in the upper three. We cannot help you if you don't provide that information.

**Comment by IntelOrca** [comment] 2017-07-01 11:11
**Loop stuck during creation of vehicles:**
loc_6DDF9C:4885:
```
do {
    ...
} while (!(vehicle_update_track_motion(train, NULL) & 0x400));
```

**Stack:**
```
#0  0x00007f125bf101ef in loc_6DDF9C (ride=0x7f125c935dc0 <gRideList+28576>, mapElement=0x7f125ca1c880 <gMapElements+273888>) at ride.c:4885
#1  0x00007f125bf10064 in ride_create_vehicles (ride=0x7f125c935dc0 <gRideList+28576>, rideIndex=47, element=0x7ffe56150260, isApplying=1) at ride.c:4833
#2  0x00007f125bf10f6c in ride_is_valid_for_test (rideIndex=47, goingToBeOpen=0, isApplying=1) at ride.c:5283
#3  0x00007f125bf11787 in game_command_set_ride_status (eax=0x7ffe561503ac, ebx=0x7ffe561503a8, ecx=0x7ffe561503a4, edx=0x7ffe561503a0, esi=0x7ffe5615039c, edi=0x7ffe56150398, ebp=0x7ffe561503c0) at ride.c:5510
```

**Comment by LordHISKI** [comment] 2017-07-01 11:29
i didnt do anything. I builded the coaster without any cheat or something. Just normal. I didnt removed anything

**Comment by IntelOrca** [comment] 2017-07-01 11:31
@Gymnasiast could you check if this happens in vanilla?

**Comment by wolfreak99** [comment] 2017-07-01 13:45
@Gymnasiast  I just tested it in Vanilla RCT2 (GOG version), and it shows an access violation.

I'm also on windows 10 and the game tends to minimize about 3 times while it opens into full screen, and i checked if it would run the Six Flags Belgium scenario okay and it stops responding about 5 seconds (with no access violation error) into the game, but for what it's worth, this save file does seem to throw an access violation error.

**Comment by IntelOrca** [comment] 2017-07-01 17:32
Interestingly, if you save the track design and place it elsewhere in the map - it works.

**Comment by IntelOrca** [comment] 2017-07-01 18:35
Removing the diagonal chain lift that goes from up to straight will fix it. I am not sure why it causes a problem yet.

**Comment by jensj12** [comment] 2017-07-02 16:31
Duplicate of #3846. If a train starts on a diagonal chain lift (in block brake mode), the game crashes.

**Closed** 2017-07-04 06:43 UTC
Labels: bug
