### ISSUE TITLE
Crash for unknown reasons

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#3629] opened 2016-05-16 04:12 UTC
**OS: 8.1** 
**Version: .5** 
**Commit: 9ebb7f4** 

Explanation of the issue: unknown crash. Simply moved the camera away from the ride. Last autosave has the same behavior.

**Dump file**
If you have a dump file, zip it and drag&drop it here.

[unknown crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/265542/unknown.crash.zip)

**Comment by janisozaur** [comment] 2016-05-16 20:46
0x6C4934
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3578

**Closed by janisozaur** 2016-05-16 20:46 UTC
Labels: investigate
