### ISSUE TITLE
Allow placing track designs underground

### ISSUE THREAD

**Issue by hiandbye7** [OpenRCT2/OpenRCT2#2856] opened 2016-02-01 13:55 UTC
So, you probably now this problem. You can save track designs like these two:
<img src="https://cloud.githubusercontent.com/assets/15168206/12718537/76b26806-c8ef-11e5-9ceb-12a3097c31bd.png" width="400" />
<img src="https://cloud.githubusercontent.com/assets/15168206/12718539/76db20ca-c8ef-11e5-96d3-c18f5acfa0dc.png" width="400" />
But there is no way to place them underground again:
<img src="https://cloud.githubusercontent.com/assets/15168206/12718538/76d2b64c-c8ef-11e5-8696-ed9f1f02ff67.png" width="400"/>
<img src="https://cloud.githubusercontent.com/assets/15168206/12718540/76dd5e9e-c8ef-11e5-9249-90d38eefb892.png" width="400"/>

This is related to issue #450, you could merge these two as you see fit.
Any prediction on how difficult it would be to implement this/when it will be implemented?

**Comment by IntelOrca** [comment] 2016-02-01 15:05
Probably just a case of implementing #450

**Comment by Gymnasiast** [comment] 2016-02-04 10:46
What do we do with this one, keep it open or consider it a duplicate of #450?

**Comment by IntelOrca** [comment] 2016-02-04 11:16
I'd merge them as the logic will most likely be shared.

**Comment by Gymnasiast** [comment] 2016-02-04 11:51
Merged with #450.

**Closed by Gymnasiast** 2016-02-04 11:51 UTC
Labels: duplicate
