### ISSUE TITLE
Some sounds are missing/doesn't play

### ISSUE THREAD

**Issue by daskelito** [OpenRCT2/OpenRCT2#15870] opened 2021-11-07 16:32 UTC
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5 (b9bc8d0) provided by GitHub

### Describe the issue

Sounds are missing, most noticably when landscaping and placing down objects, even things as guests cheering when exiting a ride they like or the sounds from the toilets. Everything else works as normal: guests chattering, cashier sounds, majority of ride sounds, water landscaping sound. I have RCT2 installed on steam and if i start that program, all sounds and music work fine. Only in RCT2 it doesn't work. Have tried different versions (3.4, 3.4.1 and 3.5) of OpenRCT2 and, both installable and portable.

### Steps to reproduce

Made a video of me reproducing it. 

https://www.youtube.com/watch?v=Eoq-yz9cPBA

**Comment by daskelito** [comment] 2021-11-07 16:53
I've noticed now that the sounds aren't really missing, the play back volume is just **really** low. Sorry for the confusion. Is there a way to fix this?

**Comment by IntelOrca** [comment] 2021-11-07 17:14
In v0.2.0, the place sound is louder than in current builds. So at some point the behaviour has changed with how it calculates the volume of sounds. Probably needs bisect to find it.

**Comment by tupaschoal** [comment] 2021-11-12 22:16
This seems to be a duplicate of #7490

**Closed by tupaschoal** 2021-11-12 22:16 UTC
Labels: bug, duplicate
