### ISSUE TITLE
Can only select one wagon

### ISSUE THREAD

**Issue by pazifi** [OpenRCT2/OpenRCT2#7157] opened 2018-02-10 11:55 UTC
**OS:** Debian
**Version:** 9.3 (Stretch/Stable)
**Commit/Build:** Latest from git (8e55c811f671f6338f05870e766720f6ba3de51c)

For various railways where the maximum number of wagons is determined by the entry point, you can select a maximum of one wagon.

- Reproducible in RCT2 (vanilla)
no
- [ ] Multiplayer?
unknown

**Steps to reproduce:**
1. Open any game
2. Create a rollercoaster like "splash boat"

![bildschirmfoto_2018-02-10_12-47-20](https://user-images.githubusercontent.com/4640284/36061849-f84298d8-0e60-11e8-86dd-1466b1e74814.png)
![bildschirmfoto_2018-02-10_12-52-34](https://user-images.githubusercontent.com/4640284/36061866-494f8eac-0e61-11e8-9201-6074ded998a5.png)

**Comment by Gymnasiast** [comment] 2018-02-10 11:56
Duplicate of #7137.

**Comment by pazifi** [comment] 2018-02-10 11:56
Excuse me, is duplicated.

**Closed by Gymnasiast** 2018-02-10 11:56 UTC
