### ISSUE TITLE
Crash When Loading Game Saved In Build dcf0a9d

### ISSUE THREAD

**Issue by WhenPenguinsAttack** [OpenRCT2/OpenRCT2#3889] opened 2016-06-17 03:21 UTC
**OS:** : Windows 7
**Version:** : 0.0.5
**Commit/Build:** : dcf0a9d

EDIT: Ignore this part.

I'm trying to remove a custom ride (the zipline coaster) from my version of the Group Park project on the ORCT2 forums, but it seems that the act of removing the ride and saving the park causes the game to crash when loading that game later.  The DAT file for the ride is attached.

EDIT: Stop ignoring.

It looks like the DAT file has nothing to do with the game crashing- reverted back to the last stable version and it saves and reloads files fine.  Looks like a bug was introduced in the last few dev versions.

- [ ] Reproducible in RCT2 (vanilla)
- [ ] Multiplayer?

**Steps to reproduce:**

EDIT: Ignore below.

1. Load original version of park with DAT file in it (need load incorrect checksums to be on, attached)
2. Remove zipline coaster as a buildable ride from the park.
3.) Save game as a different file.
4.) Load the new file.

EDIT: Stop ignoring.

1.) Start new park in build dcf0a9d.
2.) Save file.
3.) Load save file.

**Dump file**
[e9348c50-e33b-4ee5-bd1e-f3e89c0fb67f(dcf0a9d).zip](https://github.com/OpenRCT2/OpenRCT2/files/319705/e9348c50-e33b-4ee5-bd1e-f3e89c0fb67f.dcf0a9d.zip)

**Save game:**

Original Park: 
[The OpenRCT Group Park 3.57.zip](https://github.com/OpenRCT2/OpenRCT2/files/319706/The.OpenRCT.Group.Park.3.57.zip)

Park With Zipline Coaster Removed:
[The OpenRCT Group Park 3.57a.zip](https://github.com/OpenRCT2/OpenRCT2/files/319707/The.OpenRCT.Group.Park.3.57a.zip)

Park file generated by error system:
[e9348c50-e33b-4ee5-bd1e-f3e89c0fb67f.zip](https://github.com/OpenRCT2/OpenRCT2/files/319710/e9348c50-e33b-4ee5-bd1e-f3e89c0fb67f.zip)

**Comment by WhenPenguinsAttack** [comment] 2016-06-17 03:29
Actually, it looks like that saving any park with or without the zipline DAT and then loading that file at a later point causes the game to crash, so it looks like the zipline DAT may not be responsible.

**Comment by WhenPenguinsAttack** [comment] 2016-06-17 03:38
Reverting back to the last stable version appears to resolve the issue, so it looks like some kind of bug was introduced in the last few dev versions.

**Comment by janisozaur** [comment] 2016-06-17 06:41
This is the same as https://github.com/OpenRCT2/OpenRCT2/issues/3886, which I marked as a duplicate of #3193, but perhaps only the symptoms are the same and not the underlying cause.

**Closed** 2016-06-17 06:57 UTC
