### ISSUE TITLE
Crash dump: Assertion failed. Tried getting sprite 65535

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#4238] opened 2016-08-06 18:16 UTC
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** ac950e0
An assertion failed.
Version: OpenRCT2, v0.0.5-dev build ac950e0 powered by AppVeyer
Tried getting sprite 65535

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Dump file**
[04b9e17d-2b3e-47fb-8a1f-a80992591a11.zip](https://github.com/OpenRCT2/OpenRCT2/files/405128/04b9e17d-2b3e-47fb-8a1f-a80992591a11.zip)

**Comment by Nubbie** [comment] 2016-08-06 18:19
dupe of #4204

**Closed** 2016-08-06 18:22 UTC
Labels: duplicate
