### ISSUE TITLE
No scenery appearing in menu

### ISSUE THREAD

**Issue by Enzemo** [OpenRCT2/OpenRCT2#1805] opened 2015-08-17 04:15 UTC
Somehow I managed to open the scenary menu whilst I had the path menu open too. All it showed me was the bouncing fountains and showed the menu type as "Footpath scenery types". It also had a "?" tab which said "Traditional Park Entrances". When clicking on the "?" there are no scenery options, and the footpath scenery tab disappears. Closing scenery and reopening doesn't resolve. Tried reloading the game and it also didn't work. Here's the savefile http://www.filedropper.com/octagonpark

Seems to be isolated to this save. I'm unsure how I managed to open both windows at the same time; all I know was that I was building that path from the floorless rollercoaster up to the main pathline, and clicked the scenery to add some benches etc when I saw that there were only fountains. At first I thought "Oh cool, it filters to only path scenery.. Wait.. Where are the benches and lights then?"

Thanks guys :) On v.0.0.3-develop build A649 (00ab8be)

![image](https://cloud.githubusercontent.com/assets/11069930/9297924/4adeb82c-449e-11e5-82d8-34ccd6a7fd57.png)

![image](https://cloud.githubusercontent.com/assets/11069930/9297960/0042d39c-449f-11e5-8f2f-95a38dba23bb.png)

**Comment by sjoerddebruin** [comment] 2015-08-17 08:14
Have you tried opening object selection and close that window?

**Comment by Enzemo** [comment] 2015-08-18 02:31
I just tried it and it resolved the issue. Hopefully that gives a clue as to what causes it in the first place; if I manage to reproduce it I'll update this post again.

Thanks very much :) You saved my savegame

**Comment by duncanspumpkin** [comment] 2015-11-15 17:43
Has anyone had this happen again?

**Comment by ecnepsnai** [comment] 2015-12-26 02:01
I am experiencing this issue on build 1573 on both Windows and OS X.
<img width="327" alt="scr3" src="https://cloud.githubusercontent.com/assets/1607109/12004852/7ffbfcb4-ab31-11e5-941e-04f9d51c963b.png">

**Comment by janisozaur** [comment] 2015-12-26 08:53
@ecnepsnai can you provide revision you used and steps to reproduce?

**Comment by ecnepsnai** [comment] 2015-12-26 17:43
@janisozaur Rev 3b5768f

Much like @Enzemo it seems to happen with specific parks.  For me, it appears to happen with the RCT1 scenarios pack I downloaded from here: https://www.reddit.com/r/rct/comments/1h93gx/more_exact_recreations_of_rct1_scenarios_for_rct2/

1. Open a scenario (in the above screenshot it's Kate's World)
2. Click scenery button

**Comment by ecnepsnai** [comment] 2015-12-30 18:19
Still happens on rev edaec24

After doing some debugging it looks like the individual scenery items are instantiated, but lost somehow.  This line right here: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/windows/scenery.c#L360  seems weird to me (why are we skipping enabled scenery sets?)

**Comment by mrtnptrs** [comment] 2016-06-18 13:38
I can't reproduce this issue with the latest build and using the exact same steps as above. I think this issue can be closed as I never saw this happening myself. But @ecnepsnai and @Enzemo  can you still reproduce this bug?

**Comment by ecnepsnai** [comment] 2016-06-19 05:44
@mrtnptrs Cannot reproduce issue anymore. Appears to be resolved.

Vote to close issue.

**Comment by bloup** [comment] 2018-01-10 15:20
This is happening to me on v0.1.2 build 0995ab9

[Evergreen Gardens Better 3 glitched maybe.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1619354/Evergreen.Gardens.Better.3.glitched.maybe.sv6.zip)

I don't really remember what exactly happened before the problem started to occur. I do remember building paths and scenery at the same time if it matters.

**Comment by bloup** [comment] 2018-01-10 16:52
I also resolved it by opening the object selection window.

**Comment by Gymnasiast** [comment] 2018-01-10 18:42
@bloup See #6990.

**Closed by Gymnasiast** 2018-01-10 18:42 UTC
Labels: bug
