### ISSUE TITLE
error when removing paths under peeps

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#2428] opened 2015-12-03 04:50 UTC
This sometimes appears when I am removing paths under peeps. The first time, I hit "retry" and the game crashed, and the second time, I hit "ignore" and the game continued.

![image](https://cloud.githubusercontent.com/assets/3454156/11551093/e10d85fe-992a-11e5-87af-9177c95292f4.png)

So far: it has happened while right-clicking path, and it has happened when using the destroy tool set to paths.

**Comment by janisozaur** [comment] 2015-12-03 07:00
This will be a duplicate of #2417. Please use search next time and try to report issues correctly (build version, OS version, locale, …).

Try a build including 8eb313f

**Closed** 2015-12-03 07:57 UTC
Labels: duplicate
