### ISSUE TITLE
Multidimension Coaster appears in map

### ISSUE THREAD

**Issue by Manticore-007** [OpenRCT2/OpenRCT2#21744] opened 2024-04-07 17:56 UTC
### Operating System

Windows 11 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.10-3-g26d65b3 (26d65b3 on develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

from commit 26d65b3 a multidimension coaster appears in an existing map, looks like an issue with the colour scheme.

commit 5824953:
![image](https://github.com/OpenRCT2/OpenRCT2/assets/71702374/0c1764fa-f3c2-45d9-be74-87777724e47f)

commit 26d65b3:
![image](https://github.com/OpenRCT2/OpenRCT2/assets/71702374/0bf9af47-226f-477b-8393-d06f60e072cc)

### Steps to reproduce

Load BluetifulMonday's PCC entry in commit 26d65b3.
A multidimension coaster appears where there was none before this version.

### Attachments

[PCC1_bluetiful_monday.zip](https://github.com/OpenRCT2/OpenRCT2/files/14898233/PCC1_bluetiful_monday.zip)

**Comment by Gymnasiast** [comment] 2024-04-07 18:02
This is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/21731. Please see that issue for more information, as well as the fix (which needs testing).

**Closed by Gymnasiast** 2024-04-07 18:02 UTC
Labels: bug
