### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#3730] opened 2016-05-25 11:37 UTC
**OS: Windows 10** 
**Version: 0.0.5** 
**Commit: 714baf2** 

Unknown Crash during normal gameplay, fast forward through the period can avoid the issue to happen.

**Dump file**
[UnknownCrash.zip](https://github.com/OpenRCT2/OpenRCT2/files/572704/UnknownCrash.zip)

**Comment by janisozaur** [comment] 2016-11-04 21:36
@Nubbie can you please check what's in that dump, please?

**Comment by Nubbie** [comment] 2016-11-05 18:14
@Janisozaur can do it tomorrow on sunday, so will do later on

**Comment by Nubbie** [comment] 2016-11-06 22:55
@janisozaur 
Error message;
Unhandled exception at 0x609EEF07 (openrct2.dll) in 236d61ea-f556-4db9-9af2-d264a0a97923(714baf2).dmp: 0xC0000005: Access violation writing location 0x0A06D11C.

**Call stack**
```
>	openrct2.dll!ttf_draw_string_raw_ttf(rct_drawpixelinfo * dpi, const char * text, text_draw_info * info=0x000dfc5c) Line 1012	C
 	openrct2.dll!ttf_process_glyph_run(rct_drawpixelinfo * dpi=0x000dfd00, const char * text=0x0141ed6b, text_draw_info * info=0x000dfc5c) Line 1181	C
 	openrct2.dll!ttf_process_string(rct_drawpixelinfo * dpi=0x000dfd00, const char * text, text_draw_info * info=0x000dfc5c) Line 1201	C
 	openrct2.dll!ttf_draw_string(rct_drawpixelinfo * dpi=0x000dfd00, char * text=0x0141ed68, int colour=254, int x=555, int y=646) Line 1277	C
 	openrct2.dll!gfx_draw_string_centred_wrapped(rct_drawpixelinfo * dpi=0x000dfd00, void * args, int x=594, int y=652, int width=200, int format=1162, int colour=0) Line 370	C
 	openrct2.dll!window_map_tooltip_paint(rct_window * w=0x60f28b40, rct_drawpixelinfo * dpi=0x000dfd00) Line 155	C
 	openrct2.dll!window_draw(rct_window * w=0x60f27d00, int left=384, int top=576, int right=768, int bottom=648) Line 1543	C
 	openrct2.dll!gfx_redraw_screen_rect(short left=384, short top, short right, short bottom=648) Line 355	C
 	openrct2.dll!gfx_draw_dirty_blocks(int x=3, int y=9, int columns=3, int rows=2) Line 325	C
 	openrct2.dll!gfx_draw_all_dirty_blocks(...) Line 296	C
 	openrct2.dll!window_update_all(...) Line 161	C
 	openrct2.dll!rct2_draw(...) Line 284	C
 	openrct2.dll!openrct2_loop(...) Line 458	C
 	openrct2.dll!openrct2_launch(...) Line 324	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x01572f57, int nCmdShow=1) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Locals;**
```
		colour	187 '»'	unsigned char
		dpi	Variable is optimized away and not available.	
		drawX	Variable is optimized away and not available.	
		drawY	Variable is optimized away and not available.	
+		dst	0x0a06cd62 <Error reading characters of string.>	unsigned char *
		dst_orig	Variable is optimized away and not available.	
		dstScanSkip	876	int
		fontDesc	Variable is optimized away and not available.	
		height	2	int
+		info	0x000dfc5c {startX=555 startY=555 x=633 ...}	text_draw_info *
		overflowX	Variable is optimized away and not available.	
		overflowY	Variable is optimized away and not available.	
		skipX	Variable is optimized away and not available.	
		skipY	Variable is optimized away and not available.	
+		src	0x0915bc60 <Error reading characters of string.>	unsigned char *
		src_orig	Variable is optimized away and not available.	
		srcScanSkip	2	int
+		surface	0x015903d0 {flags=??? format=??? w=??? ...}	SDL_Surface *
		text	Variable is optimized away and not available.	
		width	78	int
```

**Autos;**
```
+		dst	0x0a06cd62 <Error reading characters of string.>	unsigned char *
		dstScanSkip	876	int
+		info	0x000dfc5c {startX=555 startY=555 x=633 ...}	text_draw_info *
+		info->palette	0x000dfc78 ""	unsigned char[8]
		info->palette[3]	10 '\n'	unsigned char
+		src	0x0915bc60 <Error reading characters of string.>	unsigned char *
		width	78	int
```

Think I have seen it before

**Comment by janisozaur** [comment] 2016-11-07 21:48
Duplicate of #3666

**Closed by janisozaur** 2016-11-07 21:48 UTC
Labels: crash, investigate
