### ISSUE TITLE
Remove scenario locking

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#12301] opened 2020-07-17 13:52 UTC
I think the way scenario locking is implemented is very very VERY weird and should be removed.

## Context

First of all, with “scenario locking” I mean a checkbox in the settings. When enabled, some RCT1 and RCT2 missions start locked and you have to complete more missions to proceed. But only if you have enabled this setting, otherwise, all scenarios are always unlocked.
In RCT1, some scenarios started locked and you have to win scenarios to unlock more.
In RCT2, all scenarios are unlocked from the beginning.
OpenRCT2 tries to do both, i.e. support having both locked scenarios and *not* have locked scenarios …

## List of awkwardnesses

1.: It's a gameplay feature, but it disables itself when scenarios are sorted by difficulty (purely a GUI feature)
2.: In any other game in which you have to “earn” your progress, unlocking all scenarios “for free” would be considered a cheat. In OpenRCT2, it's considered to be a “misc. setting”

I think this behavior doesn't make any sense and is confusing. OpenRCT2 kinda seems to want locked scenarios like in RCT1, but imlpements it in a super awkward and confusing way which doesn't really improve the game. It seems this was only added to bring RCT1 behavior back, but it doesn't really work out.

## Proposal for removal

I suggest to remove this feature completely, and just unlock all scenarios like in RCT2. Why? Because I think this feature, as it stands now, is currently broken by design. I doubt anyone would miss it.

Maybe there is a way to implement scenario locking in a sensible and consistent fashion, but until such solution is found, it's better to *not* have this broken-by-design feature.

**Comment by duncanspumpkin** [comment] 2020-07-17 13:55
There is a large proportion of users that wasn't both options hence why both options are available.

**Comment by AaronVanGeffen** [comment] 2020-07-17 14:08
As the developer who originally introduced it in #2575, I am against removing this. I like playing the game with the reward of unlocking scenarios, as it was originally conceived. Indeed, RCT Classic employs the same mechanism.

To be honest, I am a little taken aback by the hostile approach to this issue. Evidently, you don't like playing scenarios in unlock mode. That's fine — that's why it was made optional from the get-go. You can completely ignore it. That's not broken, that's by design.

Let the player choose how they like to play the game.

**Comment by Wuzzy2** [comment] 2020-07-17 14:55
Did you read what I wrote?

> Evidently, you don't like playing scenarios in unlock mode.

This is completely false. My issue is NOT that this feature exists, but my issue is that this feature is (IMHO) implemented rather shoddily, namely:

> 1.: It's a gameplay feature, but it disables itself when scenarios are sorted by difficulty (purely a GUI feature)
> 2.: In any other game in which you have to “earn” your progress, unlocking all scenarios “for free” would be considered a cheat. In OpenRCT2, it's considered to be a “misc. setting”

Basically, this is poor usability and all very confusing and inconsistent. This issue is about usability, NOT about making the game easier or harder. I am NOT... I repeat: NOT against the idea of the feature itself. I am concerned the behavior of this feature is just very inconsistent. Like a design flaw.

> Let the player choose how they like to play the game.

Again, you're missing the point. The reason why I suggest to remove it is because it's implemented in a very weird fashion (see first post) that feels broken by design. The alternative would be to actually improve this.

Since removal of this feature has been officially rejected, how about this?:

1.: Categorize free scenario unlocking of scenarios as a cheat, not as a “misc.” setting
2.: Make scenario unlocking functional in both scenario sorting modes (it doesn't make sense that all your scenarios automatically unlock only because you sort them differently)

**Comment by AaronVanGeffen** [comment] 2020-07-17 15:05
You have previously raised discussion around unlocking mode not working when scenarios are grouped by difficulty in #4009. The reasons for this choice still haven't changed.

I am not saying the system is perfect as-is. However, once enabled, I do believe it performs consistently throughout. The inverse is not a cheat; it is simply a different mode of playing the same scenarios — the vanilla RCT2 approach, if you will.

**Comment by Wuzzy2** [comment] 2020-07-17 15:29
Well, in #4009 I have explained how the unlocking would work in the other sorting mode (basically: the same as in the default sorting mode, i.e. the same scenarios are unlocked, the difference is only a GUI change). And it was closed after only a single reply to the first post, but no comment after my 2nd post.

**Comment by frutiemax** [comment] 2020-07-17 15:33
I suggest to put the unlock all scenarios as a cheat, it shouldn't be considered as an option.

**Comment by AaronVanGeffen** [comment] 2020-07-17 15:47
How do you propose that would work? Cheats work in-game, that is within the scope of a scenario. Anything that affects the game's functionality _outside_ of that should really just be an option… Otherwise it will be far more confusing than the current situation.

**Comment by frutiemax** [comment] 2020-07-17 15:50
In game cheats and scenario progress cheats should be two things.

**Comment by Wuzzy2** [comment] 2020-07-17 15:55
Add a cheat tab in the settings. Could be used for other “cheaty” things, like activating the cheat button in the toolbar, or early scenario win (but this is slightly OT). Why do you think it would be more confusing?

Just because this feature is not effective for a particular scenario does not mean it cannot be considered a cheat.

**Comment by frutiemax** [comment] 2020-07-17 16:01
If you check the Cheats options in the Toolbar section of the options tab, show a Unlock All Scenarios checkbox in the green zone:
![scenarioUnlock](https://user-images.githubusercontent.com/12629817/87806580-19c66900-c825-11ea-9f50-2a8231ea61c0.png)

**Comment by Umdlye** [comment] 2020-07-17 17:30
> 1.: It's a gameplay feature, but it disables itself when scenarios are sorted by difficulty (purely a GUI feature)
This is already made clear to the user by having it greyed out when the "difficulty level" sorting is selected, I don't see why this is grounds for removing this feature.

> 2.: In any other game in which you have to “earn” your progress, unlocking all scenarios “for free” would be considered a cheat. In OpenRCT2, it's considered to be a “misc. setting”
The game uses difficulty level sorting without locks by default AFAIK since that's RCT2's default behaviour, following that logic playing the game as intended would constitute cheating.

**Comment by pizza2004** [comment] 2020-07-17 19:20
This whole issue feels like it is based on the premise that we want difficulty unlocking to be the expected mode of play.  Really it's just in there to allow people who prefer RCT1 behavior to have that behavior.  This really feels like you're making a mountain out of a molehill.  If anything it just sounds like you think the game is bad if it doesn't force people to earn their scenarios.

**Comment by Gymnasiast** [comment] 2020-07-17 19:36
@frutiemax There is no green zone if you there are RCT1, AA and LL scenarios present.

> I suggest to remove this feature completely, and just unlock all scenarios like in RCT2. Why? Because I think this feature, as it stands now, is currently broken by design. I doubt anyone would miss it.

**I** would miss it, for a start. And I *know* I am not the only one, because was specifically requested quite a few times.

> Maybe there is a way to implement scenario locking in a sensible and consistent fashion, but until such solution is found, it's better to not have this broken-by-design feature.

I disagree with the premise this is broken-by-design. As evident from several other comments in this thread, I am not the only one. Meanwhile, you are stating this as if it's a fact while it's only your opinion.

Now, since it seems there is little appetite for your idea and the discussion isn't very pleasant in the first place, I will close this.

-------

I also have to say this: all of your issues are written in a quite aggressive tone. This is *really* starting to get on our nerves now. There is no need to act like this. I already [warned you about this](https://github.com/OpenRCT2/OpenRCT2/issues/10194#issuecomment-607480993) once. Since that hasn't worked, I will have be more clear. You have two choices: either you clean up your act and do away with the confrontational, aggressive and arrogant approach, or you continue with it and see what the consequences are. Choose wisely.

**Closed by Gymnasiast** 2020-07-17 19:36 UTC
Labels: discussion, user interface
