### ISSUE TITLE
Placement messages have mixed strings

### ISSUE THREAD

**Issue by S-Joao-V** [OpenRCT2/OpenRCT2#7439] opened 2018-04-23 13:08 UTC
OS: Linux
Version:0.1.2 x86-64 2018-03-18
Commit/Build: Could not find in-game

Explanation of the issue
<"Can't construct here..." "X"> messages sometimes have errors.
During gameplay I tried to find placement for a rollercoaster, clicking around and not noticing a stall, I tried anyway but in the place of the X the error message a thought from a guest apeared, so: <"Can't construct here:" "this hot dog from stall 1 is tasty" in the way>. It happened again in diferent scenarios where a tought about a ride showed up.
Before opening the issue I tried to reproduce again placing (both situations at the same time) a ride over another ride and in inpropper terrain and "undefined string" was in place of X.

- [ ] Reproducible in RCT2 (vanilla)? Cant boot it currently
- [ ] Specific to multiplayer? I only play single player

**Steps to reproduce:**
1. Try to place ride over ride / stall
2. Placement message can have error

Screenshots

![error_message](https://user-images.githubusercontent.com/30469363/39127963-eb491882-46dc-11e8-8169-bb30233d1694.png)

**Comment by Gymnasiast** [comment] 2018-04-23 13:41
Does it _only_ happen with error messages where the top message is "Can't construct this here...", or with other messages as well?

**Comment by S-Joao-V** [comment] 2018-04-23 13:59
Just ride placement messages, in footpath/money some others things are fine.
Maybe it could be caused by mixed language settings (only if my OS has a say in what language is used as in money:native, language:EN). I can play latter using another lang to check it.

**Comment by Gymnasiast** [comment] 2018-04-23 14:16
It's not likely to be related to what language you're playing OpenRCT2 in.

**Comment by duncanspumpkin** [comment] 2018-04-23 15:42
It will be a game command not setting the error message. Is it only happening on tracks with scenery? Hopefully not cause if it is the search space is much bigger.

**Comment by S-Joao-V** [comment] 2018-04-23 21:53
For the "undefined", managed to see it with both scenery and none.
Tried to reproduce the guest thought one, no luck, will try to play normally and find it again.
For the "undefined", I managed to see it happening in 2 situations:
1 - Tried to place ride over map scenary (only barrier for successful placement ), screenshot attached and scenario (not sure if the object is native or imported from the map).
[RCT2 Roman Village.zip](https://github.com/OpenRCT2/OpenRCT2/files/1940160/RCT2.Roman.Village.zip)
![roman_sc](https://user-images.githubusercontent.com/30469363/39155203-60dec188-4727-11e8-94ac-b8b6f46c3dea.png)

2 - a. Tried to place half inside, half outside owned land, with pointer out of park boundary = "not owned!" message
2 - b. Same situation, but w/ pointer inside =  <"cant place..." undefined>

**Comment by duncanspumpkin** [comment] 2018-04-24 12:05
Okay sounds like the problem will be in the track placement code. Not the scenery code. Which is good. Error will be because the string arguments have not been properly set or the wrong error message has been used.

**Comment by qwertychouskie** [comment] 2018-04-25 20:32
Seems to be the same issue as https://github.com/OpenRCT2/OpenRCT2/issues/7397.

**Comment by RogoDarius** [comment] 2018-05-29 19:47
![image](https://user-images.githubusercontent.com/12530301/40681515-4387f7aa-6381-11e8-9809-c3098c8630c0.png)
This image was taken from yesterday's build (0.1.3 617372f Windows x64)
You can reproduce the problem by trying to place a circus here in Harmonic Hills (Added Attractions)
Looks like the bug that was fixed is a different issue as this "undefined string" can still occur.

**Comment by AaronVanGeffen** [comment] 2018-10-22 06:04
With #8130 merged, does this still happen?

**Comment by AaronVanGeffen** [comment] 2018-10-22 06:04
With #8130 merged, does this still happen?

**Comment by AaronVanGeffen** [comment] 2018-10-22 06:06
Does this still happen now that #8130 has been merged?

**Comment by AaronVanGeffen** [comment] 2018-10-22 08:56
Does this still happen now that #8130 has been merged?

**Comment by Broxzier** [comment] 2018-11-19 20:33
I haven't seen any reports about this recently, and cannot reproduce it myself either.

**Comment by ALEEF02** [comment] 2019-03-10 06:58
Not fixed, happened to me today March 9th. I can't place any food stands
![image](https://user-images.githubusercontent.com/12904259/54081757-c3efc180-42be-11e9-8728-18f04fb54a9b.png)

**Comment by duncanspumpkin** [comment] 2019-03-10 07:28
Can you reliably reproduce this?

**Comment by duncanspumpkin** [comment] 2019-03-10 08:17
All game actions should have an accessible ErrorTitle. Otherwise you will get (undefined string) when not enough money.

**Comment by tupaschoal** [comment] 2020-10-01 03:56
I haven't been able to reproduce this with v0.3.1. Please reopen if you can

**Closed by tupaschoal** 2020-10-01 03:56 UTC
Labels: bug
