### ISSUE TITLE
Floating park entrance ghost

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#11160] opened 2020-03-30 21:25 UTC
**Version:** 0.2.5 release and current `develop`
**Commit/Build:** 3d223b084

A picture story by @steamroll

![Screenshot-2020-03-30-16 59 17](https://user-images.githubusercontent.com/550290/77963392-9288d000-72dd-11ea-884e-1e4ea65802cc.png)
![Screenshot-2020-03-30-16 59 24](https://user-images.githubusercontent.com/550290/77963401-974d8400-72dd-11ea-9cec-a4c5085dba1f.png)
![Screenshot-2020-03-30-16 59 31](https://user-images.githubusercontent.com/550290/77963404-99afde00-72dd-11ea-8036-787e73d3a3de.png)
![Screenshot-2020-03-30-16 59 38](https://user-images.githubusercontent.com/550290/77963409-9c123800-72dd-11ea-8321-47af0c20242e.png)
![Screenshot-2020-03-30-16 59 42](https://user-images.githubusercontent.com/550290/77963417-9e749200-72dd-11ea-88f1-ee8639ddc4b5.png)
![Screenshot-2020-03-30-16 59 44](https://user-images.githubusercontent.com/550290/77963431-a2081900-72dd-11ea-80c0-31f5499fa73d.png)
![Screenshot-2020-03-30-16 59 51](https://user-images.githubusercontent.com/550290/77963437-a5030980-72dd-11ea-93dd-cee2951d8b24.png)
![Screenshot-2020-03-30-16 59 57](https://user-images.githubusercontent.com/550290/77963450-a9c7bd80-72dd-11ea-84f1-42dbadbd4103.png)
![Screenshot-2020-03-30-17 00 04](https://user-images.githubusercontent.com/550290/77963456-ac2a1780-72dd-11ea-8fa4-e931ce6d962e.png)

**Comment by janisozaur** [comment] 2020-03-31 07:51
Bisected to be13c1fc87eaee50c0425a843af6b89698cb8f59 (#10875)
```
commit be13c1fc87eaee50c0425a843af6b89698cb8f59
Author: Michael Steenbeek <m.o.steenbeek@gmail.com>
Date:   Sat Mar 7 21:07:18 2020 +0100

    Refactor more TileCoords
```

**Comment by Gymnasiast** [comment] 2020-03-31 12:18
[This line](https://github.com/OpenRCT2/OpenRCT2/commit/be13c1fc87eaee50c0425a843af6b89698cb8f59#diff-00daf4f370a36f1497a476d3836f6ad5R80) looks suspicious in particular...

**Comment by Gymnasiast** [comment] 2020-03-31 12:20
Also, this issue seems to be a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/10951.

**Closed** 2020-03-31 12:47 UTC
Labels: bug, regression
