### ISSUE TITLE
0.41: Go Karts missing from Track Designer

### ISSUE THREAD

**Issue by Jigsy1** [OpenRCT2/OpenRCT2#17637] opened 2022-07-28 22:13 UTC
Pretty much it.

Every other track building ride appears in Track Designer (including Roto-Drop, Launched Freefall, etc.) but Go Karts is the only one that's missing.

**Comment by ocalhoun6** [comment] 2022-07-28 23:38
Go karts has no test mode -- it can only do a test run if it has guests.

Ride designs can only be saved after a successful test run. And the ride designer has no guests.

So you could build a Go Karts in the ride designer, but you could never test it and therefore you could never save the design.

-----

There are a couple ways this could be fixed:

- Allowing a park entrance and guests in the ride designer
- Giving the Go Karts (and other guest-dependent rides) test modes that run without guests ... at least in the ride designer.

But neither of these solutions is as quick and simple as just adding an entry to allow Go Karts in the ride designer.

----

For now, it's probably best to just build and test your Go Karts designs in a sandbox park instead of the ride designer. Then guests can ride it, it can be tested, and you can save the design.

**Comment by Jigsy1** [comment] 2022-07-28 23:55
Ah, I never took the test->save into consideration. That makes sense...

Guess making a a simple Go Kart Sandbox via Map Editor will have to do.

**Comment by Broxzier** [comment] 2022-07-29 07:31
When filing issues, please use the bug report form, not a blank issue.

This has also been reported before and is not a bug, this is true for all rides where guests are needed to operate the cars, so I'm closing this.

**Closed by Broxzier** 2022-07-29 07:31 UTC
