### ISSUE TITLE
Right-mouse drag speed affected by game speed

### ISSUE THREAD

**Issue by RogoDarius** [OpenRCT2/OpenRCT2#5651] opened 2017-06-18 10:44 UTC
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** e9038e5

When the game speed is set to "Turbo Speed" the camera notably pans faster when dragging with right mouse.

- [No] Reproducible in RCT2 (vanilla)?
- [N/A] Multiplayer?

**Steps to reproduce:**
1. Go to a park
2. Drag the camera around with the right mouse button (observe speed)
3. Hold + or set the game speed to Turbo Speed
4. Drag the camera around with the right mouse button (observe speed increase)

**Comment by janisozaur** [comment] 2017-06-18 10:48
Duplicate of #5647

**Closed by janisozaur** 2017-06-18 10:48 UTC
