### ISSUE TITLE
Guest status strings used for guest list

### ISSUE THREAD

**Issue by groenroos** [OpenRCT2/OpenRCT2#15453] opened 2021-09-21 02:52 UTC
The guest status strings (`STR_1431` thru `STR_1448`) - for example, `Queuing for {STRINGID}`, seem to be intended to be used in isolation, in the status bar of a guest window, and in the Actions list of the Guests window:

<img width="286" alt="Screenshot 2021-09-21 at 03 49 40" src="https://user-images.githubusercontent.com/951547/134104295-fc0a2e56-969c-46d1-bb1b-50bc3474e034.png">

However, it's also used for `STR_1820` (`Guests {STRINGID}`) - the heading in the Guests window after selecting a grouped Action from the "All guests (summarised)" tab:

<img width="379" alt="Screenshot 2021-09-21 at 03 28 58" src="https://user-images.githubusercontent.com/951547/134103076-a20b4e50-a246-44a3-bc2a-efa71aa239f6.png">

By grammatical happenstance, this interpolation still works in English, save for the inelegant capital letter, which could maybe be passed off as being in title case.

<img width="415" alt="Screenshot 2021-09-21 at 03 29 25" src="https://user-images.githubusercontent.com/951547/134103193-c47deb44-8c87-41b4-90af-26c09d5e4a81.png">

In `fi-FI`, however, the same heading does not work grammatically, because:

1. The verb "queuing" must be pluralised when it's many "Guests" rather than just some particular guest
2. The action must be explicitly written as a clause ("Guests **_who are_** Queuing") - but the words for this will be slightly different for each action, so it cannot simply be added into `STR_1820`
3. There is no concept of title case in `fi-FI`, so the random capitalisation of the first word of the action looks really out of place

As a result, this heading in `fi-FI` currently says the equivalent of "Guests do be Queuing for the attraction Woodpecker" - which is both an oddly casual tone, and not exactly the original intention of the heading.

**Solution:** The guest status strings `STR_1431` thru `STR_1448` should be duplicated, with the new set of strings used exclusively for interpolating in `STR_1820` (`Guests {STRINGID}`).

**Comment by Gymnasiast** [comment] 2021-09-21 08:37
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/1514.

**Closed by Gymnasiast** 2021-09-21 08:37 UTC
Labels: localisation
