### ISSUE TITLE
[Bug] Zooming in void zone moves the camera at the wrong location

### ISSUE THREAD

**Issue by frutiemax** [OpenRCT2/OpenRCT2#12276] opened 2020-07-15 18:27 UTC
Zooming in the void zone when dezoomed moves the camera at the incorrect location.

- Put ANY scale
- Open Create you six flags magic mountain scenario
- Zoom out
- Zoom in the void zone (black zone)

It will recenter the view at the wrong location.
This bug does not occurs in vanilla game.

EDIT- It's there in v0.2.3 and perhaps even before...

**Comment by AaronVanGeffen** [comment] 2020-07-15 18:29
Duplicate of #11623

**Comment by frutiemax** [comment] 2020-07-15 18:32
I'll try to bisect this.

**Closed** 2020-07-17 08:11 UTC
Labels: duplicate
