### ISSUE TITLE
Bugged Lift Cabins on Loading SV6

### ISSUE THREAD

**Issue by maddkattunge** [OpenRCT2/OpenRCT2#10806] opened 2020-02-21 18:45 UTC
**OS:** Windows 10
**Version:** 0.2.4 develop (also on release)
**Commit/Build:** 12ab1e9

Short Lifts composed of only two station tracks with no other track in between will bug out upon opening the park's SV6 save file. The Lift cabin will not stop at Station 2 and will instead immediately reverse direction to then be caught in an infinite loop bouncing between stations.

- [No] Reproducible in RCT2 (vanilla)?
- [No] Specific to multiplayer?

**Steps to reproduce:**
1. Build a Lift composed of only two stations.
2. Operate Lift in either Test or Open mode.
3. Save and reload.

**Video:**
https://www.youtube.com/watch?v=3jXRMtOiYn0

**Save game:**
[mxi_bug_1_brokenlift.zip](https://github.com/OpenRCT2/OpenRCT2/files/4237478/mxi_bug_1_brokenlift.zip)

**Comment by Gymnasiast** [comment] 2020-02-21 19:38
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/2128.

**Comment by maddkattunge** [comment] 2020-02-22 00:23
This does not happen in Vanilla RCT2 and I do not understand how this is a duplicate of the #2128  Chairlift bug since these are two different rides. Could you help me understand why this is a duplicate bug report?

**Comment by duncanspumpkin** [comment] 2020-02-22 07:31
I think on first read of your issue it sounded like it was talking about chairlifts. I see from your video it is talking about lifts though.
Either way its still a duplicate but this is actually a duplicate of this issue: https://github.com/OpenRCT2/OpenRCT2/issues/10509

**Comment by Gymnasiast** [comment] 2020-02-22 10:32
@maddkattunge I misread it, my bad.

@duncanspumpkin I'm not sure if it's a duplicate of that - #10509 has a "normal" lift.

**Closed** 2020-04-11 08:20 UTC
Labels: investigate
