### ISSUE TITLE
Key names are not translated

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#10145] opened 2019-10-26 14:47 UTC
**OS:** GNU/Linux
**Version:** 0.2.3-462
**Commit/Build:** e9bcad1

- [ ] Reproducible in RCT2 (vanilla)? I don't know.
- [ ] Specific to multiplayer? No.

**Description:**
The special key names like “Delete”, “Page up”, “Backspace”, etc. in the key binding window are not translated, despite having translations available in the language files.
However, CTRL and SHIFT keys are translated (as part of key combinations).

**Steps to reproduce:**
1. Select German
2. Open the key binding window
3. Look for keys like Delete Page up, Backspace, etc.

**Comment by cskrisz** [comment] 2019-10-26 15:34
Translations for those seem to be unimplemented. See [StringIds.h](https://github.com/OpenRCT2/OpenRCT2/blob/e9bcad193ac098ecd8bb73db6fbb24fb94dd86b3/src/openrct2/localisation/StringIds.h#L1932-L2086).

**Comment by IntelOrca** [comment] 2019-10-26 17:54
Duplicate of #1164

**Closed** 2019-10-26 18:14 UTC
Labels: duplicate
