### ISSUE TITLE
Cheat: Allow construction/modification of ride while it's open

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#3240] opened 2016-04-04 02:55 UTC

**Comment by Superjustinbros** [comment] 2016-04-04 04:58
I wouldn't really see any benefit form such a feature tbh, unless you're making a shuttle coaster and want to trim it to just the right length without visual inspection or painting the last piece of track the train goes over.

**Comment by Gymnasiast** [comment] 2016-04-04 07:51
I don't see much benefit either. And it's likely to cause several glitches. I don't think the trade-off is worth it.

**Comment by janisozaur** [comment] 2016-04-04 08:32
I would consider this to be a dupe of https://github.com/OpenRCT2/OpenRCT2/issues/485

**Comment by jensj12** [comment] 2016-04-04 11:56
If you just don't want the guests to leave the queue, do it while paused. Trains will be reset though.

An explanation of the use case you see would be helpful when posting suggestions.

**Comment by Margen67** [comment] 2016-04-04 19:26
I like opening a ride, then deleting a part of the track so I can make it crash while guests are on it.
This also works on rides that don't normally crash, like Mini Golf.

**Comment by Gymnasiast** [comment] 2016-04-05 07:02
I'm afraid that is way too little benefit for the amount of trouble it will cause.

**Closed by Gymnasiast** 2016-04-05 07:02 UTC
Labels: discussion, vetoed
