### ISSUE TITLE
Game keeps crashing on Multiplayer

### ISSUE THREAD

**Issue by xzalek25** [OpenRCT2/OpenRCT2#4776] opened 2016-11-08 22:06 UTC
**OS:** [e.g. Windows 10]
**Version:** [0.0.5]
**Commit/Build:** [1649]

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Crashes at multiplayer when I click the multiplayer settings button on my own server.
2. Multiplayer settings button works on other servers.

**Dump file**

**Screenshots / Video:**

![crashreport1](https://cloud.githubusercontent.com/assets/23346778/20119169/79b9c044-a5d5-11e6-8fec-18d5c25bbe15.PNG)

**Save game:**

![crashreport1](https://cloud.githubusercontent.com/assets/23346778/20119208/a374f336-a5d5-11e6-9f05-9a8f168d6b5a.PNG)

**Comment by janisozaur** [comment] 2016-11-09 07:34
duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/4684 you have not bothered to search at all.

Also: do not post screenshots of this message, this prevent search from functioning.

**Closed by janisozaur** 2016-11-09 07:34 UTC
Labels: duplicate, invalid/incomplete

**Comment by xzalek25** [comment] 2016-11-09 12:27
I looked at the other case. It's not a duplicate to my problem. It's still having the same problem even with today's build. Is there any possibility that you can investigate the issue? The commit number is 33749cc.
