### ISSUE TITLE
when saving a track design with black elevated path and dirt path, saved design changes to brown elevated path

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#18754] opened 2022-12-03 02:52 UTC
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.2-211-g7602eb6 (7602eb6 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

![error](https://user-images.githubusercontent.com/94884086/205418953-7a837608-3300-4d38-b2d3-160e8b6bf209.png)
the save track design with scenery feature alters the black elevated path to brown elevated path when loading a track design with black elevated path that was built with dirt flat path selected in the pathing tool

### Steps to reproduce

build elevated ride and build exit path  with the pathing tool set to dirt flat path and black elevated path, then save the design and try to place it, the black elevated path will change to brown elevated path

**Comment by duncanspumpkin** [comment] 2022-12-03 20:08
Limitation of the td6 format causes it to guess the path type. Until we create a new format for track designs this will happen

**Comment by Gymnasiast** [comment] 2022-12-06 10:29
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/17225.

**Closed by Gymnasiast** 2022-12-06 10:29 UTC
Labels: bug
