### ISSUE TITLE
Invisible track pieces

### ISSUE THREAD

**Issue by Venom-DO** [OpenRCT2/OpenRCT2#5428] opened 2017-05-02 18:03 UTC
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 2b54032

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build lay-down coaster with said track pieces

**Dump file**

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/28310785/25632204/14660554-2f73-11e7-99a8-8c3265458326.png)

. -->

**Save game:**

**Comment by janisozaur** [comment] 2017-05-02 18:11
I don't understand what this report is about. Please elaborate.

**Comment by IntelOrca** [comment] 2017-05-02 18:45
@janisozaur presumably the track pieces are being drawn after constructing them.

**Comment by Gymnasiast** [comment] 2017-05-02 18:46
I think it's the same issue as this: https://github.com/OpenRCT2/OpenRCT2/issues/4991

**Comment by IntelOrca** [comment] 2017-05-02 18:49
So duplicate?

**Comment by Gymnasiast** [comment] 2017-05-03 07:27
Yes, this is a duplicate of #4991.

**Closed by Gymnasiast** 2017-05-03 07:27 UTC
