### ISSUE TITLE
In the latest development version Scenaio names and money settings are not saved.

### ISSUE THREAD

**Issue by EraYaN** [OpenRCT2/OpenRCT2#4466] opened 2016-09-20 23:55 UTC
**OS:** Windows 10 x64
**Version:**v0.0.5
**Commit/Build:** 843d865
**RCT2 revision:** Steam BuildID 330047

Regression from 0.0.4 -> 0.0.5

**Steps to reproduce:**
1. Make a custom scenario and on the last dialog enter the name of the park and the scenario name.
2. Save to random file.
3. Start new park and try to find your scenario.

This did work in 0.0.4 (latest stable). So I edited my scenarios in 0.0.4 and then reinstalled 0.0.5, but it's still a shame.

But if you pick a scenario in the object lists to base it off from, you can not edit the title. Besides the first 10 or so have no name at all. It also does not save the state of the "No Money" tick and the Start capital, other amounts ARE saved.

If needed I can make a video.

**Comment by Gymnasiast** [comment] 2016-09-21 06:57
Yes, a video or a few screenshot would probably help.

**Comment by Androgeos** [comment] 2017-02-07 15:15
Not sure if this is related, but in build 546aace, loading a saved landscape in the Scenario Editor causes the Financial Options to default to No Money.

**Steps to reproduce:**
1. Create a new landscape using the Scenario Editor
2. Develop the new landscape until you are able to advance to Options Selection
3. Adjust Financial Options as you see fit
4. Save the landscape
5. Load the landscape you just saved
6. Advance to Options Selection; the "No Money" option should be checked regardless of your last settings
7. Uncheck "No Money", your previous settings are left intact
8. Repeat Steps 4 to 6

Here's a video of me showing this bug in effect:
https://www.youtube.com/watch?v=X1W0yPeAhbQ

**Comment by Gymnasiast** [comment] 2020-07-30 18:37
This is a bit of an odd issue. The no money bug bit is clear and is also described in #7969. This bug should be fixed by https://github.com/OpenRCT2/OpenRCT2/pull/12520.

This issue also mentions something about naming, but the description is so unclear I cannot even understand what the OP is trying to say. I'm going to assume this bit has been solved, considering it has been reported a long time ago and OpenRCT2 has been extensively refactored since then. If such a bug is still occurring, feel free to open a new bug report.

**Closed by Gymnasiast** 2020-07-30 18:37 UTC
Labels: investigate

**Comment by EraYaN** [comment] 2020-08-04 15:54
Wow, this is an old one. I'll have a go at reproducing it somewhere this week and confirm if this is fixed.

**Comment by EraYaN** [comment] 2020-08-07 08:50
Alright this is indeed fixed the park name i now preserved as are all other settings I could quickly verify. I did find some other problem, but it's unrelated.
