### ISSUE TITLE
Flickering and wrong tiles highlighted when placing ride entrances

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2272] opened 2015-11-10 10:49 UTC
Notice the flickering tile when placing the entrance/exit
![gif](http://i.imgur.com/4YlasWK.gif)

The entire highlight seems to have an offset when moving the exit
![gif](http://i.imgur.com/UWTbCYR.gif)

Edit:
The highlight also doesn't seem to take the rotation into account:
![scr](http://i.imgur.com/85xfKWB.png)

**Comment by IntelOrca** [comment] 2015-11-10 10:54
Similar or duplicate of #1324.

**Comment by duncanspumpkin** [comment] 2015-11-10 12:03
Yeah its a weird original bug that might be able to be fixed now.

**Comment by osconnoisseur** [comment] 2015-11-12 16:59
What did you use to record that GIF? That's pretty nice!

**Comment by Broxzier** [comment] 2015-11-13 11:44
@osconnoisseur Camtasia Recorder 7 with the lossless codec that you can download from their website. Saved it as uncompressed AVI, then converted it to gif.

**Comment by Patrik356b** [comment] 2015-11-13 14:37
If you want to avoid the video-file conversion step, i suggest looking at this: https://screentogif.codeplex.com/
Sample of roller coaster recording: http://puu.sh/jRYXg/7ea3004aaf.gif (My own design)

**Comment by duncanspumpkin** [comment] 2020-10-06 17:24
I'm closing this as a duplicate of #1324. Its all getting fixed in #13098 anyway.

**Closed by duncanspumpkin** 2020-10-06 17:24 UTC
Labels: original bug
