### ISSUE TITLE
Add console command to strip out unused objects

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5820] opened 2017-07-07 13:43 UTC

**Comment by rwjuk** [comment] 2017-07-07 13:47
One use case: stripping objects from parks used in the title sequence makes them load faster.

**Comment by Gymnasiast** [comment] 2017-07-07 13:51
It will still support commands like these, unless I'm _very_ mistaken. (Can you confirm this @IntelOrca ?)

**Comment by rwjuk** [comment] 2017-07-07 13:52
Oh in that case yeah, a console command is fine.

**Comment by IntelOrca** [comment] 2017-07-07 16:14
Duplicate of #1329

**Comment by rwjuk** [comment] 2017-07-07 16:17
Closing as dupe of #1329.

**Closed by rwjuk** 2017-07-07 16:17 UTC
Labels: feature
