### ISSUE TITLE
Game crashes upon startup

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3948] opened 2016-06-24 17:19 UTC
[Crash June 24.zip](https://github.com/OpenRCT2/OpenRCT2/files/332166/Crash.June.24.zip)
Build is develop-080f470

**Comment by Gymnasiast** [comment] 2016-06-25 13:06
Would you mind putting a proper description rather than 'Game bricks up upon lunch'?

**Comment by IntelOrca** [comment] 2016-06-25 13:41
Delete your plugins.dat and try the latest version.

**Comment by Superjustinbros** [comment] 2016-06-25 14:15
![rct2 error](https://cloud.githubusercontent.com/assets/4167951/16357176/5188c7e2-3abd-11e6-83dc-9f8c493128d5.png)
Updated to Build 2e3500e and the problem still continues.
From what I can understand the game never made a Plugin.dat file either.

**Comment by Superjustinbros** [comment] 2016-06-30 03:08
[Crash June 29th.zip](https://github.com/OpenRCT2/OpenRCT2/files/340609/Crash.June.29th.zip)
Build f70d1f4

**Comment by Nubbie** [comment] 2016-06-30 20:28
@Superjustinbros 
Could you run openrct2.exe from the command prompt and with --verbose as an argument?
This mean:

Open a command prompt
cd to the directory where openrct2.exe resides
openrct2.exe --verbose

Can you then right click and copy all the text and paste it in here? (or at least show a screenshot at the end of the text)
(copied from Dev Gymnasiast)

**Comment by Superjustinbros** [comment] 2016-06-30 20:36
Hmm... Could you explain that a bit more to me? What would that result in?

**Comment by Nubbie** [comment] 2016-06-30 20:37
--verbose will just run the program normally but with a lot better de-bugging features, telling us all the stuff being loaded
I suspect a specific file being corrupt which crashes your game

**Comment by Nubbie** [comment] 2016-06-30 21:24
@Superjustinbros 
Have something else you could try to that you should try first (if some plug in is corrupted)

**Number 1:**
1. Move the folder 'Rollercoaster Tycoon 2\**ObjData**' to another location (like the desktop)
2. Delete 'Plugin.dat' in  'Documents\OpenRCT2'
3. Run the game

**Comment by Superjustinbros** [comment] 2016-06-30 21:44
Are you sure that the file 1ATLANT.DAT would've had something to do with the crash? It worked in previous versions of OpenRCT2 and didn't crash the game as far as I remember.
[Crash June 30th.zip](https://github.com/OpenRCT2/OpenRCT2/files/342421/Crash.June.30th.zip)
It still continues to crash into build 09863a4

**Comment by Nubbie** [comment] 2016-06-30 21:48
I'm not sure and don't think anyone is either, we're trying to find a solution tho
Have now opened up the dump file and noticed it's the same errors as #3958

**Comment by janisozaur** [comment] 2016-06-30 21:53
From https://github.com/OpenRCT2/OpenRCT2/issues/3958#issuecomment-229472673

```
    #1 openrct2.dll!object_chunk_load_image_directory(unsigned char * * chunk=0x000df9b8) Line 477  C
    #2 openrct2.dll!object_type_small_scenery_load(void * objectEntry=0x04788020, unsigned int entryIndex=0) Line 882   C
    #3 openrct2.dll!object_load(int type=1, void * objectEntry=0x04788020, unsigned int entryIndex=0) Line 1624 C
    #4 openrct2.dll!object_load_file(int groupIndex=-1, const rct_object_entry * entry, int * chunkSize=0x000dfb30, const rct_object_entry * installedObject=0x03781fec) Line 143   C
    #5 openrct2.dll!install_object_entry(rct_object_entry * entry=0x000dfb70, rct_object_entry * installed_entry=0x03781fec, const char * path, rct_object_filters * filter=0x000dfb54) Line 802    C
    #6 openrct2.dll!object_list_load(...) Line 348  C
    #7 openrct2.dll!rct2_init(...) Line 167 C
    #8 openrct2.dll!openrct2_initialise(...) Line 243   C
    #9 openrct2.dll!openrct2_launch(...) Line 271   C
    #10 openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x01543157, int nCmdShow=1) Line 109    C
    openrct2.exe!004069e4() Unknown
    [Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]  
    [External Code] 
```

**Comment by janisozaur** [comment] 2016-07-01 05:49
Duplicate of #3916

**Closed by janisozaur** 2016-07-01 05:49 UTC
Labels: crash
