### ISSUE TITLE
Go Karts with 1920s racing cars ultimately gets stuck

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#12879] opened 2020-09-07 16:47 UTC
**OS:** Windows 10
**Version:** 0.3.0
**Commit/Build:** 96d1db9 and 135cc10

After running Go Karts with the 1920s racing cars, the cars get locked up on the track, and one has to reset the ride.

- [ ] Reproducible in RCT2 (vanilla)? _unknown_
- [ ] Specific to multiplayer? _no_

**Steps to reproduce:**
1. Open Schneider Shores scenario in TT
2. Build one or more Go Karts (using 1920s racing cars)
3. Open the ride(s) and run the game for a while
The cars will get stuck on the track.

**Dump file**

**Screenshots / Video:**

**Save game:**
Here's my save with the smaller Go-Kart ride stuck.
[Schneider Shores Troubleshoot.txt](https://github.com/OpenRCT2/OpenRCT2/files/5184070/Schneider.Shores.Troubleshoot.txt)

**Comment by Gymnasiast** [comment] 2020-09-07 18:04
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3588.

**Closed by Gymnasiast** 2020-09-07 18:04 UTC
