### ISSUE TITLE
BACKTRACE 675e0c track_design_mirror_scenery

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8425] opened 2018-12-12 17:59 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/675e0c580747c89a666208abfac4d0048c136c1d6016efb2b50bf4e2b8cbb63f?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Dec 12 2018 17:58:17)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Tboll\\Documents\\OpenRCT2\\646e351b-d1b8-485a-8de8-5abd9ac038b6.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Tboll\\Documents\\OpenRCT2\\646e351b-d1b8-485a-8de8-5abd9ac038b6.sv6.gz: <em>1</em><br><strong>commit:</strong> cf44ea7: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>unhandled-exception</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Object::GetLegacyData -> track_design_mirror_scenery -> window_track_place_mouseup -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 19:50
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8535

**Closed by janisozaur** 2019-02-02 19:50 UTC
Labels: backtrace.io, crash
