### ISSUE TITLE
Some minor issues with the scenario editor.

### ISSUE THREAD

**Issue by Topherroni** [OpenRCT2/OpenRCT2#12501] opened 2020-07-27 15:05 UTC
Fill in the placeholders below. Delete any headings and placeholders that you do not fill in.

MAC 
Ver. 2.6
**Commit/Build:**

Some things in the scenario editor do not save. Most notably, the invention research list does not save.  If you set the research list how you want it, save the scenario and come back to it, it will not be how you left it. It will just go back to the random default order it is set in  Even if you go back to the ride/scenery selection menu, it will reset the invention research list.  

Something else is that the financial option is always set to "no money" no matter how you save your scenario. All you have to do is deselect it but I still thought it was worth mentioning.

If you go to the scenario editor and select a file to edit and select or deselect something from the ride selection menu and save the scenario, and you happen to select a park from the park menu that happens to share the name of the scenario save file, the park will now have the random default research invention ride selection and the no money option. Even if you did not officially save the scenario to the park list

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by ocalhoun6** [comment] 2020-07-27 22:46
Seems like a duplicate of #8175, with a little bit of #7969 mixed in.

That said, as someone who builds a lot of scenarios and then often has to go back and edit them, this is a _huge_ time-waster of a bug, and it would be really awesome if someone could fix it.

When you've carefully curated an invention list, it really sucks to have to completely redo the list anytime you edit the scenario. The money settings are also annoying to redo, but at least there's fewer settings there so it's fairly quick and easy.

But this is by far the OpenRCT2 bug that causes me the most issues, and I really wish there was more interest in solving it.

**Comment by Gymnasiast** [comment] 2020-07-30 18:31
> and I really wish there was more interest in solving it.

@ocalhoun6 Cut that out. You said this twice in one week. Do I need to remind you this is a fucking volunteer project?

**Closed** 2020-07-30 19:43 UTC
Labels: bug
