### ISSUE TITLE
Crash when rotating map

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5762] opened 2017-07-03 06:28 UTC
**OS:** Windows 8.1
**Version:** 0.0.8
**Commit/Build:** cb28381

Sometimes when clicking the rotate map button, the game crashes.
Possibly related to crashes when closing windows with the X button.

**Steps to reproduce:**
1. Build your park, minding your own business
2. Rotate the map. Button or keystroke.
3. Boom. Crash.

**Dump file**
warning large file

dump when clicking button:
https://www.dropbox.com/s/okmekqdupfhpsej/rotate%20button%20crash%20dump.zip?dl=0

dump when pressing the keybind:
coming soon

**Comment by Nubbie** [comment] 2017-07-03 08:55
**Error message;**
none

**Call stack;**
```
 	openrct2.dll!Guard::Assert(bool expression, const char * message=0x00007ffd9d748928, ...) Line 81	C++
>	openrct2.dll!sprite_paint_setup(const unsigned short eax, const unsigned short ecx) Line 46	C
 	openrct2.dll!paint_generate_structs(rct_drawpixelinfo * dpi) Line 699	C
 	openrct2.dll!viewport_paint_column(rct_drawpixelinfo * dpi=0x0000004e298cf8a0, unsigned int viewFlags=1024) Line 746	C
 	openrct2.dll!viewport_paint(rct_viewport * viewport, rct_drawpixelinfo * dpi, short left=-1396, short top, short right=524, short bottom=-1296) Line 729	C
 	openrct2.dll!viewport_render(rct_drawpixelinfo * dpi=0x0000004e298cf9c0, rct_viewport * viewport, int left=0, int top=0, int right=524, int bottom=64240) Line 659	C
 	openrct2.dll!window_main_paint(rct_window * w, rct_drawpixelinfo * dpi) Line 98	C
 	openrct2.dll!window_draw_single(rct_drawpixelinfo * dpi, rct_window * w=0x00007ffd9dddf400, int left, int top, int right=1920, int bottom=1017) Line 1728	C
 	openrct2.dll!window_draw(rct_drawpixelinfo * dpi=0x0000004e298cfa80, rct_window * w=0x00007ffd9dddf400, int left=0, int top=0, int right=1920, int bottom=1017) Line 1623	C
 	openrct2.dll!window_draw_all(rct_drawpixelinfo * dpi, short left, short top, short right, short bottom) Line 584	C
 	openrct2.dll!OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks() Line 401	C++
 	openrct2.dll!OpenRCT2::Drawing::X8DrawingEngine::Draw() Line 228	C++
 	openrct2.dll!HardwareDisplayDrawingEngine::Draw() Line 127	C++
 	openrct2.dll!OpenRCT2::Context::RunVariableFrame() Line 439	C++
 	openrct2.dll!OpenRCT2::Context::RunGameLoop() Line 361	C++
 	openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int argc=698587920, char * * argv=0x0000000002040800) Line 136	C++
 	openrct2.dll!NormalisedMain(int argc=1, char * * argv=0x0000004e299db850) Line 65	C++
 	openrct2.dll!LaunchOpenRCT2(int argc, wchar_t * * argvW) Line 55	C++
 	[External Code]	
```

**Local at like 2;**
```
		dpi	Variable is optimized away and not available.	
		eax	Variable is optimized away and not available.	
		ecx	Variable is optimized away and not available.	
		image_direction	Variable is optimized away and not available.	
		spr	Variable is optimized away and not available.	
		sprite_idx	Variable is optimized away and not available.	
```

**Comment by spacek531** [comment] 2017-07-03 08:56
it appears the method of rotating the camera isn't important (button vs. keybind) so I will hold off on that dump because these are massive files.

**Comment by janisozaur** [comment] 2017-07-03 09:11
Looks related to https://github.com/OpenRCT2/OpenRCT2/pull/5757? Invalid sprite once again

**Comment by IntelOrca** [comment] 2017-07-03 09:22
@janisozaur Different kind of sprite. Unrelated.

**Comment by IntelOrca** [comment] 2017-07-03 19:43
@spacek531 can you upload the saved game that crashes please?

**Comment by spacek531** [comment] 2017-07-03 20:09
It happens in King Park and Maple Springs.

[check for bad elements.zip](https://github.com/OpenRCT2/OpenRCT2/files/1120482/check.for.bad.elements.zip)

**Comment by IntelOrca** [comment] 2017-07-03 21:07
@spacek531 I am struggling to reproduce the crash. Where about in the map does it occur?

**Comment by spacek531** [comment] 2017-07-03 21:49
On King Park, move the camera so it is about centered on the top of the mine train lift hill. At T+25 seconds, rotate the camera.

**Comment by IntelOrca** [comment] 2017-07-03 21:55
I went to the top of the mine train lift hill and kept rotating the camera for a minute, I still can't reproduce the crash.

**Comment by rwjuk** [comment] 2017-07-03 21:56
Just did the same thing, same result (unable to reproduce).

**Comment by IntelOrca** [comment] 2017-07-03 22:04
@spacek531 Perhaps it is to do with your objects, how did you acquire your RCT2 install?

**Comment by spacek531** [comment] 2017-07-03 22:20
It's not consistent at all times.

The content files are copied from an external drive which was imaged from a disk imaging software after the original hard drive crashed. I currently don't have any other way of getting the files.

**Comment by rwjuk** [comment] 2017-07-03 22:21
@spacek531 Download the demo, point OpenRCT2 to that and retest?

**Comment by IntelOrca** [comment] 2017-07-05 11:57
Closing this for #5795, I think its same issue - autosave corrupts sprites.

**Closed by IntelOrca** 2017-07-05 11:57 UTC
Labels: bug, crash
