### ISSUE TITLE
In the map window, there are more peeps flickering than there are selected

### ISSUE THREAD

**Issue by adrian17** [OpenRCT2/OpenRCT2#816] opened 2015-02-16 21:47 UTC
Example 1: I can get two separate groups of peeps to blink at the same time

http://puu.sh/fZVoR/cda911f669.mp4

Example 2: right after loading a save and selecting queuing peeps, there are some blinking ones far from the queue. The extra ones seem to stop flickering after time.

http://puu.sh/fZTac/9785d1174b.mp4

**Comment by mrtnptrs** [comment] 2016-06-18 12:48
The two links aren't valid anymore. Could you upload it again somewhere, so I can understand this issue better and can test if this still happens? Because I don't really understand what you mean with "blink"

**Comment by rwjuk** [comment] 2017-05-08 12:47
Closing as incomplete - without the videos or more information, it's impossible to work out what this bug report is getting at.

**Comment by adrian17** [comment] 2017-05-08 17:06
Oops.

Here are both videos, reuploaded:
https://puu.sh/vJFpk/75041e8611.mp4
https://puu.sh/vJFqd/e053128948.mp4

I didn't check if this still happens..

**Comment by rwjuk** [comment] 2017-05-08 17:07
Thanks, I'll reopen this for further investigation.

**Comment by duncanspumpkin** [comment] 2017-08-02 20:24
Issue is caused by flashing list not being properly reset back to false when switching filters. I'm not sure how to fix it as i cant tell why its not reseting correctly.

**Closed** 2017-08-10 21:41 UTC
Labels: original bug
