### ISSUE TITLE
(probably) too specific libduktape dependency on Linux

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#11532] opened 2020-04-29 16:37 UTC
**OS:** Linux x64, Ubuntu 19.10
**Version:** dev
**Commit/Build:** dd9e579

The newest dev builds introduce a dependency on libduktape. I have installed libduktape from the Ubuntu repo, providing `/usr/lib/x86_64-linux-gnu/libduktape.so.204`

However, starting openrct2 fails because it expects a specific, apperently older, version: 

> ./openrct2: error while loading shared libraries: libduktape.so.202: cannot open shared object file: No such file or directory

If I symlink `….202` to `….204`, the game seems to work fine, so this dependency is probably too specific.

- [ ] Reproducible in RCT2 (vanilla)?
no, its due to a new OpenRCT2 feature
- [ ] Specific to multiplayer?
no

**Comment by AaronVanGeffen** [comment] 2020-04-29 16:48
Our Ubuntu builds are built with an Ubuntu 20.04 Docker image, last refreshed two weeks ago. That's probably where the difference comes from.

I'm not sure duktape provides any guarantees about ABI compatibility… If this _is_ the case, we ideally the linker would pick a less-specific .so file, as you suggest.

**Comment by Broxzier** [comment] 2020-04-29 17:45
On Ubuntu 18.04 I had no problems. I did have to install libduktape202, but that was the only version anyway:
```
sudo apt-get install libduktape202
```

**Comment by Gymnasiast** [comment] 2020-04-29 21:16
Are you using the PPA? If not: you should. The binaries on the website are really only meant for distros for which there is no repository.

**Comment by cheweytoo** [comment] 2020-05-03 16:10
Ah. No, I don't use the PPA, since that would pollute my regular automated system backup with _way_ too many dev versions of OpenRCT2 ;-)

But yeah, the PPA's deb file dependency list says `…, libduktape204 (>= 2.0.3), …` for the Ubuntu 19.10 version, so I assume it would work. Since my use case is unusual, and we're talking dev builds anyway, I'd be perfectly fine with you considering this issue a WONTFIX.

It might still be useful for the generic Linux build's lib requirements to be more tolerant if possible though.

**Comment by Gymnasiast** [comment] 2020-05-03 18:43
The problem is that duktape does not seem to employ semantic versioning, and as a result, it has to change the .so name with every single duktape release. There really isn't anything we can do about that - once our binary is compiled, it will look for that .soname, like all Linux binaries. It's not a design decision on our part, so we can't really do anything about it.

**Comment by AaronVanGeffen** [comment] 2020-05-05 10:57
Closing this for the reasons outlined above.

**Closed by AaronVanGeffen** 2020-05-05 10:57 UTC
Labels: Linux (OS), build
