### ISSUE TITLE
Instant Crash after Loading a Save

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1561] opened 2015-07-06 01:50 UTC
stable build won't crash, but the build 928 from OpenRCT2.com crashed.

Video clip showing the bug:
https://drive.google.com/file/d/0B2_12DbzmFxYS05KMFQybEVnUjg/view?usp=sharing
The save for reproducing the bug
https://drive.google.com/file/d/0B2_12DbzmFxYVml3dTBCVjd3QTA/view?usp=sharing

**Comment by wolfblake** [comment] 2015-07-06 03:22
My OpenRCT2, v0.0.3-develop build A432 (294456d) provided by OpenRCT.net crashed in two parks when I tried to place the spiral hedges maze.

**Comment by duncanspumpkin** [comment] 2015-07-06 11:29
I played about with hedges last night so I'm not surprised that there is a bug in my changes. I'll try get the fixed tonight. I'll also try fix the crash your encountering in 928 again probably due to my changes last night.

**Comment by duncanspumpkin** [comment] 2015-07-06 16:29
@wolfblake your issue is caused by #1556. I have a fix for it and it will be up shortly. It might be the cause of this one as well.

**Comment by duncanspumpkin** [comment] 2015-07-06 16:57
There is a news item that is causing this crash. I'm trying to work out what has corrupted the news item to cause this.

**Comment by duncanspumpkin** [comment] 2015-07-06 17:06
This save is very odd. How did you create it? There are tons of corrupted names in the news items. If i play it though it doesn't cause anymore corrupt names to be created.

**Comment by daihakken** [comment] 2015-07-06 17:16
The scenario was created by the author in the description, what I can remember is that I had demolished the Viper and re-built it, named it as NuViper. I didn't use this save anymore, as I find a better copy of re-created scenario. This save was sitting in the folder for nearly a year, until I found out this project, and I always accidentally click on it to load the save. By the way, it can be opened in Vanilla RCT2 and v0.0.2, but not in the build 928. and which made me think that is a bug (maybe it's not).

**Comment by duncanspumpkin** [comment] 2015-07-06 17:40
Its crashing because of the corrupted news item. I'll give you the full reason just for fun.

I can't remember the exact name so I'll just use an example name throughout this explanation.

Correct name: "Roller Coaster 1"
Actual name in news item: "Roller Coaster 1\x7B\x12\x43\x43\x32"

The garbage at the end looks like its been pulled from unset memory. The actual values don't matter too much apart from the fact that RCT2 uses certain values as control codes. These control codes are used to put extra info in parameters into the string. For example to display number of peeps we would write "Number of peeps {FORMAT_COMMA32}". Where FORMAT_COMMA32 is 0x7B. When the game reads this string it walks along and finds the FORMAT_COMMA32 and looks into the arguments pointer and takes the first 32bits and converts that into a comma seperated value to create the final string: "Number of peeps 1,238". 

So how does this apply to this bug. When this news item tries to display it will walk along the string and hit the control code 0x7B at this point it looks for the 32bit value in the arguments and promptly crashes. The crash is because in OpenRCT2 we like to put in protection against accessing invalid memory. In this case we had set the arguments pointer to NULL as no news items have control codes that require access to the argument pointer. The dereference of the pointer causes the crash.

In the versions of the game that didn't crash the argument pointer was still pointing at nonsense memory so the game happly pulls that value from memory and converts it into whatever the control code wanted.

So something else is causing the corrupted names and that in turn is causing issues. I loaded it in vanilla rct2 and also saw the corrupted names so it must be part of the save from a while back. So therefore I'm not sure how to fix it since I don't want to remove the protection we have added just to load a corrupted save.

**Comment by Gymnasiast** [comment] 2015-07-06 18:45
@duncanspumpkin : Can we filter out incorrect(ly used) formatting codes when processing them?

**Comment by duncanspumpkin** [comment] 2015-07-06 18:48
How do you know its incorrect. We aren't going to write a special function just because someones news items are corrupt it would be better to find out how they became corrupt. Since this is an old save i doubt we will ever find out why.

**Comment by daihakken** [comment] 2015-07-07 02:48
I never thought that it was corrupted, thanks for the explanation. Well, I cannot find the news item in the Vanilla RCT2, so I think the scenario was corrupted at first, and then, the corruption is now exposed by the newer builds.

**Comment by RobertWHurst** [comment] 2015-07-07 04:56
try catch?

**Comment by wolfblake** [comment] 2015-07-10 11:35
@duncanspumpkin now I am on build 35d444e and the game crashes in any park when I place the ferris wheel.

**Comment by duncanspumpkin** [comment] 2015-07-10 11:37
@wolfblake thats unrelated to this issue. #1586 is the one for that.

**Comment by IntelOrca** [comment] 2015-08-04 01:28
Coincidently fixed in utf8 branch.

**Closed by IntelOrca** 2015-08-04 01:28 UTC
Labels: bug
