### ISSUE TITLE
track piece

### ISSUE THREAD

**Issue by Tramcoaster** [OpenRCT2/OpenRCT2#20874] opened 2023-10-11 21:25 UTC
### Operating System

Wndows 10 

### OpenRCT2 build

OpenRCT2, v0.4.6-96-gf773adc (f773adc on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Do you know that the turbo track of the Twister RC and Mini RC have been changed

### Steps to reproduce

maybe an error in the code

### Attachments

![Six Flags 2023-10-11 23-16-45](https://github.com/OpenRCT2/OpenRCT2/assets/108947550/9fa58b3d-6dc5-432b-a3cc-32903cf65c08)

**Comment by karst** [comment] 2023-10-11 21:26
Duplicate of #20866

**Comment by Tramcoaster** [comment] 2023-10-11 21:34
it's crazy to see. and very special at the same time. If you look closely you can see that the tracks almost connect

**Closed** 2023-10-12 06:59 UTC
Labels: bug, duplicate
