### ISSUE TITLE
Research window displays only vehicle name

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#10157] opened 2019-10-28 23:01 UTC
**OS:** GNU/Linux
**Version:** 0.2.3
**Commit/Build:** stable

- [ ] Reproducible in RCT2 (vanilla)? No.
- [ ] Specific to multiplayer? No.

**Steps to reproduce:**
1. Research anything with vehicles (e.g. “Mine Train” vehicle for “Wild Mouse” rollercoaster)
2. Look at the “previously researched” section of the research window when the research is done

The research window will only display the name of the vehicle, rather the ride base name. This can get pretty confusing if you have researched an entirely new rollercoaster type or track type.

For example, if you researched side-friction coaster, it will display “side-friction coaster car” (or however the vehicle is currently called). Or if you have researched the first vehicle for car ride, it will only display the vehicle, not “car ride”.

**Analysis**
Displaying only the vehicle name is not very helpful as it's not easy to remember which vehicle belongs to which ride.
On the other hand, displaying only the ride/track name is definitely not enough as it's ambigious.

**Suggested fix**
If a ride with vehicles was researched (or is being researched), in the research window display *both* the base ride name (e.g. Wild Mouse) and the vehicle name (e.g. Mine Train) that was researched.
This should be the most useful option. It might require increasing the size of the window a bit, but I hope this is not a problem.

**Comment by Gymnasiast** [comment] 2019-10-28 23:21
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/7324.

**Closed by Gymnasiast** 2019-10-28 23:21 UTC
