### ISSUE TITLE
Camera stuck in corner of the map (workaround and save file provided, for researching the cause)

### ISSUE THREAD

**Issue by dylan1114** [OpenRCT2/OpenRCT2#7104] opened 2018-01-30 11:23 UTC
**OS:** Windows 10 64-bit
**Version:** 0.1.2 
**Commit/Build:** 5cc21fd

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
Unknown, happened after I expanded my land in sandbox mode and building a log flume ride. The workaround is changing the size of your land on the map while sandbox mode is on. Then the camera will unstuck.

**Dump file**
n/a

**Screenshots / Video:**
https://vimeo.com/253286963

**Save game:**
[New Six Flags.zip](https://github.com/OpenRCT2/OpenRCT2/files/1677450/New.Six.Flags.zip)

**Comment by jensj12** [comment] 2018-01-30 12:56
Duplicate of #7085. Since the workaround you found hasn't been posted there yet, please post it on that issue so this one can be closed.

**Closed** 2018-01-30 13:00 UTC
Labels: duplicate
