### ISSUE TITLE
Objects in Selector not available for placement

### ISSUE THREAD

**Issue by myn0k** [OpenRCT2/OpenRCT2#7517] opened 2018-05-14 23:01 UTC
**OS:** [e.g. Windows 7]
**Version:** [e.g. 0.1.3]
**Commit/Build:** [e.g. bd5b137]

Certain items in some scenarios selected in the Object Selector menu are not available in the scenery menu for placing. Inconsistent issue, not universal to all scenarios.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load save-game provided and open object selector tool
2. Verify item WALLMN32.DAT is selected to be available (vanilla rct2 wooden wall, see video)
3. Open scenery placement walls tab and verify object WALLMN32.DAT is not available to be placed

**Dump file**

**Screenshots / Video:**

https://www.youtube.com/watch?v=IHL0AMlWmvg

**Save game:**

[CrumblyWoodsV0.2.txt](https://github.com/OpenRCT2/OpenRCT2/files/2002861/CrumblyWoodsV0.2.txt)

**Comment by AaronVanGeffen** [comment] 2018-05-15 07:43
If I understand the issue correctly, this is intended behaviour. You will have to edit the invention list in order to make the object(s) available immediately, too.

**Comment by Gymnasiast** [comment] 2018-05-15 09:37
Not for separate walls, though, unless part of an uninvented scenery group.

**Comment by Broxzier** [comment] 2018-05-15 10:25
That seems to be the case indeed. The mine theming was still in the to-be-inveted list. Moving it up to the list of invented items makes the wall available.

@myn0k You can fix this easily by enabling debugging tools in the options menu, then from the Debugging Tools button in the top toolbar (the one with the two cogs) select _Invention list_ and move 'Mine Theming' to the upper list.

**Closed** 2018-05-15 10:33 UTC
Labels: non-bug

**Comment by IntelOrca** [comment] 2018-05-15 10:58
Do you guys think it would be better to auto invent items if added in-game?

**Comment by myn0k** [comment] 2018-05-15 16:14
Wow. I'm such an idiot. I'm sorry :( I could have sworn I had "ignore invention status" enabled in the cheats but I must have unselected it at some point. I'm really sorry for wasting everyone's time I feel terrible.
