### ISSUE TITLE
Guest purchase animation can only be seen from 1 angle

### ISSUE THREAD

**Issue by DevNebulae** [OpenRCT2/OpenRCT2#8582] opened 2019-01-11 08:38 UTC
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 8ac731e

The guest purchases are not visible from every camera angle. You have to rotate until you see the appropriate animation corresponding to the *ka-ching* sound. **EDIT:** After some further play testing, it seems that the camera has to be facing the same way as the entrance or exit of that stall / ride.

**Steps to reproduce:**
1. Enable the "Show guest purchases as animation" option in the second tab.
2. Use the OpenGL drawing engine, which can be found in the first options tab.
3. Open a park.
4. Rotate the camera until you see the guest purchases.

**Screenshots / Video:**

![rct2-sales](https://user-images.githubusercontent.com/12952123/51022404-653eed80-1584-11e9-8bc2-22012c0f6fcd.png)

This text is only visible when I rotated the camera two times from the original camera viewpoint in the Dynamite Dunes scenario.

**Comment by Gymnasiast** [comment] 2019-01-11 13:54
Do you have your rendering mode set to OpenGL, or to one of the two software modes?

**Comment by DevNebulae** [comment] 2019-01-11 14:11
@Gymnasiast It is set in OpenGL mode.

**Comment by Gymnasiast** [comment] 2019-01-11 16:31
Ok, then it's a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8547.

**Closed by Gymnasiast** 2019-01-11 16:31 UTC
