### ISSUE TITLE
Top toolbar disappears when opening SC4 file

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#5228] opened 2017-02-16 16:03 UTC
**OS:** Windows 10
**Version:**  0.0.7
**Commit/Build:** d40bbd7

In certain situations, the top toolbar disappears when opening a RCT1 SC4-file. It happens consistently when opening the SC4-file using the "Load game" dialog, while playing another park, when no other windows are open.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open a park, either by selecting a park from the new game menu, or loading a save game.
2. Close all open windows. This is important, as having a window open does not seem to trigger the bug.
3. Click the floppy-icon > Load Game
4. Open a RCT1 SC4 file
5. The top toolbar should now be gone.

**Screenshots / Video:**

Image of the top toolbar disappearing after loading Forest Frontiers
![notoolbar](https://cloud.githubusercontent.com/assets/5968886/23028905/075f11a6-f469-11e6-8e53-64af772fcac7.png)

**Comment by Gymnasiast** [comment] 2017-02-16 19:09
Can confirm. (Kept forgetting to report it.)

**Comment by Gymnasiast** [comment] 2017-03-26 16:35
This _might_ have been fixed by accident in https://github.com/OpenRCT2/OpenRCT2/commit/e85c627bd5d6db14ac429c1695f421dd14d08ec3, because it avoid error messages about building in pause mode. It's probably best to see if this happens again for a few weeks, then close it if it doesn't.

**Comment by RoelerCoaster** [comment] 2017-03-27 16:28
Still happens for me on 2ce4b51

**Comment by janisozaur** [comment] 2017-06-27 09:23
@Gymnasiast @RoelerCoaster can you re-check?

**Comment by Gymnasiast** [comment] 2017-06-27 09:48
Still present.

**Comment by rwjuk** [comment] 2018-01-09 22:49
This doesn't seem to occur any more for me - @Gymnasiast could you check once more?

**Comment by Gymnasiast** [comment] 2018-01-10 13:36
Cannot reproduce this either. I'll close it.

**Closed by Gymnasiast** 2018-01-10 13:36 UTC
Labels: bug, rct1 import
