### ISSUE TITLE
Some pre-designs cannot be built without disabling clearances

### ISSUE THREAD

**Issue by GigaG11** [OpenRCT2/OpenRCT2#14317] opened 2021-03-14 21:16 UTC
**OS:** Windows 10
**Version:**  0.3.
**Commit/Build:** 0.3.3 Release 

Default Twister coaster "Atomizer" and Corkscrew coaster "Octivator" cannot be built  as they have parts that seem to register as intersecting other parts.

**Comment by Gymnasiast** [comment] 2021-03-14 21:18
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/13336.

**Closed by Gymnasiast** 2021-03-14 21:18 UTC
