### ISSUE TITLE
BACKTRACE 442381 window_ride_vehicle_dropdown -> input_state_widget_pressed -> game_handle_input_mouse

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8250] opened 2018-11-10 22:04 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/442381d61e2a328abca4855f01c78544430a1c8c74a2363be5ed361975586645?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Nov 10 2018 21:19:39)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 223ae74: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>window_ride_vehicle_dropdown -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> SDL_PeepEvents_REAL -> SDL_WaitEventTimeout_REAL -> SDL_PollEvent_REAL -> UiContext::ProcessMessages -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:45
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8303

**Closed by janisozaur** 2019-02-02 22:45 UTC
Labels: backtrace.io, crash
