### ISSUE TITLE
Button to pin windows 

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3458] opened 2016-04-30 09:16 UTC
A button next the 'X', to pin windows so that when you pressed shift and backspace the windows you have pinned would stay open.

A bit like how OTTD does it:

![untitled-1](https://cloud.githubusercontent.com/assets/1381723/14935062/81a878dc-0ebc-11e6-8151-1b9fcaa62648.jpg)

**Comment by IntelOrca** [comment] 2016-04-30 09:56
Duplicate of #2981... again.

**Closed by IntelOrca** 2016-04-30 09:56 UTC
Labels: duplicate
