### ISSUE TITLE
Bumblebee ride cannot be built due to clearance check violation.

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#14578] opened 2021-05-06 14:51 UTC
OS: Windows 10
Version: I don't know the version number, but it is the most recent full release build.

I was trying to build the prebuilt ride "Bumblebee" and the game told me " Is in the way" I was confused and decided to disable clearance checks, and then the ride was able to be built. a bit of testing allowed me to confirm that one of the lift hill pieces going through the loop exists in the same space as the loop, and this denies building of the ride.

Not reproduceable in vanilla.

To Reproduce:
Simply attempt to build the looping coaster prebuilt ride "Bumblebee" with "disable clearance checks" disabled, and the ride will refuse to build.

**Comment by duncanspumpkin** [comment] 2021-05-06 14:56
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/13336

**Closed by duncanspumpkin** 2021-05-06 14:56 UTC
Labels: duplicate
