### ISSUE TITLE
Waifu2x Graphics upscaling

### ISSUE THREAD

**Issue by Jargonius** [OpenRCT2/OpenRCT2#4200] opened 2016-08-01 20:32 UTC
You should use [waifu2x](https://github.com/nagadomi/waifu2x) to upscale the graphics in OpenRCT2.  It has incredible upscaling capabilities because it uses a neural network.  You can even just use it to remove noise without upscaling.

Try it out [here](http://waifu2x.udp.jp)!

**Pictures:**
Upscaling using medium noise reduction, artwork, and 2x scaling.
![image](https://cloud.githubusercontent.com/assets/6412293/17307608/304984b0-57f3-11e6-8d8a-bf2ea2acef40.png)

Noise reduction highest with no upscaling and srtwork settings.
![image](https://cloud.githubusercontent.com/assets/6412293/17307914/a7ddced6-57f4-11e6-9ee6-b8d77e67abe0.png)

**Comment by Nubbie** [comment] 2016-08-01 20:36
Presume it would solve #775

**Comment by janisozaur** [comment] 2016-08-01 20:38
Duplicate of https://github.com/OpenRCT2/OpenRCT2/pull/2328.

See https://github.com/OpenRCT2/OpenRCT2/pull/2328#issuecomment-157491637 in particular.

**Closed by janisozaur** 2016-08-01 20:38 UTC

**Comment by Jargonius** [comment] 2016-08-01 21:43
It seems like the other issue takes the approach of running waifu2x at runtime.  Wouldn't it be more efficient to upscale all of the sprites once and then use them?

**Comment by janisozaur** [comment] 2016-08-01 21:46
We can't do it, at least not yet.

**Comment by devnoname120** [comment] 2019-03-26 17:10
Note that there are now better upscaling neural networks: https://github.com/xinntao/ESRGAN and https://github.com/xinntao/SFTGAN

**Comment by janisozaur** [comment] 2019-03-26 17:55
Can you provide a sample image?
