### ISSUE TITLE
Infinite loop when resizing park with map cheat

### ISSUE THREAD

**Issue by FlukiestEmperor** [OpenRCT2/OpenRCT2#2165] opened 2015-10-30 10:49 UTC
This goto statement causes an infinite loop in function sub_68AE2A()

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/world/map.c#L4189

How to reproduce
Start a new game with Africa - Victoria Falls
Open cheats menu, turn on sandbox mode
Try to shrink the park, game will infinite loop

This also happens with this saved game
https://drive.google.com/open?id=0B6kgMkNpYHigZ05PLUFkNlkycjg

Although, in Africa - Victoria Falls, if you make the park size 1 larger, then shrink it by 1, will not infinite loop, but in my saved game it will.

**Comment by Gymnasiast** [comment] 2015-10-30 11:58
Duplicate of #1432 (even the same map...)

**Comment by FlukiestEmperor** [comment] 2015-10-30 12:06
Alright, I'll close this and comment on that issue.

**Closed** 2015-10-30 12:06 UTC
Labels: duplicate
