### ISSUE TITLE
RMC Hybrid coaster support glitch

### ISSUE THREAD

**Issue by Wilhelm1407** [OpenRCT2/OpenRCT2#22162] opened 2024-06-11 04:54 UTC
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.11-249-g8175575 (8175575 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

When placing a diagonal straight piece of track, a portion of support turns orange. 
![Desktop Screenshot 2024 06 10 - 23 48 07 96](https://github.com/OpenRCT2/OpenRCT2/assets/172352991/f10edd2f-2c85-4dbe-9be1-d212f546fcf1)

### Steps to reproduce

Build diagonal straight piece of track with RMC Hybrid track. 

### Attachments

![Desktop Screenshot 2024 06 10 - 23 48 07 96](https://github.com/OpenRCT2/OpenRCT2/assets/172352991/a7ac90b3-3840-4cab-bfe8-45fddc02a4d5)

**Comment by fidwell** [comment] 2024-06-11 17:21
Possibly a duplicate of #22063

**Comment by Gymnasiast** [comment] 2024-06-13 09:53
A duplicate indeed.

**Closed by Gymnasiast** 2024-06-13 09:53 UTC
Labels: bug
