### ISSUE TITLE
Cube/Cage supports, called "support structure" are not displaying properly in parks

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#16233] opened 2021-12-14 01:35 UTC
### Operating System

Windows 11 64-bit

### OpenRCT2 build

v0.3.5.1 (fa737dc on develop)

### Describe the issue

 "support structure" ( the simple and standard cube shaped cage supports) are now not displaying .
I don't have a vanilla install, i only have the launcher/updater version of openrct2. This began happening only in the latest (currently stated) update version, and this also did occur in the 1 previous update version (prior) to this  which was the automatic update downloaded on 12-12-21 or 12-11-21 or 12-10-21???.
I am currently running v0.3.5.1 (fa737dc on develop).

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Open an old saved park that contains cube cage support structures and observe that the cube cage supports, called "support structures" are not being displayed in parks where they previously did.
2. 
3. 

### Attachments

![XtRme Heights RMX J Marsilio 2021-12-13 20-31-09](https://user-images.githubusercontent.com/17103908/145916379-c8d75889-7318-48b2-8941-8298c3972792.png)
![Crazy Castle By JoshMarsilio 2021-12-13 20-34-20 2](https://user-images.githubusercontent.com/17103908/145916595-f584bbb3-f541-4b24-b3a0-63399c0b7a83.jpg)

**Comment by ocalhoun6** [comment] 2021-12-14 01:55
Duplicate of #16206 ?

**Comment by jamtraks** [comment] 2021-12-14 02:01
Possibly, yes. I'm not sure if this is an  issue with the object file: "support structure" not showing, or if this is an issue with the automatic-support-draw for coasters not functioning/drawing properly.

**Closed** 2021-12-14 06:59 UTC
Labels: bug
