### ISSUE TITLE
Getting a message if you want to keep the older track type on already existing track or change it

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#15468] opened 2021-09-27 05:07 UTC
### Describe the feature

well, i ask this feature since a very weird bug happened it this one here: [https://github.com/OpenRCT2/OpenRCT2/issues/15467](url)

when about to change to a new track type, you select the track you wanna build, then it show up this

what you want to do;

1. keep track type on already builded tracks
2. change the track that the new track type do (keep the impossible ones untouched)
3. change it entirely

### Feature type

Quality of life, Other

**Comment by duncanspumpkin** [comment] 2021-09-27 05:51
Duplicate of #15367

**Closed by duncanspumpkin** 2021-09-27 05:51 UTC
Labels: feature
