### ISSUE TITLE
L(l)'s in Text Boxes are being replaced by capital P's

### ISSUE THREAD

**Issue by Zyreath** [OpenRCT2/OpenRCT2#17517] opened 2022-07-07 03:43 UTC
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.0 (c6302a1 on master) provided by GitHub

### Describe the issue

l's in text are being replaced with Ps... feel i have notice before, but is VERY apparent after the install of the v0.4.0 update, as recent as July 4th, 2022... i havent seen any other reports of this so not sure if its an error in my installation or a global bug... it is very jarring and kills the experience particualrly when the title of the game becomes RoPPercoaster Tycoon & Corckscrew FoPPies, though the RoPPercoaster Tycoon 2 scenario Great WaPP of China did make me chuckle, id rather they just be back to normal Ls if possible... it does seem like a simple replace/overwrite command error

have a screenshot for reference

### Steps to reproduce

1. 
2. 
3. 

### Attachments

![Open RCT2 Bug Report](https://user-images.githubusercontent.com/22374169/177686043-6a15a63c-c5de-4acf-b968-0c1ced6c00c5.png)

**Comment by YJSoft** [comment] 2022-07-07 03:50
Duplicate of #17509. Almost sprite font problem is caused by outdated g2.dat.

**Comment by janisozaur** [comment] 2022-07-07 05:28
_sigh_ please search for issues before filing yet another duplicate

**Closed by janisozaur** 2022-07-07 05:28 UTC
Labels: bug
