### ISSUE TITLE
Disabling land smoothing leaves some edges being smoothened

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4032] opened 2016-07-10 11:16 UTC
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.5-develop
**Commit/Build:** 59c3656

If you disable land smoothing / edge smoothing in the options, there are still some edges which are always smoothened.

Screenshot (follow link to enlarge) of land smoothing setting being disabled:
![smooth](https://cloud.githubusercontent.com/assets/1675853/16713214/59e533f0-46a0-11e6-80d6-a53d9ee02f3e.png)

- Reproducible in RCT2 (vanilla)? I don't know.
- Multiplayer? N/A

**Steps to reproduce:**
1. Play any scenario, preferably with lots of hills and sand
2. Disable land smoothing in the options
3. Look at the land

**Comment by IntelOrca** [comment] 2016-07-10 11:22
I think this is a vanilla bug, or the reverse was opposite, some diagonal edges were not smoothed.

**Comment by Patrik356b** [comment] 2016-07-10 13:25
Duplicate of #2333

**Closed** 2016-07-10 13:58 UTC
Labels: bug
