### ISSUE TITLE
Numpad Enter doesn't perform the same as regular Enter key when entering a value in a name/price window.

### ISSUE THREAD

**Issue by SjoerdVlek** [OpenRCT2/OpenRCT2#17876] opened 2022-08-21 17:21 UTC
Expected behaviour would be the same as regular enter key, window is closed and new value is applied to name/price/etc.

**Comment by James103** [comment] 2022-08-21 17:25
Can confirm in 7f29e4e39c76dbf7039162368ec8bb604e943d03 on Windows 10, 64-bit.

To reproduce:
1. Open a text box.
2. Press Numpad Enter.
3. The text box does not close and changes are not applied.
4. Press the standard Enter key.
5. The text box closes and changes are applied.

**Comment by Gymnasiast** [comment] 2022-08-22 20:11
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/15589.

**Closed by Gymnasiast** 2022-08-22 20:11 UTC
Labels: good first issue
