### ISSUE TITLE
Text indentation on headless server is inconsistent when using verbose

### ISSUE THREAD

**Issue by saadbruno** [OpenRCT2/OpenRCT2#11516] opened 2020-04-27 21:52 UTC
**OS:** Ubuntu
**Version:** 18.04 LTS
**Commit/Build:**  6c3c857 (v0.2.6)

When you run a headless server with the `--verbose` option, the indentation (or tabbing?) of the text is all over the place. See attached screenshot.
I don't know if it's specific to the Linux build, or if it has any relation to the fact that I'm running this inside a screen session, but it seems consistent with all the 3 machines that I ran the server on (two Ubuntu VMs and my local Raspberry Pi)

- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Run a headless multiplayer server with the `--verbose` option
2. Connect to the server and perform some actions in game so you have the log on the terminal

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/23201434/80423824-fe4b6200-88b6-11ea-9030-c3a7a1c333a1.png)

**Comment by tupaschoal** [comment] 2020-04-27 21:54
Sounds like a duplicate of #11484

**Closed** 2020-04-28 06:53 UTC
Labels: duplicate
