### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3617] opened 2016-05-15 17:03 UTC
**OS:**  Windows 10
**Version:** 0.0.5
**Commit:** a3469cf
**Dump file**
[Dump Files.zip](https://github.com/OpenRCT2/OpenRCT2/files/265127/Dump.Files.zip)

**Comment by janisozaur** [comment] 2016-05-15 17:32
Save game is enough to reproduce. Load and zoom out.
```
#0  RCT2_CALLPROC_X (address=0x6c4934, _eax=53, _ebx=7833116, _ecx=2, _edx=168, _esi=16310904, _edi=6688, _ebp=0) at /home/janisozaur/workspace/OpenRCT2/src/addresses.c:31
#1  0x0177b7fe in track_paint (direction=<optimized out>, height=<optimized out>, mapElement=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/ride/track_paint.c:124
#2  0x01a372cb in sub_68B3FB (x=<optimized out>, y=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/paint/map_element/map_element.c:250
#3  0x01a4e383 in viewport_paint_setup () at /home/janisozaur/workspace/OpenRCT2/src/paint/paint.c:684
#4  0x01715ac3 in viewport_paint (viewport=<optimized out>, dpi=<optimized out>, left=<optimized out>, top=<optimized out>, right=<optimized out>, bottom=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:789
#5  0x017146cc in viewport_render (dpi=<optimized out>, viewport=<optimized out>, left=<optimized out>, top=<optimized out>, right=<optimized out>, bottom=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:691
#6  0x0154392d in window_main_paint (w=<optimized out>, dpi=0xffe31230) at /home/janisozaur/workspace/OpenRCT2/src/windows/main.c:98
#7  0x0174e864 in window_draw (w=<optimized out>, left=0, top=<optimized out>, right=1181, bottom=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1543
#8  0x018e63b1 in gfx_redraw_screen_rect (left=<optimized out>, top=<optimized out>, right=<optimized out>, bottom=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/drawing/drawing.c:355
#9  0x0170ed1b in sub_6E7F34 (w=<optimized out>, viewport=<optimized out>, x_diff=0, y_diff=53) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:426
#10 0x0170fd7b in sub_6E7DE1 (x=-11221, y=-11222, w=<optimized out>, viewport=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:500
#11 0x017125db in viewport_update_position (window=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:628
#12 0x0173cc01 in window_update_all_viewports () at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:149
#13 window_update_all () at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:161
#14 0x01a7eff3 in rct2_draw () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:284
#15 0x01aa1184 in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:421
#16 openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:322
#17 0x0190f9f2 in main (argc=<optimized out>, argv=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:60
```

Which makes it a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3578

**Closed by janisozaur** 2016-05-15 17:32 UTC
