### ISSUE TITLE
Weird guest behavior in one queue

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#3816] opened 2016-06-04 12:10 UTC
**OS:** Windows 8.1
**Version:** Latest
**Commit:** Latest

Guests seem to use the queue for 'Crazy Nights' as a normal path. They just walk on the queue to the end and then go back immediately. I think 60% enters the ride. Many shout that they 'already have a map' but I don't know if they all do that because the kiosk is at the other side.

**Steps to reproduce:**
1. Open save game and watch.

**Screenshots / Video:**
![scr15](https://cloud.githubusercontent.com/assets/7643972/15799458/8643f6e8-2a5d-11e6-97ea-eb34e9083425.png)

**Save game:**
[Over The Edge.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/298808/Over.The.Edge.sv6.txt)

**Comment by Gymnasiast** [comment] 2016-06-04 14:10
Duplicate of #3271.

**Closed by Gymnasiast** 2016-06-04 14:10 UTC
Labels: duplicate
