### ISSUE TITLE
Ducks swim outside water bounds

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#3663] opened 2016-05-19 10:23 UTC
**OS:** OS X
**Commit:** 01edc0f

Ducks are able to swim on the grass part of a diagonal tile.

![image](https://cloud.githubusercontent.com/assets/737603/15390513/6f30963a-1dbc-11e6-8408-10b57111c3df.png)

**Comment by AaronVanGeffen** [comment] 2016-05-19 11:33
I think this happened in the original game, too.

**Comment by Joshwoo69** [comment] 2016-05-19 13:16
land ducks?

**Comment by Patrik356b** [comment] 2016-05-19 14:56
They do this in vanilla too I recall but I don't know if there was a fix for this

**Comment by Christipher** [comment] 2016-05-19 16:02
this opens up another discussion while we are on this topic - should ducks on land be able to walk on land?

**Comment by tupaschoal** [comment] 2024-09-23 10:52
This was fixed between v0.4.0 and v0.4.1 (use this park file as reference 
[duck_diagonal_grass40.zip](https://github.com/user-attachments/files/17096334/duck_diagonal_grass40.zip))

It was fixed by #17456 (and this was a duplicate of #17450)

**Closed by tupaschoal** 2024-09-23 10:52 UTC
Labels: original bug
