### ISSUE TITLE
Distorted text in scenario description

### ISSUE THREAD

**Issue by steveexe** [OpenRCT2/OpenRCT2#15571] opened 2021-10-13 18:20 UTC
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (b4cd8e4 on develop) provided by GitHub

### Describe the issue

Hello.
After complete a mission "Rio Carnival" appeare window with distored text.
IDK, maybe i start this mission on English, i forgot. I switch back and forth language, but even backups have distored text.

### Steps to reproduce

I have only two ideas.
1) Complete "Rio Carnival" on Russian language
2) Start scenario on English, complete in Russian

### Attachments

![rct2игп](https://user-images.githubusercontent.com/63274885/137190434-04285908-fe8d-4a48-9f5e-2fabe020d2e7.PNG)

**Comment by CookiePLMonster** [comment] 2021-10-14 08:05
Given that the text (not the localization string) gets saved, that wouldn't surprise me. However, I also don't see how that isn't an original issue, if those also saved in RCT2.

**Comment by youngwii2** [comment] 2021-11-14 01:44
I've been encountering a similar issue to both this and #15888.

When I start a new scenario, the apostrophes in the scenario description appear just fine. However, after saving the game, reloading the save, and returning to the description/objective, the apostrophe gets replaced by weird characters. Even worse, the weird characters seem to multiply with each further save and load.

![Park Maharaja 2021-11-13 17-19-51](https://user-images.githubusercontent.com/52364182/141664197-b251ab30-9808-4737-9017-daa54668eb34.png)
![Park Maharaja 2021-11-13 17-19-43](https://user-images.githubusercontent.com/52364182/141664198-5c10a76a-2874-47e5-aeec-3ebf98bd51a4.png)

I am using OpenRCT2, v0.3.5 (9134bd4 on develop) provided by GitHub; unlike with steveexe, I am using the international GOG RCT2 version, plus I have consistently played my OpenRCT2 in English.

**Comment by Gymnasiast** [comment] 2021-11-14 12:21
The issue is the `’`, which is outside the ASCII range and clearly does not get encoded properly.

**Comment by Gymnasiast** [comment] 2021-11-21 13:17
This is fixed by the new-save-format branch. (Just a note)

**Comment by Gymnasiast** [comment] 2021-11-29 11:30
With the new save format merged, this should no longer occur. Sadly, any save where the text is already distorted will not be fixed automatically. Using Sandbox mode, you can correct it manually if desired.

**Closed by Gymnasiast** 2021-11-29 11:30 UTC
Labels: bug
