### ISSUE TITLE
Track Saving Crashes game

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#4697] opened 2016-10-24 20:22 UTC
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** 3d529ff

I attempted to save track designs from this particular park, but both methods of saving the designs do not work.

Opening up the system dialogue window and saving the track design without a .td6 resulted in an error message, while saving it with .td6 crashed the game.
[Oct 24 crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/548902/Oct.24.crash.zip)

**Comment by Gymnasiast** [comment] 2016-10-24 20:23
Does that apply to every single saveable ride in this park?

**Comment by Superjustinbros** [comment] 2016-10-24 21:35
I only checked the ride in the center that game saved on.

**Comment by Nubbie** [comment] 2016-10-25 14:14
**Error message;**
Unhandled exception thrown: read access violation.
td6->track_elements was 0xFFFFFFFFFFFFFFFF.

**Breakpoint;**
[src/ride/track_design_save.c](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/track_design_save.c#L1260L1264)

**Call stack;**
```
>	openrct2.exe!track_design_save_to_file(const char * path=0x000000000023f560) Line 1261	C
 	openrct2.exe!window_loadsave_select(rct_window * w, const char * path) Line 849	C
 	openrct2.exe!window_loadsave_mouseup(rct_window * w=0x0000000140b5eb20, int widgetIndex) Line 301	C
 	openrct2.exe!input_state_widget_pressed(int x=731, int y=601, int state=2, int widgetIndex, rct_window * w=0x0000000140b5eb20, rct_widget * widget=0x000000014059da60) Line 1280	C
 	openrct2.exe!game_handle_input_mouse(int x=731, int y=601, int state=2) Line 324	C
 	openrct2.exe!game_handle_input(...) Line 134	C
 	openrct2.exe!rct2_update(...) Line 459	C
 	openrct2.exe!openrct2_loop(...) Line 469	C
 	openrct2.exe!openrct2_launch(...) Line 344	C
 	openrct2.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x000000000000000a, char * lpCmdLine=0x0000000000000000, int nCmdShow=0) Line 75	C
 	[External Code]	
 	[Frames may be missing, no binary loaded for kernel32.dll]	
 	kernel32.dll!00000000774659cd()	Unknown
```

**Locals;**
```
		encodedData	Variable is optimized away and not available.	
		file	Variable is optimized away and not available.	
-		path	0x000000000023f560 "D:\\Dell_PC\\Program Files (x86)\\Infogrames Interactive\\RollerCoaster Tycoon 2\\Tracks\\The Phantom (Jon).td6"	const char *
			68 'D'	const char
		result	Variable is optimized away and not available.	
+		td6	0x0000000010178d40 {type=??? vehicle_type=??? cost=??? ...}	rct_track_td6 *
		td6Buffer	Variable is optimized away and not available.	
```

Autos;
```
-		td6	0x0000000010178d40 {type=??? vehicle_type=??? cost=??? ...}	rct_track_td6 *
		type	<Unable to read memory>	
		vehicle_type	<Unable to read memory>	
		cost	<Unable to read memory>	
		flags	<Unable to read memory>	
		ride_mode	<Unable to read memory>	
		track_flags	<Unable to read memory>	
		version_and_colour_scheme	<Unable to read memory>	
+		vehicle_colours	0x0000000010178d48 {{body_colour=??? trim_colour=??? }, {body_colour=??? trim_colour=??? }, {body_colour=...}, ...}	rct_vehicle_colour[32]
		pad_48	<Unable to read memory>	
		track_spine_colour_rct1	<Unable to read memory>	
		entrance_style	<Unable to read memory>	
		track_rail_colour_rct1	<Unable to read memory>	
		total_air_time	<Unable to read memory>	
		track_support_colour_rct1	<Unable to read memory>	
		depart_flags	<Unable to read memory>	
		number_of_trains	<Unable to read memory>	
		number_of_cars_per_train	<Unable to read memory>	
		min_waiting_time	<Unable to read memory>	
		max_waiting_time	<Unable to read memory>	
		operation_setting	<Unable to read memory>	
		max_speed	<Unable to read memory>	
		average_speed	<Unable to read memory>	
		ride_length	<Unable to read memory>	
		max_positive_vertical_g	<Unable to read memory>	
		max_negative_vertical_g	<Unable to read memory>	
		max_lateral_g	<Unable to read memory>	
		inversions	<Unable to read memory>	
		holes	<Unable to read memory>	
		drops	<Unable to read memory>	
		highest_drop_height	<Unable to read memory>	
		excitement	<Unable to read memory>	
		intensity	<Unable to read memory>	
		nausea	<Unable to read memory>	
		upkeep_cost	<Unable to read memory>	
+		track_spine_colour	0x0000000010178da0 <Error reading characters of string.>	unsigned char[4]
+		track_rail_colour	0x0000000010178da4 <Error reading characters of string.>	unsigned char[4]
+		track_support_colour	0x0000000010178da8 <Error reading characters of string.>	unsigned char[4]
		flags2	<Unable to read memory>	
+		vehicle_object	{flags=??? name=0x0000000010178db4 <Error reading characters of string.> checksum=??? }	rct_object_entry
		space_required_x	<Unable to read memory>	
		space_required_y	<Unable to read memory>	
+		vehicle_additional_colour	0x0000000010178dc2 <Error reading characters of string.>	unsigned char[32]
		lift_hill_speed_num_circuits	<Unable to read memory>	
		elements	<Unable to read memory>	
		elementsSize	<Unable to read memory>	
		maze_elements	<Unable to read memory>	
		track_elements	<Unable to read memory>	
		entrance_elements	<Unable to read memory>	
		scenery_elements	<Unable to read memory>	
		name	<Unable to read memory>	
```

**Comment by Superjustinbros** [comment] 2016-10-26 15:02
Tested in 5699b9e; the problem persists.

**Comment by IntelOrca** [comment] 2016-10-29 14:45
@Superjustinbros 
Most likely a duplicate of #4711 which is now fixed, so can you still reproduce this now?

**Comment by Chaosmeister** [comment] 2017-07-31 20:35
I'm unable to reproduce the crash

**Closed** 2017-08-05 16:14 UTC
Labels: crash, investigate
