### ISSUE TITLE
Paths like in Loopy Landscapes

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#3067] opened 2016-03-01 22:14 UTC
Please make the paths like in Loopy Landscape where you can select the path, queue line and the supports/fences independently. 

+ add the missing paths. (the last 4 on the second picture)

I think you guys already know that but to just have it on the list.
![screenshot_10](https://cloud.githubusercontent.com/assets/12634026/13443842/4aa3e962-e003-11e5-9c9e-c0a08bb35c26.png)
![screenshot_11](https://cloud.githubusercontent.com/assets/12634026/13443844/4aa80236-e003-11e5-9f73-47d5a1105bb9.png)
![screenshot_12](https://cloud.githubusercontent.com/assets/12634026/13443845/4aa993c6-e003-11e5-8d6e-5f442ca24234.png)

A new label for RCT1 features would be also great.

**Comment by janisozaur** [comment] 2016-03-01 23:15
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/2253 ?

**Comment by Horsti12** [comment] 2016-03-01 23:17
ah yeah, but the link is down.

**Closed** 2016-03-01 23:26 UTC
Labels: duplicate
