### ISSUE TITLE
Saving Flat Rides with Paths result in paths appearing far away and elevated

### ISSUE THREAD

**Issue by youngwii2** [OpenRCT2/OpenRCT2#16089] opened 2021-12-02 00:45 UTC
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (79b12d2 on develop) provided by GitHub

### Describe the issue

When saving a flat ride with scenery/paths, the scenery/paths appear far away from the ride, and are elevated.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Build a flat ride, and after testing it, save design with scenery.
2. After design is saved, return to ride selection window and build the ride type again.
3. The scenery/paths saved with the flat ride appear very far away, and are elevated.

### Attachments

![Forest Frontiers 2021-12-01 19-33-02](https://user-images.githubusercontent.com/52364182/144337119-9d390e12-d18d-4e8f-9ad2-ba2bfa05fcd3.png)
![Forest Frontiers 2021-12-01 19-33-11](https://user-images.githubusercontent.com/52364182/144337126-9c0bc677-336f-4c7d-bd71-e0621e2b9765.png)
![Forest Frontiers 2021-12-01 19-33-28](https://user-images.githubusercontent.com/52364182/144337125-b9b9e008-adb2-479d-a98d-719096b31be2.png)
![Forest Frontiers 2021-12-01 19-35-14](https://user-images.githubusercontent.com/52364182/144337123-1f9653ee-f827-4401-856b-99c6f0d118b4.png)
![Forest Frontiers 2021-12-01 19-35-12](https://user-images.githubusercontent.com/52364182/144337124-b8f3e585-df3b-4735-8dab-97a91e2b972a.png)

**Comment by duncanspumpkin** [comment] 2021-12-02 08:04
Duplicate of #16075

**Closed by duncanspumpkin** 2021-12-02 08:04 UTC
Labels: bug
