### ISSUE TITLE
Tons of visual glitches when zooming out

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6681] opened 2017-11-17 07:36 UTC
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 36236d8

When zooming out the game has some interesting visual glitches.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer? Doesn't seem to be

**Steps to reproduce:**
1.  Zoom out

**Screenshots / Video:**
![test park 2017-11-17 08-12-04](https://user-images.githubusercontent.com/25930360/32935854-34749cd4-cb72-11e7-8846-c7fe7aa11458.png)
![test park 2017-11-17 08-11-15](https://user-images.githubusercontent.com/25930360/32935860-37e88312-cb72-11e7-8ada-89dca4c22916.png)
![test park 2017-11-17 08-03-41](https://user-images.githubusercontent.com/25930360/32935862-391c0a88-cb72-11e7-8632-ebd6398cf8e3.png)
![test park 2017-11-17 08-16-17](https://user-images.githubusercontent.com/25930360/32935755-bfe03cca-cb71-11e7-9de1-379cc07a3eae.png)
![test park 2017-11-17 08-30-23](https://user-images.githubusercontent.com/25930360/32935756-bff468da-cb71-11e7-9af9-97b58af140ea.png)
![test park 2017-11-17 08-27-36](https://user-images.githubusercontent.com/25930360/32935757-c008372a-cb71-11e7-86b3-df9cc7114644.png)

**Comment by AaronVanGeffen** [comment] 2017-11-17 10:23
Which render engine are you using? (OpenGL? Software?)

**Comment by LordMarcel** [comment] 2017-11-17 10:29
Software. The glitches are also not very consistent. It seemed like it had fixed itself, but 10 minutes later it started happening again. It's also not happening now, so maybe it's fixed in the newest build.

**Comment by LordMarcel** [comment] 2017-11-17 11:17
Definitely not fixed, the bug came after like 15 minutes or so.

**Comment by duncanspumpkin** [comment] 2017-11-17 11:33
Can you check older builds and work out when it stopped working.

**Comment by duncanspumpkin** [comment] 2017-11-17 11:38
May be related to the change to the path/track interaction but it seems unlikely. This looks like the draw call for surface elements isn't being issued or is corrupting.

**Comment by janisozaur** [comment] 2017-11-17 11:57
Is this on all parks or just a particular one?

**Comment by LordMarcel** [comment] 2017-11-17 12:13
It's quite hard to pinpoint in which build it first happens because sometimes it's all fine for a while before it starts to glitch. I downloaded a bunch of builds and the oldest I saw it happening it in was 63e2469. I've tested it and it happens in all parks I've tested.

**Comment by duncanspumpkin** [comment] 2017-11-17 13:16
Could be cause by https://github.com/OpenRCT2/OpenRCT2/pull/6574 this does after all control all textures. Maybe some sort of memory corruption. Try 0f3b6b1590de8044fdbd277a5e69d35fced0b7dc and confirm if it occurs on that build as it was the last one prior to the g1 change.

**Comment by LordMarcel** [comment] 2017-11-17 13:44
I played around in that build a bit and didn't get the glitches, so it's pretty safe to say that it's still fine in that build.

**Comment by LordMarcel** [comment] 2017-11-17 14:07
I would also like to mention that openrct2 crashes frequently when trying to load parks, it's happened about 5 times today. This is also a new thing, so it might be correlated to the graphical glitches.

**Comment by TonyLaV** [comment] 2017-11-17 19:25
Same Problem 
![bumbly beach 2017-11-17 20-21-59](https://user-images.githubusercontent.com/33175850/32965016-70bcdf68-cbd5-11e7-8f39-0fbd0e44d68f.png)

**Comment by Kynake** [comment] 2017-11-19 04:35
I haven't been able to reproduce it for a picture, but I noticed that while the paths tab was open, things looked normal, and when I close it the issue comes back.

**Comment by LordMarcel** [comment] 2017-11-19 08:04
Yeah, the same happens with the scenery, scenery removal, water, and land tabs. I also noticed that the glitching only happens on flat grassland. As you can see in the image above, hills and other types of ground like sand aren't affected.

**Comment by UltimaterRCT** [comment] 2017-11-19 10:48
In **_0.1.2 build 67ebf40_**, I was able to recreate this even on multiplayer. So far it doesn't happen all the time, but it does happen commonly.

**Comment by Liampie** [comment] 2017-11-19 19:40
I got the problem in one of my saves right now. It doesn't happen always, but something triggered it this time. Will keep an eye open to see if I can figure it out next time it happens...

I did notice that it affects only flat, grass tiles.

**Comment by Nubbie** [comment] 2017-11-19 19:44
Would be great if someone checked which version that started happen at

**Comment by Broxzier** [comment] 2017-11-20 12:44
I just had this happen for the first time on bf69b2e. Opening the map window seems to trigger something for this to happen consistently.

**Comment by janisozaur** [comment] 2017-11-20 12:58
@Broxzier can you provide a recording?

**Comment by Broxzier** [comment] 2017-11-20 13:32
Using `git bisect` I found the commit that caused it: 4232be9fc290d9b15c65092e336a94104e13e433
It's parent (444a8c160279e0af6289c615522d41f63ca8e1a8) doesn't have this issue after opening the map window.

@janisozaur here's how to trigger this effect with the map window. Note that it only seems to occur when gridlines are disabled.
![recording](https://i.imgur.com/mOdrx9V.gif)

**Closed** 2017-11-20 13:48 UTC
