### ISSUE TITLE
Drink stalls are too intense for guests

### ISSUE THREAD

**Issue by hypocube** [OpenRCT2/OpenRCT2#2308] opened 2015-11-15 19:40 UTC
I'm on a custom map (Coasterization of Mars) and drinks won't sell because it is too intense for guests.

![](https://i.gyazo.com/e0b3a590dcc93a415f972e34051752ce.png)

Tried with both moon juice and drinks stall and guests are complaining about the intensity of the drink without buying it, but staying thirsty.

**Comment by duncanspumpkin** [comment] 2015-11-15 19:43
can you upload the save.

**Comment by hypocube** [comment] 2015-11-15 19:46
Uploaded to mediafire because github doesn't support file

http://www.mediafire.com/download/t3w18drvcglzizl/Coasterization+of+Mars.sv6

**Comment by HaasJona** [comment] 2015-11-15 20:01
It looks like the guests are actually getting sick from buying moon juice.

**Comment by Gymnasiast** [comment] 2015-11-15 20:22
That's very likely. The guy that created it even comments it won't work in vanilla, which means it must be corrupted.

However, if that corruption is caused by OpenRCT2, we would still need to investigate.

**Comment by hypocube** [comment] 2015-11-15 20:32
I got both of these on Amity Airfield.

![](https://i.gyazo.com/6e2a163518d37003b0f4173c9439f6e1.png)
![](https://i.gyazo.com/3b0e283ba1175009d3d9bec27278f8e6.png)

save file - http://www.mediafire.com/download/96hw0ha15passo0/Amity+Airfield.sv6

**Comment by IntelOrca** [comment] 2015-11-15 20:36
What object is this - is it from an expansion pack or is it custom?

**Comment by HaasJona** [comment] 2015-11-15 20:36
At least, I couldn't reproduce this issue with a new Moon Juice stall in a fresh park. Also rebuilding the Moon Juice stall in the submitted park also seems to help with the problem.

**Comment by hypocube** [comment] 2015-11-15 20:40
Moon Juice is from an RCT2 expansion. I opened my Amity Airfield save in vanilla RCT2 and the messages disappeared. I also opened the Coasterization of Mars save in vanilla RCT2 and the messages disappeared there too

**Comment by HaasJona** [comment] 2015-11-15 20:42
It's from Time Twister expansion (MOONJUCE.DAT)

**Comment by IntelOrca** [comment] 2015-11-15 20:43
Is ```moonjuce``` classified properly and have all the correct flags? It should be compared with another drink stall object.

**Comment by HaasJona** [comment] 2015-11-15 20:47
How do you check? It's in the stall category and it has the same UI as other drink stalls.

**Comment by IntelOrca** [comment] 2015-11-15 20:51
Use trigger-death's object browser or inspect the object structs in the code when OpenRCT2 is running.

**Comment by HaasJona** [comment] 2015-11-15 21:00
Flags look fine
![bildschirmfoto von 2015-11-15 21-58-21](https://cloud.githubusercontent.com/assets/4310707/11170993/452b2432-8be4-11e5-8186-e74452a0dbc1.png)
![bildschirmfoto von 2015-11-15 21-59-00](https://cloud.githubusercontent.com/assets/4310707/11170994/4552d3e2-8be4-11e5-8dab-1bed7e4cc364.png)

**Comment by Stryder7x** [comment] 2015-11-17 03:25
I was having this same issue with the "guests ignore intensities" cheat enabled.  Pretty sure I haven't had this problem since disabling that cheat.

**Comment by hypocube** [comment] 2015-11-17 03:36
I did not have the cheat enabled when doing the scenario, and toggling it on/off did not change the intensity of Moon Juice.

**Comment by Stryder7x** [comment] 2015-11-17 03:41
Strange.  In my case it was a Drinks Stall that was "too intense" for guests.  This was on the Gravity Gardens scenario, and I've only experienced the issue with OpenRCT2.

**Comment by osconnoisseur** [comment] 2015-11-20 01:34
Does this only occur with shops from the expansion pack, or are there vanilla RCT2 items where this happens.

And stop putting alcohol in the moon juice! :)

**Comment by hypocube** [comment] 2015-11-20 03:57
The glitch has stopped happening on Coasterization of Mars, so if there was an update then it fixed it.

**Comment by hypocube** [comment] 2015-11-20 04:58
So far I've discovered that if the guests think the drinks are good value, then they won't complain about them being too intense. If the price goes above that line, then the drinks will be too intense for them.
So basically the drinks have to be cheap or they will be too intense.

**Comment by IntelOrca** [comment] 2015-11-20 08:28
> So basically the drinks have to be cheap or they will be too intense.

Thanks, that could narrow down where the problem is considerably.

**Comment by osconnoisseur** [comment] 2015-11-20 15:55
I wonder if the problem is that the game isn't handling stalls from the expansion pack properly.

@hypocube, what did you mean when you said you changed it to a different drink stall? Did you demolish the current one and build one anew?

**Comment by hypocube** [comment] 2015-11-20 16:02
I demolished moon juice to build drinks stall. The guests will still say it's too intense if it is above the value price line.

**Comment by duncanspumpkin** [comment] 2015-11-20 17:06
Found the issue will have the fix up shortly.

**Comment by duncanspumpkin** [comment] 2015-11-20 17:13
Fixed in the pre-release

**Closed by duncanspumpkin** 2015-11-20 17:13 UTC
Labels: bug
