### ISSUE TITLE
Custom music files not deselected after running "remove_unused_objects" command

### ISSUE THREAD

**Issue by Xtreme97-RCT** [OpenRCT2/OpenRCT2#19509] opened 2023-02-27 17:49 UTC
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.3-304-g777fea6 (777fea6 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When running the remove_unused_objects console command from the console window, custom music tracks that haven't been used in the park don't get deselected. This can cause bloat when saving exported parks as the selected custom music tracks will be included and are usually a significant part of the file size.

![music_selection_command](https://user-images.githubusercontent.com/64152940/221642889-b819d014-6851-4498-b5d8-263abc514e7a.png)

![music_selection_after](https://user-images.githubusercontent.com/64152940/221642915-d461104d-b489-42a4-86e0-301bafd0a438.png)

### Steps to reproduce

1. Select a custom music parkobj file in Object Selection.
2. In console window, use the command remove_unused_objects
3. Return to Object Selection to view custom music. Unused music files have not been removed.

**Comment by Gymnasiast** [comment] 2023-02-27 19:19
This is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/19434.

**Closed** 2023-03-01 09:20 UTC
Labels: bug
