### ISSUE TITLE
Bugs with placing and hiring staff on multiplayer client

### ISSUE THREAD

**Issue by FlukiestEmperor** [OpenRCT2/OpenRCT2#2179] opened 2015-11-01 22:33 UTC
A few bugs with hiring and placing staff in multiplayer. This only affects the client.

Hiring any new staff will bring up a (random?) guest. If there are no guests in the park, it will just bring up a blank guest window and trying to move it will crash the game.
![bug](https://cloud.githubusercontent.com/assets/1393110/10871753/5f872752-80b5-11e5-9ba6-7ff947a71253.PNG)

Trying to place staff on the client is not reflected on the server. Placing staff on the client causes a desync, and on the server the staff will say it still needs to be placed.

**Comment by duncanspumpkin** [comment] 2015-11-01 22:39
Duplicate of #1943.

**Closed by duncanspumpkin** 2015-11-01 22:39 UTC

**Comment by FlukiestEmperor** [comment] 2015-11-01 22:50
#1943 Should be renamed. Placing a new staff does not cause the client or server to crash. Placing staff works just fine for the client, it just isn't reflected on the server and causes a desync.

**Comment by IntelOrca** [comment] 2015-11-01 22:53
@FlukiestEmperor it used to crash, it has probably improved since. Post your new findings in #1943.
