### ISSUE TITLE
Crash upon placing track, and certain tracks missing/ corrupted

### ISSUE THREAD

**Issue by 5percentWasTaken** [OpenRCT2/OpenRCT2#16967] opened 2022-04-10 16:05 UTC
### Operating System

Android 12

### OpenRCT2 build

3.5.1

### Describe the issue

Some tracks don't appear at all, being missing or corrupted, while the ones that aren't, crash the game upon placement

### Steps to reproduce

1. Open scenario
2. Open place track menu
3. Find desired track
4. Place track (if missing or corrupted, try another)

### Attachments

https://user-images.githubusercontent.com/83603702/162628522-ce9a9092-de10-46cb-bd91-d80a0467a951.mp4

**Comment by janisozaur** [comment] 2022-04-10 16:30
Duplicate of already solved #16308

**Closed by janisozaur** 2022-04-10 16:30 UTC
Labels: bug
