### ISSUE TITLE
Changing sign colour crashes the game

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2331] opened 2015-11-17 22:05 UTC
Tested with aade14b, gcc 5.2 & clang 3.7, Linux 4.2.5-1-ARCH

1. Start new park
2. Place a sign
3. Right-click the sign
4. In the just-opened "Banner" window, select different colour than the default one already selected
5. Crash

No backtrace available

**Comment by duncanspumpkin** [comment] 2015-11-17 22:11
Can't reproduce on windows. Do you mean a sign or a banner and do you mean  a small or a large sign.

**Comment by HaasJona** [comment] 2015-11-17 22:12
Can't reproduce on Linux, using aade14ba033519adfe918bdbd34a8145d8535fe6 as well.

**Comment by janisozaur** [comment] 2015-11-17 22:24
Ok, somewhat more detailed steps:
1. Start openrct2
2. Start new scenario "victoria falls", first from the list
3. Close welcome screen, select "place scenery…", select "signs and items for footpaths", select "Sign", place it on the only available footpath tile
4. Save the game
5. Right-click the sign
6. Try changing the colour

**Comment by duncanspumpkin** [comment] 2015-11-17 22:28
Okay thats called a banner.

**Comment by HaasJona** [comment] 2015-11-17 22:32
Will try to reproduce tomorrow.

**Comment by duncanspumpkin** [comment] 2015-11-17 22:33
I was able to reproduce it once crashing in the drawing function.

**Comment by duncanspumpkin** [comment] 2015-11-17 22:38
I know the cause same issue as #2327. Fixed in the pre-release.

**Closed by duncanspumpkin** 2015-11-17 22:38 UTC
Labels: investigate

**Comment by janisozaur** [comment] 2015-11-17 22:49
Thanks, it also fixed another minor bug I was chasing.
