### ISSUE TITLE
Recent/curent dev builds of OpenRCT2 unable to install on my Windows 10 laptop

### ISSUE THREAD

**Issue by RT12Productions** [OpenRCT2/OpenRCT2#11056] opened 2020-03-26 00:51 UTC
**OS:** Windows 10 Update 19H2

I tried a few of your most recent dev builds (within the past few days) of OpenRCT2, only to have this error message:  **Cannot install on this PC**:  Please contact the software publisher for a version that can install on your PC.  This game has installed before on my laptop PC, and the update currently installed on it works fine.
Also:  Your debug symbols .ZIP file corresponding with the game installer update now has fewer files; it usually has 5 files, but now has only 3.  What's up with that?!?!
Please resolve these issues.  Thank You!

**Comment by janisozaur** [comment] 2020-03-26 06:09
Duplicate of #11054. There are enough debug symbols in the archive for processing to work.

**Closed by janisozaur** 2020-03-26 06:09 UTC
