### ISSUE TITLE
Parks not Saving!

### ISSUE THREAD

**Issue by tylere661** [OpenRCT2/OpenRCT2#21065] opened 2023-12-08 10:26 UTC
### Operating System

windows 11 64 bit

### OpenRCT2 build

openrct2 0.4.6-178

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error, This is a development issue

### Describe the issue

I cannot save any of my parks.  When I try to save, a window comes up saying report issue to github.

### Steps to reproduce

Start a new park, then try to save the park as a new file.  A window comes up saying park cannot be saved.

### Attachments

[a5ddc2a1-dbbd-4cb3-b35c-6fdc53579830(b40b5da_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/13612883/a5ddc2a1-dbbd-4cb3-b35c-6fdc53579830.b40b5da_x86-64.dmp.gz)

**Comment by zzril** [comment] 2024-01-21 17:57
Possible duplicate of #20845 .

Do you have write permissions for the directory you are trying to save the park in?

**Comment by tylere661** [comment] 2024-01-21 18:04
I tried saving a park to a different directory and it worked.  A lot of mess with my one drive too.  Thank you!

**Comment by ZehMatt** [comment] 2024-01-21 18:05
Duplicate and user figured it out.

**Closed by ZehMatt** 2024-01-21 18:05 UTC
Labels: bug
