### ISSUE TITLE
Inclined path bug at entrance

### ISSUE THREAD

**Issue by andy55699** [OpenRCT2/OpenRCT2#19153] opened 2023-01-15 16:54 UTC
### Operating System

Windows 10,64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC), Issues building the game

### Describe the issue

Whenever there is a inclined path at the grid directly after entrance gate, some guests would not be able to land on the proper inclined path but get off from it.

See attached image and saved file in .park format.

This bug is mentioned by @MarcelVos 
 https://www.youtube.com/watch?v=XwPhu1J-tAE&embeds_euri=https%3A%2F%2Fforums.openrct2.org%2F&feature=emb_title

P.S. This bug also exists in earlier versions before v0.3.5.

### Steps to reproduce

Whenever there is a inclined path at the grid directly after entrance gate, some guests would not be able to land on the proper inclined path but get off from it.

See attached image and saved file in .park format.

 

P.S. This bug also exists in earlier versions before v0.3.5.

### Attachments

[path bug2.zip](https://github.com/OpenRCT2/OpenRCT2/files/10420698/path.bug2.zip)
![pathbug2 thumb png 5a30018f1209d3fa78b60a7523067ebe](https://user-images.githubusercontent.com/92691705/212554631-6e8cbb45-44ad-46d0-b153-afe40a35ab4a.png)

**Comment by ocalhoun6** [comment] 2023-01-15 20:03
Duplicate of #14486

**Comment by rik-smeets** [comment] 2023-03-11 10:43
Closed as duplicate.

**Closed by rik-smeets** 2023-03-11 10:43 UTC
Labels: bug
