### ISSUE TITLE
Coaster shows up in Rides window even if it isn't built yet

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2888] opened 2016-02-05 12:34 UTC
If you build a track with a predefined design, it'll show up in the Rides window when you haven't even built it yet. It'll show as 'Closed'.

**Comment by duncanspumpkin** [comment] 2016-02-05 12:40
Yes that is how the game allocates a ride. We could improve the ride list to check for something else that would confirm it exists.

**Comment by IntelOrca** [comment] 2016-02-05 13:27
This is expected behaviour, its also the same as when you build a custom track. The ride is in the ride list before you place the first track piece.

**Comment by Phyxion** [comment] 2016-02-05 13:48
But it does not make sense from a user point of view.

**Comment by Nubbie** [comment] 2017-01-02 19:10
Duplicate off #578?

**Closed** 2017-01-02 20:53 UTC
Labels: duplicate
