### ISSUE TITLE
"Dinghy" boat hire crashes the game when first boat leaves the station

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#2215] opened 2015-11-06 00:25 UTC
I have always thought it to be odd that there was no dinghy boat hire originally, so i tried to make one using the cheat "show vehicles from other tracks" or what it's named.

![img](http://puu.sh/laTiM/db27c44b89.png)

I think the dinghy vehicles should attempt to use boat hire mechanics rather than the original "Dinghy slide" mechanic (I'm assuming that is what it tries to do) in this case

**Comment by PFCKrutonium** [comment] 2015-11-06 00:32
Same as #2110

**Comment by Patrik356b** [comment] 2015-11-06 00:50
I did look for such but didn't find anything. I don't think it makes a
difference if the vehicle type is single or trains but i don't know.

On Fri, Nov 6, 2015 at 1:32 AM, Krutonium <notifications@github.com> wrote:

> Same as #2110 <https://github.com/OpenRCT2/OpenRCT2/issues/2110>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenRCT2/OpenRCT2/issues/2215#issuecomment-154245562>.
>



-- 
Best regards; Hexile

**Comment by PFCKrutonium** [comment] 2015-11-06 02:22
I think it has to do with Tracked rides being off track, if that makes any sense.

**Comment by Patrik356b** [comment] 2015-11-06 03:30
It should be pretty straightforward if debug is on/attached to see at which
point the code breaks. I think it is the wrong mechanism being executed as
mentioned before

**Comment by vzybilly** [comment] 2015-11-06 04:04
I feel this would be more of the issue, tracked cars off track... finding
the spot would be hard though... does this issue effect go karts? we might
need to change the cheat so tracked rides can only have tracked cars and
untracked rides have untracked cars... then when the real issue is found,
revert the cheat fix...

**Comment by duncanspumpkin** [comment] 2015-11-06 06:55
It's crashing in unimplemented code. And this is a duplicate of #2110. We might be able to fix it with a hook

**Closed by duncanspumpkin** 2015-11-06 06:55 UTC

**Comment by IntelOrca** [comment] 2015-11-06 08:21
I can't say its high priority at the moment and not targeted for 0.0.3 as this is a hack against the rules of the game.

**Comment by Patrik356b** [comment] 2015-11-06 13:41
Having rentable dinghies, rafts and other boat type vehicles I think would
be an improvement to creativity without affecting the game negatively.
Otherwise I agree

**Comment by Patrik356b** [comment] 2015-11-06 13:43
Mono rail rental doesn't make sense as it's not something that should float

**Comment by vzybilly** [comment] 2015-11-06 14:39
it could be a boat made to look like one.

**Comment by osconnoisseur** [comment] 2015-11-06 17:07
I think right now, we should not even bother at all about bugs in cheats. Cheats are, by definition, something that breaks the normal gameplay. Let's get the game working normally, and then we can hack it up with cheats.

**Comment by vzybilly** [comment] 2015-11-06 17:24
could we remove the boat ride from the effects of this cheat, since that's
the only real thing breaking from this cheat...

**Comment by duncanspumpkin** [comment] 2015-11-06 17:39
As @osconnoisseur said we are not going to go fixing a crash that happens very rarely only when activating a cheat and happens in a vanilla function. It will eventually get fixed when vehicle-update is finished so there is no reason to disable the cheat for this ride. Until then you know it crashes, so don't do it.
