### ISSUE TITLE
Placing banners is messed up when playing RCT1 scenarios 

### ISSUE THREAD

**Issue by BobbyS38** [OpenRCT2/OpenRCT2#7888] opened 2018-08-13 10:28 UTC
**OS:** Windows 10
**Version:** 0.2.0-277
**Commit/Build:** 9e517a5

Placing banners is really messed up when I start a RCT1 scenario. I can't place banners in the right direction I want to. I can only change the direction by using the tile inspector. 

**Screenshots / Video:**

https://files.gitter.im/BobbyS38_gitlab/KXsa/bandicam-2018-08-13-11-44-04-005.mp4

Is there any fix for that?

**Comment by Broxzier** [comment] 2018-08-13 11:51
It's very strange that it only happens to RCT1 scenarios for you. It's working fine one my end, even in the exact same scenario from RCT1 (no remake). Can you provide a saved game here?

**Comment by Gymnasiast** [comment] 2019-03-31 20:05
I tried loading your scenarios, but I cannot reproduce it any more (using commit ba08997c33f995561b7c1ec5c6c2ff951caf10ef).

I'll close this issue for now, if the problem returns please let us know.

**Closed by Gymnasiast** 2019-03-31 20:05 UTC
Labels: bug, investigate
