### ISSUE TITLE
Scenario name aliases do not work correctly

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#3093] opened 2016-03-05 04:36 UTC
For example, **Mythological - Cradle of Civilization**, 
```
(...)
<Mythological - Cradle of Civilization>
STR_SCNR    :신화 - 문명의 요람
STR_PARK    :신화의 광기
STR_DTLS    :특별한 고고학적 가치를 가진 섬을 소유하게 되었습니다. 이 지역의 풍부한 신화적 유산을 기반으로 한 테마파크를 건설해서 유산 보존 기금을 마련하기로 결정했습니다.
(...)
```

results like this:

![image](https://cloud.githubusercontent.com/assets/10726524/13545764/8a0fd8b2-e2d9-11e5-85be-59127e130c83.png)

If I edit like this (not Civilization but Civili**s**ation):
```
(...)
<Mythological - Cradle of Civilisation>
STR_SCNR    :신화 - 문명의 요람
STR_PARK    :신화의 광기
STR_DTLS    :특별한 고고학적 가치를 가진 섬을 소유하게 되었습니다. 이 지역의 풍부한 신화적 유산을 기반으로 한 테마파크를 건설해서 유산 보존 기금을 마련하기로 결정했습니다.
(...)
```
Then it works.

c.f. I used TTP demo ZIP files
p.s. There is no alias for "Utopia"(=Utopia Park)

**Comment by AaronVanGeffen** [comment] 2016-03-05 17:30
That would be because the game uses UK English internally, which prefers 'civilisation' over 'civilization'.

**Comment by IntelOrca** [comment] 2016-03-05 18:49
Aliases are only used for the actual filenames, you must specify the English (UK) name in the language file.

**Comment by Gymnasiast** [comment] 2016-03-06 14:46
I'm closing this as it works as intended. The required changes have already been made to korean.txt by the OP.

**Closed by Gymnasiast** 2016-03-06 14:46 UTC
Labels: non-bug
