### ISSUE TITLE
Queue lines of 2 rides merge 

### ISSUE THREAD

**Issue by runelaenen** [OpenRCT2/OpenRCT2#2579] opened 2015-12-29 10:17 UTC
Original: https://openrct2.org/forums/topic/736-2-bugs/

If I build a dueling coaster with 2 station and try and put the queue line entrances next to each other the queues will merge into one leading from one ride entrance to the other, it works fine on queue lines from different rides.

![Image1](https://openrct2.org/forums/uploads/monthly_2015_12/working.png.707802b9be19f1e6116fefbbdf5c3ed1.png)

![Image2](https://openrct2.org/forums/uploads/monthly_2015_12/5681881073c0d_notworking.png.af19d4710349ab4e08ae65a311d08476.png)

**Comment by raidcookie** [comment] 2016-01-03 17:11
As a temporary fix you can place a hedge or fence to separate the tiles, build the path and then remove the hedge and it will stay separated.

**Comment by IntelOrca** [comment] 2016-01-03 17:17
Does this happen in vanilla?

**Comment by raidcookie** [comment] 2016-01-03 17:52
It could also be because it's one with 2 stations, instead of 2 separate rides and thus treating the paths differently.

**Comment by jensj12** [comment] 2016-01-05 18:35
This doesn't happen in vanilla,vanilla never merged queue paths. Queue path merging/extending was added in OpenRCT2 to be able to build a queue path next to another path. If (when building a queue path tile) it finds two queue path tiles next to it, it checks if they are from the same ride (or no ride) and merge them if that's the case. This works perfectly unless you have two queues from the same ride. I can't come up with any occasion where you'd want to merge two queue paths from the same ride.
Fix: check if at most one of the queue paths is connected to an entrance before merging (instead of checking if they belong to the same ride), should fix this and not change any other situation

**Comment by Broxzier** [comment] 2016-04-23 11:27
I cannot reproduce this anymore.

**Comment by marcovmun** [comment] 2016-04-23 12:05
I can reproduce this issue. It only happend when it is one ride with two different entrances/stations

![image](https://cloud.githubusercontent.com/assets/16606883/14761275/bf76a456-095b-11e6-8bc3-2f7fadc0e374.png)

**Comment by jensj12** [comment] 2016-04-23 12:09
Indeed still happens in the way I described it earlier. The game checks for the connected ride ID instead of just a connection with a station.

**Comment by IntelOrca** [comment] 2016-04-23 12:09
@marcovmun I think that is an original bug... if you even call that a bug.

**Comment by marcovmun** [comment] 2016-04-23 12:52
It is for a part a orginal bug.
![oldrct2example1](https://cloud.githubusercontent.com/assets/16606883/14761423/9ef5e880-0961-11e6-8e1d-168846f6a177.png)
_Orginal RCT2_

But because of the chance in the chance in queue path placing the bug is bigger. Now when a path is already connected with a footpath, the same happend

**Before:** 
![openrctbefore](https://cloud.githubusercontent.com/assets/16606883/14761439/f7636358-0961-11e6-803e-ad37556e1420.PNG)
**After:**
![openrct](https://cloud.githubusercontent.com/assets/16606883/14761442/ff2e6a6a-0961-11e6-8745-28a2aef7d9fe.PNG)
_OpenRCT2_

The rollercoaster that I build in my first example is a Steel twister roller coaster "raven racer" design with scenery enabled without any changes after. So the design builder build the queue 
immediately wrong

**Closed** 2016-04-25 11:12 UTC
Labels: bug
