### ISSUE TITLE
Peeps can leave the park on boats and/or get stuck

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#6495] opened 2017-10-16 16:28 UTC
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** 6a66ef86682877188dd3b1a83b482506e33f0778

Original bug! Also in RCT1.
Build a water ride where the vehicles can move freely (rowing boats, jetskis, ...) in a water region that extends beyond the parks boundaries. The peeps will eventually move outside of the park boundaries.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start a game with the scenario "Roman Village" from RCT1s "Corkscrew Follies"
2. Observe "Boat 2" from "Canoes 1"

**Screenshots / Video:**
![leave_park](https://user-images.githubusercontent.com/8963459/31623461-cb14f1de-b29f-11e7-84fb-d7dfb1385353.png)

**Comment by Nubbie** [comment] 2017-10-16 17:27
At the same time, if they just are rowing outside the boarders, I think that would be okay. 
It's not like you can see the parks boarder when rowing in a boat, and think it's unlikely there would be any way of realistically knowing where the 'edge' of the park ends.
Look at "Botany Breakers" for example, it's on a island, I think they should realistically be able to row outside the park boarders.

However,
if they can leave the map when hitting the edge, no

**Comment by ccoors** [comment] 2017-10-16 19:09
Even worse, in this scenario they can get stuck outside the park. That is a general problem with narrow water passages, but especially in this scenario it is unwanted.

![stuck_boats](https://user-images.githubusercontent.com/8963459/31630204-3fc98e2a-b2b6-11e7-920b-2d01a24b1aef.png)

**Comment by Gymnasiast** [comment] 2017-10-16 19:44
I don't really consider guests rowing outside the boundaries a bug. Just think of it: that's exactly what they would do IRL.

**Comment by rwjuk** [comment] 2017-10-19 18:17
I'm inclined to agree that the fact they can leave isn't really a bug. If they cannot return over the park boundary however, that is a bug.

**Comment by duncanspumpkin** [comment] 2017-10-20 07:14
The AI for boats is ridiculously simple it's really easy for them to get stuck. It does nothing intelligent to get around blockages. Maybe at some point a better AI could be implemented.

**Comment by ccoors** [comment] 2017-10-20 08:17
Most of this is fine for me, the only problem I'm having with this is that the boats get stuck in an original scenario from RCT1 without any modification.

Thanks for the "Bug of the year 2017" though :)

**Comment by Liampie** [comment] 2017-10-20 14:50
It's a design flaw in that scenario. I don't think OpenRCT should mess with the design of the original scenarios.

**Comment by Nubbie** [comment] 2017-10-20 15:38
OpenRCT should mess with broken scenarios to correct issues in my opinion

**Comment by Gymnasiast** [comment] 2017-10-27 09:38
Ok, here is my verdict:
- People leaving the park on a boat is not a bug, provided they can go back as well.
- We only fix obvious mistakes in scenarios. Widening a (perceived to be) poorly designed water channel goes far beyond that.
- Boats getting stuck and doing nothing intelligent to get moving _is_ a bug. But I consider that point to be a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/866.

Because of this, I will close this issue.

**Closed by Gymnasiast** 2017-10-27 09:38 UTC
Labels: Bug of the year 2017
