### ISSUE TITLE
Stat window not showing times on more than 4 stations

### ISSUE THREAD

**Issue by ciscodisco1** [OpenRCT2/OpenRCT2#16280] opened 2021-12-20 01:15 UTC
### Operating System

Windows 10 64bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (ee62962 on develop) provided by GitHub

### Describe the issue

A lot of the windows for stats does not contain everything properly. An example of this is my 3 transport rides with 5, 6 and 7 stations. When you open the time and length of each section it can't display it properly.

### Steps to reproduce

1. 
2. 
3. 

### Attachments

![Coaster Dreams 2021-12-20 02-09-50](https://user-images.githubusercontent.com/31996583/146698543-004275f0-c154-48f5-bb77-1563aa14ac4b.png)
![Coaster Dreams 2021-12-20 02-09-28](https://user-images.githubusercontent.com/31996583/146698552-47974cd2-0e61-40cb-b34a-4ca532bf283d.png)

**Comment by James103** [comment] 2021-12-20 01:17
Likely duplicate of: #15953

**Closed** 2021-12-20 07:01 UTC
Labels: bug
