### ISSUE TITLE
Train supports draw differently based on build direction

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#15354] opened 2021-09-05 18:50 UTC
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (b2d0b54 on develop) provided by GitHub

### Describe the issue

Supports missing from train ride supports when building backwards. (Ride direction is to the left)

![image](https://user-images.githubusercontent.com/3454156/132138067-ad57ccff-5ee8-4665-8401-c414d5406406.png)

I don't know if this is a regression, but I suspect it's not. It probably is an original bug.

### Steps to reproduce

1. Build a train ride
2. Build it diagonally backwards
3. Supports don't show up

**Comment by Gymnasiast** [comment] 2021-09-05 19:01
This is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/5281.

**Closed by Gymnasiast** 2021-09-05 19:01 UTC
Labels: bug
