### ISSUE TITLE
Guests get stuck on closed ferris wheels.

### ISSUE THREAD

**Issue by wolfreak99** [OpenRCT2/OpenRCT2#4003] opened 2016-07-07 21:46 UTC
**Version:** 0.0.5
**Commit/Build:** 6c0d4c5

While closing down a park, I closed all the rides through the ride list, and set the speed to hyper to get the guests out quicker, but I noticed that anyone riding ferris wheels are stuck on because while the ride is closed, it does not continue to rotate until the guests are off. 

Unsure if it's reproducable in vanilla - vanilla is broken.

**Comment by WhenPenguinsAttack** [comment] 2016-07-08 07:26
A temporary workaround for this is to place the ride into construction mode and exit out of it right away.

**Comment by SijmenSchoon** [comment] 2016-07-08 10:11
I believe you can also close the ride a second time, forcing them out, as another temporary workaround

**Comment by ThePsionic** [comment] 2016-07-08 15:18
I'm fairly sure this is also true with non-station block breaks - closing twice has always been the fix for this.

**Comment by SijmenSchoon** [comment] 2016-07-08 17:02
Okay, I've been experimenting a bit. I could reproduce this with OpenRCT2 commit 52ed90ed95a413d197fbe115707f4700f226f22d on OS X two out of three times.

The third time it behaved exactly like the vanilla game behaves 100% of the time in my testing: finishing the "circuit", then going into ejection mode — letting every peep out by turning one seat at the time until everyone is out — and then closing.

I'm going to dig through the code and try to find where this is going wrong.

**Comment by SijmenSchoon** [comment] 2016-07-08 21:27
After some digging, debugging and Excel magic I've knocked this together:

![graphy goodness](http://i.imgur.com/XlbkK5h.png)

Starting at the left, you can see the ferris wheel completing its circuit before starting to kick out all peeps. It then arrives, unloads the peeps at the bottom, moves to the end of the station (which is instant, because it's... not a station), waits for passengers to get in (not sure why, whatever), waits to depart and then rotates to the next position, as it's supposed to. It then again arrives and does the whole thing again.

After this, things go wrong, as it refuses to rotate to the next position and gets in an infinite loop of kicking out the passengers in the exact same seat. Why it does this, I've yet to figure out.

**Comment by SijmenSchoon** [comment] 2016-07-08 21:45
As a side note, I love that graph. I'd love to have this graph in the game somewhere.

**Closed** 2016-07-08 21:45 UTC
