### ISSUE TITLE
Underground/inside mode stuck on

### ISSUE THREAD

**Issue by X123M3-256** [OpenRCT2/OpenRCT2#3520] opened 2016-05-07 21:08 UTC
**OS: Happens on both Windows and Linux** 
**Version: 0.05-develop, though this has been going on a while** 
**Commit: 305fe08, but see above** 

Sometimes, when placing scenery, the underground/inside mode gets stuck on. Turning it off via the menu works, but as soon as you try to place a scenery piece it turns on again. I know that it is supposed to switch to this mode when placing a scenery piece underground, but the problem is that it doesn't switch back when you start building above ground again. Once it has got "stuck", the only way to correct it is to restart the game - reloading the park or quitting to menu does not help.

Unfortunately, I am unable to consistently reproduce this bug, so this report isn't going to be very helpful, but it's been present long enough that I thought I'd at least report it, as I haven't seen this mentioned elsewhere. It seems to have something to do with using the menus while the cursor is underground, but this alone isn't sufficient to trigger it. It only seems to affect certain types of scenery - mainly base blocks, and never walls.

**Comment by Ziscor** [comment] 2016-05-07 21:29
This also happens (or used to happen) when using multiplayer with Clearance Checks disabled. Are the two things related, by any chance?

**Comment by X123M3-256** [comment] 2016-05-07 21:40
Sounds like it's the same issue. I also have clearance checks disabled most of the time, and for me this tends to happen when switching it on and off. Try as I might, I can't figure out how to reproduce the issue reliably - it just keeps happening randomly.

**Comment by Ziscor** [comment] 2016-05-08 06:37
I tried figuring out why this only happened for me in Multiplayer and I seem to have a sure-fire way to reproducing this:
So apparently in Multiplayer many people do their own thing right? Once Clearance Checks weren't enabled, if someone was in the process of making something that was underground at that moment, all clients would have this issue we are talking about. I can confirm only flat pieces and not walls are affected by this. 

However, if you were to uncheck the Disable Clearance Checks cheat, the effect was dropped even after checking it again. Then, you'd have to go into construction mode of the ride again for it to happen.

**Comment by Liampie** [comment] 2016-05-08 07:27
This has happened to me a lot in single player. It always involved placing large scenery.

**Comment by Ziscor** [comment] 2016-05-08 08:23
@Liampie That's strange... once I triggered this with my steps and tried placing large scenery, the game wouldn't let me. Raising heights didn't work either. All it says is "Can't position here..."

**Comment by Broxzier** [comment] 2021-08-09 12:59
Closing this as it's been a long time since I've seen this or heard from anyone else about this bug.

**Closed by Broxzier** 2021-08-09 12:59 UTC
Labels: bug
