### ISSUE TITLE
Garbage cans get full to fast.

### ISSUE THREAD

**Issue by remcooo96** [OpenRCT2/OpenRCT2#2511] opened 2015-12-18 09:37 UTC
In openrct gargage cans are full after one piece of trash. So your paths will be lithered with trash.

**Comment by duncanspumpkin** [comment] 2015-12-18 10:41
They get full after three pieces and there is also a rand in there as well so it should take about 5 pieces on average. Vanilla  rct2 had a bug preventing bins from filling at all.

**Comment by remcooo96** [comment] 2015-12-18 10:48
Is 5 pieces per garbage can not extremely low? The average can is full in just 3 minutes. Maybe a way to extend this to 10 to 20 pieces? Much more realistic

**Comment by AaronVanGeffen** [comment] 2015-12-18 11:03
This is a duplicate of #1860.

**Comment by remcooo96** [comment] 2015-12-18 11:14
Thanks, but still no solution. Just because of this reason I am playing vanilla now.

**Comment by Gymnasiast** [comment] 2015-12-18 11:23
As this is a duplicate of #1860, please move the discussion to there.

**Closed** 2015-12-18 11:44 UTC
Labels: duplicate
