### ISSUE TITLE
Some attractions names replaced by numbers in the "visited attractions" tab of a visitor.

### ISSUE THREAD

**Issue by CutterXYZ** [OpenRCT2/OpenRCT2#7820] opened 2018-07-24 18:40 UTC
**OS:Windows 10**
**Version: 0.2.0**
**Commit/Build: 0aff800**

In a visitor's "Visited attractions" tab, some attractions are shown as a number instead of their name.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Click on a visitor.
2. Click on the "visited attractions" tab.

**Screenshots / Video:**
![Screenshot](https://user-images.githubusercontent.com/29694177/43159026-7aced338-8f81-11e8-8b5c-4e08666108a3.png)

**Save game:**
[Jardins Verdoyants.txt](https://github.com/OpenRCT2/OpenRCT2/files/2224934/Jardins.Verdoyants.txt)

**Comment by AaronVanGeffen** [comment] 2018-07-24 18:53
Thanks for the report. It's a known issue in the last stable release, and a duplicate of #7674. It's been fixed as of 86ca6be58b6ab443f56e647756d6f94832822962. You might want to switch to the development releases if the issue is bugging you.

**Comment by Gymnasiast** [comment] 2018-07-24 18:53
This bug has already been solved in `develop`. Generally, it is recommend you use the `develop` version instead of `release`.

**Closed** 2018-07-24 18:53 UTC
Labels: duplicate
