### ISSUE TITLE
Gaps in land with construction rights in Six Flags over Texas and other parks

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#17774] opened 2022-08-10 19:47 UTC
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-159-g59c31e8 (59c31e8 on develop) provided by GitHub

### Describe the issue

There are a few gaps in the area with construction rights in 'Six Flags over Texas', specifically under the parking lot next to the orange Titan coaster. Since similar issues in other base game parks were also fixed, I figured I'd report this one as well.

The same issue is also present in the empty 'Build your own Six Flags over Texas' park.

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

1. Open 'Six Flags over Texas'.
2. Select the park entrance.
3. Hide paths and vegetation
4. View the land rights next to the orange Titan coaster.

### Attachments

With parking lot and vegetation hidden:
![image](https://user-images.githubusercontent.com/20048660/184006099-f0dfe54b-7a34-4e1b-9fdd-263198354c3d.png)

With nothing hidden:
![image](https://user-images.githubusercontent.com/20048660/184006205-3ebba970-6a7c-443f-8867-08aca4782f17.png)

**Comment by Basssiiie** [comment] 2022-08-10 19:56
Another one in Urban Park (about halfway through the town, at x: 46, y: 47), which was mentioned on Discord a couple days ago, but hasn't gotten an issue yet:
![image](https://user-images.githubusercontent.com/20048660/184007980-f05b9771-b3b1-4ee8-95e6-41abe7afd36a.png)

Without anything hidden:
![image](https://user-images.githubusercontent.com/20048660/184008114-3aeed526-80ee-4625-97c0-57caa3d25f81.png)

**Comment by SpartanFrederic104** [comment] 2022-08-10 21:51
Doesn't this also happen in some of the RCT2 expansion scenarios (e.g. Mythological Madness)?

**Comment by Basssiiie** [comment] 2022-08-11 16:28
Yess you are right, there's two gaps on the small island left of the park entrance in Mythological Madness/Cradle of Civilization. 
![afbeelding](https://user-images.githubusercontent.com/20048660/184182866-3e02030c-8afd-4ce4-b49a-97c920ec3a7e.png)

If you know any more, please share them :)

**Comment by Basssiiie** [comment] 2022-08-11 16:31
Found another one in Robin Hood/Sherwood Forest.
![afbeelding](https://user-images.githubusercontent.com/20048660/184183507-bdc117d3-01a6-4da0-b6db-6efe2ecb5f9b.png)

**Comment by SpartanFrederic104** [comment] 2022-08-11 18:05
![Rock ‘n’ Roll Revival 2022-08-11 10-58-54](https://user-images.githubusercontent.com/61885939/184206899-f1022af2-c715-4c89-8c70-d93c4d637d40.png)
Spotted one in Rock 'n' Roll Revival, in the large forest outside the starting park boundaries.
![Schneider Shores 2022-08-11 11-01-24](https://user-images.githubusercontent.com/61885939/184207889-bee972ce-6afc-48c3-aea6-dbe9c761ff90.png)
A few construction rights tiles are also missing above the sea in Schneider Shores.
![Rocky Rambles 2022-08-11 11-03-35](https://user-images.githubusercontent.com/61885939/184208351-3bb02c7b-210c-401e-9921-81cdec05939a.png)
![Rocky Rambles 2022-08-11 11-03-49](https://user-images.githubusercontent.com/61885939/184208354-0c94b270-2004-4cb8-9501-2bb25f181a2c.png)
And wow there's quite a number of missing purchasable land tiles in Rocky Rambles. Good thing my Time Twister Redux scenario pack fixed these issues.
![Rocky Rambles 2 2022-08-11 11-04-56](https://user-images.githubusercontent.com/61885939/184208588-0a97c953-3dfb-4f3f-88d2-966b117c2d7b.png)
![Rocky Rambles 2 2022-08-11 11-05-05](https://user-images.githubusercontent.com/61885939/184208592-e073aa1c-f44a-4ea0-896f-e31160dd54dd.png)

**Comment by 733737** [comment] 2022-08-21 10:53
how would the developers patch these scenarios? Does anybody currently plan on implementing fixes for these issues? I know they patched a scenario that had a water coaster vehicle bug

**Comment by Basssiiie** [comment] 2022-08-21 11:45
@733737 there are already land ownership fixes for RCT2's "European Culture Festival", "Extreme Hawaiian Island" implemented [here](https://github.com/OpenRCT2/OpenRCT2/blob/d44a6c25beb753c16e3ef370a0b91ccf8eb3846e/src/openrct2/rct2/S6Importer.cpp#L531-L575) and for various RCT1 scenario's [here](https://github.com/OpenRCT2/OpenRCT2/blob/d44a6c25beb753c16e3ef370a0b91ccf8eb3846e/src/openrct2/rct1/S4Importer.cpp#L2478-L2507). This should be an easy issue any beginner could pick up. :)

**Comment by Basssiiie** [comment] 2022-08-21 11:52
Found 2 more issues in Schneider Cup:
![image](https://user-images.githubusercontent.com/20048660/185789557-05d04553-88a4-4729-abd7-42fecfbc7ba1.png)

The right one (the bush) cannot be bought at all while the left one can be bought as construction rights but that seems to be a mistake since the rest of the map is split between buyable = land, construction rights = water.

**Comment by SpartanFrederic104** [comment] 2022-09-04 17:29
![Sherwood Forest 2022-09-04 10-28-45](https://user-images.githubusercontent.com/61885939/188325954-421a3c69-cda8-457b-a4b8-1bf98fa35293.png)
Found yet another one in Sherwood Forest.

**Comment by Basssiiie** [comment] 2022-09-11 13:53
Another one in Utopia Park (Added Attractions/Corkscrew Follies), originally reported on [Reddit](https://www.reddit.com/r/rct/comments/xb6mt5/2_mildly_infuriating/).

![image](https://user-images.githubusercontent.com/20048660/189531161-e4dd54bf-7a4a-4e66-9421-0400fbb16eaa.png)

**Comment by Basssiiie** [comment] 2022-09-11 13:57
Another one in the back of Katies Dreamland, where the underground coaster is.

![image](https://user-images.githubusercontent.com/20048660/189531405-19576af0-6309-4367-8f7e-fc580baaf924.png)

**Comment by Basssiiie** [comment] 2022-09-12 16:07
Another [one reported in the same Reddit thread](https://www.reddit.com/r/rct/comments/xb6mt5/2_mildly_infuriating/io0e7w9/); in the Grand Canyon scenario (Wacky Worlds), there are some tiles in the water near the map's edge that cannot be bought for construction rights.

Reported positions are: Tiles `x131 y90`, `x132 y90`, `x133 y91`, `x134 y91`, `x135 y91`, `x136 y91`, but there is a second group further up the river which is also circled here:

![image](https://user-images.githubusercontent.com/20048660/189702457-473a8a22-f7c0-4a88-9b6c-0590f2a140ee.png)

Original image from Reddit:
![image](https://user-images.githubusercontent.com/20048660/189701683-743f998d-8145-487d-8eea-7124ce93d63d.png)

**Comment by Basssiiie** [comment] 2022-09-12 16:17
Might as well write a plugin script to find these. 😛 

Three more here:

![image](https://user-images.githubusercontent.com/20048660/189704653-e809e1d6-c3ac-4642-abd1-a5375369a2d5.png)

One more here at the river split:

![image](https://user-images.githubusercontent.com/20048660/189704905-42c1ff4c-2310-40f7-abd8-82378a4c1bc4.png)

**Comment by Basssiiie** [comment] 2022-09-12 16:29
South America - Incan Lost City, near the entrance:

![image](https://user-images.githubusercontent.com/20048660/189706432-2f7be709-40cc-4fcf-b763-633a3e96365f.png)

Near the peep spawn:

![image](https://user-images.githubusercontent.com/20048660/189706669-2db88a1b-d115-4fe5-8fc8-71654428805d.png)

In the corner with the temple of the golden llamas:

![image](https://user-images.githubusercontent.com/20048660/189707255-688b4df5-9efa-4fb9-9b1a-386ad727433b.png)

**Comment by Basssiiie** [comment] 2022-09-12 16:39
Maharaja Palace (Wacky Worlds), these should all be for sale.

On the right side of the palace:

![image](https://user-images.githubusercontent.com/20048660/189708147-24e5e5f5-c8f8-4167-854d-3919e43fb53b.png)

Underwater, near the little island:

![image](https://user-images.githubusercontent.com/20048660/189708527-e9cc335f-23f4-4b39-90f7-4c9173717a90.png)

Four groups in the center of the river, right behind the palace:

![image](https://user-images.githubusercontent.com/20048660/189708855-70fa41e5-8782-4546-b7bd-62cc447adca9.png)

**Comment by Basssiiie** [comment] 2022-09-12 16:51
Asia - Japanese Coastal Reclaim (Wacky Worlds)

One tile one the left side near the bullet train coaster, on the cliff edge, should be owned construction rights:

![image](https://user-images.githubusercontent.com/20048660/189710454-3b644c49-ee93-4a26-b545-19afc7582da8.png)

One tile on the right side in the centre of the temple, should be construction rights for sale:

![image](https://user-images.githubusercontent.com/20048660/189710700-ee9ae89c-b6b0-467b-ae8e-85ffb12714ec.png)

On the biggest of the two small islands, there's four spots that should either be construction rights for sale (left three spots), or land for sale (rightmost spot):

![image](https://user-images.githubusercontent.com/20048660/189711480-ece7239e-6e3d-4956-8ad4-79954f593b7f.png)

**Comment by Basssiiie** [comment] 2022-09-12 17:08
Antartica - Ecological Suvery (Wacky Worlds)

One single tile in the water near the igloos and the stairs down to the water, should be for sale:

![image](https://user-images.githubusercontent.com/20048660/189714264-6c663284-2a19-4123-949d-9b8a378ee1c1.png)

**Comment by Basssiiie** [comment] 2022-09-12 17:18
Mythological - Animatronic Film Set (Time Twister)

Three tiles in the canyon in the middle of the map, next to the station of the Harpies Rollercoaster:

![image](https://user-images.githubusercontent.com/20048660/189716348-9e415a99-405b-430d-94db-0a74a1d6541b.png)

**Comment by Basssiiie** [comment] 2022-09-12 17:24
Prehistoric - Jurassic Safari (Time Twister)

In the canyon, right under the Pterodactyl Terror flying rollercoaster, this tile should be construction rights:

![image](https://user-images.githubusercontent.com/20048660/189717402-f9b18c85-6f47-46af-93a4-1725d5c644ad.png)

**Comment by Basssiiie** [comment] 2022-09-12 17:38
Roaring Twenties - Schneider Cup (Time Twister) has a bunch more...

Right next to the biggest of the two cruise liners, 3 tiles split in two groups, should be construction rights for sale:

![image](https://user-images.githubusercontent.com/20048660/189718716-a2b4dfa3-bcf4-41ba-998d-d47085e97ae1.png)

Five tiles at the tip of the island closest to the biggest cruise liner, should be construction rights for sale (but note that it's right next to land for sale):

![image](https://user-images.githubusercontent.com/20048660/189719649-8b9e92eb-0e17-4f1d-816f-6ef7791ce7ab.png)

Two groups, left one with 2 tiles and right one with 4 tiles, next to the starting point for the race, should be construction rights for sale:

![image](https://user-images.githubusercontent.com/20048660/189719948-1684ce73-dc9d-463e-a43a-c523446a9c72.png)

**Comment by Basssiiie** [comment] 2022-09-12 17:58
Two more tiles in Rock 'n Roll - Rock 'n Roll that should be for sale:

One is next to the small waterfall and the Jet Plane Coaster:

![image](https://user-images.githubusercontent.com/20048660/189723519-49cae316-6b10-4a98-a745-08e09cd2cf0b.png)

The other one is in the far corner of the map in the forest:

![image](https://user-images.githubusercontent.com/20048660/189723768-389e8c03-d37d-4638-9949-194f48ce6bb6.png)

**Comment by SpartanFrederic104** [comment] 2022-09-12 18:04
Quite a number of them in Six Flags Magic Mountain (I will give out the coordinates in [x, y] format):
![Six Flags Magic Mountain 2022-09-12 11-00-53](https://user-images.githubusercontent.com/61885939/189724484-2bf192b9-ca42-41b4-9606-42c8d9ecfcee.png)
[104, 190], [105, 190], [108, 197]

![Six Flags Magic Mountain 2022-09-12 11-00-58](https://user-images.githubusercontent.com/61885939/189724552-8181310b-4975-4b5f-be9e-58a0d4f9e7cb.png)
[75, 167]

![Six Flags Magic Mountain 2022-09-12 11-01-14](https://user-images.githubusercontent.com/61885939/189724622-f9a4b30e-bbb6-45dc-97f8-58186aa5d5aa.png)
[61, 92-95], [62, 90-94]

![Six Flags Magic Mountain 2022-09-12 11-01-59](https://user-images.githubusercontent.com/61885939/189724649-1a89097a-6611-47bb-b9bb-eedc89294e6d.png)
[92-93, 57], [89, 40-42], [90, 42]

![Six Flags Magic Mountain 2022-09-12 11-02-03](https://user-images.githubusercontent.com/61885939/189724674-4a5d796c-1ab8-402e-a10c-6b741df8ded1.png)
[168-169, 20]

**Comment by SpartanFrederic104** [comment] 2022-09-12 18:09
Six Flags Holland:
![Six Flags Holland 2022-09-12 11-05-58](https://user-images.githubusercontent.com/61885939/189725552-e49962aa-2799-4abd-881d-5f52371f012f.png)
[112, 33-34]

![Six Flags Holland 2022-09-12 11-08-57](https://user-images.githubusercontent.com/61885939/189725579-6da93352-83c3-4dfd-9d84-f3ee1394ddf2.png)
[113-117, 117], [114-117, 118]

**Comment by Basssiiie** [comment] 2022-09-12 18:09
Six Flags Holland, 9 tiles in the river in the far corner of the map near Goliath, these should be for sale:

![image](https://user-images.githubusercontent.com/20048660/189725408-523e61a7-8c1f-4981-abc3-788fa71cd5c4.png)

Two tiles near Robin Hood should be for sale as well:

![image](https://user-images.githubusercontent.com/20048660/189725607-ae8194db-ba37-4dbc-beda-d18b2cbbf3e6.png)

**Comment by Basssiiie** [comment] 2022-09-12 18:15
Fort Anarchronism

One tile next to the river exiting the lake should be for sale:

![image](https://user-images.githubusercontent.com/20048660/189726508-661883ba-1149-47b2-8d07-ca87d265f070.png)

One tile on the opposite side of the lake, from the river exit, should also be for sale:

![image](https://user-images.githubusercontent.com/20048660/189726634-94d90bcc-1c5a-4091-b659-705791d6dce4.png)

**Comment by SpartanFrederic104** [comment] 2022-09-12 18:18
![Mirage Madness 2022-09-12 11-16-47](https://user-images.githubusercontent.com/61885939/189727042-fbd6b3ed-5ac4-4159-89aa-00696f5570e7.png)
Africa - Oasis (Mirage Madness) has a tile of construction rights at [61, 35] that should be land not owned by park.

**Comment by Basssiiie** [comment] 2022-09-12 18:20
@SpartanFrederic104 personally I think too much construction rights/land ownership is not that important to fix. It's more frustrating if the option to own/buy anything is missing. I skipped several of these kind of errors already in the other expansion parks.

**Comment by Basssiiie** [comment] 2022-09-12 18:52
Pleasure Island (Loopy Landscapes) has one tile in the water left of the entrance that should be construction rights, at X 37, Y 66:

![image](https://user-images.githubusercontent.com/20048660/189732890-48aea7e4-36e1-434c-901f-2c557ccced59.png)

**Comment by 733737** [comment] 2022-09-13 03:24
if there is a guide on how to patch these scenarios I guarantee I willl patch them all and submit a PR within a week. Right now I don't know how, but I would gladly put the time and effort if I did

**Comment by Basssiiie** [comment] 2022-09-13 16:29
@733737 You can look at how this PR was done for inspiration, maybe it helps: #15156 For RCT1 scenarios you have to change do similar changes to [this file](https://github.com/OpenRCT2/OpenRCT2/blob/0a571cce299a79c0a901d921d21adf76100320d3/src/openrct2/rct1/S4Importer.cpp#L2482-L2505).

**Comment by 733737** [comment] 2022-09-14 05:11
If Gymnasiast has been assigned to this then I am giving up on fixing it, I'll wait for Gymnasiast to do it, even if it takes a long time

**Comment by 733737** [comment] 2022-09-17 08:14
I decided to implement at least the six flags changes

**Comment by 733737** [comment] 2022-09-18 03:48
I have a serious issue with implementing more fixes: #1 I need to know exact coordinates in x,y values for every park #2 I need to know if the issue is it should be owned, for sale, or contruction rights #3 I don't know how to implement construction rights as I only see OWNERSHIP_AVAILABLE and OWNERSHIP_OWNED in the code

**Comment by 733737** [comment] 2022-09-18 04:21
> ![Mirage Madness 2022-09-12 11-16-47](https://user-images.githubusercontent.com/61885939/189727042-fbd6b3ed-5ac4-4159-89aa-00696f5570e7.png) Africa - Oasis (Mirage Madness) has a tile of construction rights at [61, 35] that should be land not owned by park.

Gymnasiast would have to fix this because I can't read his code to see if OWNERSHIP_UNOWNED is a thing

**Comment by Gymnasiast** [comment] 2023-01-09 23:30
Yes, `OWNERSHIP_UNOWNED` is a thing.

**Comment by Basssiiie** [comment] 2023-01-10 07:31
As mentioned before, I don't think there's any harm in leaving that in, and it's kinda funny. I'd say only fix the ones that can annoy people.

**Comment by HtotheTML** [comment] 2023-03-14 20:57
![image](https://user-images.githubusercontent.com/108596959/225134451-6614bf76-d5b0-4a20-9518-e208fd932c5e.png)
Dark Age - Castle has park boundaries that make the path unusable here.

**Comment by HtotheTML** [comment] 2023-03-15 05:08
Six Flags Great Adventure contains a few stray owned tiles.
![image](https://user-images.githubusercontent.com/108596959/225212506-8817724e-bd59-4f22-9d34-34eae7b1f188.png)

**Comment by HtotheTML** [comment] 2023-03-15 05:31
Africa - Oasis
![image](https://user-images.githubusercontent.com/108596959/225216062-8a34b375-9a35-47b7-a50e-3ef81c86b226.png)

**Comment by HtotheTML** [comment] 2023-03-15 05:35
pre-owned tile in Ecological Salvage
![image](https://user-images.githubusercontent.com/108596959/225216605-0c5c8050-2f48-40a8-acf6-db9ed34f41fc.png)

**Comment by Basssiiie** [comment] 2023-03-15 08:31
@HtotheTML Some of these are not obstructing right? Just mistakes. I don't think they need fixing as they're just a funny quirk, not causing frustration.

**Comment by HtotheTML** [comment] 2023-03-16 19:51
![image](https://user-images.githubusercontent.com/108596959/225736791-bfa1e4bd-7b31-4353-a7ef-66c0ce4282c8.png)
Still an issue of land ownership, but this segment of prebuilt underground path in Cradle of Civilization is outside park boundaries even though it's meant to be inside the park.

**Comment by SpartanFrederic104** [comment] 2023-03-16 20:49
Is it actually purchasable land though?

**Comment by HtotheTML** [comment] 2023-03-16 21:00
that land is purchasable, yes, however that segment should be changed to already owned rather than for sale, or the path should be moved or changed.

**Comment by HtotheTML** [comment] 2023-03-16 22:03
I think that would be reductive, since those tiles are normally purchasable land, along with most of the rest of the map.

**Comment by HtotheTML** [comment] 2023-03-18 05:33
I'm a bit unsure how to handle fixes other than making purchasable land for RCT1 scenarios, since the code formatting is different.

**Comment by Gymnasiast** [comment] 2023-03-18 14:08
Just call `FixLandOwnershipTilesWithOwnership(tiles, OWNERSHIP_AVAILABLE);` and replace OWNERSHIP_AVAILABLE with the correct ownership status.

**Comment by jglenn1562** [comment] 2023-09-02 22:01
![Dark Age Scenario Boundary Blocking Path](https://github.com/OpenRCT2/OpenRCT2/assets/102439951/123e61c6-a1dc-413a-aedc-94db530715c6)

Dark Age - Another path that is blocked underground by park boundaries.

**Closed** 2023-11-17 11:23 UTC
Labels: bug
