### ISSUE TITLE
Some words intersect in ttf languages with opengl rendering

### ISSUE THREAD

**Issue by toimine** [OpenRCT2/OpenRCT2#16387] opened 2022-01-06 13:58 UTC
### Operating System

Windows 7 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (f9ca2ba on develop) provided by GitHub

### Describe the issue

Any text that fills in blanks after colons gets rendered at the start of strings

### Steps to reproduce

1. set the rendering engine to opengl
2. set the game language to arabic/japanese/korean
3. the funny (first screenshot)
4. it gets extra funny if you switch back to software rendering without changing the language (second screenshot)

### Attachments

![изображение](https://user-images.githubusercontent.com/62563494/148393172-a392d523-fdc7-4cfd-a9b9-af0e8778466f.png)
![изображение](https://user-images.githubusercontent.com/62563494/148393678-837884f9-7a2a-42ee-9e5a-99675b65ae52.png)

**Comment by James103** [comment] 2022-01-06 14:04
Windows 7 is no longer supported by Microsoft. Are you able to reproduce this on a build of Windows 10?

**Comment by toimine** [comment] 2022-01-06 14:24
i don't have windows 10 with me but i can try doing it in an arch vm (no idea it it'll even work tho)

**Comment by toimine** [comment] 2022-01-06 15:00
Yup, it still does it
![изображение](https://user-images.githubusercontent.com/62563494/148402871-f1f4a976-a367-490c-b57e-7c2fed677142.png)

**Comment by Gymnasiast** [comment] 2022-01-06 18:47
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/15293.

**Closed by Gymnasiast** 2022-01-06 18:47 UTC
Labels: bug
