### ISSUE TITLE
Reversing the Reversed Trains Doubles the Stat Bonus

### ISSUE THREAD

**Issue by Electrollama** [OpenRCT2/OpenRCT2#21209] opened 2024-01-17 03:09 UTC
Graphically, checking "Reversed Trains" for the "Roller Coaster Trains (Reversed)" results in normal-looking trains. However, these two settings each contribute bonuses for Excitement, Intensity, and Nausea, so these bonuses are doubled.

Steps to re-create:
1. Open Diamond Heights, open the Inventions List and Move All to Top
2. Open Agoraphobia's stats: 7.41 Excitement, 6.74 Intensity, 3.14 Nausea
3. Switch the vehicle type to "Roller Coaster Trains (Reversed)" and test the ride: 7.51 Excitement, 7.51 Intensity, 3.86 Nausea
4. Check the box for Reversed Trains. Notice that the trains are graphically the right way around. Test the ride: 7.60 Excitement, 8.43 Intensity, 4.75 Nausea.
Expected behavior: stats 7.41 Excitement, 6.74 Intensity, 3.14 Nausea; or Roller Coaster Trains (Reversed) train type removed since it's already available without research.

**Comment by jensj12** [comment] 2024-01-17 19:58
Duplicate of #20146.

**Comment by Gymnasiast** [comment] 2024-01-17 22:50
Closing as duplicate.

**Closed by Gymnasiast** 2024-01-17 22:50 UTC
Labels: bug
