### ISSUE TITLE
Alternative Vehicles for Roller Coasters cannot be selected

### ISSUE THREAD

**Issue by Generalcamo** [OpenRCT2/OpenRCT2#3960] opened 2016-06-30 22:16 UTC
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** 958

Alternative Vehicles cannot be selected for Roller Coasters. For some reason, RCT1-style building does allow for previously-split vehicles to be selected, but not alternative vehicles for the ride.

- Reproducible in RCT2 (vanilla)? No
- Multiplayer? Singleplayer and Multiplayer

**Steps to reproduce:**
1. Load "Crazy Castle"
2. Build a Mini Coaster (custom built)
3. Notice you cannot switch to Toboggan Cars
4. Build the Ride "Cairngorn Bobsleds" under the Mini-Coaster
5. Notice that while you may be able to select Automobile Cars, the Toboggan Cars that are currently on the ride cannot be selected (If on RCT1 Mode)
*OR*
5. Notice that you cannot change the vehicle at all (if in RCT2 mode)

**Comment by Gymnasiast** [comment] 2016-07-01 12:30
Duplicate of #3806.

**Closed** 2016-07-01 12:31 UTC
Labels: duplicate
