### ISSUE TITLE
No option to change the train type even when other train types are unlocked

### ISSUE THREAD

**Issue by XeroOl** [OpenRCT2/OpenRCT2#4190] opened 2016-07-30 00:28 UTC
**OS:** Windows 10
**Version:** v0.0.5 
**Commit/Build:** 3116ec3

I can't change the type of train on my wooden ride. It is currently stuck on "Articulated Roller Coaster Trains." According to the debug menu, other types of trains should be available for wooden roller coasters. (eg. "Wooden Roller Coaster Trains" in screenshot) Note that this bug happens for more cases than just wooden coasters in fungus woods. 
I have not tested what happens when pre-made rides with alternate train types are built.

- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Multiplayer? Not tested

**Steps to reproduce:**
1. Load up "Fungus Woods" scenario.
2. Build a custom wooden ride.
3. Look to change the train type.
4. Notice that there is no way to change the train even though other train types are enabled in the Object Selection debug menu

**Screenshots / Video:**
![scr3](https://cloud.githubusercontent.com/assets/6820998/17266687/45bb50e8-55c9-11e6-8408-c5cf56ad0b81.png)

**Comment by PopsiclePenguin** [comment] 2016-07-30 07:07
I can confirm this happens in multiplayer as well. Custom scenario I made a few days ago, with only vanilla rides. Can not cheat in the other train types, cant get them no matter what, but using debug tools I can confirm they are added to the map and researched. Can confirm it happens with wooden coasters, hyper twister trains, and monorails and miniature railroads. Just one type becomes available.

So yeah. Not just fungus woods. Also in multiplayer. Very frustrating.

**Comment by Gymnasiast** [comment] 2016-07-30 09:44
Duplicate of #3806

**Closed** 2016-07-30 09:44 UTC
Labels: duplicate
