### ISSUE TITLE
Doors have graphical glitches when vehicles go through

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#6725] opened 2017-11-23 00:44 UTC
**OS:** Windows 10 / ArchLinux
**Version:** 0.1.2
**Commit/Build:** aff7609b86bc333a044711856b2510d7a3f07b97

Scenery wall doors have graphical glitches when vehicles go through them. Depending on the direction they are placed relative to the vehicle, the doors will open outwards then close inwards (as if it was placed the other way). The vehicle also gets drawn over the door with visible z-fighting.

This issue pre-dates v0.1.0.

**Comment by cherct** [comment] 2020-03-30 13:37
This is still a bug:
![doorbug](https://user-images.githubusercontent.com/62889822/77918088-b2979f80-729b-11ea-824a-a8f3fd3bd98f.png)

release v0.2.4 d645338

**Comment by Gymnasiast** [comment] 2020-03-30 14:30
@cherct You're testing with a release, and a five month old one at that. If you want to test if a bug still exists, always test it using the newest `develop`.

The bug that IntelOrca describes is no longer in the game. It was fixed in 2018: https://github.com/OpenRCT2/OpenRCT2/commit/c8063a3c38cd350b3e4642d30a15ea8eac499d5a

The problem there was that it would open one way, then suddenly turn into a mirror image and close the other way. Your screenshot only shows Z fighting, which is an issue onto itself, but not this one.

**Comment by duncanspumpkin** [comment] 2021-02-13 18:46
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/drawing/X8DrawingEngine.cpp#L389-L399 Z-fighting on software renderer looks to be caused by this bit of code determining columns. In the original only the one column was ever determined which kind of makes sense as the drawing engine does everything in columns.

**Comment by AaronVanGeffen** [comment] 2021-02-13 18:48
Duncan spent 2.5 hours of debugging and rewriting to find the source of this Z-fighting for OpenLoco. Mad props to him.

**Comment by duncanspumpkin** [comment] 2021-02-13 19:06
I'm not 100% sure it will solve this particular z fighting issue as from tests the benefits haven't been as apparant as in openloco

**Comment by Gymnasiast** [comment] 2021-02-21 13:22
Not as apparent is one thing, but does it make _a_ difference? Many of our Z-fighting issues were also in vanilla, so it makes sense if it doesn't fix all of them.

**Comment by duncanspumpkin** [comment] 2021-02-21 18:03
It will possibly fix z fighting issues that are not in vanilla or in OpenGL renderer. I need to find a good park that has these conditions.

**Comment by Gymnasiast** [comment] 2021-03-03 08:23
For the record, the fix for OpenLoco is here: https://github.com/OpenLoco/OpenLoco/commit/0ee80c5d2ab7b29ef0e7149efe0df3a916ace118

**Comment by oli414** [comment] 2022-04-24 16:38
Had a look into this, the first commit already seems to have had this issue. What I find suspicious is the following:

https://github.com/OpenRCT2/OpenRCT2/blame/ab255ae90db1e0bd972accea3bfcd8d3d2a9871c/src/paint/map_element/fence.c#L120-L144

When the doorway is not double-sided (WALL_SCENERY_FLAG4), which is the case for all vanilla doors. The left and right side of the door is drawn using the same bounding boxes. To my knowledge for this to be drawn correctly the bounding boxes would need to be on the left and right sides accordingly.

The branch for the double-sided walls does have unique bounding boxes for the left and right sides, and using that branch for all doorways shows that having a different bounding box does make it work (for 2 viewing angles).

It's worth having a look at the assembly for [line 135](https://github.com/OpenRCT2/OpenRCT2/blame/ab255ae90db1e0bd972accea3bfcd8d3d2a9871c/src/paint/map_element/fence.c#L135) and line [140](https://github.com/OpenRCT2/OpenRCT2/blame/ab255ae90db1e0bd972accea3bfcd8d3d2a9871c/src/paint/map_element/fence.c#L140) to check if the parameters were decompiled properly.

@duncanspumpkin

**Closed** 2024-04-13 19:32 UTC
Labels: bug
