### ISSUE TITLE
Segfault when loading savegame, segfault when running the game...

### ISSUE THREAD

**Issue by andoruB** [OpenRCT2/OpenRCT2#6619] opened 2017-11-05 00:56 UTC
**OS:** Debian Sid 64-bit
**Version:** 0.1.2-develop build
**Commit/Build:** 4a66e98 / 4a66e98bb 

At first, I could run the game, and everything worked fine, except when I tried to load a savegame (any savegame actually, as I tried loading multiple saves), it segfaulted. 
This is what I got in stdout:

```
./openrct2 
object index out of date
Building object index (2122 items)
Finished building object index in 8.46 seconds.
track design index out of date
Building track design index (204 items)
Finished building track design index in 0.16 seconds.
Unable to load index: '~/.config/OpenRCT2/scenarios.idx'.
Unable to open '~/.config/OpenRCT2/scenarios.idx'
Building scenario index (57 items)
Finished building scenario index in 0.27 seconds.
ERROR[~/sources/OpenRCT2/src/openrct2-ui/windows/Changelog.cpp:207 (window_changelog_read_file)]: Unable to read changelog.txt
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
Segmentation fault
```

As I didn't get much info on why I got that segfault, I went ahead and started the game with gdb, but now it segfaults right from the start (so I don't get to see the main screen, only hear a few miliseconds of the title theme). Starting the game normally, without gdb now also crashes before the main screen.

Here's the backtrace: 

```
(gdb) run
Starting program: ~/bin/OpenRCT2/openrct2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea024700 (LWP 21867)]
[New Thread 0x7fffe28de700 (LWP 21868)]

Thread 1 "openrct2" received signal SIGSEGV, Segmentation fault.
0x00007ffff7af6bb8 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
(gdb) backtrace
#0  0x00007ffff7af6bb8 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#1  0x00007ffff7af6db5 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#2  0x00007ffff7af72e7 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#3  0x00005555557238c9 in OpenRCT2::Audio::MemoryAudioSource::Convert(OpenRCT2::Audio::AudioFormat const*) ()
#4  0x00005555557230cd in OpenRCT2::Audio::AudioSource::CreateMemoryFromCSS1(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, OpenRCT2::Audio::AudioFormat const*) ()
#5  0x0000555555720f05 in OpenRCT2::Audio::AudioMixerImpl::LoadAllSounds() ()
#6  0x0000555555720941 in OpenRCT2::Audio::AudioMixerImpl::Init(char const*) ()
#7  0x000055555571f3fb in OpenRCT2::Audio::AudioContext::SetOutputDevice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#8  0x000055555581c44f in Mixer_Init ()
#9  0x000055555581b711 in audio_init ()
#10 0x000055555580cc50 in OpenRCT2::Context::Initialise() ()
#11 0x000055555580c57b in OpenRCT2::Context::RunOpenRCT2(int, char const**) ()
#12 0x0000555555715250 in main ()
```

I'm not exactly sure why I got the errors about the index files, as they are present in that mentioned path, and they all have the correct permissions.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Comment by PFCKrutonium** [comment] 2017-11-05 04:09
Hm, without looking too close, I have two suggestions: Make sure your audio files are all valid, and try rebuilding with the latest version of SDL2 (2.0.7 iirc)

**Comment by janisozaur** [comment] 2017-11-05 06:28
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/6364, update your sdl2 2.0.7.

**Closed by janisozaur** 2017-11-05 06:28 UTC

**Comment by andoruB** [comment] 2017-11-05 10:44
Whoops, sorry about that. Did not find the thread when I searched last time...
Unfortunately I can't update SDL2 on this distro, as it is the latest version available (me being on unstable repos). Any suggestions?
