### ISSUE TITLE
Pasting saved design with path lays path incorrectly

### ISSUE THREAD

**Issue by jez9999** [OpenRCT2/OpenRCT2#18356] opened 2022-10-16 12:58 UTC
### Operating System

Windows 7 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.2 (8ceea45) provided by GitHub

### Describe the issue

In my attached "Spiral Slide colorful trees" saved ride, there is a queue path and one tile of exit path.  This is supposed to connect correctly like in the following screenshot (trees hidden):

![image1](https://user-images.githubusercontent.com/793830/196036660-2a6e5101-3441-49ae-a58b-fb5cce807afa.png)

The preview of the paste does actually show this.  But when I paste it, I get the wrong path connection (trees hidden):

![image2](https://user-images.githubusercontent.com/793830/196036718-603a454e-6705-4192-80ca-2445115152da.png)

### Steps to reproduce

Unzip "Spiral Slide colorful trees" into tracks directory.  Play a game and try to paste "Spiral Slide colorful trees" design into your park.

### Attachments

[Spiral Slide colorful trees.zip](https://github.com/OpenRCT2/OpenRCT2/files/9794555/Spiral.Slide.colorful.trees.zip)

**Comment by jensj12** [comment] 2022-10-17 09:48
Duplicate of #6228.

**Closed** 2022-10-17 10:00 UTC
Labels: bug
