### ISSUE TITLE
Remove guests cheat causes game crash

### ISSUE THREAD

**Issue by LostInRiverview** [OpenRCT2/OpenRCT2#11989] opened 2020-06-19 00:37 UTC
**OS:** Windows 10 v.1909
**Version:** OpenRCT2 v.0.2.6
**Commit/Build:** 6c3c857

When loading parks that already contain guests, the 'Remove Guests' cheat can sometimes cause the game to crash if the guests information window is open.

Not reproducible in vanilla (as there is no 'remove guests' cheat there), and not specific to multiplayer.

Have been able to reproduce in some RCT1 parks (Evergreen Gardens, Diamond Heights, Katie's World) but not in some others (Dynamite Dunes, Bumbly Beach). Haven't been able to reproduce in any RCT2 parks so far. It seems to affect specific parks rather than all parks, and seems irrespective of whether the park has rides in it or not.

**Dump file**
[fff908e9-7e6c-4730-aeb8-43a5d141bb88.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/4801821/fff908e9-7e6c-4730-aeb8-43a5d141bb88.sv6.gz)

**Comment by tupaschoal** [comment] 2020-06-19 00:45
Does this happen consistently? If so, can you check with the `develop` version if it still happens, please?

**Comment by LostInRiverview** [comment] 2020-06-19 01:19
> Does this happen consistently?

Yes and no. It seems to happen in the same parks consistently, regardless of whether it's a brand-new scenario or whether the park has been running with guests for some time. But it's not consistent in that it only seems to affect certain parks and not others.

> If so, can you check with the develop version if it still happens, please?

I am able to recreate the crash in version v.0.2.6-932-gd66c61ca0 (d66c61c)

**Dump file from latest dev version**
[a43756d5-35df-4252-9cea-50299f2b4ffc.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/4801945/a43756d5-35df-4252-9cea-50299f2b4ffc.sv6.gz)

**Comment by duncanspumpkin** [comment] 2020-06-20 07:31
I tried a bit to reproduce this. All I could create was a long hang (10 seconds on debug builds) if you have the PeepList window Grouped tab open. The hang is caused by some super inefficient sorting of the list that will be fixed eventually.

**Comment by LostInRiverview** [comment] 2020-06-20 08:44
I hadn't even thought to check which tab was open when the crash happened. I've noticed the hang as well when the grouped tab is selected. The crashes seem to happen when the individual guest list is selected instead of the grouped guest list.

![crash on cheat](https://user-images.githubusercontent.com/67129586/85197620-dd483180-b2a7-11ea-88c1-3c04d6a7804a.jpg)

Here, I've opened a new Evergreen Gardens scenario and used the cheat to clear the sole guest from the park. Having the guest's window open doesn't seem to trigger the crash, but having the guest list open does. Notice also that the guest window is still there even though the guest is gone, and the guest is shown as unselectable. I've experimented in other parks and having the guest selected doesn't seem to contribute to this; it's an odd behaviour that doesn't seem to have any consequences.

**Comment by duncanspumpkin** [comment] 2020-06-20 08:51
Hmm that is odd. When a guest is removed it should auto close its guest window. I confirmed that was happening for me. When a guest is removed it also forces a refresh of the guest list window (this is why the grouped tab hangs 1000 removes means 1000 refreshs which means 1000 groupings and orderings.). Could you try to reproduce this on develop as I have been unsuccessful at reproducing it.

**Comment by tupaschoal** [comment] 2020-06-20 12:31
With the guest list I can reproduce it too, thanks for the details! This is part of the stack trace Duncan
```
 	openrct2.exe!common_strnlen_simd<0,0,unsigned char>(const unsigned char * const string, const unsigned __int64 maximum_count) Line 152	C++
 	openrct2.exe!common_strnlen<0,unsigned char>(const unsigned char * const string, const unsigned __int64 maximum_count) Line 189	C++
 	openrct2.exe!strnlen(const char * string, unsigned __int64 maximum_count) Line 202	C++
 	openrct2.exe!format_append_string(char * * dest, unsigned __int64 * size, const char * string) Line 375	C++
 	openrct2.exe!format_string_code(unsigned int format_code, char * * dest, unsigned __int64 * size, char * * args) Line 1092	C++
 	openrct2.exe!format_string_part_from_raw(char * * dest, unsigned __int64 * size, const char * src, char * * args) Line 1211	C++
 	openrct2.exe!format_string_part(char * * dest, unsigned __int64 * size, unsigned short format, char * * args) Line 1239	C++
 	openrct2.exe!format_string_code(unsigned int format_code, char * * dest, unsigned __int64 * size, char * * args) Line 1084	C++
 	openrct2.exe!format_string_part_from_raw(char * * dest, unsigned __int64 * size, const char * src, char * * args) Line 1211	C++
 	openrct2.exe!format_string_part(char * * dest, unsigned __int64 * size, unsigned short format, char * * args) Line 1239	C++
 	openrct2.exe!format_string(char * dest, unsigned __int64 size, unsigned short format, const void * args) Line 1322	C++
 	openrct2.exe!DrawTextEllipsisedCompat(rct_drawpixelinfo * dpi, int x, int y, int width, unsigned short format, void * args, unsigned char colour, TextAlignment alignment, bool underline) Line 139	C++
 	openrct2.exe!gfx_draw_string_left_clipped(rct_drawpixelinfo * dpi, unsigned short format, void * args, unsigned char colour, const ScreenCoordsXY & coords, int width) Line 194	C++
 	openrct2.exe!window_guest_list_scrollpaint(rct_window * w, rct_drawpixelinfo * dpi, int scrollIndex) Line 777	C++
 	openrct2.exe!window_event_scroll_paint_call(rct_window * w, rct_drawpixelinfo * dpi, int scrollIndex) Line 1568	C++
 	openrct2.exe!widget_scroll_draw(rct_drawpixelinfo * dpi, rct_window * w, short widgetIndex) Line 725	C++
 	openrct2.exe!widget_draw(rct_drawpixelinfo * dpi, rct_window * w, short widgetIndex) Line 97	C++
 	openrct2.exe!window_draw_widgets(rct_window * w, rct_drawpixelinfo * dpi) Line 638	C++
 	openrct2.exe!window_guest_list_paint(rct_window * w, rct_drawpixelinfo * dpi) Line 685	C++
 	openrct2.exe!window_event_paint_call(rct_window * w, rct_drawpixelinfo * dpi) Line 1562	C++
 	openrct2.exe!window_draw_single(rct_drawpixelinfo * dpi, rct_window * w, int left, int top, int right, int bottom) Line 1246	C++
>	openrct2.exe!window_draw(rct_drawpixelinfo * dpi, rct_window * w, int left, int top, int right, int bottom) Line 1129	C++
 	openrct2.exe!window_draw_all::__l2::<lambda>(rct_window * w) Line 2042	C++
```

**Comment by Broxzier** [comment] 2021-09-16 21:25
Closing this issue, as I can no longer reproduce this with the steps above. The guest window gets cleared, and the peep window gets closed.

**Closed by Broxzier** 2021-09-16 21:25 UTC
Labels: crash
