### ISSUE TITLE
Running scenario in server causes no money setting to be turned on

### ISSUE THREAD

**Issue by tarrzan33** [OpenRCT2/OpenRCT2#16766] opened 2022-03-09 02:54 UTC
### Operating System

Linux

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (d219a99 on develop) provided by GitHub

### Describe the issue

When loading my custom scenario in a single player mode it loads with money turned on. (Pay for park entrance and Rides)

When I load this scenario in a server mode it disables the money. 

[My new scenario.zip](https://github.com/OpenRCT2/OpenRCT2/files/8211244/My.new.scenario.zip)

During the setup of the scenario I did enable the Have Fun mode for the objective. 

### Steps to reproduce

1. Add the scenario to your game files
2. Load in single player mode - See there is money
3. Load in a new server mode - See there is no money

### Attachments

[My new scenario.zip](https://github.com/OpenRCT2/OpenRCT2/files/8211271/My.new.scenario.zip)

**Comment by fidwell** [comment] 2022-04-17 14:38
Probably a duplicate of #16478 which is now fixed.

**Closed** 2022-04-17 15:51 UTC
Labels: bug
