### ISSUE TITLE
Guest thoughts appear in construction alerts

### ISSUE THREAD

**Issue by user-0124** [OpenRCT2/OpenRCT2#8014] opened 2018-09-22 18:05 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.1]
**Commit/Build:** [e.g. dOe318a]

When you attempt to place a coaster on an occupied area, messages will appear saying "Can't construct here... [Guest thought here] is in the way." When clicking on ride exits, the message becomes "Can't construct here... (undefined string)"

- [ no ] Reproducible in RCT2 (vanilla)?
- [ no ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a pre-made rollercoaster (I chose a LIM coaster, Drive-By)
2. Attempt to build on used land.

**Dump file**

**Screenshots / Video:**

https://cdn.discordapp.com/attachments/450316748734988289/493114027829100544/unknown.png
https://cdn.discordapp.com/attachments/450316748734988289/493113219821600774/unknown.png
https://cdn.discordapp.com/attachments/450316748734988289/493113405339861013/unknown.png
https://cdn.discordapp.com/attachments/450316748734988289/493113788187410442/unknown.png

**Save game:**

[Pleasure Avenue 2.txt](https://github.com/OpenRCT2/OpenRCT2/files/2408036/Pleasure.Avenue.2.txt)

**Comment by user-0124** [comment] 2018-09-22 18:06
(Save game uses custom content, which was pre-installed with my OpenRCT2 oddly.

**Comment by Broxzier** [comment] 2018-09-22 18:35
Are you still on 426e106 or did you forget to fill in that field? If so, try updating to last builds.

**Comment by user-0124** [comment] 2018-09-22 18:36
I forgot, it's changed

**Comment by AaronVanGeffen** [comment] 2018-09-22 18:40
Probably related to #7439. If you can find a reliable way to reproduce the issue, that'd be a big help.

**Comment by user-0124** [comment] 2018-09-22 18:42
I did, just try placing a pre-built coaster where you can't.

**Comment by AaronVanGeffen** [comment] 2018-09-22 18:47
![screen shot 2018-09-22 at 20 47 09](https://user-images.githubusercontent.com/604665/45920701-b24d6580-bea8-11e8-84ed-78332f1fd5fa.png)

It appears properly for me in an empty park. This is part of the problem: it appears to be corruption of some sort.

**Comment by user-0124** [comment] 2018-09-22 18:49
Try placing it on top of your occupied property, where guests are. Also try not to get the coaster outside of park boundaries or else you'll get "Land not owned by park!"

**Comment by tombomp** [comment] 2018-09-23 21:08
[Trinity Islands.zip](https://github.com/OpenRCT2/OpenRCT2/files/2409151/Trinity.Islands.zip)
![image](https://user-images.githubusercontent.com/43040194/45932983-104b7d00-bf7d-11e8-8991-668582adcb45.png)

Here's a reproducible example of the (undefined string) bug - build the steel wild mouse design Fungicide in this save game centred on the spot with the bench in the screenshot.

**Comment by tombomp** [comment] 2018-09-24 15:09
Also after some testing it appears you need to have the "guests" window open with the thoughts of all guests open and then the guest thoughts in the construction error thing starts happening.

**Comment by tombomp** [comment] 2018-09-25 22:36
I don't know if this is actually helpful but I found that in GuestList.cpp the get_arguments_from_peep function modifies gCommonFormatArgs - if you save that var to a temporary and then put it back at the end of the if the X_IN_THE_WAY errors start working again. However, the thought being shown in the "Guests thinking x" in the summary window still changes whenever an X_IN_THE_WAY error happens (including when you just hover the ghost outline over something).

 I spent a while trying to work out how the format strings work as well as how the guest list decides what thought to display but I gave up after a while because I was getting nowhere, heh. Sorry if this is unhelpful!

**Comment by AaronVanGeffen** [comment] 2018-10-22 06:04
With #8130 merged, does this still happen?

**Comment by AaronVanGeffen** [comment] 2018-10-22 06:04
With #8130 merged, does this still happen?

**Comment by AaronVanGeffen** [comment] 2018-10-22 06:06
Does this still happen now that #8130 has been merged?

**Comment by tombomp** [comment] 2018-10-22 15:16
Just checked, guest thoughts still show up.

**Comment by ZehMatt** [comment] 2024-02-14 14:12
I don't think this happens anymore, leave a comment if it is.

**Closed by ZehMatt** 2024-02-14 14:12 UTC
Labels: bug
