### ISSUE TITLE
BACKTRACE 86a246 vehicle_get_head -> vehicle_update_crossings -> vehicle_update_track_motion_forwards

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8265] opened 2018-11-15 21:47 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/86a2462eeab8678a92c49c0a4467d7fa1f3a171427c15fd481f518bcef657a7d?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Thu Nov 15 2018 21:47:50)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> de12a8d: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>vehicle_get_head -> vehicle_update_crossings -> vehicle_update_track_motion_forwards -> vehicle_update_track_motion -> vehicle_update_moving_to_end_of_station -> vehicle_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> SDL_PeepEvents_REAL -> SDL_WaitEventTimeout_REAL -> SDL_PollEvent_REAL -> UiContext::ProcessMessages -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:40
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8477

**Closed by janisozaur** 2019-02-02 22:40 UTC
Labels: backtrace.io, crash
