### ISSUE TITLE
Server List issue

### ISSUE THREAD

**Issue by alecward92** [OpenRCT2/OpenRCT2#6277] opened 2017-09-14 03:02 UTC
**OS:** WIndows 7
**Version:** 0.1.2-2
**Commit/Build:** 735b96a

After updating to 0.1.2 a few hours ago, I noticed neither of my servers are "advertising" on the server list. I host both FREEDOM servers. One thing I did notice though is that since I have them Favorited, clicking the name will still bring me to the server with no issues. I'm just seeing a dark red with no player list so I'm assuming that's the sign of it being "down", when in this case, it is not.

**Comment by PFCKrutonium** [comment] 2017-09-19 05:45
BlindiRL is also having this issue - His server was not able to be advertised during his last 2 Multiplayer Mondays and had to rely on direct connecting.

**Comment by GTW1226** [comment] 2017-09-21 18:50
Looks like I am one of the only popular servers that is still having this problem. I know other people that can start them with now problem and they show. My server is GTW's Nostalgia Server. Its a part time server.

**Comment by PFCKrutonium** [comment] 2017-09-25 04:49
I have another server with this issue who contacted me privately on Discord, who also can not get listed on the server. I verified that his ports are forwarded and he is connectable. This bring the total affected _that we know of_ to 3.

**Comment by GTW1226** [comment] 2017-09-28 18:22
Update: With this new Net Build Update -3. GTW's Nostalgia Server still doesn't show. I can confirm I have the ports all done right because people can connect with the IP and port Number.

**Comment by alecward92** [comment] 2017-09-28 19:14
What I have noticed @PFCKrutonium , is that after a day or so of hosting, they do eventually pop up. I admin for MoT servers too and they never have issues. They only use the Launcher so I am running a test to see if it is the downloadable updates, or in fact, something acting up.

**Comment by alecward92** [comment] 2017-09-28 19:23
After waiting 10 minutes, I'm still getting the same issue with the Launcher. Can't confirm issue :(

**Comment by alecward92** [comment] 2017-10-01 04:33
Tried uninstalling base game and OpenRCT. Deleted all files and reinstalled with a fresh copy of RCT and an updated version of OpenRCT and I'm still coming across the same issue. I'm seeing if RCTC will help but I'm having all sorts of issues getting the game to even run with previous maps.

**Comment by GTW1226** [comment] 2017-10-02 05:45
As a temporary fix, GTW's Nostalgia Server is on a virtual machine, with a fresh install, SO this issue is not fixed as of yet,since it shows with the VM running the server. I would recommend that to anyone having this issue right now.

**Comment by janisozaur** [comment] 2017-10-06 10:54
Things that are known so far:

* The issue seems to be a regression, as advertising is said to be working on latest release
* The issue is present on current `develop`, at the time of writing 4224193d6850b959f9d36b2172e5f5183c9d91ec
* Bisection led to regression introduced somewhere in 4da15a6785f9097b5534ca7b0ad59c272df6f7ad...519d5bcff88b4bdedb225f9b4fda1e8b8f9d0339
  - Bisection was done by @thiebert on Windows 7, using 64 bit builds from appveyor
* The error reported is most likely coming from https://github.com/OpenRCT2/master-server/blob/3ec276d394e193f4f8022c464d7a7e8c3edc07d4/views/routes/index.js#L44
* There is a highly suspicious commit that changes prebuilt libraries: https://github.com/OpenRCT2/OpenRCT2/commit/f4263d2cece41ae273fedc0c8ad1b4acc0c3c60a (as we moved from vs2015 to vs2017)
  - The issue, however, is said to be also present on other systems, e.g. macOS.

**Comment by janisozaur** [comment] 2017-10-07 21:33
Can you please change your `config.ini` to have this: `master_server_url = "https://glacial-scrubland-24489.herokuapp.com/"` and try hosting+advertising then?

**Comment by alecward92** [comment] 2017-10-07 23:33
@janisozaur  After modifying the config settings to what you asked, now no servers are showing up at all. Still tried to host and it still won't show up. @GTW1226  Can you confirm this?

**Comment by PFCKrutonium** [comment] 2017-10-07 23:41
@alecward92 >

(FREEDOM SERVER) MAIN 0.1.1 | Register @ freedom-server.org | 0.1.2-7 | No | 1/16 | No

**Comment by GTW1226** [comment] 2017-10-07 23:51
@PFCKrutonium I can Confirm this.

**Comment by alecward92** [comment] 2017-10-08 00:00
I am now seeing the server on that list. Just that secondary list so I see what was done. I use two user accounts between my client and host and forgot to update the client end.

**Comment by alecward92** [comment] 2017-10-08 00:12
Tried manually adding the primary master server "https://servers.openrct2.website/" and still ran into the same issue. Leaving it on "https://glacial-scrubland-24489.herokuapp.com/" for now

**Comment by Jerad2142** [comment] 2017-10-29 02:59
I found my server to be magically broadcasting after I had forgotten about it and left it running for a few weeks (we were only planning to play it as a group once in a while) I don't think anything changed on my  network, and I'm not sure what the issue was originally.

**Comment by GTW1226** [comment] 2017-10-30 04:43
I been using a Virtual Machine the last few days for the server so it shows. (A PAIN to do) On the 30th and 31st I am having special Maps and want people to JOIN! A whole new master list should be created. It seems like this list does not like our servers since they work on the other list.

**Comment by Jerad2142** [comment] 2017-12-09 00:19
So I set up a new computer and threw the newest openRCT on it, made sure the port was forwarded on my router and once again it seems to be failing to display on the listing (you can join it though by adding a server though). I just want to make sure that there isn't another port I need to forward.

**Comment by GTW1226** [comment] 2017-12-09 02:57
If people are joining it Jerad with the IP and port your good. 

Also I am running on mine on a VM for now on. I find it easier.

**Comment by Jerad2142** [comment] 2017-12-12 01:49
@GTW1226 No I mean we can't see it on the listing, so I have to tell people the IP and Port to enter every time they want to join.

**Comment by YoloSweggLord** [comment] 2018-01-20 22:37
Are others still having this issue? I know it's a bit of a bump but I've had this issue for a while now.

**Comment by YoloSweggLord** [comment] 2018-01-25 18:37
I just tested it, turning off ipv6 on my laptop allowed me to host. Since I have no clue what the difference is between these two connection types, is there any advantage to using ipv6 over ipv4? If so, does Windows 10 have a way to disable ipv6 only for specific programs? I tried an internet search but couldn't find much information on it.

**Comment by rwjuk** [comment] 2018-01-25 19:02
I'll do some investigating - there are no real user-facing advantages to IPv6 over v4, but plenty of 'hidden' ones. To say nothing of the fact that IPv4 will eventually be deprecated...

**Comment by janisozaur** [comment] 2018-01-25 20:28
Given we had reports of ipv6 hosts working with my alternative master server\*, I suspect the issue may lie with the master server.

\* that's what I get from the reports, I have not verified they actually advertise with ipv6.

**Comment by janisozaur** [comment] 2018-01-25 20:31
That leads me to suspicion: perhaps the issue lies with the way port forwarding is set up? In all cases so far I think it was only done for ipv4. Now ipv6 was supposed to alleviate things like NAT, but I know too little about ipv6 to exclude that option.

**Comment by alecward92** [comment] 2018-01-30 07:48
I'm going to run a test by shutting off the IPv6 protocol in my network settings and then try hosting to see if that resolves it.

**Comment by janisozaur** [comment] 2018-01-30 08:01
@alecward Can you check if this build fixes the problem: https://ci.appveyor.com/api/buildjobs/vat8qnbynhcw9wx2/artifacts/artifacts%2Fopenrct2-portable-release-x64-7ef0272.zip (with ipv6 enabled)?

**Comment by alecward92** [comment] 2018-01-30 08:29
@janisozaur  Just disabling IPv6 fixes the issue for me on both servers.

**Comment by alecward92** [comment] 2018-01-30 08:29
I'll take a look at that

**Comment by alecward92** [comment] 2018-01-30 08:32
I'm getting network errors from the link you provided. It downloads about halfway and stops downloading. I turned IPv6 back on while the servers are still hosted and I can confirm they are showing up still.

**Comment by janisozaur** [comment] 2018-01-30 08:36
Here's the build mirrored from appveyor: [openrct2-portable-release-x64-7ef0272.zip](https://github.com/OpenRCT2/OpenRCT2/files/1676858/openrct2-portable-release-x64-7ef0272.zip)

Please test this with ipv6 enabled

**Comment by janisozaur** [comment] 2018-02-11 21:00
This really is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/4953, but there is valuable information here, so I'll let it stay a while longer until the fix (#7103) is in.

**Comment by janisozaur** [comment] 2018-02-12 19:41
Fixed in #7103

**Closed by janisozaur** 2018-02-12 19:41 UTC
Labels: interface, investigate, multiplayer
