### ISSUE TITLE
Unable to start after crash

### ISSUE THREAD

**Issue by ptkato** [OpenRCT2/OpenRCT2#3918] opened 2016-06-20 03:44 UTC
**OS:**
Arch Linux
**Version:**
0.0.5
**Commit/Build:**
97fedab

Tried to enter in one of the "manofteal" servers, it started downloading the stuff, suddenly, it just closes. Tried to start the game and nothing happened. Started through terminal and got the following:

    INFO[/home/ptkato/.cache/pacaur/openrct2-git/src/openrct2-git/src/object_list.c:429
    (object_list_cache_load)]: 70 object added... updating object list cache
    fish: “openrct2” terminated by signal SIGSEGV (Address boundary error)

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Try to join a manofteal server;
2. Crash.

**Dump file**
[orct2_coredump.tar.gz](https://github.com/OpenRCT2/OpenRCT2/files/322688/orct2_coredump.tar.gz)

**Comment by Gymnasiast** [comment] 2016-06-20 06:52
Duplicate of #3916.

**Comment by Nubbie** [comment] 2016-06-30 20:31
@ptkato 
Could you run openrct2.exe from the command prompt and with --verbose as an argument?
This mean:

1.  Open a command prompt
2.  cd to the directory where openrct2.exe resides
3.  openrct2.exe --verbose


Can you then right click and copy all the text and paste it in here? (or at least show a screenshot at the end of the text)
_(copied from Dev Gymnasiast)_

**Comment by ptkato** [comment] 2016-06-30 23:57
Actually, no. I fixed the problem reinstalling it. See [this comment](https://github.com/OpenRCT2/OpenRCT2/issues/3916#issuecomment-228430509).

**Comment by mrtnptrs** [comment] 2016-07-15 13:26
Then this issue can be closed as there is no way for us anymore to find the cause of the original issue here, as @ptkato did a re-install.

**Comment by Gymnasiast** [comment] 2016-07-15 13:50
The object loading code has been thoroughly revised in the meantime anyway.

**Closed by Gymnasiast** 2016-07-15 13:50 UTC
Labels: crash, duplicate, multiplayer
