### ISSUE TITLE
Having over 5000 objects in your Objdata folder does not allow you to scroll down in object selection in small scenery

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5016] opened 2017-01-07 23:25 UTC
Windows 7
0.0.6
fa51d15

 If you have over 5000 objects in your Objdata folder, the object selection does not allow you to scroll down  much in small scenery.

- [ yes] Reproducible in RCT2 (vanilla)?
- [both ] Multiplayer?

**Steps to reproduce:**
1. Have over 5000 objects in your objdata folder
2. Open up object selection and navigate to small scenery
3. Scroll down, and you should see that the menu glitches and does not allow you to scroll down much.

**Screenshots / Video:**
![untitled](https://cloud.githubusercontent.com/assets/24964930/21746037/a9f21b98-d506-11e6-855b-bb0c0ba9342e.png)

**Comment by YoloSweggLord** [comment] 2017-01-07 23:28
Step 1 can be a bit hard to complete to reproduce this error. Where are we supposed to get 5000 objects in a timely manner?

**Comment by xp4xbox** [comment] 2017-01-07 23:29
I can give you a folder of my objdata files, it has over 6000 objects.

**Comment by YoloSweggLord** [comment] 2017-01-07 23:34
That would be useful, but only send the object folder in your documents/openrct2 directory, not your objdata folder which contains the base game/expansion material. We don't want to give away free copies of paid material.

**Comment by YoloSweggLord** [comment] 2017-01-07 23:36
I do remember there being an issue where having too many objects in your objdata folder would cause them to not all be displayed, but I don't remember there being a problem displaying the menu when that limit is exceeded.

**Comment by xp4xbox** [comment] 2017-01-07 23:59
My Openrct object folder has only a couple hundred objects though.

This was an issue I had with regular rct2, but with openrct2, there is a *buggy* search bar so its not critical like regular rct2. But yeah, its one of the reasons why I stopped playing a while back.

**Comment by Gymnasiast** [comment] 2017-01-08 15:39
This is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/592.

You can use the search function and the filters to work around this problem. We do plan to fix it properly though.

**Closed by Gymnasiast** 2017-01-08 15:39 UTC
