### ISSUE TITLE
Guest exhibiting odd behavior when sick.

### ISSUE THREAD

**Issue by formlesstree4** [OpenRCT2/OpenRCT2#1911] opened 2015-09-09 20:17 UTC
I've got a park that I started in Roller Coaster Tycoon 2 TTP (Steam version) and began playing in OpenRCT2.

By and large, the park works great (you guys have done fantastic work). However, I came across a recent issue that left me puzzled.

![image](https://cloud.githubusercontent.com/assets/6273530/9772962/1350093c-5705-11e5-9182-6ca434bbd2ac.png)

I have the guest above (named "darkkalvidya") that, despite being sick, walks around like normal. The save file I'm attaching will be at the point I noticed the behavior. I let the game play him out for a bit and eventually he found a pair of benches that he toggled back and forth from (with the game flashing his next action was to head to the First Aid station between movements; perhaps an AI bug?). If the game loads without the guest selected, he's one of the handful of guests that is tracked.

Here's the save game file in question.
https://www.dropbox.com/s/vgm5liku4senrsa/The%20Flatlands%202.SV6?dl=0

Note: This save file has had twitch integration enabled and the guest renamed to one of my followers. That's how I noticed this issue in the first place. May or may not be related.

EDIT: v0.0.3 Build 1215

**Comment by CannaeLogin** [comment] 2016-01-23 09:14
I'm sure I've seen this happen ocassionally in vanilla RCT2.

**Comment by IntelOrca** [comment] 2016-04-03 11:17
I can't find the guest with the problem, no guests have custom names in the saved game.

**Comment by janisozaur** [comment] 2016-04-03 11:19
Do these get saved?

@LRFLEW said he suspects #3205 is affected by nearby puke, perhaps this is all somehow connected? (#3205, #2499 and this)

**Comment by IntelOrca** [comment] 2016-04-03 11:58
@janisozaur I know the cause of #3205, I said so in that issue. Both #3205 and #2499 are related to pathfinding, this so far doesn't have any relationship.

**Comment by Gymnasiast** [comment] 2016-04-10 10:50
@formlesstree4 Could you tell us which guest in that save is exhibiting the strange behaviour?

**Comment by Nubbie** [comment] 2016-04-10 23:38
IF you guys haven't found out what causes this glitch, I think **Deluxe** gave me a clue
The guest in the picture is wearing sunglasses, it seems like balloons and sunglasses doesn't trigger the sick animation as they don't have one

See the video for more info: https://vid.me/6jTZ
Observe that 'Balloon' only has a balloon - Sunglasses only has 'Sunglasses' - Nothing has nothing

**Comment by Nubbie** [comment] 2016-09-15 18:14
Isnt it just possible to force the peep to walk slowly, even if the wear sunglasses, when nausea? 
Presume there isn't a sprite for the nausea peeps when sunglasses covers the face

**Comment by Christipher** [comment] 2016-09-20 18:17
Something is telling me that this might be a quirk handed down from the original game... probably if they are holding something and fall ill...

**Comment by kkirby** [comment] 2023-12-15 21:11
Unless the issue is reproducible, it should be closed as the original save file has been removed from dropbox. @formlesstree4 Do you still have it?

**Comment by Gymnasiast** [comment] 2024-01-25 15:24
Closing as the save it indeed no longer available. And it’s been more than 8 years, so it may simply have been fixed already. Please let us know if it isn’t.

**Closed by Gymnasiast** 2024-01-25 15:24 UTC
Labels: original bug
