### ISSUE TITLE
Mountain tool hangs

### ISSUE THREAD

**Issue by JeroenDStout** [OpenRCT2/OpenRCT2#3620] opened 2016-05-15 20:41 UTC
**OS:** Windows 7
**Version:** 701

When using the mountain tool, the game lags (or even hangs) and the console window spews out an endless amount of this:

![openrct2bug](https://cloud.githubusercontent.com/assets/14242454/15276606/fa72de10-1aec-11e6-8027-65502ef10ea8.gif)

From what I can tell it happens mostly near the edges of the map, but that does not seem to be terribly consistent. It happens on the "Build Your Own Six Flags" map, "Rock 'n Roll Flower Power", "Prison Island", but not on "Bumbly Bazaar" or "African Diamond Farm". Maybe something to do with map size, but I didn't have time to try them all.

After a deletion of the OpenRCT2 folder in /documents/, the problem was reduced, but did not disappear.

**Comment by janisozaur** [comment] 2016-05-15 20:42
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3549

**Closed by janisozaur** 2016-05-15 20:42 UTC
Labels: duplicate

**Comment by janisozaur** [comment] 2016-05-15 20:43
Also: version "701" is not a valid version.
