### ISSUE TITLE
Cannot lift terrain under sloped footpath

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#10621] opened 2020-01-25 19:07 UTC
**OS:** Windows 7
**Version:** e.g. 0.2.4-466-gd1eb04195
**Commit/Build:** d1eb041

![nopathsforyou](https://user-images.githubusercontent.com/4167951/73126010-6a968c80-3f7b-11ea-8a59-2c2194be5cba.png)

Under normal circumstances, you can raise land underneath a path to the point where the land and path "merge" and the path becomes grounded. However, if the footpath is slopped, you cannot nudge the ground upwards, either in full or at one of the angles, to merge with the footpath above.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Construct a slopped path in mid-air
2. Attempt to raise the ground underneath so it would otherwise touch or intersect with the footpath- it stops one height space short.

**Comment by jensj12** [comment] 2020-01-26 08:25
Duplicate of #2307 and very closely related to #2296.

**Closed** 2020-01-26 08:53 UTC
