### ISSUE TITLE
IPV6_V6ONLY failed. 92

### ISSUE THREAD

**Issue by jackkiej** [OpenRCT2/OpenRCT2#5212] opened 2017-02-12 23:37 UTC
```
ERROR[/root/OpenRCT2/src/openrct2/network/TcpSocket.cpp:157 (Listen)]: IPV6_V6ONLY failed. 92
```

**OS:** Fedora 25
**Commit/Build:**  5e812d5

When I start the headless server on Fedora I get the error message above, after that it states "Ready for clients" and server works perfect, but I don't understand why I get that error message above..

**Comment by Margen67** [comment] 2017-03-31 08:04
Possible duplicate of #4953

**Closed** 2017-05-03 12:08 UTC
Labels: investigate, multiplayer

**Comment by IntelOrca** [comment] 2017-06-03 23:44
This can happen if you have multiple addresses you can bind to. It is now possible to specify and address:
`openrct2 host park.sv6 --address localhost`
`openrct2 host park.sv6 --address 82.152.129.21 --port 9182`

**Comment by cablegunmaster** [comment] 2018-10-17 03:54
Thanks this made my server start correctly :) .
