### ISSUE TITLE
BACKTRACE cfcb6c rct_peep::UpdateRideLeaveVehicle

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8226] opened 2018-11-05 01:56 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/cfcb6c642ace5e618066031aa0840742f854858b37c09799dde4241cda0cd9bd?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Mon Nov 05 2018 01:56:13)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 3aeb87b: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>rct_peep::UpdateRideLeaveVehicle -> rct_peep::UpdateRide -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> SDL_PeepEvents_REAL -> SDL_WaitEventTimeout_REAL -> SDL_PollEvent_REAL -> UiContext::ProcessMessages -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2018-11-05 05:58
```
dump_path: /var/coronerd//openrct2/openrct2/_objects/0000/tx.0088.dmp outfile: -
Classifier: invalid-read
Crash info:
	Application: openrct2.com
	Crashed YES
	reason: EXCEPTION_ACCESS_VIOLATION_READ
	address: 0x3
Memory Regions:
Sysinfo:
	arch: x86 GenuineIntel family 6 model 15 stepping 11
	cpu_count: 4
	os: Windows NT windows 6.1.7601 Service Pack 1
Modules:
	0x190000 - 0x1b9000	openrct2.com 
	0xaf30000 - 0xaf68000	icm32.dll 6.1.7601.23971
	0xf9b0000 - 0x10810000	openrct2.dll 
	0x5cc10000 - 0x5cc89000	mscms.dll 6.1.7601.23971
	0x678b0000 - 0x678e6000	AudioSes.dll 6.1.7601.23471
	0x68bf0000 - 0x68c58000	UMEngx86.dll 11.5.1.29
	0x6c920000 - 0x6ca0b000	dbghelp.dll 6.1.7601.17514
	0x6cac0000 - 0x6cac6000	IconCodecService.dll 6.1.7600.16385
	0x6e8f0000 - 0x6e8f3000	api-ms-win-core-synch-l1-2-0.DLL 10.0.14393.2247
	0x713a0000 - 0x713d2000	winmm.dll 6.1.7601.17514
	0x73800000 - 0x73931000	WindowsCodecs.dll 6.2.9200.22551
	0x73970000 - 0x73983000	dwmapi.dll 6.1.7601.18917
	0x73c60000 - 0x73ca0000	uxtheme.dll 6.1.7600.16385
	0x73cc0000 - 0x73e5e000	comctl32.dll 6.10.7601.18837
	0x74210000 - 0x74305000	propsys.dll 7.0.7601.17514
	0x74310000 - 0x74349000	MMDevAPI.dll 6.1.7601.17514
	0x74390000 - 0x74397000	avrt.dll 6.1.7600.16385
	0x74540000 - 0x74565000	powrprof.dll 6.1.7600.16385
	0x74570000 - 0x74579000	version.dll 6.1.7600.16385
	0x748b0000 - 0x748eb000	rsaenh.dll 6.1.7600.16385
	0x74ad0000 - 0x74ad6000	wship6.dll 6.1.7600.16385
	0x74ae0000 - 0x74b1c000	mswsock.dll 6.1.7601.23451
	0x74b20000 - 0x74b37000	cryptsp.dll 6.1.7601.23471
	0x74e60000 - 0x74e68000	secur32.dll 6.1.7601.24260
	0x74fa0000 - 0x74fbb000	sspicli.dll 6.1.7601.24260
	0x75010000 - 0x7501c000	CRYPTBASE.dll 6.1.7601.24260
	0x750f0000 - 0x750fb000	profapi.dll 6.1.7600.16385
	0x75100000 - 0x7510c000	msasn1.dll 6.1.7601.17514
	0x75110000 - 0x75114000	api-ms-win-downlevel-user32-l1-1-0.dll 6.2.9200.16492
	0x75120000 - 0x75242000	crypt32.dll 6.1.7601.23971
	0x75250000 - 0x75253000	api-ms-win-downlevel-normaliz-l1-1-0.dll 6.2.9200.16492
	0x75260000 - 0x75272000	devobj.dll 6.1.7600.16385
	0x75280000 - 0x75284000	api-ms-win-downlevel-version-l1-1-0.dll 6.2.9200.16492
	0x75290000 - 0x752b7000	cfgmgr32.dll 6.1.7601.17514
	0x752c0000 - 0x752c5000	api-ms-win-downlevel-advapi32-l1-1-0.dll 6.2.9200.16492
	0x75300000 - 0x7534b000	KERNELBASE.dll 6.1.7601.24168
	0x753f0000 - 0x753f4000	api-ms-win-downlevel-shlwapi-l1-1-0.dll 6.2.9200.16492
	0x75400000 - 0x75417000	userenv.dll 6.1.7601.17514
	0x75420000 - 0x7557d000	ole32.dll 6.1.7601.24168
	0x75580000 - 0x75599000	sechost.dll 6.1.7601.18869
	0x755a0000 - 0x7561b000	comdlg32.dll 6.1.7601.17514
	0x75620000 - 0x7563f000	imm32.dll 6.1.7601.17514
	0x75640000 - 0x75675000	ws2_32.dll 6.1.7601.23451
	0x75680000 - 0x7571d000	usp10.dll 1.626.7601.23894
	0x75720000 - 0x75726000	nsi.dll 6.1.7601.23889
	0x75730000 - 0x757b3000	clbcatq.dll 2001.12.8530.16385
	0x757c0000 - 0x75895000	kernel32.dll 6.1.7601.24168
	0x758a0000 - 0x75c81000	wininet.dll 11.0.9600.19155
	0x75c90000 - 0x75d31000	advapi32.dll 6.1.7601.24260
	0x75da0000 - 0x75dee000	gdi32.dll 6.1.7601.24260
	0x75df0000 - 0x75ebd000	msctf.dll 6.1.7601.23915
	0x76010000 - 0x761ad000	setupapi.dll 6.1.7601.17514
	0x761b0000 - 0x76207000	shlwapi.dll 6.1.7601.17514
	0x76210000 - 0x76213000	normaliz.dll 6.1.7600.16385
	0x76220000 - 0x762b1000	oleaut32.dll 6.1.7601.24117
	0x762c0000 - 0x76389000	user32.dll 6.1.7601.23594
	0x76390000 - 0x76432000	rpcrt4.dll 6.1.7601.24260
	0x76440000 - 0x7708c000	shell32.dll 6.1.7601.24234
	0x77090000 - 0x772c6000	iertutil.dll 11.0.9600.19155
	0x77320000 - 0x77462000	ntdll.dll 6.1.7601.24260
	0x774b0000 - 0x774ba000	lpk.dll 6.1.7601.24231
	0x774c0000 - 0x7756c000	msvcrt.dll 7.0.7601.17744
Threads:
	thread-0 tid=3372 faulted
	[0] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!rct_peep::UpdateRideLeaveVehicle() [c:\projects\openrct2-ject9\src\openrct2\peep\guest.cpp : 4092 + 0xd]
		ip=0xfb11f10 sp=0x32f64c bp=0x32f69c 
	[1] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!rct_peep::UpdateRide() [c:\projects\openrct2-ject9\src\openrct2\peep\guest.cpp : 5065 + 0x5]
		ip=0xfb1332b sp=0x32f6a4 bp=0x32f6bc 
	[2] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!rct_peep::Update() [c:\projects\openrct2-ject9\src\openrct2\peep\peep.cpp : 1331 + 0x18]
		ip=0xfaaf6ba sp=0x32f6c4 bp=0x32f704 
	[3] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::GameState::UpdateLogic() [c:\projects\openrct2-ject9\src\openrct2\gamestate.cpp : 246 + 0xe0]
		ip=0xfa817a7 sp=0x32f70c bp=0x32f758 
	[4] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::GameState::Update() [c:\projects\openrct2-ject9\src\openrct2\gamestate.cpp : 140 + 0x7]
		ip=0xfa81297 sp=0x32f760 bp=0x32f798 
	[5] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::Update() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 936 + 0x8]
		ip=0xfa5af72 sp=0x32f7a0 bp=0x32f838 
	[6] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!SDL_PeepEvents_REAL(SDL_Event *,int,SDL_eventaction,unsigned int,unsigned int) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\events\sdl_events.c : 578 + 0x6]
		ip=0xfd199e2 sp=0x32f7b0 bp=0x32f838 
		guessed frame
	[7] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!SDL_WaitEventTimeout_REAL(SDL_Event *,int) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\events\sdl_events.c : 681 + 0x11]
		ip=0xfd19fb7 sp=0x32f7c4 bp=0x32f838 
	[8] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!SDL_PollEvent_REAL(SDL_Event *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\events\sdl_events.c : 662 + 0xb]
		ip=0xfd199fb sp=0x32f7e8 bp=0x32f838 
	[9] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!UiContext::ProcessMessages() [c:\projects\openrct2-ject9\src\openrct2-ui\uicontext.cpp : 523 + 0x12]
		ip=0xf9d76d7 sp=0x32f7f4 bp=0x32f838 
	[10] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunVariableFrame() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 891 + 0x7]
		ip=0xfa5ac0a sp=0x32f840 bp=0x32f888 
	[11] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunGameLoop() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 801 + 0x50]
		ip=0xfa5aaa3 sp=0x32f890 bp=0x32f8a8 
	[12] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::Launch() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 773 + 0x8]
		ip=0xfa5a9c7 sp=0x32f8b0 bp=0x32f910 
	[13] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int,char const * *) [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 213 + 0x7]
		ip=0xfa58c6a sp=0x32f918 bp=0x32f924 
	[14] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!NormalisedMain(int,char const * *) [c:\projects\openrct2-ject9\src\openrct2-ui\ui.cpp : 60 + 0x13]
		ip=0xf9d3da7 sp=0x32f92c bp=0x32f99c 
	[15] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!LaunchOpenRCT2(int,wchar_t * *) [c:\projects\openrct2-ject9\src\openrct2-dll\openrct2-dll.cpp : 46 + 0x9]
		ip=0xf9d38c2 sp=0x32f9a4 bp=0x32f9c0 
	[16] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.com!wmain(int,wchar_t * *,wchar_t *) [c:\projects\openrct2-ject9\src\openrct2-win\openrct2-win.cpp : 27 + 0xc]
		ip=0x19100f sp=0x32f9c8 bp=0x32f9d0 
	[17] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.com!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl : 288 + 0x1c]
		ip=0x1911d3 sp=0x32f9d8 bp=0x32fa18 
	[18] C:\Windows\System32\kernel32.dll!_BasepCopyEncryption@56 + 0x87
		ip=0x7580efac sp=0x32fa20 bp=0x32fa24 
	[19] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x2e
		ip=0x77383618 sp=0x32fa2c bp=0x32fa64 
	[20] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x1
		ip=0x773835eb sp=0x32fa6c bp=0x32fa7c 
	thread-1 tid=4248 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77366c04 sp=0x79fa88 bp=0x79fabc 
	[1] C:\Windows\System32\kernel32.dll!_BasepCopyEncryption@56 + 0x87
		ip=0x7580efac sp=0x79fac4 bp=0x79fac8 
		guessed frame
	[2] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x2e
		ip=0x77383618 sp=0x79fad0 bp=0x79fb08 
	[3] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x1
		ip=0x773835eb sp=0x79fb10 bp=0x79fb20 
	thread-2 tid=5708 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77366c04 sp=0x239f6ac bp=0x239f748 
	[1] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0x850
		ip=0x7736658c sp=0x239f6b0 bp=0x239f6fc 
		guessed frame
	[2] C:\Windows\System32\KERNELBASE.dll!_InterlockedExchange@8 + 0x6
		ip=0x75306a8e sp=0x239f6b4 bp=0x239f770 
		guessed frame
	[3] C:\Windows\System32\KERNELBASE.dll!_KernelBaseGetGlobalData@0 + 0x72
		ip=0x75306b36 sp=0x239f6f8 bp=0x239f770 
	[4] 0x239f7d4
		ip=0x239f7d4 sp=0x239f778 bp=0x178 
	[5] C:\Windows\System32\user32.dll!_WinStationSendMessageW@40 + 0xb300
		ip=0x7632631b sp=0x239f77c bp=0x239f7d4 
		guessed frame
	thread-3 tid=4900 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77366c04 sp=0x24ffb98 bp=0x24ffce8 
	[1] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0x880
		ip=0x773665bc sp=0x24ffb9c bp=0x24ffc4c 
		guessed frame
	[2] C:\Windows\System32\ntdll.dll!_RtlpProbeAssemblyStorageRootForAssembly@28 + 0xde
		ip=0x77351102 sp=0x24ffba0 bp=0x4f64c8 
		guessed frame
	[3] C:\Windows\System32\propsys.dll!?Worker@DeserializeHelper@@QAEJPBUtagSERIALIZEDPROPERTYVALUE@@KHHHPAUtagPROPVARIANT@@PAK@Z + 0x6f7
		ip=0x7427d739 sp=0x24ffbac bp=0x4f64c8 
		guessed frame
	[4] C:\Windows\System32\ntdll.dll!_RtlAllocateMemoryZone@12 + 0x120c
		ip=0x773f8338 sp=0x24ffbbc bp=0x4f64c8 
		guessed frame
	[5] C:\Windows\System32\ntdll.dll!_RtlAllocateMemoryZone@12 + 0x120c
		ip=0x773f8338 sp=0x24ffbc0 bp=0x4f64c8 
		guessed frame
	thread-4 tid=2520 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77366c04 sp=0x2c0f2b4 bp=0x2c0f2c4 
	[1] C:\Windows\System32\kernel32.dll!_BaseCopyStream@56 + 0x3f5
		ip=0x7580f972 sp=0x2c0f2c8 bp=0x2c0f57c 
		guessed frame
	thread-5 tid=5420 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77366c04 sp=0x2e1f958 bp=0x2e1f9b0 
	[1] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0x840
		ip=0x7736657c sp=0x2e1f95c bp=0x2e1f980 
		guessed frame
	[2] C:\Windows\System32\ntdll.dll!_RtlpSetTimeZoneInformationWorker@8 + 0xff
		ip=0x77373867 sp=0x2e1f990 bp=0x2e1f980 
		guessed frame
	[3] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!__crtSleepConditionVariableSRW(_RTL_CONDITION_VARIABLE *,_RTL_SRWLOCK *,unsigned long,unsigned long) [f:\dd\vctools\crt\crtw32\misc\winapisupp.cpp : 657 + 0x2]
		ip=0xfda4189 sp=0x2e1f9ec bp=0x2e1f9dc 
	[4] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!Concurrency::details::stl_condition_variable_win7::wait_for(Concurrency::details::stl_critical_section_interface *,unsigned int) [f:\dd\vctools\crt\crtw32\stdcpp\thr\primitives.h : 216 + 0x15]
		ip=0xff10700 sp=0x2e1fa08 bp=0xffb3b4c0 
	[5] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!do_wait(_Cnd_internal_imp_t *,_Mtx_internal_imp_t *,xtime const *) [f:\dd\vctools\crt\crtw32\stdcpp\thr\cond.c : 82 + 0x5]
		ip=0xff105fe sp=0x2e1fa20 bp=0x2e1fa54 
		guessed frame
	[6] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_b1de77b2e28beeaf6256a3f41ee36302> >,std::default_delete<std::tuple<<lambda_b1de77b2e28beeaf6256a3f41ee36302> > > > >::_Go() [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\thr\xthread : 230 + 0x110]
		ip=0xfdeffec sp=0x2e1fa5c bp=0x2e1faac 
	[7] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!std::_Pad::_Call_func(void *) [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\thr\xthread : 208 + 0x7]
		ip=0xfa8372a sp=0x2e1fab4 bp=0x2e1fab4 
	[8] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!thread_start<unsigned int (__stdcall*)(void *)>(void * const) [d:\rs1\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 115 + 0x2]
		ip=0xfdd7d15 sp=0x2e1fabc bp=0x2e1faf0 
	[9] C:\Windows\System32\kernel32.dll!_BasepCopyEncryption@56 + 0x87
		ip=0x7580efac sp=0x2e1faf8 bp=0x2e1fafc 
	[10] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x2e
		ip=0x77383618 sp=0x2e1fb04 bp=0x2e1fb3c 
	[11] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x1
		ip=0x773835eb sp=0x2e1fb44 bp=0x2e1fb54 
	thread-6 tid=5768 
	[0] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0xec8
		ip=0x77366c04 sp=0x28bf9e4 bp=0x28bfa50 
	[1] C:\Windows\System32\ntdll.dll!_RtlpNewSecurityObject@36 + 0x870
		ip=0x773665ac sp=0x28bf9e8 bp=0x28bfa68 
		guessed frame
	[2] C:\Windows\System32\kernel32.dll!_BasepMoveFileDelayed@20 + 0x26b
		ip=0x7580c4f0 sp=0x28bfa08 bp=0x3f5fd30 
		guessed frame
	[3] C:\Windows\System32\KERNELBASE.dll!_MakeNamedLocaleHashNode@8 + 0x1ce
		ip=0x753206bd sp=0x28bfa48 bp=0x28bf9f8 
		guessed frame
	[4] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!SDL_GetSurfaceAlphaMod_DEFAULT(SDL_Surface *,unsigned char *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\dynapi\sdl_dynapi_procs.h : 487 + 0x96]
		ip=0xfcf45f6 sp=0x28bfa4c bp=0x7874a86e 
		guessed frame
	[5] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!WASAPI_WaitDevice(SDL_AudioDevice *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\audio\wasapi\sdl_wasapi.c : 331 + 0x7]
		ip=0xfd40b0b sp=0x28bfa70 bp=0x7874a86e 
	[6] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!SDL_RunAudio(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\audio\sdl_audio.c : 711 + 0x7]
		ip=0xfd14ca6 sp=0x28bfa90 bp=0x7874a86e 
	[7] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll + 0x3cb40
		ip=0xf9ecb40 sp=0x28bfaac bp=0x7874a86e 
	[8] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!SDL_RunThread(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\thread\sdl_thread.c : 283 + 0x3]
		ip=0xfd0c44e sp=0x28bfab0 bp=0x7874a86e 
		guessed frame
	[9] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!RunThreadViaBeginThreadEx(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\thread\windows\sdl_systhread.c : 105 + 0x11]
		ip=0xfd33e17 sp=0x28bfad0 bp=0x7874a86e 
	[10] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll + 0x383e00
		ip=0xfd33e00 sp=0x28bfae0 bp=0x7874a86e 
	[11] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll!thread_start<unsigned int (__stdcall*)(void *)>(void * const) [d:\rs1\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 115 + 0x2]
		ip=0xfdd7d15 sp=0x28bfae4 bp=0x7874a86e 
		guessed frame
	[12] C:\Users\Owner\Documents\OpenRCT2\bin\openrct2.dll + 0x40e030
		ip=0xfdbe030 sp=0x28bfb10 bp=0x7874a86e 
		guessed frame
	[13] C:\Windows\System32\kernel32.dll!_BasepCopyEncryption@56 + 0x87
		ip=0x7580efac sp=0x28bfb20 bp=0x28bfb24 
		guessed frame
	[14] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x2e
		ip=0x77383618 sp=0x28bfb2c bp=0x28bfb64 
	[15] C:\Windows\System32\ntdll.dll!_RtlSetEnvironmentStrings@8 + 0x1
		ip=0x773835eb sp=0x28bfb6c bp=0x28bfb7c 
```

**Comment by janisozaur** [comment] 2019-02-02 19:45
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/7700

**Closed by janisozaur** 2019-02-02 19:45 UTC
Labels: backtrace.io, crash
