### ISSUE TITLE
Paths randomly lose connection to shops and ride exits

### ISSUE THREAD

**Issue by L3P3** [OpenRCT2/OpenRCT2#7042] opened 2018-01-17 20:52 UTC
**Version:** v0.1.2
**Commit/Build:** 3ba0cc3

From time to time, some connections between paths and shops/exits are lost.
A path is right next to a shop but after some minutes, it is no more connected.
I do not know why but I think it happens without me doing anything to the affected units.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build path and shop how you would do it normally
2. Go away for a moment, build etc.
3. After a few minutes you get messages saying that a ride is still not repaired, since the repair guy cannot access the exit. Or you just see that it is not connected and that it had no customers the last few months.

**Screenshots / Video:**

![disconn](https://user-images.githubusercontent.com/4629449/35066186-0f7ceefc-fbd0-11e7-8d0a-5f0e250b8165.png)

**Comment by L3P3** [comment] 2018-01-17 20:56
The bug is so critical that I do not want to play it as long as it exists.
It is unplayable when you have hundreds of shops and after half an hour the half of all shops are disconnected and practically ineffective.

**Comment by rwjuk** [comment] 2018-01-17 23:57
@L3P3 Does this happen in every park?

**Comment by saxman1089** [comment] 2018-01-18 13:50
This is something that occurs when you build paths with "disable clearance checks" enabled. It is a bug that has been around for a while and it happens in every park I've ever built on, I've just never reported it because it is happening when using a cheat-type feature. 

I'm also not sure the behavior is "random". It may be that the last path you connected to a shop/stall/ride exit that gets disconnected, but it's hard to know this for sure, given that you don't notice its been disconnected until later after doing some building. 

As for an affected save file, I can provide some later when I get home, but it's literally any park where you build path with clearance checks disabled. Try these steps for reproducing: 
1) Build a stall/shop/ride exit and connect a path to it with clearance checks ON.
2) Disable clearance checks, build some paths somewhere else.
3) See if the stall/shop/ride exit is disconnected.

**Comment by deurklink** [comment] 2018-01-21 15:25
![pathdisconnect](https://user-images.githubusercontent.com/6469413/35195683-84995fc8-fec7-11e7-8ec0-4300d58c2234.gif)
They disconnect when you hover over them with a building tool with clearance checks disabled. The one that stayed connected in the gif accidentally had a path under it (whoops).

**Comment by jamtraks** [comment] 2018-01-23 17:31
From what i have experienced this can happen quite "randomly". Sometimes when you build a path in front of a stall, the path will connect automatically to the front of the stall while sometimes it won't. Generally speaking you should always check to see if the path has connected to the actual stall, by using the tile inspector or by visually checking to see the small connection of the path to the stall. If the path is not connected to the stall, you can usually connect it by clicking the path build tool again on the front of the stall, but even better, you can click the tile inspector on the square of path in front of the stall, then click on "path", then check the quadrant or eighth box that corresponds to the front of the stall. You must have "enable debugging tools" checked in the options/miscellaneous(wrench) menu in order to access the tile inspector.

**Closed** 2018-03-18 09:19 UTC
Labels: bug, investigate
