### ISSUE TITLE
(Perhaps) Infinite loop while loading a certain RCTC custom scenario

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#7224] opened 2018-02-27 13:59 UTC
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 57be3b4

This scenario is created by RollerCoaster Tycoon Classic, and it seems that it is loaded successfully in RCTC with all expansion packs.
But it is not able to load this in OpenRCT2, only shows a black screen as you can see in the below screenshot I attached.

It says "Game save failed!" error with no black screen when I try to load this in 0.1.1.
I think it is a kind of infinite loop which could occur in during load RCTC scenario. (Not sure.)
I heard that RCTC sc6 file format is slightly different from vanilla/OpenRCT2's one, and I think it is the one reason that this scenario can't be loaded.

It was not shown in the vanilla's scenario list.

Please see this scenario and tell me what is the reason.
I think the author of this scenario would want to know why it is.

**Steps to reproduce:**
1. Load the scenario

**Dump file**
No dump files.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/36732291-ad91f0e6-1c10-11e8-897c-4d0b99447106.png)
(FPS is displayed in duplicate)

**Save game:**
[Something Wrong Park 2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1763109/Something.Wrong.Park.2.zip)

**Comment by janisozaur** [comment] 2018-02-27 14:34
Can you check if that's a dupe of https://github.com/OpenRCT2/OpenRCT2/issues/7209, namely regression from https://github.com/OpenRCT2/OpenRCT2/pull/7139, e.g. by trying 73c861ab5 or older.

**Comment by telk5093** [comment] 2018-02-27 19:11
@janisozaur 
 * Do you mean that I experience the same issue when I open the Indiana Jones save that can found in the link in #7209? If it is, The save was opened successfully, so it seems not a dupe of #7209.
 * I've tried 8b72c4f1ad2da49a34af1beab4bb18c8c9c34b51 which is older than 73c861a (I think), but it was the same.

**Comment by Gymnasiast** [comment] 2018-03-13 19:17
I just tried this in b78bd587b785525b32e14a499b94241144a4a027 and it loads correctly. Could you try it again?

**Closed** 2019-09-23 03:35 UTC
Labels: investigate
