### ISSUE TITLE
Block Brakes mess with the coaster simulation/ghost train feature

### ISSUE THREAD

**Issue by VersionEins** [OpenRCT2/OpenRCT2#11030] opened 2020-03-25 11:50 UTC
**OS:** Windows 10
**Version:** 0.2.5
**Commit/Build:** 4f6e77e

When using block brakes, the coaster simulation feature will not start, demanding that the circuit has to be closed.

**Steps to reproduce:**
1. Build part of a rollercoaster
2. Add a block brake
3. Stop the simulation and try to start it again

**Screenshots / Video:**

![Forest Frontiers 2020-03-25 12-47-49](https://user-images.githubusercontent.com/62649879/77533422-20f0f200-6e97-11ea-8e05-4bbf004ef653.png)

**Comment by Gymnasiast** [comment] 2020-03-25 11:56
This is duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/9890 .

You can follow the bug status there.

**Closed by Gymnasiast** 2020-03-25 11:56 UTC
