### ISSUE TITLE
Crash returning to main menu

### ISSUE THREAD

**Issue by lonemadman** [OpenRCT2/OpenRCT2#18564] opened 2022-11-12 18:12 UTC
### Operating System

Windows 10 Home 19043.2251

### OpenRCT2 build

v0.4.2-158-g3b183a5

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

Issues building the game

### Describe the issue

When quitting to menu, error occurs.

It is something in the park save file (also attached) as no other parks or saves cause the crash, but the problem does repeat with this save file. Save file attached.

Similar to issue #18464 but different failure

### Steps to reproduce

Steps to produce
In Alpine Adventures (.park file attached)
Select "Quit to Menu"
Attached error message shows
Main menu works for c.30 seconds, then ORCT2 freezes and closes itself

### Attachments

![image](https://user-images.githubusercontent.com/96085994/201488232-7966cf41-a273-4914-b695-f0eec1e4fd6b.png)
[Alpine Adventures.zip](https://github.com/OpenRCT2/OpenRCT2/files/9995608/Alpine.Adventures.zip)

**Comment by janisozaur** [comment] 2022-11-12 19:00
Please post the dump as well

**Comment by lonemadman** [comment] 2022-11-12 19:03
Apologies, see attached

[0277849d-4ae0-4b59-9bad-dd5aae5f076f(3b813a5_x86).zip](https://github.com/OpenRCT2/OpenRCT2/files/9995717/0277849d-4ae0-4b59-9bad-dd5aae5f076f.3b813a5_x86.zip)

**Comment by janisozaur** [comment] 2022-11-12 19:10
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/18549

**Closed by janisozaur** 2022-11-12 19:10 UTC
Labels: bug
