### ISSUE TITLE
Feature Request: Scenery saver (maybe even multi-ride saver?)

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7847] opened 2018-08-02 09:31 UTC
I'd really like a feature similar to the 'save track design with scenery' feature, but where I could just activate the tool, select a bunch of scenery, and then save that scenery without any ride necessary.

I've seen people using the 'save track design with scenery' feature to do similar things, but being able to save the scenery _without_ any ride would really make it a lot more convenient and streamline the flow ... especially when placing repetitive scenery like sections of buildings or walls. It would enable you to save entire buildings to be placed again later, or chunks of buildings to build into different shapes later, all super-easily.

------------------

And to move on to the more selfish side of this request, if this feature is made, I'd *really* enjoy it if it could be used to copy/paste rides, too. ("Why ask for that?" you say -- "the 'save track design' feature already does that!") Well, you see, I'd love it if this tool could save _multiple_ rides in the same file, so I could create an assembly of rides and then easily create many copies of that same arrangement.

Why the hell would I want to do that? Well, you see, I've been experimenting with [logic gates in RCT](https://www.reddit.com/r/rct/comments/93h10y/an_introduction_to_peepbased_logic_gates_in_rct/), and it would be _really_ helpful if, for example, I could build a full adder, save the design, complete with multiple rides in it, and then plop down a bunch more of them, each exactly the same, with very little effort.

This _could_ also be useful in normal gameplay. For example, you might construct a pair of intertwined coasters and then want to save the whole assembly so you can easily rebuild it in other parks. This feature would be useful in cases like that. (Not to mention the scenery-building uses.)

----------------------

Failing that, here's another weird request: I'd like the ability to load a save game *into* a different ongoing scenario. This would be used in much the same way, constructing a very small map that contains the part I want to copy, then being able to repeatedly place that entire small map inside a larger map.

---------------------

If even that is impossible, could someone maybe just talk to me and help explain how save games are organized? I might create my own script to go in and copy/paste segments inside a saved game ... then I could open the save file and see the changes that have been made. Part of the save file has to just be a huge grid describing where everything in the park is, right? If I copied parts of that grid into other (empty) areas (and also made sure any rides were listed as new rides, not as copies of the same), that would probably work.

**Comment by Gymnasiast** [comment] 2018-08-03 17:11
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/1926.

**Closed by Gymnasiast** 2018-08-03 17:11 UTC
