### ISSUE TITLE
Game crashed when trying to add a pre made ride 

### ISSUE THREAD

**Issue by satdav** [OpenRCT2/OpenRCT2#3961] opened 2016-06-30 23:26 UTC
**OS:** Windows 10 64 bit EDU edition 
**Version:** 0.0.5
**Commit/Build:** 2e3500e 

I cant open the vanilla build as it was crashing and this was single player for the records 

**Steps to reproduce:**
1. [step 1] Open build 2e3500e  I opened started a new world and it crashed when I tried to add viper down what is a pre build ride
2. [step 2] I never had internet at the time but it seems to be working fine again now 

**Dump file**
Please see attached

[Crashed 26th June.zip](https://github.com/OpenRCT2/OpenRCT2/files/345344/Crashed.26th.June.zip)

Admin edit: Put the crash dump link in this post.

**Comment by janisozaur** [comment] 2016-07-01 06:05
Can you make sure the dump is uploaded properly?

**Comment by satdav** [comment] 2016-07-02 16:50
Here you go

[Uploading Openrct Crash Report 26th June 2016.zip…]()

**Comment by satdav** [comment] 2016-07-02 16:50
It seems it wont reconise the dump file but I dont know why well the zip file this time

**Comment by Patrik356b** [comment] 2016-07-02 19:26
You need to wait until it no longer says "uploading" for the upload to work. Try again with this in mind.

**Comment by satdav** [comment] 2016-07-03 22:46
[Crashed 26th June.zip](https://github.com/OpenRCT2/OpenRCT2/files/345344/Crashed.26th.June.zip)

**Comment by janisozaur** [comment] 2016-07-06 07:40
Possibly a duplicate of #3957

**Comment by Jayrod4** [comment] 2016-07-06 08:18
this same thing is happening to me. it happens every time I try to place any prebuilt coaster or anything like it. Im using the Demo tho so I dont know if that would have anything to do with it.

**Comment by Nubbie** [comment] 2016-07-06 14:59
@janisozaur - No idea if it's a dupe of the issue you referenced BUT, issue #3974 is a duplicate of this

----
- 
**To devs;** Got this from dump file provided from _70e1977a-6927-4e38-ac68-1122c3665011(2e3500e).dmp_ in '_Crashed.26thJune.rar_'
**Error message:**
Unhandled exception thrown: read access violation.
[peep was 0x1DE78BC.](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/windows/ride.c#L1111)

>	openrct2.dll!ride_remove_peeps(int rideIndex=64) Line 1111	C
 	openrct2.dll!ride_set_vehicles(unsigned char rideIndex='@', unsigned char setting, unsigned char value='\x17', unsigned int flags=513, unsigned char ex='\0') Line 7760	C
 	openrct2.dll!game_command_set_ride_vehicles(int * eax=0x000dfd70, int * ebx=0x000dfd6c, int * ecx=0x000dfd58, int * edx, int * esi=0x000dfd5c, int * edi=0x000dfd60, int * ebp=0x000dfd64) Line 7814	C
 	openrct2.dll!game_do_command_p(int command=9, int * eax=0x000dfd70, int * ebx=0x000dfd6c, int * ecx=0x000dfd58, int * edx=0x000dfd68, int * esi=0x000dfd5c, int * edi=0x000dfd60, int * ebp=0x000dfd64) Line 524	C
 	openrct2.dll!place_track_design(short x, short y, short z=160, unsigned char flags='i', unsigned char * outRideIndex=0x000dfd9c) Line 1464	C
 	openrct2.dll!game_command_place_track_design(int * eax, int * ebx=0x000dfe04, int * ecx, int * edx=0x000dfe00, int * esi=0x000dfdfc, int * edi=0x000dfe18, int * ebp=0x000dfdf8) Line 1647	C
 	openrct2.dll!game_do_command_p(int command=48, int * eax=0x000dfe08, int * ebx=0x000dfe04, int * ecx=0x000dfe10, int * edx=0x000dfe00, int * esi=0x000dfdfc, int * edi=0x000dfe18, int * ebp=0x000dfdf8) Line 524	C
 	openrct2.dll!window_track_place_attempt_placement(rct_track_td6 * x, int y, int z=160, int bl, int cost=0x000dfe3c, int * rideIndex=0x000dfe34, unsigned char *) Line 438	C
 	openrct2.dll!window_track_place_toolupdate(rct_window * w=0x6af58c38, int widgetIndex=6, int x=0, int y=287) Line 276	C
 	openrct2.dll!process_mouse_tool(int x=0, int y=287) Line 1170	C
 	openrct2.dll!game_handle_input(...) Line 166	C
 	openrct2.dll!game_update(...) Line 345	C
 	openrct2.dll!rct2_update(...) Line 462	C
 	openrct2.dll!openrct2_loop(...) Line 458	C
 	openrct2.dll!openrct2_launch(...) Line 328	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x016b304b, int nCmdShow=10) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]

**Comment by Androgeos** [comment] 2016-07-09 07:48
I encountered what appears to be an identical problem a few hours ago while playing the RCT2:TT scenario "Australasia - Ayers Rock". I was thinking of starting a new issue, but then I saw that this one is open.

**OS: Windows 10 (Build 10586.420)**
**Version: 0.0.5-develop**
**Commit/Build: f4ca587 (from https://openrct2.org/downloads)**

The game runs fine until May, Year 1, at which point I attempted to build an Inverted Impulse Coaster design on the spot where Ferris Wheel 1 was. At the point of the crash, a portion of the construction ghost also inexplicably disappeared shortly after I moved it away from the rock formation and was trying to line up the ride's entrance and exit with the existing pathways.

Unfortunately, I have no save files of this game before the crash itself, and I'm also not able to replicate the crash by re-playing the scenario in vanilla RCT2.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

Save file:
[213135ed-02d1-4517-b334-8f279ae69ac5.SV6.zip](https://github.com/OpenRCT2/OpenRCT2/files/355459/213135ed-02d1-4517-b334-8f279ae69ac5.SV6.zip)

Dump file:
[213135ed-02d1-4517-b334-8f279ae69ac5(f4ca587).dmp.zip](https://github.com/OpenRCT2/OpenRCT2/files/355460/213135ed-02d1-4517-b334-8f279ae69ac5.f4ca587.dmp.zip)

Here's the Inverted Impulse Coaster design I was trying to build at the time of the crash:
[Screaming Condor.zip](https://github.com/OpenRCT2/OpenRCT2/files/355468/Screaming.Condor.zip)

Screenshot (from loading the above save file in vanilla RCT2):
![213135ed-02d1-4517-b334-8f279ae69ac5](https://cloud.githubusercontent.com/assets/18898491/16706736/f108722c-45e9-11e6-97ec-922a7e1ebc25.png)

**Comment by Patrik356b** [comment] 2016-07-17 20:25
Same problem over here, without any custom content or cheats used.
I'm attempting to build a Mini Roller Coaster
Win8.1x64 - commit dd25cdc
![openrct2-invalid-vehicle](https://cloud.githubusercontent.com/assets/2000703/16902871/fbe80ee4-4c6c-11e6-959c-2c4f970a9130.png)

dump from a few seconds after the freezing: 
[Orct2-invalid-vehicle-crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/368109/Orct2-invalid-vehicle-crash.zip)

**Comment by Patrik356b** [comment] 2016-07-18 17:13
Mine Ride does not crash on commit 2e3500e but Mini Roller Coaster does, however, the result has changed:

When running in verbose mode i can fill Electric Fields to the brim with the same coaster, but it crashes very early on when running normally attempting to build this "Automania" Mini Roller Coaster.

[Orct2-3961-dmp.zip](https://github.com/OpenRCT2/OpenRCT2/files/369686/Orct2-3961-dmp.zip)

**Comment by duncanspumpkin** [comment] 2016-07-18 18:40
Retry with the latest commit this is probably fixed

**Comment by Patrik356b** [comment] 2016-07-18 18:53
@daihakken the launcher @LRFLEW made apparently fetched an older version than intended.

However, this is not completely solved. it doesn't crash, but the console still get spammed with "error invalid vehicle type"

**Comment by LRFLEW** [comment] 2016-07-18 22:02
> the launcher @LRFLEW made apparently fetched an older version than intended.

That's odd, but shouldn't be my fault. My launcher gets the version that openrct2.org advertises with its API. The openrct2.org site gets its builds from an automated system setup with this project's CI (Travis and AppVeyor). The problem with getting an old build can be from any point in that chain, but I doubt it's something in the launcher's code.

**Comment by Patrik356b** [comment] 2016-07-19 09:23
I don't know, but it got stuck on 2e3500e and did not get anything more recent.

**Comment by Patrik356b** [comment] 2016-07-19 20:08
Tested again but further on commit 0c180b8 with the following results:

**Error Invalid Vehicle Type: **
- AutoMania (Automobile Cars)
- Cairngorm Bobsleds (Toboggan Cars)
- Crazy Cabs (Automobile Cars)
- Dream Chariots (Toboggan Cars)

**No error:**
- Supersonic (Automobile Cars)
- Raving Rockets (Rocket Cars)

Custom designs not tested*

Each time you move the ghost 1 tile the message is shown which is wasting resources

Edit; And, OH. I found the culprit in the "vehicle options";
There is only "rocket cars" in the drop-down list here so that is very odd. but it does explains the warnings

**Comment by Patrik356b** [comment] 2016-07-21 20:23
Update: I got the same issue happening on crazy castle because picking a track with articulated trains but only the "wooden coaster trains" are in the drop-down list. Seems like it's not limited to a single scenario and might be the reason for #3953

**Comment by janisozaur** [comment] 2016-11-04 20:53
Duplicate of #3929

**Closed by janisozaur** 2016-11-04 20:53 UTC
Labels: crash, investigate
