### ISSUE TITLE
Text in banners in uppercase : miss accentued upercases

### ISSUE THREAD

**Issue by Xardoz** [OpenRCT2/OpenRCT2#6938] opened 2018-01-04 21:59 UTC
Win7 64bits
OpenRCT2-0.1.2-develop-3dd98c7-windows-x64
(I tried too with version 0.1.1, same issue)

Hi !
I talked about my issue here : https://openrct2.org/forums/topic/2788-text-in-banners-in-uppercase-miss-accentued-upercases/

When I select the option "Display text in banners in uppercase" (like in RCT1), the accented letters are left in lowercase :P
Which leads to not really aesthetic things like :

Manège -> MANèGE (instead of MANÈGE )
Fermé -> FERMé (instead of FERMÉ )
etc...

Hope something can be done for that :)
Edit : if I can help, don't hesitate to ask ! 

[By the way, there is an horrible typo in the french version for Hamburger : it misses the b letter a lot of time in the french file = Hamurger but I don't know where to tell that, should I create another issue thread ?]

**Comment by AaronVanGeffen** [comment] 2018-01-04 22:11
Thanks for your report! It's interesting to see this happening – again. We should test accented characters more often!

As for the 'hamurger' issue, please report that to the [Localisation](https://github.com/OpenRCT2/Localisation) repository. If you like, you can also edit and PR the change yourself, there.

**Comment by Xardoz** [comment] 2018-01-04 22:32
:) Thank you for your work ;)
Accented characters is often problematic in games/computers... that's really great that you pay as much attention as possible to them ! If I can help don't hesitate.

Okay, I'm going there to tell it. PR ? (yeah, newbie in github :P)

**Comment by AaronVanGeffen** [comment] 2018-01-04 22:39
> Accented characters is often problematic in games/computers... that's really great that you pay as much attention as possible to them !

The thing is, the `toupper` function we use to convert characters to their uppercase variant, has different behaviour depending on the locale set — the system language, if you will. Right now, we seem to set it to `UTF-8` for the whole program. That means that the program supports basically all characters (good!), but no uppercase transformations outside of basic Latin letters… 😅 

> Okay, I'm going there to tell it. PR ? (yeah, newbie in github :P)

PR is short for [Pull Request](https://help.github.com/articles/about-pull-requests/)

**Comment by Xardoz** [comment] 2018-01-04 22:48
> The thing is, the toupper function we use to convert characters to their uppercase variant, has different behaviour depending on the locale set — the system language, if you will. Right now, we seem to set it to UTF-8 for the whole program. That means that the program supports basically all characters (good!), but no uppercase transformations outside of basic Latin letters… :sweat_smile:
I was suspecting something like that :P Well, I hope you'll find a solution one day :)
Do I close the issue, or should I wait a bit ?

> PR is short for Pull Request
Oh, ok ! Thanks, I'll look at that as soon as possible :)

**Comment by AaronVanGeffen** [comment] 2018-01-04 22:53
Just leave the issue open. Best way to keep track of these things! Hopefully, we'll be able to fix it soon.

**Comment by Xardoz** [comment] 2018-01-04 22:55
Ok !

**Comment by Gymnasiast** [comment] 2018-01-05 13:03
I have fixed the 'hamurger' typo in Localisation. It will be merged early next morning. Not sure how that has gone unnoticed for so long.
If you find more issues, could you put them into a separate issue report here? Having an issue about two unrelated things is difficult to keep track of.

**Comment by Gymnasiast** [comment] 2018-01-05 13:11
Also, I have investigated this. It's caused by `toupper()` only converting ASCII.

**Comment by AaronVanGeffen** [comment] 2018-01-05 15:39
That's what I wrote 17 hours ago as well. :wink:

**Comment by Gymnasiast** [comment] 2018-01-05 16:18
Oops, overlooked that bit!

**Comment by Xardoz** [comment] 2018-01-05 21:34
> If you find more issues, could you put them into a separate issue report here? Having an issue about two unrelated things is difficult to keep track of.

Yeah sure don't worry, I wanted to do that yesterday after AaronVanGeffen helped me to know where to tell it, but I was really lacking time and was planing to do that today, but you were faster :) Thanks for fixing the Hamburger issue ;)

**Closed** 2018-05-23 08:08 UTC
Labels: bug
