### ISSUE TITLE
BACKTRACE 8032b4 ttf_draw_string_raw_ttf

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8228] opened 2018-11-05 11:51 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/8032b4c1dbf43887ec8694cad51c5c3b0e37426796b165dabd1d840708a69de3?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Mon Nov 05 2018 10:52:02)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 3aeb87b: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ttf_draw_string_raw_ttf -> ttf_process_string -> ttf_draw_string -> DrawText -> DrawTextCompat -> window_editor_bottom_toolbar_paint -> window_draw -> window_draw_all -> WindowManager::SetMainView -> Editor::FinaliseMainView -> Editor::ConvertSaveToScenarioCallback -> window_loadsave_select -> window_loadsave_scrollmousedown -> input_scroll_begin -> input_widget_left -> game_handle_input_mouse -> game_handle_input -> OpenRCT2::TitleScreen::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2018-11-11 20:41
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8227

**Closed by janisozaur** 2018-11-11 20:41 UTC
Labels: backtrace.io, crash
