### ISSUE TITLE
Update binary icon (Windows)

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#2821] opened 2016-01-27 01:07 UTC
Is it possible to update the binary icon to the actual OpenRCT2 logo? The original logo's resolution is way too low to make it look nice on the desktop etc.

**Comment by AaronVanGeffen** [comment] 2016-01-27 01:37
As the Linux and OS X build process uses certain hardcoded offsets to extract code from the original executable, this might not be a good idea at the moment.

Maybe a .ico file could be distributed for use with shortcuts instead? (If it isn't already.)

**Comment by pizza2004** [comment] 2016-01-27 01:45
I don't understand why you couldn't make the OpenRCT2.exe have the new icon, seeing as that binary isn't even necessary for the functioning of OpenRCT2 on OS X.  It's just the RCT2.exe binary that's necessary and we don't even supply that one.

**Comment by janisozaur** [comment] 2016-01-27 06:08
@pizza2004 you obviously don't understand the build process and spread misinformation and confusion over and over again. Please put at least minimal effort into verifying what you're about to write next time. Linux and osx builds use this binary.

**Comment by pizza2004** [comment] 2016-01-27 06:16
@janisozaur Okay, no, I'm not gonna let that one slide at all.  If you're referring to the openrct2.exe file included in the git repository that's probably used to /build/ the game, then sure, that's probably true, but I didn't say anything /at all/ about building the game.  Functioning to me means running the game, not building it.  I can understand something like saying that the default build process can't include the icon because it would cause an issue, but there is absolutely a way to include it in the binaries that people are actually downloading from websites, since those aren't being actively used for anything except Windows.

**Comment by IntelOrca** [comment] 2016-01-27 08:29
Duplicate of #1168

**Closed by IntelOrca** 2016-01-27 08:29 UTC
