### ISSUE TITLE
Can no longer build bins. Disappeared from scenery menu.

### ISSUE THREAD

**Issue by drdoob** [OpenRCT2/OpenRCT2#21800] opened 2024-04-14 21:41 UTC
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.10 (e55d761) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Two days ago I could build bins. Yesterday I load this save file and I can no longer build bins. I would like to build bins again.

### Steps to reproduce

I don't know how to reproduce this. When I loaded the save file yesterday there were just no longer bins in my scenery menu.

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/125337617/6695c87a-5b80-43ff-8244-2110241fb51b)

**Comment by MASHzj** [comment] 2024-04-14 21:56
Probably related to #21496.

**Comment by drdoob** [comment] 2024-04-14 22:09
also removed a variety of lamppost from the menu

**Comment by Gymnasiast** [comment] 2024-05-07 14:29
Closing this as a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/21496.

**Closed by Gymnasiast** 2024-05-07 14:29 UTC
Labels: bug, duplicate
