### ISSUE TITLE
Construction Window - Cant start building from any piece or its neighbour.

### ISSUE THREAD

**Issue by WackedSwe** [OpenRCT2/OpenRCT2#11856] opened 2020-06-01 13:29 UTC
**OS:** [e.g. Windows 7]
**Version:** e.g. 0.2.6
**Commit/Build:**  ga1be45d / a1be45d ]

- [ ] Reproducible in RCT2 (vanilla)? 
- [ ] Specific to multiplayer? 

**Steps to reproduce:**
1.  Pick any coaster
2.  Try to start with anything else than station or flat piece. 
3. The piece is not selectable.
4. You have to build the regular way to get to the slope/piece you want.
5. Icon shows which one I want to click and start with for example. 

**Screenshots / Video:**

![capture](https://user-images.githubusercontent.com/59372559/83413550-4d3b6880-a41c-11ea-8964-afc229ecc70c.jpg)

**Save game:**

**Comment by duncanspumpkin** [comment] 2020-06-01 19:02
Pretty sure this is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/11845 can you confirm it now work how you would expect.

**Comment by IntelOrca** [comment] 2020-06-01 19:09
@duncanspumpkin The OP wants them to be enabled though.

**Comment by duncanspumpkin** [comment] 2020-06-01 19:26
From comments on discord it sounded like he wants the old behaviour which is still there its just that the bug makes it look like it isn't there. You always had to select the forward arrow (deselect station) to start with an incline.

**Comment by IntelOrca** [comment] 2020-06-01 19:34
Ah yes, I thought that was what you had to do to accomplish it but wasn't certain enough to mention it.

**Closed** 2020-06-03 17:00 UTC
