### ISSUE TITLE
BACKTRACE 307926 move_sprite_to_list

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8271] opened 2018-11-17 19:49 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/3079266a2797a7a3007d1e3750bc0d179fdf238bdfc1d572386c9dc534b97e2b?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Nov 17 2018 19:49:07)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 57a6f06: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>move_sprite_to_list -> S4Importer::ImportSprites -> S4Importer::Import -> OpenRCT2::Context::LoadParkFromStream -> OpenRCT2::Context::LoadParkFromFile -> context_load_park_from_file -> game_load_or_quit_no_save_prompt_callback -> window_loadsave_select -> window_loadsave_scrollmousedown -> input_widget_left -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2018-11-17 19:53
```
dump_path: /var/coronerd//openrct2/openrct2/_objects/0000/tx.0138.dmp outfile: -
Classifier: invalid-read
Crash info:
	Application: openrct2.com
	Crashed YES
	reason: EXCEPTION_ACCESS_VIOLATION_READ
	address: 0x8
Memory Regions:
Sysinfo:
	arch: amd64 family 6 model 42 stepping 7
	cpu_count: 8
	os: Windows NT windows 10.0.17134 
Modules:
	0x7e1100000000 - 0x7e110006e000	ConEmuHk64.dll 18.6.26.0
	0x7ff6c1a80000 - 0x7ff6c1aac000	openrct2.com 
	0x7ffae03b0000 - 0x7ffae1492000	openrct2.dll 
	0x7ffaf7e00000 - 0x7ffaf8ebf000	nvd3dumx.dll 21.21.13.7761 (Warning no symbol, nvd3dumx.pdb B13C74FCF1DE409ABFC44F6FEE8EE7D31)
	0x7ffaf8ec0000 - 0x7ffaf9057000	d3d9.dll 6.2.17134.81
	0x7ffb0bff0000 - 0x7ffb0c45f000	wininet.dll 11.0.17134.345
	0x7ffb13840000 - 0x7ffb13926000	nvSCPAPI64.dll 7.17.13.7761
	0x7ffb163f0000 - 0x7ffb1670e000	CoreUIComponents.dll 6.2.17134.376
	0x7ffb16950000 - 0x7ffb169e6000	TextInputFramework.dll 6.2.17134.376
	0x7ffb184d0000 - 0x7ffb184e0000	ColorAdapterClient.dll 6.2.17134.1
	0x7ffb184f0000 - 0x7ffb18598000	mscms.dll 6.2.17134.1
	0x7ffb188b0000 - 0x7ffb188da000	WINMMBASE.dll 6.2.17134.1
	0x7ffb188e0000 - 0x7ffb18903000	winmm.dll 6.2.17134.1
	0x7ffb18ae0000 - 0x7ffb18b23000	icm32.dll 6.2.17134.1
	0x7ffb1a040000 - 0x7ffb1a2a9000	comctl32.dll 6.10.17134.407
	0x7ffb1ef20000 - 0x7ffb1ef29000	IconCodecService.dll 6.2.17134.1
	0x7ffb1f8b0000 - 0x7ffb1f926000	MMDevAPI.dll 6.2.17134.1
	0x7ffb1fc70000 - 0x7ffb1fd9c000	AudioSes.dll 6.2.17134.407
	0x7ffb1ff20000 - 0x7ffb1ff49000	dbgcore.dll 6.2.17134.1
	0x7ffb1ff70000 - 0x7ffb20139000	dbghelp.dll 6.2.17134.1
	0x7ffb20720000 - 0x7ffb2072a000	version.dll 6.2.17134.1
	0x7ffb22d00000 - 0x7ffb22d0a000	avrt.dll 6.2.17134.1
	0x7ffb23dd0000 - 0x7ffb23ddc000	secur32.dll 6.2.17134.1
	0x7ffb245a0000 - 0x7ffb2467a000	CoreMessaging.dll 6.2.17134.407
	0x7ffb246c0000 - 0x7ffb2480d000	WinTypes.dll 6.2.17134.407
	0x7ffb25260000 - 0x7ffb25414000	propsys.dll 7.0.17134.112
	0x7ffb25600000 - 0x7ffb257ae000	WindowsCodecs.dll 6.2.17134.345
	0x7ffb25890000 - 0x7ffb25928000	uxtheme.dll 6.2.17134.1
	0x7ffb25ae0000 - 0x7ffb25b09000	dwmapi.dll 6.2.17134.1
	0x7ffb26550000 - 0x7ffb26581000	ntmarta.dll 6.2.17134.1
	0x7ffb267b0000 - 0x7ffb267e3000	rsaenh.dll 6.2.17134.254
	0x7ffb26bd0000 - 0x7ffb26c36000	mswsock.dll 6.2.17134.1
	0x7ffb26d80000 - 0x7ffb26d8b000	CRYPTBASE.dll 6.2.17134.1
	0x7ffb26d90000 - 0x7ffb26da7000	cryptsp.dll 6.2.17134.1
	0x7ffb26eb0000 - 0x7ffb26ed5000	bcrypt.dll 6.2.17134.112
	0x7ffb27160000 - 0x7ffb27187000	devobj.dll 6.2.17134.1
	0x7ffb27250000 - 0x7ffb27280000	sspicli.dll 6.2.17134.376
	0x7ffb27280000 - 0x7ffb272a8000	userenv.dll 6.2.17134.1
	0x7ffb27350000 - 0x7ffb2735a000	fltLib.dll 6.2.17134.1
	0x7ffb27360000 - 0x7ffb27372000	msasn1.dll 6.2.17134.1
	0x7ffb27380000 - 0x7ffb273cc000	powrprof.dll 6.2.17134.1
	0x7ffb273d0000 - 0x7ffb273e1000	kernel.appcore.dll 6.2.17134.112
	0x7ffb273f0000 - 0x7ffb2740f000	profapi.dll 6.2.17134.1
	0x7ffb27410000 - 0x7ffb27430000	win32u.dll 6.2.17134.1
	0x7ffb27430000 - 0x7ffb274aa000	bcryptPrimitives.dll 6.2.17134.1
	0x7ffb274b0000 - 0x7ffb27692000	crypt32.dll 6.2.17134.1
	0x7ffb27700000 - 0x7ffb277fa000	ucrtbase.dll 6.2.17134.319
	0x7ffb27800000 - 0x7ffb27992000	gdi32full.dll 6.2.17134.345
	0x7ffb279a0000 - 0x7ffb27c13000	KERNELBASE.dll 6.2.17134.407
	0x7ffb27c20000 - 0x7ffb27cbf000	msvcp_win.dll 6.2.17134.137
	0x7ffb27cc0000 - 0x7ffb27d09000	cfgmgr32.dll 6.2.17134.1
	0x7ffb27d10000 - 0x7ffb2841d000	windows.storage.dll 6.2.17134.407
	0x7ffb28670000 - 0x7ffb2875d000	comdlg32.dll 6.2.17134.1
	0x7ffb28760000 - 0x7ffb287bb000	sechost.dll 6.2.17134.319
	0x7ffb28820000 - 0x7ffb28993000	msctf.dll 6.2.17134.376
	0x7ffb289a0000 - 0x7ffb289a8000	psapi.dll 6.2.17134.1
	0x7ffb28a10000 - 0x7ffb29e4f000	shell32.dll 6.2.17134.376
	0x7ffb29e50000 - 0x7ffb29f02000	kernel32.dll 6.2.17134.1
	0x7ffb29fb0000 - 0x7ffb2a101000	ole32.dll 6.2.17134.407
	0x7ffb2a110000 - 0x7ffb2a55b000	setupapi.dll 6.2.17134.1
	0x7ffb2a560000 - 0x7ffb2a600000	clbcatq.dll 2001.12.10941.16384
	0x7ffb2a600000 - 0x7ffb2a66c000	ws2_32.dll 6.2.17134.1
	0x7ffb2a670000 - 0x7ffb2a711000	advapi32.dll 6.2.17134.319
	0x7ffb2a720000 - 0x7ffb2a748000	gdi32.dll 6.2.17134.285
	0x7ffb2a760000 - 0x7ffb2a7b1000	shlwapi.dll 6.2.17134.1
	0x7ffb2a7c0000 - 0x7ffb2a85e000	msvcrt.dll 7.0.17134.1
	0x7ffb2a870000 - 0x7ffb2a994000	rpcrt4.dll 6.2.17134.407
	0x7ffb2a9a0000 - 0x7ffb2aa62000	oleaut32.dll 6.2.17134.48
	0x7ffb2aa70000 - 0x7ffb2aa9d000	imm32.dll 6.2.17134.1
	0x7ffb2aaa0000 - 0x7ffb2adc2000	combase.dll 6.2.17134.407
	0x7ffb2add0000 - 0x7ffb2ae79000	SHCore.dll 6.2.17134.112
	0x7ffb2ae80000 - 0x7ffb2b010000	user32.dll 6.2.17134.376
	0x7ffb2b040000 - 0x7ffb2b221000	ntdll.dll 6.2.17134.376
Threads:
	thread-0 tid=10488 faulted
	[0] D:\Games\OpenRCT2\bin\openrct2.dll!move_sprite_to_list(rct_sprite *,unsigned char) [c:\projects\openrct2-ject9\src\openrct2\world\sprite.cpp : 384 + 0]
		sp=0xe18ad4f0d0 bp=0x25b8591487c 
	[1] D:\Games\OpenRCT2\bin\openrct2.dll!S4Importer::ImportSprites() [c:\projects\openrct2-ject9\src\openrct2\rct1\s4importer.cpp : 1123 + 0x3d]
	[2] D:\Games\OpenRCT2\bin\openrct2.dll!S4Importer::Import() [c:\projects\openrct2-ject9\src\openrct2\rct1\s4importer.cpp : 187 + 0x8]
	[3] D:\Games\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::LoadParkFromStream(IStream *,std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,bool) [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 515 + 0x9]
	[4] D:\Games\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::LoadParkFromFile(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,bool) [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 482 + 0x14]
	[5] D:\Games\OpenRCT2\bin\openrct2.dll!context_load_park_from_file(char const *) [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 1061 + 0x51]
	[6] D:\Games\OpenRCT2\bin\openrct2.dll!game_load_or_quit_no_save_prompt_callback(int,char const *) [c:\projects\openrct2-ject9\src\openrct2\game.cpp : 1365 + 0x8]
	[7] D:\Games\OpenRCT2\bin\openrct2.dll!window_loadsave_select(rct_window *,char const *) [c:\projects\openrct2-ject9\src\openrct2-ui\windows\loadsave.cpp : 995 + 0x18]
	[8] D:\Games\OpenRCT2\bin\openrct2.dll!window_loadsave_scrollmousedown(rct_window *,int,int,int) [c:\projects\openrct2-ject9\src\openrct2-ui\windows\loadsave.cpp : 566 + 0xf]
	[9] D:\Games\OpenRCT2\bin\openrct2.dll!input_widget_left(int,int,rct_window *,short) [c:\projects\openrct2-ject9\src\openrct2-ui\input\mouseinput.cpp : 1067 + 0x11]
	[10] D:\Games\OpenRCT2\bin\openrct2.dll!game_handle_input_mouse(int,int,int) [c:\projects\openrct2-ject9\src\openrct2-ui\input\mouseinput.cpp : 303 + 0x11]
	[11] D:\Games\OpenRCT2\bin\openrct2.dll!game_handle_input() [c:\projects\openrct2-ject9\src\openrct2-ui\input\mouseinput.cpp : 118 + 0xd]
	[12] D:\Games\OpenRCT2\bin\openrct2.dll!context_handle_input() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 1234 + 0x9]
	[13] D:\Games\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::Update() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 932 + 0xc]
	[14] D:\Games\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunVariableFrame() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 891 + 0x8]
	[15] D:\Games\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunGameLoop() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 801 + 0x56]
	[16] D:\Games\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int,char const * *) [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 213 + 0x8]
	[17] D:\Games\OpenRCT2\bin\openrct2.dll!NormalisedMain(int,char const * *) [c:\projects\openrct2-ject9\src\openrct2-ui\ui.cpp : 60 + 0x13]
	[18] D:\Games\OpenRCT2\bin\openrct2.dll!LaunchOpenRCT2(int,wchar_t * *) [c:\projects\openrct2-ject9\src\openrct2-dll\openrct2-dll.cpp : 46 + 0xf]
	[19] D:\Games\OpenRCT2\bin\openrct2.com!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl : 288 + 0x22]
	[20] C:\Windows\System32\kernel32.dll!BaseThreadInitThunk + 0x14
	[21] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x21
	thread-1 tid=8956 
	[0] C:\Windows\System32\ntdll.dll!NtWaitForWorkViaWorkerFactory + 0x14
		sp=0xe18b0ff5f8 bp=0 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x536
	[2] C:\Windows\System32\kernel32.dll!BaseThreadInitThunk + 0x14
	[3] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x21
	thread-2 tid=8172 
	[0] C:\Windows\System32\ntdll.dll!NtWaitForWorkViaWorkerFactory + 0x14
		sp=0xe18b1ff768 bp=0 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x536
	[2] C:\Windows\System32\kernel32.dll!BaseThreadInitThunk + 0x14
	[3] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x21
	thread-3 tid=6396 
	[0] C:\Windows\System32\ntdll.dll!NtWaitForWorkViaWorkerFactory + 0x14
		sp=0xe18b2ff6d8 bp=0 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x536
	[2] C:\Windows\System32\kernel32.dll!BaseThreadInitThunk + 0x14
	[3] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x21
	thread-4 tid=7116 
	[0] C:\Windows\System32\ntdll.dll!NtWaitForWorkViaWorkerFactory + 0x14
		sp=0xe18b3ff618 bp=0 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x536
	[2] C:\Windows\System32\kernel32.dll!BaseThreadInitThunk + 0x14
	[3] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x21
	thread-5 tid=9648 
	[0] C:\Windows\System32\ntdll.dll!NtWaitForWorkViaWorkerFactory + 0x14
		sp=0xe18b4ff7d8 bp=0 
	[1] C:\Windows\System32\ntdll.dll!TppWorkerThread + 0x536
	[2] C:\Windows\System32\kernel32.dll!BaseThreadInitThunk + 0x14
	[3] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x21
	thread-6 tid=2448 
	[0] C:\Windows\System32\ntdll.dll!NtGetContextThread + 0x14
		bp=0xffffffffffffffff 
	[1] 0xc0000017
	[2] C:\Windows\System32\ntdll.dll!RtlpMuiRegCreateLanguageConfigList + 0x36
	thread-7 tid=11956 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForAlertByThreadId + 0x14
	[1] C:\Windows\System32\ntdll.dll!RtlSleepConditionVariableSRW + 0x109
	[2] C:\Windows\System32\KERNELBASE.dll!SleepConditionVariableSRW + 0x32
	[3] D:\Games\OpenRCT2\bin\openrct2.dll!__crtSleepConditionVariableSRW(_RTL_CONDITION_VARIABLE *,_RTL_SRWLOCK *,unsigned long,unsigned long) [f:\dd\vctools\crt\crtw32\misc\winapisupp.cpp : 657 + 0x6]
	[4] D:\Games\OpenRCT2\bin\openrct2.dll!Concurrency::details::stl_condition_variable_win7::wait_for(Concurrency::details::stl_critical_section_interface *,unsigned int) [f:\dd\vctools\crt\crtw32\stdcpp\thr\primitives.h : 216 + 0x10]
	[5] D:\Games\OpenRCT2\bin\openrct2.dll!do_wait(_Cnd_internal_imp_t *,_Mtx_internal_imp_t *,xtime const *) [f:\dd\vctools\crt\crtw32\stdcpp\thr\cond.c : 82 + 0x26]
	[6] D:\Games\OpenRCT2\bin\openrct2.dll!std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_f574185c45dda01958beedcd6f2ea127> >,std::default_delete<std::tuple<<lambda_f574185c45dda01958beedcd6f2ea127> > > > >::_Go() [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\thr\xthread : 230 + 0xf8]
	[7] D:\Games\OpenRCT2\bin\openrct2.dll!std::_Pad::_Call_func(void *) [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\thr\xthread : 208 + 0x5]
	[8] D:\Games\OpenRCT2\bin\openrct2.dll!thread_start<unsigned int (*)(void *)>(void * const) [d:\rs1\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 115 + 0xd]
	[9] C:\Windows\System32\kernel32.dll!BaseThreadInitThunk + 0x14
	[10] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x21
	thread-8 tid=10444 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForSingleObject + 0x14
	[1] C:\Windows\System32\KERNELBASE.dll!WaitForSingleObjectEx + 0xa2
	[2] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0x7d9439
	[3] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0x7d6628
	thread-9 tid=5632 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForSingleObject + 0x14
	[1] C:\Windows\System32\KERNELBASE.dll!WaitForSingleObjectEx + 0xa2
	[2] D:\Games\OpenRCT2\bin\openrct2.dll!WASAPI_WaitDevice(SDL_AudioDevice *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\audio\wasapi\sdl_wasapi.c : 331 + 0xe]
	[3] D:\Games\OpenRCT2\bin\openrct2.dll!SDL_RunAudio(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\audio\sdl_audio.c : 711 + 0x9]
	[4] D:\Games\OpenRCT2\bin\openrct2.dll!SDL_RunThread(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\thread\sdl_thread.c : 283 + 0x5]
	[5] D:\Games\OpenRCT2\bin\openrct2.dll!RunThreadViaBeginThreadEx(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\thread\windows\sdl_systhread.c : 105 + 0x14]
	[6] D:\Games\OpenRCT2\bin\openrct2.dll!thread_start<unsigned int (*)(void *)>(void * const) [d:\rs1\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 115 + 0xd]
	[7] C:\Windows\System32\kernel32.dll!BaseThreadInitThunk + 0x14
	[8] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x21
	thread-10 tid=12092 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForMultipleObjects + 0x14
	[1] C:\Windows\System32\KERNELBASE.dll!WaitForMultipleObjectsEx + 0xf9
	[2] C:\Windows\System32\KERNELBASE.dll!WaitForMultipleObjects + 0xe
	[3] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0x932995
	[4] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0xfabe00
	[5] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0x7f3b9d
	[6] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0xaa1023
	[7] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0xaa126e
	[8] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0xfab7f0
	[9] C:\Windows\System32\kernel32.dll!BaseThreadInitThunk + 0x14
	[10] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x21
	thread-11 tid=9452 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForSingleObject + 0x14
	[1] C:\Windows\System32\KERNELBASE.dll!WaitForSingleObjectEx + 0xa2
	[2] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0x81a722
	[3] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0x81a61f
	[4] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0xaa1023
	[5] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0xfabe00
	[6] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0xaa126e
	[7] C:\Windows\System32\DriverStore\FileRepository\nvltwi.inf_amd64_db988d0f9493c7a8\nvd3dumx.dll + 0xfab7f0
	[8] C:\Windows\System32\kernel32.dll!BaseThreadInitThunk + 0x14
	[9] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x21
```
https://github.com/OpenRCT2/OpenRCT2/blob/57a6f06891534c6c8b8d886e8dfbabfd3c8f096d/src/openrct2/world/Sprite.cpp#L384

**Comment by janisozaur** [comment] 2019-02-02 22:33
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8285, I will @Gymnasiast close

**Closed** 2020-03-27 23:07 UTC
Labels: backtrace.io, crash, expired
