### ISSUE TITLE
New Crash

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3433] opened 2016-04-26 22:41 UTC
**OS:** Win 7 64 Bit
**Version:** 0.0.5 develop
**Build ID:** 45843ec

Was in a multiplayer server today when it suddenly crashes out of nowhere.

[Crash April 26.zip](https://github.com/OpenRCT2/OpenRCT2/files/237638/Crash.April.26.zip)

**Comment by janisozaur** [comment] 2016-06-03 11:01
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3193

**Closed by janisozaur** 2016-06-03 11:01 UTC
Labels: crash, investigate
