### ISSUE TITLE
Text on banners and entrance buildings glitches

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#9631] opened 2019-07-23 11:55 UTC
**OS:** Windows 10
**Version:** 0.2.3
**Commit/Build:** ab5f5b2

The text on banners, the park entrance, and entrance buildings sometimes randomly glitches like it does in the video I linked below. There seems to be no pattern to when this happens and sometimes it will stop for a few seconds and then start again.

**Screenshots / Video:**
https://www.youtube.com/watch?v=es0C28Z_vcQ

**Comment by ZehMatt** [comment] 2019-07-23 16:11
Are you using the multithreading option?

**Comment by LordMarcel** [comment] 2019-07-23 16:27
Yes, although disabling it doesn't fix it, it rather just reduces the
frequency at which it glitches (from about 10 times per second to 2 or so).

**Comment by Broxzier** [comment] 2019-07-23 17:46
Possibly a regression from #9589? I cannot reproduce this on my PC. Could you try it with a build from before that PR was merged @LordMarcel?

**Comment by LordMarcel** [comment] 2019-07-23 17:57
I tried a build from a while ago (0.2.2 ba040fc). I'm not sure how old it is but definitely older than 7 days. It's still there in the exact same way.

**Comment by Gymnasiast** [comment] 2019-07-23 19:46
Which rendering engine are you on? OpenGL or one of the software renderers?

**Comment by LordMarcel** [comment] 2019-07-24 20:49
I use the software renderer, but when I switch to software (hardware display) and OpenGL the glitching stays.

**Closed** 2021-01-03 22:02 UTC
Labels: investigate
