### ISSUE TITLE
android touch controls

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [OpenRCT2/OpenRCT2#10723] opened 2020-02-17 01:07 UTC
Are specific controls to make it easier to play on touchscreens planned?

Currently the android version is very hard to play. I had to increase the scaler to 3.5 in order to make the gui very very big just to be able to close a window with X.

As a result the park area is very small so you neeed to zoom in and out all the time.

**Comment by duncanspumpkin** [comment] 2020-02-17 12:47
Duplicate of #6140

**Closed by duncanspumpkin** 2020-02-17 12:47 UTC
