### ISSUE TITLE
3 Issues I've Noticed

### ISSUE THREAD

**Issue by fish-with-feathers** [OpenRCT2/OpenRCT2#16941] opened 2022-04-06 21:52 UTC
### Operating System

Windows 10, 84 Bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

### Describe the issue

I have run across three issues, which I am not sure are present in the base RCT2.

These include:

1.  Alt-Tab out of OpenRCT2 causes me to just get a black screen when I try to Alt-Tab back into the game. I can still hear sounds of the fame running, but can't see/do anything, forcing me to have to force close down the game and restart.

2. In the Track Designer I noticed that Go-Karts are not included, despite being a tracked ride.

3. The "Save Track with Scenery" open on a ride doesn't work. I saves the ride, but not the scenery that was selected to be saved with it. 

### Steps to reproduce

1. 
2. 
3.

**Comment by spacek531** [comment] 2022-04-07 01:40
2. Not a bug. Rides without test mode are not available in the track designer.

3. What ride are you trying to save and what scenery?

**Comment by Broxzier** [comment] 2022-04-07 07:54
1. Sounds like a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/6767.

I'm closing this one. Please file just one issue at a time, and check if it has already been reported by someone else, then provide additional information if you can.

**Closed by Broxzier** 2022-04-07 07:54 UTC
Labels: bug

**Comment by Broxzier** [comment] 2022-04-07 11:55
@fish-with-feathers Could you please head over to https://github.com/OpenRCT2/OpenRCT2/pull/16070 and test if that fixes the Alt+Tab problem for you?

**Comment by fish-with-feathers** [comment] 2022-04-07 22:49
> It is preferred to file each of these as separate bug reports, that way if multiple items require fixing, it is easy to keep the references straight.
> 
> 3. What ride are you trying to save and what scenery?

Sorry about that, I am completely new to reporting bugs. I will keep it in mind to check threads before reporting and keep reports singular from now on.
