### ISSUE TITLE
(Stall) construct window should remember orientation

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#3954] opened 2016-06-26 09:03 UTC
Like title says, version 89db25e (not sure if older versions do this, i think vanilla does but haven´t tested it)

Since the construct window is probably not different for different types of rides, the current orientation should be stored somewhere so you can keep building stuff facing the same way without having to rotate the items all the time

**Comment by Gymnasiast** [comment] 2016-06-27 07:52
I'd prefer autorotate, but I don't have a very strong opinion about this.

**Comment by PFCKrutonium** [comment] 2016-06-27 08:32
This is actually a duplicate of a request I made absolutely ages ago.

**Comment by IntelOrca** [comment] 2016-06-27 11:02
Not quite, this is saying that the current rotation for a shop to be persisted. I am surprised its not at the moment, but its probably a quick fix.

**Closed** 2018-12-16 15:03 UTC
Labels: discussion, feature

**Comment by Patrik356b** [comment] 2018-12-17 05:49
> 
> 
> Auto rotate have been added with #1675
> So this is no longer needed.

I disagree assuming one places stalls first, then add a path.
