### ISSUE TITLE
handy man is stuck in a queue

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#7451] opened 2018-04-27 04:04 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.2]
**Commit/Build:** 2ef549b

A handyman has entered a queue next to a piece of litter and won't come out:
https://gfycat.com/AnchoredSandyArmyant

I left the game running for a few minutes and he had left, but he was in there for a good while.

Here is the .sv6 file with him still in the queue:
[handyman stuck.zip](https://github.com/OpenRCT2/OpenRCT2/files/1953790/handyman.stuck.zip)

**Comment by jensj12** [comment] 2018-04-27 12:48
Duplicate of #3205.

**Closed** 2018-04-27 12:49 UTC
