### ISSUE TITLE
General improvements for setting patrol area

### ISSUE THREAD

**Issue by andoruB** [OpenRCT2/OpenRCT2#5283] opened 2017-03-07 22:31 UTC
This isn't a bug report so much it is a feature request. Could the path setting be improved in the future? This is the one thing I dreaded having to do in the original game (RCT1 or 2, I think you guys call this "vanilla"?), for the fact that I would have to micro-manage the staff, just so they wouldn't wonder off into areas where they aren't needed (like a mechanic going to places where there aren't any rides, or handymen going where there aren't that many peeps).
I was thinking perhaps the areas could be selected by dragging along (like selecting multiple files in a file manager), instead of clicking every desired area -- which was already suggested in #2940. 

Or to have an automated mode, where every member of staff is assigned a certain area, based off the coverage (total land owned, which rides tend to get broken more often, which paths get littered more often, etc.), and how many staff are employed.

Another idea would be to be able to choose to set smaller/bigger areas, instead of just 4x4 tiles (2x2, 3x3, 1x1, 8x8, etc.) -- which was sort of suggested in #681
Not sure if this is doable, but I would really love to have such (a) feature(s).

**Comment by janisozaur** [comment] 2017-03-07 22:46
nothing we can do until we move away from sv6

**Comment by pizza2004** [comment] 2017-03-08 08:57
I think the only new idea you're suggesting is one where the AI of the game allows all the staff to just work out how to divvy up the land and that work, and to me that feels like it flies in the face of some of the core gameplay.

I know I didn't just sort of suggest being able to select smaller areas for patrol, that was in fact the entire point of my issue.

It sounds like you just don't care to micromanage everything in the game, but I kind of think the point of the game is to micromanage, and that anybody who just wants to build for the sake of building or the like will be able to do sandbox mode.

I'd say this issue is more or less a duplicate, but let's see what others say.

**Comment by andoruB** [comment] 2017-03-08 10:06
> and that anybody who just wants to build for the sake of building or the like will be able to do sandbox mode.

No, it's not the same thing. I still enjoy improving things, and checking up on things if they work as intended. What I specifically don't like is micromanaging staff, and even when doing so, they still screw things up, like in the example I gave above with them going to areas where they aren't needed and dwelling there for longer than they should, afterwards getting various complaints from guests for disgusting paths, broken rides, etc.

This could be solved by our suggestion to allow more specific patrol areas (of varying sizes in my case), but I still don't think it would hurt if there would be an option to allow the AI to set the patrol areas on the fly. This way you could leave it disabled if you want to disable it, and I could leave it enabled, so I could handle other things that seem more important to me. 

There are already many path scenery items getting vandalized (a lot more often than in vanilla from what I noticed, I should probably make a new issue with that), rides breaking down, and guests complaining about getting lost, or not finding shops/toilets, and adding to that the requirement to micro manage every member of staff makes it a bit too much for me.

**Comment by pizza2004** [comment] 2017-03-08 17:09
Most of your complaints come down to the need for a new Peep AI which will come eventually, and doesn't have to do with the staff specifically or even with the patrol areas.

Again, (of varying sizes in my case) the words "Being able to set more specific areas" and, reading all the comments, the entire point of my issue was that I wanted to be able to set the patrol area on a square by square basis.  Suggesting the different sizes is just repeating what I was asking for.

It's been said many times on many different issues related to the Staff AI that part of the issue is just a need to refactor everything, and that part of doing that is a new save format.  More than that though, the AI has various issues that require a new AI to be built from scratch, at least based on what I've read so far.  Once this stuff is fixed, the staff will be better at handling things in general, and I believe that if you give them a patrol area they'll manage it better, and so your desire for everything to be managed automatically flies in the face of the idea of the game in general that you're /supposed/ to manage this stuff yourself.

For now we just have to deal with the staff being kind of poor, and if you do notice any issues and regressions in the way they behave vs vanilla, report them, but please search to make sure nobody else has before, because there are issues for this stuff all the time.  Off the top of my head I know it's been reported that there's more vandalism than in vanilla, that Mechanics try to fix stuff outside their patrol area (this wasn't an issue in vanilla, as they were allowed to leave the patrol area to fix a ride, but one of the changes to the AI so far has been to disallow that), and that handymen are somewhat poor at finding mess and cleaning it.  All things I've seen you bring up in the recent past.

**Comment by ocalhoun6** [comment] 2017-03-21 13:31
If I could put in my own two cents, it would be a really nice update to the staff AI to simply be able to keep them off of queue lines.

Of course entertainers would have to be exempt from that, and maybe even handymen because there's occasionally a puke in a queue line that needs to be cleaned. But at the very least, mechanics and guards have no reason to ever go into a queue line. As for handymen, maybe they could be updated so that when offered the choice to enter a queue, they only have a 10% chance of accepting?

**Comment by ViktorFriberg** [comment] 2018-09-02 22:32
Since i wanted this to work better myself and did not find anyone else doing any work on this i made some improvements in my fork/branch. Figured it could be useful to post here incase anyone want to try it out. 

* I added option support for 1x1 tiling the patrol area, however my solution does not support saving the new 1x1 selected areas.
* I also added support for mouse-dragging the patrol area selection.
https://github.com/ViktorFriberg/OpenRCT2/tree/tilespecific-patrolling

I might clean it up more and make a pull request later if people think this is good.

**Comment by Patrik356b** [comment] 2018-09-03 16:35
Can't the que TV object be vandalized?

**Comment by AaronVanGeffen** [comment] 2018-09-03 16:48
@ViktorFriberg Sounds like you had fun changing the code. Unfortunately, until we have a new save format in which such patrol areas can actually be changed, I don't think we can merge it yet… Players would be upset if they lost their patrol areas without notice.

**Comment by IntelOrca** [comment] 2018-09-03 19:09
@ViktorFriberg Just tried your fork out and it works well. My only suggestions are that you try to refrain from putting direct staff logic in `game_handle_input_mouse`. We might also want a more space efficient way of storing the patrol areas if we are considering 1024x1024 maps with up to 1024 staff.

This can be go in when we move to new save format.

**Comment by ViktorFriberg** [comment] 2018-09-03 20:58
@IntelOrca Thanks for the feedback :) Yes i pretty much hastily added that function and couldnt figure out how to do it otherwise. Now i have explored enough of the codebase to know and made a pull request with some better code for the mouse-painting.

Regarding the 1x1 patrol areas i was thinking some kind of x,y offset to avoid storing bit for every part of map, also maybe can be different modes for each staff member to make it efficient if someone wants to paint a 1x1024 area it can still be done, but storing in a different way which can be determined when reading the format and looking up the "meta data"(stored in the redundant 4x staffgroup area bits). Will see, maybe i am overcomplicating it and should just wait for new save format(is there any work being done on this? where can i see progress or is it still just brainstorming stage?)

**Comment by IntelOrca** [comment] 2018-09-03 22:42
@ViktorFriberg The only problem with a list of offsets is that it will kill the performance of checking if a tile is enabled for patrol or not which is currently an O(1) operation.

I will be working on new save format soon, this is all we have so far:
https://raw.githubusercontent.com/IntelOrca/OpenRCT2/new-save-format/docs/save-format.md

**Comment by ViktorFriberg** [comment] 2018-09-03 23:14
@IntelOrca I was thinking more in terms of, specifying that a staffs areadata starts at coordinate 32,127 and then the bits in the array are for coordinates 32,127->96,191. It would then still be a O(1) operation. 

Another example is it could just be the compressed format which is used for saving and then it gets expanded when savefile is loaded.

The biggest performance hit would be making the toggle and set(if going from a 0->1) potentially a lot more expensive(certain usecases will have to move the 128 bytes bitarray for the staff), but this can only happen maximum 5~ times a second, think we can afford it :)

This all puts some limits into the staff patrol area selection though, there would have to be a point where you get a "can not assign this tile to area patrol because the area is too big" warning :)

**Comment by ZehMatt** [comment] 2023-11-26 23:17
I think this is solved with the new save format.

**Closed by ZehMatt** 2023-11-26 23:17 UTC
Labels: requires new save format
