### ISSUE TITLE
Boats get stuck

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2956] opened 2016-02-16 10:50 UTC
If there are multiple boats near the exist they get stuck and it takes very long before they are entering the harbor. This seems to happen with all boats and this does not happen in vanilla.

![scr14](https://cloud.githubusercontent.com/assets/7643972/13074069/932d2818-d4a2-11e5-9683-e2b6a9e3e9ef.png)

If you load the save in vanilla you'll see all boats entering as soon as possible, whereas the boats remain stuck in OpenRCT2.
[Rainbow Summit.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/132279/Rainbow.Summit.sv6.txt)

Also interesting, as you can see in the screenshot, the jet ski's are all in one place and they hardly ever leave. This also does not happen in vanilla as they are actually going to the exit instead of sticking together.

**Comment by Phyxion** [comment] 2016-02-16 11:02
[Rainbow Summit.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/132306/Rainbow.Summit.sv6.txt)

Addtional save to highlight the Jet Ski problem. Once you load this in vanilla they all start going to the exit. If you load this in OpenRCT2 they remain there forever.

**Comment by Gymnasiast** [comment] 2016-02-16 11:16
Duplicate of #866.

**Closed by Gymnasiast** 2016-02-16 11:16 UTC

**Comment by Phyxion** [comment] 2016-02-16 11:18
That says it's an original bug, this isn't as it's not present in vanilla.

**Comment by Gymnasiast** [comment] 2016-02-16 11:28
It is. I have encountered it multiple times.

**Comment by Phyxion** [comment] 2016-02-16 11:30
If you load the save game above you'll see that both issues are not present (at least not noticeable to this extent) in vanilla but are in OpenRCT2.

**Comment by duncanspumpkin** [comment] 2016-02-16 12:14
This happens all the time in vanilla. I find it unlikely that they would group up more but there is a chance there is a mistake in the code.

**Comment by Phyxion** [comment] 2016-02-16 12:18
I did some more checking and it indeed also happens in vanilla but it happens far more often in OpenRCT2 and the time it takes for the boats to get unstuck is a **LOT** longer.

Also, jet ski's always manage to find the exit in vanilla. They do not find the exit in OpenRCT2, they remain all together in one area.

**Comment by duncanspumpkin** [comment] 2016-02-16 18:56
![jetskis](https://cloud.githubusercontent.com/assets/1277401/13087257/e040ab8e-d4de-11e5-920a-82e6176d3501.PNG)
Yup definitly original rubbish pathfinding bug. This is after a good few minutes in vanilla.

**Comment by Phyxion** [comment] 2016-02-16 19:06
But at the top left you'll notice a jet ski, this does not happen in OpenRCT2 as they never get around the wall. I've watched it for a full year in-game time and not once did one get to the exit. In vanilla they also stack behind the wall but eventually do make their way to the exit (takes a few days). I agree that path finding is rubbish but the path finding in OpenRCT2 is worse. 

Regardless, let's keep this closed and continue in the other issue if needed :+1:
