### ISSUE TITLE
RCT1 scenario research status not saved

### ISSUE THREAD

**Issue by flipflop97** [OpenRCT2/OpenRCT2#6562] opened 2017-10-25 17:39 UTC
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** c9c0c07ec

I have installed the original RCT1 scenarios from Steam. While loading my save from last time I noticed the Go Karts not yet available while I had previously built one. So the research status doesn't seem to save.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load an original RCT1 scenario.
2. Wait until an attraction is researched (and optionally build it).
3. Save then load the game, the researched attraction is now gone from the build menu.

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/13943260/32013648-088cd252-b9bc-11e7-8f90-a2c318d59113.png)

**Save game:**
[Dynamite Dunes.zip](https://github.com/OpenRCT2/OpenRCT2/files/1415584/Dynamite.Dunes.zip)

**Comment by Gymnasiast** [comment] 2017-12-31 21:49
I cannot reproduce this. What I tried:
- Load Dynamite Dunes.
- Wait until Junior RC is available.
- Build one.
- Save the game.
- Restart OpenRCT2.
- Load the game again.

Junior is still available.

**Comment by Gymnasiast** [comment] 2018-01-23 18:09
I'm going to close it since I cannot reproduce, but feel free to reopen if it happens again.

**Closed by Gymnasiast** 2018-01-23 18:09 UTC
Labels: bug, rct1 import
