### ISSUE TITLE
macOS release 0.2.5 has invalid permissions

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#11050] opened 2020-03-25 22:05 UTC
**OS:** macOS
**Version:** 0.2.5

The v0.2.5 release is reported to have the executable bit on binary missing.

```
 janisozaur@trurl  ~/Downloads  zipinfo -s OpenRCT2-0.2.4-macos-x86_64.zip | grep Contents/Mac
drwxr-xr-x  3.0 unx        0 bx stor 19-Oct-28 22:01 OpenRCT2.app/Contents/MacOS/
-rwxr-xr-x  3.0 unx 10503808 bx defN 19-Oct-28 22:01 OpenRCT2.app/Contents/MacOS/OpenRCT2
 janisozaur@trurl  ~/Downloads  zipinfo -s OpenRCT2-0.2.5-macos-x86_64.zip | grep Contents/Mac
-rw----     2.0 fat        0 b- stor 20-Mar-24 20:54 OpenRCT2.app/Contents/MacOS/
-rw----     2.0 fat 10596700 bl defN 20-Mar-24 20:54 OpenRCT2.app/Contents/MacOS/OpenRCT2
```

Between the releases we have switched where out builds are done, from Travis CI to GitHub actions. I'm not sure how the packing is done, but I guess it uses invalid zip format which discards file permissions.

**Comment by Zweedeend** [comment] 2020-03-26 08:03
I can confirm this. MacOS would complain that 'Application cannot be opened'
Setting the executable bit fixed it for me:

`chmod +x OpenRCT2.app/Contents/MacOS/OpenRCT2 `

**Comment by IntelOrca** [comment] 2020-03-26 14:49
It looks like the release used the zip from the CI artefacts rather than openrct2.org. We create the zip within the action for openrct2.org which is why develop builds are fine.

The artefacts are zipped automatically by GitHub actions and it uses DOS format. We will need to artefact the zip we create in the action instead of the .app folder.

https://github.com/OpenRCT2/OpenRCT2/blob/develop/.github/workflows/ci.yml#L99

**Comment by janisozaur** [comment] 2020-03-26 14:54
The upload action recently got open sourced and it gained ability to also push single files, we can use that to to not end up with a zip in a zip.

**Comment by IntelOrca** [comment] 2020-03-26 18:17
> it gained ability to also push single files

Ah good, been waiting ages for that.

**Comment by thamara** [comment] 2020-04-13 03:09
I could not reproduce this on MacOS Catalina 10.15.3 using the release from the site nor a local release.

**Comment by andypettit** [comment] 2020-04-13 08:09
This is still occurring as of 4/12/2020 for me on Catalina 10.15.1, console logged the following:
`Apr 12 18:16:43 Andys-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000058.OpenRCT2[4910]): Could not find and/or execute program specified by service: 13: Permission denied: /private/var/folders/ff/cm0fxnz57ms8dyh9m05_3kxc0000gn/T/AppTranslocation/4431EC32-3357-4D42-93CD-D357680D1A86/d/OpenRCT2.app/Contents/MacOS/OpenRCT2
Apr 12 18:16:43 Andys-MacBook-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000058.OpenRCT2[4910]): Service exited with abnormal code: 78`

**Comment by janisozaur** [comment] 2020-04-13 09:14
The OS version should not play a factor here, there were reports on Reddit using 10.15.4

**Comment by tupaschoal** [comment] 2020-04-13 12:31
@andypettit can you describe in detail what you downloaded and how you executed, please?

**Comment by andypettit** [comment] 2020-04-13 19:59
Sure thing;

First attempt was to use the launcher which failed out with "Error extracting archive" next to its "play" button. Then I checked in ~/Application Support/OpenRCT2/bin and the app had the default MacOS app icon with an error symbol over it. Trying to run this errored out with "You can't open the application "OpenRCT2" because it may be damaged or incomplete.

I then decided to attempt the release portable zip, so I downloaded the 0.2.5 release zip, and unzipped. This time the app had the proper OpenRCT2 logo for the icon. I attempted to run it and the popup error said "The application OpenRCT2" can't be opened. 

I then decided to post in a few Discords before being informed of this thread which clued me in on it being a permissions issue so I was able to ultimately run the game by changing permissions as @Zweedeend did.

The release file was downloaded as recently as 6:04 UTC-7 on 4/12/2020 so these steps should still be reproducible.

**Comment by Gymnasiast** [comment] 2020-04-17 13:01
Should have been solved. Keeping this open for a bit.

**Closed** 2024-09-29 16:26 UTC
Labels: build, macOS (OS)
