### ISSUE TITLE
Feature Request: Single-Player Zero Clearance Permission in Multiplayer

### ISSUE THREAD

**Issue by thyeggman** [OpenRCT2/OpenRCT2#4292] opened 2016-08-15 21:04 UTC
Permit single players to be able to use zero clearance.  Perhaps add another user role to enable this.

I may take a stab at this at some point, but I don't know when I would get to it.

**Comment by joshbgosh10592** [comment] 2016-08-20 18:25
Or, vice verse. Cheat is globally enabled, and a single user wants to turn it back on so they cannot collide.

**Comment by Margen67** [comment] 2016-10-31 10:45
Fixed by #4483?

**Comment by Nubbie** [comment] 2017-07-15 10:47
Duplicate #3641

**Comment by Gymnasiast** [comment] 2017-07-15 10:50
Closing as (more-or-less a) duplicate of #3641.

**Closed by Gymnasiast** 2017-07-15 10:50 UTC
Labels: enhancement, multiplayer
