### ISSUE TITLE
MSVC builds ignore vcpkg-provided libraries

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#6792] opened 2017-12-06 22:17 UTC
**OS:** Windows 10
**Commit/Build:** 0a28b6e

MSVC builds ignore vcpkg-provided libraries.

**Steps to reproduce:**
1. Follow vcpkg installation instructions
2. Integrate vcpkg (`./vcpkg.exe install integrate`)
3. Install libraries with vcpkg, e.g. `./vcpkg.exe install sdl2:x64-windows ; ./vcpkg.exe install speexdsp:x64-windows`
4. Build `openrct2-win` project with MSVC IDE

Expected result:
* Build of openrct2 succeeds

Actual result:
* `E1696	cannot open source file "SDL.h"	libopenrct2ui	c:\Users\User\source\repos\openrct2-msvc\src\openrct2-ui\audio\AudioChannel.cpp	19	`
* `E1696	cannot open source file "speex/speex_resampler.h"	libopenrct2ui	c:\Users\User\source\repos\openrct2-msvc\src\openrct2-ui\audio\AudioChannel.cpp	20	`

**Comment by IntelOrca** [comment] 2017-12-07 12:18
How exactly do you want this to work?

The problem is we specify the dependencies lib, not the individual lib files. If you specify both you'll get conflict errors. Would an environment variable be satisfactory to say use vcpkg?

**Comment by janisozaur** [comment] 2017-12-07 21:28
Trying out windows/MSVC I would expect vcpkg to work with all the projects I set up. My personal view on that is that any custom build of libraries should have to be forced over the default vcpkg-provided ones.

Many libraries did in fact work (provided proper headers in expected paths), e.g. jansson or freetype, but not the ones mentioned.

**Comment by IntelOrca** [comment] 2017-12-07 22:39
I am not sure its easy to detect if there is a vcpkg library and if not use our dependencies. The problem is also that with vcpkg you must specify each lib individually where as with our dependencies - it is all merged into one.

What I might be able to do is enable vcpkg if the dependencies lib does not exist.

**Comment by janisozaur** [comment] 2017-12-08 08:58
Can't we just use `vcpkg export` and package libraries this way, as if they were provided by vcpkg? Is there any benefit in merging them into one superlibrary that breaks default way of working?

**Comment by IntelOrca** [comment] 2017-12-08 09:43
We can distribute the lib files separately instead of merging them. I did that just as a simplification.

**Comment by janisozaur** [comment] 2017-12-08 10:01
Wouldn't this automatically fix this issue?

**Comment by IntelOrca** [comment] 2017-12-08 12:22
It depends what has precedence.

**Closed** 2018-06-11 11:20 UTC
Labels: Windows (OS), bug, build
