### ISSUE TITLE
Title sequences window: Long names are not cropped in drop-down list

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4038] opened 2016-07-10 13:16 UTC
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.5-develop
**Commit/Build:** 59c3656

- Reproducible in RCT2 (vanilla)? No.
- Multiplayer? N/A

Try to do this:

* Open the title sequences window
* Create a new title sequence
* Enter the name “This is an ultralong name lalalalalalalalalalalalalalalalalalalalalalalalala”
* Watch the name being displayed on the drop-down list

Expected: The very long name gets cropped
Actual: The very long name is written over the drop-down list and even outside of the window!

**Comment by Nubbie** [comment] 2016-07-10 14:00
Duplicate of #3979

**Closed** 2016-07-10 15:36 UTC
Labels: duplicate
