### ISSUE TITLE
crash when saving

### ISSUE THREAD

**Issue by kevdog3700** [OpenRCT2/OpenRCT2#3410] opened 2016-04-23 23:14 UTC
windows 10
0.0.5
**Commit:** 

I when I hit save all the paths in my park disappeared then the game froze and crashed.
[Dump file .zip](https://github.com/OpenRCT2/OpenRCT2/files/233194/Dump.file.zip)

- [ ] Reproducible in RCT2 (vanilla):
- [ ] Multiplayer:

**Steps to reproduce:**
1. Load the save I put in the dump.zip file
2. just build a ride or 2 
3. try and save and it should then crash

**Dump file**
If you have a dump file, zip it and drag&drop it here.

**Save game:**
My save game is inside the Dump file.zip

**Comment by zsilencer** [comment] 2016-04-24 07:38
Started happening at faa2fb4fa12c465ee31a7558d4e7bc09dad2ec88

**Comment by jensj12** [comment] 2016-04-24 15:27
I had all _custom_ paths removed when saving (while paused, that may prevented a crash). They were saved properly and loading the park fixed it, no crash experienced. Still needs to be looked into.

**Comment by kevdog3700** [comment] 2016-04-24 17:03
Yes it happens on dev and stable builds. The park is saved but the game still crashes so i can still play on the map and save but it just crashes when I save but the park is still saved.

**Comment by jensj12** [comment] 2016-04-24 19:28
Possibly a duplicate: #3323

**Comment by kevdog3700** [comment] 2016-04-25 22:55
Here are some more dump files if it will help you i can get more.

[Dump file 2.zip](https://github.com/OpenRCT2/OpenRCT2/files/235555/Dump.file.2.zip)

**Comment by IntelOrca** [comment] 2016-05-07 17:23
Duplicate of 3323

**Closed** 2016-05-07 17:23 UTC
Labels: duplicate
