### ISSUE TITLE
Wooden Rollercoasters in Ghost Town not working correctly. 

### ISSUE THREAD

**Issue by Tshroom11** [OpenRCT2/OpenRCT2#17554] opened 2022-07-15 02:01 UTC
### Operating System

macOS Monterey

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4 on HEAD)

### Describe the issue

The pre-built wooden rollercoasters in Ghost Town not working correctly. 

They will not complete their full cycles. Very strange. 

I have adjusted the settings of the coaster every way I can but it will not work. 

I checked the other scenarios and the wooden coasters worked just fine. 

### Steps to reproduce

1. 
2. 
3.

**Comment by James103** [comment] 2022-07-15 02:07
The scenario "Ghost Town" does not have any pre-built rides at the start. What scenario actually has the problem?

**Comment by Gymnasiast** [comment] 2022-07-28 12:32
Please provide an affected save.

**Comment by Gymnasiast** [comment] 2022-12-31 17:28
Since the description is not very extensive and OP has not provided a way to reproduce it, I’ll have to close this.

**Closed by Gymnasiast** 2022-12-31 17:28 UTC
Labels: invalid/incomplete
