### ISSUE TITLE
Ghost paths placed down when placing paths

### ISSUE THREAD

**Issue by thewesker** [OpenRCT2/OpenRCT2#9730] opened 2019-08-05 22:46 UTC
**OS: Windows 10** 
**Version: 0.2.3-129** 
**Commit/Build: 2fd91fd**

When placing paths, there is a ghost path placed wherever the cursor moves without clicking anything. Just noticed today and can reproduce. Upon saving and loading the save of the park, the ghost paths are gone. New and existing parks are producing the issue.

**Steps to reproduce:**
1. Load or start new park
2. Click path tool
3. Move cursor over ground

**Screenshots / Video:**
![RCTOA  Acres 2019-08-05 18-41-14](https://user-images.githubusercontent.com/8624039/62499580-3eab0300-b7b1-11e9-8ade-84d3b807e6af.png)
![Crazy Castle 2019-08-05 18-46-02](https://user-images.githubusercontent.com/8624039/62499592-48cd0180-b7b1-11e9-84bd-e5067164ffc4.png)

**Comment by ZehMatt** [comment] 2019-08-05 23:10
Looks like its a regression from #9531

**Comment by UrbanSoldier9** [comment] 2019-08-06 01:13
I've been having this same issue, any way to fix it or are they gonna patch it sometime soon, i haven't seen much info on this bug so I'm guessing its new...

**Comment by smolmuffin** [comment] 2019-08-06 03:02
Yeah I just discovered this bug when I tried to play tonight. Very frustrating. Hopefully its fixed with a patch before this weekend. I'm moving by then and I was looking forward to playing this while I was internetless for a few days. If not I might have to go to a earlier version. Is that possible without a complete uninstall?

**Comment by duncanspumpkin** [comment] 2019-08-06 05:48
It's ridiculously easy to switch versions just run the old .exe. this will be a regression from the refactor

**Closed** 2019-08-06 17:44 UTC
Labels: bug
