### ISSUE TITLE
BACKTRACE 1d7695 ttf_draw_string_raw_ttf

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8192] opened 2018-10-31 16:34 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/1d76953540714fbe030b81f72cfa5cf6f25346432dd337fcf5332c2c9dc7e865?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Oct 31 2018 16:34:46)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 83c3f3a: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ttf_draw_string_raw_ttf -> ttf_process_glyph_run -> ttf_process_string -> DrawText -> DrawTextCompat -> window_editor_bottom_toolbar_paint -> window_draw_single -> window_draw -> window_draw_all -> OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks -> OpenRCT2::Drawing::X8DrawingEngine::PaintWindows -> OpenRCT2::Paint::Painter::Paint -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2018-11-02 22:14
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8180

**Closed by janisozaur** 2018-11-02 22:14 UTC
Labels: backtrace.io, crash
