### ISSUE TITLE
If the user is missing a plug in for a save - Invalid data comes up which isn't clear

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#4666] opened 2016-10-20 21:26 UTC
When the user tries to load a map where there is a missing plug-in, the error "File contains invalid data" comes up which might be misleading for people as it sounds like the save file could be broken, especially when it sounds like a object/data file is invalid in a way that it's the wrong format/location etc

Instead it might should say "File is missing objects"

**Why?**
There were right now a issue with a person who tried to open his save file with that error showing up, not many common players knew what it ment as he got the info to clean up the plug-in/object folder which made it worse.
Right now when he tried verbose (which could be a option for easier de-bug), [it told him these files are missing](http://pastebin.com/rkKu2NJN)

**Comment by IntelOrca** [comment] 2016-10-20 21:31
Duplicate of #1399

**Closed by IntelOrca** 2016-10-20 21:31 UTC
