### ISSUE TITLE
Cannot save tracks

### ISSUE THREAD

**Issue by waylon531** [OpenRCT2/OpenRCT2#1636] opened 2015-07-16 23:56 UTC
I am unable to save custom designed rides. Saved tracks do not appear when building another coaster of the same type and no files with the name of my coaster are created. This happens even when running the game as root, so it's probably not a file permissions issue. My OS is Arch Linux and I'm running the GOG version of rct2. I am using the git version of openrct2.

**Comment by duncanspumpkin** [comment] 2015-07-17 11:45
Duplicate of #1486.

**Closed by duncanspumpkin** 2015-07-17 11:45 UTC
Labels: duplicate
