### ISSUE TITLE
BACKTRACE ae33c9

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8296] opened 2018-11-25 15:07 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/ae33c950a2fb7d2ba5ed370e21b1e2dcf9fca2907a610856fabfa487050921d9?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sun Nov 25 2018 14:09:57)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> d0108b3: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>rct_peep::SetState -> vehicle_update_unloading_passengers -> vehicle_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:17
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8332

**Closed by janisozaur** 2019-02-02 22:17 UTC
Labels: backtrace.io, crash
