### ISSUE TITLE
Linux static and portable build

### ISSUE THREAD

**Issue by legluondunet** [OpenRCT2/OpenRCT2#9722] opened 2019-08-04 12:13 UTC
**OS:**
Linux Ubuntu 19.04

**Commit/Build:** [e.g. 426e106]
./openrct2 -v
OpenRCT2, v0.2.3-105 (c3234b144 on develop, DEBUG)
Linux (x86-64)

I would like to compile a static and portable openRCT2 build to distribute it in a Lutris script.
I need a static build to minimize libraries dependencies on different Linux platform.
I checked portable and static in ccmake ..
but I obtained error at the end of the compilation:

```
[ 98%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/TitleScenarioSelect.cpp.o
[ 98%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Tooltip.cpp.o
[ 98%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/TopToolbar.cpp.o
[ 99%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/TrackDesignManage.cpp.o
[ 99%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/TrackDesignPlace.cpp.o
[ 99%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/TrackList.cpp.o
[ 99%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/ViewClipping.cpp.o
[100%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Viewport.cpp.o
[100%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Water.cpp.o
[100%] Linking CXX executable openrct2
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o) : dans la fonction « String::ToUtf8[abi:cxx11](std::basic_string_view<wchar_t, std::char_traits<wchar_t> > const&) » :
String.cpp:(.text+0x26e) : référence indéfinie vers « icu_63::UnicodeString::fromUTF32(int const*, int) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x29a) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x2cb) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o) : dans la fonction « String::ToWideChar[abi:cxx11](std::basic_string_view<char, std::char_traits<char> > const&) » :
String.cpp:(.text+0x36a) : référence indéfinie vers « icu_63::UnicodeString::fromUTF8(icu_63::StringPiece) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x424) : référence indéfinie vers « icu_63::UnicodeString::toUTF32(int*, int, UErrorCode&) const »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x431) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x4aa) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o) : dans la fonction « String::CodePageFromUnicode(icu_63::UnicodeString, int) » :
String.cpp:(.text+0x18de) : référence indéfinie vers « ucnv_open_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x18ff) : référence indéfinie vers « u_errorName_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x196c) : référence indéfinie vers « ucnv_getMaxCharSize_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x19fa) : référence indéfinie vers « icu_63::UnicodeString::getTerminatedBuffer() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1a5b) : référence indéfinie vers « ucnv_fromUnicode_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1a7c) : référence indéfinie vers « u_errorName_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1ae6) : référence indéfinie vers « ucnv_close_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o) : dans la fonction « String::Convert[abi:cxx11](std::basic_string_view<char, std::char_traits<char> > const&, int, int) » :
String.cpp:(.text+0x1c01) : référence indéfinie vers « icu_63::UnicodeString::UnicodeString(char const*, char const*) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1c4d) : référence indéfinie vers « icu_63::UnicodeString::UnicodeString(icu_63::UnicodeString const&) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1c9d) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1cad) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1cd5) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1cf8) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o) : dans la fonction « String::ToUpper[abi:cxx11](std::basic_string_view<char, std::char_traits<char> > const&) » :
String.cpp:(.text+0x1d9a) : référence indéfinie vers « icu_63::UnicodeString::fromUTF8(icu_63::StringPiece) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1dc1) : référence indéfinie vers « icu_63::UnicodeString::toUpper() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1df3) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : String.cpp:(.text+0x1e5d) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o) : dans la fonction « icu_63::ByteSink::ByteSink() » :
String.cpp:(.text._ZN6icu_638ByteSinkC2Ev[_ZN6icu_638ByteSinkC5Ev]+0xb) : référence indéfinie vers « vtable for icu_63::ByteSink »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o) : dans la fonction « icu_63::StringByteSink<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~StringByteSink() » :
String.cpp:(.text._ZN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEED2Ev[_ZN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEED5Ev]+0x26) : référence indéfinie vers « icu_63::ByteSink::~ByteSink() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o) : dans la fonction « icu_63::StringByteSink<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~StringByteSink() » :
String.cpp:(.text._ZN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEED0Ev[_ZN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEED5Ev]+0x20) : référence indéfinie vers « icu_63::UMemory::operator delete(void*) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o) : dans la fonction « std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >& icu_63::UnicodeString::toUTF8String<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const » :
String.cpp:(.text._ZNK6icu_6313UnicodeString12toUTF8StringINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERT_S9_[_ZNK6icu_6313UnicodeString12toUTF8StringINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERT_S9_]+0x50) : référence indéfinie vers « icu_63::UnicodeString::toUTF8(icu_63::ByteSink&) const »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o) : dans la fonction « icu_63::StringByteSink<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::StringByteSink(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int) » :
String.cpp:(.text._ZN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEC2EPS6_i[_ZN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEC5EPS6_i]+0xb5) : référence indéfinie vers « icu_63::ByteSink::~ByteSink() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o):(.data.rel.ro._ZTVN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTVN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x28) : référence indéfinie vers « icu_63::ByteSink::GetAppendBuffer(int, int, char*, int, int*) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o):(.data.rel.ro._ZTVN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTVN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x30) : référence indéfinie vers « icu_63::ByteSink::Flush() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(String.cpp.o):(.data.rel.ro._ZTIN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTIN6icu_6314StringByteSinkINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x10) : référence indéfinie vers « typeinfo for icu_63::ByteSink »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(LanguagePack.cpp.o) : dans la fonction « icu_63::UObject::UObject() » :
LanguagePack.cpp:(.text._ZN6icu_637UObjectC2Ev[_ZN6icu_637UObjectC5Ev]+0xb) : référence indéfinie vers « vtable for icu_63::UObject »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(LanguagePack.cpp.o) : dans la fonction « icu_63::Replaceable::Replaceable() » :
LanguagePack.cpp:(.text._ZN6icu_6311ReplaceableC2Ev[_ZN6icu_6311ReplaceableC5Ev]+0x1b) : référence indéfinie vers « vtable for icu_63::Replaceable »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(LanguagePack.cpp.o) : dans la fonction « icu_63::UnicodeString::UnicodeString() » :
LanguagePack.cpp:(.text._ZN6icu_6313UnicodeStringC2Ev[_ZN6icu_6313UnicodeStringC5Ev]+0x1b) : référence indéfinie vers « vtable for icu_63::UnicodeString »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(LanguagePack.cpp.o) : dans la fonction « LanguagePack::FixRTL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) » :
LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xd0) : référence indéfinie vers « icu_63::UnicodeString::fromUTF8(icu_63::StringPiece) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x119) : référence indéfinie vers « ubidi_openSized_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x15c) : référence indéfinie vers « ubidi_setPara_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x173) : référence indéfinie vers « icu_63::UnicodeString::getBuffer(int) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x19a) : référence indéfinie vers « ubidi_writeReordered_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1a9) : référence indéfinie vers « ubidi_close_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1c0) : référence indéfinie vers « icu_63::UnicodeString::releaseBuffer(int) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1d4) : référence indéfinie vers « icu_63::UnicodeString::getBuffer(int) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x211) : référence indéfinie vers « u_shapeArabic_63 »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x225) : référence indéfinie vers « icu_63::UnicodeString::releaseBuffer(int) »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x257) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x266) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x275) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x2f5) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x304) : référence indéfinie vers « icu_63::UnicodeString::~UnicodeString() »
/usr/bin/x86_64-linux-gnu-ld.bfd.real : libopenrct2.a(LanguagePack.cpp.o):LanguagePack.cpp:(.text._ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN12LanguagePack6FixRTLERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x313) : encore plus de références indéfinies suivent vers « icu_63::UnicodeString::~UnicodeString() »
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/openrct2.dir/build.make:1780: openrct2] Error 1
make[1]: *** [CMakeFiles/Makefile2:211: CMakeFiles/openrct2.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Thank you for your help.

**Comment by janisozaur** [comment] 2019-08-04 12:30
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/9592

Additionally, post error messages in English.

**Closed by janisozaur** 2019-08-04 12:30 UTC
