### ISSUE TITLE
scenery tabs messed up + magic extra objects

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#3563] opened 2016-05-10 22:21 UTC
**OS: 8.1** 
**Version: .5** 
**Commit: 4298f41** 

Duplicate scenery tabs, objects mysteriously being added to the objects list.

![image](https://cloud.githubusercontent.com/assets/3454156/15164275/a4ad20c2-16c2-11e6-9c49-44037f2bb005.png)

here's a dump when I removed some of the extra scenery and went into the misc. tab

[scenery crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/258236/scenery.crash.zip)

**Comment by Gymnasiast** [comment] 2016-05-11 07:53
Duplicate of #3562.

**Closed by Gymnasiast** 2016-05-11 07:53 UTC
