### ISSUE TITLE
Competive scenarios/mode for multiplayer games

### ISSUE THREAD

**Issue by Littlemeister** [OpenRCT2/OpenRCT2#2663] opened 2016-01-07 06:53 UTC
Hi. Wouldnt it be really cool to have competetive modes for multiplayer. Where players have to compete against eachother about who can make the best park (or even small scenarios like who can make the best rollercoaster in under "x" minuts).

I think it would be cool. 

Example: You could make it so you are up against, lets say 4 players, and there is only 5k peeps in the map. And after four years the game ends, and whoever has the most peeps wins. 

This is just an example and you could make many different multiplayer modes. The main point is that many people really enjoy competing and having a challange, and I think multiplayer competetive mode could be really really cool. I would absolutely play it.

**Comment by PFCKrutonium** [comment] 2016-01-07 08:19
This can not be done yet, unfortunately. It sounds like a good idea though :D

**Comment by IntelOrca** [comment] 2016-09-29 11:28
Duplicate of #896

**Closed by IntelOrca** 2016-09-29 11:28 UTC
Labels: duplicate, feature, multiplayer, requires more implementation
