### ISSUE TITLE
BACKTRACE 3cfdc2 DrawRLESprite1<0> -> gfx_rle_sprite_to_buffer

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8395] opened 2018-12-09 03:45 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/3cfdc2b3f0ca06795b06544222cc00ad8d8b9c85041b16bacd79c0eaf3ef291d?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sun Dec 09 2018 03:06:41)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Wags\\Documents\\OpenRCT2\\3dbf6673-bcf8-4f82-a2d8-9114d1ef81fb.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Wags\\Documents\\OpenRCT2\\3dbf6673-bcf8-4f82-a2d8-9114d1ef81fb.sv6.gz: <em>1</em><br><strong>commit:</strong> dc7d141: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>DrawRLESprite1<0> -> gfx_rle_sprite_to_buffer -> gfx_draw_sprite_palette_set_software -> gfx_draw_sprite_software -> set_vehicle_type_image_max_sizes -> RideObject::Load -> ObjectManager::LoadObjects -> Network::LoadMap -> Network::Client_Handle_MAP -> Network::ProcessConnection -> Network::UpdateClient -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::TitleScreen::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 19:59
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8471

**Closed by janisozaur** 2019-02-02 19:59 UTC
Labels: backtrace.io, crash
