### ISSUE TITLE
Keep non-config files outside of XDG_CONFIG_DIR

### ISSUE THREAD

**Issue by PureTryOut** [OpenRCT2/OpenRCT2#6738] opened 2017-11-27 17:37 UTC
Right now (a3be15c9c9759005e04c88b007ccb315acf4b93c) all per-user settings are saved in `XDG_CONFIG_DIR/OpenRCT2` (`~/.config/OpenRCT2` on Linux). However, this directory should only be used to save settings and user preferences. All other data (like savegames and user scenarios most notably) should be kept in `~/.local/share/OpenRCT2` instead.

**Comment by janisozaur** [comment] 2017-11-27 18:18
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/2410

**Closed by janisozaur** 2017-11-27 18:18 UTC
