### ISSUE TITLE
Cannot sign name after scenario is completed

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#1962] opened 2015-09-23 11:58 UTC
When I complete a scenario that I haven't yet completed, I get the "Congratulations!" Pop up, however there is no button to allow me to sign my name.
Is there something wrong there?

**Comment by IntelOrca** [comment] 2015-09-23 16:12
Can you give steps to reproduce and let us know what version you are using.

**Comment by UTNerd24** [comment] 2015-09-24 02:58
I was using 1253, but it seems that 1255 has fixed it.
Thank you!

**Comment by IntelOrca** [comment] 2015-09-24 11:30
There haven't been any recent commits related to this so it seems strange that it would of been fixed unless it was indirectly caused by a memory issue.

**Comment by UTNerd24** [comment] 2015-09-24 11:54
Yeah. It happened again even after using the latest build.

I think It might have something to do with my Saved games.

**Comment by IntelOrca** [comment] 2015-09-24 11:59
If you have a saved game which quickly reproduces the issue, that would be very helpful.

**Comment by Bouncer** [comment] 2015-10-03 06:29
I'm having the exact same issue. Completed four levels so far, and for two I could not enter my name. Also in the scenario selection screen it does not say I ever completed these parks. If I trigger the win manually from the cheats window it also does not give me the option to enter a name and save the score.

**Comment by IntelOrca** [comment] 2015-10-03 09:42
@Bouncer what version of the game are you using?

**Comment by tuut84** [comment] 2015-10-03 12:32
I have the same issue as Bouncer with the sherwood forest scenario ( Dark Age - Robin Hood ). I could not enter my name and in the scenario selection screen it doesn't say it is completed. I noticed that no pop up window appeared when the level was completed. I had to look for it manually to see if the mission objectives were completed.

Im using OpenRCT2-develop-830.zip from https://openrct.net/builds.php

**Comment by Bouncer** [comment] 2015-10-03 15:15
For me the window does popup, there is just no button to enter your name. I'm also running develop v0.0.3 - A831, on Windows 10. The scenarios are Crazy Castle and Dusty Greens. I saved them after completion so I cannot provide you with a save game (yet).

**Comment by IntelOrca** [comment] 2015-10-08 11:45
I don't understand, I fixed this awhile ago and yet this bug keeps cropping up again.

**Comment by duncanspumpkin** [comment] 2015-10-09 21:13
I've made a small change that i think solves this bug. Can everyone retest with new scenarios. The bug will still happen on old saves.

**Comment by tuut84** [comment] 2015-10-10 09:09
I tested sherwood forest scenario ( Dark Age - Robin Hood ) and the fix seems to work for me. will try some other scenarioes as well today/tomorrow.

**Comment by duncanspumpkin** [comment] 2015-10-16 11:33
Is everyone okay with me closing this?

**Comment by Bouncer** [comment] 2015-10-16 11:39
Sure. I have not been able to test it, but I'll report it if the bug shows up again.

**Closed** 2015-10-16 11:41 UTC
Labels: bug

**Comment by schott12521** [comment] 2017-10-24 20:54
I'm using the latest dev version and this occurs only if I beat a park in the Wacky Worlds section, it does not occur in any other parks.
