### ISSUE TITLE
Local Network

### ISSUE THREAD

**Issue by devnoname120** [OpenRCT2/OpenRCT2#2662] opened 2016-01-06 21:00 UTC
Currently, a player that is willing to join someone on a local network needs to manually input the IP address of the server.

I think that the game should automatically detect servers on the local network, by doing UDP broadcasting.

**Comment by IntelOrca** [comment] 2016-01-06 21:11
Duplicate of #2339

**Closed** 2016-01-06 21:12 UTC
Labels: duplicate
