### ISSUE TITLE
Vehicles not appearing in ride window nor on the track

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5850] opened 2017-07-09 12:53 UTC
As you can see on the screen I tried putting vintage cars on steel wild mouse track. This has always worked in both RCT2 and OpenRCT2, until now. The ride vehicle window is empty and when I test the ride there are no cars on the track. It's not just vintage cars, some other vehicles types are also similarly not working and I think the reverser coaster has a weird sprite instead of the vehicle showing.

![erroreroor](https://user-images.githubusercontent.com/19242088/27994055-e4555748-6483-11e7-9530-65d9ff85fb22.png)

v0.0.8 ba2f129 on windows 8

**Comment by janisozaur** [comment] 2017-07-11 20:52
![openrct2_229](https://user-images.githubusercontent.com/550290/28090123-8753b3b4-668b-11e7-8008-d9034b4f1c80.png)

Works for me on ba2f129

**Comment by Gymnasiast** [comment] 2017-07-12 09:30
Can't reproduce this either.

I'm not saying the bug isn't there, but I think it's probably no showstopper, so I'm moving this off the 0.1.0 milestone.

**Comment by IntelOrca** [comment] 2017-07-19 17:08
I can not reproduce this earlier. @Liampie could you please provide steps to reproduce either from a new game or a provided saved game?

**Comment by Gymnasiast** [comment] 2018-01-01 13:48
Since there has been no comment for six months, I'll close this. Feel free to reopen if this persists.

**Closed by Gymnasiast** 2018-01-01 13:48 UTC
Labels: bug
