### ISSUE TITLE
Making Virtual Floor Less Visually Prominent

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#7221] opened 2018-02-25 22:57 UTC
Not really an issue, but a discussion about the virtual floor.

I personally use the virtual floor without much issue, although sometimes it does annoy me when placing smaller custom scenery objects, because it blends in with the water-colored virtual floor and its thick outlines. Would there be a way to make the outlines a bit less thick, and the water-colored floor a bit more transparent?

I know many others, particularly on New Element, who do not use the virtual floor because of how visually prominent it is.

Thanks all!

**Comment by AaronVanGeffen** [comment] 2018-02-25 23:02
I suppose we could make it optionally fully transparent, as was the case in @JeroenDStout's original PR? #6338

**Comment by JeroenDStout** [comment] 2018-02-25 23:11
@saxman1089 could you perhaps post some situations you have encountered in which it is too intrusive? I have heard the comment from New Element (and BlindIRL), but I am not sure where exactly the problem is. What is a moment at which it feels too prominent?

That said, a non-indicative floor is of course possible. I am not sure if less transparent is very possible. I did cycle through a lot of colours in trying it out, but something always clashes with something.

Customising it (a bit) sounds good to me. Ultimately why I put the transparent floor in (and made the lines thicker) was because it tends to fall 'to' the background otherwise... but I may have gone too far in a few places.

**Comment by Gammadivided** [comment] 2018-02-28 01:09
The collision edges are white, so trying to place certain white objects, like custom trims, is a nightmare. Placing water-colored trims also sounds horrible in these circumstances.

**Comment by Liampie** [comment] 2018-03-21 16:37
A single pixel wide grid with no fill should be enough, in my opinion.

**Comment by thiebert** [comment] 2018-03-21 17:29
I was using virtual floor for a while last night, then when trying to place certain objects like trim walls and some decor posts, they were completely lost in the thick white outline, and i was unable to see where the object was being placed.

**Comment by JeroenDStout** [comment] 2018-03-21 17:41
@thiebert If it is not too much of an effort, could you post some screenshots of placements that were giving you trouble? Or even preferably a gif that shows the problem. I think when I designed the floor I optimised it for my own use-cases, so I think I need to see it from a different perspective.

**Comment by thiebert** [comment] 2018-03-21 17:47
If I can remember to do so when I get home, certainly.

**Comment by thiebert** [comment] 2018-03-21 17:50
In the meantime, you can try placing this object using virtual floor to replicate the issue:

https://www.nedesigns.com/rct2-object/11211/itmbeam2/

**Comment by JeroenDStout** [comment] 2018-03-21 18:22
@thiebert Just to be clear, the problem is placing it while white, right? If the object is black or grey it is still clear?

**Comment by Broxzier** [comment] 2018-03-21 18:46
Sometimes it's difficult to see small quarter objects through the virtual floor, especially when there is a lot of 'noise' below it.

![image](https://user-images.githubusercontent.com/9705046/37730126-2452441c-2d3f-11e8-9c32-157df50d5e52.png)

I find it much easier to see without the transparent floor:

![image](https://user-images.githubusercontent.com/9705046/37730628-7445b692-2d40-11e8-8f5f-a1e95477c6fd.png)

**Comment by thiebert** [comment] 2018-03-21 18:48
@JeroenDStout it's always white while placing, since the object "ghosts" until placed.

**Comment by JeroenDStout** [comment] 2018-03-21 19:28
@thiebert you're completely right, I got a bit confused.

I see the problem in @Broxzier 's example, though. I suppose when making the floor I was mostly worried about creating vertical contrast, so I went quite far with the isolation. But if you have to do a lot of complex small things that can be a problem.

I might have a suggestion for this; when the virtual floor is enabled through the regular way, add a tickbox in a dropdown menu for the 'thicker & filled' option, much like the toggle for invisible supports. I think there will be moments that the thick fill will be useful and moments the thinner version will be useful, and rather than creating something in the middle being able to switch between the two while working on something could be useful.

**Comment by janisozaur** [comment] 2018-03-21 20:04
If there are to be two modes of this, I think that having a tickbox to select them is a poor experience. If anything, it should change the default state and there should be user-selectable hotkey to switch to alternative mode. That said hotkeys can be empty by default too.

**Comment by thiebert** [comment] 2018-03-21 20:07
A hotkey seems to obfuscate the ability to change modes. I'm not sure that most users would even know it's an option.

**Comment by saxman1089** [comment] 2018-03-21 21:04
I do agree that the thick/filled and thinner/unfilled options are a good idea. I see the advantage of a hotkey switch, i.e. being able to make the change between versions on the fly without jumping into the settings, but I also see the advantage of setting it in the settings menu. I'm good with either way, but mostly because I think I'd find myself gravitating towards using the thinner/more transparent option most of the time.

**Comment by AaronVanGeffen** [comment] 2018-05-30 11:17
We've merged some changes to the virtual floor (#7577) to give you some more control over its appearance. It doesn't tackle all the comments laid out in this thread yet, but I'd be interested in hearing your thoughts on the changes.

**Comment by saxman1089** [comment] 2018-05-30 11:19
Thanks guys. I'll check it out tonight and let you know what I think!

**Comment by Gymnasiast** [comment] 2020-05-20 08:06
https://github.com/OpenRCT2/OpenRCT2/pull/11157 made the lines thinner. I'd argue that that, combined with #7577, should be adequate.

**Closed by Gymnasiast** 2020-05-20 08:06 UTC
Labels: discussion
