### ISSUE TITLE
Saved Mazes are incomplete

### ISSUE THREAD

**Issue by imbw267** [OpenRCT2/OpenRCT2#10751] opened 2020-02-20 06:33 UTC
**OS:** Windows 10
**Version:** 0.2.4 develop
**Commit/Build:** 1272c0c04

Saving any Maze with the "Save Track Design" will create a track that is incomplete when using the pre-built track selection

**Steps to reproduce:**
1. First create 1x2 maze (or any complete maze)
2. Add Entrance and Exit
4. Let guests use the ride to generate ratings
5. Save the Track as a new custom track
6. Create a new Maze
7. Select and build the custom track
8. Enjoy the missing slice!

**Screenshots / Video:**
![2x2_saved_and_original](https://user-images.githubusercontent.com/25447160/74907020-8cb7da80-5380-11ea-8465-48fc8ec2df13.png)

![4x4_saved_and_original](https://user-images.githubusercontent.com/25447160/74907007-8590cc80-5380-11ea-87e5-e0b857ec8f09.png)

**Save game:**

[Canvas_148_Blank_2.zip](https://github.com/OpenRCT2/OpenRCT2/files/4229166/Canvas_148_Blank_2.zip)

**Comment by YJSoft** [comment] 2020-02-20 09:55
possible duplicate of #10687 
(although that one is from stable version)

**Closed** 2020-08-05 17:18 UTC
Labels: bug
