### ISSUE TITLE
BACKTRACE 323825

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8362] opened 2018-12-05 10:24 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/32382546e04162599bade644b1eed36503461d03abe2616f1293ad4d2fbf1a7a?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Dec 05 2018 10:23:36)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> *: <em>1</em><br><strong>commit:</strong> 1abb31a: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ImageTable::~ImageTable -> Object::~Object -> SmallSceneryObject::scalar deleting destructor' -> ObjectManager::UnloadAll -> OpenRCT2::Context::~Context -> OpenRCT2::Context::scalar deleting destructor' -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 20:07
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8423

**Closed by janisozaur** 2019-02-02 20:07 UTC
Labels: backtrace.io, crash
