### ISSUE TITLE
Language Spoken On Start Server Section

### ISSUE THREAD

**Issue by harrysbird** [OpenRCT2/OpenRCT2#5709] opened 2017-06-26 00:23 UTC
Hello.

I Would to have Language Spoken Settings on the Server Config Section. Seen in OpenTTD
Some People can speak or chat another language like in: English, French, German, Japanese, China, Thai, etc

![idea](https://user-images.githubusercontent.com/3393747/27520945-a274430c-59ca-11e7-8590-1f53c8286d4f.png)

**Comment by Nubbie** [comment] 2017-06-26 00:52
Isn't it easier just saying [GER], [SWE], [DUTCH] or something in the server name? 
As it doesn't feel like there are that many people speaking specific languages - English feels more standard 😞

**Comment by YJSoft** [comment] 2017-06-26 01:35
duplicate of #3116

**Closed** 2017-06-26 05:29 UTC
