### ISSUE TITLE
White Screen in openRCT2 0.0.5/1517 (Win7 64-Bit)

### ISSUE THREAD

**Issue by DonCamatic** [OpenRCT2/OpenRCT2#4579] opened 2016-10-10 14:27 UTC
Hello guys 

Windows 7 64-Bit
0.0.5
36578fc

I just start the game and i got a white screen and a fail message.
I have the dump zipped but renamed the file extension.

**Dump file**
[0426307a-0add-4171-bc17-03496f0c4224(36578fc).txt](https://github.com/OpenRCT2/OpenRCT2/files/519698/0426307a-0add-4171-bc17-03496f0c4224.36578fc.txt)
Rename txt to zip please. Even if the file ext. is zip i got a upload error lol.

**Screenshots / Video:**
![unbenannt](https://cloud.githubusercontent.com/assets/22748142/19239418/4d123c50-8f06-11e6-8dcf-0aee6238c89e.png)

**Comment by Nubbie** [comment] 2016-10-10 15:25
I suggest you try update https://openrct2.org/downloads/develop/6f95ba4

**Comment by janisozaur** [comment] 2016-10-10 18:10
Duplicate of #4577

**Closed by janisozaur** 2016-10-10 18:10 UTC
