### ISSUE TITLE
Mechanics Walk to Tile 0,0 After Fixing Ride from an Entrance-Only Station

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#11695] opened 2020-05-10 01:39 UTC
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** fa91b40 on develop

Working on a park with a bunch of rides that have entrances and exits in separate stations. I noticed that all of my mechanics would disappear as I was working on the park, then finally found them all hanging out off the map at tile 0,0. After a bunch of testing, I figured out that the mechanics were fixing the ride for a vehicle malfunction at the entrance station, and then walking all the way to the corner of the map. It looks to me like when the mechanics enter through an entrance in order to fix a ride, some flag or coordinate which indicates they should exit through the same way isn't set, and the game is putting them on tile 0,0.

I didn't want to share my park yet, so I made a small test park and was able to reproduce the issue using the junior coaster. This test park is attached.

- [ ] Reproducible in RCT2 (vanilla)? Don't think so, but don't know for sure
- [ ] Specific to multiplayer? No.

**Steps to reproduce:**
1.  Build a tracked ride with separate stations for entrance and exit.
2. Force (or wait for) a vehicle malfunction breakdown in the entrance station.
3. Wait for the mechanic to finish fixing the ride.
4. Watch the mechanic walk to coordinate 0,0 (off the map), and then "finish" fixing the ride and return to the "walking" state.

**Save game:**
[File_003.txt](https://github.com/OpenRCT2/OpenRCT2/files/4604992/File_003.txt)

**Comment by AaronVanGeffen** [comment] 2020-05-10 07:43
Duplicate of #8145. Unfortunately, this old bug still hasn't been fixed.

**Comment by duncanspumpkin** [comment] 2020-05-10 15:40
Turns out this isn't a duplicate but a regression due to some refactoring

**Closed** 2020-05-11 18:28 UTC
Labels: regression
