### ISSUE TITLE
When using the terrain generator in the scenario creator it puts "aboriginal art set piece" instead of trees

### ISSUE THREAD

**Issue by salpert95** [OpenRCT2/OpenRCT2#15994] opened 2021-11-25 03:50 UTC
### Operating System

Windows 10 x64

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (b44b5ec on develop) provided by GitHub

### Describe the issue

when creating a scenario, the terrain generator ONLY selects "aboriginal art set piece" when trees are selected.

### Steps to reproduce

1. open game
2. choose to create a new scenario
3. choose to generate terrain with trees
4. 

### Attachments

![image](https://user-images.githubusercontent.com/1409407/143365426-abf4a219-86b4-4a4b-9e3a-7adc8d60418c.png)

**Comment by Fred-1044276** [comment] 2021-11-25 06:11
Does this happen even if you don't have the object selected (i.e. the Australasia Themeing was selected)?

**Comment by salpert95** [comment] 2021-11-25 06:33
It was not selected, but yes, I did open it and actually select a specific tree, it still did this, even after a restart.

**Comment by telk5093** [comment] 2021-11-25 11:36
Looks like duplicate of #14155

**Closed** 2022-02-09 20:50 UTC
Labels: bug
