### ISSUE TITLE
Assertion Failed error when build new ride/attraction is clicked

### ISSUE THREAD

**Issue by kenrick95** [OpenRCT2/OpenRCT2#4977] opened 2017-01-03 07:57 UTC
**OS:** Windows 10
**Version:** 0.0.6-develop
**Commit/Build:** 68ed961

```
Assertion failed!

Program: D:\Program Filed\OpenRCT2\openrct2.exe
File: src\windows\new_rice.c
Line: 394

Expression: _windowNewRideCurrentTab < countof(_windowNewRideHighlightedItem)

For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)

[Abort] [Retry] [Ignore]
```

- [ ] Reproducible in RCT2 (vanilla)? Unknown
- [ ] Multiplayer? Unknown

**Steps to reproduce:**
1. Play the game
2. After some time (around 30 minutes or so of playtime), click "Build new ride/attraction"
3. Error message is produced (see below). Ignoring the error will let the game continue. Usually, I save the current game, exit, and then load it back and now "Build new ride/attraction" works as expected.

**Dump file**

N.A. clicking "Abort" or "Retry" does not produce the debug dump.

**Screenshots / Video:**

![20170103143959_1](https://cloud.githubusercontent.com/assets/3090380/21602181/d2f4b7ee-d1c3-11e6-88eb-86cc767af712.jpg)
![capture-newrite](https://cloud.githubusercontent.com/assets/3090380/21602176/b71de400-d1c3-11e6-8a4d-0d788e31156c.PNG)

**Save game:**

[Electric Fields.zip](https://github.com/OpenRCT2/OpenRCT2/files/681843/Electric.Fields.zip)

**Comment by janisozaur** [comment] 2017-01-03 08:07
duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/4958

**Closed by janisozaur** 2017-01-03 08:07 UTC
