### ISSUE TITLE
Large portions of the screen do not invalidate properly

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#7655] opened 2018-06-11 12:04 UTC
Not sure how to best describe this, but peeps and coaster cars are fucked up in some parks. They would keep moving like they normally would, except the sprites aren't keeping up and are just frozen somewhere. Like a video where the audio keeps playing but the video itself is buffering. Open this park and it should be obvious:
https://www.nedesigns.com/park/556/peublo-canyon-boardwalk/

Using version 0.2.0 bcd4e9c on Window 8

**Comment by AaronVanGeffen** [comment] 2018-06-11 12:07
Sounds like this might have something to do with https://github.com/OpenRCT2/OpenRCT2/pull/6998. Could you enable drawing debug tools to check whether some tiles have been marked as blocked?

**Comment by Broxzier** [comment] 2018-06-11 12:09
It looks like almost nothing gets invalidated anymore. Somehow maximizing and then minimizing the screen reset it to normal behaviour.

**Comment by JappyNE** [comment] 2018-06-11 15:40
The problem does improve itself when alt-tabbing out of the game and coming back later but not always. Some parks are really messed up and are completely frozen, rides and peeps not moving until I click on them, same for trains. 
![cutoff peeps](https://user-images.githubusercontent.com/40169350/41241919-7829d650-6d9e-11e8-98ad-bc963653586d.png)
![here](https://user-images.githubusercontent.com/40169350/41241920-7948ac8c-6d9e-11e8-8c36-fc1a7aadf4d7.png)


For some parks the problem is very local like this one. Here, the problem lies with one specific long stretch of path. When I turn on the 'blocked tiles' function with the debugging tools this is what I get: the tiles marked as blocked keep shifting and the peeps are all stuck on them while the world around them keeps moving. Using version 0.2.0 bcd4e9c as Liam is. 
![blocke](https://user-images.githubusercontent.com/40169350/41241683-e3d3275e-6d9d-11e8-8656-1fd4a034bf96.PNG)

**Comment by Gymnasiast** [comment] 2018-06-14 09:02
If I checkout fac0960c6e6b1c59273e18e34d301f7c1f59288e (the last commit in the wait-for-train PR) and compile it, the problem does not occur. So while #6998 was a likely suspect, it doesn't seem to be the actual cause of it.

**Closed** 2018-06-14 10:01 UTC
Labels: bug, investigate
