### ISSUE TITLE
Game is locked into saving track designs as "TD?"

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3145] opened 2016-03-18 17:57 UTC
Ever since I downloaded this newer version of OpenRCT2, every time I try to go save a track design, it attempts to save it as a TD? instead of a TD6. And if I do change it to TD6, it says it's an "invalid" file type.

**Comment by janisozaur** [comment] 2016-03-18 19:02
https://github.com/OpenRCT2/OpenRCT2/pull/3009

**Comment by Superjustinbros** [comment] 2016-03-18 19:06
I don't really see how this helps the problem.

**Comment by janisozaur** [comment] 2016-03-18 19:07
why don't you give 8b85030 a try?

**Comment by IntelOrca** [comment] 2016-03-18 19:12
Duplicate of #3112

**Closed by IntelOrca** 2016-03-18 19:12 UTC
Labels: duplicate
