### ISSUE TITLE
remove_unused_objects causing gfx glitch when game is paused

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#8538] opened 2018-12-29 21:28 UTC
Upon using "remove_unused_objects" when the game is paused, this graphical error appears:

![christmas valley 2018-12-29 22-24-21](https://user-images.githubusercontent.com/4934209/50542241-06a76600-0bb9-11e9-9fb4-dfc070a0a71d.jpg)

I've seen it with any park I've done this with. Not a big problem, but perhaps of interest to the devs.

**Comment by IntelOrca** [comment] 2018-12-29 21:39
Duplicate of #8493

**Closed by IntelOrca** 2018-12-29 21:39 UTC
