### ISSUE TITLE
Camera position resets on window resize

### ISSUE THREAD

**Issue by osconnoisseur** [OpenRCT2/OpenRCT2#2209] opened 2015-11-05 04:31 UTC
With the latest build at the time of writing (build 1404 on Windows), resizing the window resets the camera position to a specific spot. This didn't happen a few days ago. This bug may be related to #2200.

**Comment by PFCKrutonium** [comment] 2015-11-05 04:36
Confirmed.

**Comment by IntelOrca** [comment] 2015-11-05 08:30
Duplicate of #2200

**Closed by IntelOrca** 2015-11-05 08:30 UTC
Labels: duplicate
