### ISSUE TITLE
Saved games not loading

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#5168] opened 2017-02-03 23:18 UTC
**windows vista 32-bit**
**v0.0.7**
**build:3b02b05**

<in the latest build which was installed by my launcher today friday feb. 3 around 3 pm, i am completely unable to load any saved games. The game freezes or studders on a save game load and in a few seconds, goes back to the opening sequence menu screen.>

- [did not try]
- [did not try]

**Steps to reproduce:**
1. click "continue playing saved game" box; double click a save file and wait
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by IntelOrca** [comment] 2017-02-04 00:13
Duplicate of #5169

**Closed by IntelOrca** 2017-02-04 00:13 UTC
Labels: bug
