### ISSUE TITLE
Loading Map leads to graphic error

### ISSUE THREAD

**Issue by rcthorizons** [OpenRCT2/OpenRCT2#21637] opened 2024-03-19 11:06 UTC
### Operating System

macOS Monterey 12.0.1

### OpenRCT2 build

OpenRCT2, v0.4.9 (a172405 on HEAD)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

graphic error displays 'black' spaces where scenery is placed in game. This error does not happen on my Macbook Air 

### Steps to reproduce

- When loading the 'map' menu in OpenRCT, this leads to a graphical error on my Macbook.
- I can only solve it by closing and restarting the game (loading a new save game does not solve this). 

### Attachments

![Screenshot 2024-03-19 at 12 00 10](https://github.com/OpenRCT2/OpenRCT2/assets/130150409/2871c6a3-ea20-4b29-bdbf-844aba7ff7cc)
![Screenshot 2024-03-19 at 12 04 21](https://github.com/OpenRCT2/OpenRCT2/assets/130150409/6ddaf360-6959-4eeb-8df7-6be951894567)
![Image 19 03 24 at 12 03](https://github.com/OpenRCT2/OpenRCT2/assets/130150409/bc28ac75-26c6-48f6-b698-900a277501be)

**Comment by janisozaur** [comment] 2024-03-19 12:17
Which drawing engine do you use?

**Comment by rcthorizons** [comment] 2024-03-19 12:43
I use OpenGL; it doesn't happen in the other modes.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/130150409/a3241f49-3544-46a0-9e93-a9be33ef8185)

**Comment by 733737** [comment] 2024-03-19 13:28
why is multithreading turned off?

**Comment by rcthorizons** [comment] 2024-03-19 14:56
I'm not sure; I may have deselected it when experimenting with different settings. In any case; turning it back on does not solve the issue.

**Comment by AaronVanGeffen** [comment] 2024-05-07 13:02
I can't reproduce this error on my Macbook Pro (2022). Does this still happen on the current release?

**Comment by rcthorizons** [comment] 2024-07-28 21:45
Yes it still happens on current release OpenRCT2 v0.4.12-e24a77c develop. It must be something caused by my Macbook Pro 2016, as I can't reproduce it on my Macbook Air 2021.

**Comment by AaronVanGeffen** [comment] 2024-07-28 21:50
I think this is likely due to hardware/driver-specific differences in the OpenGL implementation. Does the problem go away if you switch to one of the software drawing engines?

**Comment by rcthorizons** [comment] 2024-07-28 21:51
Yes it does go away.

**Comment by AaronVanGeffen** [comment] 2024-07-28 22:14
Happy to hear it. Then I'm indeed going to blame the OpenGL drivers.

Unfortunately there's not much we can do about it without hardware to test on. Considering the age of the device, it's probably not worth the effort, anyway, especially if software rendering works fine.

Closing this issue, as it appears to be driver-related.

**Closed by AaronVanGeffen** 2024-07-28 22:14 UTC
Labels: bug
