### ISSUE TITLE
Multiplayer desync when choosing a ride with track designs

### ISSUE THREAD

**Issue by FlukiestEmperor** [OpenRCT2/OpenRCT2#2270] opened 2015-11-10 06:38 UTC
Multiplayer will desync when the server or a client selects a ride that brings up the track designs menu such as the wooden roller coaster or mini golf.

**Comment by duncanspumpkin** [comment] 2015-11-10 06:52
Duplicate of #2043

**Closed by duncanspumpkin** 2015-11-10 06:52 UTC
Labels: duplicate

**Comment by FlukiestEmperor** [comment] 2015-11-10 07:05
#2043 talks about designing your own roller coaster. This issue is about selecting a ride that brings up the premade track list, or is the paint issue what's causing that?

On rides that do not have premade tracks and go immediately into ride construction such as the Rhino or Ostrich roller coaster in Africa - Victoria Falls, it does not cause a desync.

**Comment by IntelOrca** [comment] 2015-11-10 08:15
Its actually a duplicate of #1895.

**Comment by IntelOrca** [comment] 2015-11-10 08:17
Kind of the same issue, the first discrepancy when building a ride is when it chooses a random colour. And this gets called for every track preview you hover over.
