### ISSUE TITLE
Crash when joining multiplayer server that has expansion packs

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#2281] opened 2015-11-10 22:27 UTC
If the server has expansion packs and you don't, the game crashes after loading all the objects.

It's possible this bug also applies to servers with custom scenery that does not have the "include add-on objects" selected, but I do not know how to run a server to test this.

**Comment by Gymnasiast** [comment] 2015-11-10 22:32
Duplicate of #2246. Please search before reporting

**Closed by Gymnasiast** 2015-11-10 22:32 UTC
