### ISSUE TITLE
Alternative colors doesn't show to other players in Multiplayer

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3962] opened 2016-07-01 10:38 UTC
**OS:** Win 7 
**Version:** 0.0.5
**Commit/Build:** 09863a4

When clients use alternative colors on a roller coaster, it only shows up on their client side, doesn't get changed for other players nor host, they will see it with just the main colors. Don't cause de-syncs either and it isn't because of de-sync. 
The client see different colors, everyone else the main color

- [x] Multiplayer?

**Steps to reproduce:**
1. Start a host server
2. Join with a client
3. Let the client use alternative colors on a coaster
4. See how it doesn't sync up with the host
5. When the client disconnects and re-join, it's back to original colors

**Note:** This is not thanks to de-sync as even if you're synced, it doesn't change the alternative colors and you don't get desynced because of it 

**Screenshots / Video:**
![colors](https://cloud.githubusercontent.com/assets/17282384/16519359/a4ecc7ce-3f88-11e6-9083-feeac0f6a7e0.png)

**Comment by janisozaur** [comment] 2016-07-01 10:43
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3832

**Comment by Nubbie** [comment] 2016-07-01 10:44
wow, so there was, couldn't find one :s

**Closed by janisozaur** 2016-07-01 10:43 UTC
