### ISSUE TITLE
Construction rights on entrance path

### ISSUE THREAD

**Issue by runelaenen** [OpenRCT2/OpenRCT2#1461] opened 2015-06-24 18:27 UTC
Hello. I've run across a bug where if I try to set construction rights as owned/purchasable over the path leading to the park entrance, they become unset when you move on to the next step, and ultimately, are not saved with the scenario.

Actually, this bug occurred in the original RCT2 as well. I was quite an avid scenario designer back in the day, and this always annoyed me. Yet it seems like so few people know about it - I've run across a number of custom scenarios where the designer didn't notice this happening.

Thanks.

Posted by WhiteRakogis
https://openrct.net/forum/topic/80/scenario-editor---construction-rights-on-entrance-path

**Comment by Gymnasiast** [comment] 2015-06-24 18:36
Duplicate of #441

**Closed** 2016-04-20 17:39 UTC
Labels: duplicate
