### ISSUE TITLE
Crash when saving very (very!) large track designs

### ISSUE THREAD

**Issue by rwjuk** [OpenRCT2/OpenRCT2#5838] opened 2017-07-08 14:41 UTC
See [this report](https://www.reddit.com/r/openrct2/comments/6lu70l/orct2_crashes_when_trying_to_save_an_enormous/).

Crash in `track_design_save.c - track_design_save_to_td6_for_tracked_ride()`, L1038 when `realloc()`ing memory for the track elements. The track design in question contains 130540 elements, which I believe is far above the limit for TD6.

We should display some sensible error message in this case rather than just crashing.

[SV6 containing a test case](https://github.com/OpenRCT2/OpenRCT2/files/1133019/The.Longest.Coaster.Ever.zip)

**Comment by Chaosmeister** [comment] 2017-11-22 22:13
I'm unable to reproduce the crash.  
I could save the file without a problem on current develop (ef65a520)

**Comment by IntelOrca** [comment] 2017-11-22 22:26
@Chaosmeister what happens if you place the track design?

**Comment by Gymnasiast** [comment] 2017-11-30 22:26
Fixed in  1332004.

**Closed by Gymnasiast** 2017-11-30 22:26 UTC
Labels: bug, crash
