### ISSUE TITLE
Can't Re-edit Rides.

### ISSUE THREAD

**Issue by GravityUnown** [OpenRCT2/OpenRCT2#3069] opened 2016-03-02 04:33 UTC
Mac OS X 10.10.5
0.0.4.0-rct1-import build e76c7c7

Either during or after I finish building a design for a ride I cannot go back and edit it. The construction button does not work, and I cannot even right click on part of the ride to edit the track.

- [ ] Original bug?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Make a coaster or some custom design.
2. Try to construct ride while closed

**UPDATE:** It seems like I can still edit old rides, but for rides that I made within the past day or so I cannot edit at all.

**Comment by Overv** [comment] 2016-03-02 17:18
I can't reproduce this on Windows with the latest build, `aac0430`. I'm also confused by the check next to "Original bug". Could you record a video?

**Comment by Gymnasiast** [comment] 2016-03-02 20:25
You should not be using the rct1-import branch (it's a branch because the feature is not finished yet). Where did you get that build from?

**Comment by IntelOrca** [comment] 2016-03-02 21:43
@Gymnasiast all branches on the main repo are available: https://openrct2.org/downloads

**Comment by Gymnasiast** [comment] 2016-03-02 22:38
@IntelOrca : I see. I'd say only develop and master should be available.

**Comment by GravityUnown** [comment] 2016-03-02 22:50
I'm sorry, I just literally download whichever the latest developer Mac build for that day is on the downloads page. I'm also unable to record a video, but all that happens is that I try to hit the construction button on my desired ride, and nothing happens, it doesn't take me to the track editing window.

Also even after trying out the most recent mac build as of this post (0.0.4.0-develop build 846d72c, updated 3 hours ago), I still have this problem with my newer rides. This is pretty frustrating because this means until I can figure out what's going on I have to get all of my coasters perfect on the first try otherwise I have to start from scratch again.

**Comment by janisozaur** [comment] 2016-03-02 22:51
@Gymnasiast I'm of the opposite opinion. I'd rather provide all the branches in this repository, so people who know what they're doing can check our work in progress. The build in question was most probably served by launcher, which I believe should only server develop or master (perhaps also other, manually entered branches as well, but that's a different topic).

See https://openrct2.org/forums/topic/959-unable-to-save-games-as-sv6/#comment-4037

**Comment by GravityUnown** [comment] 2016-03-02 23:02
This might be a foolish question, but does this problem have anything to do with the size of my park? I've been trying to fill out nearly every inch of the "make your own Six Flags park" map and after a while I just haven't been able to edit any of the recent rides. I can still edit rides when I start a new game, I can still edit rides in other save files, and I can even edit old rides in the particular save file that I'm experiencing this bug in.

**Comment by IntelOrca** [comment] 2016-03-02 23:44
@Gymnasiast those builds allow easy user testing of any branch. Unfortunately the branch selection is not very intuitive on the site. I can't actually find a way of viewing all the available builds - just the last several regardless of branch. Not sure what the launchers do.

**Comment by IntelOrca** [comment] 2016-03-02 23:46
@GravityUnown please provide a save file to we can investigate.

**Comment by GravityUnown** [comment] 2016-03-02 23:51
@IntelOrca Is there a way to send the save file privately? Just curious to know.

**Comment by IntelOrca** [comment] 2016-03-03 00:00
@GravityUnown you can e-mail to me if you want, but usually its just better to upload here in a zip... unless you really don't want other people to see your park.

**Comment by GravityUnown** [comment] 2016-03-03 00:09
I'll try the e-mail. You're right, I really don't want others to see my park until it's fully completed, heh.
I've just sent an e-mail to you. Thank you for the help.

**Comment by IntelOrca** [comment] 2016-03-03 00:18
@GravityUnown thanks, it should be fixed now in the next build

**Closed** 2016-03-03 00:18 UTC
Labels: investigate

**Comment by GravityUnown** [comment] 2016-03-03 00:23
@IntelOrca Wonderful, thank you so much. Will that be the next stable, presumably from one of the notes here? Or will it possibly be fixed in one of the develop builds? I apologize, I don't know much of the ins and outs of RCT.

**Comment by IntelOrca** [comment] 2016-03-03 00:25
There will soon be a develop build, e4372cca5e0e26f3f6162303d746dd15e215e7de which will have the fix in, and any version beyond that.

https://openrct2.org/downloads shows that the version is now available for Windows, other platforms take longer, because Travis seems to be slower than AppVeyor.

**Comment by GravityUnown** [comment] 2016-03-03 00:27
Alright, sounds like a plan. Once again thank you so much for the help. I will keep an eye out for when that build comes out on other platforms.

**Comment by GravityUnown** [comment] 2016-03-03 01:56
I just tried out the updated build and I can edit my rides again! Very well done on the efficient bug fixing.
