### ISSUE TITLE
Game crashes when clicking "Specials..." after building powered staright track on looping coaster

### ISSUE THREAD

**Issue by ALEEF02** [OpenRCT2/OpenRCT2#5372] opened 2017-04-16 05:39 UTC
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 4a97d53

When building a looping rollercoaster on multiplayer, the game **sometimes** crashes when pressing "specials..." after building a chained straight piece. Sometimes it never happens, sometimes pressing it a few times, and sometimes pressing it once.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Open OpenRCT2
2. Go onto a server
3. start a looping coaster
4. build a powered straight track
5. Press "specials..." a few or so times
6. Crash

**Dump file**

Dump file failed

**Screenshots / Video:**

https://vid.me/k6sd

**Save game:**

It said zips aren't supported

[bugged.txt](https://github.com/OpenRCT2/OpenRCT2/files/924105/bugged.txt)

**Comment by ALEEF02** [comment] 2017-04-16 07:16
In the title I mean chained straight track, not powered

**Comment by ALEEF02** [comment] 2017-04-16 07:43
Edit: this also sometimes occurs with chained banked pieces

**Comment by duncanspumpkin** [comment] 2017-04-16 13:02
I've tried for a while but i can't reproduce this. Are there any more steps you could give to reproduce?

**Comment by rwjuk** [comment] 2017-04-16 13:22
Have also tried and been unable to reproduce on the latest build.

**Comment by ALEEF02** [comment] 2017-04-16 14:43
No, those are the only steps it takes me. You can see that in the video. It doesn't happen very often, but when it does, it's very annoying

**Comment by janisozaur** [comment] 2017-04-16 20:20
On that very same version, I cannot reproduce it either; multiplayer or not.

@ALEEF02 If your client crashes sort-of reliably, you can create dump manually from task manager.

Can you also post your `g2.dat`? It will be somewhere in openrct2's files, in a directory called `data/`.

**Comment by ALEEF02** [comment] 2017-04-16 20:47
A) how do i make a dump from the task mgr?
B) I will send that file when I get home

**Comment by janisozaur** [comment] 2017-04-16 21:21
> how do i make a dump from the task mgr?

@IntelOrca

**Comment by ALEEF02** [comment] 2017-04-17 03:28
g2.dat:
[g2.txt](https://github.com/OpenRCT2/OpenRCT2/files/924863/g2.txt)

**Comment by janisozaur** [comment] 2017-04-17 09:24
That g2 file looks correct. I have no other clue what could it be then. Our only chance is if we get provided with a manually created dump.

@ALEEF02 induce a crash, then when the error message pops up, don't close it, but follow these steps: https://support.kaspersky.com/us/general/dumps/1419

**Comment by ALEEF02** [comment] 2017-04-17 20:12
Ok, I'll do that tonight @janisozaur

**Comment by janisozaur** [comment] 2017-04-23 18:28
@ALEEF02 ping

**Comment by ALEEF02** [comment] 2017-04-23 21:48
@janisozaur sorry, ive had family in town the past week and have been busy. Expect the dump by tonight

**Comment by ALEEF02** [comment] 2017-04-25 00:13
@janisozaur It seems like I can't do the crash again

**Comment by janisozaur** [comment] 2017-04-25 05:06
make sure you are still on https://github.com/OpenRCT2/OpenRCT2/commit/4a97d53c0ad6284c8ab94bf382c021a7e254bacf

**Comment by ALEEF02** [comment] 2017-04-25 15:14
I have the launcher, and I don't know how to switch versions

**Comment by janisozaur** [comment] 2017-04-26 08:17
You can grab individual builds from https://openrct2.org/downloads

**Comment by janisozaur** [comment] 2017-05-02 18:02
@ALEEF02 you are the only one having this issue and we would like to try fixing it before next release, but we need the dump to have any idea what's going wrong.

Can you please provide it, as none of our testing was able to reproduce that. Otherwise we will have to postpone this.

**Comment by ALEEF02** [comment] 2017-05-04 23:07
@janisozaur if this is only happening to me, it's probably just my computer.

**Comment by rwjuk** [comment] 2017-05-23 22:08
Was anybody other than @ALEEF02 able to reproduce this?

**Comment by janisozaur** [comment] 2017-07-05 06:31
I was not able to reproduce it back then and I couldn't just now.

**Comment by Chaosmeister** [comment] 2017-07-31 20:39
I'm unable to reproduce the crash as well

**Comment by Gymnasiast** [comment] 2018-01-12 11:44
I'm going to close this because it appear to have gone away.

However, @ALEEF02 , if this issue persists please say so and we'll reopen it.

**Closed by Gymnasiast** 2018-01-12 11:44 UTC
Labels: crash, investigate
