### ISSUE TITLE
Roto drop built on top of another without top piece can crash the bottom roto drop

### ISSUE THREAD

**Issue by erikhuizinga** [OpenRCT2/OpenRCT2#17481] opened 2022-07-01 08:50 UTC
### Operating System

MarcelvOS

### OpenRCT2 build

?

### Describe the issue

See this Marcel Vos video at around this time: https://youtu.be/in1FVEV5bww?t=530, where the bug is reproduced and described.

The suggestion is to customise the 'topless' roto drop behaviour so that it always operates like a standalone topless roto drop, regardless of surrounding rides. I.e.: the vehicle stays at the bottom. As suggested by Marcel, this might be due to the bottom roto drop detecting a (ghost) top piece from another roto drop being built above itself. If that is the cause of the bug, then it should not detect pieces that aren't part of its own ride.

### Steps to reproduce

1. Build a roto drop without a top piece and open it.
2. Build a roto drop exactly on top of it and have the build ghost of the top piece showing.
3. Wait until the bottom roto drop starts riding.
4. Get rid of the ghost top piece.
5. The bottom roto drop will crash or start crashing permanently.

**Comment by duncanspumpkin** [comment] 2022-07-01 10:09
Looks like a missing ghost check. (Also a missing ride id check but that is required for track merging)

**Comment by Gymnasiast** [comment] 2022-07-01 13:30
I think adding a ride id check wouldn’t hurt either - otherwise, wouldn’t this bug also occur with non-ghost top pieces that are not the bottom rides’ own? And tower rides are not used in track merging anyway.

**Comment by Broxzier** [comment] 2022-07-01 13:40
As I understand it, the issue is caused by the ghost piece only being there for a moment. The ghost piece disappears when closing the ride construction window, but in the meantime the roto drop vehicle could've moved up higher than what it would consider the top of the ride. That explains why it seems to happen randomly in Marcel's video.

Omitting the ride index check should be keep implicit support for merged roto drop towers.

**Comment by duncanspumpkin** [comment] 2022-07-01 13:41
> I think adding a ride id check wouldn’t hurt either - otherwise, wouldn’t this bug also occur with non-ghost top pieces that are not the bottom rides’ own? And tower rides are not used in track merging anyway.

I am never sure what things nowadays are being abused so I would err on the side of caution and only do the ghost check.

**Comment by Gymnasiast** [comment] 2022-07-01 15:02
Exactly as I suspected, ghost status has nothing to do with it:

![afbeelding](https://user-images.githubusercontent.com/1478678/176919901-9f1b4899-4d3c-48c1-b09f-c2c4fce3897f.png)

Roto-drop 1 is the bottom one, yet its car worked its way through the station of Roto-drop 2 and got stuck there.

**Comment by Broxzier** [comment] 2022-07-01 15:06
> It doesn’t make sense for it to _only_ happen if it’s a ghost piece. Nevertheless, I will do an experiment to check.

That's not what I'm saying, I'm saying that the the top piece (which happens to be a ghost) was there for a moment because of the ride construction.

I suspect that in your example, it gets stuck instead of crashing.

**Comment by Gymnasiast** [comment] 2022-07-01 15:14
Yeah, I guess that’s what caused Marcel’s issue.

Anyway, the point is that ghost status is not really the cause here, it’s the missing ride id check, and we cannot fix it without theoretically affected merged tower rides, although I doubt if 1) those even exist, and 2) they will even break.

**Comment by Gymnasiast** [comment] 2022-07-01 15:21
Ok, just for shits and giggles, I tried merging tower rides. This does not seem to work:

![afbeelding](https://user-images.githubusercontent.com/1478678/176923010-be128d66-4f03-414c-8438-7365a6177544.png)

It just gets stuck at the top piece. When I switch the two around, it does go all the way to the top, but _then_ it crashes.

**Comment by karst** [comment] 2022-07-01 17:08
Does this bug occur on space shots set to freefall mode aswell?

**Closed** 2022-07-02 10:27 UTC
Labels: bug, good first issue
