### ISSUE TITLE
River Rapids boats overlap on lift hill

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#19088] opened 2023-01-08 17:32 UTC
### Operating System

Ubuntu Linux 20.04.5

### OpenRCT2 build

18d9e72 develop, AppImage

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Since the speed a boat goes up a River Rapids lift hill depends on its load, lighter boats can catch up to heavier ones if there is enough lift length on a given track.

This leads to overlapping boats, often quite badly so:

![overlapping_river_rapids_boats_1](https://user-images.githubusercontent.com/29800630/211210159-59c4a0d9-e486-4955-b394-13c4e1903c93.png)

![overlapping_river_rapids_boats_2](https://user-images.githubusercontent.com/29800630/211210202-75a3b666-88b9-4272-a9d3-e46915c1b7e6.png)

### Steps to reproduce

- Build RiverRapids with – in sum – a long lift hill length
- Have _differently loaded_ boats follow each other with little waiting time
- Boats start to overlap as soon as they catch up to each other

example park attached

### Attachments

[overlapping_river_rapids_boats.zip](https://github.com/OpenRCT2/OpenRCT2/files/10369049/overlapping_river_rapids_boats.zip)

**Comment by rik-smeets** [comment] 2023-03-11 10:45
Closed as duplicate of #2153.

**Closed by rik-smeets** 2023-03-11 10:45 UTC
Labels: original bug
