### ISSUE TITLE
Game does not save setting "Show 'real' names of guests"

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#5576] opened 2017-06-10 04:49 UTC
**OS:** Arch
**Version:** 0.0.8
**Commit/Build:** 5c5389

Game does not save setting "Show 'real' names of guests"
(Options -> Wrench)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Comment by rwjuk** [comment] 2017-06-11 12:55
Duplicate of #3187, this is a technical restriction for now as the setting is saved in the SV6, rather than global options. I'd like to see an "override real names setting of saved games" option however, so I'll leave this open.

**Comment by IntelOrca** [comment] 2017-06-11 13:25
@rwjuk This can be done now if you like. Just simply ignore the setting within the SV6 and always use our own one.

**Closed** 2017-06-12 12:05 UTC
Labels: enhancement
