### ISSUE TITLE
Water/Underwater Textures appear differently

### ISSUE THREAD

**Issue by ArcticX9** [OpenRCT2/OpenRCT2#5416] opened 2017-04-30 17:14 UTC
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 1ab90d8

Following a recent update, the water sprites and anything underwater has appeared differently. I have heard that it is potentially an error, and am reporting it here for visibility.

**Screenshots / Video:**
Before
![inselfieber 2017-01-26 15-59-51](https://cloud.githubusercontent.com/assets/20503645/25566453/7d011fee-2d9e-11e7-8b65-f2b56ab65a8c.png)

After
![inselfieber 2017-04-30 12-05-40](https://cloud.githubusercontent.com/assets/20503645/25566454/7f13c84a-2d9e-11e7-94f1-8d4924a0d034.png)

**Comment by Liampie** [comment] 2017-04-30 17:59
Another error in both screens: the black supports under the barrels are not supposed to be there. It's an OpenRCT byproduct that surfaces in many pre-OpenRCT parks.

**Comment by xp4xbox** [comment] 2017-04-30 18:19
@Liampie are you sure its openrct2 only, because many custom objects draw supports under them.

**Comment by janisozaur** [comment] 2017-04-30 18:23
Most likely a regression from recently merged https://github.com/OpenRCT2/OpenRCT2/pull/5396. @ArcticX9 can you verify?

@ArcticX9 @Liampie it would be much more useful if your screenshots had matching viewports. Can you update them to such state and provide a highlighted version of the differences?

@camthesaxman can you look into that?

**Comment by IntelOrca** [comment] 2017-04-30 19:08
The commit that caused this (fde3c8a3ed30b91e3c5056a1a37905a5689abdd9) has been reverted now.

**Closed** 2017-04-30 19:07 UTC
Labels: bug

**Comment by camthesaxman** [comment] 2017-05-02 02:03
Yeah, I messed something up. I'll take a look at it soon.
