### ISSUE TITLE
Multi-dimensional, Flying, and Lay-down coasters crash as soon as they go into the inverted state

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6689] opened 2017-11-17 18:43 UTC
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 8ffe7d5

These three coasters can all go both inverted and non-inverted, but whenever they go into the inverted mode they crash. For the flying coaster this means that it crashes right out of the station because it starts in inverted mode. Happens for the first time in 9a40219.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/25930360/32963132-43fdbc82-cbcf-11e7-8b21-c104e4ae3136.png)

**Comment by LordMarcel** [comment] 2017-11-17 18:50
Also, my game crashes whenever I put the prebuilt multi-dimensional coaster X into testing mode and there aren't yet trains on the track. This doesn't happen with other multi-dimensional coasters.

**Comment by Gymnasiast** [comment] 2017-11-17 22:12
Most likely caused by this: https://github.com/OpenRCT2/OpenRCT2/pull/6668/files#diff-d6e06f15170b4fae7c1d6ddf1c9e1e01R2548

Basically, it used to xor (either a, or b, not both), but I changed it to and by accident.

**Comment by Patrik356b** [comment] 2017-11-17 22:15
On same build, I get the following results: 
Flying coaster train never leaves the station
Any custom Multi-Dimension Coaster will work, but not existing designs (hangs my game)

**Comment by Gymnasiast** [comment] 2017-11-17 22:24
Fixed in 8027af56b6074d8456f5e0af538c41af11efe7a5.

**Closed by Gymnasiast** 2017-11-17 22:24 UTC
