### ISSUE TITLE
"Enable lighting effect" option cannot be disabled without day/night cycling enabled

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/OpenRCT2#5289] opened 2017-03-09 07:09 UTC
**OS:** macOS 10.12
**Version:** 0.0.7
**Commit/Build:** 76c154a

disable day/night cycling option without disabling "Enable lighting effect" option can cause unchangeable lighting effect option.(and weird graphic glitch) this is because enable lighting effect option applies seperately although it is sub option of "day/night cycling".

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Enabe day/night cycling option
2. Enable lighting effect
3. Disable day/night cycling option without disabling lighting effect
4. lighting effect option is cannot be changed and effect is always applied(although there will be no "lighting effect" because there will be no night, weird graphic glitches can occur)

**Comment by andoruB** [comment] 2017-03-09 12:39
I can also reproduce this behaviour. Same commit/build, on Debian Sid.

**Comment by duncanspumpkin** [comment] 2017-03-09 19:46
Duplicate of #5178

**Closed by duncanspumpkin** 2017-03-09 19:46 UTC
