### ISSUE TITLE
Land purchase not possible when No money flag is set

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7461] opened 2018-04-29 00:47 UTC
**Version:** [0.1.3]
**Commit/Build:** [2ef549b]

If the No Money flag is set, land purchase gets disabled. Since we can now set the no money flag in scenarios which have purchasable land using the cheat menu, I think land purchase should be enabled (and free).

**Comment by Broxzier** [comment] 2018-04-29 00:54
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/2674

**Closed by Broxzier** 2018-04-29 00:54 UTC
