### ISSUE TITLE
AI prefers single-wide path over much faster double-wide path

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#3423] opened 2016-04-25 13:24 UTC
**OS:** win10
**Version:** 0.0.5 develop
**Commit:** 4149bcd

The mechanic heading for the ride on the left takes the much slower single-wide path instead of the path heading straight to it. Changing the faster path to be one tile wide fixes the issue, as well as making the slow path 2 tiles wide.
![scr92](https://cloud.githubusercontent.com/assets/13868449/14784412/e1e55d3e-0af5-11e6-8116-011d447b8dd4.png)
I have not tested it in vanilla as my installation seems to be broken.

Steps to reproduce:
1. Open the save
2. Put the mechanic in the top-right corner
3. Make sure the ride breaks down
4. Watch the mechanic take a long walk

[Pathfinding test.zip](https://github.com/OpenRCT2/OpenRCT2/files/234619/Pathfinding.test.zip)

What could have been a 2 day walk, took this mechanic three full in-game months (15 minutes) (and he even gave up four times doing so). Making the path go back beyond where the mechanic started seems to prevent this too.
![scr94](https://cloud.githubusercontent.com/assets/13868449/14785797/b74d2488-0afc-11e6-9b8a-f364107e406a.png)

**Comment by AaronVanGeffen** [comment] 2016-04-25 14:06
I presume this has the same behaviour as the original game, right? No improvements have been made yet with regards to AI pathfinding.

**Comment by jensj12** [comment] 2016-04-25 14:13
There may have been made some mistakes while decompiling, #2499 is a good example peep AI being worse than in vanilla. If you'd ask me, I'd say wide paths are the root of most (if not all) pathfinding issues. I've seen inefficient mechanic behaviour in the latest forum group park (even taking a single-wide path which doesn't lead to it instead of a straight triple-wide route) so I tried to illustrate it in an empty park.

**Comment by janisozaur** [comment] 2016-04-25 14:16
These could make for a valid test cases for peep AI, if someone could verify results consistently *differ* from vanilla. Also, keep in mind staff AI would be somewhat different from peep AI.

**Comment by jensj12** [comment] 2016-04-25 14:27
Here's an even better example of bad staff AI:
![scr95](https://cloud.githubusercontent.com/assets/13868449/14786866/26fcca6e-0b01-11e6-986e-f25dd2872bf4.png)
The single-wide path the mehcanic chooses does not lead to the ride while the triple-wide path is ignored. Same thing happens with peeps:
![scr97](https://cloud.githubusercontent.com/assets/13868449/14787109/534a552c-0b02-11e6-9da2-eadb8605beaa.png)
![scr98](https://cloud.githubusercontent.com/assets/13868449/14787170/919883f8-0b02-11e6-81a9-716a551c0acb.png)

Here's the new save [Pathfinding test.zip](https://github.com/OpenRCT2/OpenRCT2/files/234728/Pathfinding.test.zip)

**Comment by janisozaur** [comment] 2016-04-25 14:30
One thing all your designs share in common is there's always a bad-left-turn and forward-correct paths. Can you test similar things happen if you mirror those designs around the wide path axis?

**Comment by jensj12** [comment] 2016-04-25 14:34
That was completely unintentional. The same thing happens on a bad-right-hand turn, both guests and staff.

**Comment by duncanspumpkin** [comment] 2016-04-25 14:49
Okay that definitely looks like a bug. Thanks for the extensive testing should make it easier to work out where the issue is

**Comment by jensj12** [comment] 2016-04-27 16:36
Did some more testing: it breaks as soon as the faster path has 8 or more intersections (and the slower path has at most 7). If the intersections are all next to each other (which is the case for wide paths, but the same happens with T-intersections left-right-left-right), it breaks as soon as there are 14 consecutive intersections. If both paths have 9 intersections, it takes the path where the 9th intersection is the closest to it's destination (the locations of the other 8 don't matter). If I move the highlighted brown path one tile to the top-left the mechanic takes the faster path.
![scr99](https://cloud.githubusercontent.com/assets/13868449/14859601/29e09472-0ca5-11e6-825b-dcd20db82bc6.png)

This means the basic peep AI is as follows (without taking history into account): peeps look 9 intersections forward, if their destination hasn't passed by in the pathfinding algorithm, peeps take the route to the closest tile. The lenght of the route only seems to matter if a path tile can be reached in from two sides (both with less than 8 intersections in between).

**Comment by duncanspumpkin** [comment] 2016-04-27 17:51
So I spent a good while trying to work out what went wrong only to find out this is an original ai issue.

**Comment by jensj12** [comment] 2016-04-27 21:43
I thought RCT2 fixed the issue of double-wide paths killing the pathfinding AI like in RCT1 (where even an 80x80 scenario would suffer greatly from it), turns out it is *only* half as bad now. I hope this helps to improve the AI.

**Comment by Wirlie** [comment] 2016-04-28 20:20
@jensj12 okay, the explanation of the comment https://github.com/OpenRCT2/OpenRCT2/issues/3423#issuecomment-215141526 explains my problem, but... the title of your issue do not say much about this... this is the reason of that I could not see that my problem already been reported in your issue. (I don't know if I said it correctly).

**Comment by jensj12** [comment] 2016-04-28 21:40
@Wirlie I can't get all visible cases in one title. To me the wide paths are more of an issue than your park, though their root cause is the same. Fixing this might also fix yours (you'll never know :P ).
I'll give a shot at understanding and hopefully fixing some of the pathfinding (will take a while).

**Comment by duncanspumpkin** [comment] 2016-08-22 05:47
Fixed in #4221

**Closed by duncanspumpkin** 2016-08-22 05:47 UTC
Labels: original bug
