### ISSUE TITLE
Forcing uppercase for banners causes glitching

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2762] opened 2016-01-17 22:24 UTC
The entrances appear to be fine, but the banners over a path seem to be using the regular width to determine the number of frames needed. Causing the animation to reset too early.

**Comment by Gymnasiast** [comment] 2016-01-17 22:44
Note: @IntelOrca attempted to fix it some months ago, which slightly decreased the problem.

**Comment by IntelOrca** [comment] 2016-01-17 22:56
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/2238

**Closed by IntelOrca** 2016-01-17 22:56 UTC
