### ISSUE TITLE
Vehicle speed underflows when going backward only in openRCT2

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#8507] opened 2018-12-20 23:08 UTC
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** c457d1

When going forward there is a minimum speed of 1 km/h in all versions of the game. However, when going backward there is a minimum speed of 0 km/h in classic and vanilla, but in OpenRCT2 it will underflow to the minimum forward speed. Here are two examples:

Vanilla/Classic: https://www.youtube.com/watch?v=No22AJ7thXE

OpenRCT2: https://www.youtube.com/watch?v=HjKEKkZI3ZA

This has been in openrct2 since at least late 2016, which is when I first encountered it. For a long time I thought it a thing in vanilla as well but today someone found out it is not.

**Comment by harrysbird** [comment] 2018-12-28 19:40
This first project of openrct2 maded in 2014 not 2016

**Comment by duncanspumpkin** [comment] 2019-02-07 08:08
This will be due to replacing some arithmetic shifts with divides

**Comment by bdupree5** [comment] 2019-04-05 16:25
I would like to take a look at this any ideas where to start looking in the code?

**Comment by duncanspumpkin** [comment] 2019-04-05 17:05
@bdupree5 it will be very difficult to find where the problem is. Its to do with how the acceleration works at slow values. The code is very messy for this. vehicle.cpp is where the code resides.

**Comment by bdupree5** [comment] 2019-04-06 02:27
Ill take your word for it. I don't really want to deal with messy code lol

**Comment by w-flo** [comment] 2019-04-26 18:46
I believe I found a fix for this. The negative velocity goes up from e.g. -6000 at an acceleration of 1 until it hits -4096, then the "magical implicit forward creeping boosters" kick in to speed up the train to +32k (~1km/h) even though they shouldn't while the train is moving backwards. I can send a simple PR next week that will keep the negative speed at -4095 (about 12.5% of the forward creeping speed) that should probably mirror the RCT2 behavior.

**Closed** 2019-05-02 20:32 UTC
Labels: bug
