### ISSUE TITLE
BACKTRACE 263ffa surface_paint -> sub_68B3FB -> paint_session_generate

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8386] opened 2018-12-07 22:22 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/263ffaed8515a08c982dca6c60e817b72a9b2cdb25b067e5aea771afb48a5151?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Dec 07 2018 22:21:43)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Gene\\Documents\\OpenRCT2\\6744ecd4-12f1-41c9-bc03-d857bf99a60e.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Gene\\Documents\\OpenRCT2\\6744ecd4-12f1-41c9-bc03-d857bf99a60e.sv6.gz: <em>1</em><br><strong>commit:</strong> dc7d141: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>surface_paint -> sub_68B3FB -> paint_session_generate -> window_main_paint -> window_draw_single -> window_draw -> window_draw_all -> OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks -> OpenRCT2::Drawing::X8DrawingEngine::PaintWindows -> OpenRCT2::Paint::Painter::Paint -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 20:01
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8387

**Closed by janisozaur** 2019-02-02 20:01 UTC
Labels: backtrace.io, crash
