### ISSUE TITLE
Crash on Winning

### ISSUE THREAD

**Issue by skquisenberry** [OpenRCT2/OpenRCT2#7973] opened 2018-09-06 01:57 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.1]
**Commit/Build:** [e.g. a1fd033]

I was playing Crazy Castle on multiplayer and the game crashed immediately upon winning.
Auto-detect completion was turned on

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1.  Win crazy castle? Maybe, who knows
2. 

**Dump file**

[8e804b6e-e085-45f3-8625-129e0d1fb68b(a1fd033_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/2355174/8e804b6e-e085-45f3-8625-129e0d1fb68b.a1fd033_x86-64.zip)

**Screenshots / Video:**

**Save game:**

[Crazy_Castle_multi.txt](https://github.com/OpenRCT2/OpenRCT2/files/2355175/Crazy_Castle_multi.txt)

**Comment by Gymnasiast** [comment] 2021-07-26 19:45
Template is not filled in correctly, there are no specific steps to reproduce and it has been three years since it was reported. For those reason, I’ll have to close this.

**Closed by Gymnasiast** 2021-07-26 19:45 UTC
Labels: crash, investigate
