### ISSUE TITLE
Entrance shows dashed lines.

### ISSUE THREAD

**Issue by Duvelthehobbit** [OpenRCT2/OpenRCT2#11470] opened 2020-04-26 10:37 UTC
**OS:** Windows 10
**Version:** 0.2.6-176
**Commit/Build:** a3e7f09
Upon placing entrance, the entrance sign on the building shows only dashed lines. This happens immediately after placing the entrance of the ride, or placing a prebuilt ride. Rides already built have the same issue. The issue persists after loading the game. The sign above the queue is unaffected and either shows ride name or closed. Video shows new park, saved game of same park, and new park with existing rides.

**Steps to reproduce:**
1. Open new park _or_ load park from save
2. Place ride
3. Place entrance
4. Entrance shows dashed lines. 

**Screenshots / Video:**
https://youtu.be/d550Plh1sKA

**Comment by tupaschoal** [comment] 2020-04-26 12:15
Duplicate of #11469

**Closed by tupaschoal** 2020-04-26 12:15 UTC
