### ISSUE TITLE
Red warning message disappears very quickly making it illegible

### ISSUE THREAD

**Issue by RCThijs** [OpenRCT2/OpenRCT2#21208] opened 2024-01-16 20:58 UTC
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.7-42-g717682a (717682a on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

The red warning box (e.g. when placing a ride outside of the park) disappears so quickly that it is nearly impossible to read.

### Steps to reproduce

Open a random park
Do something that triggers a warning (build ride without money, place ride outside of park etc.)
The red warning box appears and disappears almost instantly

**Comment by astraylife1** [comment] 2024-02-09 21:04
Same thing happens to me in MacOS

**Comment by ZehMatt** [comment] 2024-02-10 14:13
I just checked, error messages will stay for exactly 6 seconds, we could raise it to 12 which is double the time then.

**Comment by ocalhoun6** [comment] 2024-02-10 18:22
I don't think the delay time is what the original bug report here was about. 6 seconds is reasonable.

Honestly, I suspect this is a duplicate of another bug report where error messages didn't stay for 6 seconds -- they stayed for exactly 1 frame. The way they mention it disappearing "almost instantly" makes me think they're talking about the 1-frame bug, not 6 seconds.

**Comment by ZehMatt** [comment] 2024-02-10 23:47
> I don't think the delay time is what the original bug report here was about. 6 seconds is reasonable.
> 
> Honestly, I suspect this is a duplicate of another bug report where error messages didn't stay for 6 seconds -- they stayed for exactly 1 frame. The way they mention it disappearing "almost instantly" makes me think they're talking about the 1-frame bug, not 6 seconds.

Well I did exactly what the reproduction step says and it doesn't disappear immediately so I'm not sure how to trigger this bug if it even is a bug, maybe there are some plugins that mess with this, can't really look into it if I don't know how to reproduce the problem.

**Comment by ocalhoun6** [comment] 2024-02-11 01:08
Yeah, might possibly be plugin-related.

Or might only happen for a specific drawing method, or even only on a specific OS. Or, possibly that bug has already been fixed and the one who reported it is using an older version?

**Comment by RCThijs** [comment] 2024-02-11 06:02
Thanks for looking into the issue! The last update didn’t solve the problem. As stated above, it indeed looks like the message stays for one frame. I will try to uninstall my plugins and see if that resolves the issue.

**Closed** 2024-02-13 19:03 UTC
Labels: bug
