### ISSUE TITLE
Crash In Multiplayer

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3515] opened 2016-05-07 16:37 UTC
**OS:** Windows 10
**Version:** 0.0.5

**Dump file**

[dumpfiles.zip](https://github.com/OpenRCT2/OpenRCT2/files/253488/dumpfiles.zip)

**Comment by janisozaur** [comment] 2016-05-07 16:56
You have not provided build ID.

**Comment by chrismilne300** [comment] 2016-05-07 16:59
@janisozaur Sorry build 355b163

**Comment by janisozaur** [comment] 2016-06-03 11:19
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3193

**Closed by janisozaur** 2016-06-03 11:19 UTC
Labels: crash, investigate, multiplayer
