### ISSUE TITLE
Ride name number randomly changed every frame for a few seconds

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#10630] opened 2020-01-28 22:06 UTC
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 550da84

I was messing around with copying stations via the tile inspector and suddenly the number in the name of my standup coaster randomly changed every frame to what seems a number between -32767 and 32767 for a few seconds: https://www.youtube.com/watch?v=nd2AQo7QMks. 

I have no idea what triggered it or how to reproduce it.

**Comment by James103** [comment] 2020-01-28 22:09
Frame by frame analysis suggests that a factor is being added to the number in the name of the standup coaster, with said factor increasing over time.

**Comment by James103** [comment] 2020-12-04 18:56
@LordMarcel Are you still able to reproduce this issue in the latest versions (v0.3.x)? If not, this issue can be closed as 'cannot reproduce'.

**Comment by LordMarcel** [comment] 2020-12-18 12:43
I have never been able to reproduce this as I have no idea what circumstances caused it.

**Comment by duncanspumpkin** [comment] 2020-12-18 13:40
Most likely something broke the station ID and that was causing it to access invalid memory. I think we can close this.

**Closed** 2020-12-23 18:58 UTC
Labels: bug
