### ISSUE TITLE
Loading .sc4 Scenario While Paused Removes Fences and Walls

### ISSUE THREAD

**Issue by ThornTSC** [OpenRCT2/OpenRCT2#5245] opened 2017-02-21 02:23 UTC
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** f6f6d27

If a .sc4 scenario is loaded from the "Select scenario for new game" menu while the game is paused, it will load without any objects from the "Fences and Walls" scenery category.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Pause the game during play.
2. Select the New Game option from the "Disk and game options" menu.
3. Load a .sc4 scenario.

**Comment by Gymnasiast** [comment] 2017-03-21 07:17
Found the cause. The `FixWalls()` command calls (via a double detour) WallPlace, which won't place a wall if the game is in pause mode.

The solution would be to save the old state of gCheatsBuildInPauseMode, enable it, carry out the fixes, then restore the old value.

I will apply that fix when I have time, but if someone else wants to have a go, feel free to do so.

**Comment by duncanspumpkin** [comment] 2017-03-21 08:17
Shouldn't you pass the build while paused game command flag in the fix walls function.

**Comment by Gymnasiast** [comment] 2017-03-21 08:39
That doesn't help, as the error is in `WallPlace()`, which is called by `FixWalls()`.

**Comment by Gymnasiast** [comment] 2017-03-25 20:58
Fixed in e85c627.

**Closed by Gymnasiast** 2017-03-25 20:58 UTC
Labels: bug, rct1 import
