### ISSUE TITLE
Invention list won't save

### ISSUE THREAD

**Issue by Topherroni** [OpenRCT2/OpenRCT2#12283] opened 2020-07-16 01:38 UTC
Mac
Very 2.6
**Commit/Build:** [e.g. 426e106]

I've run into a bit of an issue when creating parks.  When in the invention research list menu.  After rearranging how I want the rides to be researched, if i save the file and come back to it later, the research list doesn't save the order you put them in.  It's just back to the default alphabetical order.

**Comment by telk5093** [comment] 2020-07-16 04:42
I think it is duplicated with #9726, needs a new save file format to solve

**Comment by Gymnasiast** [comment] 2020-07-16 11:29
It is a duplicate of #9726, but it has nothing to do with the new save format. It's just the scenario editor being buggy as hell.

**Closed by Gymnasiast** 2020-07-16 11:29 UTC
