### ISSUE TITLE
Feature Request - Right-Click Rotate Button Rotates View 90 Degrees Counterclockwise (Like Chris Sawyer's Locomotion)

### ISSUE THREAD

**Issue by wildgoosespeeder** [OpenRCT2/OpenRCT2#5419] opened 2017-04-30 23:40 UTC
I see that you can rotate the view 90 degrees in both the clockwise and counterclockwise directions as vanilla RCT2 can only go clockwise. You know what would be a great enhancement? Right-clicking that button to go counterclockwise, just like Chris Sawyer's Locomotion.

**Comment by xp4xbox** [comment] 2017-05-01 00:49
There are already shortcut keys that you can map, for switching the direction you want.

**Comment by wildgoosespeeder** [comment] 2017-05-01 00:54
I don't think I was clear enough. I'll make a title change.

**Comment by xp4xbox** [comment] 2017-05-01 00:58
I still do not see the point of that, if you want to rotate the other way, then just use the quick drop down menu.
![untitled](https://cloud.githubusercontent.com/assets/24964930/25569563/cdcc545e-2de7-11e7-83d6-e7f61c350cb8.png)

**Comment by wildgoosespeeder** [comment] 2017-05-01 00:59
Right-clicking is quicker than click-hold drag-and-drop.

**Comment by xp4xbox** [comment] 2017-05-01 01:01
Then use the shortcut keys, right now, there is no right click option on any menu (I could be wrong). It would be confusing to add right-click options to other menus

**Comment by wildgoosespeeder** [comment] 2017-05-01 01:12
Only in CSL right-click does something different than left-click. The zoom button is one button, but that's a different story. If this isn't desired, I would be happy with this design change:

![fort anachronism 2017-04-30 20-05-04](https://cloud.githubusercontent.com/assets/18543809/25569684/43733f4e-2de1-11e7-951d-748fc0d797f2.png)

**Comment by xp4xbox** [comment] 2017-05-01 01:18
I would prefer two buttons rather than right-click, but I really do not see the point.

**Comment by wildgoosespeeder** [comment] 2017-05-01 01:31
The desired action is instantaneous rather than a little drawn out. It's just better interface design.

**Comment by janisozaur** [comment] 2017-05-01 05:30
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/5314

**Closed by janisozaur** 2017-05-01 05:30 UTC
