### ISSUE TITLE
BACKTRACE f8dd89

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8291] opened 2018-11-24 19:07 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/f8dd898b304d348e7f48853fc9a4f0e79ae3390a00ef453369b82c905c8ee237?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Nov 24 2018 19:07:32)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> d0108b3: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guard::Assert_VA -> Guard::Assert -> vehicle_get_head -> vehicle_update_crossings -> vehicle_update_track_motion_forwards -> vehicle_update_track_motion -> vehicle_update_travelling -> vehicle_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> SDL_PeepEvents_REAL -> SDL_WaitEventTimeout_REAL -> SDL_PollEvent_REAL -> UiContext::ProcessMessages -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:19
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8477

**Closed by janisozaur** 2019-02-02 22:19 UTC
Labels: backtrace.io, crash
