### ISSUE TITLE
Scroll bar can get tiny for extremely long lists

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4013] opened 2016-07-08 17:11 UTC
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.4

For windows with lists (like the list of attractions), you have a scroll bar. But the “bar” which you can click and drag can get tiny if the list is very long, making it hard (but not impossible) to click. This easily happens in the guest list with over 1000 guests.

- Reproducible in RCT2 (vanilla)? Yes, this is originally a RCT2 flaw, OpenRCT should not copy it IMO.
- Multiplayer? N/A

**Steps to reproduce:**
 1. Play a game with a park with over 1000 guests
 2. Open the guets list
 3. Look at the scroll bar

A simple fix for this would be to force a more useful minimum size of the “bar”, not just 1 or 2 pixels. The bar should never get smaller than this mimium size, no matter how large the list. It could still be small but it should be just large enough that it is less annoying to click on it. :-)

**Comment by gDanix** [comment] 2016-07-08 18:57
![screenshot](https://cloud.githubusercontent.com/assets/1117657/16698434/8358fc74-454e-11e6-8772-b83087150e7c.png)

**Comment by duncanspumpkin** [comment] 2016-07-09 06:48
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/592 Although this one has a better description.

**Comment by Gymnasiast** [comment] 2016-07-10 18:03
Not a duplicate at all, #592 is about the object list having all sorts of bugs, this is about the inconvenience of small scrollbar thumbs. Totally different problems. (Reading #592 in-issue description would have shown that.)

**Closed** 2016-07-15 19:49 UTC
