### ISSUE TITLE
After loading park: all rides turned invisible with Crooked House crash immediately

### ISSUE THREAD

**Issue by FischNE** [OpenRCT2/OpenRCT2#6455] opened 2017-10-12 20:39 UTC
OS: Windows 10
Version:** [0.1.2.]
Commit/Build: [6d29fd5]

Since today, whenever I load any park that has rides which were turned invisible with the crooked house track type, as soon as the park is loaded those rides crash. It's as if they had no track and the cars just drop into destruction and all peeps die.
This happens in Single- and Multiplayer.

Steps to reproduce:
Open a park with invisible rides.

**Comment by Gymnasiast** [comment] 2017-10-12 21:27
Caused by https://github.com/OpenRCT2/OpenRCT2/commit/7dc6e4e9c3568c3f71852ce62839935038e68221 and fixed in https://github.com/OpenRCT2/OpenRCT2/commit/202244eda624381319bf39724006726bf18c61e2.

**Closed by Gymnasiast** 2017-10-12 21:27 UTC
Labels: bug
