### ISSUE TITLE
Go-Karts Stuck on Corner Track

### ISSUE THREAD

**Issue by FreeJusticeHere** [OpenRCT2/OpenRCT2#8093] opened 2018-10-15 04:54 UTC
**OS:** Windows 10 64-bit
**Version:**  0.2.1
**Commit/Build:**  8ac731e

Guests riding on the Go-Kart track will get stuck when the race begins on the corner track after the station. This has occurred just after a vehicle malfunction was fixed, although I do not know if this is the cause.

**Steps to reproduce:**
1. Create a Go-Kart track similar to the (hopefully) attached screenshot, with a station followed by a sharp turn into a slope.
2. Allow ride to run until a breakdown occurs and is then fixed.

**Screenshots / Video:**
![woody forest 2018-10-14 21-33-03](https://user-images.githubusercontent.com/20288209/46930620-9480a580-cffb-11e8-8bd6-de95a8b9c4d6.jpg)

**Comment by jensj12** [comment] 2018-10-15 07:33
Does this also happen with other go-kart vehicles? I think it was an issue with these longer vehicles.

**Comment by Gymnasiast** [comment] 2018-10-15 07:33
This issue is specific to the 1920s racing cars.
It's a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3588

**Closed by Gymnasiast** 2018-10-15 07:33 UTC
