### ISSUE TITLE
Finances window shows same amount for all fields

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12968] opened 2020-09-19 02:04 UTC
**OS:** Windows 10
**Version:** 0.3.0
**Commit/Build:** 4a79e93

The financial summary window has become bugged where it now shows the same number across all fields (e.g. $51.90 in ride tickets, park entrance tickets, landscaping, etc.). The plus and minus signs are also now missing.

**Steps to reproduce:**
1. Load up any saved game in a scenario with money enabled or start up a new game in any scenario with money.
2. Place down something (e.g. a ride or scenery object) and then open up the financial summary window.
3. You will now see a random number in each row and column of the financial summary window, with that number being the same across all rows and columns.

**Screenshot:**
![Test Park 2020-09-18 18-59-09](https://user-images.githubusercontent.com/61885939/93656757-8acefc00-f9e1-11ea-8a54-36f35de44691.png)

**Comment by AaronVanGeffen** [comment] 2020-09-19 06:49
Likely caused by 4a79e93 (#12966), which was merged around the time you opened this.

**Closed** 2020-09-19 12:58 UTC
