### ISSUE TITLE
Crash when trying to build a design to any thrill ride

### ISSUE THREAD

**Issue by coltongit** [OpenRCT2/OpenRCT2#3632] opened 2016-05-16 15:22 UTC
**OS: Windows 8.1 x64** 
**Version: Latest development version** 
**Commit: d4394c7** 

Explanation of the issue...

- [No] Reproducible in RCT2 (vanilla)?
- [No] Multiplayer?

**Steps to reproduce:**
1. Go to build a Thrill Ride.
2. Build any ride that has a factory design, & use it.
3. Once you click on the design, it crashes the game. Main reason for this is because the factory designs for the thrill rides have no icons.

**Dump file**
If you have a dump file, zip it and drag&drop it here.

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

Don't know where the save file/crash dump files go to, otherwise I would have them both up here. Sorry.

**Comment by janisozaur** [comment] 2016-05-16 20:17
duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3623

**Closed by janisozaur** 2016-05-16 20:17 UTC
Labels: duplicate
