### ISSUE TITLE
Bug: extremely long ride times

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5968] opened 2017-07-22 10:58 UTC
Using 0.1.1 52372b7 on windows 8

The rides times displayed in the statistics tab of a tracked ride are incorrect and excessively long. I'm talking about a normal coaster being 400 minutes long, which is obviously a load of bollocks.

**Comment by Gymnasiast** [comment] 2017-07-22 12:48
Duplicate of #5966 and already fixed in https://github.com/OpenRCT2/OpenRCT2/commit/4852633a1b0c0e133fdce90786b8715ea4877616.

**Closed by Gymnasiast** 2017-07-22 12:48 UTC

**Comment by Gymnasiast** [comment] 2017-07-22 13:26
Saves made between https://github.com/OpenRCT2/OpenRCT2/commit/343e436e452630ffc3f3e05bdd2035e7a1f6e2f6 and 4852633 will have this bug until you clear the measurements.

Problem was caused by rewritten import of rides - previously, the whole ride list was copied in one go, but now it is imported field by field. This is an early preparation step for allowing a new save format.
