### ISSUE TITLE
Using A Sign crashes to desktop

### ISSUE THREAD

**Issue by BunkyBoss** [OpenRCT2/OpenRCT2#8086] opened 2018-10-13 06:35 UTC
**OS:** Windows 8
**Version:** v0.2.1-237
**Commit/Build:** 63c6486 on Develop

So I usually use signs in RCT2 for various stuff like: Labeling a space I claim in Multiplayer, Using it for a ride sign, or an area sign, etc. But on the version I have on OpenRCT2, Signs are a real pain to use. That's because, Whenever I want to use a sign, I select the specific sign I would like to use (lets say the Vertical Sign), and then I get crashed to the desktop. Another glitch about signs, is that, when I want to edit a sign, I click on it, and the game crashes to the desktop. So is there anyway to fix this problem?

**Comment by Gymnasiast** [comment] 2018-10-17 12:19
Perhaps Windows-specific?

Can you reproduce this, @IntelOrca ?

**Comment by tombomp** [comment] 2018-10-17 16:13
I'm on Windows 10 and can't reproduce it in single player - tested all the signs and editing them and they seem fine. Only weirdness I saw was that when the various non-path signs get placed their text gets set to the nearest ride's name, but when you then click to edit the text the edit field just has the number 0 in it instead of the name of the ride that the sign is displaying. i'd assume that's a separate bug though.

**Comment by StrangeAnomoly** [comment] 2018-10-18 20:07
I am having the exact same issue. Happens on single player as well.
Attached DMP file in .zip file of recent crash I had.

[87fcb9de-a7a0-4573-ad8e-b883f6aa0fc3(f26c4c3_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/2493444/87fcb9de-a7a0-4573-ad8e-b883f6aa0fc3.f26c4c3_x86-64.zip)

**Comment by xminusone** [comment] 2018-10-18 20:36
I think this is related to https://github.com/OpenRCT2/OpenRCT2/issues/8033 and the signs being "linked" to the wrong data for the text.

**Comment by StrangeAnomoly** [comment] 2018-12-13 16:33
Don't know whether this is relevant or not but this bug does not affect the latest Release Build [v0.2.1(8ac731e)]

**Comment by duncanspumpkin** [comment] 2018-12-16 18:42
Closing as https://github.com/OpenRCT2/OpenRCT2/pull/8453 sounds like fixed this.

**Closed by duncanspumpkin** 2018-12-16 18:42 UTC
Labels: investigate, multiplayer
