### ISSUE TITLE
Black Rectangle when game is wide enough.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1400] opened 2015-06-19 19:25 UTC
![screenshot 9](https://cloud.githubusercontent.com/assets/3945538/8261305/615d3086-1697-11e5-8f4c-3df4466aed71.png)

It's only there until the next scene change updates it.

(Orange Box Added for Emphasis.)

**Comment by IntelOrca** [comment] 2015-06-20 01:07
I think this can also happen when zooming in / out with in a game.

**Comment by Phyxion** [comment] 2015-06-23 07:45
@IntelOrca Yes, that black rectangle also occurs sometimes when you zoom out a lot.

**Comment by Phasedetect** [comment] 2015-06-26 18:32
I think I may be having a related issue... 
![screen shot 2015-06-26 at 2 31 26 pm](https://cloud.githubusercontent.com/assets/7439907/8384616/2d4f0318-1c10-11e5-94b9-7ab398da1b5b.png)
![screen shot 2015-06-26 at 2 31 35 pm](https://cloud.githubusercontent.com/assets/7439907/8384617/2d4fd90a-1c10-11e5-8096-7ca7d8d1a1d3.png)

**Comment by Phasedetect** [comment] 2015-06-26 18:34
And when I demolish it, I get this. Stays until I scroll far enough that it goes offscreen. ![screen shot 2015-06-26 at 2 33 15 pm](https://cloud.githubusercontent.com/assets/7439907/8384631/581fece2-1c10-11e5-9628-f700b7d7f5c1.png)

**Comment by Phyxion** [comment] 2015-06-27 17:39
Looks like the same issue indeed. I'm not entirely sure if this is related to this but I also sometimes have rendering problems with paths (they are more like a triangle instead of a square).

**Comment by AaronVanGeffen** [comment] 2015-07-05 15:09
Has #1549 had a positive effect on this, by any chance?

**Comment by zsilencer** [comment] 2015-07-05 15:10
yeah this looks like a duplicate of #1002

**Closed** 2015-07-10 20:07 UTC
Labels: bug
