### ISSUE TITLE
Missing Sound Effects

### ISSUE THREAD

**Issue by FlatoutDude** [OpenRCT2/OpenRCT2#7490] opened 2018-05-04 23:29 UTC
**OS:** Windows 10
**Version:** V0.0.13
**Commit/Build:** Build dbbd5b8

No sound effects for various menu items and when building things.

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. load an RCT 1 Scenario, for me this was dynamite dunes
2. try placing paths and structures such as rides and stalls, and navigating menu panes while in-game.

**Dump file**
I don't have a dump file right now.

**Screenshots / Video:**
https://www.youtube.com/watch?v=TVp8J0V-NDw&feature=youtu.be

(i've noticed that sound effects appear to be working in the video, but they still persist to not work when actually in game.)

**Save game:**
[Dynamite Dunes.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1976128/Dynamite.Dunes.sv6.txt)

**Comment by FlatoutDude** [comment] 2018-05-04 23:32
edit: i can hear the sounds for when i am building coasters, it's just that they are very, very faint, how can i fix this? the sounds are maxed out and there isn't any music playing.

**Comment by AaronVanGeffen** [comment] 2018-05-05 07:14
Have you only looked at OpenRCT2's volume settings, or also in Windows' mixer settings? Since Windows Vista, Windows has allowed you to set the volume on a per-application basis. Perhaps something has accidentally gone wrong there?

**Comment by Umdlye** [comment] 2018-05-07 21:37
The sound effect volume is wrong here too. Was used to it/never really noticed it until I booted up the vanilla games yesterday. Some sounds play at full volume (raising/lowering water, opening windows), all the others are much quieter. In vanilla all the UI sound effects are equally loud as far as I can tell.

Windows 10 (x64), appears in release as well as develop.

**Comment by meatbee** [comment] 2018-06-14 14:13
I'm having the same issue. I miss the coaster build sound effects.

**Comment by NicNamSam** [comment] 2020-04-19 23:46
Same issue, 19 April, 2020. No "click" sounds when using menus or placing paths, tracks, or rides.

**Comment by tupaschoal** [comment] 2020-04-26 14:44
I ran every release on GitHub from `0.2.6` to `0.0.5` and in all of them the sounds of building appears to be muffled when compared to Vanilla
[muffled_build.zip](https://github.com/OpenRCT2/OpenRCT2/files/4535524/muffled_build.zip)

**Comment by lah7** [comment] 2020-06-30 22:32
I can confirm the issue (v0.2.6 on Linux x64 + Windows 7 x86). These particular sounds are extremely quiet, but certainly not missing:

* Error sound (e.g. adjusting terrain height out of bounds, or cannot construct track as object in the way)
* Build coaster track
* Build path (both land/bridge modes)
* Raising/lowering water
* Raising/lowering terrain tools
* Click UI sound for buttons and tabs is notably quieter then a dialog box opening up.

It can be reproduced by opening any park, and trying one of the above. I was hacking about in the code and tried changing some of these lines:

    audio_play_sound_at_location(SoundId::LayingOutWater, res->Position);

with:

    audio_play_sound(SoundId::LayingOutWater, 1, AUDIO_PLAY_AT_CENTRE);

which seems a _tad bit audible (losing the left/right panning),_ but still not as loud as vanilla, particularly when the rest of the game is making noise (crowd noise, ride sounds, etc). 

At first I thought it could be a panning issue (too distant?), but even vanilla pans these sounds, so it looks to be a problem with the volume in OpenRCT2. Maybe an additional sound slider for "Interface sounds" could help distinguish these UI sounds from other sound effects?

**Comment by Xardoz** [comment] 2021-01-15 16:33
I noticed that the sound of guests purchasing things (the "cash" sound) seems to be a lot lower than in original games too, which is very disturbing.
I tested with the latest version of OpenRCT2, and compared with vanilla RCT1.

**Comment by Hyperspeed1313** [comment] 2021-04-30 19:32
Having this issue on Windows 10 20H2 with release v0.3.3 (3f65f28)

**Comment by guljam** [comment] 2021-06-09 06:55
same issue

**Comment by Stevoisiak** [comment] 2022-01-15 18:00
Reporting the same issue on Windows 11 with release v0.3.5.1

**Comment by lah7** [comment] 2022-03-19 16:56
I've been poking and experimenting with the code (I'd love to see this fixed!) and found that in `src/openrct2/audio/Audio.cpp`, there is a place to relatively adjust the each sound effect:
```c++
    static int32_t SoundVolumeAdjust[RCT2SoundCount] =
    {
        0,      // LiftClassic
        0,      // TrackFrictionClassicWood
        ....
        -400,   // Purchase
        0,      // Crash
        ....
        0,      // TrainDeparting
        -1000,  // WaterSplash
        0,      // GoKartEngine
        -800,   // RideLaunch1
```

I noticed `WaterSplash` for a ride like River Rapids is much quieter in OpenRCT2 then original RCT2. Not sure if it was intentional.

Even if you force all the sounds to maximum in the code:
```diff
src/openrct2/audio/Audio.cpp

- Mixer_Play_Effect(soundId, MIXER_LOOP_NONE, DStoMixerVolume(volume), DStoMixerPan(mixerPan), 1, 1);
+ Mixer_Play_Effect(soundId, MIXER_LOOP_NONE, MIXER_VOLUME_MAX, DStoMixerPan(mixerPan), 1, 1);
```

Some sounds like UI button clicks, and the error sound are still painfully quiet. The code that handles the 3D volumes/panning seems fine (I'm really not a C++ programmer, I was experimenting with the values), so it makes me wonder if there's a problem with how they are read from the original `css1.dat` file that causes them to be quiet? The error SFX in particular is not crisp like vanilla RCT2 (#16824)

**Comment by IntelOrca** [comment] 2022-05-07 12:17
I think I might have found the solution for this:
```diff
--- a/src/openrct2/audio/AudioMixer.cpp
+++ b/src/openrct2/audio/AudioMixer.cpp
@@ -73,6 +73,7 @@ IAudioChannel* Mixer_Play_Effect(
                 channel->SetVolume(volume);
                 channel->SetPan(pan);
                 channel->SetRate(rate);
+                channel->UpdateOldVolume();
             }
             mixer->Unlock();
         }
```

**Comment by AaronVanGeffen** [comment] 2022-05-11 22:06
@IntelOrca Could you perhaps file a PR, so we can easily test using build artefacts?

**Comment by Broxzier** [comment] 2022-05-11 22:17
> I think I might have found the solution for this:
> 
> ```diff
> --- a/src/openrct2/audio/AudioMixer.cpp
> +++ b/src/openrct2/audio/AudioMixer.cpp
> @@ -73,6 +73,7 @@ IAudioChannel* Mixer_Play_Effect(
>                  channel->SetVolume(volume);
>                  channel->SetPan(pan);
>                  channel->SetRate(rate);
> +                channel->UpdateOldVolume();
>              }
>              mixer->Unlock();
>          }
> ```

Just tested this change locally, and it works indeed! I must say that I'll have to get used to the louder sounds again.

**Comment by tupaschoal** [comment] 2022-05-17 01:07
@IntelOrca is this being fixed in any of your audio PRs?

**Comment by IntelOrca** [comment] 2022-05-17 09:16
yes

**Comment by Xardoz** [comment] 2022-05-19 20:34
I'm sorry to ask but I'm a bit lost with github : has this fix been implemented ? Is this planned ?
Thanks !

**Comment by IntelOrca** [comment] 2022-05-19 22:02
> I'm sorry to ask but I'm a bit lost with github : has this fix been implemented ? Thanks !

Not yet

**Comment by IntelOrca** [comment] 2022-07-08 07:58
Change is in develop and latest release now.

**Closed by IntelOrca** 2022-07-08 07:58 UTC
Labels: bug, investigate
