### ISSUE TITLE
Crash when extra long train breaks down at the back

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#3346] opened 2016-04-19 16:22 UTC
**OS:** Win10
**Version:** v0.0.5 develop
**Commit:** 385b03e

Two crashes (edit: three) during my contribution to the group park of the forum, dumps attached.
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
Just play the game (I was playing singleplayer) :P

**Dump/save file**
[OpenRCT2crashes.zip](https://github.com/OpenRCT2/OpenRCT2/files/226321/OpenRCT2crashes.zip)

**Comment by IntelOrca** [comment] 2016-04-19 16:28
I can't load the saved games because I do not have the required objects. Most multiplayer games crash because they contain an invalid track piece. We don't know what causes this to happen.

**Comment by jensj12** [comment] 2016-04-19 16:31
Opening this save should give you all the required objects (two path types and two rides): [The OpenRCT Group Park 3.18.zip](https://github.com/OpenRCT2/OpenRCT2/files/226339/The.OpenRCT.Group.Park.3.18.zip)

**Comment by IntelOrca** [comment] 2016-04-19 16:43
```
Unhandled exception thrown: read access violation.

vehicle_type->peep_loading_positions was nullptr.
```

**Ride: ** 26
**Train: ** 0

**Comment by janisozaur** [comment] 2016-04-19 17:18
Has anyone tinkered with that save using the longer trains cheat?

**Comment by jensj12** [comment] 2016-04-19 17:33
Yes, there's a ride with 16 cars per train / 1 train (King of Durango Mountain). Got a crash on the stable build as well. Is there any way to see the ID of a ride in-game?

**Comment by IntelOrca** [comment] 2016-04-19 17:35
@jensj12 no, but I wish there was

**Comment by jensj12** [comment] 2016-04-19 19:31
Even with that cheated ride closed the game still crashes. I'll be waiting for a console command to get the ride name by ride ID. Here's the dump from the last crash (hope it helps): [OpenRCT2crashes2.zip](https://github.com/OpenRCT2/OpenRCT2/files/226684/OpenRCT2crashes2.zip)

**Comment by IntelOrca** [comment] 2016-04-20 11:38
@jensj12 From 44717cfe2a6f63f8e4da81a151d0ecc520d12215 there should now be a console command which lists the rides against IDs.

**Comment by jensj12** [comment] 2016-04-20 12:11
Ride 26 is a custom ride named treetop bouncers (subtype 30) and ride 30 is King of Darungo Mountain (can't find 26 anywhere there) with cheated train lenght. I'll try to debug more when I have the time (which won't be until saturday).

**Comment by jensj12** [comment] 2016-05-03 09:23
I've found the cause, here are the steps to reproduce (not sure if step 2 is needed):
1. Use the disable train lenght limit cheat and build a coaster with more cars than normally allowed.
2. Disable the cheat.
3. Wait for a restraints stuck open/closed breakdown applied to one of the cars that normally can't exist.
4. Crash... [OpenRCT2crashes3.zip](https://github.com/OpenRCT2/OpenRCT2/files/246579/OpenRCT2crashes3.zip)
This dump is created with build 98bff69

**Comment by Chaosmeister** [comment] 2017-07-09 20:28
I can't open any save file from this issue.

**Comment by PFCKrutonium** [comment] 2017-07-09 20:38
@Chaosmeister Opened fine for me.

**Comment by Chaosmeister** [comment] 2017-07-09 21:47
I'm unable to reproduce the crash.

**Comment by jensj12** [comment] 2017-07-09 22:00
![image](https://user-images.githubusercontent.com/13868449/27997875-5b2a850a-6501-11e7-926c-f305534001a6.png)
I still get the crash (or rather, an assertion) when trying to force a breakdown on King of Durango Mountain. Whenever it does not crash, the breakdown is triggered in the front half of the train, so you may need to try a few times.
[The OpenRCT Group Park 3.17.txt](https://github.com/OpenRCT2/OpenRCT2/files/1134109/The.OpenRCT.Group.Park.3.17.txt) (earlier version of the same park as before)

**Comment by jensj12** [comment] 2017-07-09 22:12
I can't reproduce this with other coasters. @Broxzier: How did you build that coaster?

**Comment by Broxzier** [comment] 2017-07-09 22:22
I don't thing I've used any hacks for this ride, other than the longer trains. At the time, that was a relatively new feature, and it may have set something wrong. Is the assertion still hit after double-closing the ride, and changing the train length?

**Comment by Chaosmeister** [comment] 2017-07-10 20:03
I can finally reproduce the crash  but I need to force repair the track after forcing a shutdown to trigger the assert with a following crash

**Comment by jensj12** [comment] 2017-07-11 19:17
I closed the coaster, set the number of cars per train to what it was before and reopened the ride. No more crashes, and I noticed a subtle difference in the vehicle tab: before resetting it showed 2 trains of 7 cars (while only 1 train of 16 cars exists), after resetting the vehicle tab showed the correct number of cars.

I have no idea how to get a coaster into that bugged state.

**Comment by Chaosmeister** [comment] 2017-07-11 19:17
all shutdown crashes are caused by an invalid state of the ride.  
ride->num_vehicles is 2 and ->num_cars_per_train is 7, but there is only 1 vehicle with about 16 cars.

**Closed** 2017-07-12 19:23 UTC
Labels: crash, investigate
