### ISSUE TITLE
Vehicle Type Selection: Text Clipping

### ISSUE THREAD

**Issue by ipatix** [OpenRCT2/OpenRCT2#1727] opened 2015-08-04 20:26 UTC
If you enable the RCT1 vehicle selection, you get some text clipping if the descriptions are too long:

![scr12](https://cloud.githubusercontent.com/assets/8502545/9071827/d1ba3660-3af7-11e5-8e7d-0c0f6116c24f.png)

**Comment by IntelOrca** [comment] 2015-08-05 20:40
duplicate of #697

**Closed by IntelOrca** 2015-08-05 20:40 UTC
