### ISSUE TITLE
Sandbox/Freeform mode?

### ISSUE THREAD

**Issue by MadeInDutch** [OpenRCT2/OpenRCT2#12371] opened 2020-07-24 10:28 UTC
Can we have a sandbox mode in OpenRCT2? I've been playing the original Zoo Tycoon and I think the addition of a freeform mode in-game really made it way more fun for me, as well as others. I think that for most simulation games, there needs to be both a customisable sandbox mode and a story mode/set of scenarios, so it'd be great to have something like that for an already fantastic simulation game.

**Comment by AaronVanGeffen** [comment] 2020-07-24 10:34
Presumably, you mean something other than what's already there:
![Screenshot_20200724_123350](https://user-images.githubusercontent.com/604665/88383012-f6159c80-cda9-11ea-9923-c148f8f473ad.png)

Could you elaborate on what you think is missing?

**Comment by IntelOrca** [comment] 2020-07-24 11:06
I think this is a duplicate of #2214

I have toyed with the idea in the past but never got something fully implemented. Basically it would be a button next to start new scenario which instead does start new sandbox which starts a blank map with no objective (similar to RCT3).

**Comment by ocalhoun6** [comment] 2020-07-24 22:35
> Basically it would be a button next to start new scenario which instead does start new sandbox which starts a blank map with no objective

Might be nice (though also more difficult to code) to have it automatically generate a reasonable map, using some of the map generation tools already in the scenario editor and random values (within reasonable limits) entered into it ... but not just randomly generated terrain -- complete with owned land, a park entrance, a peep generation point, and a path to the entrance. So you could just hit that button and then be in a ready-to-go procedurally generated scenario with the 'have fun' objective.

(As opposed to doing the same, but with a default scenario that's just 100% flat with nothing but grass, which would be easier, but much more boring. Though that might be what some people want in a sandbox scenario.)

Personally, I'd prefer to expand this window:
![Untitled](https://user-images.githubusercontent.com/26573303/88440390-a5f70400-cdc2-11ea-8b32-b0b95c8a7509.png)
With a button or two. Hell, maybe three:
[start a blank sandbox scenario] [start a randomly generated sandbox scenario] [start a randomly generated playable scenario]
Where the first button immediately starts up a sandbox with just a blank, flat map.
The second button starts up a randomly generated scenario like I was talking about above.
And the third button starts up a randomly generated scenario just like the previous, but also with randomly generated (within reasonable parameters) goals to achieve for scenario completion. (You could make the automatic goal selection a little easier by having a pre-defined list of acceptable scenario goals -- probably derived from some of the original game's scenarios -- and the code just randomly selects one set of scenario parameters from that approved list.)

**Comment by IntelOrca** [comment] 2020-07-25 13:17
@ocalhoun6 you would probably want an in-game wizard for the terrain generation when you click the sandbox button. I remember Sim City 3000 having one.

**Comment by karst** [comment] 2024-01-08 15:35
This discussion has been moved to https://github.com/OpenRCT2/OpenRCT2/discussions/15656

It's definitely something we want to see implemented at some point in the future.

**Closed by karst** 2024-01-08 15:35 UTC
Labels: feature
