### ISSUE TITLE
Multiple stop rides path issues

### ISSUE THREAD

**Issue by moawkwrd** [OpenRCT2/OpenRCT2#2990] opened 2016-02-21 11:18 UTC
OS: Windows 7 x64
Version: 0.0.4 build f68fe7d

Having trouble with queues and paths with rides that multiple entrances/exits (i.e. chairlift, steam train, etc). At first the paths wouldn't connect. I then tried the other way round, adding the paths first and then placing the entrances and exits to the ride. This seemed to work, until I tried to open the ride and then it was asking me to place exits and entrances again, alongside the existing ones, to each station.

Steps to reproduce:
1. Build a chairlift with multiple stops, place multiple entrances and exits
2. Try to add queues and paths

[Dynamite Dunes.txt](https://github.com/OpenRCT2/OpenRCT2/files/139578/Dynamite.Dunes.txt)

**Comment by zaxcav** [comment] 2016-10-23 21:03
@Gymnasiast This issue seems to have been resolved. I can't reproduce it on build 88ccfad. Close it?

**Comment by Gymnasiast** [comment] 2016-10-24 07:01
Yes, this PR predates your modifications anyway.

@moawkwrd If you run into this problem with the newest build, please let us know.

**Closed by Gymnasiast** 2016-10-24 07:01 UTC
Labels: investigate
