### ISSUE TITLE
Game crashes when I try to build a Go Karts

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6378] opened 2017-10-05 18:50 UTC
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** f2195b4

The game crashes when I click on the Go Karts in the ride selection screen. I've tried this in multiple save files so it's not an issue caused in a specific park.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer? It doesn't crash in multiplayer, but I do get an "invalid ride type" error, which I don't get with other rides.

**Steps to reproduce:**
1. Try to build a go karts

**Comment by duncanspumpkin** [comment] 2017-10-05 18:55
Duplicate of #6376
Can you check with the very latest build.

**Comment by duncanspumpkin** [comment] 2017-10-05 18:58
I'm pretty sure it is the same bug I've just tried it with the latest build and its not crashing.

**Closed by duncanspumpkin** 2017-10-05 18:58 UTC
Labels: duplicate

**Comment by LordMarcel** [comment] 2017-10-05 19:16
just checked, it works now, thanks
