### ISSUE TITLE
Guests not boarding gentle tracked rides successfully.

### ISSUE THREAD

**Issue by gjgordon** [OpenRCT2/OpenRCT2#1838] opened 2015-08-24 05:29 UTC
Guests on some of my more unpopular gentle tracked rides won't board the ride unless there are enough guests in line to fill the cars. I saw this happen with the Ghost Train ride and an Old Timers ride. Both of these rides can hold two riders per car, but if there was only one person in line, the riders would enter the entrance, then fail to board, turn around, walk back out to the line, and the car would launch without any passengers. This would happen repeatedly until a second passenger got in line, and then both guests would board successfully. I haven't seen this happen on any of my coasters or flat rides.

I put a recording on YouTube. There's a play by play in the YouTube description if you can't tell what's going on. It's hard to see with my tiny windows.

https://youtu.be/9TqugQycr30

I also saved a copy of the save file in my Dropbox with my Ghost Train ride in place. 
https://www.dropbox.com/s/fendrcj30cp69gf/GhostTrainBug.sv6?dl=0

**Comment by IntelOrca** [comment] 2015-08-24 06:22
I think the only bug is the fact that they keep trying to board when there is no second passenger. Otherwise this is normal behaviour - the game only has sprites for an empty car or a car with two passengers.

**Comment by gjgordon** [comment] 2015-08-24 06:41
What are they supposed to do in the base game? Wait in the queue until the second passenger shows up to board?

**Comment by Gymnasiast** [comment] 2015-08-24 07:31
No, wait in the entrance until a second passenger shows up, or go back to the front of the entrance if a car should leave.

**Comment by IntelOrca** [comment] 2015-08-24 11:26
I marked it as a bug as I believe the peeps shouldn't be go in as far as they are in the video when waiting for a partner.

**Comment by duncanspumpkin** [comment] 2015-08-24 11:38
I think this is what they are meant to do. If no second person arrives before the car leaves they have to return to the front of the queue.

**Comment by clamburger** [comment] 2015-10-08 11:53
I've discovered that this affects many more rides than the ones listed.

Rides affected (2 people are required):
* Transport rides: Miniature Railway, Monorail, Suspended Monorail, Chairlift, Elevator, River Rafts, Mini Helicopters, Ghost Train, Canoes, Launched Freefall, Bumper Boats, River Rapids, Splash Boats, Floorless Roller Coaster, Wooden Roller Coaster

Rides unaffected:
* Monorail Cycles, Maze, Mini Golf, Observation Tower, Hover Car Ride, Dodgems, Submarine Ride, Go Karts, Roto Drop, Jet Skis

Additionally, it's not just a "minimum 2 peeps" requirement, it affects all multiples of 2. (For example, if 5 people are lining up for the Floorless Roller Coaster, 4 can board and 1 gets left behind)

**Comment by Gymnasiast** [comment] 2015-10-08 11:55
That's intended behaviour. There is a flag that specifies that riders met ride in pairs.

**Comment by IntelOrca** [comment] 2015-10-08 17:04
Yes, its because the objects do not contain sprites for the vehicles with just one peep in them. Only with no peeps or with two peeps.

**Comment by duncanspumpkin** [comment] 2015-11-04 19:42
Okay i've tested this in the vanilla and the behaviour is identical. I'm going to close the issue and it can be reopened if people think there is something wrong.

**Closed by duncanspumpkin** 2015-11-04 19:42 UTC
Labels: bug
