### ISSUE TITLE
Mechanics can't find ride

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2957] opened 2016-02-16 11:09 UTC
Mechanic 10 keeps running around in circles, ending up with complaints that the ride is still not fixed. This does not happen in vanilla.
[Rainbow Summit.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/132312/Rainbow.Summit.sv6.txt)

EDIT: Sometimes, after a while, it seems it does go to the entrance of the ride but then it doesn't do anything and another mechanic gets the call again. Which will then also have the same problem with 'Go Karts 1'.

**Comment by Phyxion** [comment] 2016-02-16 12:41
[Rainbow Summit - Copy.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/132456/Rainbow.Summit.-.Copy.sv6.txt)

Another save with the same problem, check mechanic 20. It just gives up after a while.

**Comment by duncanspumpkin** [comment] 2016-02-16 12:52
probably to do with the change in staff ai on sunday.

**Comment by raidcookie** [comment] 2016-02-16 15:04
Have you built any paths with disabled clearance checks? Sometimes staff and guests won't walk on these.

**Comment by Phyxion** [comment] 2016-02-16 15:50
No, I have not.

**Comment by duncanspumpkin** [comment] 2016-02-16 18:51
Happens in vanilla this is a duplicate of the peep pathfinding not being great.

**Closed** 2016-02-16 18:53 UTC
Labels: duplicate
