### ISSUE TITLE
Path objects disappear from scenery selection when save is reloaded.

### ISSUE THREAD

**Issue by rctGuy101** [OpenRCT2/OpenRCT2#22191] opened 2024-06-24 19:02 UTC
### Operating System

Windows 11, 64 Bit

### OpenRCT2 build

OpenRCT2 4.11

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

In a nutshell, if you reload a save, the "non-standard" (aka ones that come from a theme) path objects will disappear from the scenery selection menu. This includes benches, lampposts, and trash cans. This can cause real issues for scenarios whose only options for these come from a theme, as the player will be unable to use these. This does not happen if the "theme" (or scenery category) is unlocked. 

### Steps to reproduce

1. Open a scenario that has path objects part of a theme but not the theme itself (Japanese Coastal Reclaim for example).
2. Save and load.
3. Many of the path objects will go missing.

**Comment by 733737** [comment] 2024-06-24 21:31
this is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/21496 which was fixed 3 days ago. Please update to the latest development build

**Comment by Gymnasiast** [comment] 2024-06-24 21:43
I’m not sure what version you’re on. There is no such version as 4.11. There is v0.4.11, but that may still refer to either release or develop. If it’s release, try `develop` first - as 73 pointed out, we very recently fixed a bug that sounds a lot like yours.

If you are already on develop, please properly copy the build string (there is a button for it in the About window).

**Comment by Gymnasiast** [comment] 2024-08-19 22:22
Closing this as OP has not answered in two months.

**Closed by Gymnasiast** 2024-08-19 22:22 UTC
Labels: invalid/incomplete
