### ISSUE TITLE
Text overlaps with all graphs.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#4276] opened 2016-08-13 20:05 UTC
**OS:** Win 10
**Version:** 0.0.5
**Commit/Build:**  7f71bec (latest build)

This looks like that an abbreviation of the month is needed for display these strings.

- [ ] ~~Reproducible in RCT2 (vanilla)?~~
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open the park window.
2. Go to the ranking tab.
3. See the problem.

**Screenshots / Video:**
**OpenRCT2:**
![fundador de la ciudad perdida 2016-08-13 14-46-36](https://cloud.githubusercontent.com/assets/7508197/17645246/939d7a00-6165-11e6-9c21-4bb6860913b9.png)
**RCT2:** 
![scr1](https://cloud.githubusercontent.com/assets/7508197/17645248/9b448a96-6165-11e6-84ac-84957ddb960e.png)

**Comment by Wirlie** [comment] 2016-08-13 20:07
Also, I noticed that this happens with all graphs, like the finance window.

**Comment by marijnvdwerf** [comment] 2016-08-13 20:11
Duplicate of #4087

**Closed** 2016-08-13 20:12 UTC

**Comment by Wirlie** [comment] 2016-08-13 20:13
ops, you're right, sorry
