### ISSUE TITLE
Loading screen glitches out on OpenGL and unlocked frame rate

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#22432] opened 2024-07-31 16:33 UTC
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.12-117-gf6aa08c (f6aa08c on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When running the game in OpenGL drawing engine and having the framerate unlocked, the loading bar for indexing the objects glitches like crazy. The other loading segments seem to do fine though. On software rendering, and without uncapped framerate, everything works as expected.

I presume that clearing the screen and redrawing the loading bar are not in sync with each other?

### Steps to reproduce

1. Ensure the game is using the OpenGL drawing engine.
2. Unlock your framerate.
3. Delete `objects.idx` from your user directory (to force a reindex next startup).
4. Restart OpenRCT2.

### Attachments

https://github.com/user-attachments/assets/bff94b9a-f103-4342-b7fe-60ecdc7c77d6

**Comment by AaronVanGeffen** [comment] 2024-07-31 16:35
Looks like a regression from #22354, unfortunately.

**Comment by 733737** [comment] 2024-07-31 23:53
duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/22418

**Closed** 2024-08-01 21:07 UTC
Labels: bug
