### ISSUE TITLE
Button to fix vandalism but with proper repair cost (feature)

### ISSUE THREAD

**Issue by ipatix** [OpenRCT2/OpenRCT2#2343] opened 2015-11-19 02:37 UTC
So we already got the cheat window to fix vandalism in a park which is really awesome.
Sometimes, though, I personally don't feel like wanting to cheat but I'm still too lazy to go through my entire park and look for broken benches and trash cans. So wouldn't it be kinda cool to have a button that fixes all the vandalism but requires the actual money to repair everything? I'm not sure where to place the button and how difficult it is do implement but I just felt like leaving that idea here and see if anyone is interested in it.

**Comment by osconnoisseur** [comment] 2015-11-19 03:37
I think it's better if the player actually has to manually fix all of the broken stuff. It makes the game more of a challenge and gives an incentive to keep the park clean.

**Comment by PFCKrutonium** [comment] 2015-11-19 05:59
Perhaps have it as an optional thing? Enabled via Options, Provided as a button in the scenery window?

**Comment by IntelOrca** [comment] 2015-11-19 08:26
I prefer the feature for a staff member to be able to fix vandalism than this.

**Comment by PFCKrutonium** [comment] 2015-11-19 10:56
That actually sounds like a good idea, but what about animation?

**Comment by Gymnasiast** [comment] 2015-11-19 11:30
Duplicate of #1285.

**Comment by Gymnasiast** [comment] 2015-11-19 11:33
By the way, I agree with @IntelOrca's idea. The 'staff member' should be a handyman, IMO. Although I have to say I don't find it mutually exclusive: we could implement both.

**Closed** 2015-11-19 13:29 UTC
Labels: duplicate
