### ISSUE TITLE
Not able to ban players from a multiplayer server

### ISSUE THREAD

**Issue by arjanvlek** [OpenRCT2/OpenRCT2#11003] opened 2020-03-23 12:37 UTC
**OS:** [e.g. Windows 10]
Linux Ubuntu 18.04 LTS server

**Version:** [e.g. 0.2.4]
0.2.4

**Commit/Build:** [e.g. 426e106]
Public release version

Hi,

I'm hosting a dedicated multiplayer server and sometimes there are people trolling or deliberately destroying other people's work. As I'd like to offer everybody a chance to start building, I don't want to make everyone a spectator by default and require me to upgrade their permissions manually. 

As such, I'd like to be able to ban people who misbehave on the server. Given that every player has an unique hash to assign groups on the server, i think there should be a ban button for server admins which put these hashes in a list of blocked users. 
I know this ban can probably be bypassed, but it makes it at least harder for trollers to come back to a server.

If that's really not possible, it should -at the very least- be possible to view previous hashes of joined players so we can put these in the users.json file with zero permissions. And this must be possible without having to restart the game server.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Player destroys the park on a server and then leaves
2. Unable to ban or reduce permissions of this player

**Dump file**

N/A

**Screenshots / Video:**

N/A

**Save game:**

N/A

**Comment by IntelOrca** [comment] 2020-03-23 13:23
We are closing to rolling our a plugin system, that will allow plugins to be written for server management such as excluding those with a certain IP address or hash etc.

**Comment by telk5093** [comment] 2020-03-23 14:34
Currently, you need to ban trollers by banning their IP using your firewall system, such as ufw.
Note that IP is logged when a client joins in the server log file if you have turned on ``log_server_actions = true`` in your ``~/.config/OpenRCT2/config.ini`` file.

**Comment by arjanvlek** [comment] 2020-03-24 14:12
Hi @IntelOrca I see the plugin branch but it is last updated in 2018. Are you sure this is almost ready?

**Comment by Gymnasiast** [comment] 2020-03-24 14:15
@IntelOrca Yes, but the OP is not asking for IP block, he is asking for blocks based on user keys. I thought that we supported that.

**Comment by IntelOrca** [comment] 2020-03-24 14:21
@Gymnasiast no, the keys really just prevent spoofing (and only if the real person joined first or otherwise had their public key added in advance). You can also require keys to join but the OP wanted anyone to join immediately with build permissions. If they leave, change their name and re-join they have a new key anyway.

@arjanvlek Try looking at this one: 😄 
https://github.com/IntelOrca/OpenRCT2/tree/epic/plug-in-4

We hope to merge soon after we have done a release which will be soon.

**Comment by janisozaur** [comment] 2020-03-24 16:58
To clarify: changing the name does not imply new key. It's simply a mechanism to select appropriately named file containing the key and creating one for user, if it doesn't exist. There is nothing preventing a user from using a given key under different names.

**Comment by Broxzier** [comment] 2020-03-24 19:53
@arjanvlek You can create a group with no permissions and assign the trolling people to that group, then they won't be able to do anything on that account. They could however easily change their key by using another username.

You can view hashes of previous people by checking the server logs. Search for "has joined the game".

**Comment by duncanspumpkin** [comment] 2020-03-27 17:37
This is a duplicate of #2667

**Comment by IntelOrca** [comment] 2022-02-12 13:14
Plugins can provide all desired functionality. An example is https://github.com/CorySanin/openrct2-ffa-plugin-suite

**Closed by IntelOrca** 2022-02-12 13:14 UTC
Labels: feature
