### ISSUE TITLE
Missing Title Sequence

### ISSUE THREAD

**Issue by fischfood** [OpenRCT2/OpenRCT2#7813] opened 2018-07-24 04:44 UTC
**OS:** macOS 10.13.2
**Version:** [e.g. 0.2.0]
**Commit/Build:** [e.g. oaff800]

No title sequence exists when opening the game. Also when going to Options > Miscellaneous, the title sequence dropdown is blank, and clicking Edit Title Sequences and going to the Save or Script tag causes the game to crash.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open OpenRCT2

**Screenshots / Video:**
<img width="1094" alt="screen shot 2018-07-24 at 12 32 56 am" src="https://user-images.githubusercontent.com/4094141/43117371-792679ac-8eda-11e8-82aa-6951cc492e73.png">

**Crash Report (When clicking on Tabs in Edit Title Sequence Modal):**
[OpenRCT2_7813_CrashReport.txt](https://github.com/OpenRCT2/OpenRCT2/files/2221992/OpenRCT2_7813_CrashReport.txt)

**Comment by IntelOrca** [comment] 2018-07-24 06:45
Duplicate of #7734

**Closed by IntelOrca** 2018-07-24 06:45 UTC
