### ISSUE TITLE
Error with the save game

### ISSUE THREAD

**Issue by viiciio** [OpenRCT2/OpenRCT2#9182] opened 2019-05-01 13:44 UTC
**OS: Windows 10**
**Version: 0.2.2**
**Commit/Build: 298c9f5**

When the game is running (not paused), after a few seconds oppened, the game crashes and show the error message.

- [ ] Reproducible in RCT2 (vanilla)?
The savegame don't open on Vanilla.
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the save game
2. Wait a few seconds with the game unpaused

**Dump file**
[89773f0f-1e3a-4d86-94cb-b027db7cf6e2(298c9f5_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/3134641/89773f0f-1e3a-4d86-94cb-b027db7cf6e2.298c9f5_x86-64.dmp.gz)

**Screenshots / Video:**
![dwm_2019-05-01_10-31-08](https://user-images.githubusercontent.com/50173014/57019472-05d12000-6bfd-11e9-81fb-9b6cb8da0df5.png)

**Save game:**
[Grande Aventura Six Flags.zip](https://github.com/OpenRCT2/OpenRCT2/files/3134646/Grande.Aventura.Six.Flags.zip)

**Comment by ZehMatt** [comment] 2019-05-01 14:32
I'm unable to reproduce the crash, its possible that this is already fixed in the latest develop version, could you try a newer build?

**Comment by viiciio** [comment] 2019-05-01 14:44
Unfortunately this error happens since 0.2.0 version... :(
The 298c9f5 isn't the newer build? I've updated today.

**Comment by ZehMatt** [comment] 2019-05-01 14:47
Thats the latest release, you can find newer builds here: https://openrct2.org/downloads

**Comment by viiciio** [comment] 2019-05-01 14:51
It worked in a c5b66c0 build! Tksss!

**Closed** 2019-05-01 14:51 UTC
