### ISSUE TITLE
Ride Ratings are not available

### ISSUE THREAD

**Issue by StrangeAnomoly** [OpenRCT2/OpenRCT2#8532] opened 2018-12-24 23:30 UTC
[Windows 7]
[v0.2.1-478(8d9fcb7) on develop]

Currently, I have a ride [Ultraphobia (B&M Invert)] that shows the stats but the ratings do not appear.

There are no rides with infinite loops.

I have noticed this is the same issue as this one:
https://github.com/OpenRCT2/OpenRCT2/issues/4695

So if someone could take a look at my park (that is attached) to see if this is indeed the same problem and how to fix this bug, that'd be much appreciated.

- [?] Reproducible in RCT2 (vanilla)?
- [ ?] Specific to multiplayer?

**Steps to reproduce:**
1. Open the park attached
2. You will notice the ratings will never load as well any additional new ride ratings either.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/41911850/50407601-434b1a00-07d3-11e9-8958-fa5618c97600.png)

**Save game:**
[Hearfield's Land of Amusement (2).zip](https://github.com/OpenRCT2/OpenRCT2/files/2707803/Hearfield.s.Land.of.Amusement.2.zip)

****UPDATE [26/12/2018]**** 

It seems I have fixed the issue by closing all rides, re-building Ultraphobia's 2 station platforms (one boarding/unboarding), toggling the chain lift speed of Ultraphobia by 1mph up&down (to reset all stats).

I still do not know what could've caused the issue in the first place though...

**Comment by jensj12** [comment] 2018-12-25 08:55
The problem probably isn’t the ride itself. You can find the offending ride by force-closing them one at a time and check if ratings start to appear in the rest of the park. Once you know the offending ride, the problem is much easier to investigate.

**Comment by janisozaur** [comment] 2018-12-25 13:55
If this is a technical limitation, there should be a way to investigate the currently evaluated ride or have confirmation none is being evaluated.

**Comment by StrangeAnomoly** [comment] 2018-12-26 12:38
I have added an update to my post as the issue (affecting the ride) appears to have been fixed. [Not sure what caused the issue to begin with though...]

**Comment by jensj12** [comment] 2018-12-26 14:02
Check the park for any other rides that haven't got their ratings (or build a new ride to test if it still works). If that is all fine, I don't know what could have caused the issue in the first place.

**Comment by sjoerddebruin** [comment] 2024-09-29 15:47
Doesn't seem to be an issue anymore, probably since #19683.

**Comment by ZehMatt** [comment] 2024-09-29 16:25
One ride can no longer block all of them.

**Closed by ZehMatt** 2024-09-29 16:25 UTC
Labels: investigate
