### ISSUE TITLE
Time Twister objects translate bug

### ISSUE THREAD

**Issue by NeverDruid** [OpenRCT2/OpenRCT2#2611] opened 2015-12-31 17:21 UTC
![3434343](https://cloud.githubusercontent.com/assets/16353804/12066041/7945171e-b024-11e5-8ff4-4c0fcaa22af5.JPG)
this string is already translated korean.txt.
and many other Untranslated string for already translated strings.

**Comment by Gymnasiast** [comment] 2015-12-31 21:14
Close OpenRCT2, delete plugin.dat and then restart OpenRCT2.

**Comment by telk5093** [comment] 2016-01-01 04:41
He told me it doesn't solved after he deleted plugin.dat.
It occurs to me too, and I definitly deleted plugin.dat.

![image](https://cloud.githubusercontent.com/assets/10726524/12069757/49aa7d28-b08d-11e5-9ac8-a1dbf7493156.png)

**Comment by Gymnasiast** [comment] 2016-04-26 09:40
Does this still happen?

**Comment by telk5093** [comment] 2016-04-26 09:45
@Gymnasiast Yes, still happened in the last commit.

**Comment by YJSoft** [comment] 2016-04-26 13:19
for some reasons, those Time Twister object strings are searched at `_scenarioOverrides`. It is not happening other objects.

**Comment by YJSoft** [comment] 2016-04-26 13:25
If I change code like
```cpp
if (stringId >= ScenarioOverrideBase)
    {
        int offset = stringId - ScenarioOverrideBase;
        int ooIndex = offset / ScenarioOverrideMaxStringCount;
        int ooStringIndex = offset % ScenarioOverrideMaxStringCount;

        if (_scenarioOverrides.size() > (size_t)ooIndex)
        {
            return _scenarioOverrides[ooIndex].strings[ooStringIndex];
        }
        else
        {
			offset = stringId - ObjectOverrideBase;
			ooIndex = offset / ObjectOverrideMaxStringCount;
			ooStringIndex = offset % ObjectOverrideMaxStringCount;
			
			if (_objectOverrides.size() > (size_t)ooIndex)
			{
				return _objectOverrides[ooIndex].strings[ooStringIndex];
			}
			else
			{
				return nullptr;
			}
        }
    }
```
, everything works fine.(If search from `_scenarioOverrides` fails it will try searching from `_objectOverrides`)

<img width="611" alt="2016-04-26 10 25 01" src="https://cloud.githubusercontent.com/assets/5893514/14819581/be8c7a12-0bfd-11e6-826e-b016f5cbcf8f.png">

**Comment by IntelOrca** [comment] 2016-04-26 16:50
I only allowed 4096 object override strings, so that just needs to be extended.

**Comment by YJSoft** [comment] 2016-04-26 22:03
@IntelOrca It's not related to that(I think)
Other object's id is below 30000, but Time Twister object ids are all over 30000.

Since `ScenarioOverrideBase` is 0x7000(28627), all object id over 28627 will be recognized as scenario string id, not object string id.
<img width="302" alt="2016-04-27 7 02 15" src="https://cloud.githubusercontent.com/assets/5893514/14835684/035f9a14-0c46-11e6-840b-42c2c0deadfd.png">

**Comment by IntelOrca** [comment] 2016-04-26 23:18
String IDs above and equal to 0x8000 can not be used as they are reserved for user strings unfortunately.

**Comment by YJSoft** [comment] 2016-04-27 00:41
Anyway since the problem is range overlapping each other, It can't be fixed without changeing range.

**Comment by Gymnasiast** [comment] 2017-04-04 13:47
Does this still happen?

**Comment by Lastorder-DC** [comment] 2017-04-05 04:37
@Gymnasiast Yep. 
<img width="377" alt="2017-04-05 1 36 08" src="https://cloud.githubusercontent.com/assets/18280396/24689927/df473696-1a04-11e7-87eb-153859e86285.png">

**Comment by Gymnasiast** [comment] 2017-05-08 13:59
@IntelOrca Can we not move user-defined strings further?

**Comment by IntelOrca** [comment] 2017-05-08 16:18
@Gymnasiast nope

**Comment by Gymnasiast** [comment] 2017-05-08 16:35
@IntelOrca That is a very unhelpful answer. At least try to provide more information, this bug has been rotting away for a year and five months.

**Comment by Gymnasiast** [comment] 2018-04-09 07:31
Checked again on `develop`. It works correctly now.

I'm closing this, please let me know if it works or not.

**Closed by Gymnasiast** 2018-04-09 07:31 UTC
Labels: bug, investigate

**Comment by Lastorder-DC** [comment] 2018-04-09 07:52
![2018-04-09 16-45-46](https://user-images.githubusercontent.com/18280396/38485882-488c10f2-3c16-11e8-8aa9-8b742f18494d.png)
![2018-04-09 16-45-53](https://user-images.githubusercontent.com/18280396/38485888-4ce6de5c-3c16-11e8-81a6-347492e546df.png)
Works very well without any problem.
