### ISSUE TITLE
Auto updater

### ISSUE THREAD

**Issue by thenamelessone1** [OpenRCT2/OpenRCT2#10745] opened 2020-02-19 23:14 UTC
Feature request: auto-updater so the game can update itself by downloading either a new official or development release (user selectable)

It can be done too in android  , see Forge for Android for example.
This game also updates the data files.

**Comment by AaronVanGeffen** [comment] 2020-02-19 23:15
Duplicate of #2975.

**Closed by AaronVanGeffen** 2020-02-19 23:15 UTC
Labels: duplicate
