### ISSUE TITLE
Unable to use Nightly PPA to install on Ubuntu 22.04

### ISSUE THREAD

**Issue by cloudwitch** [OpenRCT2/OpenRCT2#18722] opened 2022-11-29 16:20 UTC
### Operating System

Ubuntu 22.04

### OpenRCT2 build

N/A

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

Issues building the game

### Describe the issue

I am unable to install Openrct2 on Ubuntu 22.04 using the nightly PPA.  I expected to be able to install a package called `openrct2` but only see the two below.  Looks like there was a [build failure](https://launchpadlibrarian.net/636532721/buildlog_ubuntu-jammy-amd64.openrct2_0.4.2-develop-0~3933-202211282017-g050f3f85a~ubuntu22.04.1_BUILDING.txt.gz) on the amd64 version which is the one I want to install.

```bash
➜  ~ sudo apt search openrct 
Sorting... Done
Full Text Search... Done
openrct2-objects/jammy,jammy 1.0.21+dfsg-3 all
  Object definitions for OpenRCT2

openrct2-title-sequences/jammy,jammy 0.1.2c-2 all
  Title sequences for OpenRCT2
```

### Steps to reproduce

1. Install PPA on Ubuntu 22.04 desktop.
2. Run `sudo apt install openrct2`
3. Unable to install.

**Comment by cloudwitch** [comment] 2022-11-29 16:27
And with the non-nightly, I get this pretty error because there are uninstallable packages as dependencies.  Installing `innoextract` as suggested does not help.

```bash
➜  ~ sudo apt -y install openrct2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openrct2 : Depends: libduktape206 (>= 2.0.3) but it is not installable
            Depends: libicu67 (>= 67.1-1~) but it is not installable
            Depends: libssl1.1 (>= 1.1.1) but it is not installable
            Recommends: innoextract but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by janisozaur** [comment] 2022-11-29 19:44
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/16691

**Closed** 2022-11-29 19:44 UTC
Labels: bug
