### ISSUE TITLE
'invalid name for park' shown when opening a scenario

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7367] opened 2018-03-31 20:24 UTC
**OS:** Windows 8
**Version:** e.g. 0.1.3
**Commit/Build:** 69bb1cd

Since updating, every scenario I open begins with a 'invalid name for park' error. This isn't a big deal at all -- as soon as I click anything, the error vanishes and it doesn't seem to have any ill effects. Just a little bit annoying and weird.

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. Open any scenario

![screenshot_1522527643](https://user-images.githubusercontent.com/26573303/38167233-cbcd39c8-34e6-11e8-8a82-e7ff06dd3079.png)

**Comment by AaronVanGeffen** [comment] 2018-03-31 20:33
It's been four days since #7343 was merged, which introduced `ParkSetNameAction`. Could this be a regression?

**Comment by ZehMatt** [comment] 2018-04-02 08:41
The issue appears to be that the string already exists, I'll add a check that prevents from executing the action if the ride name is identical.

**Closed** 2018-04-10 16:14 UTC
Labels: bug
