### ISSUE TITLE
Peeps waiting for train crossings results in unnecessarily frozen peeps

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#7938] opened 2018-08-27 15:53 UTC
Fun idea, that new bit of peep AI. Sadly it always affects every ride, and that's 'breaking' a lot of parks that have rides and paths on the same tile at the same height, that aren't supposed to operate like a train crossing. You can see for yourself in [Tubiao Action Park](https://www.nedesigns.com/park/4091/h2h8-r2-tubiao-action-park/) for example, around the zebra crossing the behaviour of the peeps looks ridiculous.

I'd really like it if this behaviour was a setting, per ride. I'd disable it for all rides default. If someone wants peeps waiting for trains, just check a box in the ride settings or something. Or put it in the options menu, affecting all rides that the player builds (and not all rides that are in the game). 

I just don't want any of these arbitrary creative decisions affecting parks that me and other people have been building over the past sixteen years.

Using v0.2.1-2 (4db9b36) on Windows 8. Is there an easier way to write down whatever the latest version is than waiting for the game to load in five minutes and typing over these random characters? Esepcially for when it's pretty meaningless like in this issue.

**Comment by Gymnasiast** [comment] 2018-08-27 17:09
I don't think it warrants a setting. Restricting it to just the miniature railway should help a lot already.

**Comment by AaronVanGeffen** [comment] 2018-08-27 17:09
Duplicate of #7690.

**Closed** 2018-08-27 20:32 UTC

**Comment by Broxzier** [comment] 2018-08-27 20:34
@Liampie the commit hash is not meaningless, especially not for issues like these.

> Is there an easier way to write down whatever the latest version is than waiting for the game to load in five minutes and typing over these random characters?

Yes. Run `openrct2.com --version`  to get the version info (from command line in the bin folder where openrct2.com is located).

**Comment by Liampie** [comment] 2018-08-27 23:56
How is this a duplicate? Jappy's issue is a bug, this is not a bug but a side-effect.

**Comment by AaronVanGeffen** [comment] 2018-08-28 08:49
@Liampie As was noted elsewhere, both issues will be resolved by constraining the peeps' waiting behaviour to just miniature railway tracks.

**Comment by Liampie** [comment] 2018-08-28 10:37
I didn't catch that, but fair enough! Thanks. :)

**Comment by Gymnasiast** [comment] 2019-08-04 11:05
Another one: https://www.nedesigns.com/park/4013/riverland/download/
