### ISSUE TITLE
Item colours of the invension list are coloured incorrectly

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#13653] opened 2020-12-27 14:03 UTC
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 556c786

Some text's colours are coloured incorrectly.
You may check it via invension list.

It can even be discovered in the title sequence's New game button in Korean.

**Steps to reproduce:**
1. Enable the cheat button in the options
2. Open the Invension list menu
3. See the items' colour
4. Or, set into Korean, go to the title sequence and hover it the "New Game" button.

**Screenshots / Video:**
Invension list in English:
![image](https://user-images.githubusercontent.com/10726524/103172419-93638800-4896-11eb-9579-ea723a3adc05.png)

Invension list in Korean:
![image](https://user-images.githubusercontent.com/10726524/103166369-a78e9180-4864-11eb-9021-f9011fd22030.png)

Title sequence in Korean:
![image](https://user-images.githubusercontent.com/10726524/103172448-e2112200-4896-11eb-8765-bd1aed3e0ade.png)

(There is no problem with title sequence in english)

**Comment by csunday95** [comment] 2020-12-27 19:13
Sorry, its a bit unclear to me what exactly is incorrect. In the invention list do you expect the text items to be a different color? And if so, why?

**Comment by telk5093** [comment] 2020-12-28 02:09
@csunday95 Yes, the texts should be coloured like below:
![image](https://user-images.githubusercontent.com/10726524/103184873-318a3900-48fd-11eb-9009-7c4edf115a86.png)
![image](https://user-images.githubusercontent.com/10726524/103184859-20d9c300-48fd-11eb-844e-06db23ac743f.png)

**Comment by csunday95** [comment] 2020-12-28 23:44
I did a little digging on this, and it seems that the line

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/EditorInventionsList.cpp#L634
`colour = COLOUR_BRIGHT_GREEN | COLOUR_FLAG_TRANSLUCENT;`

in the invention editor window is to blame. I'm not sure what changed since 0.3.2 release and the current develop that would affect this, but it seems that the green is now being _properly_ displayed. Strangely, there's a comment on the prior line 

`// TODO: this is actually just a black colour.`

which is a bit confusing. Tracing through the text drawing code, it appears that the text color here will be pulled from a palette in the G1 file. Simply changing the line to 

`colour = COLOUR_BRIGHT_BLACK | COLOUR_FLAG_TRANSLUCENT;`

seems to be insufficient, however, as the current text drawing code pulls a very light version of "black" from the palette based on using the `colour_11` index. This occurs in the `colour_char_window()` function in the Drawing.String.cpp file. The likely candidates I can think of for why this may have broken are:

1) the color value in the palette stored at the color_11 index of the `COLOUR_BRIGHT_GREEN` color changed from black to a more appropriate light color green at some point. 
2) the code that handles default color selection from a palette has changed

I think somebody more familiar with the text drawing code would need to take a close look at this, as I'd be a bit reluctant to unilaterally change such core code that I'm looking at for the first time.

**Comment by Gymnasiast** [comment] 2020-12-29 20:00
This problem is most likely caused by the new formatting framework.

**Comment by tupaschoal** [comment] 2020-12-29 20:54
> This problem is most likely caused by the new formatting framework.

Yep, I was bisecting it but there are too many broken commits in the format PR, in any case, here's the list of culprits, all of which I think are from it:
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
c6152efa4ef58d6728c346dbdcd4ad26c41e762d
1e5d9983387fcce189eac6fb1c2774c36a00e338
80537832e987d5c97d037a69470eac9c5787381a
2f7c1aab14cacfc1e9939419bb32da551baa2afc
711ac7675326e8b64894f07a4ddad1b8d1e967dc
157c984d4cf87291b583238550bd91cebe93ce94
eebababa90b2d708d3f518faabe17fe201ce9882
644f7f07b3b4f8ae94f2e9b212d460406175423c
b6a688e5400d48dc228d05a8d876fbf70f66cb21
6294188e9327d8f1199f313a92c3e6a8b4e17306
92fcdfbd9b5c72774ffd11f61453b92b88beb6d2
2847ac556ad40c5c981b8922a8892b0583c41d17
6c23da49657b0ef47cc1d85462c23c925d1b8b6d
43842bb668452107ccc82c33a76b2067af6c36fa
c7fea71db576882463769b40d3968aa5f1bf42b4
0e0c581258a776e4d9777fd2b8cc102cc793876d
167aaac633c73bd22f232340cb9387d5fafce2f4
fd605d7399a686c08c55df9c9bc8cb72e3944238

**Comment by Gymnasiast** [comment] 2021-01-02 20:11
The tooltip issue is separate - that is down to scrubbing the language files a little bit too hard. I have that in Localisation ( https://github.com/OpenRCT2/Localisation/commit/182f33b7e52be622439f092a45160bae570203d5 ) and it should be merged into `develop` in 7 to 8 hours.

**Closed** 2021-01-03 13:06 UTC
Labels: bug, user interface
