### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by WhenPenguinsAttack** [OpenRCT2/OpenRCT2#4704] opened 2016-10-25 23:53 UTC
Random multiplayer crash happened on a server I was on- putting it here so the devs can take a look at it if they want to.

**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 5.699b9e

- [x] Multiplayer?

**Steps to reproduce:**

None, because I have no idea what happened- the server was running normally, and I was not doing anything at the time other then looking at the park, and I am not aware of anything anyone else was doing in the park at the time.

~~**Dump file**
[501216d0-eb6b-4714-a306-2b85458be2a1(dd63caf).zip](https://github.com/OpenRCT2/OpenRCT2/files/552023/501216d0-eb6b-4714-a306-2b85458be2a1.dd63caf.zip)

**Save game:**
[501216d0-eb6b-4714-a306-2b85458be2a1.zip](https://github.com/OpenRCT2/OpenRCT2/files/552024/501216d0-eb6b-4714-a306-2b85458be2a1.zip)~~

Wrong files, see below for right files.

**Comment by Nubbie** [comment] 2016-10-26 09:12
@WhenPenguinsAttack Please update your game first and try again as this build is **2 months old**

**Comment by WhenPenguinsAttack** [comment] 2016-10-26 09:30
That's odd.  I updated to the latest version just before that.  I'll check again today.

**Comment by Nubbie** [comment] 2016-10-26 09:32
The dump file is using the version 501216d0-eb6b-4714-a306-2b85458be2a1(**dd63caf**) which might indicate it's not updated/wrong dump file

**Comment by WhenPenguinsAttack** [comment] 2016-10-27 00:59
@Nubbie 

Found the right files.

[b0da588e-44e0-4728-95ac-93a6d0c44b76.zip](https://github.com/OpenRCT2/OpenRCT2/files/554728/b0da588e-44e0-4728-95ac-93a6d0c44b76.zip)

[b0da588e-44e0-4728-95ac-93a6d0c44b76(5699b9e_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/554729/b0da588e-44e0-4728-95ac-93a6d0c44b76.5699b9e_x86-64.zip)

**Comment by Nubbie** [comment] 2016-10-27 14:39
Duplicate off #4708 it seems:

**Error message;**
Unhandled exception thrown: read access violation.
info->y_offset was 0xFFFFFFFFFFFFFFFF.

**Call Stack;**
```
>	openrct2.exe!ttf_draw_character_sprite(rct_drawpixelinfo * dpi=0x0000007edfcff540, int codepoint, text_draw_info * info=0x0000007edfcff558) Line 921	C
 	openrct2.exe!ttf_draw_string_raw_sprite(rct_drawpixelinfo * dpi=0x0000007edfcff540, const char * text, text_draw_info * info=0x0000007edfcff558) Line 936	C
 	openrct2.exe!ttf_process_glyph_run(rct_drawpixelinfo * dpi=0x0000007edfcff540, const char * text, text_draw_info * info=0x0000007edfcff558) Line 1180	C
 	openrct2.exe!ttf_process_string(rct_drawpixelinfo * dpi=0x0000007edfcff540, const char * text, text_draw_info * info=0x0000007edfcff558) Line 1197	C
 	openrct2.exe!paint_draw_money_structs(rct_drawpixelinfo * dpi, paint_string_struct *) Line 1056	C
 	openrct2.exe!viewport_paint_column(rct_drawpixelinfo * dpi=0x0000007edfcff7b0, unsigned int viewFlags) Line 764	C
 	openrct2.exe!viewport_paint(rct_viewport * viewport, rct_drawpixelinfo * dpi, short left=-1495, short top, short right=-901, short bottom=2435) Line 734	C
 	openrct2.exe!viewport_render(rct_drawpixelinfo * dpi=0x0000007edfcff8d0, rct_viewport * viewport, int left=128, int top=0, int right=64635, int bottom=2435) Line 664	C
 	openrct2.exe!window_main_paint(rct_window * w, rct_drawpixelinfo * dpi) Line 98	C
 	openrct2.exe!window_draw_single(rct_drawpixelinfo * dpi, rct_window * w=0x00007ff7b928d300, int left, int top, int right=722, int bottom=128) Line 1689	C
 	openrct2.exe!window_draw(rct_drawpixelinfo * dpi=0x0000007edfcff990, rct_window * w=0x00007ff7b928d300, int left=128, int top=0, int right=722, int bottom=128) Line 1584	C
 	openrct2.exe!window_draw_all(rct_drawpixelinfo * dpi, short left, short top, short right, short bottom) Line 460	C
 	openrct2.exe!SoftwareDrawingEngine::DrawAllDirtyBlocks() Line 572	C++
 	openrct2.exe!SoftwareDrawingEngine::Draw() Line 391	C++
 	openrct2.exe!openrct2_loop(...) Line 475	C
 	openrct2.exe!openrct2_launch(...) Line 344	C
 	openrct2.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x000000000000000a, char * lpCmdLine=0x0000000000000000, int nCmdShow=0) Line 75	C
 	[External Code]	
```

**Locals;**
```
		characterWidth	6	int
		codepoint	Variable is optimized away and not available.	
+		dpi	0x0000007edfcff540 {bits=0x0000027021895927 <Error reading characters of string.> x=-1376 y=2307 ...}	rct_drawpixelinfo *
+		info	0x0000007edfcff558 {startX=64179 startY=64179 x=64179 ...}	text_draw_info *
		sprite	Variable is optimized away and not available.	
		x	64179	int
		y	2422	int
```

**Autos;**
```
		TEXT_DRAW_FLAG_Y_OFFSET_EFFECT	TEXT_DRAW_FLAG_Y_OFFSET_EFFECT (536870912)	<unnamed-enum-TEXT_DRAW_FLAG_INSET>
+		info	0x0000007edfcff558 {startX=64179 startY=64179 x=64179 ...}	text_draw_info *
		info->flags	536870914	int
		info->x	64179	int
		info->y	2422	int
		x	64179	int
		y	2422	int
```

**Closed** 2016-10-28 21:01 UTC
