### ISSUE TITLE
FPS drops to almost zero when mass-adding staff

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#3840] opened 2016-06-08 14:46 UTC
**OS:** OS X
**Version:** 0.0.5.0-develop build 84334c1
**Commit:** 84334c1485f1eaf9e3e4530210f2606ddf032eb5

My FPS drops to almost zero when I mass-add staff to my park. I have auto placement on. Saving and loading the save makes the FPS normal again.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Add a lot of staff members by repeatedly pressing the button.
2. Watch how the game slows down to almost zero FPS, making it unplayable.

**Comment by Nubbie** [comment] 2016-06-08 14:51
Duplicate of: #3746 
It's because new windows opens up on top of each other which makes the FPS drop the more windows you get

PR #3805 is fixing that by setting a window how many windows the game can have up the same time

**Closed** 2016-06-08 14:55 UTC
Labels: duplicate
