### ISSUE TITLE
Coaster Train Issues

### ISSUE THREAD

**Issue by satdav** [OpenRCT2/OpenRCT2#3931] opened 2016-06-20 12:25 UTC
**OS:** Windows 10 
**Version:** 0.0.5
**Commit/Build:** c177cc7 

[Explanation of the issue...]

- [ ] Reproducible in RCT2 (vanilla)? 
- [ ] Multiplayer?

**Steps to reproduce:**
1. [step 1] I opened a new game what I created and it wont let me to remove any trains from the ride or carriges, this is happening sometimes with the game 
2. [step 2] I have tried on the water coaster and the Limo one so far for this to happen

**Comment by mrtnptrs** [comment] 2016-06-20 12:38
Can you provide us with a save file which is affected by the problem? Can you also further explain what the issue is/in more detail?

**Comment by satdav** [comment] 2016-06-20 12:47
Issue is me lol I see it does not have the drop down like the old versions its a little side button lol

**Comment by Gymnasiast** [comment] 2016-06-20 13:02
Please write more clearly. I have requested this several times, as we only understand about half of what you're saying. Use punctuation and explain things more clearly. Enclosing a screenshot showing your problem is also usually a good idea, so please do so.

**Comment by pizza2004** [comment] 2016-06-20 15:52
You guys can close this issue.  He's saying he was unable to reduce the number of trains on a ride, which he thought was a bug, but instead it was just him not seeing that the dropdown had been changed to the up and down arrows.  He was just tripped up by a change in UI is all.

**Closed** 2016-06-20 16:20 UTC
