### ISSUE TITLE
Windows stable and portable version: no changelog at start

### ISSUE THREAD

**Issue by legluondunet** [OpenRCT2/OpenRCT2#10160] opened 2019-10-29 20:20 UTC
Hello,
not very important issue but the changelog does not show on first OpenRCT2 launch, latest stable windows 0.2.4 version (64 bits portable).

**Comment by AaronVanGeffen** [comment] 2019-10-29 20:27
Thanks for taking the time to file an issue. This is odd though, because the changelog.txt file is included — in the portable release at least. The changelog is supposed to only be loaded once, though. Is it possible you missed it when you first launched a version of the game that identifies as v0.2.4?

Just to clarify, what file did you use to install the release? A link to the source file will do.

**Comment by IntelOrca** [comment] 2019-10-29 20:30
GetDocsPath is not implemented for Windows. This needs to be set to `GetInstallPath`

**Comment by legluondunet** [comment] 2019-10-30 12:58
Is it possible you missed it when you first launched a version of the game that identifies as v0.2.4?
Nope, I can reproduce this issue at each first launch.
Just to clarify, what file did you use to install the release? A link to the source file will do.
latest stable windows 0.2.4 version (64 bits portable) from official OpenRCT2 page:
https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.2.4/OpenRCT2-0.2.4-windows-portable-x64.zip

**Comment by ZehMatt** [comment] 2019-10-30 14:42
It appears that the function GetChangelogPath results "data\changelog.txt" but the changelog.txt sits in the root directory. I assume on linux this would be copied into the data directory?

**Comment by legluondunet** [comment] 2019-10-30 17:47
@ZehMatt in the doc directory located in the game root directory.

**Comment by legluondunet** [comment] 2019-11-01 21:31
could it be possible to move all txt files from windows version to a doc folder, like for linux? It is more easier for contributor if all release follow the same schema, isn't it?

**Comment by AaronVanGeffen** [comment] 2019-11-01 21:57
It doesn't really matter in what folder the file is, as long as OpenRCT2 is looking in it. Which folders are looked in currently depends on the platform, anyway.

**Comment by ZehMatt** [comment] 2020-02-13 07:47
We should have this fixed for the next version, added milestone.

**Comment by Gymnasiast** [comment] 2020-02-13 08:55
Appears to be a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/6766.

**Closed** 2020-03-17 20:35 UTC
Labels: bug
