### ISSUE TITLE
Edge case where Resolutions don't work correctly: Overscan Corrected Displays (nVidia 750 Ti)

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1048] opened 2015-05-07 23:38 UTC
![screenres](https://cloud.githubusercontent.com/assets/3945538/7528032/95ef7a16-f4f0-11e4-81b3-66407fdc0b3c.png)

The actual resolution of the screen is 1824x1036.

**Comment by IntelOrca** [comment] 2015-05-08 01:22
It works for me still. Did you have more than one monitor?

**Comment by PFCKrutonium** [comment] 2015-05-08 01:24
Nope, it's just plugged into a HDTV.

**Comment by IntelOrca** [comment] 2015-08-03 17:56
Seems to also happen when Windows is not 100% DPI scale and openrct2.exe is not set to disable DPI scaling.

**Comment by mrtnptrs** [comment] 2016-06-18 12:53
I have seen this bug quite a lot of times in the past, but isn't this fixed now?

**Comment by IntelOrca** [comment] 2016-09-30 11:12
@PFCKrutonium can you still reproduce this?

**Closed** 2017-07-04 11:49 UTC
Labels: bug
