### ISSUE TITLE
Minimum Energy Cheat Bug

### ISSUE THREAD

**Issue by roboexplorer** [OpenRCT2/OpenRCT2#6196] opened 2017-08-17 19:12 UTC
**OS: Windows 10**
**Version: 0.1.2-develop**
**Commit/Build: 6547116**

Setting guests' energy to minimum using cheats causes their energy to be set at minimum as intended but receive a sudden energy boost after a second or two. The energy bar will also be off the screen when observing guest stats when it happens.

- [ Y ] Reproducible in RCT2 (vanilla)?
- [ Y ] Multiplayer?

**Steps to reproduce:**
1. Have any number of guests in the park
2. Set guests' energy to minimum using cheats

**Screenshots / Video:**
<img width="607" alt="superenergy" src="https://user-images.githubusercontent.com/31110139/29429286-28364654-835e-11e7-88eb-d236218839e1.png">

**Comment by janisozaur** [comment] 2017-08-17 19:29
Must be a case of nuclear Gandhi.

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by roboexplorer** [comment] 2017-08-17 19:48
I wish to add further to this bug:
Energy drain (and/or gain?) isn't working correctly with this same build. Opened a random scenario (screenshot of Six Flags Great Belgium) and multiple guests had more energy than is allowed. I tried to tire some guests out to see if their energy decreases but I could not even tire a guest to minimum by restricting them on a single path tile at turbo speed. Their energy does not decrease from their intended maximum. Similar situation with multiplayer as well.

Six Flags Great Belgium:
![](https://i.gyazo.com/231c3556748714c57aa27f8215ed7c73.png)

**Comment by 60trainhunter** [comment] 2017-08-17 19:48
guests wont ever lose energy either without cheat.

**Comment by Gymnasiast** [comment] 2017-10-05 10:27
Issue was caused by using `max(MAX_ENERGY, proposed_energy_level)`, rather than the intended min. So the code that was intended to prevent overflows would not do so, and at the same time would make sure energy never dropped below the max of 128! This explains both @roboexplorer 's and @60trainhunter 's issues.

A PR with a fix has been opened.

**Closed** 2017-10-10 08:07 UTC
Labels: bug
