### ISSUE TITLE
Rusty Track

### ISSUE THREAD

**Issue by Wimali** [OpenRCT2/OpenRCT2#2366] opened 2015-11-22 23:14 UTC
As rides deteriorate over time, the nice bright paint finish will peel off the steel track to reveal rusty and bare metal, and require re-painting. As originally intended (but later abandoned) by Chris Sawyer.

Example picture from the game's concept art here: http://i.imgur.com/aMcWHjC.gif

**Comment by Gymnasiast** [comment] 2015-11-23 09:28
I find this irritating.

Also a duplicate of #663.

**Closed** 2016-03-23 14:42 UTC
Labels: alteration

**Comment by Patrik356b** [comment] 2016-03-24 12:40
This might be a mod later. I don't like it as a default thing

**Comment by Joshwoo69** [comment] 2016-03-24 16:47
Yeah same as patrik.
