### ISSUE TITLE
Able to change music in Merry Go Round ride

### ISSUE THREAD

**Issue by harrysbird** [OpenRCT2/OpenRCT2#14654] opened 2021-05-14 05:15 UTC
I Clicked the Merry go round and I Want to change it and It's can only select Fairground organ style and please allow to change because so player don't like play this music too much without having turning off the merry go round music.
![Merry Go Round](https://user-images.githubusercontent.com/3393747/118224800-b56e3900-b438-11eb-9d41-6fa74e5eede1.png)

I Think that will be for new save format for this.

**Comment by IntelOrca** [comment] 2021-05-14 08:49
There are two ways you can already achieve this:
* Using cheats, change the ride type to something else temporarily so you have the full music selection.
* Use a plugin / or script command to change the music for the ride.

**Comment by Margen67** [comment] 2021-05-14 10:15
#14511

**Comment by Gymnasiast** [comment] 2021-05-14 10:22
Closing as duplicate of #14511.

**Closed by Gymnasiast** 2021-05-14 10:22 UTC
Labels: duplicate
