### ISSUE TITLE
BACKTRACE b97c19 track_block_get_next

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8172] opened 2018-10-27 14:44 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/b97c190bf1cf5e0ccad68c6646929fbaf6a8a01f3e1783c53d843a672cc873c5?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Oct 27 2018 14:06:13)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>track_block_get_next -> vehicle_update_track_motion_mini_golf -> vehicle_update_departing -> vehicle_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 22:13
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8398

**Closed by janisozaur** 2019-02-02 22:13 UTC
Labels: backtrace.io, crash
