### ISSUE TITLE
Invalid sprite access in vehicle_update_track_motion_mini_golf

### ISSUE THREAD

**Issue by greenwalt98** [OpenRCT2/OpenRCT2#4714] opened 2016-10-27 18:43 UTC
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.5]
**Commit/Build:** [e.g. b32e2ea]

 After only 10 seconds of play this pops up. Happen the past 2 updates.
- [ X] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**
[496a8fc3-6fe9-4fb3-9ec8-382d15fc92af(b32e2ea_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/556709/496a8fc3-6fe9-4fb3-9ec8-382d15fc92af.b32e2ea_x86-64.zip)

**Screenshots / Video:**

![error1](https://cloud.githubusercontent.com/assets/23105731/19780519/4fd4b01c-9c53-11e6-9d6a-53543a2c5a75.png)

![error2](https://cloud.githubusercontent.com/assets/23105731/19780533/626b9db2-9c53-11e6-9abe-7c54504a8d64.png)

**Comment by Nubbie** [comment] 2016-10-27 20:06
@greenwalt98 seems like the mini golf is messing it up, try removing it to play on the save

------
To devs;

**Error Message;**
Unhandled exception at 0x00007FF661E5B680 (openrct2.exe) in 496a8fc3-6fe9-4fb3-9ec8-382d15fc92af(b32e2ea_x86-64).dmp: 0xC0000005: Access violation reading location 0x00007FF66362EA3C.

**Call stack;**
```
>	openrct2.exe!vehicle_update_track_motion_mini_golf(rct_vehicle * vehicle=0x00007ff66267cea0, int * outStation=0x0000000000000000) Line 8144	C
 	openrct2.exe!vehicle_update_track_motion(rct_vehicle * vehicle=0x00007ff66267cda0, int * outStation=0x0000000000000000) Line 8571	C
 	openrct2.exe!vehicle_update_travelling(rct_vehicle * vehicle=0x00007ff66267cda0) Line 3158	C
 	openrct2.exe!vehicle_update(rct_vehicle * vehicle=0x00007ff66267cda0) Line 1645	C
 	openrct2.exe!vehicle_update_all(...) Line 1058	C
 	openrct2.exe!game_logic_update(...) Line 380	C
 	openrct2.exe!game_update(...) Line 298	C
 	openrct2.exe!rct2_update(...) Line 473	C
 	openrct2.exe!openrct2_loop(...) Line 469	C
 	openrct2.exe!openrct2_launch(...) Line 344	C
 	openrct2.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x000000000000000a, char * lpCmdLine=0x0000000000000000, int nCmdShow=0) Line 75	C
 	[External Code]	
```

Autos;
```
		VEHICLE_ENTRY_FLAG_B_9	VEHICLE_ENTRY_FLAG_B_9 (512)	<unnamed-enum-VEHICLE_ENTRY_FLAG_B_0>
+		rideEntry	0x000001852b2053e0 {name=??? description=??? images_offset=??? ...}	rct_ride_entry *
+		rideEntry->vehicles	0x000001852b2053fa {{rotation_frame_mask=??? var_02=??? var_03=??? ...}, {rotation_frame_mask=??? var_02=...}, ...}	rct_ride_entry_vehicle[4]
+		rideEntry->vehicles[0]	{rotation_frame_mask=??? var_02=??? var_03=??? ...}	rct_ride_entry_vehicle
+		vehicle	openrct2.exe!0x00007ff66267cea0 {sprite_identifier=0 '\0' is_child=1 '\x1' next_in_quadrant=1251 ...}	rct_vehicle *
		vehicle->swinging_car_var_0	0	short
		vehicle->var_4A	0 '\0'	unsigned char
		vehicle->vehicle_sprite_type	0 '\0'	unsigned char
```

**Comment by greenwalt98** [comment] 2016-10-27 20:16
@Nubbie You got it. Appreciate it!

**Comment by Nubbie** [comment] 2016-10-27 20:24
@greenwalt98 The issue still needs to be resolved so please don't close it :p

**Comment by Gymnasiast** [comment] 2016-10-28 07:04
Could you upload your save?

**Comment by janisozaur** [comment] 2016-11-04 21:33
@Gymnasiast it's in the zip and hits the assert.

**Comment by duncanspumpkin** [comment] 2016-11-05 08:46
This is caused by closing the ride just before the peep has started his round of golf. The peep leaves the ride but the vehicle (the ball still thinks it needs to do a circuit). I'm still trying to work out why the vehicle still sets off without a peep.

**Comment by duncanspumpkin** [comment] 2016-11-09 19:01
Okay thats the bug fixed. Instead of crashing it will display a phantom player that consists of just the ball.

**Closed** 2016-11-09 19:00 UTC
Labels: original bug
