### ISSUE TITLE
Crash at loading online games

### ISSUE THREAD

**Issue by chrisklunder** [OpenRCT2/OpenRCT2#3976] opened 2016-07-03 10:49 UTC
[Fill in the placeholders below. Delete any headings and placeholders that you do not fill in. Delete this line as well]

**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.5]
**Commit/Build:** [e.g. 426e106]

[Game crashes constantly upon loading a multiplayer game.]

- [ ] Reproducible in RCT2 (vanilla)?
- [X ] Multiplayer?

**Steps to reproduce:**
1. [step 1]
2. [step 2]

**Dump file**
[If you have a dump file: zip it before you drag & drop it here.]

**Screenshots / Video:**
[Drag & drop screenshots here. Use https://vid.me to upload video.]

**Save game:**
[Change the file extension to .txt or package to a .zip so that it can be drag & dropped here...]

[5f9c32ae-cf69-46cb-9005-20da8d8c7808.txt.zip](https://github.com/OpenRCT2/OpenRCT2/files/344983/5f9c32ae-cf69-46cb-9005-20da8d8c7808.txt.zip)

**Comment by Patrik356b** [comment] 2016-07-03 13:32
Delete unused placeholders and correctly fill in what windows and what build/commit your using (this is visible in the bottom left corner at the main menu)

**Comment by Nubbie** [comment] 2016-07-03 15:36
To devs from dump file provided by OP

Unhandled exception thrown: read access violation.
object was 0xE24F925.

```
>	openrct2.dll!set_load_objects_fail_reason(...) Line 524	C
 	openrct2.dll!game_load_network(SDL_RWops * rw=0x07763658) Line 493	C++
 	openrct2.dll!Network::Client_Handle_MAP(NetworkConnection & connection={...}, NetworkPacket & packet={...}) Line 1615	C++
 	openrct2.dll!Network::ProcessPacket(NetworkConnection & connection={...}, NetworkPacket & packet={...}) Line 1247	C++
 	openrct2.dll!Network::ProcessConnection(NetworkConnection & connection={...}) Line 1205	C++
 	openrct2.dll!Network::UpdateClient() Line 479	C++
 	openrct2.dll!rct2_update(...) Line 452	C
 	openrct2.dll!openrct2_loop(...) Line 456	C
 	openrct2.dll!openrct2_launch(...) Line 328	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x0150377e, int nCmdShow=10) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Autos:** (gCommonFormatArgs are full of gibberish, corrupt file?)
```
+		gCommonFormatArgs	0x612e6ae0 "%ù$\xeMEDIPATHòoV\x10"	unsigned char[80]
-		object	0x0e24f925 {flags=??? name=0x0e24f929 <Error reading characters of string.> checksum=??? }	rct_object_entry *
		flags	<Unable to read memory>	
-		name	0x0e24f929 <Error reading characters of string.>	char[8]
		[0]	<Unable to read memory>	
		[1]	<Unable to read memory>	
		[2]	<Unable to read memory>	
		[3]	<Unable to read memory>	
		[4]	<Unable to read memory>	
		[5]	<Unable to read memory>	
		[6]	<Unable to read memory>	
		[7]	<Unable to read memory>	
		checksum	<Unable to read memory>	
```

Locals;
```
		expansion	Variable is optimized away and not available.	
		expansionNameId	35916	unsigned short
-		object	0x0e24f925 {flags=??? name=0x0e24f929 <Error reading characters of string.> checksum=??? }	rct_object_entry *
		flags	<Unable to read memory>	
+		name	0x0e24f929 <Error reading characters of string.>	char[8]
		checksum	<Unable to read memory>	
```

**Comment by janisozaur** [comment] 2016-07-03 20:16
Dupe of #3909

**Closed by janisozaur** 2016-07-03 20:16 UTC
