### ISSUE TITLE
Undo and Redo buttons in OpenRCT2

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#2978] opened 2016-02-19 20:17 UTC
In case somebody makes a mistake in OpenRCT2 like when somebody is editing a scenario in scenario editor and somebody accidentally modify hills and deletes something, there should be an undo button in game. If somebody accidentally undoes something or changes his mind, there should be a redo button in game. So what do you think of this idea developers?

**Comment by danidoedel** [comment] 2016-02-19 21:43
Duplicate of  #2256

**Closed** 2016-02-19 21:45 UTC
Labels: duplicate
