### ISSUE TITLE
Invalid memory access in DrawRLESprite2<0,0>

### ISSUE THREAD

**Issue by max95812** [OpenRCT2/OpenRCT2#4710] opened 2016-10-26 13:03 UTC
OS: **Windows 10**
Version: **0.0.5**
Commit/Build: **5699b9e**

Crashed when (maybe after) loading a map from server

**Steps to reproduce:**
I can't reproduce it.
I was able load the saved game (attached below) and joined the server.
- [ ] Reproducible in RCT2 (vanilla)? - I don't think so (Multiplayer)
- [x] Multiplayer?

**Dump file**
[ccc3b912-c009-4aba-afbb-0e094dc99f4f(5699b9e_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/553272/ccc3b912-c009-4aba-afbb-0e094dc99f4f.5699b9e_x86-64.zip)

**Save game:**
[ccc3b912-c009-4aba-afbb-0e094dc99f4f.zip](https://github.com/OpenRCT2/OpenRCT2/files/553273/ccc3b912-c009-4aba-afbb-0e094dc99f4f.zip)

**Comment by Nubbie** [comment] 2016-10-26 17:53
What I extracted from the dumpfile

**Error message;**
Unhandled exception at 0x00007FF747A226E4 (openrct2.exe) in ccc3b912-c009-4aba-afbb-0e094dc99f4f(5699b9e_x86-64).dmp: 0xC0000005: Access violation reading location 0x000002367F43F834.

**Call stack;**
```
>	openrct2.exe!DrawRLESprite2<0,0>(const unsigned char * source_bits_pointer=0x000002367f4321cb, unsigned char * dest_bits_pointer=0x000002367f438e65, const unsigned char * dpi, const rct_drawpixelinfo * source_y_start=1201405952, int height=47, int source_x_start=0, int width=45, int) Line 68	C++
 	openrct2.exe!gfx_rle_sprite_to_buffer(const unsigned char * source_bits_pointer, unsigned char * dest_bits_pointer, const unsigned char * palette_pointer, const rct_drawpixelinfo * dpi, int image_type=0, int source_y_start=0, int height=47, int source_x_start=0, int width=45) Line 203	C++
 	openrct2.exe!gfx_draw_sprite_palette_set_software(rct_drawpixelinfo * dpi=0x0000023653ec2ac0, int image_id, int x=0, int y, unsigned char * palette_pointer=0x0000000000000000, unsigned char * unknown_pointer=0x0000000000000000) Line 499	C
 	openrct2.exe!TextureCache::GetImageAsDPI(unsigned int image=324331, unsigned int) Line 267	C++
 	openrct2.exe!TextureCache::LoadImageTexture(unsigned int image) Line 168	C++
 	openrct2.exe!TextureCache::GetOrLoadImageTexture(unsigned int image=324331) Line 63	C++
 	openrct2.exe!OpenGLDrawingContext::DrawSprite(unsigned int image=3195335403, int x, int y, unsigned int tertiaryColour=28961) Line 738	C++
 	openrct2.exe!paint_ps_image(rct_drawpixelinfo * dpi, paint_struct * ps, unsigned int imageId=3195335403, short x, short y=3666) Line 978	C
 	openrct2.exe!paint_draw_structs(rct_drawpixelinfo * dpi=0x0000007c86aff5f0, paint_struct * ps=0x00007ff7487a2880, unsigned int viewFlags=1024) Line 891	C
 	openrct2.exe!viewport_paint_column(rct_drawpixelinfo * dpi=0x0000007c86aff5f0, unsigned int viewFlags=1024) Line 755	C
 	openrct2.exe!viewport_paint(rct_viewport * viewport, rct_drawpixelinfo * dpi, short left=-9344, short top, short right=-224, short bottom=7976) Line 734	C
 	openrct2.exe!viewport_render(rct_drawpixelinfo * dpi=0x0000007c86aff710, rct_viewport * viewport, int left=0, int top=0, int right=65312, int bottom=7976) Line 664	C
 	openrct2.exe!window_main_paint(rct_window * w, rct_drawpixelinfo * dpi) Line 98	C
 	openrct2.exe!window_draw_single(rct_drawpixelinfo * dpi, rct_window * w=0x00007ff7487ed300, int left, int top, int right=1140, int bottom=871) Line 1689	C
 	openrct2.exe!window_draw(rct_drawpixelinfo * dpi=0x0000007c86aff7d0, rct_window * w=0x00007ff7487ed300, int left=0, int top=0, int right=1140, int bottom=871) Line 1584	C
 	openrct2.exe!window_draw_all(rct_drawpixelinfo * dpi, short left, short top, short right, short bottom) Line 460	C
 	openrct2.exe!OpenGLDrawingEngine::Draw() Line 342	C++
 	openrct2.exe!openrct2_loop(...) Line 442	C
 	openrct2.exe!openrct2_launch(...) Line 344	C
 	openrct2.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x000000000000000a, char * lpCmdLine=0x0000000000000000, int nCmdShow=0) Line 75	C
 	[External Code]	
 	[Frames may be missing, no binary loaded for ntdll.dll]	
 	ntdll.dll!00007ffa57e45e91()	Unknown
```

**Comment by duncanspumpkin** [comment] 2016-11-03 17:48
I can't load the save for some reason but from the call stack this is clearly crashing in the OpenGL renderer which is experimental at the moment.
For the mean time just avoid using the OpenGL renderer.

**Comment by AaronVanGeffen** [comment] 2018-01-17 11:18
I'm unable to reproduce this. The OpenGL code has also changed considerably in the last year. Combined with the @max95812 stating he's unable to reproduce the issue himself, I'm closing this.

**Closed by AaronVanGeffen** 2018-01-17 11:18 UTC
Labels: OpenGL, crash

**Comment by janisozaur** [comment] 2018-01-17 23:04
Just in case anyone needs it, here's the version with objects embedded: 
[4710_with_obj.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1640928/4710_with_obj.sv6.zip)
