### ISSUE TITLE
Wrong research list in Loopy Landscapes scenarios

### ISSUE THREAD

**Issue by MASHzj** [OpenRCT2/OpenRCT2#18963] opened 2022-12-29 01:00 UTC
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.3 (285e0fc on master) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

The description of Woodworm Park says that it's only possible to build "older-style" rides. But when playing for several in-game years, I get many rides which are clearly not old-style, like the motion simulator, 3D cinema and steel-type roller coasters. I checked on RCT wiki ([https://rct.fandom.com/wiki/Woodworm_Park](https://rct.fandom.com/wiki/Woodworm_Park)). According to this page, those rides should not be researched or available from the start (assuming this info is correct, the rides available from the start seem to correspond). On the other hand, the linked [scenario guide](https://rct.fandom.com/wiki/Woodworm_Park/Scenario_Guide) mentions the 3D cinema, which is not available in this scenario according to the main scenario page, and it's obviously not an old-style ride. So the writer of this guide probably has this issue too.

I also checked if this is the case with other scenarios. It looks like all RCT1 rides will be researched in all Loopy Landscape scenarios. For example: Iceberg Islands has the Swinging Inverter Ship and River Rafts in the inventions list, while not listed on the wiki page. Scenarios in the original/base RCT1 and in Corkscrew Follies don't seem to have this issue.

It is unclear to me if it has something to do with [this issue](https://github.com/OpenRCT2/OpenRCT2/issues/14439).

### Steps to reproduce

- Open Woodworm Park
- Fast forward until all rides have been researched, or open the inventions list

### Attachments

![2022-12-29](https://user-images.githubusercontent.com/121574637/209890265-080d3505-0f99-4216-85af-38472a2001ff.png)

**Comment by Gymnasiast** [comment] 2022-12-31 19:10
I have found the availability info on the wiki to be incorrect on quite a few occasions. The only reliable way is to check in Loopy Landscapes itself. You also linked to the old wiki, which is outdated. The RCT Wiki moved to https://rct.wiki last year. Though we haven’t yet corrected all data on that one either.

**Comment by MASHzj** [comment] 2023-04-08 17:12
First, I didn't know there is a new wiki. I often google scenario names to read the scenario guides, and then the old wiki always appears first. This new wiki is often not even not on the first page of Google. So I guess many other people don't know this either.

Again to this issue: after months of playing many RCT1 scenarios, I can provide some more information about this. Although I haven't checked in the original RCT1 game myself (as that would be very time consuming and boring, since there's no fast-forward or invention list cheat), I found some other things where it is clearly visible that the list of researchable items is not imported correctly.

- For **Woodworm Park**, I found [this video](https://www.youtube.com/watch?v=aANmA04NPgw&t=9214s). On 2:33:31 it's clearly visible that the only thrill rides in this scenario are the Twist, Swinging Ship and Go Karts, as thrill rides have all been researched. Also roller coasters have finished research, and more than one minute later you can see that only wood-type coaster are available to build. Also [this website] (https://tvtropes.org/pmwiki/pmwiki.php/ThatOneLevel/RollerCoasterTycoon) confirms this.
I found this issue: #10547. Is it possible that a similar thing happens here? As in: the rides are in the object selection, but hidden afterwards. But since hidden rides are not yet implemented in OpenRCT2 (#16455), they're added to the bottom of the invention list.

- I have an old save file of **Razor Rocks** from the original game. All research was finished. However, if you open this in OpenRCT2 and go to the research window, all categories except scenery/theming show as there are still items to invent. There are also rides in the park that aren't available yet in the ride construction window, like Enterprise and Balloon Stall. On the other hand, while all scenery groups show as researched, I used item of the Snow/ice and Abstract themes, while these groups are not available to build. When sandbox mode is enabled, the items I used show up in a miscellaneous tab, in a similar way like the mine objects in Forest Frontiers (in which case it's intended, but not here in Razor Rocks). In other scenarios I investigated, it's often the Snow/ice, Abstract and Pagoda themes that seem to be lacking, unless when they're available from start.
[Razor Rocks.zip](https://github.com/OpenRCT2/OpenRCT2/files/11183701/Razor.Rocks.zip)

I still only have observed this behaviour in Loopy Landscapes scenarios and in "Real parks" (probably those that come with LL). I tried to look into the code for this issue. I'm not familiar with it, but I found a comment on https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/rct1/S4Importer.cpp#L2459 ("Loopy Landscapes stores research items in a different place"). Might it be related to that? I don't know...

Anyway, I stopped playing Looping Landscapes scenarios as this is quite annoying to me because it really breaks the balance in some scenarios.

**Comment by ZeeMaji** [comment] 2023-05-11 14:02
This appears to be happening with any kind of save file that was saved in RCT1LL, not just LL's scenarios
Forest frontiers opened directly in OpenRCT2:
![Screenshot_select-area_20230511095815](https://github.com/OpenRCT2/OpenRCT2/assets/42477864/e0671c5a-3dd3-48f2-91e1-37af3ba40e9f)
Forest frontiers saved to a .sv4, then opened in OpenRCT2:
![Screenshot_select-area_20230511095849](https://github.com/OpenRCT2/OpenRCT2/assets/42477864/d9014f93-2b99-42cf-9f6e-57ce30257989)
Oddly enough it only seems to enable nearly all of the RCT1 base game's rides in base game scenarios, none of the AA/LL rides are enabled sans the b&m invert trains due to them being used for the inverted coaster ride type in the rct1 import table.
The only ones that are missing are the alternative vehicles like the car cars and bumper boats.

Test park incase it is of any use.
[LLForest Frontiers.SV4.tar.gz](https://github.com/OpenRCT2/OpenRCT2/files/11452962/LLForest.Frontiers.SV4.tar.gz)

**Comment by MASHzj** [comment] 2023-05-11 15:03
@ZeeMaji I have also a SV4-save of Forest Frontiers and I can confirm this. It seems to happen to all ride categories except shops & stalls (and scenery themes).

**Comment by MASHzj** [comment] 2023-05-11 15:08
Although strange that in the case of Razor Rocks there are actually _less_ rides than there should be.

**Comment by ZeeMaji** [comment] 2023-10-29 16:23
I did some research on this, OpenRCT2 used to correctly import LL research/available rides in 0.2.4 and earlier, but it was broken in 0.2.5

Opening woodworm park in 0.2.4 and looking at the invention list has the mini golf as the last item to research, but in 0.2.5 and later there's a bunch of rides after it.

After looking at the commit history of S4Importer.cpp it appears that this commit might be the culprit? #10556

**Comment by MASHzj** [comment] 2023-10-29 21:01
I remember someone saying exactly the same in discord a while ago when we had a discussion about this issue. So yes, it's quite likely because of that commit. So if the old code did import the research correctly, the fix may be relatively simple by doing something like this in pseudo-code:

`if (Loopy Landscapes scenario OR SV4 savefile){
    *old code*
} else {
    *current code*
}
`

But I could be totally wrong :)

**Comment by ZeeMaji** [comment] 2024-02-05 22:13
I've been doing some more research on this recently and i believe i've possibly found the culprit? There's two of them actually.

Firstly, the issue in razor rocks with there being less rides/scenery is being caused due to the full research table not being fully imported in RCT1LL scenarios. This should be fixed by #21130.

Secondly, the issue with too many rides being available seems to have been introduced in #11419. Removing the check for FILE_VERSION_RCT1_LL from the if statement introduced by this PR gets rid of all of the erroneous extra rides as the issue of research having vehicles that aren't actually vehicles still seems to apply to LL scenarios in contrary to the comment in the code.

Combining both of these fixes seems to fix research in RCT1LL import, i haven't tested every scenario yet but i can confirm that the research of iceberg isles, woodworm park, alton towers, and black pool pleasure beach are accurately imported after applying the fix from #21130 and removing the LL version check from the previously mentioned if statement. At least going by the RCT1 save game modifier program's research viewer which seems to be accurate?

**Comment by Gymnasiast** [comment] 2024-02-08 01:19
Fixes are ready in https://github.com/OpenRCT2/OpenRCT2/pull/21130 . Please test thoroughly and let me know the results.

**Closed** 2024-02-08 21:05 UTC
Labels: investigate, rct1
