### ISSUE TITLE
BACKTRACE 1dcd27 assert in rct_peep::UpdateRideAdvanceThroughEntrance

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8221] opened 2018-11-03 22:41 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/1dcd274f0ad032cd27aba55b2ad04115942f3eab5579912c150abdc81c4d1e0e?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Nov 03 2018 22:41:03)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 3aeb87b: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guard::Assert_VA -> openrct2_assert_fwd -> rct_peep::UpdateRideAdvanceThroughEntrance -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2018-11-05 06:10
```
dump_path: /var/coronerd//openrct2/openrct2/_objects/0000/tx.0078.dmp outfile: -
Classifier: invalid-write
Crash info:
	Application: openrct2.exe
	Crashed YES
	reason: EXCEPTION_ACCESS_VIOLATION_WRITE
	address: 0
Memory Regions:
Sysinfo:
	arch: amd64 family 6 model 26 stepping 4
	cpu_count: 8
	os: Windows NT windows 6.3.9600 
Modules:
	0x73520000 - 0x757de000	nvoglv64.dll 23.21.13.8813 (Warning no symbol, nvoglv64.pdb 6FAFFAF41C6B46D09084AB5988E8980F1)
	0x7ff75f7d0000 - 0x7ff75f7fc000	openrct2.exe 
	0x7ffbeeaf0000 - 0x7ffbefbd1000	openrct2.dll 
	0x7ffbf2f50000 - 0x7ffbf3048000	ddraw.dll 6.3.9600.17415
	0x7ffbf3050000 - 0x7ffbf317b000	opengl32.dll 6.3.9600.17415
	0x7ffbf5180000 - 0x7ffbf5189000	IconCodecService.dll 6.3.9600.17415
	0x7ffbf53b0000 - 0x7ffbf542e000	AudioSes.dll 6.3.9600.17415
	0x7ffbfb370000 - 0x7ffbfb38d000	ncryptsslp.dll 6.3.9600.18377
	0x7ffbfb970000 - 0x7ffbfb97c000	secur32.dll 6.3.9600.17415
	0x7ffbfc580000 - 0x7ffbfc58a000	rasadhlp.dll 6.3.9600.17415
	0x7ffbfe900000 - 0x7ffbfed57000	wininet.dll 11.0.9600.19155
	0x7ffbfed60000 - 0x7ffbff02a000	iertutil.dll 11.0.9600.19101
	0x7ffbff710000 - 0x7ffbff899000	dbghelp.dll 6.3.9600.17787
	0x7ffc009c0000 - 0x7ffc00a2b000	FWPUCLNT.DLL 6.3.9600.18229
	0x7ffc011c0000 - 0x7ffc01252000	mscms.dll 6.3.9600.18589
	0x7ffc016f0000 - 0x7ffc016fa000	winnsi.dll 6.3.9600.17415
	0x7ffc01700000 - 0x7ffc0172a000	IPHLPAPI.DLL 6.3.9600.18264
	0x7ffc02340000 - 0x7ffc024bf000	propsys.dll 7.0.9600.17415
	0x7ffc02a50000 - 0x7ffc02cb6000	nvspcap64.dll 3.13.1.30
	0x7ffc033f0000 - 0x7ffc0341e000	glu32.dll 6.3.9600.17415
	0x7ffc037f0000 - 0x7ffc03831000	icm32.dll 6.3.9600.18589
	0x7ffc03d20000 - 0x7ffc03d29000	dciman32.dll 6.3.9600.17415
	0x7ffc03f00000 - 0x7ffc03f32000	ntmarta.dll 6.3.9600.17415
	0x7ffc03fa0000 - 0x7ffc04010000	MMDevAPI.dll 6.3.9600.17415
	0x7ffc04050000 - 0x7ffc0407a000	WINMMBASE.dll 6.3.9600.17415
	0x7ffc04080000 - 0x7ffc040a2000	winmm.dll 6.3.9600.17415
	0x7ffc040b0000 - 0x7ffc040ba000	version.dll 6.3.9600.17415
	0x7ffc056e0000 - 0x7ffc0595b000	comctl32.dll 6.10.9600.18006
	0x7ffc05b60000 - 0x7ffc05b6c000	avrt.dll 6.3.9600.17415
	0x7ffc05db0000 - 0x7ffc05dc2000	wtsapi32.dll 6.3.9600.17415
	0x7ffc05dd0000 - 0x7ffc05f7e000	WindowsCodecs.dll 6.3.9600.19133
	0x7ffc05fd0000 - 0x7ffc05ff1000	dwmapi.dll 6.3.9600.17415
	0x7ffc06480000 - 0x7ffc06532000	SHCore.dll 6.3.9600.17666
	0x7ffc068d0000 - 0x7ffc069f9000	uxtheme.dll 6.3.9600.18835
	0x7ffc06a50000 - 0x7ffc06a78000	devobj.dll 6.3.9600.17415
	0x7ffc06aa0000 - 0x7ffc06aab000	kernel.appcore.dll 6.3.9600.17415
	0x7ffc06f90000 - 0x7ffc06fea000	winsta.dll 6.3.9600.17415
	0x7ffc070a0000 - 0x7ffc0710e000	schannel.dll 6.3.9600.18970
	0x7ffc07150000 - 0x7ffc07186000	rsaenh.dll 6.3.9600.18191
	0x7ffc07280000 - 0x7ffc072a1000	userenv.dll 6.3.9600.17415
	0x7ffc072b0000 - 0x7ffc072f6000	powrprof.dll 6.3.9600.17415
	0x7ffc07340000 - 0x7ffc073e4000	dnsapi.dll 6.3.9600.19060
	0x7ffc07540000 - 0x7ffc07599000	mswsock.dll 6.3.9600.18340
	0x7ffc075a0000 - 0x7ffc075c0000	cryptsp.dll 6.3.9600.17415
	0x7ffc07780000 - 0x7ffc077b7000	ntasn1.dll 6.3.9600.17415
	0x7ffc077c0000 - 0x7ffc077e5000	ncrypt.dll 6.3.9600.18970
	0x7ffc077f0000 - 0x7ffc07816000	bcrypt.dll 6.3.9600.18541
	0x7ffc07b10000 - 0x7ffc07b73000	bcryptPrimitives.dll 6.3.9600.18895
	0x7ffc07b80000 - 0x7ffc07b8b000	CRYPTBASE.dll 6.3.9600.17415
	0x7ffc07c40000 - 0x7ffc07c55000	profapi.dll 6.3.9600.17415
	0x7ffc07cf0000 - 0x7ffc07d01000	msasn1.dll 6.3.9600.17415
	0x7ffc07dc0000 - 0x7ffc07f9f000	crypt32.dll 6.3.9600.18653
	0x7ffc07fa0000 - 0x7ffc07fce000	sspicli.dll 6.3.9600.18454
	0x7ffc07fd0000 - 0x7ffc080e6000	KERNELBASE.dll 6.3.9600.18938
	0x7ffc080f0000 - 0x7ffc0813f000	cfgmgr32.dll 6.3.9600.17415
	0x7ffc08140000 - 0x7ffc08191000	wintrust.dll 6.3.9600.18508
	0x7ffc081a0000 - 0x7ffc083b2000	combase.dll 6.3.9600.19038
	0x7ffc08420000 - 0x7ffc084ca000	advapi32.dll 6.3.9600.18895
	0x7ffc084d0000 - 0x7ffc0857a000	msvcrt.dll 7.0.9600.17415
	0x7ffc08580000 - 0x7ffc08589000	nsi.dll 6.3.9600.17415
	0x7ffc08590000 - 0x7ffc086dc000	gdi32.dll 6.3.9600.19153
	0x7ffc086f0000 - 0x7ffc08867000	user32.dll 6.3.9600.18535
	0x7ffc08870000 - 0x7ffc088ca000	ws2_32.dll 6.3.9600.18340
	0x7ffc088d0000 - 0x7ffc08a10000	rpcrt4.dll 6.3.9600.19033
	0x7ffc08a20000 - 0x7ffc08bfa000	setupapi.dll 6.3.9600.17415
	0x7ffc08c00000 - 0x7ffc08cb6000	clbcatq.dll 2001.12.10530.17415
	0x7ffc08cc0000 - 0x7ffc0a1eb000	shell32.dll 6.3.9600.19125
	0x7ffc0a1f0000 - 0x7ffc0a384000	ole32.dll 6.3.9600.18895
	0x7ffc0a3b0000 - 0x7ffc0a404000	shlwapi.dll 6.3.9600.17415
	0x7ffc0a410000 - 0x7ffc0a469000	sechost.dll 6.3.9600.17734
	0x7ffc0a470000 - 0x7ffc0a536000	oleaut32.dll 6.3.9600.19003
	0x7ffc0a540000 - 0x7ffc0a67e000	kernel32.dll 6.3.9600.17415
	0x7ffc0a680000 - 0x7ffc0a736000	comdlg32.dll 6.3.9600.17415
	0x7ffc0a750000 - 0x7ffc0a786000	imm32.dll 6.3.9600.17415
	0x7ffc0a9c0000 - 0x7ffc0ab11000	msctf.dll 6.3.9600.18819
	0x7ffc0ab20000 - 0x7ffc0accd000	ntdll.dll 6.3.9600.19153
Threads:
	thread-0 tid=8256 faulted
	[0] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!Guard::Assert_VA(bool,char const *,char *) [c:\projects\openrct2-ject9\src\openrct2\core\guard.cpp : 108 + 0]
		
	[1] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!openrct2_assert_fwd(bool,char const *,...) [c:\projects\openrct2-ject9\src\openrct2\core\guard.cpp : 67 + 0x5]
	[2] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!rct_peep::UpdateRideAdvanceThroughEntrance() [c:\projects\openrct2-ject9\src\openrct2\peep\guest.cpp : 3599 + 0x14]
	[3] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!rct_peep::Update() [c:\projects\openrct2-ject9\src\openrct2\peep\peep.cpp : 1331 + 0x8]
	[4] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::GameState::UpdateLogic() [c:\projects\openrct2-ject9\src\openrct2\gamestate.cpp : 246 + 0xf9]
	[5] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::GameState::Update() [c:\projects\openrct2-ject9\src\openrct2\gamestate.cpp : 140 + 0x8]
	[6] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::Update() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 936 + 0xc]
	[7] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunVariableFrame() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 891 + 0x8]
	[8] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunGameLoop() [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 801 + 0x56]
	[9] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int,char const * *) [c:\projects\openrct2-ject9\src\openrct2\context.cpp : 213 + 0x8]
	[10] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!NormalisedMain(int,char const * *) [c:\projects\openrct2-ject9\src\openrct2-ui\ui.cpp : 60 + 0x13]
	[11] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!LaunchOpenRCT2(int,wchar_t * *) [c:\projects\openrct2-ject9\src\openrct2-dll\openrct2-dll.cpp : 46 + 0xf]
	[12] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.exe!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl : 288 + 0x22]
	[13] C:\Windows\System32\kernel32.dll + 0x13d2
	[14] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x34
	thread-1 tid=7604 
	[0] C:\Windows\System32\ntdll.dll!NtGetContextThread + 0xa
		
	thread-2 tid=2420 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForAlertByThreadId + 0xa
		sp=0x31b76ff9e8 bp=0x31b76ffa40 
	[1] C:\Windows\System32\ntdll.dll!RtlSleepConditionVariableSRW + 0xec
	[2] C:\Windows\System32\KERNELBASE.dll!ReadConsoleOutputW + 0x18
	[3] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!__crtSleepConditionVariableSRW(_RTL_CONDITION_VARIABLE *,_RTL_SRWLOCK *,unsigned long,unsigned long) [f:\dd\vctools\crt\crtw32\misc\winapisupp.cpp : 657 + 0x6]
	[4] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!Concurrency::details::stl_condition_variable_win7::wait_for(Concurrency::details::stl_critical_section_interface *,unsigned int) [f:\dd\vctools\crt\crtw32\stdcpp\thr\primitives.h : 216 + 0x10]
	[5] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!do_wait(_Cnd_internal_imp_t *,_Mtx_internal_imp_t *,xtime const *) [f:\dd\vctools\crt\crtw32\stdcpp\thr\cond.c : 82 + 0x26]
	[6] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_f574185c45dda01958beedcd6f2ea127> >,std::default_delete<std::tuple<<lambda_f574185c45dda01958beedcd6f2ea127> > > > >::_Go() [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\thr\xthread : 230 + 0xf8]
	[7] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!std::_Pad::_Call_func(void *) [c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\thr\xthread : 208 + 0x5]
	[8] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!thread_start<unsigned int (*)(void *)>(void * const) [d:\rs1\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 115 + 0xd]
	[9] C:\Windows\System32\kernel32.dll + 0x13d2
	[10] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x34
	thread-3 tid=8456 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForSingleObject + 0xa
	[1] C:\Windows\System32\KERNELBASE.dll + 0x1118
	[2] C:\Windows\System32\nvoglv64.dll + 0xc5bffa
	[3] C:\Windows\System32\nvoglv64.dll + 0xa1456e
	[4] C:\Windows\System32\nvoglv64.dll + 0xa14220
	[5] C:\Windows\System32\nvoglv64.dll + 0xc5e14b
	[6] C:\Windows\System32\nvoglv64.dll + 0xc5e130
	[7] C:\Windows\System32\nvoglv64.dll + 0xc5e130
	[8] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x34
	thread-4 tid=8760 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForMultipleObjects + 0xa
	[1] C:\Windows\System32\KERNELBASE.dll + 0x13ed
	[2] C:\Windows\System32\kernel32.dll + 0x106f
	[3] C:\Windows\System32\nvoglv64.dll + 0xc8e9a5
	[4] C:\Windows\System32\nvoglv64.dll + 0xc8e489
	[5] C:\Windows\System32\nvoglv64.dll + 0x1042a1c
	[6] C:\Windows\System32\nvoglv64.dll + 0x10429cc
	[7] C:\Windows\System32\nvoglv64.dll + 0x10429cc
	[8] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x34
	thread-5 tid=7260 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForMultipleObjects + 0xa
	[1] C:\Windows\System32\KERNELBASE.dll + 0x13ed
	[2] C:\Windows\System32\kernel32.dll + 0x106f
	[3] C:\Windows\System32\nvoglv64.dll + 0xca80d6
	[4] C:\Windows\System32\nvoglv64.dll + 0xca8080
	[5] C:\Windows\System32\nvoglv64.dll + 0xca8080
	[6] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x34
	thread-6 tid=7988 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForMultipleObjects + 0xa
	[1] C:\Windows\System32\KERNELBASE.dll + 0x13ed
	[2] C:\Windows\System32\user32.dll + 0x30f0
	[3] C:\Windows\System32\user32.dll + 0x31c4
	[4] C:\Windows\System32\nvoglv64.dll + 0xc56bad
	[5] 0x73520000
	[6] C:\Windows\System32\nvoglv64.dll + 0xc56a80
	[7] C:\Windows\System32\nvoglv64.dll + 0xc56a80
	[8] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x34
	thread-7 tid=8356 
	[0] C:\Windows\System32\ntdll.dll!ZwWaitForSingleObject + 0xa
	[1] C:\Windows\System32\KERNELBASE.dll + 0x1118
	[2] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!WASAPI_WaitDevice(SDL_AudioDevice *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\audio\wasapi\sdl_wasapi.c : 331 + 0xe]
	[3] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!SDL_RunAudio(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\audio\sdl_audio.c : 711 + 0x9]
	[4] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!SDL_RunThread(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\thread\sdl_thread.c : 283 + 0x5]
	[5] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!RunThreadViaBeginThreadEx(void *) [c:\projects\dependencies\vcpkg\buildtrees\sdl2\src\ease-2.0.8-42957b8d01\src\thread\windows\sdl_systhread.c : 105 + 0x14]
	[6] C:\Users\joe\Documents\OpenRCT2\bin\openrct2.dll!thread_start<unsigned int (*)(void *)>(void * const) [d:\rs1\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 115 + 0xd]
	[7] C:\Windows\System32\kernel32.dll + 0x13d2
	[8] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x34
	thread-8 tid=9056 
	[0] C:\Windows\System32\ntdll.dll!NtRemoveIoCompletion + 0xa
		sp=0x31be37fe88 bp=0 
	[1] C:\Windows\System32\mswsock.dll!WSPGetSockOpt + 0x1b9
	[2] C:\Windows\System32\kernel32.dll + 0x13d2
	[3] C:\Windows\System32\ntdll.dll!RtlUserThreadStart + 0x34
```

**Comment by janisozaur** [comment] 2019-02-02 22:31
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8462

**Closed by janisozaur** 2019-02-02 22:31 UTC
Labels: backtrace.io, crash
