### ISSUE TITLE
Check if RCT2 is installed

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#504] opened 2014-10-04 22:08 UTC
Many people have compiled and/or run OpenRCT2 without specifying the RCT2 install directory or without installing RCT2. They report it not finding files such as g1.dat or config.dat. More checks and information should be displayed in this situation to notify users that they need to have RCT2 installed or copied somewhere before running OpenRCT2.

**Comment by ThomasdenH** [comment] 2015-06-25 18:04
I think the game should check for the data files, not whether the registry is set. This is because the files may have come from a different source than the installation.

**Comment by RollingStar** [comment] 2015-06-25 18:15
@ThomasdenH, how, if not the registry, do you propose that Open 2 find the needed files? Does it search the entire computer?

I propose an automated registry check, and an additional option to specify the folder if the registry folder doesn't have the right files.

**Comment by ThomasdenH** [comment] 2015-06-25 18:18
You're right. That's perfect.

**Comment by janisozaur** [comment] 2016-01-23 18:05
If this is only about registry (which probably it is, given we now search some some expected paths), it looks like a duplicate of #765

**Comment by pizza2004** [comment] 2016-01-24 04:03
Wouldn't that make #765 a duplicate of this, since this is older?

**Comment by PFCKrutonium** [comment] 2016-01-24 04:39
Relevant Code for Finding it much better: https://github.com/PFCKrutonium/OpenRCT2Launcher/blob/develop/Launcher/LauncherWFP/Management/RctLocator.cs

**Closed** 2018-03-06 16:28 UTC
Labels: enhancement, platform
