### ISSUE TITLE
Land/Water tool selection dissapearence ?.

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#1927] opened 2015-09-12 15:50 UTC
Sometimes in the scenario editor the land and water selection vanishes and both water and land tools stops working, switching or reopen them does not solve the issue.

However it seems when there is another action taken the issue is reverted, i.e. saving the landscape

**Comment by duncanspumpkin** [comment] 2015-10-16 11:51
Duplicate of #1619.

**Closed by duncanspumpkin** 2015-10-16 11:51 UTC
Labels: duplicate
