### ISSUE TITLE
Small scenery Object Titles List blanking out at, and after: "RIDE-Chute drop-1 of 2"

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#5485] opened 2017-05-16 18:22 UTC
windows vista 32-bit
0.0.8
e725672

when selecting "object selection" in the gears menu, then pressing the "advanced" tab, next to the "filter" tab, then going into "small scenery" group (which seems to be the longest list of object files to choose from), the names of the objects are disappearing at or near object: RIDE-Chute drop-1 of 2. All objects alphabetically after "RIDE-Chute drop-1 of 2"  are unnamed in the sense that i can't see their black letter name at the left. The black lettered listing to the left that describes the object file is becoming blank after "RIDE-Chute drop-1 of 2" So that's about from "R-Z". I can however drag the mouse over the "invisible" object-name and then it's picture will appear in the box to the right, i just can't see it's name to the left.

note - i may be without internet for months or more and therefore unable to respond to any questions.
I am also aware that this may only be happening to me, but it does happen every time i play.

it doesn't seem to happen in vanilla i do think i tested it in vanilla and it wasn't a problem
- [did not try ] Multiplayer?

**Steps to reproduce:**
1.  as described above
2. 

**Dump file**
<!-no dump file->

**Screenshots / Video:**
<!--no screen shots->

**Save game:**
<!no save game->

**Comment by Gymnasiast** [comment] 2017-05-16 19:35
It would help a lot of you could post a screenshot.

**Comment by Gymnasiast** [comment] 2017-05-17 05:51
Looking at your description it looks like you have the problem reported in https://github.com/OpenRCT2/OpenRCT2/issues/592.

**Comment by Gymnasiast** [comment] 2017-05-17 15:47
I'm 99% sure this is a duplicate of #592.
You can follow the status of this bug there.

**Closed by Gymnasiast** 2017-05-17 15:47 UTC
Labels: duplicate
