### ISSUE TITLE
Issue with too many guests inside queue line

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#5580] opened 2017-06-10 15:01 UTC
OS: Windows 7
Version: 0.0.8
Commit/Build: 5c5389a

Guests seem to ignore that there is already a queue line and go through other peeps to form a ''new'' queue. In the screenshot below for example I have 58 guests in 7 tiles.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

Steps to reproduce:
I do not have a reliable way to reproduce the issue but I think it only happens when to entrance to the queue line is next to the ride exit like in the screenshot below.

Screenshots / Video:
![lost city founder 2017-06-09 22-21-13](https://user-images.githubusercontent.com/28242696/27003647-ba926a26-4dc8-11e7-9bb1-63cb0630f945.png)

Save game:
[Lost City Founder.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1065875/Lost.City.Founder.sv6.txt)

**Comment by ipatix** [comment] 2017-06-11 12:40
I've ran into this as well. No idea what's causing it though.

**Comment by deurklink** [comment] 2017-12-07 17:34
I was able to trigger this behaviour by making the queue path shorter, by replacing queue path tiles with normal path tiles. If i opened the same park in vanilla RCT2, instead of queuing, guests will simply walk to the ride entrance and then walk back.

**Comment by sjoerddebruin** [comment] 2023-02-25 08:09
Might be fixed now with #19068.

**Comment by Wirlie** [comment] 2023-02-25 09:36
I think that #19068 only fixes this in a partially way, because it only fixes the case where guests can accidentally skip the queue if the entrance to the queue line is placed next to a ride exit, but it doesn't fix the fact that guests can go through other peeps to form a "new" queue. 

An easy way to reproduce this is by editing a queue line with peeps in this way:
![image](https://user-images.githubusercontent.com/7508197/213029155-4b10b4d9-0828-4773-a76d-cc889757efb3.gif)

Unfortunately, I do not have much time right now to take a look at this 😢 but I will try to take a look later if nobody has fixed this remaining issue.

**Closed** 2023-02-25 09:36 UTC
Labels: investigate

**Comment by Broxzier** [comment] 2023-02-25 09:47
The mentioned PR also prevents a new queue from forming, the queue in the saved game will remain broken until emptied. I don't think this specific issue has to remain opened.

To fix the problem from the gif above, I think that the best solution is to simply remove all guests from the queue that are on that tile, and all behind them.
