### ISSUE TITLE
Old libraries

### ISSUE THREAD

**Issue by ThePreviousOne** [OpenRCT2/OpenRCT2#7493] opened 2018-05-07 00:28 UTC
#**OS:** Debian Buster \ Arch Linux
**Commit/Build:** 5d102fd40b95866f1af1910f8025d64a72763536

libpng 1.6.34 and libssl 1.0.2 installed

./openrct2: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

**Steps to reproduce:**
1.  I tryied symlinking it and found out about libcrypto.so.1.0.0
2. symlinked that and got this error:
./openrct2: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: no version information available (required by /home/useri/Libre-Games/OpenRCT2/libopenrct2.so)
./openrct2: /usr/lib/x86_64-linux-gnu/libpng12.so.0: version `PNG12_0' not found (required by /home/user/Libre-Games/OpenRCT2/libopenrct2.so)

**Comment by AaronVanGeffen** [comment] 2018-05-07 07:48
libpng 1.6 should work fine on Arch… Is libpng12 installed beside it, then?

**Comment by janisozaur** [comment] 2018-05-07 07:54
This is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3092, https://github.com/OpenRCT2/OpenRCT2/issues/6697 and https://github.com/OpenRCT2/OpenRCT2/issues/7186

**Closed by janisozaur** 2018-05-07 07:54 UTC
