### ISSUE TITLE
Game stops responding or crashes when starting a new game

### ISSUE THREAD

**Issue by sr1gh** [OpenRCT2/OpenRCT2#14115] opened 2021-02-18 19:15 UTC
OS: Windows 7
Version: 0.3.2
Commit/Build: 0a8cfe7 and later

The game stops responding when starting a new scenario but not when loading a saved game. The UI gets stuck and buttons can't be pressed, but there are sound effects and the FPS counter works, but it draws over the frozen UI. In software rendering mode, the UI freezes with the map visible, but with ride vehicles and people missing. In OpenGL mode, it freezes showing the main menu. Sometimes the game crashes shortly after the game stops responding. Windows 10 seems to be fine.

Steps to reproduce:
1. Start a new scenario from the main menu on Windows 7
2. 

Dump files:
[31a52506-85ec-4ab7-9244-9e8304b0ca64(14cca95_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/6005154/31a52506-85ec-4ab7-9244-9e8304b0ca64.14cca95_x86-64.dmp.gz)
[c3f8ec20-67f5-4bf1-bb17-3498eb8a1174(34b1506_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/6005155/c3f8ec20-67f5-4bf1-bb17-3498eb8a1174.34b1506_x86-64.dmp.gz)

Screenshots:
![Untitled3](https://user-images.githubusercontent.com/45770511/108408239-cc630d80-71f2-11eb-89e6-ed8cc8beec46.png)

**Comment by Fred-1044276** [comment] 2021-02-18 19:18
This happens to me too. I'm on Windows 10, and I have had this issue both with plugins and without plugins.

**Comment by Gymnasiast** [comment] 2021-02-18 19:56
Looks like a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/14111.

**Closed by Gymnasiast** 2021-02-18 19:56 UTC
