### ISSUE TITLE
Multi-dimension Icon Missing

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#8531] opened 2018-12-24 02:15 UTC
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 8d9fcb7

Sometimes, the icon/preview for the Multi-dimension roller coaster does not appear.  I was playing a custom scenario for a while, built a roller coaster.  That's when I first noticed.  

Then, I opened a new scenario of Magic Mountain, and it is blank.  However, I closed and reopened the game and launched Magic Mountain again, and it is back.  It is also back in my saved game.  

This icon has disappeared more than once.  It seems to happen after playing for a while.  

Reproducible in RCT2 (vanilla)?  No
Specific to multiplayer? No

**Steps to reproduce:**
I don't know.  I will let you know if I find a pattern.  

Please let me know if you have any questions. 

**Screenshots / Video:**

![multidimension icon missing](https://user-images.githubusercontent.com/32249806/50389254-1b39b900-06f6-11e9-99e0-39f23a65f676.png)

**Comment by IntelOrca** [comment] 2018-12-24 09:11
Duplicate of #6073

**Closed** 2018-12-24 09:11 UTC
Labels: duplicate
