### ISSUE TITLE
Feature idea - Changeable Cluster size

### ISSUE THREAD

**Issue by L3mmy** [OpenRCT2/OpenRCT2#7824] opened 2018-07-25 09:41 UTC
As you may know, there's an option when placing small scenery (Trees & Others) that can place them into clusters, however, the area of effect may be too big for certain uses, so that's why i think a scroll that can change the area of effect could be nice, *ideally, to 5 to 20 would be good*.
**Thanks ! ^^**

**Comment by Gymnasiast** [comment] 2018-07-25 09:42
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/5828.

**Closed by Gymnasiast** 2018-07-25 09:42 UTC
