### ISSUE TITLE
Mechanic Glitch-Walking Across Water

### ISSUE THREAD

**Issue by Oricuss** [OpenRCT2/OpenRCT2#11262] opened 2020-04-10 20:20 UTC
Windows 10
v0.2.5 
(4f6e77e)

One of my mechanics is walking across the water in my game where there is no path and I didn't make anything invisible there. I didn't see what caused him to do this, I only noticed it when I saw him in the middle of my lake. He is twitching back and a forth and traveling diagonal. He cannot be picked up but can be fired. I also didn't notice him until he was halfway across the map from the ride he was fixing so I don't know what caused it. But his status bar says he is mid fixing the ride. The ride has invisible exits using the No Entrance option in the drop down menu. The Entrance and Exit face the normal directions. But otherwise it is the pre-made Flying Dutchman Gold Mine Wild Mouse. I watched him until he hit the edge of the map and he fell off the side and reset at that point.

- I don't know if it is reproducible in Vanilla as I don't know what caused it.
- Single Player Game
- The game didn't crash so I don't have a dump file.

[Infernal Views Save Game](https://github.com/OpenRCT2/OpenRCT2/files/4463271/Infernal.Views.Glitch.txt)

![Capture](https://user-images.githubusercontent.com/54409340/79020536-11d09c00-7b47-11ea-8e52-6ba9f38d8fab.PNG)

**Comment by AaronVanGeffen** [comment] 2020-04-10 21:55
Yeah, this is an interesting one… Duplicate of #8145 (and, by extension, #11210), though.

**Closed** 2020-04-10 21:55 UTC
Labels: duplicate
