### ISSUE TITLE
Feature: Track Save height check

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3270] opened 2016-04-09 15:05 UTC
in a nutshell, since a lot of people (as far as I can remember) save track designs that normally cannot be placed unless some landscaping is done first because of "Too High for Supports", I feel as if there should be a way to know that if you saved a track design that cannot be placed on perfectly flat land (or especially in the Roller Coaster designer), like the design's name being outlined in a more crisp red on the track design list once the player's mouse rolls over it and the game checks to see if the highest track element is over a certain limit.

**Comment by Gymnasiast** [comment] 2016-04-10 11:06
Duplicate of #444. (Which you even opened yourself.)

**Closed by Gymnasiast** 2016-04-10 11:06 UTC
