### ISSUE TITLE
BACKTRACE 67d0b3

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8429] opened 2018-12-13 04:46 UTC
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/67d0b3f69ab050a9c2eaf4f408389b82ade1d6a3455b0aca52d321e2eab5e305?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Thu Dec 13 2018 04:46:07)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\RickyPinguX\\Documents\\OpenRCT2\\811262c4-d646-466f-a74f-5e4f7b4d7816.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\RickyPinguX\\Documents\\OpenRCT2\\811262c4-d646-466f-a74f-5e4f7b4d7816.sv6.gz: <em>1</em><br><strong>commit:</strong> cf44ea7: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>unhandled-exception</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Object::GetLegacyData -> track_design_mirror_scenery -> window_track_place_mouseup -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment] 2019-02-02 19:48
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/8535

**Closed by janisozaur** 2019-02-02 19:48 UTC
Labels: backtrace.io, crash
